#!/usr/bin/env python
"""Script 2: ai-customer-service, ai-finance, ai-health, ai-education, ai-manufacturing."""
import json, subprocess, time

TOKEN = "sbp_9d3bb1ca2c1b81ded0e6ebf813b66dd81e29896f"
URL = "https://api.supabase.com/v1/projects/amhfxaqolholacanqyas/database/query"
ok_count = 0
fail_count = 0

def run_sql(sql, label):
    global ok_count, fail_count
    payload = json.dumps({"query": sql})
    r = subprocess.run(["curl","-s","-X","POST",URL,"-H",f"Authorization: Bearer {TOKEN}","-H","Content-Type: application/json","-d",payload], capture_output=True, text=True, timeout=120)
    out = r.stdout.strip()
    if '"error"' in out or '"message"' in out:
        print(f"FAIL: {label} -> {out[:400]}")
        fail_count += 1
        return False
    print(f"OK: {label}")
    ok_count += 1
    return True

def O(o, a, d):
    return json.dumps([{"text":o[0],"score":100,"feedbackText":o[1]},{"text":a[0],"score":0,"feedbackText":a[1]},{"text":d[0],"score":-100,"feedbackText":d[1]}])

def E(s): return s.replace("'","''")

def build_insert(rows):
    vals = []
    for loc,cat,sc,tip,op,diff in rows:
        vals.append(f"('{E(loc)}','{E(cat)}','{E(sc)}','{E(tip)}','{E(op)}',{diff},'claude-opus-4-6',true)")
    return "INSERT INTO questions (locale,category,scenario_text,mindset_tip,options,difficulty,generated_by,is_active) VALUES\n" + ",\n".join(vals) + ";"

Q = []

# ===== ai-customer-service DE =====
Q += [
("de","ai-customer-service","Ihr Unternehmen moechte einen KI-Chatbot fuer den Kundenservice einsetzen. Kunden sollen einfache Anfragen selbst loesen koennen.","KI-Chatbots entlasten den Support, muessen aber nahtlos an Menschen eskalieren koennen.",O(("Implementieren Sie den Chatbot fuer einfache Anfragen mit klarer Eskalation an menschliche Mitarbeiter.","Perfekt! KI fuer Routine plus menschliche Eskalation bietet die beste Kundenerfahrung insgesamt."),("Verzichten Sie auf einen Chatbot und behalten ausschliesslich menschlichen Support fuer alle Anfragen.","Moeglich, aber bei hohem Anfragevolumen wird der Support ueberlastet und Kunden warten laenger."),("Ersetzen Sie den gesamten menschlichen Support durch den KI-Chatbot fuer maximale Kosteneinsparung.","Gefaehrlich! Komplexe Probleme erfordern menschliches Einfuehlungsvermoegen und kreative Loesungsfindung.")),2),
("de","ai-customer-service","Ein Kunde droht in einem Support-Chat mit rechtlichen Schritten. Der KI-Chatbot erkennt die Eskalation nicht und antwortet mit Standard.","KI muss Eskalationsmuster erkennen koennen — ohne menschliche Uebernahme wird es schnell kritisch.",O(("Konfigurieren Sie Eskalationsregeln fuer Schluesselwoerter wie Anwalt und Klage mit sofortiger Weiterleitung.","Richtig! Automatische Eskalation bei kritischen Schluesselwoertern schuetzt vor juristischen Risiken."),("Vertrauen Sie darauf, dass der Chatbot durch Machine Learning diese Situationen irgendwann selbst erkennt.","Riskant! Ohne explizite Regeln kann der Chatbot kritische Situationen monatelang falsch behandeln."),("Deaktivieren Sie den Chatbot komplett, weil er mit schwierigen Faellen nicht umgehen kann und unbrauchbar ist.","Uebertrieben! Der Chatbot funktioniert gut fuer Routine — nur die Eskalationslogik muss angepasst werden.")),3),
("de","ai-customer-service","Ihr KI-Chatbot gibt einem Kunden eine falsche Produktempfehlung, die zu einer Rueckgabe und Beschwerde fuehrt. Wie reagieren Sie?","KI-Fehler passieren — schnelle Korrektur und Transparenz staerken das Kundenvertrauen langfristig.",O(("Entschuldigen Sie sich beim Kunden, korrigieren die Empfehlungslogik und ueberpruefen aehnliche Faelle.","Perfekt! Schnelle Entschuldigung plus Fehlerkorrektur im System baut Vertrauen nachhaltig auf."),("Ignorieren Sie den Einzelfall, weil KI-Systeme eine gewisse Fehlerquote einfach immer haben werden.","Unprofessionell! Jeder Beschwerdefall ist eine Chance, das System und den Service zu verbessern."),("Deaktivieren Sie alle KI-Produktempfehlungen dauerhaft, weil sie offensichtlich nicht zuverlaessig genug sind.","Uebertrieben! Ein einzelner Fehler rechtfertigt nicht die Abschaltung eines sonst nuetzlichen Systems.")),2),
("de","ai-customer-service","Kunden beschweren sich, dass Ihr KI-Chatbot immer die gleichen Standardantworten gibt und nicht auf individuelle Probleme eingeht.","Kundenzufriedenheit braucht Personalisierung — KI muss kontextbezogen antworten, nicht generisch.",O(("Verbessern Sie den Chatbot mit kontextbezogenen Antworten und ermoeglichen jederzeit menschliche Hilfe.","Richtig! Kontextbezogene Antworten plus menschliche Option erhoehen die Kundenzufriedenheit deutlich."),("Ersetzen Sie den Chatbot komplett durch ein groesseres menschliches Support-Team fuer alle Anfragen.","Teuer und unnoetig — mit der richtigen Konfiguration kann der Chatbot viel individueller antworten."),("Fuegen Sie noch mehr Standardantworten hinzu und hoffen, dass eine davon irgendwann die Frage trifft.","Kontraproduktiv! Mehr generische Antworten verschlimmern das Problem statt es wirklich zu loesen.")),2),
("de","ai-customer-service","Ihr Support-Team ist ueberfordert mit Tickets. KI koennte Tickets automatisch kategorisieren und priorisieren. Wie fuehren Sie das ein?","KI-Ticket-Kategorisierung spart enorm Zeit — aber die Kriterien muessen klar definiert sein.",O(("Definieren Sie klare Kategorien und Prioritaetsregeln, trainieren die KI damit und ueberwachen Genauigkeit.","Perfekt! Klare Regeln plus KI-Training plus Monitoring ergibt ein effizientes Ticketsystem fuer alle."),("Lassen Sie das Support-Team weiterhin manuell alle Tickets kategorisieren und priorisieren wie bisher.","Ineffizient! Bei wachsendem Volumen wird die manuelle Sortierung zum Engpass und verzoegert Antworten."),("Aktivieren Sie die KI-Kategorisierung sofort fuer alle Tickets ohne vorherige Regeldefinition oder Tests.","Riskant! Ohne klare Regeln kategorisiert die KI falsch und dringende Tickets gehen unter.")),2),
("de","ai-customer-service","Ein Kunde fragt den KI-Chatbot nach einer Rueckerstattung. Der Chatbot hat keine Befugnis, Rueckerstattungen zu genehmigen. Was soll er tun?","KI muss ihre Grenzen kennen und transparent kommunizieren, wann ein Mensch uebernehmen muss.",O(("Der Chatbot erklaert transparent seine Grenzen und leitet den Kunden direkt an einen Mitarbeiter weiter.","Richtig! Transparenz ueber KI-Grenzen plus schnelle Weiterleitung schafft Vertrauen beim Kunden."),("Der Chatbot versucht, den Kunden mit Rabattcodes und Alternativen von der Rueckerstattung abzubringen.","Problematisch! Kunden durchschauen Ablenkungstaktiken und werden noch weiter unzufriedener damit."),("Der Chatbot genehmigt die Rueckerstattung selbststaendig, um den Kunden schnell zufriedenzustellen.","Gefaehrlich! Unbefugte Rueckerstattungen durch KI verursachen finanzielle und rechtliche Probleme.")),1),
("de","ai-customer-service","Sie analysieren Kundenfeedback mit KI und stellen fest, dass viele Kunden sich ueber lange Wartezeiten beschweren. Was tun Sie?","KI-Analyse von Kundenfeedback ist wertvoll — aber nur wenn die Erkenntnisse zu Massnahmen fuehren.",O(("Praesentieren Sie die Analyse der Fuehrung mit konkreten Verbesserungsvorschlaegen und messbaren Zielen.","Perfekt! Datenbasierte Analyse plus konkrete Massnahmen ueberzeugen das Management zur Verbesserung."),("Speichern Sie die Analyse ab, weil Wartezeiten ein bekanntes Problem sind, das niemand loesen kann.","Resignation! KI-Analysen sind nur wertvoll, wenn sie zu konkreten Verbesserungsmassnahmen fuehren."),("Aendern Sie die Chatbot-Antworten so, dass Wartezeiten beschoenigt statt tatsaechlich reduziert werden.","Taeuschend! Kunden merken, wenn Wartezeiten schoengerechnet werden, und verlieren jedes Vertrauen.")),2),
("de","ai-customer-service","Ihr KI-System erkennt, dass ein Kunde gerade emotional aufgeloest ist. Soll die KI empathisch antworten oder sofort weiterleiten?","Emotionale Situationen brauchen echte Menschen — KI kann Empathie simulieren, aber nicht fuehlen.",O(("Die KI antwortet empathisch und leitet gleichzeitig proaktiv an einen menschlichen Mitarbeiter weiter.","Richtig! Empathische Ueberbrueckung plus menschliche Uebernahme ist die beste Strategie dafuer."),("Die KI leitet sofort ohne jede Antwort an einen Menschen weiter, auch wenn dieser nicht verfuegbar ist.","Problematisch! Wortlose Weiterleitung kann Kunden verunsichern — eine empathische Nachricht hilft."),("Die KI fuehrt das gesamte Gespraech alleine weiter und versucht den Kunden selbststaendig zu beruhigen.","Riskant! Simulierte Empathie kann bei stark emotionalen Situationen nach hinten losgehen.")),3),
("de","ai-customer-service","Ihre Konkurrenz hat einen fortschrittlichen KI-Kundenservice. Ihr Chef fordert, Sie sollen das gleiche System ueber Nacht einsetzen.","KI-Kundenservice braucht sorgfaeltige Einfuehrung — kopieren ohne Strategie fuehrt zu schlechter Qualitaet.",O(("Erklaeren Sie die Notwendigkeit einer strukturierten Einfuehrung mit Pilotphase und Qualitaetssicherung.","Perfekt! Professionelle KI-Einfuehrung dauert, aber liefert nachhaltig bessere Ergebnisse als Hektik."),("Kaufen Sie sofort das gleiche System wie die Konkurrenz und schalten es live fuer alle Kunden heute.","Gefaehrlich! Ungetestete KI im Kundenservice verursacht Frustration und schaedigt die Marke stark."),("Sagen Sie Ihrem Chef, dass KI-Kundenservice nur ein Hype ist und manueller Support voellig ausreicht.","Kurzsichtig! KI-Kundenservice ist kein Hype — wer nicht modernisiert, verliert Kunden an Konkurrenz.")),2),
("de","ai-customer-service","Ein mehrsprachiger Kunde schreibt auf Spanisch an Ihren deutschen KI-Chatbot. Der Chatbot antwortet auf Deutsch. Was ist die Loesung?","Mehrsprachiger KI-Support zeigt Wertschaetzung und erweitert den Kundenkreis deutlich.",O(("Aktivieren Sie automatische Spracherkennung im Chatbot und Antworten in der Sprache des Kunden.","Perfekt! Automatische Spracherkennung zeigt Wertschaetzung und verbessert die Kundenerfahrung."),("Bitten Sie den Kunden, seine Anfrage auf Deutsch zu wiederholen, weil der Support nur Deutsch anbietet.","Akzeptabel, aber kundenunfreundlich — moderne KI-Chatbots koennen problemlos mehrsprachig arbeiten."),("Ignorieren Sie die Nachricht komplett, weil der Chatbot fuer fremdsprachige Anfragen nicht zustaendig ist.","Unprofessionell! Jede Kundenanfrage verdient eine Antwort — Sprachbarrieren sind kein Ausschlussgrund.")),1),
]

# ===== ai-customer-service EN =====
Q += [
("en","ai-customer-service","Your company wants to deploy an AI chatbot for customer service. Customers should resolve simple inquiries on their own. How do you implement?","AI chatbots relieve support teams but must seamlessly escalate to human agents when needed.",O(("Implement the chatbot for simple inquiries with clear escalation paths to human agents for complex issues.","Perfect! AI for routine tasks plus human escalation provides the best overall customer experience."),("Skip the chatbot entirely and maintain exclusively human support for all customer inquiries regardless.","Possible, but with high inquiry volumes the support team becomes overwhelmed and wait times increase."),("Replace the entire human support team with the AI chatbot to maximize immediate cost savings.","Dangerous! Complex problems require human empathy, creativity, and nuanced problem-solving skills.")),2),
("en","ai-customer-service","A customer threatens legal action in a support chat. The AI chatbot fails to recognize the escalation and responds with standard answers.","AI must recognize escalation patterns — without human takeover, situations become legally critical fast.",O(("Configure escalation rules for keywords like lawyer and lawsuit with immediate routing to human agents.","Correct! Automatic escalation on critical keywords protects against serious legal risks proactively."),("Trust that the chatbot will eventually learn to recognize these situations through machine learning alone.","Risky! Without explicit rules, the chatbot may mishandle critical situations for months continuously."),("Deactivate the chatbot for all customer communication because it cannot handle any difficult cases.","Excessive! The chatbot works well for routine inquiries — only the escalation logic needs adjustment.")),3),
("en","ai-customer-service","Your AI chatbot gives a customer an incorrect product recommendation, leading to a return and formal complaint. How do you handle this?","AI errors happen — fast correction and transparency strengthen customer trust in the long term.",O(("Apologize to the customer, correct the recommendation logic, and review similar cases systematically.","Perfect! Quick apology plus system correction builds lasting customer trust and improves service."),("Ignore the individual case because AI systems will always have some inherent error rate regardless.","Unprofessional! Every customer complaint is an opportunity to improve both the system and service."),("Permanently deactivate all AI product recommendations because they are obviously unreliable and useless.","Excessive! A single error does not justify shutting down an otherwise useful and helpful system.")),2),
("en","ai-customer-service","Customers complain your AI chatbot always gives the same standard responses without addressing individual problems. What do you do?","Customer satisfaction requires personalization — AI must respond contextually, not with generic answers.",O(("Improve the chatbot with context-aware responses and always enable the option for live human assistance.","Correct! Context-aware responses plus human availability significantly increases customer satisfaction."),("Replace the chatbot completely with a larger human support team to handle every single customer inquiry.","Expensive and unnecessary — with proper configuration, the chatbot can respond much more individually."),("Add even more standard response templates hoping that eventually one will match the customer question.","Counterproductive! More generic responses make the problem worse instead of solving it effectively.")),2),
("en","ai-customer-service","Your support team is overwhelmed with tickets. AI could automatically categorize and prioritize them. How do you introduce this system?","AI ticket categorization saves enormous time — but the criteria must be clearly defined beforehand.",O(("Define clear categories and priority rules, train the AI accordingly, and monitor accuracy continuously.","Perfect! Clear rules plus AI training plus monitoring creates an efficient ticket system for everyone."),("Let the support team continue manually categorizing and prioritizing all tickets exactly as before.","Inefficient! With growing volume, manual sorting becomes a bottleneck delaying customer responses."),("Activate AI categorization immediately for all tickets without prior rule definition or testing.","Risky! Without clear rules, AI miscategorizes tickets and urgent issues get buried and forgotten.")),2),
("en","ai-customer-service","A customer asks the AI chatbot for a refund. The chatbot has no authority to approve refunds. What should it do in this situation?","AI must know its limitations and transparently communicate when a human needs to take over immediately.",O(("The chatbot transparently explains its limitations and immediately routes the customer to a human agent.","Correct! Transparency about AI limitations plus quick routing builds lasting customer trust."),("The chatbot tries to distract the customer with discount codes and alternatives to avoid the refund.","Problematic! Customers see through deflection tactics and become even more dissatisfied and frustrated."),("The chatbot approves the refund independently to quickly satisfy the customer without human involvement.","Dangerous! Unauthorized refunds by AI cause significant financial and serious legal problems.")),1),
("en","ai-customer-service","You analyze customer feedback with AI and discover many customers complain about long wait times. How do you use this insight?","AI analysis of customer feedback is valuable — but only when insights lead to concrete measurable actions.",O(("Present the analysis to leadership with concrete improvement proposals and measurable target metrics.","Perfect! Data-driven analysis plus concrete action plans convinces management to make improvements."),("Archive the analysis because long wait times are a known problem that nobody can realistically solve.","Resignation! AI analyses are only valuable when they drive concrete actionable improvement measures."),("Modify chatbot responses to downplay wait times rather than actually working to reduce them.","Deceptive! Customers notice when wait times are misrepresented and completely lose all trust.")),2),
("en","ai-customer-service","Your AI system detects a customer is emotionally distressed. Should the AI respond empathetically or immediately transfer to a human?","Emotional situations need real humans — AI can simulate empathy but cannot genuinely feel it.",O(("The AI responds empathetically while simultaneously proactively routing to a human agent for support.","Correct! Empathetic bridging plus human handover is the best strategy for emotional situations."),("The AI transfers immediately without any response, even if a human agent is not currently available.","Problematic! Silent transfers unsettle customers — an empathetic bridging message always helps."),("The AI continues the entire conversation alone and attempts to calm the customer down independently.","Risky! Simulated empathy can backfire significantly in highly emotional customer situations.")),3),
("en","ai-customer-service","Your competitor has advanced AI customer service. Your boss demands you deploy the same system overnight. How do you respond?","AI customer service needs careful implementation — copying without strategy leads to poor quality outcomes.",O(("Explain the necessity of a structured rollout with a pilot phase and thorough quality assurance.","Perfect! Professional AI implementation takes time but delivers sustainably better results than rushing."),("Buy the same system immediately and launch it live for all customers starting today without testing.","Dangerous! Untested AI in customer service causes frustration and damages your brand reputation."),("Tell your boss that AI customer service is just hype and your manual support is completely sufficient.","Shortsighted! AI customer service is not hype — companies that fail to modernize will lose customers.")),2),
("en","ai-customer-service","A multilingual customer writes to your English AI chatbot in Spanish. The chatbot responds only in English. What is the best solution?","Multilingual AI support shows appreciation and significantly expands your potential customer base.",O(("Enable automatic language detection so the chatbot responds in the customer preferred language always.","Perfect! Automatic language detection shows customer appreciation and improves the overall experience."),("Ask the customer to repeat their inquiry in English because support is only offered in that language.","Acceptable but unfriendly — modern AI chatbots can easily handle multilingual conversations today."),("Ignore the message completely because the chatbot is not responsible for non-English language inquiries.","Unprofessional! Every customer inquiry deserves a response — language barriers are never an excuse.")),1),
]

# ===== ai-finance DE =====
Q += [
("de","ai-finance","Ihr Buchhaltungsteam moechte KI-Software einsetzen, die Rechnungen automatisch erfasst und kategorisiert. Wie fuehren Sie das ein?","KI in der Buchhaltung spart enorm Zeit, erfordert aber regelmaessige menschliche Stichproben.",O(("Fuehren Sie das System schrittweise ein, pruefen Ergebnisse mit Stichproben und schulen das gesamte Team.","Perfekt! Schrittweise Einfuehrung mit Qualitaetskontrolle minimiert Fehler und schafft Vertrauen."),("Lassen Sie die KI ab sofort alle Rechnungen komplett autonom verarbeiten ohne menschliche Ueberpruefung.","Gefaehrlich! Fehlerhafte Buchungen koennen zu falschen Bilanzen und rechtlichen Konsequenzen fuehren."),("Lehnen Sie KI-Buchhaltung ab, weil Finanzdaten zu sensibel fuer automatisierte Verarbeitung sind.","Zu konservativ! Moderne KI-Buchhaltung ist sicher und effizient, braucht aber menschliche Aufsicht.")),2),
("de","ai-finance","Ihre KI-Software prognostiziert einen Umsatzeinbruch im naechsten Quartal basierend auf aktuellen Marktdaten. Wie reagieren Sie?","KI-Prognosen sind Fruehwarnsysteme — sie ersetzen keine menschliche Urteilskraft bei Entscheidungen.",O(("Nehmen Sie die Prognose ernst, analysieren die zugrundeliegenden Daten und entwickeln einen Notfallplan.","Richtig! KI-Prognosen als Fruehwarnsystem nutzen und mit menschlicher Analyse kombinieren ist klug."),("Ignorieren Sie die KI-Prognose, weil Algorithmen die Komplexitaet von Maerkten ohnehin nicht verstehen.","Riskant! KI erkennt Muster in Daten, die Menschen uebersehen — Ignorieren kann sehr teuer werden."),("Kuendigen Sie sofort Mitarbeiter und kuerzen Budgets basierend allein auf der KI-Vorhersage ohne Pruefung.","Gefaehrlich! Drastische Massnahmen nur auf Basis einer unvalidierten KI-Prognose sind unverantwortlich.")),2),
("de","ai-finance","Ein Wirtschaftspruefer fragt, wie Ihr Unternehmen KI in der Buchhaltung einsetzt und ob Ergebnisse auditierbar sind. Was antworten Sie?","KI in der Buchhaltung muss auditierbar und dokumentiert sein — Transparenz ist absolute Pflicht.",O(("Zeigen Sie die dokumentierten KI-Prozesse, Stichprobenprotokolle und menschliche Freigabeschritte vor.","Perfekt! Dokumentierte Prozesse mit menschlicher Aufsicht erfuellen Audit-Anforderungen zuverlaessig."),("Erklaeren Sie, dass KI-Systeme zu komplex fuer Audits sind und der Pruefer das akzeptieren muss.","Inakzeptabel! Jeder automatisierte Prozess in der Buchhaltung muss auditierbar und nachvollziehbar sein."),("Verschweigen Sie die KI-Nutzung und behaupten, alles werde weiterhin manuell von Mitarbeitern erledigt.","Gefaehrlich! Verschweigen von KI-Nutzung gegenueber Pruefern ist ein schwerwiegender Compliance-Verstoss.")),3),
("de","ai-finance","Ihr KI-System meldet eine ungewoehnliche Transaktion auf einem Firmenkonto. Es koennte Betrug oder ein technischer Fehler sein.","KI-Betrugserkennung ist ein wertvolles Fruehwarnsystem — aber immer menschlich verifizieren.",O(("Pruefen Sie die Transaktion sofort manuell, kontaktieren die Bank und dokumentieren den gesamten Vorfall.","Richtig! Schnelle menschliche Pruefung bei KI-Warnungen verhindert Schaeden und schuetzt das Unternehmen."),("Ignorieren Sie die KI-Warnung, weil Fehlalarme haeufig sind und die Transaktion wahrscheinlich korrekt ist.","Riskant! Auch wenn Fehlalarme vorkommen, kann ein ignorierter Betrugsfall enorme Schaeden verursachen."),("Sperren Sie sofort alle Konten und stoppen den gesamten Zahlungsverkehr bis Untersuchung abgeschlossen.","Uebertrieben! Eine verdaechtige Transaktion rechtfertigt keine vollstaendige Lahmlegung des Unternehmens.")),2),
("de","ai-finance","Ihr Chef moechte KI-basierte automatische Gehaltsabrechnungen einfuehren, um Personal in der HR-Abteilung einzusparen.","KI-Gehaltsabrechnung erfordert besondere Sorgfalt — Fehler betreffen direkt die Mitarbeitenden.",O(("Empfehlen Sie KI-Unterstuetzung bei gleichzeitiger menschlicher Kontrolle jeder einzelnen Abrechnung.","Richtig! KI beschleunigt die Abrechnung, aber menschliche Kontrolle verhindert kostspielige Fehler."),("Unterstuetzen Sie die vollautomatische Abrechnung ohne Kontrolle, um maximale Effizienz zu erreichen.","Gefaehrlich! Fehlerhafte Abrechnungen verursachen rechtliche Probleme und Mitarbeiterunzufriedenheit."),("Lehnen Sie jede KI-Nutzung bei Gehaeltern ab, weil Gehaltsabrechnung zu sensibel fuer Automatisierung ist.","Zu konservativ! KI kann Gehaltsabrechnung verbessern, muss aber unter menschlicher Aufsicht stehen.")),2),
("de","ai-finance","Sie muessen eine Finanzpraesentation fuer Investoren erstellen. KI-Tools bieten automatisch generierte Diagramme und Prognosen an.","KI-generierte Finanzdaten fuer Investoren muessen immer manuell verifiziert und freigegeben werden.",O(("Nutzen Sie KI-Diagramme als Entwurf, verifizieren alle Zahlen manuell und lassen alles pruefend freigeben.","Perfekt! KI als Arbeitshilfe plus gruendliche Pruefung schuetzt vor fehlerhaften Investorpraesentationen."),("Erstellen Sie alle Diagramme manuell ohne KI, weil Investoren KI-generierte Inhalte nicht vertrauenswuerdig finden.","Moeglich, aber KI kann die Erstellung erheblich beschleunigen, wenn Sie Ergebnisse sorgfaeltig pruefen."),("Uebernehmen Sie die KI-generierten Prognosen und Diagramme direkt ohne Pruefung in die Investorpraesentation.","Gefaehrlich! Falsche Finanzdaten fuer Investoren koennen zu Klagen und Vertrauensverlust fuehren.")),3),
("de","ai-finance","Ihre KI-Software schlaegt vor, Lieferantenrechnungen fruehzeitig zu bezahlen, um Skonto zu nutzen. Der Cashflow waere angespannt.","KI-Finanzoptimierung muss Gesamtliquiditaet beruecksichtigen, nicht nur einzelne Einsparungen.",O(("Pruefen Sie die Gesamtliquiditaet, berechnen den Netto-Vorteil und entscheiden dann differenziert pro Rechnung.","Richtig! Gesamtbetrachtung von Skonto-Vorteil gegen Cashflow-Risiko ist finanzielle Sorgfaltspflicht."),("Ignorieren Sie den KI-Vorschlag komplett, weil Skonto-Optimierung bei angespanntem Cashflow nie sinnvoll ist.","Voreilig! In einigen Faellen kann Skonto den Cashflow-Nachteil deutlich ueberwiegen."),("Folgen Sie dem KI-Vorschlag blind und zahlen alle Rechnungen sofort fruehzeitig fuer maximales Skonto.","Gefaehrlich! Blindes Skontoziehen bei knappem Cashflow kann die Liquiditaet des Unternehmens gefaehrden.")),3),
("de","ai-finance","Ein Kollege nutzt kostenlose KI-Tools im Internet, um Firmensteuerdaten zu analysieren. Er laedt sensible Finanzdaten hoch.","Sensible Finanzdaten gehoeren nie in kostenlose Online-KI-Tools — Datenschutz hat absolute Prioritaet.",O(("Weisen Sie den Kollegen sofort auf die Datenschutzrisiken hin und eskalieren an die IT-Abteilung.","Richtig! Sensible Finanzdaten in kostenlosen KI-Tools sind ein ernstes Datenschutzrisiko fuer die Firma."),("Lassen Sie den Kollegen weitermachen, weil kostenlose KI-Tools wahrscheinlich sicher genug sein werden.","Fahrlaaessig! Kostenlose Tools bieten oft keine Datenschutzgarantien fuer vertrauliche Unternehmensdaten."),("Kuendigen Sie dem Kollegen sofort wegen grober Verletzung der Datenschutzrichtlinien des Unternehmens.","Uebertrieben! Aufklaerung und Schulung sind der bessere erste Schritt als sofortige Kuendigung.")),2),
("de","ai-finance","Ihr Unternehmen erwaegt KI fuer die automatische Erstellung von Steuererklaerungen. Der Steuerberater ist skeptisch. Was empfehlen Sie?","KI kann Steuererklaerungen vorbereiten, aber die finale Pruefung durch Steuerexperten bleibt Pflicht.",O(("Nutzen Sie KI fuer die Vorbereitung und lassen den Steuerberater die finale Pruefung und Freigabe machen.","Perfekt! KI-Vorbereitung plus Experten-Pruefung kombiniert Effizienz mit Zuverlaessigkeit und Compliance."),("Ueberlassen Sie die Steuererklaerung vollstaendig der KI ohne Einbindung des skeptischen Steuerberaters.","Gefaehrlich! Fehler in Steuererklaerungen fuehren zu Nachzahlungen, Strafen und Pruefungen."),("Verzichten Sie auf KI-Unterstuetzung komplett, weil der Steuerberater dagegen ist und er der Experte ist.","Suboptimal! KI kann die Vorarbeit deutlich beschleunigen — der Berater sollte nur pruefen und bestaetigen.")),2),
("de","ai-finance","Ihre Bank bietet einen KI-gesteuerten Anlageberater an, der basierend auf Ihrem Risikoprofil Investments vorschlaegt.","KI-Anlageberatung gibt Orientierung, ersetzt aber keine individuelle Finanzberatung durch echte Experten.",O(("Nutzen Sie die KI-Vorschlaege als Orientierung und besprechen wichtige Entscheidungen mit einem Finanzberater.","Richtig! KI-Vorschlaege als Ausgangspunkt plus menschliche Beratung ist die sicherste Anlagestrategie."),("Investieren Sie sofort alles genau nach den KI-Empfehlungen, weil Algorithmen besser analysieren als Menschen.","Riskant! KI-Modelle haben blinde Flecken und koennen unerwartete Marktentwicklungen nicht vorhersagen."),("Ignorieren Sie das Angebot komplett, weil Sie KI-generierter Finanzberatung grundsaetzlich nicht vertrauen.","Verpasste Chance! KI-Analyse kann wertvolle Einblicke liefern, wenn sie kritisch betrachtet wird.")),1),
]

# ===== ai-finance EN =====
Q += [
("en","ai-finance","Your accounting team wants AI software that automatically captures and categorizes invoices. How do you introduce this system?","AI in accounting saves enormous time but requires regular human spot checks for quality assurance.",O(("Introduce the system gradually, verify results with spot checks, and train the entire team properly.","Perfect! Gradual introduction with quality controls minimizes errors and builds team confidence."),("Let the AI process all invoices completely autonomously without any human review from the very start.","Dangerous! Erroneous bookings can lead to incorrect financial statements and legal consequences."),("Reject AI accounting because financial data is too sensitive for any kind of automated processing.","Too conservative! Modern AI accounting is secure and efficient but needs ongoing human oversight.")),2),
("en","ai-finance","Your AI software predicts a revenue decline next quarter based on current market data. How do you respond to this forecast?","AI forecasts are early warning systems — they do not replace human judgment for important business decisions.",O(("Take the forecast seriously, analyze the underlying data, and develop a contingency plan proactively.","Correct! Using AI forecasts as early warnings combined with human analysis is the smart approach."),("Ignore the AI forecast because algorithms cannot truly understand the full complexity of real markets.","Risky! AI detects patterns in data that humans miss — ignoring warnings can be extremely costly."),("Immediately lay off employees and cut budgets based solely on the AI prediction without verification.","Dangerous! Drastic measures based only on an unvalidated AI forecast are completely irresponsible.")),2),
("en","ai-finance","An auditor asks how your company uses AI in accounting and whether results are properly auditable. What do you answer?","AI in accounting must be auditable and documented — transparency is an absolute compliance requirement.",O(("Present the documented AI processes, spot check protocols, and human approval steps to the auditor.","Perfect! Documented processes with human oversight reliably meet all audit requirements."),("Explain that AI systems are too complex for audits and the auditor simply needs to accept that fact.","Unacceptable! Every automated process in accounting must be auditable and traceable at all times."),("Conceal the AI usage and claim everything is still done manually by the accounting staff members.","Dangerous! Hiding AI usage from auditors is a serious compliance violation with severe consequences.")),3),
("en","ai-finance","Your AI system flags an unusual transaction on a company account. It could be fraud or a technical error. How do you proceed?","AI fraud detection is a valuable early warning system — but always verify findings with human review.",O(("Review the transaction manually immediately, contact the bank, and document the entire incident carefully.","Correct! Swift human review of AI warnings prevents damage and protects the company effectively."),("Ignore the AI warning because false alarms are common and the transaction is probably perfectly fine.","Risky! Even though false alarms occur, one ignored fraud case can cause enormous financial damage."),("Immediately freeze all accounts and halt all payment operations until the investigation is complete.","Excessive! One suspicious transaction does not justify completely paralyzing the entire business.")),2),
("en","ai-finance","Your boss wants AI-based automatic payroll processing to reduce HR staff costs. What do you recommend for implementation?","AI payroll processing requires special care — errors directly affect employees and their livelihoods.",O(("Recommend AI assistance with mandatory human review of every single payroll calculation before processing.","Correct! AI speeds up payroll but human review prevents costly errors that affect employees directly."),("Support fully automated payroll without any human checks to achieve maximum operational efficiency.","Dangerous! Payroll errors cause legal problems, employee dissatisfaction, and potential lawsuits."),("Reject any AI involvement in payroll because salary processing is far too sensitive for automation.","Too conservative! AI can improve payroll processing but must always operate under human supervision.")),2),
("en","ai-finance","You need a financial presentation for investors. AI tools offer auto-generated charts and forecasts. How do you use them?","AI-generated financial data for investors must always be manually verified and formally approved first.",O(("Use AI charts as drafts, manually verify all numbers, and get formal approval before any presenting.","Perfect! AI as a work aid plus thorough review protects against errors in investor presentations."),("Create all charts manually without AI because investors find AI-generated content untrustworthy always.","Possible, but AI can significantly speed up creation when you carefully verify all the results."),("Use AI-generated forecasts and charts directly in the investor presentation without any verification.","Dangerous! Incorrect financial data for investors can lead to lawsuits and devastating trust loss.")),3),
("en","ai-finance","Your AI suggests paying supplier invoices early to capture discounts. However, this would temporarily strain your cash flow.","AI financial optimization must consider overall liquidity, not just individual savings opportunities.",O(("Assess total liquidity, calculate the net benefit, and decide individually for each invoice accordingly.","Correct! Balancing discount benefit against cash flow risk is sound financial due diligence practice."),("Ignore the AI suggestion completely because discount optimization never makes sense with tight cash flow.","Premature! In some cases, the discount can significantly outweigh the temporary cash flow disadvantage."),("Follow the AI suggestion blindly and pay all invoices early for maximum early payment discount savings.","Dangerous! Blindly chasing discounts with tight cash flow can jeopardize overall company liquidity.")),3),
("en","ai-finance","A colleague uses free online AI tools to analyze company tax data, uploading sensitive financial information to these platforms.","Sensitive financial data should never be uploaded to free online AI tools — data privacy comes first.",O(("Immediately alert the colleague to the data privacy risks and escalate the issue to IT department.","Correct! Sensitive financial data in free AI tools poses a serious data privacy risk for the company."),("Let the colleague continue because free AI tools are probably secure enough for basic financial analysis.","Negligent! Free tools often provide no data privacy guarantees for confidential corporate information."),("Terminate the colleague immediately for gross violation of company data protection policies today.","Excessive! Education and training is a much better first step than immediate termination of employment.")),2),
("en","ai-finance","Your company considers using AI for automatic tax return preparation. The tax advisor is skeptical. What do you recommend?","AI can prepare tax returns but final review by tax professionals remains mandatory for compliance.",O(("Use AI for preparation and have the tax advisor perform the final review and formal sign-off.","Perfect! AI preparation plus expert review combines efficiency with reliability and full compliance."),("Leave the tax return entirely to AI without involving the skeptical tax advisor in the process.","Dangerous! Tax return errors lead to penalties, back payments, and potentially triggering full audits."),("Skip AI support entirely because the tax advisor objects and they are the recognized expert here.","Suboptimal! AI can significantly accelerate preliminary work — the advisor should only review and confirm.")),2),
("en","ai-finance","Your bank offers an AI-powered investment advisor suggesting investments based on your risk profile. How do you use it wisely?","AI investment advice provides guidance but does not replace individualized financial advice from experts.",O(("Use AI suggestions as orientation and discuss important investment decisions with a human financial advisor.","Correct! AI suggestions as a starting point plus human advice is the safest investment strategy."),("Invest everything exactly according to AI recommendations because algorithms analyze better than humans.","Risky! AI models have blind spots and cannot predict unexpected market developments or black swans."),("Ignore the offering completely because you fundamentally do not trust AI-generated financial advice.","Missed opportunity! AI analysis can provide valuable insights when approached with appropriate skepticism.")),1),
]

# ===== ai-health DE =====
Q += [
("de","ai-health","Sie laden ein Foto eines Hautausschlags in eine KI-Diagnose-App hoch. Die App diagnostiziert eine harmlose Allergie. Wie verhalten Sie sich?","KI-Diagnose-Apps sind Orientierungshilfen, keine aerztlichen Diagnosen — immer zum Arzt gehen.",O(("Nutzen Sie die KI-Einschaetzung als ersten Hinweis und vereinbaren zeitnah einen Termin beim Hautarzt.","Richtig! KI als erste Orientierung nutzen und dann professionelle aerztliche Diagnose einholen."),("Vertrauen Sie der Diagnose und behandeln den Ausschlag selbst mit freiverkaeuflichen Allergiemitteln.","Riskant! KI-Apps koennen Hautkrankheiten verwechseln — eine aerztliche Diagnose ist unverzichtbar."),("Ignorieren Sie den Ausschlag komplett, weil die KI gesagt hat, es sei harmlos und nichts zu tun sei.","Gefaehrlich! KI-Apps haben Fehlerquoten und koennen ernsthafte Erkrankungen als harmlos einstufen.")),2),
("de","ai-health","Ihre Firma fuehrt eine KI-gestuetzte Mental-Health-App fuer Mitarbeitende ein. Einige Kollegen haben Datenschutzbedenken.","Mental-Health-Apps brauchen hoechsten Datenschutz — Vertrauen ist die Grundlage fuer Akzeptanz.",O(("Pruefen Sie Datenschutzzertifizierungen, garantieren Anonymitaet und informieren transparent ueber Datennutzung.","Perfekt! Transparenz und zertifizierter Datenschutz schaffen Vertrauen bei sensiblen Gesundheitsdaten."),("Fuehren Sie die App trotz Bedenken ein, weil psychische Gesundheit wichtiger als Datenschutzsorgen ist.","Problematisch! Ohne Vertrauen in den Datenschutz wird niemand die App fuer persoenliche Themen nutzen."),("Verzichten Sie auf die App komplett, weil Datenschutz bei Gesundheitsapps nie garantiert werden kann.","Uebertrieben! Zertifizierte Apps koennen hohe Datenschutzstandards erfuellen und echten Mehrwert bieten.")),3),
("de","ai-health","Ein KI-Fitnesstracker warnt Sie, dass Ihr Herzrhythmus unregelmaessig ist. Sie fuehlen sich aber voellig gesund. Was tun Sie?","KI-Gesundheitswarnungen ernst nehmen, aber nicht in Panik verfallen — aerztliche Klaerung ist der Weg.",O(("Nehmen Sie die Warnung ernst, bleiben ruhig und vereinbaren zeitnah einen Termin beim Kardiologen.","Richtig! KI-Warnungen ernst nehmen und aerztlich abklaeren lassen ist die vernuenftige Reaktion."),("Ignorieren Sie die Warnung komplett, weil Sie sich fit fuehlen und der Tracker sicher nur fehlerhaft ist.","Riskant! Herzrhythmusstoerungen koennen symptomlos sein und trotzdem behandlungsbeduerftig ausfallen."),("Rufen Sie sofort den Rettungswagen, weil eine KI-Warnung ueber den Herzrhythmus ein Notfall sein muss.","Uebertrieben! Ruhig bleiben und zeitnah zum Arzt gehen ist angemessener als sofortige Panik.")),2),
("de","ai-health","Sie nutzen eine KI-App fuer Schlafanalyse. Seit zwei Wochen schlafen Sie trotz Befolgung aller Empfehlungen weiterhin schlecht.","KI-Schlafanalyse liefert wertvolle Daten, kann aber Ursachen chronischer Schlafprobleme nicht behandeln.",O(("Nutzen Sie die KI-Daten als Grundlage fuer ein Gespraech mit Ihrem Hausarzt ueber die Schlafprobleme.","Perfekt! KI-Daten als Gespraechsbasis beim Arzt kombiniert Technologie mit professioneller Beratung."),("Folgen Sie weiter blind den KI-Empfehlungen, weil der Algorithmus bestimmt irgendwann die Loesung findet.","Riskant! Chronische Schlafprobleme koennen medizinische Ursachen haben, die KI nicht diagnostiziert."),("Loeschen Sie die App, weil sie offensichtlich nicht funktioniert und Ihre Schlafprobleme verschlimmert.","Voreilig! Die App liefert wertvolle Daten — das Problem liegt moeglicherweise tiefer als Schlafhygiene.")),2),
("de","ai-health","Ein Kollege behauptet, eine KI-App habe seine Depression diagnostiziert und er brauche keinen Therapeuten mehr. Wie reagieren Sie?","KI kann psychische Gesundheit screenen, aber niemals eine professionelle Therapie ersetzen.",O(("Ermutigen Sie ihn einfuehlsam, die KI-Einschaetzung mit einem Therapeuten zu besprechen und Hilfe anzunehmen.","Richtig! KI-Screening als Anlass fuer professionelle Hilfe nutzen ist der verantwortungsvolle Weg."),("Akzeptieren Sie seine Entscheidung, weil jeder selbst ueber seine Gesundheitsversorgung entscheidet.","Verstaendlich, aber riskant — bei Depressionen ist professionelle Unterstuetzung lebensrettend wichtig."),("Sagen Sie ihm direkt, dass KI-Apps fuer Depressionsdiagnose voellig ungeeignet und gefaehrlich nutzlos sind.","Zu hart! Anerkennen Sie seinen Schritt und ermutigen sanft zur ergaenzenden professionellen Hilfe.")),3),
("de","ai-health","Ihre Firma bietet ein KI-Wellness-Programm an, das Stresslevel anhand von Tastaturverhalten und Mausbewegungen am Arbeitsplatz analysiert.","Arbeitsplatz-Monitoring muss transparent und freiwillig sein — heimliche Ueberwachung zerstoert Vertrauen.",O(("Fordern Sie vollstaendige Transparenz, freiwillige Teilnahme und anonymisierte Datenverarbeitung ein.","Perfekt! Transparenz plus Freiwilligkeit plus Anonymisierung schuetzt Mitarbeiterrechte und Vertrauen."),("Nutzen Sie das Programm heimlich zur Leistungsbewertung, weil Stressdaten nuetzliche Leistungsindikatoren sind.","Illegal! Heimliche Ueberwachung und Leistungsbewertung durch Verhaltensdaten verstossen gegen Arbeitsrecht."),("Lehnen Sie das Programm komplett ab, weil jede Form von Mitarbeiter-Monitoring grundsaetzlich falsch ist.","Zu pauschal! Freiwillige und anonymisierte Wellness-Programme koennen echten Mehrwert fuer alle bieten.")),3),
("de","ai-health","Sie moechten eine KI-App nutzen, die Ihre Ernaehrung analysiert und persoenliche Naehrstoffempfehlungen gibt. Wie gehen Sie damit um?","KI-Ernaehrungsapps geben Orientierung, koennen aber individuelle Stoffwechselbesonderheiten nicht erfassen.",O(("Nutzen Sie die App als Orientierung und besprechen die Empfehlungen bei Bedarf mit einem Ernaehrungsberater.","Richtig! KI-Empfehlungen als Startpunkt plus professionelle Beratung ergibt die beste Strategie."),("Folgen Sie allen KI-Empfehlungen exakt, weil der Algorithmus Ihre Ernaehrung besser analysiert als Sie.","Riskant! KI kennt keine Vorerkrankungen oder Unvertraeglichkeiten, die Ihr Arzt beruecksichtigen wuerde."),("Ignorieren Sie die App komplett, weil gesunde Ernaehrung kein Technikproblem ist, das KI loesen sollte.","Verpasst! KI-Apps koennen blinde Flecken in der eigenen Ernaehrung aufdecken und Bewusstsein schaerfen.")),1),
("de","ai-health","Ihr Arbeitgeber moechte KI-gestuetzte Gesundheitschecks als Teil des betrieblichen Gesundheitsmanagements anbieten. Was raten Sie?","Betriebliche KI-Gesundheitschecks muessen freiwillig und datenschutzkonform sein — immer ohne Ausnahme.",O(("Empfehlen Sie freiwillige Teilnahme, zertifizierte Anbieter und strikte Trennung von Gesundheits- und Arbeitsdaten.","Perfekt! Freiwilligkeit plus zertifizierter Datenschutz plus Datentrennung schuetzt alle Beteiligten."),("Unterstuetzen Sie verpflichtende Gesundheitschecks, weil sie helfen, kranke Mitarbeiter frueh zu erkennen.","Illegal! Verpflichtende Gesundheitschecks verletzen das Recht auf koerperliche Selbstbestimmung."),("Lehnen Sie KI-Gesundheitschecks komplett ab, weil Arbeitgeber nichts ueber Mitarbeitergesundheit wissen duerfen.","Zu pauschal! Freiwillige, anonyme Programme koennen die Gesundheit am Arbeitsplatz wirklich verbessern.")),2),
("de","ai-health","Eine Freundin nutzt ausschliesslich KI-Chatbots statt einer Therapeutin fuer ihre Angststoerung. Sie machen sich Sorgen um sie.","KI-Chatbots fuer mentale Gesundheit sind Ergaenzung, niemals Ersatz fuer professionelle Therapie.",O(("Sprechen Sie empathisch mit ihr und ermutigen sie, den KI-Chatbot als Ergaenzung zu professioneller Hilfe zu sehen.","Richtig! Empathie zeigen und sanft auf professionelle Therapie hinweisen ist der beste Ansatz."),("Lassen Sie sie in Ruhe, weil jeder das Recht hat, seine eigene Behandlungsmethode frei zu waehlen.","Verstaendlich, aber Angststoerungen verschlimmern sich ohne Therapie — professionelle Hilfe kann lebensrettend sein."),("Sagen Sie ihr direkt, dass es verrueckt ist, einen Chatbot statt einen echten Therapeuten zu benutzen.","Verletzend! Solche Aussagen erhoehen die Hemmschwelle fuer professionelle Hilfe noch weiter.")),3),
("de","ai-health","Sie arbeiten im Homeoffice und eine KI-App schlaegt regelmaessige Bewegungspausen vor. Bisher ignorieren Sie die Erinnerungen.","KI-Gesundheitserinnerungen funktionieren nur, wenn Sie bereit sind, Gewohnheiten bewusst zu aendern.",O(("Aktivieren Sie die Erinnerungen als festen Termin und starten mit kurzen fuenfminuetigen Bewegungspausen.","Perfekt! Kleine Schritte mit fester Routine machen KI-Empfehlungen zu nachhaltigen Gewohnheiten."),("Deaktivieren Sie die App komplett, weil die staendigen Erinnerungen Sie nur zusaetzlich stressen und nerven.","Verstaendlich, aber Bewegungsmangel im Homeoffice ist ein ernstes langfristiges Gesundheitsrisiko."),("Ignorieren Sie die Erinnerungen weiterhin, weil Sie spaeter irgendwann von selbst mehr Sport machen werden.","Unrealistisch! Ohne konkrete Aenderung der Gewohnheiten bleibt Bewegungsmangel dauerhaft bestehen.")),1),
]

# ===== ai-health EN =====
Q += [
("en","ai-health","You upload a photo of a skin rash to an AI diagnosis app. The app diagnoses a harmless allergy. How do you proceed?","AI diagnosis apps are orientation aids, not medical diagnoses — always see a real doctor afterwards.",O(("Use the AI assessment as an initial hint and schedule an appointment with a dermatologist promptly.","Correct! AI as first orientation combined with professional medical diagnosis is the responsible approach."),("Trust the diagnosis and treat the rash yourself with over-the-counter allergy medication immediately.","Risky! AI apps can confuse skin conditions — a professional medical diagnosis is always essential."),("Ignore the rash completely because the AI said it was harmless and there is nothing to worry about.","Dangerous! AI apps have error rates and can incorrectly classify serious conditions as harmless.")),2),
("en","ai-health","Your company introduces an AI mental health app for employees. Some colleagues have data privacy concerns. What do you recommend?","Mental health apps need the highest data privacy standards — trust is the foundation for acceptance.",O(("Verify privacy certifications, guarantee anonymity, and transparently communicate all data usage policies.","Perfect! Transparency and certified privacy protection build trust for sensitive health data."),("Introduce the app despite concerns because mental health is more important than privacy worries.","Problematic! Without privacy trust, nobody will use the app for deeply personal mental health topics."),("Reject the app entirely because data privacy for health apps can never be fully guaranteed.","Excessive! Certified apps can meet high privacy standards and provide genuine value to employees.")),3),
("en","ai-health","An AI fitness tracker warns your heart rhythm is irregular. However, you feel completely healthy and fine. What do you do?","Take AI health warnings seriously without panicking — medical clarification is always the right path.",O(("Take the warning seriously, stay calm, and schedule an appointment with a cardiologist promptly.","Correct! Taking AI warnings seriously and getting medical verification is the sensible response."),("Ignore the warning completely because you feel fine and the tracker is surely just malfunctioning.","Risky! Heart rhythm disorders can be symptomless yet still require medical treatment and attention."),("Call an ambulance immediately because an AI heart rhythm warning must indicate a medical emergency.","Excessive! Stay calm and see a doctor promptly — that is more appropriate than calling emergency services.")),2),
("en","ai-health","You use an AI sleep analysis app. Despite following its recommendations for two weeks, you still sleep poorly every night.","AI sleep analysis provides valuable data but cannot treat the underlying causes of chronic sleep problems.",O(("Use the AI data as a basis for a conversation with your doctor about your persistent sleep problems.","Perfect! AI data as a discussion basis with your doctor combines technology with professional care."),("Continue following the AI recommendations blindly because the algorithm will eventually find the solution.","Risky! Chronic sleep problems can have medical causes that no AI app is able to diagnose properly."),("Delete the app because it obviously does not work and is only making your sleep problems even worse.","Premature! The app provides valuable data — the problem may be deeper than sleep hygiene alone.")),2),
("en","ai-health","A colleague claims an AI app diagnosed their depression and they no longer need a therapist. How do you respond responsibly?","AI can screen for mental health issues but can never replace professional therapy and treatment.",O(("Encourage them empathetically to discuss the AI assessment with a therapist and accept professional help.","Correct! Using AI screening as motivation to seek professional help is the responsible approach."),("Accept their decision because everyone has the right to choose their own mental health care methods.","Understandable but risky — for depression, professional support can be critically important and lifesaving."),("Tell them bluntly that using AI apps for depression diagnosis is completely useless and dangerously naive.","Too harsh! Acknowledge their step and gently encourage supplementary professional help instead.")),3),
("en","ai-health","Your company offers an AI wellness program analyzing employee stress through keyboard typing patterns and mouse movements.","Workplace monitoring must be transparent and voluntary — secret surveillance destroys employee trust.",O(("Demand complete transparency, voluntary participation, and anonymized data processing for all employees.","Perfect! Transparency plus voluntary participation plus anonymization protects employee rights and trust."),("Use the program secretly for performance evaluation because stress data are useful performance indicators.","Illegal! Secret surveillance and performance evaluation through behavioral data violates employment laws."),("Reject the program entirely because any form of employee monitoring is fundamentally wrong in principle.","Too broad! Voluntary and anonymized wellness programs can provide genuine value for all employees.")),3),
("en","ai-health","You want to use an AI nutrition app that analyzes your diet and gives personalized recommendations. How do you approach this?","AI nutrition apps provide guidance but cannot capture individual metabolic conditions or medical history.",O(("Use the app as guidance and discuss the recommendations with a nutrition professional when needed.","Correct! AI recommendations as a starting point plus professional advice creates the best strategy."),("Follow all AI recommendations exactly because the algorithm analyzes your nutrition better than you can.","Risky! AI does not know about conditions or intolerances that your doctor would carefully consider."),("Ignore the app completely because healthy eating is not a technology problem that AI should solve.","Missing out! AI apps can reveal blind spots in your diet and effectively raise nutritional awareness.")),1),
("en","ai-health","Your employer wants to offer AI health checks as part of the workplace wellness program. What do you advise them?","Workplace AI health checks must be voluntary and privacy-compliant — always without any exceptions.",O(("Recommend voluntary participation, certified providers, and strict separation of health and employment data.","Perfect! Voluntariness plus certified privacy plus data separation protects everyone involved."),("Support mandatory health checks because they help the company identify unwell employees early on.","Illegal! Mandatory health checks violate the fundamental right to bodily autonomy of all employees."),("Reject AI health checks entirely because employers must never know anything about employee health.","Too broad! Voluntary and anonymous programs can genuinely improve workplace health and wellbeing.")),2),
("en","ai-health","A friend exclusively uses AI chatbots instead of a therapist to manage their anxiety disorder. You are worried about them.","AI chatbots for mental health are supplements, never replacements for professional therapeutic treatment.",O(("Speak with them empathetically and encourage using the AI chatbot as a supplement to professional therapy.","Correct! Showing empathy and gently pointing toward professional therapy is the best supportive approach."),("Leave them alone because everyone has the right to freely choose their own preferred treatment method.","Understandable, but anxiety disorders can worsen — professional help can be truly life-changing."),("Tell them directly that using a chatbot instead of seeing a real qualified therapist is completely foolish.","Hurtful! Such statements raise the barrier to seeking professional help even higher than before.")),3),
("en","ai-health","You work from home and an AI app suggests regular movement breaks. So far you have consistently ignored every reminder.","AI health reminders only work if you are willing to consciously change your daily habits and routines.",O(("Enable the reminders as fixed calendar events and start with short five-minute movement breaks daily.","Perfect! Small steps with a fixed routine turn AI recommendations into sustainable healthy habits."),("Disable the app completely because the constant reminders only stress you out and annoy you more.","Understandable, but lack of movement while working from home is a serious long-term health risk."),("Keep ignoring the reminders because you plan to start exercising more on your own eventually someday.","Unrealistic! Without concrete changes to your habits, lack of movement will persist indefinitely.")),1),
]

# ===== ai-education DE =====
Q += [
("de","ai-education","Ein Azubi nutzt ChatGPT, um sein Berichtsheft zu schreiben. Der Ausbilder bemerkt ungewoehnlich gute Formulierungen. Wie reagieren Sie?","KI kann Berichtshefte unterstuetzen, aber der Lerneffekt entsteht nur durch eigene Reflexion.",O(("Sprechen Sie den Azubi an und zeigen ihm, wie KI als Lernhilfe statt als Ghostwriter genutzt wird.","Richtig! KI als Lernwerkzeug zu nutzen ist legitim — der Azubi muss aber selbst reflektieren."),("Ignorieren Sie es, weil der Azubi offensichtlich effizient arbeitet und gute Ergebnisse abliefert.","Riskant! Ohne eigene Reflexion lernt der Azubi nichts und die Ausbildung verliert ihren Sinn."),("Verbieten Sie dem Azubi jegliche KI-Nutzung und drohen mit Konsequenzen bei erneutem Vergehen.","Ueberzogen! KI-Verbote bereiten Azubis schlecht auf die digitale Arbeitswelt von morgen vor.")),2),
("de","ai-education","Sie sind Dozent und vermuten, dass mehrere Studierende ihre Hausarbeit mit KI geschrieben haben. Wie gehen Sie damit um?","KI-Nutzung in der Bildung braucht klare Regeln — nicht Verbote, sondern transparente Leitlinien.",O(("Fuehren Sie klare KI-Richtlinien ein, die transparente Nutzung erlauben und die Eigenleistung definieren.","Perfekt! Transparente Regeln foerdern verantwortungsvollen Umgang statt heimliche Nutzung von KI."),("Fuehren Sie muendliche Pruefungen ein, um sicherzustellen, dass Studierende den Stoff wirklich verstanden haben.","Sinnvolle Ergaenzung, aber ohne klare KI-Richtlinien bleibt das Grundproblem ungeloest."),("Verbieten Sie KI-Nutzung komplett und fuehren Software zur Erkennung von KI-generierten Texten ein.","Kontraproduktiv! KI-Erkennungstools sind unzuverlaessig und Verbote foerdern nur heimliche Nutzung.")),3),
("de","ai-education","Ihr Kind nutzt KI-Lerntools fuer Mathematik-Hausaufgaben. Die Noten verbessern sich, aber Sie sind unsicher ob echtes Lernen stattfindet.","KI-Lerntools koennen Verstaendnis foerdern oder ersetzen — der Unterschied liegt in der Nutzungsweise.",O(("Ueberpruefen Sie gemeinsam die KI-Loesungswege und stellen sicher, dass Ihr Kind den Rechenweg versteht.","Richtig! Gemeinsame Pruefung der Loesungswege sichert echtes Verstaendnis beim KI-gestuetzten Lernen."),("Freuen Sie sich ueber die besseren Noten und vertrauen darauf, dass das KI-Tool richtig unterrichtet.","Riskant! Bessere Noten bedeuten nicht automatisch besseres Verstaendnis — Kontrolle ist wichtig."),("Verbieten Sie das KI-Tool sofort und bestehen darauf, dass Ihr Kind nur mit dem Schulbuch allein lernt.","Uebertrieben! KI-Lerntools koennen echtes Verstaendnis foerdern, wenn sie richtig eingesetzt werden.")),1),
("de","ai-education","Sie muessen sich in drei Wochen fuer eine berufliche Zertifizierung weiterbilden. KI-Tools koennten beim Lernen helfen. Wie setzen Sie sie ein?","KI kann Lernmaterial strukturieren und Wissensluecken aufdecken — aber Lernen bleibt Ihre Aufgabe.",O(("Nutzen Sie KI um Lernplaene zu erstellen, Wissensluecken zu identifizieren und Uebungsfragen zu generieren.","Perfekt! KI als Lernorganisator und Uebungspartner maximiert Ihre Vorbereitungseffizienz optimal."),("Lernen Sie ausschliesslich mit traditionellen Lehrmaterialien, weil KI-gestuetztes Lernen oberflaechlich ist.","Moeglich, aber Sie verschenken effiziente Lernmoeglichkeiten durch personalisierte KI-Unterstuetzung."),("Verlassen Sie sich darauf, dass KI Ihnen waehrend der Pruefung ueber Umwege die Antworten liefern kann.","Gefaehrlich! Betrugsversuche bei Zertifizierungen fuehren zu Ausschluss und Reputationsverlust.")),2),
("de","ai-education","Eine Berufsschule moechte KI-Tools fuer individualisiertes Lernen einfuehren. Eltern sind besorgt wegen Datenschutz und Abhaengigkeit.","KI in der Bildung braucht Balance zwischen Innovation und Schutz der Lernenden — Dialog ist entscheidend.",O(("Organisieren Sie einen Elternabend, praesentieren Datenschutzkonzepte und bieten eine Pilotphase an.","Richtig! Transparente Kommunikation und Pilotphase bauen Vertrauen bei besorgten Eltern auf."),("Fuehren Sie die KI-Tools trotz Elternbedenken ein, weil paedagogische Entscheidungen der Schule obliegen.","Problematisch! Ohne Elternvertrauen fehlt die Unterstuetzung, die fuer erfolgreiche KI-Nutzung noetig ist."),("Verzichten Sie auf KI-Tools komplett, weil Datenschutz bei Minderjaerigen absolute Prioritaet haben muss.","Uebervorsichtig! Datenschutzkonforme KI-Loesungen existieren und koennen das Lernen verbessern.")),2),
("de","ai-education","Ihr Mitarbeiter nutzt KI um eine Praesentation fuer eine interne Weiterbildung zu erstellen. Die Inhalte enthalten faktische Fehler.","KI-generierte Lernmaterialien muessen immer auf Richtigkeit geprueft werden — Fehler sind haeufig.",O(("Pruefen Sie die KI-Inhalte gemeinsam auf Fakten, korrigieren Fehler und schulen den Umgang mit Quellenpruefung.","Perfekt! Gemeinsame Faktencheck-Schulung baut KI-Kompetenz und kritisches Denken gleichzeitig auf."),("Lassen Sie die Praesentation so durchgehen, weil kleine Fehler in internen Weiterbildungen nicht schlimm sind.","Riskant! Falsche Informationen in Schulungen verbreiten sich und fuehren zu Fehlentscheidungen."),("Verbieten Sie KI fuer interne Praesentationen, weil die Fehlerquote bei KI-generierten Inhalten zu hoch ist.","Uebertrieben! KI mit Faktencheck ist effizienter als Totalverbot und baut wichtige Kompetenz auf.")),2),
("de","ai-education","Sie sind Lehrer und ein Schueler gibt zu, dass er seinen Aufsatz komplett mit KI geschrieben hat. Wie reagieren Sie paedagogisch?","Der ehrliche Umgang des Schuelers mit KI-Nutzung ist ein Lernmoment — nutzen Sie ihn konstruktiv.",O(("Wuerdigen Sie die Ehrlichkeit, erklaeren die Lernziele und lassen den Schueler den Aufsatz eigenstaendig ueberarbeiten.","Vorbildlich! Ehrlichkeit wertschaetzen und Lernziele verdeutlichen foerdert verantwortungsvolle KI-Nutzung."),("Geben Sie dem Schueler eine Sechs, weil KI-generierte Arbeiten als Taeuschungsversuch gewertet werden muessen.","Zu streng! Der Schueler war ehrlich — eine harte Strafe entmutigt kuenftige Transparenz."),("Ignorieren Sie das Gestaendnis und bewerten den Aufsatz ganz normal wie jeden anderen abgegebenen Text.","Problematisch! Ohne paedagogische Reaktion lernt der Schueler nicht, warum Eigenleistung wichtig ist.")),2),
("de","ai-education","Eine Universitaet plant, KI-gestuetzte Pruefungen einzufuehren, die sich automatisch an das Wissensniveau der Studierenden anpassen.","Adaptive KI-Pruefungen koennen fairer sein als Standardtests — wenn Chancengleichheit gewaehrleistet ist.",O(("Fuehren Sie Pilottests durch, pruefen Fairness und Chancengleichheit und holen Studierenden-Feedback ein.","Perfekt! Pilotphase mit Fairness-Pruefung und Studierenden-Einbindung sichert die Qualitaet."),("Ersetzen Sie alle Pruefungen sofort durch KI-adaptive Tests ohne Pilotphase, um modern zu wirken.","Riskant! Ungeprueft koennen adaptive Tests systematische Benachteiligungen erzeugen und verstaerken."),("Lehnen Sie KI-Pruefungen ab, weil traditionelle Klausuren seit Jahrzehnten bewaehrt und ausreichend sind.","Innovationsfeindlich! Adaptive Pruefungen koennen individuelle Staerken besser erfassen als Standardtests.")),3),
("de","ai-education","Sie muessen als Personalentwickler eine Weiterbildungsstrategie mit KI-Elementen fuer 200 Mitarbeitende erstellen.","KI-gestuetzte Weiterbildung funktioniert am besten, wenn sie individuell und freiwillig gestaltet wird.",O(("Analysieren Sie individuelle Lernbedarfe mit KI, bieten personalisierte Lernpfade und messen den Erfolg.","Perfekt! Personalisierte KI-Lernpfade mit Erfolgsmessung maximieren den Weiterbildungserfolg fuer alle."),("Kaufen Sie eine KI-Lernplattform und machen die Nutzung fuer alle Mitarbeitenden sofort verpflichtend.","Problematisch! Zwang erzeugt Widerstand — freiwillige und personalisierte Angebote motivieren besser."),("Setzen Sie weiterhin auf Praesenzschulungen, weil KI-gestuetztes Lernen nicht fuer alle geeignet ist.","Zu pauschal! KI-gestuetzte und Praesenzformate ergaenzen sich ideal fuer diverse Lerntypen.")),2),
("de","ai-education","Ein Student nutzt KI-Uebersetzungstools fuer seine Sprachkurse und besteht alle Tests, kann aber kein Gespraech fuehren.","KI-Uebersetzungstools koennen Sprachlernen sabotieren, wenn sie als Abkuerzung statt als Hilfe genutzt werden.",O(("Raten Sie dem Studenten, KI als Lernpartner fuer Vokabeln zu nutzen und Gespraeche aktiv zu ueben.","Richtig! KI als Lernhilfe nutzen und gleichzeitig aktive Sprachpraxis foerdern ist der beste Weg."),("Lassen Sie den Studenten weitermachen, weil die Testergebnisse gut sind und das Lernen funktioniert.","Taeuscht! Gute Noten ohne Sprechfaehigkeit bedeuten, dass das eigentliche Lernziel verfehlt wird."),("Verbieten Sie alle KI-Tools in Sprachkursen, weil sie echtes Sprachlernen grundsaetzlich verhindern.","Uebertrieben! KI-Tools koennen beim Vokabellernen und Grammatikverstaendnis sehr effektiv helfen.")),2),
]

# ===== ai-education EN =====
Q += [
("en","ai-education","An apprentice uses ChatGPT to write their training logbook. The trainer notices unusually polished language. How do you respond?","AI can support training logs, but the learning effect only comes through personal reflection and writing.",O(("Talk to the apprentice and show them how AI can be used as a learning aid rather than a ghostwriter.","Correct! Using AI as a learning tool is legitimate — the apprentice must still reflect on their own."),("Ignore it because the apprentice is clearly efficient and delivering good quality results consistently.","Risky! Without personal reflection, the apprentice learns nothing and the training loses its purpose."),("Ban the apprentice from using any AI tools and threaten consequences for any repeated violations.","Excessive! AI bans poorly prepare apprentices for the digital workplace of tomorrow and beyond.")),2),
("en","ai-education","As a lecturer, you suspect several students wrote their assignments with AI assistance. How do you handle this situation?","AI use in education needs clear rules — not bans, but transparent guidelines that define expectations.",O(("Introduce clear AI guidelines that allow transparent usage while defining what constitutes original work.","Perfect! Transparent rules promote responsible AI use instead of encouraging secretive usage."),("Introduce oral exams to ensure students truly understand the material they submitted in written form.","Useful supplement, but without clear AI guidelines the fundamental problem remains unresolved."),("Ban AI usage completely and implement software to detect AI-generated text in all submissions.","Counterproductive! AI detection tools are unreliable and complete bans only encourage secret usage.")),3),
("en","ai-education","Your child uses AI learning tools for math homework. Grades improve, but you are unsure whether real learning is happening.","AI learning tools can promote or replace understanding — the difference lies in how they are used.",O(("Review the AI solution paths together and ensure your child actually understands the mathematical reasoning.","Correct! Joint review of solution paths ensures real understanding during AI-assisted learning."),("Celebrate the better grades and trust that the AI tool is teaching the material correctly on its own.","Risky! Better grades do not automatically mean better understanding — verification is important."),("Ban the AI tool immediately and insist your child learns only with the textbook and nothing else.","Excessive! AI learning tools can promote real understanding when they are used correctly.")),1),
("en","ai-education","You have three weeks to prepare for a professional certification. AI tools could help with studying. How do you use them?","AI can structure learning material and reveal knowledge gaps — but actual learning remains your task.",O(("Use AI to create study plans, identify knowledge gaps, and generate practice questions for yourself.","Perfect! AI as a learning organizer and practice partner maximizes your preparation efficiency."),("Study exclusively with traditional materials because AI-assisted learning is superficial and unreliable.","Possible, but you miss efficient learning opportunities through personalized AI-powered support."),("Count on AI somehow providing you with answers during the exam through creative workarounds.","Dangerous! Cheating attempts in certification exams lead to exclusion and serious reputational damage.")),2),
("en","ai-education","A vocational school wants to introduce AI tools for individualized learning. Parents are concerned about privacy and dependency.","AI in education needs balance between innovation and learner protection — dialogue is essential always.",O(("Organize a parent meeting, present data privacy concepts, and offer a transparent pilot phase first.","Correct! Transparent communication and pilot phases build trust with concerned parents effectively."),("Introduce AI tools despite parent concerns because pedagogical decisions belong to the school alone.","Problematic! Without parental trust, the support needed for successful AI adoption will be missing."),("Skip AI tools entirely because data privacy for minors must always have absolute priority over everything.","Overcautious! Privacy-compliant AI solutions exist and can genuinely enhance the learning experience.")),2),
("en","ai-education","Your employee uses AI to create a presentation for internal training. The content contains several factual errors. How do you handle this?","AI-generated learning materials must always be fact-checked — errors are surprisingly common in AI output.",O(("Review the AI content together for accuracy, correct errors, and train them on source verification.","Perfect! Joint fact-checking builds both AI competence and critical thinking skills simultaneously."),("Let the presentation slide because small errors in internal training sessions are not a big deal.","Risky! Wrong information in training materials spreads quickly and leads to poor decisions later."),("Ban AI for internal presentations because the error rate in AI-generated content is simply too high.","Excessive! AI with fact-checking is more efficient than a total ban and builds important skills.")),2),
("en","ai-education","You are a teacher and a student admits they wrote their entire essay with AI. How do you respond pedagogically?","The student honest admission about AI usage is a learning moment — use it constructively and wisely.",O(("Appreciate their honesty, explain the learning objectives, and have them revise the essay independently.","Exemplary! Valuing honesty and clarifying learning goals promotes responsible AI use effectively."),("Give the student a failing grade because AI-generated work must be considered academic dishonesty always.","Too harsh! The student was honest — severe punishment discourages future transparency from others."),("Ignore the confession and grade the essay normally as you would grade any other submitted text.","Problematic! Without pedagogical response, the student does not learn why original work matters.")),2),
("en","ai-education","A university plans to introduce AI-adaptive exams that automatically adjust to each student knowledge level during the test.","Adaptive AI exams can be fairer than standard tests — if equal opportunity is properly ensured for all.",O(("Conduct pilot tests, verify fairness and equal opportunity, and gather comprehensive student feedback.","Perfect! Pilot phase with fairness review and student involvement ensures quality and acceptance."),("Replace all exams immediately with AI-adaptive tests without any pilot phase to appear innovative.","Risky! Untested adaptive tests can create and amplify systematic disadvantages for certain students."),("Reject AI exams because traditional written exams have been proven and sufficient for decades already.","Innovation-averse! Adaptive exams can capture individual strengths better than standardized tests.")),3),
("en","ai-education","As an L&D manager, you need to create a training strategy with AI elements for two hundred employees across the organization.","AI-powered training works best when it is individualized, voluntary, and properly measured for effectiveness.",O(("Analyze individual learning needs with AI, offer personalized learning paths, and measure success metrics.","Perfect! Personalized AI learning paths with success measurement maximize training impact for everyone."),("Buy an AI learning platform and make usage mandatory for all employees immediately without consultation.","Problematic! Mandatory participation creates resistance — voluntary personalized offerings motivate better."),("Continue with in-person training only because AI-based learning is not suitable for all employee types.","Too broad! AI-based and in-person formats complement each other ideally for diverse learning styles.")),2),
("en","ai-education","A student uses AI translation tools for their language courses and passes all tests but cannot hold a basic conversation.","AI translation tools can sabotage language learning when used as shortcuts instead of genuine learning aids.",O(("Advise the student to use AI as a vocabulary partner while actively practicing real conversations separately.","Correct! AI as a learning aid combined with active speaking practice is the most effective approach."),("Let the student continue because the test results are good and the learning appears to be working.","Deceptive! Good grades without speaking ability means the actual learning objective is being missed."),("Ban all AI tools in language courses because they fundamentally prevent real language acquisition.","Excessive! AI tools can help very effectively with vocabulary learning and grammar understanding.")),2),
]

# ===== ai-manufacturing DE =====
Q += [
("de","ai-manufacturing","Ihre Produktionsanlage setzt KI fuer Predictive Maintenance ein. Die KI meldet einen drohenden Maschinenausfall in 48 Stunden.","KI-Predictive-Maintenance spart Kosten und verhindert Ausfaelle — wenn die Warnungen ernst genommen werden.",O(("Planen Sie eine vorbeugende Wartung ein, pruefen die KI-Diagnose und dokumentieren den gesamten Vorgang.","Perfekt! Vorbeugende Wartung bei KI-Warnung spart Kosten und verhindert ungeplante Produktionsausfaelle."),("Ignorieren Sie die Warnung, weil die Maschine noch einwandfrei laeuft und KI-Warnungen oft falsch liegen.","Riskant! Ein ignorierter Maschinenausfall kann Tausende Euro Schaden und Lieferverzoegerungen verursachen."),("Stoppen Sie die Produktion sofort fuer eine Woche, um eine umfassende Inspektion aller Anlagen durchzufuehren.","Uebertrieben! Eine gezielte Wartung in 48 Stunden ist sinnvoller als ein vollstaendiger Produktionsstopp.")),2),
("de","ai-manufacturing","KI-gestuetzte Qualitaetskontrolle erkennt in der Produktion fehlerhafte Teile. Die Fehlerquote sinkt, aber Mitarbeiter fuehlen sich ueberwacht.","KI-Qualitaetskontrolle unterstuetzt Mitarbeitende — sie ersetzt weder Erfahrung noch menschliches Urteil.",O(("Erklaeren Sie dem Team, dass die KI Fehler findet, nicht Mitarbeiter bewertet, und schulen Sie die Nutzung.","Richtig! Klare Kommunikation dass KI Werkzeug und nicht Ueberwachung ist, schafft Akzeptanz."),("Fuehren Sie die KI-Kontrolle heimlich ein, um unverfaelschte Daten ueber die Arbeitsqualitaet zu sammeln.","Illegal! Heimliche Ueberwachung verstosst gegen Arbeitnehmerrechte und zerstoert das Teamvertrauen."),("Deaktivieren Sie die KI-Kontrolle, weil das Wohlbefinden der Mitarbeiter wichtiger ist als niedrige Fehlerquoten.","Kurzfristig denkend! Mit richtiger Kommunikation profitieren sowohl Qualitaet als auch Mitarbeitende.")),2),
("de","ai-manufacturing","Ihr Logistikleiter moechte KI fuer die automatische Routenplanung der Lieferfahrzeuge einsetzen. Die Fahrer sind skeptisch.","KI-Routenplanung optimiert Lieferzeiten — aber Fahrerwissen ueber lokale Besonderheiten ist wertvoll.",O(("Fuehren Sie die KI-Routen als Vorschlaege ein, die Fahrer bei Bedarf anpassen koennen und Feedback geben.","Perfekt! KI-Vorschlaege plus Fahrerwissen kombiniert ergibt die besten Routen fuer alle Beteiligten."),("Machen Sie KI-Routen verbindlich ohne Ausnahmen, weil der Algorithmus immer effizienter ist als Menschen.","Problematisch! Fahrer kennen lokale Bedingungen wie Baustellen und Zufahrten besser als jeder Algorithmus."),("Verzichten Sie auf KI-Routenplanung, weil erfahrene Fahrer ihre Routen seit Jahren kennen und optimiert haben.","Veraltet! KI kann Echtzeit-Verkehrsdaten nutzen, die erfahrenen Fahrern nicht zur Verfuegung stehen.")),1),
("de","ai-manufacturing","Ein Handwerksbetrieb moechte KI fuer die Angebotserstellung nutzen. Die Meisterin bezweifelt, dass KI die Komplexitaet ihrer Auftraege versteht.","KI kann Standardangebote beschleunigen — die Expertise des Handwerks bleibt fuer Sonderfaelle unverzichtbar.",O(("Nutzen Sie KI fuer Standardangebote und lassen die Meisterin komplexe Auftraege weiterhin manuell kalkulieren.","Richtig! Abgestufte KI-Nutzung nutzt Effizienzvorteile und bewahrt Handwerksexpertise fuer Sonderfaelle."),("Fuehren Sie KI fuer alle Angebote ein und ignorieren die Bedenken der Meisterin ueber Komplexitaet.","Riskant! Komplexe Handwerksauftraege haben Nuancen, die KI ohne Branchenwissen nicht erfassen kann."),("Lehnen Sie KI-Angebotserstellung komplett ab, weil Handwerksarbeit zu individuell fuer Algorithmen ist.","Zu pauschal! Standardangebote machen oft den Grossteil aus und koennen effizient automatisiert werden.")),1),
("de","ai-manufacturing","KI-Sensoren in Ihrer Fabrik melden ungewoehnliche Vibrationen an einer Maschine. Der erfahrene Techniker sagt, das sei normal.","Kombinieren Sie KI-Daten mit Technikererfahrung — beide Perspektiven zusammen ergeben das beste Bild.",O(("Dokumentieren Sie die KI-Meldung, besprechen sie mit dem Techniker und vereinbaren eine gemeinsame Pruefung.","Perfekt! KI-Daten und Technikererfahrung zusammen ergeben die zuverlaessigste Einschaetzung fuer alle."),("Vertrauen Sie dem Techniker blind, weil menschliche Erfahrung immer zuverlaessiger ist als KI-Sensoren.","Riskant! Auch erfahrene Techniker koennen schleichende Verschlechterungen uebersehen, die Sensoren erfassen."),("Stoppen Sie die Maschine sofort gegen den Rat des Technikers, weil die KI-Warnung Prioritaet haben muss.","Uebertrieben! Ein gemeinsamer Check ist besser als uebereilte Massnahmen ohne menschliche Einschaetzung.")),2),
("de","ai-manufacturing","Ihr Unternehmen fuehrt KI-gestuetzte Lagerverwaltung ein. Die Software optimiert Bestaende automatisch und reduziert Lagerkosten.","KI-Lagerverwaltung spart Kosten — aber Sicherheitsbestaende fuer kritische Teile duerfen nicht fehlen.",O(("Definieren Sie Mindestbestaende fuer kritische Teile und lassen die KI nur unkritische Bestaende optimieren.","Richtig! Kritische Sicherheitsbestaende schuetzen vor Produktionsausfaellen trotz KI-Optimierung."),("Ueberlassen Sie die gesamte Bestandssteuerung der KI, weil der Algorithmus besser rechnet als Menschen.","Gefaehrlich! Ohne Sicherheitsbestaende kann ein unvorhergesehener Engpass die gesamte Produktion stoppen."),("Behalten Sie die manuelle Lagerverwaltung bei, weil KI die Komplexitaet der Lieferkette nicht versteht.","Ineffizient! KI-Lagerverwaltung mit menschlichen Sicherheitsgrenzen ist deutlich kosteneffizienter.")),2),
("de","ai-manufacturing","Ein Zulieferer bietet Ihnen KI-generierte Qualitaetszertifikate fuer seine Bauteile an. Die Zertifikate sehen professionell aus.","KI-generierte Zertifikate koennten gefaelscht sein — verifizieren Sie Qualitaetsnachweise immer unabhaengig.",O(("Ueberpruefen Sie die Zertifikate unabhaengig bei der Zertifizierungsstelle und fuehren eigene Qualitaetstests durch.","Perfekt! Unabhaengige Verifizierung plus eigene Tests schuetzt vor gefaelschten KI-Zertifikaten."),("Akzeptieren Sie die Zertifikate, weil der Zulieferer seit Jahren zuverlaessig liefert und vertrauenswuerdig ist.","Riskant! Auch bei bekannten Zulieferern koennen KI-generierte Zertifikate Faelschungen enthalten."),("Brechen Sie die Geschaeftsbeziehung sofort ab, weil KI-generierte Zertifikate grundsaetzlich verdaechtig sind.","Voreilig! KI-generiert bedeutet nicht zwingend gefaelscht — erst pruefen, dann urteilen.")),3),
("de","ai-manufacturing","Ihre Produktionslinie nutzt KI-Roboter, die mit menschlichen Arbeitern zusammenarbeiten. Ein Mitarbeiter hat Sicherheitsbedenken.","Mensch-Roboter-Kollaboration erfordert hoechste Sicherheitsstandards — Bedenken muessen ernst genommen werden.",O(("Nehmen Sie die Bedenken ernst, fuehren eine Sicherheitspruefung durch und schulen alle Mitarbeitenden.","Richtig! Sicherheitsbedenken bei Roboter-Kollaboration ernst nehmen schuetzt Menschen und Produktivitaet."),("Ignorieren Sie die Bedenken, weil KI-Roboter technisch sicher sind und Unfaelle statistisch unwahrscheinlich.","Gefaehrlich! Jeder Sicherheitshinweis verdient Pruefung — ein einzelner Unfall kann fatale Folgen haben."),("Entfernen Sie alle KI-Roboter und kehren zu rein manueller Produktion zurueck fuer maximale Sicherheit.","Uebertrieben! Zertifizierte KI-Roboter mit guter Schulung sind sicher und steigern die Produktivitaet.")),2),
("de","ai-manufacturing","KI analysiert Ihre Produktionsdaten und schlaegt vor, die Schichtplanung komplett zu aendern. Die Mitarbeiter sind dagegen.","KI-Schichtplanung kann effizienter sein — aber die Akzeptanz der Mitarbeitenden ist entscheidend.",O(("Praesentieren Sie die KI-Vorschlaege dem Team, sammeln Feedback und passen die Planung gemeinsam an.","Perfekt! Partizipative Einfuehrung von KI-Schichtplanung schafft Akzeptanz und bessere Ergebnisse."),("Setzen Sie die KI-Schichtplanung sofort um, weil Effizienz wichtiger ist als Mitarbeiterwuensche.","Problematisch! Erzwungene Schichtaenderungen ohne Dialog fuehren zu Unzufriedenheit und hoher Fluktuation."),("Verzichten Sie auf KI-Schichtplanung, weil die Mitarbeiter dagegen sind und ihre Zufriedenheit Vorrang hat.","Kurzfristig! Ein gemeinsamer Kompromiss kann Effizienz und Mitarbeiterzufriedenheit gleichzeitig verbessern.")),2),
("de","ai-manufacturing","Ein Konkurrent setzt KI-Roboter ein und produziert 30 Prozent guenstiger. Ihr Chef fordert sofortige Automatisierung Ihrer Produktion.","KI-Automatisierung braucht Planung und Investition — blindes Kopieren der Konkurrenz fuehrt zu Problemen.",O(("Analysieren Sie zuerst Ihre spezifischen Prozesse, berechnen den ROI und planen eine stufenweise Automatisierung.","Richtig! Individuelle Analyse und stufenweiser Ansatz liefern bessere Ergebnisse als hastiges Kopieren."),("Automatisieren Sie sofort alle Prozesse mit den gleichen Robotern wie die Konkurrenz ohne eigene Analyse.","Riskant! Unterschiedliche Produktionen erfordern individuelle Automatisierungsloesungen und Anpassungen."),("Lehnen Sie Automatisierung ab, weil Ihre Mitarbeiter das Handwerk besser beherrschen als jede Maschine.","Kurzfristig! Ohne Automatisierung wird die Preisdifferenz langfristig Kunden zur Konkurrenz treiben.")),2),
]

# ===== ai-manufacturing EN =====
Q += [
("en","ai-manufacturing","Your production facility uses AI for predictive maintenance. The AI reports a likely machine failure within forty-eight hours.","AI predictive maintenance saves costs and prevents outages — when warnings are taken seriously always.",O(("Schedule preventive maintenance, verify the AI diagnosis, and document the entire process carefully.","Perfect! Preventive maintenance on AI warnings saves costs and prevents unplanned production outages."),("Ignore the warning because the machine is still running fine and AI warnings are often false alarms.","Risky! An ignored machine failure can cause thousands in damage and significant delivery delays."),("Stop all production immediately for a full week to conduct a comprehensive inspection of every machine.","Excessive! Targeted maintenance within 48 hours is smarter than a complete production shutdown.")),2),
("en","ai-manufacturing","AI quality control detects defective parts in production. The defect rate drops, but workers feel they are being surveilled.","AI quality control supports workers — it replaces neither experience nor human judgment in production.",O(("Explain to the team that AI finds defects not evaluates workers, and provide proper training on usage.","Correct! Clear communication that AI is a tool not surveillance creates acceptance among workers."),("Introduce AI control secretly to collect unbiased data about work quality without informing any workers.","Illegal! Secret surveillance violates employee rights and completely destroys team trust and morale."),("Deactivate AI quality control because worker wellbeing is more important than lowering defect rates.","Short-sighted! With proper communication, both quality and worker satisfaction can improve together.")),2),
("en","ai-manufacturing","Your logistics manager wants AI for automatic delivery route planning. The drivers are skeptical about computer-planned routes.","AI route planning optimizes delivery times — but driver knowledge of local conditions is truly valuable.",O(("Introduce AI routes as suggestions that drivers can adjust when needed and provide ongoing feedback.","Perfect! AI suggestions plus driver knowledge combined creates the best routes for everyone."),("Make AI routes mandatory without exceptions because the algorithm is always more efficient than humans.","Problematic! Drivers know local conditions like construction zones and access roads better than algorithms."),("Skip AI route planning because experienced drivers have optimized their routes over many years already.","Outdated! AI can use real-time traffic data that even experienced drivers do not have access to.")),1),
("en","ai-manufacturing","A craft business wants AI for quote generation. The master craftsperson doubts AI understands their complex custom jobs.","AI can accelerate standard quotes — craft expertise remains essential for complex custom work always.",O(("Use AI for standard quotes and let the master craftsperson continue manually pricing complex custom jobs.","Correct! Graduated AI use captures efficiency gains while preserving craft expertise for special cases."),("Implement AI for all quotes and dismiss the master concerns about complexity as resistance to change.","Risky! Complex craft jobs have nuances that AI without industry knowledge simply cannot capture."),("Reject AI quote generation entirely because craft work is too individualized for any algorithm.","Too broad! Standard quotes often make up the majority and can be efficiently automated by AI.")),1),
("en","ai-manufacturing","AI sensors report unusual vibrations on a machine. The experienced technician says it is completely normal. What do you do?","Combine AI data with technician experience — both perspectives together provide the most reliable picture.",O(("Document the AI alert, discuss it with the technician, and schedule a joint inspection of the machine.","Perfect! AI data and technician experience together yield the most reliable assessment for everyone."),("Trust the technician completely because human experience is always more reliable than AI sensor data.","Risky! Even experienced technicians can miss gradual deterioration that sensors consistently detect."),("Stop the machine immediately against the technician advice because the AI warning must take priority.","Excessive! A joint check is better than hasty action without incorporating human expert assessment.")),2),
("en","ai-manufacturing","Your company introduces AI warehouse management. The software automatically optimizes inventory levels and reduces storage costs.","AI warehouse management saves costs — but safety stock for critical parts must never be eliminated.",O(("Define minimum stock levels for critical parts and let AI optimize only non-critical inventory levels.","Correct! Critical safety stock protects against production outages despite overall AI optimization."),("Hand over all inventory control to AI because the algorithm calculates better than human planners.","Dangerous! Without safety stock, an unforeseen shortage can halt the entire production line."),("Keep manual warehouse management because AI cannot understand supply chain complexity adequately.","Inefficient! AI warehouse management with human safety parameters is significantly more cost-effective.")),2),
("en","ai-manufacturing","A supplier offers AI-generated quality certificates for their components. The certificates look very professional and official.","AI-generated certificates could be forged — always verify quality documentation independently and carefully.",O(("Verify the certificates independently with the certification body and conduct your own quality tests.","Perfect! Independent verification plus own testing protects against potentially forged AI certificates."),("Accept the certificates because the supplier has been reliable for years and is generally trustworthy.","Risky! Even with known suppliers, AI-generated certificates could potentially contain falsified data."),("Immediately terminate the business relationship because AI-generated certificates are inherently suspicious.","Premature! AI-generated does not necessarily mean forged — verify first, then make informed judgments.")),3),
("en","ai-manufacturing","Your production line uses collaborative AI robots working alongside human workers. An employee expresses safety concerns about them.","Human-robot collaboration requires the highest safety standards — concerns must always be taken seriously.",O(("Take the concerns seriously, conduct a safety review, and train all workers on proper collaboration.","Correct! Taking safety concerns about robot collaboration seriously protects people and productivity."),("Dismiss the concerns because AI robots are technically safe and accidents are statistically very unlikely.","Dangerous! Every safety concern deserves investigation — a single accident can have fatal consequences."),("Remove all AI robots and return to purely manual production for maximum workplace safety instead.","Excessive! Certified AI robots with proper training are safe and significantly boost productivity.")),2),
("en","ai-manufacturing","AI analyzes your production data and suggests completely changing shift scheduling. Workers are opposed to the proposed changes.","AI shift planning can be more efficient — but worker acceptance is decisive for successful implementation.",O(("Present the AI suggestions to the team, gather their feedback, and adjust the plan collaboratively.","Perfect! Participative introduction of AI shift planning creates acceptance and better results."),("Implement the AI shift plan immediately because efficiency is more important than worker preferences.","Problematic! Forced schedule changes without dialogue lead to dissatisfaction and high turnover."),("Abandon AI shift planning entirely because workers are against it and their satisfaction takes priority.","Short-sighted! A collaborative compromise can improve both efficiency and satisfaction simultaneously.")),2),
("en","ai-manufacturing","A competitor uses AI robots and produces thirty percent cheaper. Your boss demands immediate automation of your entire production.","AI automation requires planning and investment — blindly copying competitors leads to costly problems.",O(("Analyze your specific processes first, calculate ROI, and plan a phased automation strategy carefully.","Correct! Individual analysis and phased approach delivers better results than hastily copying competitors."),("Automate all processes immediately with the same robots as the competitor without your own analysis.","Risky! Different productions require individually tailored automation solutions and careful adaptations."),("Reject automation because your skilled workers do better work than any machine could ever achieve.","Short-sighted! Without automation, the price gap will eventually drive customers to the competition.")),2),
]

# Insert all
batch_size = 10
for i in range(0, len(Q), batch_size):
    batch = Q[i:i+batch_size]
    sql = build_insert(batch)
    label = f"batch {i//batch_size+1}: {batch[0][1]} {batch[0][0]}"
    run_sql(sql, label)
    time.sleep(0.3)

print(f"\nSCRIPT 2 DONE: {ok_count} OK, {fail_count} FAIL, {len(Q)} total questions")
