#!/usr/bin/env python
"""Generate and insert 280 quiz questions into Supabase for AI-Shift Happens."""
import json, subprocess, time, sys

TOKEN = "sbp_9d3bb1ca2c1b81ded0e6ebf813b66dd81e29896f"
URL = "https://api.supabase.com/v1/projects/amhfxaqolholacanqyas/database/query"

ok_count = 0
fail_count = 0

def run_sql(sql, label):
    global ok_count, fail_count
    payload = json.dumps({"query": sql})
    r = subprocess.run(
        ["curl", "-s", "-X", "POST", URL,
         "-H", f"Authorization: Bearer {TOKEN}",
         "-H", "Content-Type: application/json",
         "-d", payload],
        capture_output=True, text=True, timeout=120
    )
    out = r.stdout.strip()
    if '"error"' in out or '"message"' in out:
        print(f"FAIL: {label} -> {out[:400]}")
        fail_count += 1
        return False
    print(f"OK: {label}")
    ok_count += 1
    return True

def O(o, a, d):
    """Build options JSON: optimal, acceptable, dangerous."""
    return json.dumps([
        {"text": o[0], "score": 100, "feedbackText": o[1]},
        {"text": a[0], "score": 0, "feedbackText": a[1]},
        {"text": d[0], "score": -100, "feedbackText": d[1]}
    ])

def E(s):
    """Escape single quotes for SQL."""
    return s.replace("'", "''")

def build_insert(rows):
    vals = []
    for loc, cat, sc, tip, op, diff in rows:
        vals.append(f"('{E(loc)}','{E(cat)}','{E(sc)}','{E(tip)}','{E(op)}',{diff},'claude-opus-4-6',true)")
    return "INSERT INTO questions (locale,category,scenario_text,mindset_tip,options,difficulty,generated_by,is_active) VALUES\n" + ",\n".join(vals) + ";"

Q = []  # all questions

# ===== ai-everyday DE =====
Q += [
("de","ai-everyday","Sie moechten mit ChatGPT einen Wochenplan fuer gesunde Mahlzeiten erstellen. Allerdings haben Sie Allergien gegen Nuesse und Laktose. Wie gehen Sie vor?","Je praeziser Ihre Angaben, desto besser das KI-Ergebnis — Kontext ist alles.",O(("Geben Sie alle Allergien, Vorlieben und Portionsgroessen direkt im ersten Prompt an und bitten um Einkaufsliste.","Perfekt! Detaillierte Angaben liefern sichere und passende Ergebnisse."),("Bitten Sie einfach um einen Wochenplan und pruefen danach manuell auf allergene Zutaten im Ergebnis.","Funktioniert, aber riskant — Sie koennten allergene Zutaten leicht uebersehen."),("Vertrauen Sie darauf, dass die KI automatisch Ihre Gesundheitsdaten kennt und Allergien beruecksichtigt.","Gefaehrlich! KI kennt Ihre Allergien nicht, wenn Sie sie nicht explizit nennen.")),1),
("de","ai-everyday","Sie planen eine Reise nach Japan und nutzen KI zur Reiseplanung. Die KI schlaegt Restaurants vor, die angeblich hervorragend bewertet sind. Wie verfahren Sie?","KI-Empfehlungen sind Ausgangspunkte — verifizieren Sie aktuelle Informationen immer extern.",O(("Nutzen Sie die Vorschlaege als Startpunkt und pruefen aktuelle Bewertungen auf Google Maps und TripAdvisor.","Genau richtig! KI-Vorschlaege immer mit aktuellen Quellen sorgfaeltig gegenchecken."),("Ignorieren Sie die KI-Vorschlaege komplett und planen die gesamte Reise ausschliesslich mit Reisefuehrern.","Moeglich, aber Sie verschenken nuetzliche Inspiration durch die KI-Vorschlaege dabei."),("Uebernehmen Sie die Empfehlungen direkt und buchen alle Restaurants ohne weitere Recherche vorab fest.","Riskant! KI-Daten koennen veraltet sein, Restaurants geschlossen oder komplett verlegt.")),1),
("de","ai-everyday","Ihre Tante bittet Sie, ein Foto fuer eine Einladungskarte zu verbessern. Sie moechten eine KI-App zur Bildbearbeitung nutzen. Worauf achten Sie?","Bildbearbeitungs-KI ist maechtig, aber Transparenz ueber KI-Nutzung wahrt Vertrauen und Respekt.",O(("Nutzen Sie die KI fuer dezente Verbesserungen und informieren Ihre Tante ueber die verwendete KI-Bearbeitung.","Vorbildlich! Dezente Verbesserung plus Transparenz ist der optimale und respektvolle Weg."),("Verzichten Sie auf KI und bearbeiten das Foto muehsam manuell mit einem einfachen kostenlosen Bildeditor.","Funktioniert, aber KI-Tools koennen bei realistischer Nutzung deutlich mehr Zeit sparen."),("Lassen Sie die KI das Gesicht komplett verjuengen und ueberraschen Ihre Tante mit dem tollen Ergebnis.","Problematisch! Starke Veraenderungen ohne Einwilligung verletzen die Persoenlichkeitsrechte.")),2),
("de","ai-everyday","Sie nutzen einen KI-Assistenten um Ihren Einkauf zu optimieren. Die KI schlaegt vor, Markenprodukte durch guenstigere Alternativen zu ersetzen.","KI kann beim Sparen helfen, aber persoenliche Qualitaetsansprueche bleiben stets Ihre Entscheidung.",O(("Pruefen Sie die Alternativvorschlaege einzeln, vergleichen Inhaltsstoffe und testen schrittweise neue Produkte.","Perfekt! Kritisches Pruefen der KI-Vorschlaege spart Geld ohne echten Qualitaetsverlust."),("Ignorieren Sie die Vorschlaege komplett und kaufen weiterhin ausschliesslich gewohnte Markenprodukte ein.","Verpasste Chance! Manche Alternativen sind tatsaechlich gleichwertig und deutlich guenstiger."),("Ersetzen Sie sofort alle Produkte durch die guenstigsten KI-Vorschlaege ohne weitere Pruefung der Qualitaet.","Riskant! Guenstig heisst nicht gleichwertig — Inhaltsstoffe koennen deutlich stark abweichen.")),1),
("de","ai-everyday","Sie moechten mit einer KI-App Ihre Wohnung umgestalten und laden ein Foto hoch. Die KI generiert einen beeindruckenden Designvorschlag. Was tun Sie?","KI-Designs inspirieren, aber physische Masse und Budget muessen Sie selbst sorgfaeltig pruefen.",O(("Nutzen Sie den Vorschlag als Inspiration, messen die Raeume nach und pruefen die Machbarkeit realistisch.","Genau richtig! KI-Designs sind Inspiration, die Umsetzung erfordert einen Realitaetscheck."),("Speichern Sie den Vorschlag ab, tun aber nichts weiter damit und belassen die Wohnung komplett unveraendert.","Schade! Der Vorschlag koennte mit Anpassungen durchaus umsetzbar und sehr wertvoll sein."),("Bestellen Sie sofort alle vorgeschlagenen Moebel online, bevor jemand anderes die gleiche Idee bekommt.","Gefaehrlich! Ohne Masse und Budgetcheck riskieren Sie teure Fehlkaeufe und aufwendige Retouren.")),2),
("de","ai-everyday","Ihr Sohn nutzt ChatGPT fuer seine Geburtstagseinladungen. Er moechte lustige personalisierte Texte fuer jeden Freund generieren. Welchen Rat geben Sie?","KI ist ein kreatives Werkzeug — der persoenliche Touch kommt immer vom Menschen selbst.",O(("Ermutigen Sie ihn, die KI-Texte als Basis zu nehmen und mit eigenen persoenlichen Details zu ergaenzen.","Perfekt! KI als Kreativhilfe nutzen und eigene Persoenlichkeit einbringen ist ideal."),("Lassen Sie ihn alle Texte komplett von der KI schreiben und direkt unveraendert an Freunde versenden.","Geht, aber die Texte koennten generisch wirken und den persoenlichen Touch leider vermissen."),("Verbieten Sie die KI-Nutzung komplett und bestehen darauf, dass er alles handschriftlich allein verfasst.","Uebertrieben! KI-Nutzung kindgerecht zu begleiten foerdert wichtige Zukunftskompetenzen.")),1),
("de","ai-everyday","Sie verwenden einen KI-Sprachassistenten im Auto, um waehrend der Fahrt Nachrichten zu diktieren. Die KI versteht Dialektausdruecke haeufig falsch.","Sprachassistenten lernen durch klare Kommunikation — Hochdeutsch erhoeht die Trefferquote enorm.",O(("Wechseln Sie bei Diktaten bewusst zu Hochdeutsch und lesen kritische Nachrichten vor dem Senden nochmals.","Klug! Klare Aussprache und Gegenlesen vermeiden peinliche Fehler sehr zuverlaessig."),("Deaktivieren Sie den Sprachassistenten komplett und tippen Nachrichten lieber manuell waehrend der Fahrt.","Gefaehrlich! Tippen waehrend der Fahrt ist wesentlich riskanter als gute Sprachsteuerung."),("Diktieren Sie weiter im Dialekt und senden Nachrichten direkt ohne jegliche Kontrolle an alle Empfaenger.","Riskant! Falsch erkannte Woerter koennen zu Missverstaendnissen oder peinlichen Situationen fuehren.")),2),
("de","ai-everyday","Sie nutzen eine KI-Fitness-App, die Ihnen einen personalisierten Trainingsplan erstellt. Nach einer Woche haben Sie starke Knieschmerzen.","KI-Fitnessplaene ersetzen keine medizinische Beratung — bei Schmerzen immer Profis fragen.",O(("Pausieren Sie den Plan sofort, konsultieren einen Arzt und passen danach die KI-Eingaben entsprechend an.","Richtig! Gesundheit geht vor — KI-Plaene brauchen medizinische Absicherung bei Beschwerden."),("Loeschen Sie die App sofort und kehren zu Ihrem alten Plan ohne jegliche KI-Unterstuetzung zurueck.","Verstaendlich, aber uebertrieben — nach aerztlicher Klaerung kann die KI-App hilfreich sein."),("Trainieren Sie trotz Schmerzen weiter, weil die KI den Plan bestimmt optimal berechnet haben muss.","Gefaehrlich! KI kennt Ihre koerperlichen Einschraenkungen nicht — ignorieren Sie Schmerzen nie.")),2),
("de","ai-everyday","Sie moechten mit einer KI ein Geschenk fuer Ihren Partner finden. Die KI fragt nach Vorlieben und Budget und schlaegt fuenf Optionen vor.","KI-Geschenkvorschlaege sind Denkanstoesse — die emotionale Komponente bestimmen nur Sie selbst.",O(("Waehlen Sie den Vorschlag der am besten passt und personalisieren ihn mit einer eigenen persoenlichen Note.","Perfekt! KI-Vorschlag als Basis plus persoenliche Note ergibt das ideale Geschenk."),("Kaufen Sie den erstbesten Vorschlag der KI ohne weitere Ueberlegung und verpacken ihn dann einfach schnell.","Funktioniert, aber ohne persoenliche Note wirkt das Geschenk moeglicherweise recht beliebig."),("Geben Sie der KI auch private Details wie Beziehungsprobleme fuer bessere personalisierte Vorschlaege.","Problematisch! Sensible Beziehungsdetails gehoeren nicht in KI-Chatverlaeufe hinein.")),1),
("de","ai-everyday","Sie nutzen eine KI-Uebersetzungs-App im Urlaub, um mit einem Arzt ueber ein gesundheitliches Problem zu sprechen. Wie setzen Sie die App ein?","Bei medizinischen Gespraechen ist Genauigkeit kritisch — KI ist Hilfe, nicht vollstaendiger Ersatz.",O(("Nutzen Sie die App als Verstaendigungshilfe und bitten zusaetzlich um einen professionellen Dolmetscher dazu.","Richtig! Bei medizinischen Themen ist professionelle Uebersetzung als Absicherung unverzichtbar."),("Verzichten Sie auf die App komplett und versuchen sich ausschliesslich mit Haenden und Fuessen verstaendlich.","Mutig, aber unpraktisch — die App kann zumindest grundlegende Verstaendigung deutlich erleichtern."),("Verlassen Sie sich komplett auf die KI-Uebersetzung und beschreiben alle Symptome detailliert per App.","Gefaehrlich! Uebersetzungsfehler bei medizinischen Begriffen koennen fatale Folgen haben.")),3),
]

# ===== ai-everyday EN =====
Q += [
("en","ai-everyday","You want to use ChatGPT to create a weekly meal plan for your family. Some members have severe food allergies. How do you approach this?","The more specific your prompts, the safer and more useful the AI output will be for everyone.",O(("Include all allergies, dietary preferences, and portion sizes in your initial prompt for accurate meal results.","Perfect! Detailed context ensures the AI generates safe and well-tailored meal plans."),("Ask for a generic meal plan and manually check each recipe afterwards for potential allergen ingredients.","Works but risky — you might overlook hidden allergens in complex recipes and ingredients."),("Trust the AI to automatically detect and avoid allergens based on your previous conversation history data.","Dangerous! AI does not remember your medical data unless you explicitly provide it each time.")),1),
("en","ai-everyday","You are planning a vacation to Italy and use an AI assistant for recommendations. It suggests a hotel that looks perfect. How do you proceed?","AI travel recommendations are starting points — always verify availability and current reviews independently.",O(("Use the AI suggestion as a starting point, then verify ratings on Booking.com and check recent reviews.","Smart approach! Cross-referencing AI suggestions with current reviews ensures quality and accuracy."),("Ignore the AI completely and spend hours manually searching through dozens of travel booking websites.","Possible but inefficient — AI suggestions can significantly speed up your initial research process."),("Book the hotel immediately based solely on the AI recommendation to secure the room before others.","Risky! AI data may be outdated — the hotel could be closed, renovated, or poorly managed now.")),1),
("en","ai-everyday","Your friend asks you to enhance their portrait photo using an AI editing app for their social media profile. What do you consider?","AI photo editing is powerful but transparency about modifications preserves trust and authenticity.",O(("Make subtle enhancements like lighting and color, and let your friend know which AI tools were used.","Perfect! Subtle improvements plus transparency is the responsible approach to AI photo editing."),("Refuse to use AI tools entirely and suggest they hire a professional photographer for a new session.","Valid option but overkill — AI tools can achieve great results for casual social media photos."),("Use AI to dramatically change their appearance — slimmer face, perfect skin — as a fun surprise.","Problematic! Significant alterations without consent can damage self-image and personal trust.")),2),
("en","ai-everyday","You are using an AI shopping assistant to find deals on electronics. It recommends a laptop from an unknown brand at half price. What do you do?","AI can find great deals, but verifying seller reputation and product quality remains your responsibility.",O(("Research the brand independently, read verified customer reviews, and check the return policy before buying.","Excellent! Due diligence on AI recommendations protects you from scams and poor quality products."),("Ignore the recommendation entirely and only buy from the most expensive well-known brand available online.","Safe but costly — some lesser-known brands genuinely offer good value with proper prior research."),("Buy it immediately since the AI found the best deal and must have compared all available options already.","Dangerous! AI may recommend unknown brands without verifying legitimacy or actual product quality.")),1),
("en","ai-everyday","You want to use AI to help redecorate your living room. You upload a photo and receive an impressive design suggestion. What is next?","AI designs inspire creativity, but real-world constraints like measurements and budget need human verification.",O(("Use the design as inspiration, measure your room carefully, and create a realistic budget before buying.","Smart! AI designs are great starting points but need real-world validation before any purchases."),("Save the design but never act on it because AI-generated interior designs are probably not practical.","Too dismissive! Many AI design suggestions are surprisingly practical with just minor adjustments."),("Order all suggested furniture immediately online to transform your room exactly as the AI design shows.","Risky! Without measuring first, furniture may not fit and returns are expensive and wasteful.")),2),
("en","ai-everyday","Your child wants to use an AI chatbot to help write a school essay about their summer vacation. How do you guide them through this?","AI is a creative tool for children too — guidance ensures they learn while using technology responsibly.",O(("Encourage them to use AI for brainstorming ideas, then write the essay in their own words and voice.","Perfect! Using AI for inspiration while maintaining authentic voice teaches responsible AI use."),("Forbid any AI use completely and insist they write everything from scratch using only printed resources.","Overly restrictive — teaching responsible AI use prepares children better for the modern future."),("Let them submit the AI-generated text directly as their own work without any personal modifications.","Wrong! Submitting AI text as own work is dishonest and undermines the learning objective entirely.")),1),
("en","ai-everyday","You use an AI voice assistant while driving to dictate text messages. The assistant frequently misinterprets words and names. How do you handle it?","Voice assistants work best with clear articulation — always review messages before sending them out.",O(("Speak clearly, use simple sentences, and always review the transcribed message before sending it out.","Correct! Clear speech and review prevent embarrassing autocorrect failures consistently each time."),("Stop using voice features entirely and type all messages manually while keeping one hand on the wheel.","Dangerous! Manual typing while driving is far riskier than using voice with proper review."),("Continue dictating naturally and send messages without checking because the AI is usually accurate enough.","Risky! Misinterpreted words can cause serious misunderstandings in professional and personal contexts.")),2),
("en","ai-everyday","You are using an AI fitness app that creates personalized workout plans. After a week, you experience persistent knee pain. What do you do?","AI fitness plans cannot replace medical advice — always listen to your body and consult professionals.",O(("Stop the workout immediately, see a doctor, and then adjust the AI settings based on medical advice.","Correct! Health always comes first — AI plans need human medical oversight when issues arise."),("Delete the app permanently and give up on structured training because AI fitness plans clearly fail.","Overreaction — after medical clearance, a properly adjusted AI plan can still be very helpful."),("Push through the pain because the AI algorithm must have calculated the optimal training intensity level.","Dangerous! AI cannot feel your pain or know your body — ignoring pain risks serious injury.")),2),
("en","ai-everyday","You want to use AI to find the perfect birthday gift for your partner. The AI suggests five options after asking preferences. How do you decide?","AI gift suggestions are helpful starting points — adding your personal touch makes the real difference.",O(("Choose the suggestion that fits best and add a personal touch like a handwritten note or customization.","Perfect! AI suggestion plus personal touch creates the ideal meaningful gift for someone special."),("Buy the first suggestion without thinking further because the AI probably analyzed it perfectly already.","Quick but impersonal — without your personal touch, the gift may feel generic and quite thoughtless."),("Share intimate relationship details with the AI to get even more personalized and accurate suggestions.","Problematic! Sensitive personal information should never be shared with AI chat systems at all.")),1),
("en","ai-everyday","You are abroad and use an AI translation app to communicate with a local doctor about a health concern. How do you use the app?","For medical conversations, AI translation is a helpful aid but should be supplemented with professional help.",O(("Use the app as a communication aid and also request a professional interpreter for medical accuracy.","Correct! Medical conversations require professional accuracy that AI alone simply cannot guarantee."),("Skip the app entirely and attempt to communicate through gestures and basic words without any tools.","Brave but impractical — the app can help significantly even if it is not perfectly accurate always."),("Rely entirely on the AI translation app to convey your symptoms and understand the diagnosis completely.","Dangerous! Translation errors in medical contexts can lead to misdiagnosis or wrong treatment.")),3),
]

# ===== ai-career DE =====
Q += [
("de","ai-career","Ihre Firma kuendigt an, KI-Tools fuer die Buchhaltung einzufuehren. Mehrere Kollegen befuerchten, ihren Job zu verlieren. Was raten Sie ihnen?","KI ersetzt selten ganze Jobs, aber veraendert fast jeden — Weiterbildung ist der beste Schutz.",O(("Empfehlen Sie, sich aktiv mit den neuen KI-Tools vertraut zu machen und Schulungen wahrzunehmen.","Richtig! Wer KI-Tools beherrscht, macht sich unersetzbar statt ersetzbar im Unternehmen."),("Beruhigen Sie die Kollegen mit dem Hinweis, dass KI noch lange nicht so weit sei und alles bleibe.","Zu optimistisch — Veraenderungen kommen schnell, Vorbereitung ist besser als Abwarten."),("Unterstuetzen Sie die Kollegen dabei, gemeinsam gegen die KI-Einfuehrung offiziell zu protestieren.","Kontraproduktiv! Widerstand gegen Innovation schadet der eigenen Karriere und dem ganzen Team.")),1),
("de","ai-career","Sie moechten sich auf eine neue Stelle bewerben und ueberlegen, ChatGPT fuer Ihr Anschreiben zu nutzen. Wie setzen Sie die KI ein?","KI kann Bewerbungen verbessern, aber Authentizitaet und persoenliche Erfahrungen sind entscheidend.",O(("Nutzen Sie ChatGPT fuer Struktur und Formulierungen, fuegen aber persoenliche Erfahrungen selbst hinzu.","Perfekt! KI als Schreibhilfe plus eigene Persoenlichkeit ergibt die staerkste Bewerbung."),("Schreiben Sie alles komplett selbst ohne KI-Hilfe, weil Bewerbungen authentisch handgeschrieben sein muessen.","Moeglich, aber Sie verschenken wertvolle Optimierungschancen durch professionelle KI-Unterstuetzung."),("Lassen Sie ChatGPT das komplette Anschreiben schreiben und senden es direkt ohne Aenderung ab.","Riskant! Generische KI-Texte werden von Recruitern erkannt und sofort aussortiert.")),1),
("de","ai-career","Ihr Chef bittet Sie, innerhalb einer Woche einen KI-Kurs zu absolvieren und die Ergebnisse dem Team zu praesentieren. Sie haben keine Erfahrung.","Lebenslanges Lernen ist im KI-Zeitalter keine Option, sondern Pflicht fuer Karriereerfolg.",O(("Starten Sie sofort mit einem strukturierten Online-Kurs und dokumentieren Ihre Lernfortschritte taeglich.","Richtig! Proaktives Lernen zeigt Initiative und baut schnell praxisrelevante KI-Kompetenz auf."),("Bitten Sie einen KI-erfahrenen Kollegen, die Praesentation fuer Sie vorzubereiten und zu halten stattdessen.","Verpasste Chance! Sie verpassen wichtige Lernmoeglichkeiten und wirken unselbststaendig dabei."),("Sagen Sie Ihrem Chef, dass KI-Kurse Zeitverschwendung sind und Sie wichtigere Aufgaben zu erledigen haben.","Karriereschaedigend! KI-Kompetenz wird zur Grundvoraussetzung in fast allen Berufsfeldern.")),2),
("de","ai-career","Ein Headhunter kontaktiert Sie ueber LinkedIn. Er nutzt offensichtlich KI-generierte Nachrichten. Wie gehen Sie mit dieser Situation professionell um?","KI-generierte Nachrichten sind die neue Normalitaet — beurteilen Sie den Inhalt, nicht das Werkzeug.",O(("Antworten Sie professionell auf den Inhalt und fragen gezielt nach konkreten Details zur ausgeschriebenen Stelle.","Klug! Den Inhalt bewerten statt das Werkzeug — KI-Nutzung ist im Recruiting voellig normal."),("Ignorieren Sie die Nachricht komplett, weil KI-generierte Anschreiben unserioes und respektlos wirken.","Voreilig! Viele serioese Recruiter nutzen KI-Tools fuer die Erstansprache ganz professionell."),("Antworten Sie mit einer ebenfalls KI-generierten Standardantwort ohne die Nachricht gelesen zu haben.","Unprofessionell! Automatische Antworten ohne inhaltliche Pruefung verspielen echte Karrierechancen.")),2),
("de","ai-career","Sie bereiten sich auf eine Gehaltsverhandlung vor und moechten KI nutzen, um Ihre Argumentation zu staerken. Wie setzen Sie KI strategisch ein?","KI liefert Daten und Argumente — die Verhandlung fuehren muessen Sie selbst mit Ueberzeugung.",O(("Nutzen Sie KI fuer Gehaltsrecherche, Argumentationsstruktur und ueben Sie mit einem KI-Rollenspiel.","Perfekt! KI als Vorbereitungstool nutzen staerkt Ihre Position und Ihr Selbstvertrauen."),("Verlassen Sie sich auf Ihr Bauchgefuehl und verhandeln spontan ohne jegliche KI-gestuetzte Vorbereitung.","Riskant! Ohne Daten und Struktur verlieren Sie schnell die Verhandlungsposition gegenueber Vorgesetzten."),("Lassen Sie ChatGPT eine E-Mail an Ihren Chef schreiben, in der die KI eine Gehaltserhoehung fordert.","Gefaehrlich! Gehaltsverhandlungen per KI-generierter E-Mail wirken unpersoenlich und respektlos.")),2),
("de","ai-career","Ihre Kollegin nutzt KI-Tools intensiv und erledigt Aufgaben doppelt so schnell. Ihr Vorgesetzter bemerkt den Unterschied. Wie reagieren Sie?","KI-Kompetenz ist eine Faehigkeit wie jede andere — wer frueh lernt, hat den groessten Vorteil.",O(("Bitten Sie Ihre Kollegin um Tipps, welche KI-Tools sie nutzt, und investieren Sie Zeit in eigene Schulung.","Perfekt! Von Kolleginnen lernen und eigene KI-Kompetenz aufbauen ist die kluge Strategie."),("Arbeiten Sie laenger und haerter, um den Produktivitaetsunterschied durch mehr Arbeitsstunden auszugleichen.","Nicht nachhaltig! Mehr Stunden kompensieren nicht den strategischen Vorteil durch KI-Tools."),("Beschweren Sie sich beim Vorgesetzten, dass KI-Nutzung unfair ist und verboten werden sollte fuer alle.","Kontraproduktiv! KI-Tools werden zum Standard — Widerstand schadet nur Ihrer eigenen Karriere.")),1),
("de","ai-career","Sie sind Teamleiter und sollen entscheiden, ob Ihr Team KI-Tools fuer das Projektmanagement einsetzen darf. Wie treffen Sie die Entscheidung?","Erfolgreiche KI-Einfuehrung erfordert Pilotphasen und Feedback — nicht alles auf einmal aendern.",O(("Starten Sie ein Pilotprojekt mit freiwilligen Teammitgliedern, evaluieren Ergebnisse und skalieren dann.","Vorbildlich! Pilotprojekte minimieren Risiken und schaffen Akzeptanz durch messbare Erfolge."),("Warten Sie ab, bis andere Teams im Unternehmen KI-Tools getestet haben, bevor Sie selbst handeln.","Zu passiv! Fruehe Adopter gewinnen wertvolle Erfahrungen und positionieren ihr Team besser."),("Fuehren Sie KI-Tools sofort fuer alle Teammitglieder verpflichtend ein ohne vorherige Testphase.","Riskant! Uebereilte Einfuehrung ohne Schulung und Pilotphase erzeugt Widerstand und viele Fehler.")),3),
("de","ai-career","Ihr Lebenslauf wird bei Online-Bewerbungen staendig abgelehnt. Ein Freund schlaegt vor, KI fuer die Optimierung zu nutzen. Wie gehen Sie vor?","KI kann Lebenslaeufe ATS-konform optimieren — aber Ehrlichkeit bleibt die wichtigste Regel.",O(("Nutzen Sie KI um Keywords zu optimieren und das Format ATS-konform zu gestalten, bleiben aber ehrlich.","Perfekt! ATS-Optimierung mit KI ist schlau, solange alle Angaben wahrheitsgetreu bleiben."),("Ueberarbeiten Sie den Lebenslauf komplett selbst ohne KI, weil Sie misstrauen was KI da einbaut.","Moeglich, aber ATS-Systeme haben spezifische Anforderungen, die KI effizient adressieren kann."),("Lassen Sie die KI erfundene Qualifikationen und uebertriebene Erfahrungen in den Lebenslauf schreiben.","Gefaehrlich! Gefaelschte Angaben fuehren zu sofortiger Kuendigung und Reputationsschaden.")),2),
("de","ai-career","Ein Kollege nutzt KI heimlich und gibt die Ergebnisse als eigene Leistung aus. Sie bemerken es zufaellig. Was tun Sie in dieser Situation?","Transparenz ueber KI-Nutzung ist professionelle Pflicht — heimliche Nutzung untergaebt Vertrauen.",O(("Sprechen Sie den Kollegen freundlich an und ermutigen ihn, die KI-Nutzung offen zu kommunizieren.","Richtig! Offene KI-Nutzung ist legitim — das Problem ist die Heimlichkeit, nicht das Tool."),("Ignorieren Sie es komplett, weil es Sie nichts angeht, wie andere ihre Arbeit erledigen oder organisieren.","Riskant! Wenn das Team glaubt, er leiste alles allein, entsteht eine unfaire Erwartungshaltung."),("Melden Sie den Kollegen sofort beim Vorgesetzten und fordern disziplinarische Konsequenzen gegen ihn.","Uebertrieben! Ein Gespraech unter Kollegen ist der bessere erste Schritt als sofortige Eskalation.")),3),
("de","ai-career","Sie moechten sich beruflich umorientieren und in den Bereich KI-Beratung wechseln. Wie bereiten Sie den Karrierewechsel sinnvoll vor?","Ein Karrierewechsel in den KI-Bereich erfordert sowohl technisches als auch strategisches Wissen.",O(("Erwerben Sie KI-Zertifikate, bauen ein Portfolio mit Praxisprojekten auf und vernetzen sich aktiv.","Perfekt! Kombination aus Zertifikaten, Praxis und Netzwerk ist der staerkste Karrierehebel."),("Bewerben Sie sich direkt auf KI-Beraterstellen und lernen alles Noetige dann einfach direkt im Job.","Riskant! Ohne Grundlagen fehlt das Fundament fuer glaubwuerdige Beratung und Praxiskompetenz."),("Warten Sie ab, ob der KI-Hype anhaelt, bevor Sie Zeit und Geld in eine Umschulung investieren.","Verpasste Chance! KI ist kein Hype, sondern struktureller Wandel — fruehe Positionierung zahlt sich aus.")),2),
]

# ===== ai-career EN =====
Q += [
("en","ai-career","Your company announces it will implement AI tools for accounting tasks. Several colleagues fear losing their jobs. What advice do you give?","AI rarely replaces entire jobs but changes almost every one — continuous learning is the best protection.",O(("Recommend they proactively learn the new AI tools and attend every available training session offered.","Correct! Those who master AI tools become indispensable rather than replaceable in the workplace."),("Reassure them that AI is still far from replacing humans and everything will stay exactly the same.","Too optimistic — changes come fast, and preparation is always better than waiting passively."),("Support them in organizing a formal protest against the AI implementation within the company.","Counterproductive! Resistance to innovation harms your career and damages the entire team.")),1),
("en","ai-career","You want to apply for a new position and consider using ChatGPT for your cover letter. How do you use the AI tool effectively?","AI can improve applications, but authenticity and personal experiences are what truly make the difference.",O(("Use ChatGPT for structure and phrasing, but add your personal experiences and achievements yourself.","Perfect! AI as a writing aid plus personal authenticity creates the strongest possible application."),("Write everything completely by yourself without AI help because applications must be fully handwritten.","Possible, but you miss valuable optimization opportunities through professional AI-powered assistance."),("Let ChatGPT write the complete cover letter and send it directly without any changes or personalization.","Risky! Generic AI texts are recognized by experienced recruiters and immediately filtered out.")),1),
("en","ai-career","Your boss asks you to complete an AI course within one week and present results to the team. You have no prior AI experience. What do you do?","Lifelong learning is not optional in the AI age — it is essential for sustained career success.",O(("Start immediately with a structured online course and document your learning progress every single day.","Correct! Proactive learning shows initiative and quickly builds practical AI competence for work."),("Ask an AI-experienced colleague to prepare and deliver the presentation on your behalf to the team.","Missed opportunity! You miss important learning moments and appear unable to work independently."),("Tell your boss that AI courses are a waste of time and you have more important tasks to focus on.","Career-damaging! AI competence is becoming a basic requirement in virtually every professional field.")),2),
("en","ai-career","A recruiter contacts you on LinkedIn using obviously AI-generated messages. How do you handle this situation professionally and effectively?","AI-generated messages are the new normal — judge the content and opportunity, not the tool used.",O(("Respond professionally to the content and ask specific questions about the role and company details.","Smart! Evaluating content over tools is pragmatic — AI usage in recruiting is completely normal."),("Ignore the message completely because AI-generated outreach is disrespectful and inherently unprofessional.","Premature! Many legitimate recruiters use AI tools professionally for initial candidate outreach."),("Reply with your own AI-generated standard response without actually reading the original message content.","Unprofessional! Automatic replies without reading the content waste real career opportunities forever.")),2),
("en","ai-career","You are preparing for a salary negotiation and want to use AI to strengthen your arguments. How do you use AI strategically here?","AI provides data and arguments — but you must lead the negotiation yourself with genuine confidence.",O(("Use AI for salary research, argument structure, and practice through AI-powered role-playing scenarios.","Perfect! AI as a preparation tool strengthens your position and builds negotiation confidence."),("Rely on gut feeling and negotiate spontaneously without any AI-assisted preparation or market research.","Risky! Without data and structure, you quickly lose your negotiation position against management."),("Have ChatGPT write an email to your boss demanding a raise on your behalf without personal conversation.","Dangerous! Salary negotiations via AI-generated email appear impersonal and disrespectful to managers.")),2),
("en","ai-career","Your colleague uses AI tools extensively and completes tasks twice as fast as you. Your manager notices the difference. How do you respond?","AI competence is a skill like any other — those who learn early gain the greatest competitive advantage.",O(("Ask your colleague for tips on which AI tools they use and invest dedicated time in your own training.","Perfect! Learning from colleagues and building your own AI competence is the smartest strategy."),("Work longer and harder hours to compensate for the productivity difference through sheer effort alone.","Not sustainable! More hours cannot compensate for the strategic advantage that AI tools provide."),("Complain to your manager that AI usage is unfair and should be prohibited for all team members.","Counterproductive! AI tools are becoming standard — resistance only harms your own career advancement.")),1),
("en","ai-career","You are a team leader deciding whether your team should adopt AI tools for project management. How do you approach this decision?","Successful AI adoption requires pilot phases and feedback loops — never change everything at once.",O(("Start a pilot project with volunteer team members, evaluate the results carefully, then scale gradually.","Exemplary! Pilot projects minimize risks and build acceptance through measurable and demonstrable success."),("Wait until other teams in the company have tested AI tools before taking any action yourself.","Too passive! Early adopters gain valuable experience and position their teams ahead of the competition."),("Mandate AI tools immediately for all team members without any prior testing or training phase.","Risky! Rushed implementation without training and piloting creates resistance, errors, and frustration.")),3),
("en","ai-career","Your resume keeps getting rejected by online application systems. A friend suggests using AI for optimization. How do you proceed?","AI can optimize resumes for ATS systems — but honesty remains the most important rule of all.",O(("Use AI to optimize keywords and format for ATS compatibility while keeping all information truthful.","Perfect! ATS optimization with AI is smart as long as all qualifications remain completely honest."),("Rework the resume entirely by yourself without AI because you distrust what AI might add automatically.","Possible, but ATS systems have specific requirements that AI can address much more efficiently."),("Let the AI add fabricated qualifications and exaggerated experience to make your resume stand out.","Dangerous! Falsified credentials lead to immediate termination and severe reputational damage.")),2),
("en","ai-career","A colleague secretly uses AI to complete their work and presents results as their own solo achievement. You notice this by accident. What do you do?","Transparency about AI usage is a professional duty — secretive use undermines trust within teams.",O(("Speak to your colleague privately and encourage them to openly communicate their AI usage to everyone.","Correct! Open AI usage is legitimate — the problem is secrecy, not the tool itself in this case."),("Ignore it completely because it is none of your business how other people organize their own work.","Risky! If the team believes they do everything alone, unfair expectations arise for everyone else."),("Report the colleague immediately to management and demand formal disciplinary consequences against them.","Excessive! A private conversation between colleagues is a much better first step than escalation.")),3),
("en","ai-career","You want to pivot your career into AI consulting. How do you prepare for this professional transition effectively and strategically?","A career switch into AI requires both technical knowledge and strategic business understanding together.",O(("Earn AI certifications, build a portfolio with practical projects, and actively network with professionals.","Perfect! Combining certifications, hands-on practice, and networking is the strongest career lever."),("Apply directly for AI consulting positions and plan to learn everything you need on the job itself.","Risky! Without foundational knowledge, you lack the credibility needed for professional AI consulting."),("Wait to see if the AI trend persists before investing any time or money into retraining or education.","Missed opportunity! AI is not a trend but structural change — early positioning pays significant dividends.")),2),
]

# ===== ai-communication DE =====
Q += [
("de","ai-communication","Ihr Vorgesetzter bittet Sie, eine wichtige Kunden-E-Mail zu verfassen. Sie moechten ChatGPT zur Hilfe nehmen. Wie setzen Sie KI professionell ein?","KI-E-Mails klingen oft generisch — Ihr persoenlicher Stil und Kontext machen den echten Unterschied.",O(("Lassen Sie ChatGPT einen Entwurf erstellen, passen Tonalitaet an und fuegen kundenspezifische Details ein.","Perfekt! KI-Entwurf plus persoenliche Anpassung ergibt eine professionelle und authentische E-Mail."),("Schreiben Sie die E-Mail komplett selbst, weil KI-Texte angeblich immer als generisch erkannt werden.","Moeglich, aber KI kann als Sparringspartner fuer Struktur und Formulierungen sehr hilfreich sein."),("Kopieren Sie den ChatGPT-Text direkt in die E-Mail und senden ihn ohne jegliche Anpassung sofort ab.","Riskant! Generische KI-Texte wirken unpersoenlich und koennen Kundenbeziehungen nachhaltig beschaedigen.")),1),
("de","ai-communication","Sie muessen ein einstuendiges Teammeeting zusammenfassen. Ein Kollege schlaegt KI-Transkription und automatische Zusammenfassung vor.","KI-Transkription spart enorm Zeit, erfordert aber Einwilligung aller Teilnehmenden vorher.",O(("Holen Sie vorher die Zustimmung aller Teilnehmer ein und pruefen die KI-Zusammenfassung auf Richtigkeit.","Vorbildlich! Datenschutz plus Qualitaetskontrolle ist der professionelle Umgang mit KI-Transkription."),("Fassen Sie das Meeting weiterhin manuell zusammen, weil KI-Transkription zu ungenau sein koennte.","Moeglich, aber KI-Transkription ist inzwischen sehr zuverlaessig und spart erheblich viel Zeit."),("Starten Sie die KI-Aufnahme ohne Ankuendigung, weil Effizienz wichtiger ist als formale Zustimmung.","Illegal! Heimliche Aufnahmen verletzen Datenschutzgesetze und zerstoeren Vertrauen im Team.")),2),
("de","ai-communication","Sie bereiten eine wichtige Praesentation fuer den Vorstand vor. KI-Tools bieten automatisch generierte Folien an. Wie nutzen Sie diese Moeglichkeit?","KI-generierte Folien sind Startpunkte — Ihre Expertise und Storytelling machen sie ueberzeugend.",O(("Nutzen Sie KI-Folien als Grundgeruest und verfeinern Inhalte, Design und Argumentation selbst sorgfaeltig.","Perfekt! KI-Grundgeruest plus eigene Expertise ergibt eine ueberzeugende Vorstandspraesentation."),("Erstellen Sie alle Folien komplett manuell, weil KI-generierte Praesentationen immer gleich aussehen.","Moeglich, aber KI kann erheblich Zeit beim Entwurf sparen, die Sie in Inhalte investieren."),("Uebernehmen Sie die KI-generierten Folien direkt ohne Aenderungen und praesentieren sie dem Vorstand.","Riskant! Generische KI-Folien ohne individuelle Anpassung ueberzeugen keinen erfahrenen Vorstand.")),2),
("de","ai-communication","Ein Kunde beschwert sich per E-Mail sehr emotional. Sie moechten KI nutzen, um eine deeskalierende Antwort zu formulieren. Ist das angemessen?","KI kann bei schwierigen Nachrichten helfen, den richtigen Ton zu treffen und professionell zu bleiben.",O(("Nutzen Sie KI fuer einen deeskalierenden Entwurf und ergaenzen persoenliches Verstaendnis und spezifische Details.","Richtig! KI hilft den Ton zu finden, persoenliche Empathie macht die Antwort dann authentisch."),("Antworten Sie dem Kunden spontan aus dem Bauch heraus, weil authentische Emotionen wichtiger als KI sind.","Riskant! Emotionale Spontanantworten koennen die Situation verschlimmern statt zu beruhigen."),("Lassen Sie die KI eine Standardantwort generieren und senden sie ohne jegliche Personalisierung sofort.","Problematisch! Standardantworten auf emotionale Beschwerden wirken ignorant und verstaerken Aerger.")),2),
("de","ai-communication","Sie sollen einen Newsletter fuer 5000 Kunden schreiben. Ein Kollege schlaegt KI fuer personalisierte Anreden und Inhalte vor. Was beachten Sie?","KI-Personalisierung steigert Engagement, erfordert aber sorgfaeltigen Umgang mit Kundendaten.",O(("Pruefen Sie zuerst Datenschutzkonformitaet, nutzen dann KI fuer Personalisierung mit genehmigten Daten.","Perfekt! Datenschutz zuerst, dann KI-Personalisierung — so entstehen effektive und legale Newsletter."),("Schreiben Sie einen identischen Newsletter fuer alle Kunden ohne jegliche Personalisierung durch KI-Tools.","Funktioniert, aber niedrigere Oeffnungsraten — Personalisierung steigert Engagement deutlich messbar."),("Fuettern Sie die KI mit allen verfuegbaren Kundendaten fuer maximale Personalisierung ohne jede Pruefung.","Gefaehrlich! Ungepruefter Datentransfer an KI-Tools kann massive Datenschutzverletzungen verursachen.")),3),
("de","ai-communication","Ihr internationales Team kommuniziert in vier Sprachen. KI-Uebersetzungstools koennten helfen, aber Sie sorgen sich um Nuancen.","KI-Uebersetzung ist fuer den Alltag gut genug — bei wichtigen Dokumenten braucht es menschliche Kontrolle.",O(("Nutzen Sie KI-Uebersetzung fuer alltaegliche Kommunikation und lassen wichtige Dokumente menschlich pruefen.","Klug! Abgestufte Nutzung spart Zeit bei Routine und sichert Qualitaet bei wichtigen Texten."),("Bestehen Sie darauf, dass alle ausschliesslich Englisch sprechen, um Uebersetzungsprobleme zu vermeiden.","Problematisch! Sprachzwang schafft Barrieren und benachteiligt Muttersprachler anderer Sprachen."),("Uebersetzen Sie alles nur mit KI ohne jede menschliche Pruefung, weil die Tools inzwischen perfekt sind.","Riskant! KI-Uebersetzungen koennen kulturelle Nuancen und Fachbegriffe falsch wiedergeben.")),2),
("de","ai-communication","Sie muessen ein schwieriges Feedbackgespraech mit einem Mitarbeiter fuehren. KI koennte beim Formulieren helfen. Wie bereiten Sie sich vor?","KI kann sachliche Formulierungen liefern — echte Empathie und aktives Zuhoeren kommen von Ihnen.",O(("Nutzen Sie KI fuer sachliche Formulierungsvorschlaege und bereiten sich emotional auf das Gespraech vor.","Richtig! KI-Formulierungen plus echte Empathie ergibt ein professionelles Feedbackgespraech."),("Fuehren Sie das Gespraech komplett spontan, weil vorbereitete Saetze kuenstlich und unnatuerlich wirken.","Riskant! Ohne Vorbereitung koennen schwierige Gespraeche schnell eskalieren oder verletzen."),("Lesen Sie dem Mitarbeiter die KI-generierten Feedback-Saetze wortwortlich von Ihrem Bildschirm ab.","Entmenschlichend! Abgelesenes KI-Feedback zerstoert Vertrauen und wirkt respektlos gegenueber Mitarbeitern.")),3),
("de","ai-communication","Sie posten regelmaessig auf LinkedIn und ueberlegen, KI fuer Ihre Beitraege zu nutzen. Wie bewahren Sie Ihre Authentizitaet dabei?","KI kann LinkedIn-Content verbessern, aber Ihre persoenliche Stimme und Erfahrungen sind unersetzlich.",O(("Nutzen Sie KI fuer Ideenfindung und Strukturierung, schreiben den finalen Text aber in Ihrem eigenen Stil.","Perfekt! KI als Kreativpartner nutzen und eigene Stimme bewahren ist die beste Content-Strategie."),("Schreiben Sie alles komplett selbst ohne jede KI-Hilfe, weil echte Authentizitaet keine Tools braucht.","Moeglich, aber KI-Unterstuetzung bei Ideenfindung und Struktur kann Ihre Reichweite steigern."),("Lassen Sie alle LinkedIn-Posts komplett von KI schreiben und posten sie taeglich vollautomatisiert.","Problematisch! Reine KI-Posts sind erkennbar generisch und untergraben Ihre persoenliche Marke.")),1),
("de","ai-communication","Ein Kunde ruft wuetend wegen einer verspaeteten Lieferung an. Ihr CRM schlaegt eine KI-generierte Antwort vor. Wie reagieren Sie am Telefon?","Am Telefon zaehlt Menschlichkeit — KI-Vorschlaege sind Orientierung, nicht Ihr Skript zum Ablesen.",O(("Nutzen Sie den KI-Vorschlag als Orientierung, hoeren dem Kunden aktiv zu und antworten persoenlich.","Richtig! KI als Leitfaden plus aktives Zuhoeren schafft die beste Kundenerfahrung am Telefon."),("Ignorieren Sie den KI-Vorschlag komplett und improvisieren das gesamte Gespraech aus dem Bauch heraus.","Riskant! Ohne strukturierte Leitlinie koennen schwierige Kundengespraeche schnell eskalieren."),("Lesen Sie die KI-generierte Antwort wortwortlich vom Bildschirm ab, waehrend der Kunde noch spricht.","Katastrophal! Abgelesene Standardsaetze bei wuetenden Kunden verschlimmern die Situation erheblich.")),2),
("de","ai-communication","Sie sollen eine Pressemitteilung fuer Ihr Unternehmen schreiben. Die Marketingabteilung schlaegt KI fuer den ersten Entwurf vor. Was beachten Sie?","KI-Entwuerfe brauchen immer eine redaktionelle Pruefung — besonders bei oeffentlichen Dokumenten.",O(("Erstellen Sie einen KI-Entwurf, pruefen Fakten, passen den Stil an und lassen alles vom Team freigeben.","Perfekt! KI-Entwurf plus gruendliche Pruefung und Freigabe ist der professionelle Standardprozess."),("Schreiben Sie die Pressemitteilung komplett manuell, weil oeffentliche Dokumente keine KI-Hilfe brauchen.","Moeglich, aber ein KI-Erstentwurf kann wertvolle Zeit sparen, die in Qualitaetspruefung fliesst."),("Lassen Sie die KI die Pressemitteilung erstellen und veroeffentlichen sie direkt ohne interne Freigabe.","Gefaehrlich! Ungepruefter KI-Text in Pressemitteilungen kann Fehlinformationen weit verbreiten.")),2),
]

# ===== ai-communication EN =====
Q += [
("en","ai-communication","Your manager asks you to write an important client email. You want to use ChatGPT for assistance. How do you use AI professionally?","AI emails often sound generic — your personal style and specific context make the real difference.",O(("Have ChatGPT draft a version, then adjust the tone and add client-specific details before sending.","Perfect! AI draft plus personal adjustments creates a professional and authentic client email."),("Write the email completely by yourself because AI-generated texts are always recognized as generic.","Possible, but AI can serve as a great sparring partner for structure and professional formulations."),("Copy the ChatGPT text directly into the email and send it without any adjustments or personalization.","Risky! Generic AI texts appear impersonal and can permanently damage important client relationships.")),1),
("en","ai-communication","You need to summarize a one-hour team meeting. A colleague suggests using AI transcription and summarization tools. What do you consider?","AI transcription saves enormous time but requires consent from all participants beforehand always.",O(("Obtain consent from all participants first and review the AI summary carefully for accuracy afterwards.","Exemplary! Privacy compliance plus quality control is the professional approach to AI transcription."),("Continue summarizing meetings manually because AI transcription might be too inaccurate for important notes.","Possible, but modern AI transcription is very reliable and saves considerable time for everyone."),("Start AI recording without any announcement because efficiency matters more than formal consent processes.","Illegal! Secret recordings violate privacy laws and destroy trust within the entire team permanently.")),2),
("en","ai-communication","You are preparing an important board presentation. AI tools offer automatically generated slides. How do you use this capability?","AI-generated slides are starting points — your expertise and storytelling make them truly convincing.",O(("Use AI slides as a framework and carefully refine the content, design, and argumentation yourself.","Perfect! AI framework plus your own expertise creates a convincing board presentation every time."),("Create all slides completely manually because AI-generated presentations always look exactly the same.","Possible, but AI can save significant time on drafting that you can invest in content quality."),("Use the AI-generated slides directly without any changes and present them to the board as final.","Risky! Generic AI slides without individual customization will never convince an experienced board.")),2),
("en","ai-communication","A customer sends a very emotional complaint email. You want to use AI to craft a de-escalating response. Is this appropriate?","AI can help find the right tone for difficult messages while you add genuine personal empathy.",O(("Use AI for a de-escalating draft and add personal understanding and specific details to the response.","Correct! AI helps find the right tone, and your personal empathy makes the response authentic."),("Reply spontaneously from your gut because authentic emotions are more important than AI-crafted words.","Risky! Emotional spontaneous replies can worsen the situation significantly instead of calming it."),("Have AI generate a standard response and send it immediately without any personalization or adjustments.","Problematic! Standard responses to emotional complaints appear ignorant and increase customer anger.")),2),
("en","ai-communication","You need to write a newsletter for five thousand customers. A colleague suggests using AI for personalized greetings. What do you consider?","AI personalization boosts engagement but requires careful handling of customer data and privacy.",O(("Check data privacy compliance first, then use AI for personalization with only approved customer data.","Perfect! Privacy first, then AI personalization — this creates effective and legally compliant newsletters."),("Write one identical newsletter for all customers without any personalization or AI assistance whatsoever.","Works, but lower open rates — personalization measurably increases engagement across all customer segments."),("Feed all available customer data into the AI for maximum personalization without any compliance checks.","Dangerous! Unchecked data transfer to AI tools can cause massive data privacy violations and fines.")),3),
("en","ai-communication","Your international team communicates in four languages. AI translation tools could help, but you worry about nuances being lost.","AI translation works well for daily communication — important documents still need human review always.",O(("Use AI translation for everyday communication and have important documents reviewed by human translators.","Smart! Graduated usage saves time on routine messages while ensuring quality for important texts."),("Insist that everyone communicates exclusively in English to avoid any translation problems whatsoever.","Problematic! Language mandates create barriers and disadvantage non-native English speakers unfairly."),("Translate everything using only AI without any human review because these tools are now essentially perfect.","Risky! AI translations can misinterpret cultural nuances and technical terminology in serious ways.")),2),
("en","ai-communication","You need to deliver difficult performance feedback to a team member. AI could help with phrasing. How do you prepare for this?","AI can provide objective phrasing — genuine empathy and active listening must come from you personally.",O(("Use AI for objective phrasing suggestions and emotionally prepare yourself for the actual conversation.","Correct! AI phrasing plus genuine empathy creates a professional and effective feedback conversation."),("Conduct the conversation completely spontaneously because prepared sentences always sound artificial.","Risky! Without preparation, difficult conversations can quickly escalate or unintentionally cause harm."),("Read the AI-generated feedback sentences word-for-word from your screen during the actual conversation.","Dehumanizing! Reading AI feedback verbatim destroys trust and shows disrespect to the team member.")),3),
("en","ai-communication","You regularly post on LinkedIn and consider using AI for your content. How do you use AI without losing your authentic voice?","AI can enhance LinkedIn content, but your personal voice and real experiences are truly irreplaceable.",O(("Use AI for brainstorming and structuring ideas, but write the final text in your own personal style.","Perfect! AI as a creative partner while preserving your voice is the best content strategy overall."),("Write everything entirely by yourself without any AI help because true authenticity needs no tools.","Possible, but AI support for ideation and structure can meaningfully increase your overall reach."),("Have AI write all LinkedIn posts completely and publish them daily through automated scheduling tools.","Problematic! Pure AI posts are recognizably generic and systematically undermine your personal brand.")),1),
("en","ai-communication","A customer calls angry about a delayed delivery. Your CRM suggests an AI-generated response script. How do you handle the call?","On the phone, humanity matters most — AI suggestions are guidance, not your script to read aloud.",O(("Use the AI suggestion as guidance, actively listen to the customer, and respond with personal empathy.","Correct! AI as a guide plus active listening creates the best possible customer experience overall."),("Ignore the AI suggestion completely and improvise the entire conversation based purely on gut instinct.","Risky! Without structured guidance, difficult customer conversations can escalate out of control quickly."),("Read the AI-generated response word-for-word from the screen while the customer is still speaking.","Catastrophic! Reading scripted responses to angry customers dramatically worsens the entire situation.")),2),
("en","ai-communication","You need to write a press release for your company. Marketing suggests using AI for the first draft. What do you keep in mind?","AI drafts always need editorial review — especially for public-facing documents and official communications.",O(("Create an AI draft, fact-check thoroughly, adjust the style, and get team approval before publishing.","Perfect! AI draft plus thorough review and approval is the professional standard process always."),("Write the press release completely manually because public documents should never involve AI assistance.","Possible, but an AI first draft can save valuable time that you can invest in quality review."),("Have AI create the press release and publish it directly without any internal review or team approval.","Dangerous! Unreviewed AI text in press releases can spread misinformation and damage your reputation.")),2),
]

# ===== REMAINING CATEGORIES - compact format =====
# ai-tools-comparison, ai-customer-service, ai-finance, ai-health, ai-education, ai-manufacturing, ai-public-sector, ai-media-content, ai-sustainability, ai-psychology, ai-myths-facts
# Each: 10 DE + 10 EN

# ai-tools-comparison DE
Q += [
("de","ai-tools-comparison","Sie muessen einen langen Vertrag analysieren und die wichtigsten Klauseln zusammenfassen. Welches KI-Tool waehlen Sie und warum?","Claude eignet sich besonders fuer lange Dokumente — aber kein KI-Tool ersetzt juristischen Rat.",O(("Nutzen Sie Claude fuer die Analyse langer Texte und lassen die Zusammenfassung von einem Juristen pruefen.","Richtig! Claude hat ein grosses Kontextfenster fuer Dokumente, aber juristischer Rat bleibt Pflicht."),("Verwenden Sie ausschliesslich Google-Suche, weil KI-Tools fuer juristische Dokumente ungeeignet sind.","Moeglich, aber KI-Tools koennen die Voranalyse erheblich beschleunigen und Zeit sparen."),("Lassen Sie ChatGPT den Vertrag analysieren und unterschreiben sofort basierend auf der KI-Zusammenfassung.","Gefaehrlich! Keine KI-Zusammenfassung ersetzt juristische Expertise bei vertraglichen Entscheidungen.")),2),
("de","ai-tools-comparison","Ihr Team debattiert, ob ChatGPT, Claude oder Gemini fuer taegliche E-Mail-Kommunikation am besten geeignet ist. Wie entscheiden Sie?","Das beste KI-Tool haengt vom Anwendungsfall ab — testen Sie mehrere und waehlen situativ.",O(("Testen Sie alle drei Tools mit typischen E-Mails aus Ihrem Alltag und vergleichen Qualitaet und Effizienz.","Perfekt! Praxistests mit echten Aufgaben liefern die zuverlaessigste Entscheidungsgrundlage fuer Teams."),("Waehlen Sie einfach ChatGPT, weil es das bekannteste Tool ist und die meisten Nutzer weltweit hat.","Voreilig! Bekanntheit bedeutet nicht Eignung — verschiedene Tools haben verschiedene Staerken."),("Verbieten Sie alle KI-Tools fuer E-Mails, weil verschiedene Tools im Team nur unnoetig Chaos verursachen.","Kontraproduktiv! KI-Vielfalt kann Innovation foerdern, wenn klare Richtlinien dafuer existieren.")),1),
("de","ai-tools-comparison","Sie moechten Code fuer eine Webanwendung schreiben lassen. Copilot, ChatGPT und Claude stehen zur Verfuegung. Wie entscheiden Sie sich?","Copilot glaenzt bei Code-Integration, ChatGPT und Claude bei komplexer Logik und Erklaerungen.",O(("Nutzen Sie Copilot fuer Code-Vervollstaendigung im Editor und ChatGPT oder Claude fuer Architektur-Fragen.","Richtig! Kombination der Staerken verschiedener Tools maximiert Ihre Entwicklungsproduktivitaet."),("Verwenden Sie nur ChatGPT fuer alles, weil ein einziges Tool einfacher zu handhaben ist als mehrere.","Suboptimal! Jedes Tool hat Spezialstaerken — ein Tool fuer alles nutzt das Potenzial nicht aus."),("Schreiben Sie den gesamten Code manuell ohne jede KI, weil KI-generierter Code unsicher und fehlerhaft ist.","Veraltet! Moderne KI-Code-Tools sind leistungsfaehig, erfordern aber immer menschliches Code-Review.")),2),
("de","ai-tools-comparison","Ihre Marketingabteilung will KI-generierte Bilder fuer Social Media. DALL-E, Midjourney und Stable Diffusion stehen zur Auswahl.","Bildgenerierungs-KI braucht klare Lizenz- und Nutzungsrechte — pruefen Sie immer die kommerzielle Nutzung.",O(("Pruefen Sie die Lizenzbedingungen aller drei Tools und waehlen basierend auf kommerziellen Nutzungsrechten.","Perfekt! Lizenzen und kommerzielle Nutzungsrechte sind bei KI-generierten Bildern entscheidend wichtig."),("Waehlen Sie Midjourney, weil die Bilder am schoensten aussehen, ohne die Lizenzen zu ueberpruefen.","Riskant! Schoene Bilder nuetzen nichts, wenn die kommerzielle Nutzung nicht lizenziert und erlaubt ist."),("Verzichten Sie auf KI-Bilder komplett, weil urheberrechtliche Fragen noch voellig ungeklaert und riskant sind.","Zu vorsichtig! Viele KI-Bildtools bieten klare kommerzielle Lizenzen fuer professionelle Nutzung.")),3),
("de","ai-tools-comparison","Sie suchen ein KI-Tool, das Meetings transkribiert und Aufgaben ableitet. Otter.ai, Fireflies und Microsoft Copilot sind Optionen.","Meeting-KI spart enorm Zeit, aber Datenschutz und Integration ins bestehende System sind entscheidend.",O(("Evaluieren Sie Datenschutz, Integration in Ihre bestehenden Systeme und testen jedes Tool zwei Wochen.","Richtig! Datenschutz plus Systemintegration plus Praxistest ergibt die fundierte Entscheidung."),("Waehlen Sie Microsoft Copilot, weil Sie bereits Microsoft 365 nutzen, ohne Alternativen zu pruefen.","Bequem, aber voreilig — andere Tools koennten bessere Transkription oder guenstigere Preise bieten."),("Verzichten Sie auf Meeting-KI und lassen weiterhin einen Mitarbeiter manuell ausschliesslich Protokoll fuehren.","Ineffizient! KI-Transkription ist praezise, schnell und entlastet Mitarbeiter fuer wichtigere Aufgaben.")),2),
("de","ai-tools-comparison","Ein Freelancer empfiehlt Perplexity AI fuer Recherchen statt Google. Sie kennen das Tool nicht. Wie gehen Sie mit der Empfehlung um?","Neue KI-Recherchetools wie Perplexity koennen Google sinnvoll ergaenzen, nicht zwingend ersetzen.",O(("Testen Sie Perplexity fuer verschiedene Rechercheaufgaben und vergleichen die Ergebnisse mit Google-Suche.","Klug! Eigene Tests mit realen Aufgaben zeigen, ob ein neues Tool echten Mehrwert fuer Sie bietet."),("Bleiben Sie bei Google, weil Sie dem Tool vertrauen und keine Zeit fuer neue Werkzeuge investieren wollen.","Verstaendlich, aber Sie verpassen moeglicherweise effizientere Wege der Informationsrecherche."),("Wechseln Sie sofort komplett zu Perplexity und kuendigen Ihr Google-Workspace-Abo fuer die ganze Firma.","Uebereilt! Ein einzelnes Tool kann Google nicht in allen Bereichen ersetzen — testen Sie zuerst.")),1),
("de","ai-tools-comparison","Ihr Unternehmen ueberlegt, ob ein Open-Source-LLM wie Llama oder ein kommerzielles Tool wie ChatGPT Plus genutzt werden soll.","Open-Source-LLMs bieten Kontrolle und Datenschutz, kommerzielle Tools Komfort und staendige Updates.",O(("Analysieren Sie Datenschutzanforderungen, IT-Ressourcen und Use Cases, bevor Sie eine Entscheidung treffen.","Perfekt! Die Wahl haengt von Datenschutz, IT-Kapazitaet und konkreten Anwendungsfaellen ab."),("Waehlen Sie sofort ChatGPT Plus, weil kommerzielle Tools immer besser sind als Open-Source-Alternativen.","Falsch! Open-Source-LLMs bieten Vorteile bei Datenschutz, Anpassbarkeit und Kostenkontrolle."),("Waehlen Sie sofort Llama, weil Open Source grundsaetzlich vertrauenswuerdiger und sicherer ist als alles.","Falsch! Open Source allein garantiert weder Sicherheit noch Qualitaet — eine Analyse ist noetig.")),3),
("de","ai-tools-comparison","Sie moechten KI fuer automatische Uebersetzungen nutzen. DeepL, Google Translate und ChatGPT sind verfuegbar. Welches Tool fuer Geschaeftsbriefe?","Fuer professionelle Uebersetzungen ist DeepL oft ueberlegen — aber menschliche Pruefung bleibt Pflicht.",O(("Testen Sie alle drei mit einem typischen Geschaeftsbrief und waehlen das Tool mit der besten Tonalitaet.","Richtig! Vergleichstests mit echten Dokumenten zeigen, welches Tool am besten zu Ihrem Stil passt."),("Nutzen Sie Google Translate, weil es kostenlos ist und fuer alle Sprachen die groesste Abdeckung hat.","Suboptimal! Kostenlos ist nicht immer am besten — bei Geschaeftsbriefen zaehlt Qualitaet vor Preis."),("Uebersetzen Sie Geschaeftsbriefe nie mit KI, weil Uebersetzungstools fuer formelle Texte ungeeignet sind.","Veraltet! Moderne Uebersetzungs-KI liefert bei Geschaeftsbriefen sehr gute Ergebnisse als Startpunkt.")),1),
("de","ai-tools-comparison","Ihr Team nutzt vier verschiedene KI-Tools gleichzeitig. Die monatlichen Kosten steigen stark. Ihr Chef fragt, ob das noetig ist.","KI-Tool-Kosten muessen sich an messbarem Produktivitaetsgewinn orientieren, nicht an Vielfalt allein.",O(("Erstellen Sie eine Kosten-Nutzen-Analyse pro Tool mit messbaren Produktivitaetsgewinnen fuer das gesamte Team.","Perfekt! Datenbasierte Argumentation ueberzeugt Vorgesetzte und optimiert das Tool-Portfolio."),("Kuendigen Sie sofort alle Tools ausser einem, um Kosten zu sparen und den Chef zufriedenzustellen.","Voreilig! Ohne Analyse koennten Sie das wertvollste Tool kuendigen und Produktivitaet verlieren."),("Ignorieren Sie die Kostenfrage und hoffen, dass der Chef das Thema von selbst wieder vergessen wird.","Unprofessionell! Kostenverantwortung zu ignorieren untergaebt Vertrauen und Ihre Glaubwuerdigkeit.")),2),
("de","ai-tools-comparison","Ein neues KI-Tool verspricht, alle anderen zu ersetzen. Die Bewertungen sind begeistert, aber es ist erst zwei Monate auf dem Markt.","Neue KI-Tools begeistern oft anfangs — nachhaltige Qualitaet zeigt sich erst nach Monaten im Alltag.",O(("Testen Sie das Tool in einer Sandbox-Umgebung und vergleichen es drei Monate parallel mit bestehenden Loesungen.","Klug! Paralleler Langzeittest zeigt, ob das neue Tool im Alltag wirklich besser funktioniert."),("Bleiben Sie bei Ihren aktuellen Tools und ignorieren alle neuen KI-Tools grundsaetzlich als unnoetig.","Zu konservativ! Neue Tools koennen echte Vorteile bieten, wenn man sie strukturiert evaluiert."),("Wechseln Sie sofort komplett zum neuen Tool und kuendigen alle bestehenden Lizenzen und Abonnements.","Gefaehrlich! Ein zwei Monate altes Tool kann verschwinden, die API aendern oder an Qualitaet verlieren.")),2),
]

# ai-tools-comparison EN
Q += [
("en","ai-tools-comparison","You need to analyze a lengthy contract and summarize key clauses. Which AI tool do you choose and what is your reasoning?","Claude excels with long documents — but no AI tool replaces professional legal advice under any circumstances.",O(("Use Claude for long document analysis and have the summary reviewed by a qualified legal professional.","Correct! Claude has a large context window for documents, but legal advice remains absolutely essential."),("Use only Google search because AI tools are completely unsuitable for any kind of legal document analysis.","Possible, but AI tools can significantly accelerate preliminary analysis and save valuable time."),("Have ChatGPT analyze the contract and sign immediately based on the AI summary without legal review.","Dangerous! No AI summary replaces professional legal expertise for important contractual decisions.")),2),
("en","ai-tools-comparison","Your team debates whether ChatGPT, Claude, or Gemini is best for daily email communication. How do you make this decision?","The best AI tool depends on the specific use case — test multiple options and choose based on results.",O(("Test all three tools with typical emails from your daily work and compare quality and efficiency.","Perfect! Real-world testing with actual tasks provides the most reliable basis for team decisions."),("Choose ChatGPT simply because it is the most well-known tool with the largest user base worldwide.","Premature! Popularity does not equal suitability — different tools have distinctly different strengths."),("Ban all AI tools for emails because having different tools across the team only creates unnecessary chaos.","Counterproductive! AI diversity can foster innovation when clear guidelines and policies are established.")),1),
("en","ai-tools-comparison","You want to use AI to write code for a web application. GitHub Copilot, ChatGPT, and Claude are all available. How do you decide?","Copilot shines at code integration, while ChatGPT and Claude excel at complex logic and explanations.",O(("Use Copilot for code completion in your editor and ChatGPT or Claude for architecture discussions.","Correct! Combining the strengths of different tools maximizes your overall development productivity."),("Use only ChatGPT for everything because managing a single tool is simpler than juggling multiple tools.","Suboptimal! Each tool has specialized strengths — one tool for everything wastes significant potential."),("Write all code manually without any AI because AI-generated code is inherently insecure and always buggy.","Outdated! Modern AI code tools are powerful, though they always require careful human code review.")),2),
("en","ai-tools-comparison","Your marketing team wants AI-generated images for social media. DALL-E, Midjourney, and Stable Diffusion are available options.","AI image generation requires clear licensing — always verify commercial usage rights before any publishing.",O(("Review licensing terms for all three tools and choose based on commercial usage rights and quality.","Perfect! Licensing and commercial usage rights are critical factors for AI-generated business images."),("Choose Midjourney because the images look the most beautiful without checking any licensing terms first.","Risky! Beautiful images are worthless if commercial usage is not properly licensed and permitted."),("Avoid AI images entirely because copyright questions are still completely unresolved and far too risky.","Too cautious! Many AI image tools offer clear commercial licenses for professional business use.")),3),
("en","ai-tools-comparison","You need an AI tool that transcribes meetings and derives action items. Otter, Fireflies, and Copilot are your main options.","Meeting AI saves enormous time, but data privacy and system integration are the decisive selection factors.",O(("Evaluate data privacy, integration with existing systems, and test each tool for at least two full weeks.","Correct! Privacy plus system integration plus practical testing produces the most informed decision."),("Choose Microsoft Copilot because you already use Microsoft 365 without evaluating any alternatives first.","Convenient but premature — other tools might offer better transcription quality or pricing options."),("Skip meeting AI entirely and continue having an employee take manual meeting notes every single time.","Inefficient! AI transcription is accurate, fast, and frees employees for more important work tasks.")),2),
("en","ai-tools-comparison","A freelancer recommends Perplexity AI for research instead of Google. You have never heard of this tool. How do you respond?","New AI research tools like Perplexity can complement Google but do not necessarily replace it entirely.",O(("Test Perplexity for various research tasks and compare results with Google search side by side.","Smart! Personal testing with real tasks shows whether a new tool adds genuine value for your work."),("Stick with Google because you trust it and have no time to invest in learning any new research tools.","Understandable, but you might miss significantly more efficient ways of finding information online."),("Switch completely to Perplexity immediately and cancel your Google Workspace subscription right away.","Hasty! A single tool cannot replace Google in all areas — always test thoroughly before switching.")),1),
("en","ai-tools-comparison","Your company debates using an open-source LLM like Llama versus a commercial tool like ChatGPT Plus. What do you recommend?","Open-source LLMs offer control and privacy, commercial tools offer convenience and constant updates.",O(("Analyze data privacy requirements, IT resources, and specific use cases before making any decision.","Perfect! The choice depends on privacy needs, IT capacity, and concrete use cases for your team."),("Choose ChatGPT Plus immediately because commercial tools are always superior to open-source alternatives.","Wrong! Open-source LLMs offer significant advantages in privacy, customization, and cost control."),("Choose Llama immediately because open source is fundamentally more trustworthy and secure than anything.","Wrong! Open source alone guarantees neither security nor quality — thorough analysis is always required.")),3),
("en","ai-tools-comparison","You want AI for automatic translations. DeepL, Google Translate, and ChatGPT are available. Which do you choose for business letters?","For professional translations, DeepL often excels — but human review remains mandatory for quality.",O(("Test all three with a typical business letter and choose the tool with the best professional tone.","Correct! Comparative tests with real documents show which tool best matches your professional style."),("Use Google Translate because it is free and has the broadest language coverage available anywhere.","Suboptimal! Free is not always best — for business letters, quality matters significantly more than price."),("Never translate business letters with AI because translation tools are unsuitable for formal documents.","Outdated! Modern AI translation delivers excellent results for business letters as a starting point.")),1),
("en","ai-tools-comparison","Your team uses four different AI tools simultaneously. Monthly costs are rising sharply. Your boss asks if this is necessary.","AI tool costs must be justified by measurable productivity gains, not by variety for its own sake.",O(("Create a cost-benefit analysis per tool with measurable productivity gains documented for the team.","Perfect! Data-driven argumentation convinces managers and optimizes the overall tool portfolio."),("Cancel all tools except one immediately to cut costs and satisfy your boss without further analysis.","Premature! Without analysis, you might cancel the most valuable tool and lose real productivity."),("Ignore the cost question and hope your boss eventually forgets about the topic on their own.","Unprofessional! Ignoring cost responsibility undermines trust and your credibility as team leader.")),2),
("en","ai-tools-comparison","A brand-new AI tool promises to replace all others. Reviews are enthusiastic, but it launched only two months ago. How do you react?","New AI tools often dazzle initially — sustainable quality only becomes apparent after months of daily use.",O(("Test the tool in a sandbox environment and run it parallel to existing solutions for three months.","Smart! A parallel long-term test reveals whether the new tool truly performs better in daily use."),("Stay with your current tools and ignore all new AI tools as unnecessary distractions from real work.","Too conservative! New tools can offer genuine advantages when you evaluate them in a structured way."),("Switch completely to the new tool immediately and cancel all existing licenses and subscriptions today.","Dangerous! A two-month-old tool could disappear, change its API, or decline in quality rapidly.")),2),
]

# For the remaining 10 categories (customer-service, finance, health, education, manufacturing, public-sector, media-content, sustainability, psychology, myths-facts)
# I'll generate them in a second script file to avoid size limits

# Insert all questions in batches of 10
batch_size = 10
for i in range(0, len(Q), batch_size):
    batch = Q[i:i+batch_size]
    sql = build_insert(batch)
    cat = batch[0][1]
    loc = batch[0][0]
    label = f"batch {i//batch_size+1}: {cat} {loc}"
    run_sql(sql, label)
    time.sleep(0.3)

print(f"\nDONE: {ok_count} OK, {fail_count} FAIL, {len(Q)} total questions in script 1")
