const TOKEN = 'sbp_f314cf27b5b2a01eea48048a7b1c015cc9cf4b42'
const API = 'https://api.supabase.com/v1/projects/amhfxaqolholacanqyas/database/query'
function esc(s) { return s.replace(/'/g, "''") }
async function insert(batch) {
  const values = batch.map(q => {
    const opts = JSON.stringify(q.options).replace(/'/g, "''")
    return `('en','${q.cat}','${esc(q.s)}','${esc(q.t)}','${opts}'::jsonb,${q.d},'claude',true)`
  }).join(',')
  const sql = `INSERT INTO questions (locale,category,scenario_text,mindset_tip,options,difficulty,generated_by,is_active) VALUES ${values};`
  const r = await fetch(API, {method:'POST',headers:{'Authorization':`Bearer ${TOKEN}`,'Content-Type':'application/json'},body:JSON.stringify({query:sql})})
  const d = await r.json()
  if(d.message) { console.error('ERR:',d.message.substring(0,120)); return false }
  console.log('OK:', batch.length, 'inserted')
  return true
}

const ALL = [

// ===== ai-law-regulation (20) =====
{cat:'ai-law-regulation',d:1,s:'Your company wants to deploy a customer-facing AI chatbot in the EU. You are not sure if any regulations apply.',t:'The EU AI Act classifies customer-facing AI systems by risk level and mandates specific transparency and documentation requirements before deployment.',options:[
  {text:'Launch the chatbot immediately and address legal issues if regulators raise them later',score:-100,feedbackText:'Reactive compliance after deployment creates retroactive liability. Proactive regulatory review before launch is standard practice for customer-facing AI in regulated markets.'},
  {text:'Review the EU AI Act risk classification for your chatbot\'s use case, identify applicable transparency and documentation requirements, and complete them before launch',score:100,feedbackText:'Correct! Risk classification under the EU AI Act determines which requirements apply. Transparency requirements for customer-facing AI are not optional and must be met before go-live.'},
  {text:'Deploy only to non-EU users initially to avoid EU regulation',score:0,feedbackText:'Geo-restricted initial deployment is a practical approach to limit scope but does not resolve the regulatory question for EU expansion. Build compliance architecture from the start.'}
]},
{cat:'ai-law-regulation',d:2,s:'You are building an AI hiring tool for a US employer. Your legal team flags concerns about disparate impact discrimination risk.',t:'AI hiring tools that have disparate impact on protected groups create Title VII liability regardless of whether bias was intentional.',options:[
  {text:'Proceed with the AI hiring tool since it uses objective data and therefore cannot be biased',score:-100,feedbackText:'Objective data can encode historical discrimination. AI tools built on biased historical hiring data will replicate that bias regardless of their technical objectivity.'},
  {text:'Conduct disparate impact testing on your hiring data before deployment, document findings, remediate identified bias, and establish ongoing demographic monitoring',score:100,feedbackText:'Excellent! Pre-deployment disparate impact testing is the legal and ethical standard for AI hiring tools. Documentation and ongoing monitoring are also components of defensible compliance.'},
  {text:'Add a disclaimer that the AI tool is one of several factors in hiring decisions',score:0,feedbackText:'A disclaimer does not eliminate disparate impact liability. The legal standard is impact, not intent or process design. Testing for impact is the required step.'}
]},
{cat:'ai-law-regulation',d:1,s:'A healthcare AI company wants to market its product as a diagnostic device in the US. You are unsure about FDA requirements.',t:'AI diagnostic tools that meet the definition of a medical device require FDA clearance through 510k or De Novo pathways before US marketing.',options:[
  {text:'Market the product as a clinical decision support tool to avoid FDA device classification',score:0,feedbackText:'Clinical decision support classification avoids FDA requirements only if the product truly meets that narrower definition. Misclassification to avoid regulation creates enforcement risk.'},
  {text:'Determine whether the product meets the FDA\'s medical device definition, and if so, pursue the appropriate premarket review pathway before marketing',score:100,feedbackText:'Correct! FDA device classification turns on specific criteria about intended use and clinical decision authority. Premarket review is not optional for products that meet the definition.'},
  {text:'Launch the product since it is software and software is not a medical device',score:-100,feedbackText:'Software-as-a-Medical-Device (SaMD) is explicitly regulated by the FDA. The software format does not exempt a product from medical device regulation if it meets the intended use criteria.'}
]},
{cat:'ai-law-regulation',d:2,s:'You process customer personal data from European users to train an AI model. Your legal team warns about GDPR implications.',t:'Using personal data to train AI models requires a valid legal basis under GDPR, purpose limitation compliance, and often privacy impact assessment.',options:[
  {text:'Use the data since customers accepted your terms of service when signing up',score:-100,feedbackText:'ToS acceptance is not a valid GDPR legal basis for AI training without specific consent for that use case. Purpose limitation under GDPR requires that data is used for the purpose it was collected.'},
  {text:'Identify the legal basis for each data category used in training, conduct a DPIA for high-risk processing, anonymize where possible, and document the data lineage',score:100,feedbackText:'Excellent! Legal basis, DPIA for high-risk processing, anonymization, and documentation are the four pillars of GDPR-compliant AI training data management.'},
  {text:'Anonymize all data before training since anonymized data is exempt from GDPR',score:0,feedbackText:'True anonymization is GDPR-exempt, but genuine irreversibility is technically difficult. Legal review of the anonymization approach is needed before relying on this exemption.'}
]},
{cat:'ai-law-regulation',d:3,s:'A government agency wants to use AI for predictive policing to allocate patrol resources. Civil liberties organizations raise concerns.',t:'Predictive policing AI can perpetuate racial bias in historical crime data and must be evaluated against constitutional due process and equal protection standards.',options:[
  {text:'Deploy the AI since it allocates resources based on data rather than officer bias',score:-100,feedbackText:'Historical crime data encodes arrest patterns influenced by prior enforcement bias. AI-based predictive policing can systematically concentrate enforcement in already over-policed communities.'},
  {text:'Conduct an independent bias audit of the training data and model outputs by demographic, obtain legal review for constitutional compliance, and pilot with robust community oversight',score:100,feedbackText:'Correct! Independent bias auditing, constitutional review, and community oversight are the components of responsible evaluation before any predictive policing deployment.'},
  {text:'Commission a pilot study and evaluate the AI\'s accuracy before addressing civil liberties concerns',score:0,feedbackText:'Accuracy and fairness are separate properties. A model can be accurate on average while systematically discriminating against protected groups. Fairness review must accompany accuracy evaluation.'}
]},
{cat:'ai-law-regulation',d:1,s:'You want to use AI to review and summarize contracts but you are worried about attorney-client privilege implications.',t:'AI contract review tools that process privileged materials must be evaluated for privilege-waiving risk before use in legal workflows.',options:[
  {text:'Use any AI contract review tool since summarization does not constitute legal advice',score:0,feedbackText:'Privilege risk is about the confidentiality of the information shared, not whether the AI is giving advice. Third-party AI processing of privileged materials can waive privilege in some jurisdictions.'},
  {text:'Use AI tools that process materials within the firm\'s secure environment, obtain legal ethics guidance for your jurisdiction, and document the tool\'s data handling',score:100,feedbackText:'Excellent! On-premises or secure-environment AI tools reduce third-party privilege risk. Jurisdiction-specific ethics guidance ensures your use complies with bar obligations.'},
  {text:'Avoid AI for contract review entirely since legal work requires human lawyers',score:-100,feedbackText:'AI contract review is widely used in legal practice with appropriate safeguards. Categorical avoidance sacrifices real efficiency without eliminating the risk that proper safeguards would address.'}
]},
{cat:'ai-law-regulation',d:2,s:'Your AI system makes automated credit decisions for consumers. A regulator asks you to explain a specific denial decision.',t:'Equal Credit Opportunity Act requirements mandate that credit decisions, including AI-generated ones, must be explainable in specific terms to applicants and regulators.',options:[
  {text:'Provide the regulator with the AI\'s overall accuracy metrics since individual decisions are algorithmic and cannot be explained',score:-100,feedbackText:'System accuracy does not satisfy adverse action notice requirements. ECOA requires specific reason codes for each adverse decision, not aggregate model performance statistics.'},
  {text:'Retrieve the decision factors for that specific case from your explainability layer and provide them in the standardized reason code format ECOA requires',score:100,feedbackText:'Correct! ECOA requires individual-level explainability for adverse decisions. Explainability architecture must be designed into credit AI before deployment, not added after regulatory inquiry.'},
  {text:'Argue that modern AI models are too complex for individual decision explanations and request a regulatory exemption',score:0,feedbackText:'Regulatory exemptions from adverse action notice requirements are not available. Regulators require explainability regardless of model complexity. Explainable-by-design is the only compliant path.'}
]},
{cat:'ai-law-regulation',d:1,s:'You are building a chatbot that will interact with children under 13 on an educational platform. You need to understand the legal requirements.',t:'COPPA requires verifiable parental consent before collecting personal information from children under 13 and imposes strict data use limitations.',options:[
  {text:'Add a birth year field to the registration form and accept user-provided age without verification',score:-100,feedbackText:'Self-reported age without verification is not verifiable parental consent under COPPA. Regulators and courts have consistently rejected honor-system age verification for child data collection.'},
  {text:'Implement a verifiable parental consent mechanism, limit data collection to what is necessary for the educational function, and review all third-party integrations for COPPA compliance',score:100,feedbackText:'Excellent! Verifiable consent, data minimization, and third-party integration review are the three COPPA compliance pillars for child-directed applications.'},
  {text:'Restrict data collection to only name and email address since minimal data means minimal risk',score:0,feedbackText:'Any personal information collection from under-13 users requires verifiable parental consent under COPPA regardless of how minimal the data is.'}
]},
{cat:'ai-law-regulation',d:2,s:'An AI system you use recommends content to users. You notice it sometimes recommends content involving dangerous activities.',t:'AI recommender systems that surface harmful content to users create liability exposure and require content moderation layers regardless of algorithm sophistication.',options:[
  {text:'Report the harmful content recommendations as a bug to your AI vendor and wait for a fix',score:0,feedbackText:'Reporting to the vendor is appropriate but incomplete. While waiting for a fix, you remain liable for harmful recommendations. Immediate interim content moderation is necessary.'},
  {text:'Implement content filters as an immediate interim measure, report to the vendor, review your terms of service for content safety obligations, and document the incident',score:100,feedbackText:'Correct! Immediate interim protection plus vendor reporting plus legal review is the complete response. Waiting for vendor fix while continuing to surface harmful content creates ongoing liability.'},
  {text:'Shut down the recommendation system entirely until the vendor resolves the issue',score:-100,feedbackText:'Full shutdown may be disproportionate if interim content filtering can control the risk. The response should be calibrated to the harm severity and availability of interim mitigations.'}
]},
{cat:'ai-law-regulation',d:3,s:'Your company operates an AI system in both the EU and UK. Post-Brexit, they now have separate AI regulatory frameworks.',t:'Operating AI systems across EU and UK jurisdictions requires compliance with both frameworks, which may have overlapping but non-identical requirements.',options:[
  {text:'Comply with the stricter EU framework and assume UK compliance follows automatically',score:0,feedbackText:'EU compliance does not guarantee UK compliance. Post-Brexit, the UK has developed its own AI regulatory approach that may differ in specific requirements even where the policy goals are similar.'},
  {text:'Map each jurisdiction\'s specific requirements against your AI system\'s use cases, identify where they differ, and build compliance architecture that satisfies both',score:100,feedbackText:'Excellent! Comparative regulatory mapping followed by dual-jurisdiction compliance architecture is the right approach. Assume divergence until proven identical for each specific requirement.'},
  {text:'Wait until both frameworks stabilize before investing in compliance since AI regulation is still evolving',score:-100,feedbackText:'Waiting for stable regulation means operating out of compliance during the waiting period. Current requirements are enforceable now regardless of future regulatory evolution.'}
]},
{cat:'ai-law-regulation',d:1,s:'You want to use AI to generate marketing content but are unsure about copyright ownership of AI-generated material.',t:'Copyright law for AI-generated content varies by jurisdiction and depends on the degree of human authorship involved in the creation process.',options:[
  {text:'Use AI-generated content freely since AI outputs are not copyrightable and therefore not infringing',score:0,feedbackText:'AI outputs may not be protectable by copyright, but AI trained on copyrighted works may generate outputs that infringe those works. The copyright analysis runs in both directions.'},
  {text:'Consult legal counsel about copyright status in your jurisdiction, document human authorship contributions, and review the AI tool\'s terms about IP ownership of outputs',score:100,feedbackText:'Correct! Jurisdiction-specific legal advice, documented human contribution, and vendor IP terms review are the three components of copyright risk management for AI-generated content.'},
  {text:'Register copyrights on all AI-generated content to protect your assets',score:-100,feedbackText:'Most copyright offices currently reject copyright registration for works without human authorship. Claiming copyright you may not hold creates its own legal exposure.'}
]},
{cat:'ai-law-regulation',d:2,s:'Your AI model was trained partly on scraped web data. A content creator claims the model reproduces their work without permission.',t:'Training AI on copyrighted content creates legal exposure that is not yet fully resolved but active litigation is establishing boundaries around permissible use.',options:[
  {text:'Assert that AI training on publicly available web data is clearly legal fair use',score:0,feedbackText:'Fair use in AI training is an active litigation question, not settled law. Asserting clear legality overstates the certainty of a still-contested legal question.'},
  {text:'Consult IP counsel about your specific training data provenance, review licensing for data sources, and assess whether the model can be shown to reproduce training data verbatim',score:100,feedbackText:'Excellent! Training data provenance review, licensing assessment, and memorization risk analysis are the components of defensible copyright risk management for AI models.'},
  {text:'Remove the AI model from service immediately to avoid litigation',score:-100,feedbackText:'Immediate removal may be disproportionate. Legal assessment of actual risk, potential licensing solutions, and filtering options should inform the response before removal.'}
]},
{cat:'ai-law-regulation',d:1,s:'Your company operates an automated AI system that makes employment-related decisions affecting workers. An employee asks to know what data about them the AI uses.',t:'Several jurisdictions grant workers rights to know what automated systems use to make employment decisions affecting them.',options:[
  {text:'Tell the employee that the AI system is proprietary and you cannot share that information',score:-100,feedbackText:'Proprietary claims do not override data subject rights in jurisdictions with automated decision transparency requirements. Denying access to required disclosures creates enforcement risk.'},
  {text:'Provide the employee with the categories of data used, the logic of the automated system, and their right to challenge automated decisions under applicable law',score:100,feedbackText:'Correct! Data categories, system logic, and challenge rights are the disclosure elements required under GDPR Article 22 and equivalent frameworks. This is a legal obligation, not discretionary.'},
  {text:'Offer to speak with an HR representative who can explain the general employment process without revealing AI specifics',score:0,feedbackText:'HR conversation without the specific AI disclosure does not satisfy transparency rights. The employee is entitled to information about the specific automated process, not a general HR conversation.'}
]},
{cat:'ai-law-regulation',d:3,s:'Your AI risk assessment tool gives different outcomes for similarly situated individuals when tested repeatedly. The inconsistency is random.',t:'Non-deterministic AI systems used in consequential decisions may violate due process principles because similarly situated individuals receive different outcomes without justification.',options:[
  {text:'Accept some randomness as inherent in probabilistic AI systems since all models have variance',score:0,feedbackText:'Statistical variance is expected and acceptable at the population level. The legal concern is individual-level inconsistency in consequential decisions where similarly situated persons receive different outcomes.'},
  {text:'Investigate the source of randomness, determine whether it is model architecture or input variation, and establish whether the variance is within acceptable legal bounds for the decision type',score:100,feedbackText:'Excellent! Root cause diagnosis followed by legal assessment for the specific decision type is the right approach. Acceptable variance differs between low-stakes and high-stakes applications.'},
  {text:'Retrain the model with more data to reduce variance to acceptable levels',score:-100,feedbackText:'More training data reduces overall variance but does not necessarily reduce the type of inconsistency that creates due process concerns. The variance source must be diagnosed before the fix is designed.'}
]},
{cat:'ai-law-regulation',d:2,s:'You operate an AI system in a state that recently passed a comprehensive AI transparency law requiring disclosure to users when they interact with AI.',t:'State AI transparency laws typically require conspicuous disclosure of AI interaction and often prohibit AI from impersonating humans when asked.',options:[
  {text:'Add a generic privacy policy reference to the AI disclosure requirement',score:-100,feedbackText:'Burying disclosure in a privacy policy does not satisfy conspicuous disclosure requirements. Transparency laws require prominent, upfront disclosure before or at the start of AI interaction.'},
  {text:'Add a clear disclosure statement at the beginning of every AI interaction and configure the system to acknowledge being AI when directly asked',score:100,feedbackText:'Correct! Upfront disclosure plus honest acknowledgment when asked are the two core requirements of AI transparency laws. Both must be technically implemented, not just policy-stated.'},
  {text:'Update your terms of service to include an AI disclosure acknowledgment users must accept',score:0,feedbackText:'Terms of service acknowledgment provides legal coverage but may not meet conspicuous disclosure requirements. Prominent in-product disclosure at the time of interaction is the safer design.'}
]},
{cat:'ai-law-regulation',d:1,s:'Your company uses AI to monitor employee productivity. An employee in France raises concerns about their rights.',t:'French and EU labor law impose significant restrictions on employee monitoring technology, including AI-based productivity tracking, requiring employee and works council consultation.',options:[
  {text:'Continue the monitoring program since productivity data is legitimate business information',score:-100,feedbackText:'Business legitimacy does not override French labor law requirements for works council consultation and individual employee notification before deploying monitoring technology.'},
  {text:'Pause French deployment, consult the works council as required, notify individual employees of the monitoring, and review the data processing against GDPR requirements',score:100,feedbackText:'Excellent! Works council consultation, employee notification, and GDPR review are the legal prerequisites for employee monitoring technology deployment in France.'},
  {text:'Reduce the monitoring intensity to the minimum necessary data collection',score:0,feedbackText:'Minimization is a good principle but does not satisfy the consultation and notification requirements regardless of monitoring intensity. Process requirements apply before any level of monitoring.'}
]},
{cat:'ai-law-regulation',d:2,s:'You want to use AI for automated resume screening for a role that requires security clearance. The screening eliminates many candidates from minority groups.',t:'Employment AI with disparate impact requires adverse impact analysis even in security-cleared roles since equal employment law applies to cleared positions.',options:[
  {text:'Continue screening since national security roles have different equity standards',score:-100,feedbackText:'Equal employment opportunity law applies to security-cleared positions. National security requirements affect candidate eligibility criteria but do not create an exemption from disparate impact law.'},
  {text:'Conduct disparate impact analysis on the screening outcomes, identify which screening criteria drive the disparate impact, and evaluate whether those criteria are job-related and consistent with business necessity',score:100,feedbackText:'Correct! Job-relatedness and business necessity are the legal standards for justifying disparate impact in employment screening. The analysis must be completed before continuing the screening program.'},
  {text:'Have security experts manually review all screened-out candidates to look for missed qualified individuals',score:0,feedbackText:'Manual review of screened-out candidates mitigates harm but does not analyze or address the source of disparate impact. Root cause analysis must accompany any interim mitigation.'}
]},
{cat:'ai-law-regulation',d:1,s:'A small business owner in the US wants to use an AI tool that processes customer payment information to improve billing accuracy.',t:'Payment card data processed by AI tools is subject to PCI DSS requirements regardless of whether AI or humans handle it.',options:[
  {text:'Use any AI billing tool since it is just for accuracy improvement, not actual payment processing',score:0,feedbackText:'PCI DSS scope depends on cardholder data contact, not the purpose of the processing. Any system that processes, transmits, or stores payment card data is in scope.'},
  {text:'Verify that the AI billing tool is PCI DSS compliant or operates in a scope-reducing manner, and confirm this with your payment processor before enabling payment data access',score:100,feedbackText:'Excellent! PCI compliance verification and payment processor confirmation are the two required steps before connecting any tool to payment card data. Compliance is the vendor\'s responsibility, but verification is yours.'},
  {text:'Contact your payment card processor before using any third-party billing tool since they govern payment data use',score:-100,feedbackText:'Processor contact is a good step but PCI DSS compliance is not just a processor question — it is a standard that applies to every system in your payment data environment.'}
]},
{cat:'ai-law-regulation',d:3,s:'Your AI system was found to have made errors affecting government benefit determinations. Affected individuals were not notified.',t:'Government AI errors affecting individual rights typically trigger due process notification obligations and may require retroactive review of affected decisions.',options:[
  {text:'Correct the AI system going forward and assume historical errors will be surfaced through normal appeals processes',score:0,feedbackText:'Passive reliance on appeals processes for systemic AI errors ignores due process notification obligations. People who did not receive benefits they were entitled to may not know to appeal.'},
  {text:'Identify all affected determinations, proactively notify affected individuals of potential errors, establish a review process for their cases, and report to the relevant oversight body',score:100,feedbackText:'Correct! Proactive identification, individual notification, case review, and oversight reporting are the components of responsible response to systemic AI errors in government decision-making.'},
  {text:'Immediately disable the AI system and revert all determinations to manual review',score:-100,feedbackText:'Full reversion may not be operationally feasible and does not address the harm already caused. Targeted remediation with proactive notification is more proportionate and immediately responsive to affected individuals.'}
]},
{cat:'ai-law-regulation',d:2,s:'Your company wants to use AI-generated synthetic data to train models without using real customer data. Your legal team has questions.',t:'Synthetic data generated from real customer data may retain identifiable information and its use may still require legal basis under applicable privacy law.',options:[
  {text:'Use synthetic data freely since it is not real customer data by definition',score:-100,feedbackText:'Synthetic data derived from real customer data may contain residual identifiable information. The generation process and the output must be evaluated, not just the label "synthetic."'},
  {text:'Have technical and legal teams jointly assess whether the synthetic generation process genuinely prevents re-identification, and obtain legal opinion on whether original data processing creates legal basis requirements',score:100,feedbackText:'Excellent! Re-identification risk assessment plus legal basis analysis are both required. Synthetic data is only as privacy-safe as its generation methodology, which requires technical validation.'},
  {text:'Ask your AI vendor whether their synthetic data generation is privacy-compliant and rely on their confirmation',score:0,feedbackText:'Vendor confirmation transfers responsibility in contractual terms but not in regulatory terms. Your organization remains responsible for data protection compliance regardless of vendor assurances.'}
]},

// ===== ai-leadership (20) =====
{cat:'ai-leadership',d:1,s:'You are a team lead and want to introduce AI tools to your team, but several members are resistant because they fear job loss.',t:'Addressing job security concerns honestly and early in AI adoption is more effective than dismissing fears or promising immunity you cannot guarantee.',options:[
  {text:'Tell the team that AI will not affect any of their jobs to reduce resistance and encourage adoption',score:-100,feedbackText:'Making job security promises you cannot keep destroys trust when roles do change. Honest, specific conversation about what AI will and will not change is more effective and sustainable.'},
  {text:'Have honest conversations about which tasks AI will automate, which roles will evolve, and what upskilling support the organization will provide',score:100,feedbackText:'Correct! Honest, specific, and forward-looking communication about AI impact is what resistant team members actually need. Vague reassurance amplifies rather than reduces anxiety.'},
  {text:'Implement AI tools without discussion and address concerns as they arise',score:0,feedbackText:'Surprise AI implementation without consultation triggers the exact resistance you wanted to avoid. Pre-emptive honest conversation is always more effective than reactive damage control.'}
]},
{cat:'ai-leadership',d:2,s:'You are a department head and want to set measurable goals for your team\'s AI adoption over the next six months.',t:'Measurable AI adoption goals must connect tool usage to business outcomes, not just track license utilization or time spent with tools.',options:[
  {text:'Set a goal that 100% of the team uses the AI tools daily',score:0,feedbackText:'Usage frequency is an activity metric, not an outcome metric. Teams can use AI daily without any business improvement if the usage is not targeted at the right tasks.'},
  {text:'Set goals for specific business outcomes: hours saved per week on defined task types, error rate reduction, or output quality scores that the team can realistically achieve in six months',score:100,feedbackText:'Excellent! Business outcome metrics connect AI adoption to actual value creation. Outcome-focused goals also help the team understand which uses of the tool matter most.'},
  {text:'Skip formal AI goals since tool adoption should be organic and self-directed',score:-100,feedbackText:'Organic adoption without goals produces highly uneven results. Clear goals with adequate support drive adoption faster and more equitably across a diverse team.'}
]},
{cat:'ai-leadership',d:1,s:'As a senior manager, you have been asked to create an AI usage policy for your department. You do not know where to start.',t:'Department AI policies work best when built from actual team use cases rather than abstract principles copied from generic templates.',options:[
  {text:'Find a comprehensive AI policy template online and apply it to your department',score:0,feedbackText:'Generic templates provide a starting point but often miss the specific use cases, risk types, and data sensitivity that vary significantly by department.'},
  {text:'Survey your team on current AI uses, identify the highest-risk use cases, draft guidelines for those specific situations, and review with legal and security before publishing',score:100,feedbackText:'Correct! Use case inventory plus risk assessment plus targeted guidance plus legal review is the right policy development sequence. Policy that reflects actual team behavior gets followed.'},
  {text:'Wait for company-wide policy guidance and defer to whatever corporate publishes',score:-100,feedbackText:'Waiting for corporate policy means operating without guidance in the interim. A department-level policy can supplement and precede corporate policy while still aligning with company direction.'}
]},
{cat:'ai-leadership',d:2,s:'One of your highest performers is using AI to produce work that looks like three people working instead of one. Colleagues notice the output gap and some feel unfair pressure.',t:'Extraordinary AI-leveraged productivity creates team dynamics issues that leaders must address proactively before they damage cohesion.',options:[
  {text:'Praise the high performer publicly and encourage all team members to match their output',score:-100,feedbackText:'Praising AI-leveraged output without sharing the methods creates an unfair playing field. Team members without access to the same tools or skills cannot realistically match the output.'},
  {text:'Work with the high performer to document their AI workflow, share it with the team, and use it as a teaching opportunity that lifts everyone',score:100,feedbackText:'Excellent! Turning individual advantage into team knowledge is a leadership multiplier. The high performer gets recognition; the team gains capability; cohesion improves.'},
  {text:'Reduce the high performer\'s AI access to create more equitable output levels',score:0,feedbackText:'Reducing capability rather than spreading it is exactly the wrong response to a productivity advantage. Equalization should come from uplifting others, not constraining the leader.'}
]},
{cat:'ai-leadership',d:3,s:'As a CTO, you must decide whether to build proprietary AI capabilities or use off-the-shelf models for your core product. Investors are watching.',t:'Build vs. buy AI capability is a strategic positioning decision that requires clear articulation of what differentiation requires proprietary capability and what does not.',options:[
  {text:'Build everything proprietary to create maximum competitive moat',score:0,feedbackText:'Proprietary AI for non-differentiating capabilities is expensive and slow. The decision should be made capability by capability, not as a blanket policy.'},
  {text:'Map each AI capability to whether it is a genuine competitive differentiator, build only the differentiating components, and use best-in-class external models for everything else',score:100,feedbackText:'Correct! Capability-by-capability differentiation analysis is the right strategic framework. Building what makes you different and buying what is commodity is the efficient AI strategy.'},
  {text:'Use only off-the-shelf models to manage costs since custom AI rarely delivers the promised return',score:-100,feedbackText:'Off-the-shelf models are right for commodity capabilities but cannot provide the data advantages or fine-tuning that make AI a genuine differentiator in your specific domain.'}
]},
{cat:'ai-leadership',d:1,s:'You manage a content team and want to use AI to help writers produce more content per week. Your writers worry AI will replace their creative voice.',t:'AI-augmented writers who learn to use AI as a productivity multiplier typically increase both output and quality, becoming more competitive rather than replaceable.',options:[
  {text:'Increase output quotas immediately since AI assistance means writers can produce more',score:-100,feedbackText:'Immediate quota increases without training or transition time treats AI as a drop-in tool rather than a new skill. Writers need time to integrate AI without sacrificing quality or burning out.'},
  {text:'Pilot AI tools with two or three willing writers, measure output and quality together, share learnings across the team, and set new expectations based on demonstrated results',score:100,feedbackText:'Excellent! Pilot with willing early adopters plus quality measurement plus shared learning is the right introduction model. Expectations should follow evidence, not precede adoption.'},
  {text:'Let each writer decide whether to use AI since creative professionals should control their tools',score:0,feedbackText:'Voluntary adoption in creative teams often means uneven use and emerging equity issues over time. Shared pilot learning plus flexible implementation respects creativity while building collective capability.'}
]},
{cat:'ai-leadership',d:2,s:'Your engineering team has started using AI coding assistants. You notice code review times have dropped but bug rates have increased in staging.',t:'AI-generated code is often syntactically correct but semantically flawed. Code review processes must adapt to review AI output differently from human-written code.',options:[
  {text:'Restrict AI coding assistant use since the bug rate increase outweighs the review speed benefit',score:0,feedbackText:'Restriction is one option but diagnose first. The bug increase likely reflects code review processes that are not calibrated to AI-generated code patterns, not an inherent AI problem.'},
  {text:'Analyze which types of bugs are increasing, adjust code review criteria to address AI-specific failure patterns, and add targeted testing for common AI code weaknesses',score:100,feedbackText:'Correct! Failure pattern analysis plus targeted review criteria adaptation is the right response. AI code has characteristic weaknesses that traditional review processes are not designed to catch.'},
  {text:'Increase code review standards uniformly to compensate for AI quality issues',score:-100,feedbackText:'Uniform review increases reduce the speed benefit that motivated AI adoption. Targeted review for AI-specific failure modes is more efficient than blanket review intensification.'}
]},
{cat:'ai-leadership',d:1,s:'You are presenting a business case to your board for a $500K investment in AI infrastructure. The board wants to understand the ROI.',t:'Board-level AI investment cases need three elements: the problem it solves, the cost without AI, and the realistic benefit within a defined time horizon.',options:[
  {text:'Present the exciting capabilities of the AI infrastructure and let the board draw their own ROI conclusions',score:-100,feedbackText:'Capability presentations without financial framing do not answer the ROI question. Boards approve investments based on expected returns, not technology excitement.'},
  {text:'Present the current cost of the problem being solved, the projected impact of AI at conservative and optimistic assumptions, and the timeline to break even',score:100,feedbackText:'Excellent! Problem cost, scenario-based impact modeling, and break-even timeline are the three elements of a credible board-level ROI case. Conservative and optimistic scenarios show you have done the analysis honestly.'},
  {text:'Show competitor AI investments and argue that matching them is necessary to remain competitive',score:0,feedbackText:'Competitive argument alone is weak without your own ROI analysis. "Everyone else is doing it" does not tell the board whether the investment makes sense for your specific business.'}
]},
{cat:'ai-leadership',d:2,s:'Several of your team members have become significantly more productive using AI but now resist doing the slower parts of their work that AI cannot automate.',t:'AI-driven workflow redesign must address the full workflow, including the components AI cannot automate, so bottleneck shifting does not reduce overall productivity.',options:[
  {text:'Allow team members to delegate all AI-incompatible work to junior staff',score:-100,feedbackText:'Delegating AI-incompatible work down creates a two-tier workflow where junior staff do the hardest work without development. It also fails to solve the bottleneck.'},
  {text:'Redesign the full workflow to minimize the non-automatable bottlenecks through better process design, team rotation, or targeted hiring where the non-AI work is genuinely high-value',score:100,feedbackText:'Correct! Workflow redesign that addresses bottlenecks rather than shifting them is the complete solution. The goal is to eliminate or minimize the remaining manual burden, not create a new equity problem.'},
  {text:'Set minimum standards for manual work completion alongside AI work to ensure all tasks get done',score:0,feedbackText:'Minimums prevent bottlenecks from being completely ignored but create a two-track system where AI-accelerated work is fast and manual-required work is slow. Process redesign is a more structural solution.'}
]},
{cat:'ai-leadership',d:3,s:'You are asked to lead an AI ethics committee at your company. Most committee members want to focus on abstract principles rather than practical governance.',t:'Effective AI ethics governance needs operational specificity: clear guidelines for defined use cases, review processes, and escalation paths — not just abstract values.',options:[
  {text:'Focus the committee on developing a comprehensive set of AI ethics principles for the company',score:0,feedbackText:'Principles provide direction but without operational specificity they do not prevent harm. Abstract ethics without implementation guidance regularly fails to change organizational behavior.'},
  {text:'Anchor the committee to specific use cases currently in development, create decision frameworks for those cases, and establish review and escalation processes that are practical to execute',score:100,feedbackText:'Excellent! Use-case-grounded governance with operational decision frameworks and escalation processes is what moves ethics from declaration to practice. Abstract principles follow from specific hard cases.'},
  {text:'Commission an external ethics audit since internal committees lack objectivity',score:-100,feedbackText:'External audits provide independent perspective but are periodic. A functioning internal governance process provides ongoing review that external audits cannot replace.'}
]},
{cat:'ai-leadership',d:1,s:'Your team is developing an AI feature but is behind schedule. An engineer suggests skipping testing to meet the deadline.',t:'Skipping AI testing creates disproportionate downstream risk because AI failures can be unexpected in nature and scope compared to traditional software bugs.',options:[
  {text:'Allow selective testing reduction since missing the deadline has clear business consequences',score:0,feedbackText:'Some testing reduction may be manageable but "selective" should be rigorously defined. AI-specific failure modes like bias and edge case behavior must be tested regardless of schedule pressure.'},
  {text:'Protect the minimum viable testing suite that covers safety, bias, and high-consequence edge cases, then negotiate with stakeholders on a realistic launch timeline',score:100,feedbackText:'Correct! Non-negotiable test coverage for safety and bias cases plus stakeholder negotiation on timeline is the responsible approach. Testing shortcuts in AI have asymmetric downside risk.'},
  {text:'Ship without testing since post-launch monitoring can catch most issues',score:-100,feedbackText:'Post-launch monitoring catches issues after they have affected real users. For AI systems with safety or fairness implications, harm-after-launch cannot be the quality strategy.'}
]},
{cat:'ai-leadership',d:2,s:'As a people manager, you want to use AI to help you write more consistent performance reviews across your ten direct reports.',t:'AI assistance with performance reviews ensures consistent language and structure while you provide the substantive assessment that only you can make.',options:[
  {text:'Have AI write the complete performance review for each employee based on their output data',score:-100,feedbackText:'AI-written reviews without manager substantive input are both ethically problematic and legally risky. You are certifying observations about an employee\'s work that only you can make.'},
  {text:'Write your substantive assessment for each employee and use AI to help you frame it consistently, ensure balanced language, and flag any unintentional tone disparities across the team',score:100,feedbackText:'Excellent! Your assessment plus AI consistency check is the right collaboration model. The substance and accountability stay with you; AI helps you deliver it equitably across your team.'},
  {text:'Use AI to generate questions to ask each employee during the review cycle and incorporate their self-evaluations into the final review',score:0,feedbackText:'AI-generated review questions are a legitimate efficiency tool. The missing piece is still your substantive assessment of each employee\'s performance and development.'}
]},
{cat:'ai-leadership',d:3,s:'Your organization is considering AI systems that would reduce headcount by 25% over three years. You are asked to lead the change management.',t:'AI-driven workforce reductions require transparent communication, genuine transition support, and honest timelines to maintain organizational trust during the change.',options:[
  {text:'Keep the headcount reduction plan confidential until implementation to avoid anxiety and attrition',score:-100,feedbackText:'Concealing planned reductions until implementation destroys trust and accelerates attrition of exactly the people you want to retain. Managed transparency is less disruptive than leaked surprise.'},
  {text:'Communicate the plan with honest timelines, provide specific transition support for affected roles, create retraining pathways for those who can transition to new AI-augmented roles, and commit to no surprise eliminations',score:100,feedbackText:'Correct! Honest communication, specific support, retraining pathways, and no-surprise commitment are the four elements of change management that preserves organizational integrity during AI-driven workforce change.'},
  {text:'Accelerate the reduction timeline to complete the change before anxiety builds in the organization',score:0,feedbackText:'Accelerating to outrun anxiety sacrifices the retraining time and transition support that protect individual employees. Speed reduces the human cost only if it reduces the total reduction volume.'}
]},
{cat:'ai-leadership',d:1,s:'Your team lead reports that the team has stopped questioning AI outputs and treats them as ground truth.',t:'AI over-reliance is a management problem that requires setting explicit norms for when human judgment must override AI recommendations.',options:[
  {text:'Increase AI tool accuracy so the team\'s trust becomes more justified',score:0,feedbackText:'Higher accuracy is always welcome but uncritical acceptance of any tool regardless of accuracy creates systemic fragility. Norms for critical evaluation are necessary independently of tool quality.'},
  {text:'Establish explicit team norms for when AI outputs must be reviewed and questioned, create examples where AI was wrong, and reward team members who catch AI errors',score:100,feedbackText:'Excellent! Explicit review norms, concrete error examples, and reward structures for catching AI mistakes all work together to rebuild appropriate skepticism without undermining the tool\'s value.'},
  {text:'Switch to a different AI tool with built-in uncertainty indicators',score:-100,feedbackText:'Tool design changes help but do not address the team culture of uncritical acceptance. Culture change through norms and examples is more durable than tool-dependent solutions.'}
]},
{cat:'ai-leadership',d:2,s:'As a product leader, you need to decide where to invest AI features first in your product roadmap. Resources are limited.',t:'AI feature prioritization should target use cases where AI\'s specific capabilities solve genuine user problems rather than adding AI features for novelty value.',options:[
  {text:'Add AI to the features where competitors have already added it to remain competitive',score:0,feedbackText:'Matching competitors\' AI features is a reactive strategy. Your users may have different needs than competitors\' users, and genuine differentiation comes from solving problems competitors have not.'},
  {text:'Identify user problems where AI provides a qualitatively better solution than the current approach, prioritize those use cases by user value and feasibility, and build a case for each',score:100,feedbackText:'Correct! Problem-first AI feature prioritization with a value and feasibility filter ensures investment goes to features that users actually want, not features added for marketing.'},
  {text:'Build AI into every feature since the competitive advantage comes from deep AI integration throughout the product',score:-100,feedbackText:'Deep AI integration for its own sake creates complexity without value in features where AI does not improve the user experience. Every AI feature must solve a real user problem to justify its cost.'}
]},
{cat:'ai-leadership',d:1,s:'A direct report came to you with an AI-generated analysis that contradicts your intuition built from ten years of experience. Who is right?',t:'When AI analysis contradicts expert intuition, the right response is to investigate both — neither should be dismissed without examination.',options:[
  {text:'Trust your ten years of experience since AI lacks the contextual knowledge you have built',score:0,feedbackText:'Experience is a powerful input but can also reflect outdated patterns or confirmation bias. AI analysis that contradicts intuition is worth investigating, not automatically dismissing.'},
  {text:'Investigate the discrepancy by examining the AI\'s data sources and assumptions, then test your intuition against the same data to understand why they diverge',score:100,feedbackText:'Excellent! Investigation of the discrepancy is the right response. Understanding why AI and intuition diverge often reveals either a data limitation or an intuition that has drifted from current reality.'},
  {text:'Accept the AI analysis since data-driven insights are more reliable than human intuition',score:-100,feedbackText:'Automatic deference to AI over experienced human judgment is as wrong as automatic dismissal. Both carry information. The investigation of their divergence is the productive response.'}
]},
{cat:'ai-leadership',d:2,s:'You are building a new team specifically to develop AI capabilities for your business unit. You need to decide what skills to hire for.',t:'Effective AI capability teams combine AI/ML technical skills with domain expertise and data engineering — the weakest link in this triad determines team output quality.',options:[
  {text:'Hire the most technically skilled AI/ML engineers you can find and train them in your domain later',score:0,feedbackText:'ML engineering talent without domain context typically builds technically impressive systems that solve the wrong problems. Domain expertise is not easily transferred after hiring.'},
  {text:'Hire a balanced team with AI engineers, data engineers, and domain experts, then create structured collaboration processes so each discipline informs the others',score:100,feedbackText:'Correct! The triad of ML engineering, data engineering, and domain expertise is the full capability stack. Structured collaboration ensures each discipline strengthens the others rather than operating in isolation.'},
  {text:'Hire only domain experts and equip them with no-code AI tools since they understand the business problems best',score:-100,feedbackText:'No-code tools enable experimentation but reach real limits at custom model development and production-scale deployment. Domain expertise without technical depth limits your capability ceiling.'}
]},
{cat:'ai-leadership',d:3,s:'Your company\'s AI-assisted recommendation system has been shown to have subtle gender bias in job promotion suggestions. You are the head of HR.',t:'AI bias in promotion recommendations requires immediate operational response, systemic root cause investigation, and governance redesign to prevent recurrence.',options:[
  {text:'Notify the AI vendor and ask them to fix the bias in the next model update',score:0,feedbackText:'Vendor notification is necessary but insufficient as your only action. The bias is affecting real promotion decisions now. An interim mitigation cannot wait for a vendor update cycle.'},
  {text:'Suspend the AI recommendation component immediately, manually review promotions made using it in the past year, brief the board, and commission a root cause investigation',score:100,feedbackText:'Excellent! Suspension, retroactive review, board briefing, and root cause investigation are the four elements of a complete leadership response to discovered AI bias in a consequential system.'},
  {text:'Add a human review step for all AI-generated recommendations going forward and continue using the system',score:-100,feedbackText:'Adding human review going forward is a necessary step but does not address promotions that already occurred under biased recommendations. Retroactive review and disclosure are required.'}
]},
{cat:'ai-leadership',d:1,s:'You are leading a meeting where the team is heavily debating whether to use AI for a key workflow. The discussion is going in circles.',t:'Unresolved AI adoption debates usually reflect unspoken disagreements about risk tolerance or success criteria that need to be made explicit before the choice can be made.',options:[
  {text:'End the meeting and make the decision yourself since the team cannot reach consensus',score:0,feedbackText:'Unilateral decision-making ends the debate but leaves underlying disagreements unresolved, leading to low commitment in implementation. Surfacing the real disagreement is more effective.'},
  {text:'Reframe the discussion around the specific concern driving resistance and the specific evidence that would resolve it, then design a test or a decision point that settles the question',score:100,feedbackText:'Correct! Surfacing the real concern and designing a testable resolution converts circular debate into a structured path forward. Most AI adoption debates have a specific fear at the center.'},
  {text:'Let the team keep discussing until they reach organic consensus since forcing a decision creates resentment',score:-100,feedbackText:'Circular discussion without facilitated resolution drains energy and produces frustration rather than organic consensus. Leadership intervention to structure the path forward is exactly what the situation requires.'}
]},

// ===== ai-manufacturing (20) =====
{cat:'ai-manufacturing',d:1,s:'A factory floor manager wants to use AI to predict equipment failures before they happen to reduce unplanned downtime.',t:'AI predictive maintenance reduces unplanned downtime by identifying failure precursors in sensor data that scheduled maintenance intervals cannot catch.',options:[
  {text:'Implement AI predictive maintenance immediately and eliminate all scheduled maintenance intervals',score:-100,feedbackText:'AI predictive maintenance supplements scheduled maintenance — it does not eliminate it. Some degradation patterns require time-based inspection regardless of sensor data indicators.'},
  {text:'Pilot AI predictive maintenance on the three highest-downtime machines, measure unplanned outage reduction after 90 days, and validate against your maintenance cost baseline before scaling',score:100,feedbackText:'Correct! Highest-downtime machines provide the best ROI signal for a pilot. 90-day validation against a cost baseline gives you real numbers before committing to full deployment.'},
  {text:'Continue with scheduled maintenance since predictive systems introduce new complexity without proven benefit',score:0,feedbackText:'Predictive maintenance has demonstrated significant downtime reduction in manufacturing environments. Categorical skepticism ignores well-documented industry evidence.'}
]},
{cat:'ai-manufacturing',d:2,s:'An AI visual quality control system flags 15% of products as defective. Your human inspectors reject the AI\'s assessment on 40% of those flags.',t:'High human override rates signal that AI quality thresholds need calibration to match actual defect standards, not that human review should be eliminated.',options:[
  {text:'Trust the AI over human inspectors since humans have inconsistent judgment',score:-100,feedbackText:'A 40% human override rate is strong evidence that the AI\'s rejection threshold does not match your quality standards. Human judgment in this case is valuable calibration data, not noise.'},
  {text:'Analyze which defect types drive the high override rate, recalibrate AI thresholds using the override cases as training data, and measure override rates after recalibration',score:100,feedbackText:'Excellent! Override case analysis plus threshold recalibration plus remeasurement is the right improvement cycle. Human overrides are valuable supervision signal, not system failure.'},
  {text:'Eliminate human review entirely to reduce processing time and accept the 15% rejection rate as the quality standard',score:0,feedbackText:'Accepting AI quality threshold as quality standard without validation against your actual spec is backwards. The AI must match your standards, not define them.'}
]},
{cat:'ai-manufacturing',d:1,s:'Your production line generates terabytes of sensor data daily but you have never used it to improve operations.',t:'Manufacturing sensor data contains actionable patterns about waste, downtime, and quality that AI can extract when raw data has been accumulating unanalyzed.',options:[
  {text:'Wait until you have a dedicated data science team before attempting to use the sensor data',score:0,feedbackText:'Waiting for perfect conditions delays value extraction from data that is already available. Starting with a targeted question on one production line is feasible without a full data team.'},
  {text:'Start with one specific operational question — like which line segment causes most downtime — and use AI to analyze sensor data for that targeted insight before expanding',score:100,feedbackText:'Correct! Targeted question-first analysis produces actionable insight faster than attempting comprehensive analysis of all data at once. One clear question, one clear dataset, one clear outcome.'},
  {text:'Hire a data vendor to analyze all your sensor data and report back with opportunities',score:-100,feedbackText:'Fully delegating data analysis without internal question formulation produces generic insights that do not match your specific operational priorities. Start with your own questions.'}
]},
{cat:'ai-manufacturing',d:2,s:'A robot arm on your production line is AI-controlled and begins making small systematic errors that accumulate into product defects.',t:'AI-controlled equipment errors that accumulate systematically indicate model drift and require retraining or recalibration before defect rates exceed specification.',options:[
  {text:'Recalibrate the robot arm mechanically since the errors must be a hardware issue',score:0,feedbackText:'Mechanical recalibration addresses hardware drift but not AI model drift. Systematic errors in AI-controlled equipment require diagnosis that separates mechanical from model causes.'},
  {text:'Diagnose whether the error pattern indicates model drift by comparing current sensor inputs to training distribution, then retrain the AI component if model drift is confirmed',score:100,feedbackText:'Excellent! Model drift diagnosis before intervention prevents recalibrating the wrong component. Systematic errors in AI systems are often distributional drift — the world has changed outside the training range.'},
  {text:'Revert the robot arm to manual control until the errors stop since AI-controlled equipment is less reliable than human-operated machines',score:-100,feedbackText:'Manual reversion is a valid last resort but a systematic error in AI equipment usually has a diagnosable cause. Diagnosis and targeted fix should precede full reversion.'}
]},
{cat:'ai-manufacturing',d:3,s:'Your AI supply chain optimization model recommended reducing safety stock significantly. A major supplier then had a two-week outage you did not anticipate.',t:'AI supply chain models optimize for historical patterns and cannot predict novel disruption events. Safety stock decisions require human judgment about tail risk scenarios the model has not seen.',options:[
  {text:'Replace the AI model with a more sophisticated one that can handle supply disruptions better',score:0,feedbackText:'More sophisticated models improve historical pattern recognition but cannot predict unprecedented disruption events. No AI model can reliably anticipate supplier outages it has never seen.'},
  {text:'Maintain AI recommendations for routine optimization while establishing risk-adjusted safety stock floors that reflect tail-risk scenarios AI cannot model',score:100,feedbackText:'Correct! AI for routine optimization plus human-determined risk floors for tail scenarios is the right design. The floors should reflect disruption scenarios the model cannot learn from data.'},
  {text:'Discard AI supply chain optimization since it failed to anticipate a real-world disruption',score:-100,feedbackText:'Discarding AI because it failed to predict an unprecedented event misunderstands what AI optimization is for. The right response is defining its role more clearly, not eliminating it.'}
]},
{cat:'ai-manufacturing',d:1,s:'You want to use AI to reduce energy consumption in your factory. The production team is not sure where to start.',t:'Energy optimization AI delivers fastest ROI when applied to the highest-consumption equipment first, using historical consumption data to identify scheduling and setting improvements.',options:[
  {text:'Apply AI energy optimization to every piece of equipment simultaneously',score:0,feedbackText:'Simultaneous deployment across all equipment makes it hard to measure the impact of any individual change and creates complexity that slows the learning cycle.'},
  {text:'Identify your five highest-energy-consuming machines using utility data, pilot AI optimization on those first, and measure consumption reduction before expanding',score:100,feedbackText:'Excellent! High-consumption first with measured pilot results is the right sequence. The pilot gives you validated ROI data before you scale to equipment with smaller energy footprints.'},
  {text:'Hire an energy consultant before using AI since energy optimization requires domain expertise',score:-100,feedbackText:'Energy consultants and AI tools are complementary rather than alternatives. AI processes the continuous sensor data that consultant expertise can help interpret but cannot monitor continuously.'}
]},
{cat:'ai-manufacturing',d:2,s:'Your manufacturing plant wants to use AI-powered autonomous mobile robots to navigate the warehouse floor alongside human workers.',t:'Human-robot collaborative environments require safety system design that guarantees stopping distances and collision avoidance regardless of AI navigation confidence levels.',options:[
  {text:'Deploy autonomous robots after standard equipment safety certification since AI navigation is sufficiently reliable',score:-100,feedbackText:'AI navigation reliability statistics do not satisfy human co-working safety requirements. Safety system design must guarantee safe stopping and collision avoidance even when the AI fails.'},
  {text:'Design dedicated safety zones, require physical collision prevention systems as backup to AI navigation, conduct supervised human-presence testing, and stage rollout by work area',score:100,feedbackText:'Correct! Physical safety systems as backup to AI navigation, human-presence testing, and staged rollout are the safety engineering requirements for human-robot collaborative workspaces.'},
  {text:'Train workers to avoid the robot navigation paths and trust the AI collision avoidance system',score:0,feedbackText:'Worker behavioral accommodation for robot navigation is insufficient as a safety strategy. The safety burden must be on the system, not on human workers to adapt to robot limitations.'}
]},
{cat:'ai-manufacturing',d:1,s:'Your maintenance team wants to use AI to create repair manuals that update automatically as equipment ages and maintenance patterns change.',t:'Living documentation that evolves with actual maintenance history provides more accurate repair guidance than static manuals that go out of date.',options:[
  {text:'Update the maintenance manual annually with the engineering team reviewing changes',score:0,feedbackText:'Annual reviews miss the real-time pattern changes that AI can track continuously. Maintenance documentation that is one year behind current practice leads to suboptimal repair guidance.'},
  {text:'Implement AI that continuously incorporates actual maintenance records into repair guidance, with engineers reviewing AI-suggested changes before they are published',score:100,feedbackText:'Excellent! Continuous incorporation with engineering review balances currency with accuracy. Real-time maintenance pattern updates make documentation a living asset rather than a static artifact.'},
  {text:'Avoid AI documentation since maintenance guidance must be exact and AI introduces imprecision',score:-100,feedbackText:'AI-assisted documentation with engineering review produces more current and accurate guidance than manually updated documents. The review step maintains the precision requirement.'}
]},
{cat:'ai-manufacturing',d:2,s:'An AI production scheduling system suggests running overnight shifts on weekends to maximize throughput. Operators resist the schedule change.',t:'AI scheduling optimization that maximizes throughput without worker input creates operational resistance that reduces actual productivity gains.',options:[
  {text:'Implement the AI schedule since optimized throughput benefits all stakeholders including workers',score:-100,feedbackText:'AI throughput optimization without worker consultation creates schedule changes workers will work around. Actual productivity in shift-dependent manufacturing requires operator buy-in.'},
  {text:'Share the AI recommendation with operators, hear their concerns, adjust the schedule to address legitimate constraints, and measure whether the adjusted schedule still improves throughput',score:100,feedbackText:'Correct! Operator consultation followed by adjusted implementation is more likely to produce sustained throughput gains than imposed optimization. People implement schedules they helped design.'},
  {text:'Ask the AI to generate an alternative schedule that avoids weekend overnight shifts and use that instead',score:0,feedbackText:'Generating an alternative without understanding what constraints drive operator resistance may simply produce a different schedule with different problems. Consultation reveals the real constraints.'}
]},
{cat:'ai-manufacturing',d:3,s:'Your AI production optimization system consistently recommends reducing quality inspection frequency. Output has increased but your recall rate is also increasing.',t:'When AI optimization gains in throughput are offset by quality cost increases, the system is optimizing for the wrong objective function.',options:[
  {text:'Trust the AI since increased output more than compensates for the higher recall rate',score:0,feedbackText:'Recall costs are often underaccounted in throughput models. Customer relationship damage, return logistics, and brand impact from recalls regularly exceed the throughput value the AI gained.'},
  {text:'Update the AI objective function to include quality cost, recall cost, and customer satisfaction impact, then rerun the optimization to find the true efficiency-quality optimum',score:100,feedbackText:'Excellent! Objective function expansion is the correct technical response. AI optimizes exactly what you tell it to optimize — if quality is not in the objective, it will sacrifice quality for throughput.'},
  {text:'Revert to manual scheduling since AI optimization has created more problems than it solved',score:-100,feedbackText:'The problem is not AI optimization — it is an incomplete objective function. Fixing the objectives produces better outcomes than abandoning the optimization capability.'}
]},
{cat:'ai-manufacturing',d:1,s:'Your factory generates production reports that take two days to compile manually each week. You want to automate this with AI.',t:'AI report automation of structured manufacturing data can reduce compilation time from days to hours while improving data freshness and accuracy.',options:[
  {text:'Automate the full report and eliminate the two staff members who currently compile it',score:-100,feedbackText:'Eliminating positions before the automated report has been validated creates operational risk. Validate accuracy in parallel first, then reassign based on confirmed reliability.'},
  {text:'Automate data collection and report generation, run in parallel with manual reports for four weeks, then transition to automated reports after confirming accuracy',score:100,feedbackText:'Correct! Parallel validation before full transition is the responsible path for operational reports. Four weeks provides enough cycles to catch systematic errors before they affect decision-making.'},
  {text:'Automate only data collection and let staff continue to compile the reports manually using the automatically collected data',score:0,feedbackText:'Partial automation reduces but does not eliminate the time cost. Report generation automation is the step that produces the time savings you are targeting.'}
]},
{cat:'ai-manufacturing',d:2,s:'You are evaluating two AI quality control systems. One has higher accuracy but requires extensive custom integration. The other is less accurate but deploys in days.',t:'Quality control AI selection requires balancing deployment speed, integration cost, and accuracy against the cost of defects that escape the system.',options:[
  {text:'Choose the faster deployment since any quality improvement is better than waiting months',score:0,feedbackText:'Deployment speed matters but the accuracy gap has a real cost. Calculate the defect escape rate difference and its financial impact before deciding speed over accuracy is the right trade.'},
  {text:'Model the annual cost of defects the accuracy gap allows to escape, compare to integration cost, and choose the option where the benefit exceeds the cost over a defined horizon',score:100,feedbackText:'Excellent! Defect escape cost modeling versus integration cost is the right framework. The answer depends on your defect cost and integration complexity, not a universal rule.'},
  {text:'Choose the higher-accuracy system regardless of integration complexity since quality standards must not be compromised',score:-100,feedbackText:'Quality standards matter but integration complexity delays all benefit while costing engineering resources. The decision should be grounded in financial analysis of the trade-off.'}
]},
{cat:'ai-manufacturing',d:1,s:'A machine learning engineer suggests using AI to automatically adjust chemical mixing ratios on your pharmaceutical production line.',t:'AI control systems in pharmaceutical manufacturing require FDA validation and robust manual override capability before any autonomous adjustment authority is granted.',options:[
  {text:'Implement AI autonomous chemical adjustment since the engineer\'s tests show it improves yield',score:-100,feedbackText:'Pharmaceutical process changes require FDA validation regardless of internal test results. Autonomous AI adjustment of validated processes creates regulatory compliance violations.'},
  {text:'Run AI as an advisory system that recommends ratio adjustments for human operator approval, while pursuing FDA validation for any future autonomous control authority',score:100,feedbackText:'Correct! Advisory mode with human approval is the only legally compliant AI role for validated pharmaceutical processes. FDA validation must precede any autonomous control authority.'},
  {text:'Test the AI system in non-GMP production only since regulated manufacturing lines cannot use AI',score:0,feedbackText:'GMP manufacturing can use AI but with appropriate validation and control requirements. Non-GMP-only testing limits AI benefit while missing the regulatory pathway that would allow proper use.'}
]},
{cat:'ai-manufacturing',d:2,s:'Your AI demand forecasting system has been predicting demand accurately for two years. This quarter it was significantly off and you over-produced.',t:'Long-accurate AI forecast models can fail suddenly when market conditions change beyond their training distribution — variance monitoring prevents silent model degradation.',options:[
  {text:'Accept this quarter as an outlier since two years of accuracy justifies continued trust in the model',score:-100,feedbackText:'Attributing forecast failure to outlier luck without investigation misses the possibility of model drift. A significant miss after long accuracy often signals a distributional shift the model cannot handle.'},
  {text:'Investigate whether the miss reflects a change in market dynamics outside the model\'s training distribution, and add variance monitoring to detect future drift before it causes large over-production',score:100,feedbackText:'Excellent! Root cause investigation plus drift monitoring prevents recurrence. The question is whether the market changed or the model degraded — both have different remediation paths.'},
  {text:'Add a 20% safety buffer to all future forecasts since AI models have inherent uncertainty',score:0,feedbackText:'Blanket safety buffers add inventory cost without fixing the underlying accuracy problem. Understanding why the model failed and addressing that cause is the right response.'}
]},
{cat:'ai-manufacturing',d:3,s:'An AI model analyzing your supply chain has identified a supplier that appears to be at high risk of failure based on financial and operational signals.',t:'AI supplier risk flags require confidential human verification with the supplier before any procurement action since AI analysis of indirect signals can produce false positives.',options:[
  {text:'Immediately begin reducing orders to the flagged supplier to manage risk exposure',score:0,feedbackText:'Reducing orders before verification could damage a viable supplier relationship or trigger the financial distress the AI wrongly predicted. Verification must precede procurement action.'},
  {text:'Confidentially verify the AI risk signals through direct supplier dialogue and your procurement team\'s market intelligence before making any sourcing changes',score:100,feedbackText:'Correct! Verification through direct contact and market intelligence allows you to act on real risk while avoiding self-fulfilling prophecy actions based on potentially incorrect AI signals.'},
  {text:'Share the AI risk assessment with the supplier to give them a chance to address the identified issues',score:-100,feedbackText:'Sharing AI-generated risk assessments with the assessed supplier creates relationship damage if the assessment is wrong and may trigger the collapse it is trying to prevent if it is right.'}
]},
{cat:'ai-manufacturing',d:1,s:'Workers on your production line are concerned that AI monitoring of their pace and performance feels invasive and is increasing their stress levels.',t:'Worker wellbeing concerns about AI monitoring must be addressed through transparent use of data, limitations on punitive use, and genuine involvement in how monitoring is designed.',options:[
  {text:'Reassure workers that the monitoring is for safety and optimization, not performance evaluation',score:0,feedbackText:'Assurances without structural commitments do not address the concern. Workers need policy protections and involvement in monitoring design, not just verbal reassurance.'},
  {text:'Meet with worker representatives to understand specific concerns, establish clear policies limiting how monitoring data can be used, and involve workers in adjusting what is monitored',score:100,feedbackText:'Excellent! Worker representative engagement, use limitation policies, and participatory design address the specific sources of monitoring stress. Trust requires structural protection, not only verbal assurance.'},
  {text:'Remove the monitoring system entirely since worker wellbeing outweighs operational data benefits',score:-100,feedbackText:'Complete removal may not be necessary. Many monitoring concerns are addressable through policy and design changes that preserve useful data while protecting worker experience.'}
]},
{cat:'ai-manufacturing',d:2,s:'Your AI system controls temperature and pressure in a high-stakes industrial process. A sensor failure provides wrong data to the AI.',t:'AI control systems in high-stakes industrial processes must have sensor validation layers that detect anomalous readings and trigger safe-state failsafe modes rather than acting on corrupted data.',options:[
  {text:'Add redundant sensors to the most critical measurement points to reduce sensor failure risk',score:0,feedbackText:'Redundancy reduces sensor failure frequency but does not address what the AI control system does when a sensor does fail. Failsafe behavior design is the missing element.'},
  {text:'Add sensor anomaly detection that compares readings against physical plausibility bounds, and design the AI to trigger a safe-state mode when anomalous sensor data is detected',score:100,feedbackText:'Correct! Sensor validation plus safe-state failsafe design is the complete safety engineering solution. Both are needed: validation detects the failure, and failsafe defines the response.'},
  {text:'Continue operating since sensor failures are rare and the AI is generally robust',score:-100,feedbackText:'Rare events in high-stakes processes are precisely the cases that require explicit failsafe design. Robustness to corrupted sensor data cannot be assumed — it must be designed and tested.'}
]},
{cat:'ai-manufacturing',d:1,s:'Your company wants to use AI to generate production quotes for custom orders faster. Currently quotes take three days and lose you business.',t:'AI quote generation for custom manufacturing can reduce response time from days to hours when trained on historical quotes and configured with appropriate approval thresholds.',options:[
  {text:'Fully automate all quotes and publish them instantly to win more business',score:-100,feedbackText:'Full automation without approval thresholds will generate incorrect quotes for complex orders. Orders priced wrong are often worse than slow quotes — they create contractual and financial problems.'},
  {text:'Automate standard order quotes up to a defined complexity threshold and have AI generate a draft for complex orders that a sales engineer approves before sending',score:100,feedbackText:'Excellent! Threshold-based automation captures speed improvement for standard orders while preserving human review for complex ones where AI error risk is highest.'},
  {text:'Use AI to gather requirements faster but continue manual quote calculation since pricing accuracy is non-negotiable',score:0,feedbackText:'Requirement gathering AI with manual calculation captures some speed improvement but not the full gain. Threshold-based automation of the calculation step is achievable with appropriate design.'}
]},
{cat:'ai-manufacturing',d:2,s:'You want to use AI to optimize the layout of a new production facility before construction begins.',t:'AI facility layout optimization can test thousands of layout configurations against flow, safety, and capacity criteria in days rather than weeks of manual planning.',options:[
  {text:'Design the layout using traditional industrial engineering methods since facility design is a one-time decision where AI investment may not be worth it',score:0,feedbackText:'Facility layout is actually an ideal AI use case because the decision is consequential, made once, and the cost of a suboptimal layout compounds over the facility\'s lifespan.'},
  {text:'Use AI simulation to test layout configurations against material flow efficiency, safety spacing, and capacity utilization before finalizing, then validate top configurations with your industrial engineers',score:100,feedbackText:'Correct! AI simulation of layout alternatives provides options no manual planning process could evaluate at the same speed. Expert validation of the top options ensures the AI insights translate into practical designs.'},
  {text:'Have AI design the entire facility layout autonomously and build from that output',score:-100,feedbackText:'Autonomous AI facility design without industrial engineering validation risks practical issues with safety codes, workflow realities, and maintenance access that simulation models do not fully capture.'}
]},

]

for(let i=0; i<ALL.length; i+=20) {
  const batch = ALL.slice(i, i+20)
  const cat = batch[0].cat
  process.stdout.write(`Inserting ${batch.length} ${cat} questions... `)
  const ok = await insert(batch)
  if(!ok) { console.error('FAILED at index', i); break }
}
console.log('DONE. Total:', ALL.length)
