const TOKEN = 'sbp_f314cf27b5b2a01eea48048a7b1c015cc9cf4b42'
const API = 'https://api.supabase.com/v1/projects/amhfxaqolholacanqyas/database/query'

function esc(s) { return s.replace(/'/g, "''") }

async function insert(batch) {
  const values = batch.map(q => {
    const opts = JSON.stringify(q.options).replace(/'/g, "''")
    return `('en','${q.cat}','${esc(q.s)}','${esc(q.t)}','${opts}'::jsonb,${q.d},'claude',true)`
  }).join(',')
  const sql = `INSERT INTO questions (locale,category,scenario_text,mindset_tip,options,difficulty,generated_by,is_active) VALUES ${values};`
  const r = await fetch(API, {method:'POST',headers:{'Authorization':`Bearer ${TOKEN}`,'Content-Type':'application/json'},body:JSON.stringify({query:sql})})
  const d = await r.json()
  if(d.message) { console.error('ERR:',d.message.substring(0,120)); return false }
  console.log('OK:', batch.length, 'inserted')
  return true
}

const ALL = [

// ===== ai-career (20) =====
{cat:'ai-career',d:1,s:'You want to update your resume for a data analyst role. You have raw bullet points but the phrasing feels weak.',t:'AI is a great writing partner for resumes — it helps structure and polish language, but you must provide the authentic achievements.',options:[
  {text:'Ask AI to generate an entire resume from scratch based only on the job title',score:-100,feedbackText:'AI-generated resumes without your real experience data produce generic, unverifiable claims that recruiters spot immediately.'},
  {text:'Feed your bullet points to AI and ask it to rephrase them with stronger action verbs and metrics language',score:100,feedbackText:'Correct! AI excels at polishing your real content — stronger verbs and clearer impact language make a genuine difference.'},
  {text:'Keep your existing resume since changing it might make it sound too formal',score:0,feedbackText:'Leaving weak phrasing on the table is a missed opportunity. AI can improve your authentic content without making it feel fake.'}
]},
{cat:'ai-career',d:1,s:'You have a job interview in two days and want to prepare for likely questions about your management experience.',t:'AI-powered mock interviews let you practice handling tough questions so you arrive confident and articulate.',options:[
  {text:'Memorize scripted answers from AI for every possible question',score:-100,feedbackText:'Scripted answers sound rehearsed and break down when interviewers follow up. Practice for fluency, not memorization.'},
  {text:'Use AI to generate likely interview questions and practice answering them out loud, then get feedback on your responses',score:100,feedbackText:'Excellent! Simulated practice with real-time feedback builds genuine confidence and helps you spot gaps in your narratives.'},
  {text:'Skip preparation since your experience speaks for itself',score:0,feedbackText:'Experience matters, but articulating it under pressure takes practice. AI mock interviews are a low-risk way to sharpen your delivery.'}
]},
{cat:'ai-career',d:2,s:'You are considering a career pivot from marketing to UX design. You are unsure which skills you already have and which you need to learn.',t:'AI can map your existing skills to a new field and identify the exact gaps — giving you a concrete learning roadmap instead of guesswork.',options:[
  {text:'Ask AI to list all UX skills and start learning everything from scratch',score:0,feedbackText:'Starting from scratch ignores transferable skills like user psychology and communication that you already have from marketing.'},
  {text:'Have AI analyze your current skill set against UX job descriptions to identify gaps and suggest targeted learning resources',score:100,feedbackText:'Spot on! A gap analysis saves months of learning things you do not need and focuses effort on what actually matters for the role.'},
  {text:'Assume that marketing and UX are too different and abandon the pivot idea',score:-100,feedbackText:'Many marketing skills transfer directly to UX. A data-driven gap analysis reveals the real picture rather than assumptions.'}
]},
{cat:'ai-career',d:2,s:'You want to reach out to three senior professionals on LinkedIn for informational interviews but your messages always feel awkward.',t:'Personalized outreach messages that reference the recipient\'s actual work significantly improve response rates.',options:[
  {text:'Send identical AI-generated template messages to all three contacts at once',score:-100,feedbackText:'Identical templates are obvious and feel disrespectful of the recipient\'s time. Response rates drop sharply with copy-paste messages.'},
  {text:'Research each person\'s background, then use AI to draft personalized messages referencing their specific work and your genuine interest',score:100,feedbackText:'Correct! Personalization shows effort and creates a real hook. AI drafts save time while your research provides the authenticity.'},
  {text:'Avoid outreach entirely and wait for job postings to apply to instead',score:0,feedbackText:'Waiting for postings means competing with hundreds of applicants. Networking expands your access to unadvertised opportunities.'}
]},
{cat:'ai-career',d:2,s:'Your company just announced that your department will adopt a new AI-powered analytics platform in three months. You have no experience with it.',t:'Proactive skill-building before a technology rollout positions you as an early adopter rather than a reluctant follower.',options:[
  {text:'Wait for the official training sessions before learning anything about the tool',score:0,feedbackText:'Official training is valuable but arriving with zero knowledge means you spend training time on basics others already know.'},
  {text:'Use AI tutors and online resources now to build foundational fluency before the rollout',score:100,feedbackText:'Excellent! Getting ahead of a technology change shows initiative and lets you contribute productively from day one of the rollout.'},
  {text:'Resist learning the new tool since your current methods are already effective',score:-100,feedbackText:'Resisting mandated tools creates friction with leadership and colleagues. Adapting early is a professional advantage, not a concession.'}
]},
{cat:'ai-career',d:1,s:'You want to negotiate a higher salary at your annual review. You have no idea what your role pays in the current market.',t:'Data-driven salary negotiations backed by current market research produce better outcomes than gut-feel requests.',options:[
  {text:'Ask for a 20% raise based purely on how long you have been at the company',score:0,feedbackText:'Tenure alone is a weak argument. Employers respond better to market data and demonstrated impact combined.'},
  {text:'Use AI to analyze salary data from multiple sources for your role, location, and experience level, then build your negotiation case around the numbers',score:100,feedbackText:'Correct! Concrete market data shifts the conversation from personal opinion to objective benchmarking, which is harder for employers to dismiss.'},
  {text:'Avoid salary discussions to keep the relationship with your manager positive',score:-100,feedbackText:'Avoiding negotiation costs real money over time. Most managers expect candidates to negotiate and respect those who do it professionally.'}
]},
{cat:'ai-career',d:3,s:'An AI tool claims it can predict whether you will get hired based on your resume. You are tempted to optimize everything it suggests before applying.',t:'AI hiring predictors reflect biases in historical data. Over-optimizing for them can strip away the authentic voice that actually differentiates you.',options:[
  {text:'Follow every optimization suggestion from the AI predictor to maximize your score',score:-100,feedbackText:'Gaming a biased predictor optimizes for the algorithm, not the human reader. Overly keyword-stuffed resumes often feel hollow in person.'},
  {text:'Use AI salary and skill insights as one input while keeping your authentic achievements and voice as the core of your application',score:100,feedbackText:'Balanced approach! AI tools provide useful signals, but your genuine narrative and real accomplishments are what ultimately win offers.'},
  {text:'Ignore all AI tools for job applications since they are unreliable',score:0,feedbackText:'Completely ignoring AI tools means missing useful benchmarking data. The key is using them critically, not blindly.'}
]},
{cat:'ai-career',d:3,s:'You are a freelancer and considering whether to publicly showcase AI-assisted work in your portfolio without disclosing the AI involvement.',t:'Transparency about AI tools in professional work builds long-term trust and aligns with emerging industry norms.',options:[
  {text:'Never disclose AI use since clients might value the work less',score:-100,feedbackText:'Hiding AI involvement is increasingly seen as deceptive. Clients who discover it later feel misled, damaging the relationship irreparably.'},
  {text:'Clearly note where AI assisted your process, emphasizing your curation, judgment, and creative direction as the core skill',score:100,feedbackText:'Excellent! Transparent disclosure repositions you as a skilled AI collaborator rather than hiding a tool, which is itself a valuable differentiator.'},
  {text:'Only disclose AI use if the client specifically asks about your process',score:0,feedbackText:'Reactive disclosure is better than none, but proactive transparency builds stronger client relationships and professional reputation.'}
]},
{cat:'ai-career',d:2,s:'You want to build a personal brand on LinkedIn but struggle to post consistently because writing content takes too much time.',t:'AI can reduce the friction of content creation so you post consistently — but your unique perspective must remain the core.',options:[
  {text:'Let AI generate and post all your LinkedIn content automatically without your review',score:-100,feedbackText:'Fully automated content lacks your authentic voice. Followers and potential employers who meet you in person will notice the disconnect immediately.'},
  {text:'Use AI to draft post outlines and initial drafts based on your ideas, then edit and add your personal perspective before publishing',score:100,feedbackText:'Correct! AI handles the blank-page problem while you provide the ideas and voice. Consistency plus authenticity builds real professional authority.'},
  {text:'Post only when you have enough time to write everything yourself without AI help',score:0,feedbackText:'Waiting for perfect conditions means posting rarely. Consistent presence beats occasional perfect posts for building professional visibility.'}
]},
{cat:'ai-career',d:1,s:'Your manager asked you to prepare a self-evaluation for your performance review. You are not sure how to frame your achievements.',t:'A well-structured self-evaluation quantifies your impact and connects your work to business goals — AI can help you do both.',options:[
  {text:'Write a general list of tasks you completed this year without specific metrics',score:0,feedbackText:'Task lists show activity but not impact. Performance reviews reward demonstrated value, which requires measurable outcomes.'},
  {text:'Use AI to help you structure your achievements in the STAR format and suggest impact metrics you may have overlooked',score:100,feedbackText:'Excellent! Structured frameworks and metric prompts ensure your evaluation is comprehensive and focused on what decision-makers value.'},
  {text:'Exaggerate accomplishments using AI-generated content to sound more impressive',score:-100,feedbackText:'Inflated claims in performance reviews backfire badly. AI should help you present real achievements more effectively, not fabricate them.'}
]},
{cat:'ai-career',d:2,s:'You are applying for jobs in a new industry and your cover letters keep getting rejected. You suspect the language feels too insider-focused for your old field.',t:'Industry-specific language is a key filter in applications. AI can help you translate your experience into the vocabulary of your target industry.',options:[
  {text:'Submit the same cover letter to every company to save time',score:-100,feedbackText:'Generic letters signal low motivation. Hiring managers in competitive industries can spot them instantly and deprioritize them.'},
  {text:'Ask AI to analyze job descriptions in your target industry and help you rephrase your experience using the language and priorities they signal',score:100,feedbackText:'Correct! Industry vocabulary alignment dramatically improves how your background reads to insiders and passes automated screening tools.'},
  {text:'Remove all references to your previous industry to avoid appearing to be a career changer',score:0,feedbackText:'Hiding your background creates gaps. The better approach is translating your experience, not erasing it.'}
]},
{cat:'ai-career',d:3,s:'A recruiter tells you that your LinkedIn profile is being scanned by AI tools that extract keywords before a human ever sees it.',t:'Understanding AI screening tools helps you optimize your profile without sacrificing authenticity or becoming keyword spam.',options:[
  {text:'Fill your LinkedIn profile with every possible AI and tech keyword regardless of whether they reflect your actual skills',score:-100,feedbackText:'Keyword stuffing gets through the bot but fails with humans. Mismatched profiles create awkward interviews and damaged credibility.'},
  {text:'Naturally integrate relevant keywords throughout your profile by using the same terminology employers use in job descriptions for roles you actually qualify for',score:100,feedbackText:'Balanced approach! Authentic keyword alignment passes screening and holds up in human review because the skills are real.'},
  {text:'Ignore keyword optimization since a good recruiter will read between the lines',score:0,feedbackText:'Counting on humans to override the algorithm is risky. Most profiles never reach human review if they fail the automated scan.'}
]},
{cat:'ai-career',d:1,s:'You want to learn prompt engineering to improve your work with AI tools but you do not know where to start.',t:'Practical, hands-on learning beats theory for AI skills. Start with your actual daily tasks and gradually increase complexity.',options:[
  {text:'Enroll in a three-month formal course before trying any AI tools in your real work',score:0,feedbackText:'Formal courses have value but waiting three months to start using AI tools means three months of missed productivity improvement.'},
  {text:'Start using AI tools on a real work task today, learn from the outputs, and refine your prompts iteratively',score:100,feedbackText:'Correct! Hands-on learning with real tasks builds practical skills faster. Each output teaches you something theory never could.'},
  {text:'Ask a colleague to write all your prompts for you until you feel ready',score:-100,feedbackText:'Delegating prompt writing prevents you from developing the core skill. The only way to learn is by doing it yourself.'}
]},
{cat:'ai-career',d:2,s:'You are helping your company define an AI usage policy for employees and need to balance productivity gains with risk management.',t:'Effective AI policies enable productivity while setting clear guardrails for data privacy, accuracy, and accountability.',options:[
  {text:'Ban all AI tools at work to eliminate any potential risks',score:-100,feedbackText:'Blanket bans are unenforceable and push AI usage underground. They also sacrifice competitive productivity gains for theoretical risk avoidance.'},
  {text:'Develop a tiered policy that approves AI for defined tasks, restricts it for sensitive data, and requires human review for customer-facing outputs',score:100,feedbackText:'Excellent! Tiered policies capture productivity benefits while managing specific risks. They also set clear expectations employees can actually follow.'},
  {text:'Allow all employees to use any AI tool freely since restricting them slows innovation',score:0,feedbackText:'Unrestricted use creates real data privacy and accuracy risks. A policy framework that enables innovation while managing risks is better.'}
]},
{cat:'ai-career',d:3,s:'You suspect that AI tools will automate most of your current job tasks within five years. You are unsure whether to upskill or look for a different career.',t:'The jobs most resistant to automation combine judgment, empathy, creativity, and AI oversight — these are the skills worth developing.',options:[
  {text:'Assume AI cannot replace your specific role and continue working as you do today',score:-100,feedbackText:'Assuming immunity is the most dangerous response. The roles that survive automation are those that actively evolved alongside it.'},
  {text:'Audit which parts of your job require uniquely human judgment, then deliberately develop those skills while learning to orchestrate AI for the automatable parts',score:100,feedbackText:'Correct! This is strategic adaptation. You become the person who uses AI tools effectively rather than the person those tools replace.'},
  {text:'Quit your job immediately and retrain for a completely unrelated field that seems AI-proof',score:0,feedbackText:'Radical career changes based on speculation are risky. Most roles will change rather than disappear — strategic upskilling is usually smarter.'}
]},
{cat:'ai-career',d:1,s:'You want to track your job application progress across twenty open positions. The spreadsheet is getting unmanageable.',t:'AI-powered organization tools help you stay on top of multi-track job searches without critical follow-ups slipping through.',options:[
  {text:'Continue manually updating the spreadsheet even as it grows to hundreds of rows',score:0,feedbackText:'Manual tracking works but becomes error-prone at scale. At twenty-plus applications, important follow-up deadlines start getting missed.'},
  {text:'Use an AI-assisted job tracking tool that logs applications, sends follow-up reminders, and flags stale opportunities',score:100,feedbackText:'Excellent! Job search tools reduce cognitive overhead so your mental energy goes to preparation and interviews rather than administration.'},
  {text:'Apply to fewer jobs to make tracking easier',score:-100,feedbackText:'Reducing volume to manage process overhead is backwards. Better tooling lets you scale your search without sacrificing organization.'}
]},
{cat:'ai-career',d:2,s:'You are preparing a presentation to convince leadership to invest in your team\'s AI training program. They are skeptical about ROI.',t:'Decision-makers respond to concrete business outcomes, not abstract technology enthusiasm. Frame AI training in terms of time saved and revenue impact.',options:[
  {text:'Present a list of exciting AI capabilities without connecting them to specific business outcomes',score:-100,feedbackText:'Feature lists do not persuade finance-focused executives. Without ROI framing, AI enthusiasm reads as cost without benefit.'},
  {text:'Calculate the time your team currently spends on automatable tasks, translate that to salary cost, and model the ROI of training against that baseline',score:100,feedbackText:'Correct! Concrete numbers like hours saved per week multiplied by headcount costs make the case undeniable to budget holders.'},
  {text:'Tell leadership that competitors are using AI so you have no choice',score:0,feedbackText:'Competitive pressure is a valid point but not sufficient alone. Pair it with your own ROI data for a compelling argument.'}
]},
{cat:'ai-career',d:3,s:'A headhunter uses AI to screen candidates and gives you feedback that your profile scored low on a key dimension you know is your strength.',t:'AI screening scores are proxies, not truth. Understanding how they work lets you address the signal rather than accepting a flawed verdict.',options:[
  {text:'Accept the AI score as accurate and assume you need to improve that skill from scratch',score:0,feedbackText:'AI scores reflect how your profile is written, not necessarily your actual ability. Accepting the score without investigation is premature.'},
  {text:'Analyze how that dimension is typically signaled in high-scoring profiles and adjust your language to make your actual strength more visible to the algorithm',score:100,feedbackText:'Excellent! This is the right response — understanding what the AI looks for helps you make your genuine strength legible, not fake a new one.'},
  {text:'Argue with the recruiter that the AI screening system is wrong and demand a human review',score:-100,feedbackText:'Confrontation rarely helps. The practical move is to fix how your profile communicates your strength, then resubmit through the proper channel.'}
]},
{cat:'ai-career',d:2,s:'You completed an online AI certification but realize most of your daily work tasks do not seem to use what you learned.',t:'Certificates signal willingness to learn but applied AI skills come from integrating tools into real workflows, not just passing exams.',options:[
  {text:'Keep taking more certifications since more credentials always help your career',score:0,feedbackText:'Additional certificates have diminishing returns without application. Employers increasingly value demonstrated use over credential accumulation.'},
  {text:'Identify one workflow in your current job where you can apply your certification knowledge, implement it, and document the outcome',score:100,feedbackText:'Correct! A real-world application case study is worth ten certificates. It proves practical ability where credentials only prove theoretical exposure.'},
  {text:'List the certification on your resume and mention it in interviews without worrying about applying it',score:-100,feedbackText:'Certificates without demonstrated application are easy to challenge in interviews. The ability to describe real outcomes is far more compelling.'}
]},
{cat:'ai-career',d:1,s:'You want to build a project portfolio to support your job applications but are unsure what kind of projects to include.',t:'Portfolio projects are strongest when they solve real problems you actually encountered. AI can help you scope, build, and document them effectively.',options:[
  {text:'Build generic tutorial projects from YouTube videos to fill out your portfolio',score:0,feedbackText:'Tutorial replicas show you can follow instructions but not that you can solve novel problems. Employers prize original thinking.'},
  {text:'Use AI to help you scope and build projects that solve genuine problems you have personally encountered, then document your decision process',score:100,feedbackText:'Excellent! Projects born from real problems come with authentic stories about constraints and tradeoffs — the substance that impresses interviewers.'},
  {text:'Wait until you have more experience before creating any portfolio items',score:-100,feedbackText:'Waiting for more experience before building your portfolio is circular. Start with what you know — imperfect real projects beat waiting indefinitely.'}
]},

// ===== ai-communication (20) =====
{cat:'ai-communication',d:1,s:'You need to send an important update email to fifty clients about a service change. Your draft is long and unclear.',t:'AI editing assistants are excellent at making long, dense text scannable and action-oriented for busy readers.',options:[
  {text:'Send the draft as-is since the information is all there even if it is long',score:0,feedbackText:'All information present does not mean information will be absorbed. Busy clients scan first and read details only when compelled.'},
  {text:'Ask AI to restructure the email with a clear subject line, key point up front, and action items in bullet form',score:100,feedbackText:'Correct! Structure-first communication respects client time and dramatically increases the chance your message is read and acted on.'},
  {text:'Delegate the email entirely to AI without reviewing it before sending to all fifty clients',score:-100,feedbackText:'Sending AI-drafted client communications without review risks factual errors, wrong tone, or missing context that erodes client trust.'}
]},
{cat:'ai-communication',d:1,s:'Your team uses Slack and emails in both English and German. Non-native speakers on your team often miss nuances in messages.',t:'AI translation and localization tools can bridge language gaps in diverse teams, but human context still matters for tone and subtext.',options:[
  {text:'Insist that all team communication happen in one language to avoid confusion',score:0,feedbackText:'Forcing a single language excludes native fluency. Multilingual AI tools can support both languages without sacrificing anyone\'s ability to communicate.'},
  {text:'Use AI translation tools for key communications and encourage team members to flag when nuance seems lost in translation',score:100,feedbackText:'Excellent! AI translation plus human feedback creates a feedback loop that catches the nuance gaps tools alone miss.'},
  {text:'Assume team members will ask if they do not understand something and do not take additional steps',score:-100,feedbackText:'Many people will not admit confusion, especially in cross-cultural settings. Proactive translation support removes the burden from individuals.'}
]},
{cat:'ai-communication',d:2,s:'You are drafting a difficult email to a colleague who gave poor work and you need to give critical feedback professionally.',t:'Feedback that separates behavior from character and focuses on future improvement is received far better than accusatory language.',options:[
  {text:'Let AI generate the entire feedback email without providing any of your specific observations',score:-100,feedbackText:'Generic AI feedback lacks the specific observations needed to be actionable. It also signals to the recipient that you did not engage seriously.'},
  {text:'Write your observations, then use AI to help restructure the message to focus on impact and improvement rather than blame',score:100,feedbackText:'Correct! Your observations provide the substance. AI helps you frame them constructively so the recipient can hear and act on the feedback.'},
  {text:'Avoid the email entirely and hope the poor work improves on its own',score:0,feedbackText:'Avoiding feedback allows problems to compound. Clear, professional feedback is a management responsibility that AI can help you deliver well.'}
]},
{cat:'ai-communication',d:2,s:'You want to present complex technical findings to a non-technical board. Your slide deck is filled with jargon and charts.',t:'Translating technical content for executive audiences means leading with business impact first and explaining only the necessary mechanisms.',options:[
  {text:'Present all the technical details so the board has the full picture to make decisions',score:0,feedbackText:'Executives need conclusions with key supporting evidence, not raw data. Overloading non-technical audiences causes them to tune out.'},
  {text:'Use AI to help you identify the three business-impact takeaways from your findings and rebuild the deck around those',score:100,feedbackText:'Excellent! Leading with impact and limiting yourself to three key points is the structure boards respond to. AI helps you find and frame those points.'},
  {text:'Remove all charts and replace them with text paragraphs for clarity',score:-100,feedbackText:'Visual data is powerful when designed for the audience. Removing charts entirely is not the answer — replacing complex ones with simple visuals is.'}
]},
{cat:'ai-communication',d:1,s:'You need to write weekly project status updates for your manager. Each report takes you an hour even though the actual content is minimal.',t:'Templated AI writing assistants can reduce administrative writing time so you spend effort on the thinking, not the formatting.',options:[
  {text:'Continue writing each report from scratch since consistency matters',score:0,feedbackText:'Writing from scratch guarantees consistency but at unsustainable time cost. A good template preserves consistency while eliminating redundant effort.'},
  {text:'Build a status update template with AI, then fill in only the changing elements each week',score:100,feedbackText:'Correct! Template-driven reporting is a productivity multiplier. You provide the new information; AI handles the consistent structure and phrasing.'},
  {text:'Stop writing weekly updates and only report when there is a major issue',score:-100,feedbackText:'Irregular reporting creates anxiety and information gaps for managers. Regular cadence with efficient tools is the sustainable solution.'}
]},
{cat:'ai-communication',d:2,s:'A vendor sent you a 40-page contract to review before next week\'s meeting. You do not have time to read it fully.',t:'AI contract summarizers can extract key clauses and flag unusual terms, but critical agreements always need a final human review.',options:[
  {text:'Sign the contract without review since the vendor is trustworthy',score:-100,feedbackText:'Trusting vendors without reviewing contracts is a legal risk regardless of the relationship. Key clause surprises are common even with known partners.'},
  {text:'Use an AI document tool to summarize the key terms, flag unusual clauses, and prepare targeted questions for the meeting',score:100,feedbackText:'Excellent! AI extraction saves hours and makes sure you ask the right questions in the meeting. Human judgment still applies to the flagged items.'},
  {text:'Ask a junior team member to skim it and report back',score:0,feedbackText:'Junior review without structured guidance often misses critical details. AI-assisted review with specific flags is more reliable than casual skim.'}
]},
{cat:'ai-communication',d:3,s:'Your company sends newsletters to 10,000 subscribers. Open rates have dropped 40% over the past year.',t:'AI-powered personalization and A/B testing can recover declining engagement, but only if you understand why engagement dropped first.',options:[
  {text:'Ask AI to rewrite the newsletter with more exclamation points and urgency language',score:-100,feedbackText:'Adding urgency language to an already disengaged audience accelerates unsubscribes. Diagnosing the root cause must come before tactical changes.'},
  {text:'Use AI to analyze open and click patterns by segment, form a hypothesis about the drop, then test personalized content variants',score:100,feedbackText:'Correct! Data-driven diagnosis before intervention is the right sequence. AI helps you find the pattern — then you design the hypothesis to test.'},
  {text:'Increase send frequency to give subscribers more chances to engage',score:0,feedbackText:'Sending more of content that is already failing will accelerate disengagement. Frequency is not a substitute for relevance.'}
]},
{cat:'ai-communication',d:2,s:'You need to document a complex technical process for a team handbook. Colleagues have tried before but the docs always get outdated quickly.',t:'Living documentation maintained with AI assistance stays current because updating it becomes less effort than avoiding it.',options:[
  {text:'Write a comprehensive 50-page handbook one time and call it done',score:0,feedbackText:'One-time documentation is better than none but becomes a liability as it ages. The effort barrier to updating large docs is why they go stale.'},
  {text:'Create modular documentation with AI assistance, establish a lightweight update workflow, and use AI to flag inconsistencies when processes change',score:100,feedbackText:'Excellent! Modular structure plus a low-friction update workflow keeps docs current. AI spotting inconsistencies is the key to long-term accuracy.'},
  {text:'Abandon documentation efforts since everyone always goes outdated anyway',score:-100,feedbackText:'Abandoning documentation creates dependency on tribal knowledge and makes onboarding painful. Better tooling solves the maintenance problem.'}
]},
{cat:'ai-communication',d:1,s:'You are preparing talking points for a difficult conversation with your team about a missed deadline. You want to be direct without being demotivating.',t:'Factual, non-judgmental communication that focuses on what went wrong and how to fix it is more effective than emotional framing.',options:[
  {text:'Let emotions guide the conversation and address the missed deadline as it comes up naturally',score:0,feedbackText:'Unstructured emotional conversations often derail. Prepared talking points keep you focused on facts and forward direction.'},
  {text:'Use AI to help you structure talking points that acknowledge the impact, identify contributing factors, and close with clear next steps',score:100,feedbackText:'Correct! Structure prevents you from rambling under stress. AI-prepared talking points let you be clear and empathetic simultaneously.'},
  {text:'Send an email instead of having the conversation to avoid emotional responses',score:-100,feedbackText:'Difficult conversations about team performance need to happen in real time where tone and dialogue allow for genuine resolution.'}
]},
{cat:'ai-communication',d:3,s:'You notice that AI-generated emails in your company are increasingly indistinguishable from human ones. Clients cannot tell the difference.',t:'As AI communication becomes invisible, the value shifts from production efficiency to strategic judgment about what to communicate and when.',options:[
  {text:'Use AI to automate all client communications since they cannot tell the difference anyway',score:-100,feedbackText:'When every message feels the same, clients disengage. The communications that break through will be those with demonstrable human thought and care.'},
  {text:'Use AI for routine communications and reserve authentic human-written messages for moments that require genuine relationship investment',score:100,feedbackText:'Excellent! Selective human communication becomes a differentiator. Clients notice when a message feels genuinely personal, especially amid a flood of automated text.'},
  {text:'Stop using AI for communication to ensure all messages are authentically human',score:0,feedbackText:'Full manual communication is unsustainable at scale. The strategic question is not whether to use AI but which communications require human depth.'}
]},
{cat:'ai-communication',d:2,s:'You want to improve your public speaking skills for conference presentations. You deliver content well but struggle with audience questions.',t:'Anticipating audience questions and rehearsing concise answers is a skill AI can help you systematically build.',options:[
  {text:'Avoid taking questions at presentations to reduce pressure',score:-100,feedbackText:'Cutting Q&A removes one of the most valuable parts of conference talks. It also signals lack of mastery to audiences who notice.'},
  {text:'Feed your presentation to AI, ask it to generate the hardest questions an audience might ask, and practice answering each one under time pressure',score:100,feedbackText:'Correct! Anticipatory practice with AI-generated challenges builds genuine fluency. The questions you most dread asking are the ones worth rehearsing most.'},
  {text:'Rely on your expertise to answer questions naturally since you know the material',score:0,feedbackText:'Domain expertise does not automatically produce clear, concise spoken answers under pressure. Deliberate practice always outperforms assuming you will perform.'}
]},
{cat:'ai-communication',d:1,s:'You manage a remote team across four time zones and want to make your written updates clearer so fewer people misinterpret them.',t:'Clear asynchronous writing anticipates ambiguity and eliminates it before the message is sent, saving multiple back-and-forth clarification cycles.',options:[
  {text:'Add more words to explain everything in detail in each message',score:0,feedbackText:'More words often add more ambiguity. Clear writing is concise and structured, not long. Detail should serve the reader, not the writer\'s anxiety.'},
  {text:'Ask AI to review your drafts and flag any sentence that could be misread, then rewrite those before sending',score:100,feedbackText:'Excellent! A second-pass ambiguity check catches the sentences you are blind to because you know what you meant. AI is a reliable fresh eye.'},
  {text:'Schedule a weekly call to explain all written updates verbally in case of misunderstanding',score:-100,feedbackText:'Replacing clear writing with verbal follow-up adds meeting load to everyone. Better writing eliminates the need for the call.'}
]},
{cat:'ai-communication',d:3,s:'Your AI writing assistant has started adapting so closely to your style that colleagues assume you wrote everything without assistance.',t:'AI that mirrors your style so well it is invisible changes the ethics conversation — disclosure becomes a matter of professional integrity, not detection.',options:[
  {text:'Never disclose AI use since detection is impossible and disclosure creates unnecessary doubt',score:-100,feedbackText:'Invisible AI use does not eliminate the ethical question. Professional integrity means being honest about your process regardless of detection risk.'},
  {text:'Be transparent about using AI writing assistance when the context calls for it, particularly in formal deliverables or when your writing is being evaluated',score:100,feedbackText:'Correct! Contextual disclosure is the right frame. Not every email requires a disclaimer, but deliverables tied to your expertise should acknowledge AI input.'},
  {text:'Stop using AI writing tools since the line between your writing and AI writing has become too blurry',score:0,feedbackText:'The tool itself is not the problem. Developing clear personal guidelines for when and how to disclose is the more constructive response.'}
]},
{cat:'ai-communication',d:2,s:'You want to create a chatbot for your company\'s website to answer common customer questions.',t:'Effective customer chatbots are trained on accurate, current information and have a clear escalation path to humans for edge cases.',options:[
  {text:'Launch the chatbot as soon as it is configured, with no test period',score:-100,feedbackText:'Untested chatbots often give wrong answers to real customers. A test period catches the failure modes before they damage customer relationships.'},
  {text:'Test the chatbot internally with your toughest common questions, define escalation criteria, and set up monitoring for poor responses',score:100,feedbackText:'Excellent! Structured testing plus monitoring turns a chatbot from a liability into an asset. Escalation paths maintain quality where AI reaches its limits.'},
  {text:'Use the chatbot for all questions including complex complaints since it is faster than human support',score:0,feedbackText:'Routing complex complaints to a chatbot frustrates customers who already feel unheard. Knowing where the human handoff is critical for satisfaction.'}
]},
{cat:'ai-communication',d:1,s:'You want to summarize a one-hour recorded team meeting so absent colleagues can catch up without watching the full recording.',t:'AI transcription and summarization tools can turn an hour-long recording into a five-minute read without losing key decisions.',options:[
  {text:'Write a manual summary from memory after the meeting without reviewing the recording',score:0,feedbackText:'Memory-based summaries miss details and embed your perspective on what mattered. A transcript-based summary is more accurate and complete.'},
  {text:'Use an AI transcription tool to generate a transcript and then have AI summarize the key decisions, action items, and open questions',score:100,feedbackText:'Correct! Transcript-based AI summaries are comprehensive, accurate, and produced in minutes. They respect absent colleagues\' time without losing substance.'},
  {text:'Send the full recording link and let absent colleagues watch whatever parts they care about',score:-100,feedbackText:'Expecting colleagues to watch a full recording to catch up is a significant time burden. Structured summaries are a professional courtesy that gets used.'}
]},
{cat:'ai-communication',d:2,s:'Your team is drafting a new client proposal and wants to make it feel personalized to the specific client rather than a standard template.',t:'Client proposals that reference the client\'s specific challenges and language feel more credible than generically formatted templates.',options:[
  {text:'Use the same proposal template for all clients and change only the client name',score:-100,feedbackText:'Name-swapped templates are transparent to clients and signal low effort. They rarely win competitive deals against genuinely tailored proposals.'},
  {text:'Research the client\'s public communications and use AI to identify their key priorities, then tailor the proposal language to mirror those themes',score:100,feedbackText:'Excellent! Mirroring the client\'s own language back in your proposal signals genuine understanding. AI helps you do this at scale without a full research team.'},
  {text:'Manually write every proposal completely from scratch to demonstrate effort',score:0,feedbackText:'Full manual writing is time-intensive and often adds little if the structure is similar. A smart template plus targeted personalization is more efficient and equally credible.'}
]},
{cat:'ai-communication',d:3,s:'AI summarization tools have made it possible for executives to stay informed with minimal reading. You worry important nuance is being lost.',t:'AI summaries excel at extracting facts but can miss tone, subtext, and the significance of what was omitted — human judgment fills that gap.',options:[
  {text:'Replace all executive reading with AI summaries to maximize their time efficiency',score:-100,feedbackText:'Full reliance on AI summaries strips out the signal that lives in how something is written, not just what it says. Important nuance gets filtered out.'},
  {text:'Use AI summaries as the first pass and flag specific source documents for human reading when the content is strategic, sensitive, or ambiguous',score:100,feedbackText:'Correct! AI summaries as triage tools, not replacements. The judgment about which documents warrant direct engagement is itself a high-value human skill.'},
  {text:'Avoid AI summaries and require all executives to read everything in full to ensure nothing is missed',score:0,feedbackText:'Full reading is unrealistic at executive scale and does not guarantee better decisions. The challenge is improving AI summary quality, not abandoning them.'}
]},
{cat:'ai-communication',d:1,s:'You are writing a social media post about a new product launch and want to make it engaging without sounding like typical marketing copy.',t:'Authentic social content that speaks like a person rather than a brand consistently outperforms polished but generic marketing language.',options:[
  {text:'Use AI to generate the most persuasive possible marketing language for the post',score:0,feedbackText:'Persuasive marketing templates often trigger the audience\'s spam filter. Authentic, slightly less polished content reads as real and earns more engagement.'},
  {text:'Tell AI the story behind the product, who it helps, and the tone you want, then use its draft as a starting point and make it sound more like your actual voice',score:100,feedbackText:'Excellent! Starting with your story then refining AI output with your voice produces content that is both polished and human. That combination is rare and effective.'},
  {text:'Write the post entirely yourself since social media requires an authentic voice that AI cannot capture',score:-100,feedbackText:'AI absolutely cannot capture your voice alone — but it is a great collaborator. The combination of your story and AI structuring usually beats either alone.'}
]},
{cat:'ai-communication',d:2,s:'Your customer support team receives 500 tickets per day. You want to use AI to categorize and prioritize them but your manager worries it will miss urgent issues.',t:'AI triage systems need a confidence threshold below which urgent-sounding tickets are escalated to human review rather than auto-routed.',options:[
  {text:'Implement AI routing for all tickets since the volume is too high for manual handling',score:0,feedbackText:'Full AI routing without a human review threshold creates risk for the most sensitive tickets. Efficiency must not come at the cost of urgent case accuracy.'},
  {text:'Set up AI categorization with a defined escalation rule that routes any ticket with urgent keywords or low confidence scores directly to senior agents',score:100,feedbackText:'Correct! Hybrid triage — AI handles the confident cases, humans handle the uncertain and urgent ones — delivers both efficiency and quality at scale.'},
  {text:'Continue manual ticket handling to ensure no urgent issues are missed',score:-100,feedbackText:'At 500 tickets per day, manual handling leads to burnout and inconsistent prioritization. Smart automation with human override is the right model.'}
]},
{cat:'ai-communication',d:1,s:'You need to translate your company\'s product documentation from English into Spanish for a new market launch.',t:'AI translation is fastest for volume but technical documentation requires specialized review to ensure terms are accurate and consistent.',options:[
  {text:'Publish the AI translation directly without review since Spanish-speaking staff said the translation sounded fine',score:-100,feedbackText:'General fluency approval is not sufficient for technical docs. Incorrect terminology in manuals creates support burdens and can create safety issues.'},
  {text:'Use AI for the initial translation, then have a native Spanish speaker with domain expertise review and correct terminology and style',score:100,feedbackText:'Excellent! AI provides the volume, domain expertise provides the accuracy. For technical documentation this combination is both efficient and responsible.'},
  {text:'Hire a full translation agency instead of using AI since accuracy is critical',score:0,feedbackText:'Full agency translation is accurate but slow and expensive for updates. AI plus expert review achieves comparable quality at a fraction of the time and cost.'}
]},

// ===== ai-cost-business (20) =====
{cat:'ai-cost-business',d:1,s:'Your manager asks you to calculate whether an AI writing tool at $50/month per user is worth buying for a team of 20.',t:'ROI calculations for AI tools convert time saved per user per week into annual salary cost to compare against subscription cost.',options:[
  {text:'Approve the purchase immediately since AI tools always pay for themselves',score:-100,feedbackText:'Blanket approval without an ROI calculation skips the business case. Not every AI tool delivers value proportional to its cost for every team.'},
  {text:'Survey the team on current hours spent on writing tasks, estimate time saved, convert to cost, and compare to $12,000 annual subscription cost',score:100,feedbackText:'Correct! Time-saved-to-salary-cost conversion is the standard ROI model. If one hour saved per user per week is worth $15 per hour, the math is quick.'},
  {text:'Decline the purchase since the team is already productive without it',score:0,feedbackText:'Declining without analysis means potentially leaving significant value on the table. Running the numbers takes an hour and answers the question properly.'}
]},
{cat:'ai-cost-business',d:2,s:'Your startup is evaluating three AI infrastructure providers. One is 30% cheaper but has had two major outages in the past year.',t:'Total cost of downtime must be calculated and compared against subscription savings before infrastructure cost decisions are made.',options:[
  {text:'Choose the cheapest provider since infrastructure costs directly impact your burn rate',score:0,feedbackText:'Cheapest upfront is not cheapest overall if downtime is costly. A two-hour outage during peak traffic can exceed months of subscription savings.'},
  {text:'Model the revenue impact of each historical outage pattern against the cost delta, then decide based on total expected cost including downtime risk',score:100,feedbackText:'Excellent! Risk-adjusted cost modeling is the right framework. Downtime cost includes lost revenue, engineering time, and customer churn, not just the hours offline.'},
  {text:'Choose the most expensive provider since price correlates with reliability',score:-100,feedbackText:'Price and reliability do not always correlate. Model the actual downtime data rather than assuming premium pricing means better performance.'}
]},
{cat:'ai-cost-business',d:1,s:'Your team is spending $3,000/month on an AI analytics platform but only two of your ten team members use it regularly.',t:'AI tool sprawl creates cost waste when adoption is low. Usage audits and consolidation are a standard cost optimization strategy.',options:[
  {text:'Keep paying since any tool someone finds useful is worth having available',score:-100,feedbackText:'Low adoption tools are a significant budget drain. A $36,000 annual tool used by two people rarely justifies its cost without exceptional ROI from those users.'},
  {text:'Audit usage, interview the two active users about value delivered, and either negotiate a lower seat count or replace with a cheaper tool that meets their needs',score:100,feedbackText:'Correct! Usage audits followed by renegotiation or replacement are standard SaaS cost optimization moves. Most vendors prefer reduced contracts to churn.'},
  {text:'Mandate that all team members use the tool to justify the subscription cost',score:0,feedbackText:'Forcing tool adoption rarely produces genuine engagement. The better question is whether two users generate enough value to justify the cost.'}
]},
{cat:'ai-cost-business',d:2,s:'You are choosing between building a custom AI solution in-house or buying a vendor platform. The custom build would cost $200K upfront.',t:'Build vs. buy decisions for AI require honest assessment of maintenance cost, time to value, and differentiation before committing to custom development.',options:[
  {text:'Always build custom since proprietary AI is a competitive advantage',score:-100,feedbackText:'Custom AI is a competitive advantage only if the problem is truly unique. For commodity tasks, vendor platforms deliver better value at lower total cost.'},
  {text:'Assess whether the capability is differentiating, whether the vendor platform meets 80% of needs, and whether $200K buys more business value than the alternative uses of that capital',score:100,feedbackText:'Excellent! Build vs. buy is always a capital allocation decision. Differentiation and total cost of ownership, including maintenance, should drive it.'},
  {text:'Choose the vendor platform since it is always cheaper than building',score:0,feedbackText:'Vendor platforms can become expensive at scale through licensing and data costs. The analysis depends heavily on volume, customization needs, and team capacity.'}
]},
{cat:'ai-cost-business',d:2,s:'You run a retail business and an AI-powered inventory forecasting tool vendor promises it will reduce your overstock by 30%.',t:'Vendor ROI claims should always be validated against your own data before committing to multi-year contracts.',options:[
  {text:'Sign the three-year contract based on the vendor\'s promise since 30% overstock reduction would be transformative',score:-100,feedbackText:'Vendor ROI claims are optimistic by design. Long-term contracts based on unvalidated promises lock you in without recourse if the numbers do not materialize.'},
  {text:'Run a 90-day pilot on one product category, measure actual overstock reduction against the vendor\'s claim, then decide on the full contract',score:100,feedbackText:'Correct! Pilot validation with your own data is the right framework before multi-year commitment. Real-world performance often differs significantly from vendor benchmarks.'},
  {text:'Negotiate a shorter one-year contract and decide based on results',score:0,feedbackText:'A shorter contract is better than a three-year lock-in but a pilot before any contract gives you negotiating leverage and validation at the same time.'}
]},
{cat:'ai-cost-business',d:1,s:'You want to use AI to reduce the time your team spends on manual data entry by connecting systems that do not currently talk to each other.',t:'Integration costs for AI automation should include API fees, developer time, and ongoing maintenance, not just the initial setup.',options:[
  {text:'Connect the systems yourself quickly using a no-code automation tool and launch it next week',score:0,feedbackText:'No-code tools are a great starting point but underestimating maintenance needs is common. Factor in how the integration breaks when source systems update.'},
  {text:'Map the full cost including developer time, API costs, and maintenance burden before committing, and compare to the long-term value of hours saved',score:100,feedbackText:'Excellent! Full lifecycle cost modeling before automation projects prevents the common pattern of building integrations that cost more to maintain than they save.'},
  {text:'Hire additional data entry staff since automation is too complex',score:-100,feedbackText:'Hiring for manually-avoidable labor is an unsustainable cost choice. A proper cost analysis usually shows automation winning beyond a modest volume threshold.'}
]},
{cat:'ai-cost-business',d:3,s:'Your company\'s AI API costs have grown from $2K to $15K/month in six months as usage scaled. Leadership is concerned.',t:'Unmonitored AI API costs scale non-linearly with usage. Proactive cost controls like caching, model tiering, and usage quotas prevent surprises.',options:[
  {text:'Reduce all AI features to control costs even if it impacts product quality',score:0,feedbackText:'Reducing features is a blunt instrument. The better approach is identifying which calls have the highest cost-to-value ratio and optimizing those specifically.'},
  {text:'Implement usage dashboards by feature, add caching for repeated queries, and route lower-stakes requests to cheaper model tiers',score:100,feedbackText:'Correct! Layered optimization addresses AI cost scaling: caching eliminates redundant calls, model tiering matches cost to complexity, and visibility drives accountability.'},
  {text:'Accept the cost increase since it means the product is growing in usage',score:-100,feedbackText:'Uncapped API costs become a margin problem even with revenue growth. Usage growth does not automatically justify cost growth if efficiency improvements are possible.'}
]},
{cat:'ai-cost-business',d:2,s:'You are evaluating whether to replace your human customer support team with AI chatbots to reduce costs by 60%.',t:'Customer service automation ROI must account for churn from poor bot experiences, not just the headcount savings it generates.',options:[
  {text:'Replace the entire support team with AI chatbots immediately since 60% cost savings is transformative',score:-100,feedbackText:'Customer satisfaction costs are not in the 60% saving projection. Poor bot experiences drive churn that can exceed the labor savings within a year.'},
  {text:'Automate routine queries with AI while retaining human agents for complex issues, measuring both support costs and customer satisfaction before deciding on further automation',score:100,feedbackText:'Excellent! Hybrid models capture efficiency gains while protecting the customer satisfaction that drives retention. Measuring both sides of the ledger is essential.'},
  {text:'Keep the full human team since customers always prefer human support',score:0,feedbackText:'Many customers actually prefer fast AI resolution for simple issues. The question is which query types suit automation, not whether automation is acceptable at all.'}
]},
{cat:'ai-cost-business',d:1,s:'Your marketing team wants to use AI to generate content and reduce the agency budget by eliminating external writers.',t:'AI content generation reduces production costs but still requires skilled human oversight for quality, strategy, and brand voice control.',options:[
  {text:'Cancel all agency contracts immediately and generate all content with AI to cut costs',score:-100,feedbackText:'Abrupt elimination of content expertise without replacement creates quality gaps. AI output still requires human direction, editing, and strategy — that expertise costs money.'},
  {text:'Pilot AI content generation for one content type, measure quality and efficiency, and reallocate agency budget toward higher-value strategy work',score:100,feedbackText:'Correct! Controlled pilots identify which content types AI handles well before committing. Shifting agency spend to strategy is smarter than eliminating it entirely.'},
  {text:'Keep all agency contracts since AI content lacks brand authenticity',score:0,feedbackText:'AI content can achieve authentic brand voice with proper guidelines and oversight. Dismissing it wholesale means missing significant cost reduction potential.'}
]},
{cat:'ai-cost-business',d:3,s:'You discover that your company has subscriptions to nine different AI tools with overlapping features. Total spend is $180K annually.',t:'AI tool consolidation requires capability mapping against actual needs to identify redundancy without cutting tools that drive unique value.',options:[
  {text:'Cancel all tools immediately and restart with one comprehensive platform',score:-100,feedbackText:'Blanket cancellation disrupts teams relying on specific tools and loses unique features that a single platform may not replicate. Audit first.'},
  {text:'Map each tool\'s actual use cases and users, identify overlaps, then consolidate to three platforms that cover all active needs',score:100,feedbackText:'Excellent! Usage audit plus capability mapping is the right consolidation approach. Targeting a 3-5 platform portfolio is a reasonable outcome for most organizations.'},
  {text:'Keep all tools since specialization has value even with overlap',score:0,feedbackText:'Some specialization is valuable but nine tools with significant overlap represents cost duplication. Consolidation analysis finds where redundancy exists without assuming all overlap is waste.'}
]},
{cat:'ai-cost-business',d:2,s:'A salesperson claims your company can save $500K annually by switching to their AI procurement tool. They offer a free trial.',t:'Savings claims from vendors should always be validated against your own procurement data in a controlled trial before purchase decisions.',options:[
  {text:'Purchase the tool immediately since $500K savings justifies any reasonable subscription cost',score:-100,feedbackText:'Vendor savings claims are almost always based on favorable assumptions. Purchasing before validation risks the contract before the saving is proven.'},
  {text:'Run the free trial on a representative sample of your real procurement transactions and measure actual savings, then extrapolate to the annual figure',score:100,feedbackText:'Correct! Vendor savings claims need your own validation data, not their benchmark cases. The trial is valuable only if run on real transactions at sufficient volume.'},
  {text:'Ask for case studies from similar companies before deciding',score:0,feedbackText:'Case studies from other companies are useful directional evidence but do not account for your specific procurement patterns. Your own trial data is more reliable.'}
]},
{cat:'ai-cost-business',d:1,s:'Your finance team wants to use AI to generate financial reports that currently take two analysts two days each month.',t:'AI financial reporting automation can save significant labor costs but requires strong data governance and output validation protocols.',options:[
  {text:'Automate the reports entirely and reassign both analysts to other tasks immediately',score:0,feedbackText:'Immediate redeployment before validation creates risk. The first few automated reports should run in parallel with the manual process to verify accuracy.'},
  {text:'Implement AI report generation, run in parallel with manual reports for three months to validate accuracy, then transfer ownership when confidence is high',score:100,feedbackText:'Excellent! Parallel running validation is the responsible automation path for financial reports. Three months of parallel data builds justified confidence before full cutover.'},
  {text:'Avoid automating financial reports since financial data requires human judgment',score:-100,feedbackText:'Many elements of financial reporting are rule-based and well-suited to automation. Avoiding automation categorically means foregoing real analyst time that could go to higher-value analysis.'}
]},
{cat:'ai-cost-business',d:2,s:'Your e-commerce store wants to use AI for dynamic pricing but you are concerned it could accidentally undercut competitors to unprofitable levels.',t:'AI dynamic pricing needs floor and ceiling guardrails to ensure automated price changes never move outside pre-defined margin boundaries.',options:[
  {text:'Deploy the AI pricing engine and monitor results after launch',score:0,feedbackText:'Post-launch monitoring is necessary but insufficient as the only safeguard. By the time you see a pricing error, you may have already sold at a loss at scale.'},
  {text:'Define hard price floors based on fully-loaded costs, configure AI pricing to operate only within approved boundaries, and set alerts for prices near the floor',score:100,feedbackText:'Correct! Guardrails before deployment prevent the error, not just detect it. AI pricing engines need cost-floor constraints baked in before being trusted with live transactions.'},
  {text:'Avoid AI pricing entirely and continue with manual price setting',score:-100,feedbackText:'Manual pricing at e-commerce scale fails to respond quickly enough to competitor moves. Smart AI pricing with guardrails is far more competitive than manual.'}
]},
{cat:'ai-cost-business',d:3,s:'Your investors push you to cut AI R&D spending to reduce burn rate. But your competitive advantage is built on your proprietary AI capabilities.',t:'Cutting AI investment to manage burn can damage long-term competitive position when AI is the core differentiator.',options:[
  {text:'Cut all AI R&D immediately to extend runway since survival is the priority',score:0,feedbackText:'Runway extension matters, but indiscriminate R&D cuts can eliminate the differentiation that makes you fundable at all. Strategic cuts beat blanket reductions.'},
  {text:'Distinguish between AI capabilities that are core differentiators and those that are commodity features, cut commodity AI spending while protecting the differentiating investment',score:100,feedbackText:'Excellent! Strategic triage in R&D spending protects competitive moat while still reducing burn. The key is clearly distinguishing what makes you different from what makes you functional.'},
  {text:'Reject all investor pressure to cut AI spending since it signals you do not understand the business',score:-100,feedbackText:'Dismissing investor pressure on burn rate ignores real financial risk. The right response is a credible argument for which cuts protect value and which destroy it.'}
]},
{cat:'ai-cost-business',d:1,s:'You are setting budget for next year and need to decide how much to allocate to AI tools and training.',t:'AI tool investment without corresponding training investment consistently underperforms because adoption stays low.',options:[
  {text:'Allocate the full budget to the best AI tools available and trust that the team will learn them',score:-100,feedbackText:'Tools without training are commonly underused. Adoption rates for untrained software are typically below 30%, turning significant tool spend into waste.'},
  {text:'Allocate budget to both tools and training, with training representing at least 20% of the total AI investment',score:100,feedbackText:'Correct! Training investment drives adoption, which drives ROI. The tools-only budget is the most common reason AI investments underperform expectations.'},
  {text:'Invest only in training and use free AI tools to maximize the training budget',score:0,feedbackText:'Free tools are a good starting point but often lack the features that unlock the ROI you are training toward. Training and capable tools must go together.'}
]},
{cat:'ai-cost-business',d:2,s:'Your HR department wants to use AI to screen job applications at scale but is unsure how to account for implementation cost.',t:'AI hiring tool total cost includes configuration, bias testing, maintenance, and the legal review needed before deploying in regulated hiring contexts.',options:[
  {text:'Purchase the AI screening tool and go live within the month',score:-100,feedbackText:'AI hiring tools are legally sensitive in most jurisdictions. Going live without bias testing and legal review creates discrimination liability that far exceeds any efficiency gain.'},
  {text:'Budget for tool cost plus configuration, bias testing with real candidate data, legal review, and quarterly audits before and after deployment',score:100,feedbackText:'Excellent! Full-cost budgeting for AI hiring tools includes ongoing audit costs that are non-optional in regulated environments. Initial setup is just the first expense.'},
  {text:'Test the tool internally by running it on past applications in parallel with no plans to audit',score:0,feedbackText:'Parallel testing without bias auditing misses the core risk. Historical application data often embeds historical biases that the AI learns to replicate.'}
]},
{cat:'ai-cost-business',d:3,s:'Your logistics company is evaluating a full fleet automation system that costs $5 million but promises to eliminate $8 million in annual driver costs over five years.',t:'Large AI investment decisions require sensitivity analysis on key assumptions since small changes in the model can flip the projected ROI.',options:[
  {text:'Approve the investment immediately since $15M savings over five years versus $5M cost is clearly positive',score:0,feedbackText:'Simple subtraction ignores discount rates, adoption risk, and maintenance costs. A $10M projected gain on a $5M investment can flip to negative under realistic assumptions.'},
  {text:'Build a financial model with sensitivity analysis on key variables: adoption rate, maintenance cost, regulatory changes, and driver retention during transition',score:100,feedbackText:'Correct! Sensitivity analysis on a decision of this scale is essential. A 10% reduction in adoption or a 20% increase in maintenance costs can dramatically change the real ROI.'},
  {text:'Decline since fleet automation is not mature enough to bet $5M on',score:-100,feedbackText:'Declining without analysis is as bad as approving without it. The right answer depends on a careful model with realistic assumptions, not a general stance on technology maturity.'}
]},
{cat:'ai-cost-business',d:1,s:'Your team signed up for five different AI subscriptions during an experimental period and is now paying for all of them.',t:'AI subscription hygiene — regular audits and ruthless cancellation of unused tools — prevents tool sprawl from becoming a silent budget drain.',options:[
  {text:'Keep all subscriptions active for flexibility even if not all are in regular use',score:-100,feedbackText:'Paying for flexibility is expensive. SaaS tools you do not use actively cost real money. The cancellation is usually reversible if you need them again.'},
  {text:'Audit each subscription\'s actual usage over the past 90 days and cancel any with fewer than three active users',score:100,feedbackText:'Excellent! Usage-based audit criteria make the cancellation decision objective. 90-day inactivity with low user counts is a reliable signal that a tool has not found its purpose.'},
  {text:'Ask each team member which tools they use and keep any tool at least one person uses',score:0,feedbackText:'One-user retention is better than zero but still wasteful. Single-user tools should be evaluated against whether their value justifies the full subscription cost.'}
]},
{cat:'ai-cost-business',d:2,s:'Your manufacturing company wants to use AI quality inspection instead of manual checkers. Each camera installation costs $15,000.',t:'AI vision system ROI in manufacturing depends on defect catch rate improvement, labor cost offset, and the cost of defects that slip through.',options:[
  {text:'Install cameras at all 40 inspection points immediately to capture the full efficiency gain',score:0,feedbackText:'Full deployment before validation locks in $600,000 before you know if the AI matches manual checker accuracy on your specific product types.'},
  {text:'Pilot at three representative inspection points, measure catch rates versus manual checkers, and calculate actual labor and defect cost savings before scaling',score:100,feedbackText:'Correct! A pilot at representative points gives real defect data and labor cost comparisons. The scale-up decision should be data-driven, not assumption-driven.'},
  {text:'Avoid AI inspection since manufacturing quality cannot be trusted to algorithms',score:-100,feedbackText:'AI vision systems often outperform human checkers on consistent, high-volume inspection tasks. Categorical resistance ignores real quality and cost improvements in production environments.'}
]},
{cat:'ai-cost-business',d:2,s:'You want to estimate the productivity benefit of your company\'s AI adoption so far but do not have baseline measurements from before the rollout.',t:'Productivity impact measurement without baselines requires proxy metrics and controlled comparisons to estimate AI contribution credibly.',options:[
  {text:'Declare the AI program a success based on positive team feedback',score:0,feedbackText:'Qualitative feedback is valuable but not sufficient for board-level reporting. Positive sentiment and measurable productivity gains are not the same thing.'},
  {text:'Identify proxy metrics now, compare AI-heavy versus non-AI teams on output quality and volume, and use regression to isolate AI contribution from other factors',score:100,feedbackText:'Excellent! Controlled comparison with regression analysis is the right approach when baselines are missing. It is imperfect but far more credible than sentiment alone.'},
  {text:'Conclude that measurement is impossible without baselines and move on',score:-100,feedbackText:'Measurement is harder without baselines but not impossible. Proxy metrics and comparative analysis can generate credible estimates even retrospectively.'}
]},

// ===== ai-customer-service (20) =====
{cat:'ai-customer-service',d:1,s:'A customer emails to complain that an AI chatbot gave them incorrect refund information, costing them two hours of effort.',t:'AI support errors that cause customer harm must be corrected immediately with human follow-up — and investigated to fix the root cause.',options:[
  {text:'Respond with a template apology and explain that AI chatbots occasionally make mistakes',score:-100,feedbackText:'Template apologies for AI-caused harm feel dismissive. Customers who lost time due to your AI error expect a specific resolution, not a general disclaimer.'},
  {text:'Apologize specifically, resolve the correct refund immediately, and trigger an internal investigation of the chatbot\'s incorrect response',score:100,feedbackText:'Correct! Specific apology plus immediate resolution restores customer trust. The internal investigation prevents the same error from harming future customers.'},
  {text:'Offer a discount code as compensation and close the ticket',score:0,feedbackText:'A discount addresses the financial friction but does not demonstrate that you take the AI error seriously. Resolution plus investigation is the complete response.'}
]},
{cat:'ai-customer-service',d:2,s:'Your AI customer service chatbot handles 80% of queries successfully but 20% result in frustrated customers demanding human agents.',t:'Failure mode analysis on your 20% failure cases is more valuable than optimizing the 80% your AI already handles well.',options:[
  {text:'Improve the chatbot\'s general language models to try to reduce failures across the board',score:0,feedbackText:'General improvement without analyzing the specific failure mode is inefficient. The 20% likely has identifiable patterns that targeted fixes can address.'},
  {text:'Analyze the 20% failure cases for common themes, then fix those specific failure modes through better training data or escalation triggers',score:100,feedbackText:'Excellent! Targeted failure mode analysis is the highest-leverage improvement approach. Addressing the specific patterns in the failing 20% produces better results than general training.'},
  {text:'Increase human agent staffing to cover the 20% that AI fails',score:-100,feedbackText:'Staffing around AI failure rather than fixing the AI perpetuates the cost structure automation was supposed to reduce. Root cause analysis first.'}
]},
{cat:'ai-customer-service',d:1,s:'You want to set up an AI system to handle after-hours customer support when your team is offline.',t:'After-hours AI support must clearly communicate its limitations and escalation paths so customers are not left without recourse for urgent issues.',options:[
  {text:'Configure the AI to handle all queries including urgent ones and wait until morning for human review',score:-100,feedbackText:'Urgent issues handled only by AI without escalation paths can result in serious customer harm. After-hours AI must have emergency escalation routes.'},
  {text:'Deploy AI for common queries with a clear escalation path for urgent issues, such as an emergency email or callback request that routes to on-call staff',score:100,feedbackText:'Correct! AI coverage plus an emergency escalation channel protects customers who have time-sensitive issues while still capturing after-hours efficiency gains.'},
  {text:'Simply close support outside business hours rather than using AI',score:0,feedbackText:'Closing support entirely is a competitive disadvantage in an era where customers expect availability. AI coverage with proper guardrails is better than nothing.'}
]},
{cat:'ai-customer-service',d:2,s:'Customer satisfaction scores dropped after you introduced AI chat support even though average handle time improved.',t:'Efficiency metrics and satisfaction metrics can move in opposite directions if AI resolves queries faster but leaves customers feeling unheard.',options:[
  {text:'Revert to full human support since the satisfaction drop shows AI does not work here',score:0,feedbackText:'Reverting without investigating the cause wastes the efficiency gains you already achieved. The satisfaction drop has a specific cause that analysis can identify.'},
  {text:'Analyze the sessions where satisfaction dropped most, identify whether the issue is resolution accuracy or conversational tone, and fix the specific failure',score:100,feedbackText:'Excellent! Satisfaction drops in AI interactions are usually either accuracy problems or tone problems. Diagnosing which one leads to targeted fixes that restore both metrics.'},
  {text:'Increase AI response speed further since faster resolution should improve satisfaction',score:-100,feedbackText:'Speed improvements that customers did not ask for do not address tone or accuracy issues. Making an unsatisfying interaction faster makes it worse, not better.'}
]},
{cat:'ai-customer-service',d:3,s:'Your AI support system has access to the customer\'s full purchase history and uses it to personalize responses. A customer asks who can see their data.',t:'Transparency about AI personalization and data use is required in many jurisdictions and builds the trust that increases acceptance of AI systems.',options:[
  {text:'Tell the customer that data access is proprietary and decline to share details',score:-100,feedbackText:'Refusing to explain data use undermines trust and may violate privacy regulations requiring disclosure of automated decision-making.'},
  {text:'Clearly explain what data the AI accesses, how it uses it to improve responses, and how the customer can opt out of personalization',score:100,feedbackText:'Correct! Transparent disclosure about AI data use builds trust and fulfills regulatory requirements in GDPR and equivalent frameworks. Opt-out paths are required, not optional.'},
  {text:'Reassure the customer that their data is safe without explaining what the AI accesses',score:0,feedbackText:'Reassurance without explanation does not answer the question. Customers asking about data access are entitled to specific information, not vague comfort.'}
]},
{cat:'ai-customer-service',d:1,s:'You want to use AI sentiment analysis to prioritize customer tickets by emotional urgency rather than just arrival time.',t:'Sentiment-based prioritization improves routing when combined with topic classification since emotion alone is an incomplete urgency signal.',options:[
  {text:'Route all high-sentiment tickets to senior agents regardless of issue type',score:0,feedbackText:'High sentiment on a simple issue may not warrant senior escalation. Combining sentiment with issue complexity produces smarter routing than emotion alone.'},
  {text:'Use AI to classify both sentiment and issue complexity, then route high-sentiment or high-complexity tickets to the appropriate specialist tier',score:100,feedbackText:'Excellent! Two-dimensional classification produces more accurate routing. Urgency without context misses the tickets that are complex but calmly phrased.'},
  {text:'Continue with first-in-first-out queuing since fairness to all customers matters',score:-100,feedbackText:'First-in-first-out ignores genuine urgency differences that affect customer outcomes. Smart prioritization serves customers better and is widely accepted as fair.'}
]},
{cat:'ai-customer-service',d:2,s:'Your AI chatbot can answer most questions but occasionally says "I don\'t know" and leaves customers stuck. You want to reduce this frustration.',t:'A well-designed "I don\'t know" response routes customers to the most efficient alternative path, not just acknowledges the limitation.',options:[
  {text:'Train the chatbot to avoid saying "I don\'t know" entirely by giving a response even when uncertain',score:-100,feedbackText:'Forcing confident responses on uncertain topics produces confidently wrong answers, which damage trust far more than honest uncertainty.'},
  {text:'Replace "I don\'t know" with a structured fallback that offers relevant FAQ links, an escalation button, or a callback request',score:100,feedbackText:'Correct! Constructive dead ends are far less frustrating than blank admissions of ignorance. A structured fallback converts a failure into a managed handoff.'},
  {text:'Add more information to the chatbot\'s knowledge base until it never says "I don\'t know"',score:0,feedbackText:'Complete knowledge coverage is an impossible target. Every chatbot has edge cases. The escalation path matters at least as much as the breadth of answers.'}
]},
{cat:'ai-customer-service',d:2,s:'You are launching an AI voice assistant for phone support. Your team is concerned that elderly customers will struggle to use it.',t:'Accessible AI support design includes clear opt-out paths to human agents and design testing with the full range of users, not just the average case.',options:[
  {text:'Launch for all customers since the AI will work fine once they get used to it',score:-100,feedbackText:'Launching without accessibility testing risks significant customer harm for vulnerable segments. "They will get used to it" is not an acceptable stance for essential services.'},
  {text:'Test the voice system with elderly users before launch, provide immediate "speak to a person" shortcut commands, and monitor escalation rates by age segment post-launch',score:100,feedbackText:'Excellent! Pre-launch testing with the target segment plus instant human escalation and post-launch monitoring is the responsible deployment path.'},
  {text:'Offer both phone AI and live agents so customers can choose',score:0,feedbackText:'Choice is good but does not substitute for making the AI option accessible. Even customers who try the AI and struggle need a clear out.'}
]},
{cat:'ai-customer-service',d:1,s:'A customer who had a poor chatbot experience just angrily demanded to speak with a human. The human agent has the full chat history.',t:'When customers escalate from AI to human, the human agent\'s most powerful tool is acknowledging the frustration before jumping to resolution.',options:[
  {text:'The human agent should immediately solve the problem without mentioning the chatbot experience',score:0,feedbackText:'Solution-first ignores the emotional state the customer is in. Jumping to resolution without acknowledgment often prolongs the conversation because the customer still feels unheard.'},
  {text:'The agent should briefly acknowledge the frustrating chat experience, then take ownership of the resolution and deliver it without further friction',score:100,feedbackText:'Correct! Acknowledgment of the chatbot failure signals that the customer\'s frustration was valid and seen. It resets the emotional tone before resolution restores confidence.'},
  {text:'The agent should apologize extensively for the AI before attempting any resolution',score:-100,feedbackText:'Excessive apology without resolution prolongs the negative experience. Customers want to feel heard briefly and then have their issue solved efficiently.'}
]},
{cat:'ai-customer-service',d:3,s:'Your AI customer service system is connected to the company\'s CRM and can take some autonomous actions like processing refunds up to $50.',t:'Autonomous AI actions in customer service require explicit authorization boundaries and full audit logs to maintain accountability.',options:[
  {text:'Expand AI autonomous authority to cover all standard refund amounts since human review slows resolution',score:-100,feedbackText:'Expanding autonomous authority without audit infrastructure creates accountability gaps. Every automated action affecting money needs a complete audit trail regardless of amount.'},
  {text:'Keep the $50 autonomous authority, ensure full logging of every automated action, and set a quarterly review to adjust the threshold based on fraud rates and customer satisfaction',score:100,feedbackText:'Excellent! Bounded authority plus audit logging plus review cycles is the responsible AI autonomy model. The threshold should be data-driven, not set and forgotten.'},
  {text:'Remove all autonomous AI authority and require human approval for every action',score:0,feedbackText:'Full human approval requirements eliminate the efficiency AI autonomy provides. The right answer is bounded authority with strong audit trails, not zero autonomy.'}
]},
{cat:'ai-customer-service',d:2,s:'You want to train a new customer service AI on your company\'s historical support tickets. You realize the older tickets reflect outdated policies.',t:'Training data for customer service AI must be current and policy-aligned, since AI trained on outdated policies will confidently give wrong answers.',options:[
  {text:'Train on all available historical data since more data always produces better AI performance',score:-100,feedbackText:'More data is only better if the data is correct and current. Training on outdated policy tickets teaches the AI to replicate discontinued procedures confidently.'},
  {text:'Filter training data to only include tickets from the past 18 months and exclude tickets where policy has since changed',score:100,feedbackText:'Correct! Data recency and policy alignment are quality criteria for training data, not just quantity. A smaller, accurate dataset outperforms a larger, outdated one.'},
  {text:'Train on all data but add a disclaimer that the AI may give outdated answers',score:0,feedbackText:'A disclaimer does not prevent customer harm from outdated responses. Filtering the training data at the source is the right fix.'}
]},
{cat:'ai-customer-service',d:1,s:'You want to measure whether your AI customer service implementation is working. Your current metric is tickets closed per day.',t:'Volume metrics tell you how busy the system is, not how well it is serving customers. Resolution quality and satisfaction must be measured alongside volume.',options:[
  {text:'Focus on tickets closed per day since reducing ticket volume is the goal of automation',score:0,feedbackText:'Tickets closed per day can increase even when customers are unsatisfied. Volume metrics without quality metrics create pressure toward faster closures rather than better resolutions.'},
  {text:'Track tickets closed per day alongside CSAT scores, repeat contact rates, and escalation rates to get a full picture of AI support quality',score:100,feedbackText:'Excellent! Multi-metric measurement captures the efficiency-quality tradeoff. Repeat contact rates in particular reveal whether resolutions are actually resolving issues.'},
  {text:'Survey customers after every AI interaction to get the most accurate satisfaction data',score:-100,feedbackText:'Post-interaction surveys have very low response rates and selection bias. Operational metrics like repeat contacts and escalation rates are more reliable and require no customer participation.'}
]},
{cat:'ai-customer-service',d:3,s:'Your AI support system makes recommendations to customers based on their past purchases. A customer complains the recommendations feel invasive.',t:'AI personalization requires a privacy sensitivity calibration — what feels helpful versus what feels surveillant depends on context and user expectation.',options:[
  {text:'Disable all personalization since any use of customer data risks feeling invasive',score:-100,feedbackText:'Removing all personalization throws away the value that makes AI support useful. The issue is calibration, not the existence of personalization.'},
  {text:'Audit which data points trigger the invasiveness feeling, adjust recommendation timing and phrasing, and add a clear "manage my preferences" control for customers',score:100,feedbackText:'Correct! Invasiveness perception usually comes from specific triggers: timing, data specificity, or phrasing. Audit and adjust those elements, and give users control.'},
  {text:'Explain to the customer how personalization works and that it benefits them',score:0,feedbackText:'Explaining the mechanism rarely addresses the emotional response. Customers who feel surveilled want control, not an explanation of why surveillance is for their own good.'}
]},
{cat:'ai-customer-service',d:2,s:'You want to use AI to analyze customer feedback at scale to identify product improvement opportunities.',t:'AI text analysis of feedback can surface recurring themes that individual reading misses, but requires verification that the categories reflect genuine customer priorities.',options:[
  {text:'Use AI to categorize feedback automatically and have product managers act on the top ten themes immediately',score:0,feedbackText:'Acting on AI category outputs without verification risks optimizing around noise or misclassified data. A review step before action is prudent.'},
  {text:'Run AI analysis to surface themes, review a random sample of tickets in each theme to validate the category is real, then prioritize themes that verified samples confirm',score:100,feedbackText:'Excellent! AI surfaces the signal; human sampling validates it. Acting on unvalidated categories is faster but leads to optimizing for classification artifacts rather than real problems.'},
  {text:'Manually read all feedback since AI analysis may miss important context',score:-100,feedbackText:'Manual reading at scale is impractical and ironically less accurate than AI because humans tire and miss patterns that span thousands of tickets.'}
]},
{cat:'ai-customer-service',d:1,s:'Your chatbot frequently misunderstands questions about your product that use informal or slang language.',t:'Training chatbots on real customer language samples from your own user base outperforms generic language model improvements for domain-specific accuracy.',options:[
  {text:'Expand the chatbot\'s vocabulary with general slang from public databases',score:0,feedbackText:'General slang databases may not match the specific informal language your customers use. Training on your own customer data is more targeted and effective.'},
  {text:'Collect examples of misunderstood queries, identify the slang patterns, and add those specific examples to the training data',score:100,feedbackText:'Correct! Your own error cases are the highest-value training data. Each misunderstood query teaches the chatbot the specific language patterns your customers actually use.'},
  {text:'Require customers to use formal language when chatting with the bot',score:-100,feedbackText:'Requiring formal language creates friction for all customers and ignores the basic principle that tools should adapt to users, not the other way around.'}
]},
{cat:'ai-customer-service',d:2,s:'A major customer is threatening to churn. You want to use AI to analyze their interaction history and predict what would retain them.',t:'AI churn prediction adds value when it surfaces specific signals that humans can act on, not just a probability score without explanation.',options:[
  {text:'Use the AI churn probability score to prioritize the account and have a sales call immediately',score:0,feedbackText:'A probability score without context leads to a conversation without a plan. Analyzing why the score is high reveals what retention offer actually addresses their issue.'},
  {text:'Have AI analyze all interaction history for this customer to identify specific pain points and service failures, then design the retention approach around those findings',score:100,feedbackText:'Excellent! Diagnosis before intervention is the right sequence. Knowing the specific source of dissatisfaction lets you make a retention offer that actually addresses it.'},
  {text:'Apply a standard retention discount offer since price is usually the reason customers churn',score:-100,feedbackText:'Price is frequently not the primary churn driver. Applying a discount without diagnosis misses the real issue and trains customers to threaten churn for discounts.'}
]},
{cat:'ai-customer-service',d:3,s:'Your company plans to replace email support entirely with an AI chat system by the end of the quarter. Customers have not been informed.',t:'Significant changes to support channels require customer communication and transition planning — users who prefer email need an alternative path.',options:[
  {text:'Launch the migration on the planned date and update the website to reflect the change',score:-100,feedbackText:'Silent migration without customer communication creates confusion and complaint spikes when customers try to email and cannot. Transition plans must include user communication.'},
  {text:'Announce the migration at least 30 days in advance, explain the new channel, provide a temporary email path for the first 60 days, and monitor escalation rates closely',score:100,feedbackText:'Correct! Advance notice, transition period, and monitoring are the three components of responsible channel migration. Each protects a different group of customers.'},
  {text:'Migrate only new customers to AI chat while keeping email for existing customers',score:0,feedbackText:'Segmented migration reduces disruption but creates operational complexity. A managed full migration with proper communication is usually cleaner and equally respectful.'}
]},
{cat:'ai-customer-service',d:1,s:'You want to use AI to automatically send personalized follow-up emails after customer support interactions close.',t:'Automated follow-up sequences add value when they are genuinely helpful, not when they create noise that customers tune out.',options:[
  {text:'Set up AI to send a follow-up email every three days until the customer rates the interaction',score:-100,feedbackText:'Repeated automated follow-ups for ratings feel more like harassment than care. One well-timed follow-up with genuine content produces better responses than persistence campaigns.'},
  {text:'Send one automated follow-up 24 hours after closure with a satisfaction question and a relevant help article based on the issue that was resolved',score:100,feedbackText:'Excellent! Single touchpoint plus relevant content adds genuine value. Satisfaction measurement and proactive help for similar future issues are both things customers appreciate.'},
  {text:'Skip follow-up emails entirely since customers reach out again if they have issues',score:0,feedbackText:'Waiting for customers to re-contact misses satisfaction issues that customers will not bother reporting. A single well-crafted follow-up recovers feedback that would otherwise be lost.'}
]},
{cat:'ai-customer-service',d:2,s:'A new regulation requires your company to provide customers with the ability to request human review of any AI-generated decision affecting their account.',t:'Regulatory compliance for AI decisions requires documented human review processes, not just a promise that humans are involved.',options:[
  {text:'Add a note to your terms of service stating that human review is available on request',score:0,feedbackText:'A terms-of-service note is not a functional process. Customers who request human review need an actual path, not a legal disclaimer.'},
  {text:'Build a documented human review workflow, train agents on how to conduct reviews, add an accessible request button to the AI decision notification, and test the process end to end',score:100,feedbackText:'Correct! Regulatory compliance requires a functioning process, not just a policy statement. End-to-end testing before launch verifies the review path actually works.'},
  {text:'Ensure a human always reviews every AI decision to avoid the regulatory risk entirely',score:-100,feedbackText:'Full human review of every decision eliminates the efficiency AI provides and is operationally unsustainable. The regulation requires accessible review, not universal review.'}
]}

]

// Insert in batches of 20
for(let i=0; i<ALL.length; i+=20) {
  const batch = ALL.slice(i, i+20)
  const cat = batch[0].cat
  process.stdout.write(`Inserting ${batch.length} ${cat} questions... `)
  const ok = await insert(batch)
  if(!ok) { console.error('FAILED at index', i); break }
}
console.log('DONE. Total:', ALL.length)
