const TOKEN = 'sbp_f314cf27b5b2a01eea48048a7b1c015cc9cf4b42'
const API = 'https://api.supabase.com/v1/projects/amhfxaqolholacanqyas/database/query'
function esc(s) { return s.replace(/'/g, "''") }
async function insert(batch) {
  const values = batch.map(q => {
    const opts = JSON.stringify(q.options).replace(/'/g, "''")
    return `('en','${q.cat}','${esc(q.s)}','${esc(q.t)}','${opts}'::jsonb,${q.d},'claude',true)`
  }).join(',')
  const sql = `INSERT INTO questions (locale,category,scenario_text,mindset_tip,options,difficulty,generated_by,is_active) VALUES ${values};`
  const r = await fetch(API, {method:'POST',headers:{'Authorization':`Bearer ${TOKEN}`,'Content-Type':'application/json'},body:JSON.stringify({query:sql})})
  const d = await r.json()
  if(d.message) { console.error('ERR:',d.message.substring(0,120)); return false }
  console.log('OK:', batch.length, 'inserted')
  return true
}

const ALL = [

// ===== ai-media-content (20) =====
{cat:'ai-media-content',d:1,s:'A journalist wants to use AI to research background for a story about climate policy. The AI provides detailed statistics with no sources.',t:'AI research assistance must always lead to primary source verification since AI statistical claims without citations cannot be independently verified.',options:[
  {text:'Use the AI statistics directly since the numbers sound credible and consistent with other reporting',score:-100,feedbackText:'"Sounds credible" is not a journalistic standard. AI-generated statistics without sources must be traced to a primary source before publication.'},
  {text:'Treat AI-provided statistics as leads to investigate, then verify each number against primary sources before including it in the story',score:100,feedbackText:'Correct! AI research is a starting point, not an endpoint for journalism. Every specific claim needs primary source verification before it appears in a published story.'},
  {text:'Add a note that statistics were AI-generated so readers can assess them independently',score:0,feedbackText:'Reader disclosure does not replace editorial verification. Publishing unverified AI statistics with a disclaimer still creates accuracy liability for the outlet.'}
]},
{cat:'ai-media-content',d:2,s:'A music streaming platform uses AI to recommend artists to listeners. Small and independent artists say they never get recommended regardless of quality.',t:'AI recommendation bias against new and independent artists requires active curation intervention since recommendation models favor established signals.',options:[
  {text:'Explain that the algorithm recommends based on listener data and cannot favor smaller artists',score:-100,feedbackText:'Algorithm neutrality is a myth when the training data systematically underrepresents new artists. Passive algorithmic neutrality reproduces structural disadvantages.'},
  {text:'Audit recommendation rates by artist size, introduce algorithmic diversity floors for emerging artists, and create editorial playlists that surface high-quality independent content',score:100,feedbackText:'Excellent! Audit plus algorithmic floors plus editorial curation is the complete response to AI recommendation bias against independent artists. Each element addresses a different part of the problem.'},
  {text:'Let the algorithm work as designed since listener preferences naturally determine which artists succeed',score:0,feedbackText:'Listener preference data is circular — it reflects prior exposure, which AI recommendations control. The algorithm shapes what listeners know about, not just what they want.'}
]},
{cat:'ai-media-content',d:1,s:'You are a content creator and want to use AI to repurpose a long YouTube video into a LinkedIn article, five social posts, and a newsletter summary.',t:'AI content repurposing from a single source can multiply distribution reach while preserving the core ideas, dramatically improving content ROI.',options:[
  {text:'Manually rewrite each format separately since each platform has distinct tone and structure requirements',score:0,feedbackText:'Manual rewriting for each format is the high-quality but high-effort approach. AI repurposing with format-specific editing captures most of the quality at a fraction of the time.'},
  {text:'Use AI to generate format-specific drafts from a video transcript, then edit each for platform tone and add your personal voice before publishing',score:100,feedbackText:'Correct! AI drafts give you the structure; your editing gives each format its authentic voice and platform fit. This combination multiplies reach without multiplying effort proportionally.'},
  {text:'Publish the AI-generated repurposed content directly without editing to maximize output speed',score:-100,feedbackText:'Unedited AI repurposing often lacks the platform-specific voice and nuance that drives engagement. A quick editing pass dramatically improves quality with minimal added time.'}
]},
{cat:'ai-media-content',d:2,s:'A media company wants to use AI to generate news summaries for their mobile app. Editors worry the summaries will lose editorial judgment about what matters.',t:'AI news summarization captures what was said but not why it matters — editorial judgment about significance must remain with human editors.',options:[
  {text:'Replace all manual editorial curation with AI summaries to reduce costs',score:-100,feedbackText:'AI summarization tells you what a story says but not whether it matters and to whom. Editorial significance judgment is the core value that AI cannot replicate.'},
  {text:'Use AI to generate first-pass summaries while editors review for accuracy, add significance context, and apply editorial judgment about which stories to feature',score:100,feedbackText:'Excellent! AI handles the extraction; editors handle the significance judgment. Each does what it does best — AI cannot understand reader context and story importance; editors cannot read 500 stories per day.'},
  {text:'Avoid AI in news summarization since editorial quality requires full human attention',score:0,feedbackText:'AI summarization of factual extraction saves significant time that editors can then invest in higher-value significance and curation judgment. The combination outperforms either alone.'}
]},
{cat:'ai-media-content',d:3,s:'A social media platform uses AI to detect and remove misinformation. Critics say it removes accurate content from minority communities more often than majority ones.',t:'AI content moderation systems require demographic equity audits since training data imbalances can produce systematic disparate enforcement by community.',options:[
  {text:'Trust the AI moderation since it applies the same rules to all content regardless of community',score:-100,feedbackText:'Equal rule application by a biased classifier produces unequal outcomes. If training data underrepresents minority community expression, the classifier will misidentify it as problematic more often.'},
  {text:'Conduct regular demographic equity audits of removal rates by community, investigate specific patterns of disparate removal, and retrain with more representative data from affected communities',score:100,feedbackText:'Correct! Equity auditing plus root cause investigation plus retraining is the complete response. Disparate removal rates in AI moderation are a technical problem with a technical solution.'},
  {text:'Add an appeals process so communities can challenge incorrect moderation decisions',score:0,feedbackText:'Appeals are necessary but do not address systematic removal at scale. Auditing and fixing the classifier is more effective than managing individual appeals for systemic errors.'}
]},
{cat:'ai-media-content',d:1,s:'You want to use AI to generate thumbnail designs for your YouTube videos to improve click-through rates.',t:'AI-generated thumbnails need A/B testing against your specific audience since generic optimization does not account for channel-specific viewer expectations.',options:[
  {text:'Generate AI thumbnails for all videos since AI-optimized design always outperforms manually created ones',score:0,feedbackText:'AI-optimized design outperforms on general engagement metrics but may not reflect your specific audience. A/B testing with your actual viewers validates which approach works for your channel.'},
  {text:'A/B test AI-generated thumbnails against your current designs on several videos before switching entirely',score:100,feedbackText:'Excellent! A/B testing with your audience validates performance claims for your specific context. Generic AI optimization research does not substitute for testing on your actual viewers.'},
  {text:'Continue with manually designed thumbnails since AI aesthetics feel generic',score:-100,feedbackText:'Generic aesthetics are a risk with poorly prompted AI design, not an inherent characteristic. Proper prompting with your channel\'s visual identity can produce AI thumbnails that feel authentic.'}
]},
{cat:'ai-media-content',d:2,s:'A podcaster wants to use AI to transcribe episodes and create searchable show notes. Some episodes contain sensitive guest disclosures.',t:'Transcription AI processes audio content without context about what is sensitive — human review is required before publishing notes containing personal disclosures.',options:[
  {text:'Publish AI transcription-based show notes immediately since transcription is just documentation',score:-100,feedbackText:'Transcription-based show notes may surface personal disclosures guests shared in audio form without expecting them to appear as searchable text. Human review protects both guests and the show.'},
  {text:'Use AI transcription for efficiency, then have a producer review the notes before publishing to identify and handle sensitive disclosures appropriately',score:100,feedbackText:'Correct! AI handles volume; human review handles sensitivity judgment. Guests who share something in conversation may not expect it to become searchable text without explicit consent.'},
  {text:'Ask guests to sign a release form that covers all AI processing of their episode audio',score:0,feedbackText:'Release forms provide legal coverage but do not address the editorial judgment of what should appear in published notes. Human review and editorial discretion remain necessary regardless of release coverage.'}
]},
{cat:'ai-media-content',d:3,s:'AI-generated deepfake videos of public figures are becoming indistinguishable from real footage. Your news outlet needs a policy.',t:'News outlet deepfake policies must address both verification standards for content received and guidelines for any AI-generated content the outlet itself produces.',options:[
  {text:'Prohibit all AI-generated video content and continue with traditional video standards',score:0,feedbackText:'Prohibition covers outlet production but does not address the verification challenge for received footage. A comprehensive policy addresses both sides: what you publish and how you verify received content.'},
  {text:'Implement technical verification protocols for received video content, establish clear labeling requirements for any AI-generated content published, and create editorial standards for deepfake coverage',score:100,feedbackText:'Excellent! Verification protocols, labeling standards, and editorial guidelines for covering deepfakes are the three components of a comprehensive news outlet deepfake policy.'},
  {text:'Rely on audience media literacy since sophisticated deepfakes are becoming common knowledge',score:-100,feedbackText:'Audience media literacy does not substitute for outlet responsibility. Publishing unverified footage because "audiences should know better" abandons editorial standards.'}
]},
{cat:'ai-media-content',d:1,s:'You run a marketing agency and want to use AI to create personalized ad copy for different customer segments at scale.',t:'AI ad personalization at scale requires segment-specific testing since what resonates with one segment can actively alienate another.',options:[
  {text:'Create one AI-generated ad and use it across all segments to maintain brand consistency',score:-100,feedbackText:'Single ad across all segments wastes the personalization capability. Segment-specific resonance drives conversion; brand consistency is maintained through visual identity, not copy uniformity.'},
  {text:'Generate segment-specific AI copy variants, run A/B tests for each segment, and build a performance database of what works for each audience profile',score:100,feedbackText:'Correct! AI generates the variant volume; testing validates which variants work. The performance database becomes the asset that makes each subsequent campaign more effective.'},
  {text:'Let clients approve all AI copy before running ads since they know their customers best',score:0,feedbackText:'Client approval is appropriate but not a substitute for audience testing. Client knowledge of their customers is valuable input for prompting, not a replacement for empirical performance data.'}
]},
{cat:'ai-media-content',d:2,s:'A book publisher wants to use AI to identify which manuscript submissions are most likely to become bestsellers.',t:'AI manuscript screening can surface patterns from historical bestsellers but creative work breaks established patterns — pure pattern-matching misses breakthrough books.',options:[
  {text:'Use AI to pre-screen all submissions and only have editors read AI-selected manuscripts',score:-100,feedbackText:'AI screening for bestseller potential optimizes for historical pattern replication. Many of the best books have been rejected precisely because they broke the patterns that AI would optimize for.'},
  {text:'Use AI to filter for quality markers in writing craft while requiring editors to read a diverse sample beyond the AI shortlist',score:100,feedbackText:'Excellent! AI for craft quality plus editorial diversity beyond the AI shortlist captures efficiency without eliminating the serendipity that produces breakthrough books.'},
  {text:'Reject AI screening entirely since literary quality cannot be quantified',score:0,feedbackText:'AI screening for specific quality markers like coherent structure and prose quality is technically feasible. The risk is in using those markers as the primary commercial filter, not in using them at all.'}
]},
{cat:'ai-media-content',d:1,s:'You are a graphic designer and AI image generation tools can now create professional illustrations faster than you can. Your clients ask why they should pay for your services.',t:'Designers who use AI as a tool add judgment, iteration, and strategic thinking that prompt-only generation cannot provide — the value proposition has shifted, not disappeared.',options:[
  {text:'Lower your rates to compete with AI-only pricing since clients can now get similar work cheaper',score:0,feedbackText:'Competing on price with AI is a race to the bottom. Your value is in the judgment and creative direction that transforms AI output into work that fits the client\'s specific needs.'},
  {text:'Demonstrate how your creative direction, iteration, and brand understanding produces better outcomes than what clients get from AI prompting alone',score:100,feedbackText:'Correct! The value demonstration is the business pivot. Clients who try AI prompting alone often discover they still need creative expertise to get work that actually fits their context and brand.'},
  {text:'Refuse to use AI tools to differentiate your fully human creative process',score:-100,feedbackText:'Refusing AI tools limits your productivity and speed without improving quality. Designers who use AI well are more competitive, not less, than those who refuse it.'}
]},
{cat:'ai-media-content',d:2,s:'Your company creates educational video content. AI can now generate realistic presenter avatars. Learners do not know if they are watching a human or an AI.',t:'Undisclosed AI presenter avatars in educational content undermine the authenticity contract learners expect, especially for content requiring expert credibility.',options:[
  {text:'Use AI avatars without disclosure since the content quality is identical to human-presented video',score:-100,feedbackText:'Identical content quality does not justify undisclosed misrepresentation. Learners have legitimate expectations about whether they are learning from a human expert or an AI simulation of one.'},
  {text:'Clearly label AI avatar content and use human presenters for content where expert credibility and authentic experience are critical to learner trust',score:100,feedbackText:'Excellent! Labeling plus content-type-appropriate presenter choice is the right framework. AI avatars work well for instructional content; human experts are necessary where personal authority matters.'},
  {text:'Add a generic disclosure in the terms of service and use AI avatars freely',score:0,feedbackText:'Buried ToS disclosures do not satisfy the transparency obligation for ongoing presentation choices learners encounter in every video. Labeling at the content level is the right approach.'}
]},
{cat:'ai-media-content',d:3,s:'An AI model trained on news articles has started generating fictional news stories that are stylistically indistinguishable from real reporting.',t:'AI systems capable of generating convincing synthetic journalism require explicit safeguards and content provenance mechanisms before deployment.',options:[
  {text:'Deploy the AI with usage guidelines asking users not to present AI-generated content as real news',score:-100,feedbackText:'Usage guidelines are unenforceable against bad actors and do not address the harm potential of a tool whose primary failure mode is convincing fake journalism.'},
  {text:'Add technical content provenance labels, watermarking, and partner with fact-checking organizations before deployment, and restrict API access to verified publishing entities',score:100,feedbackText:'Correct! Provenance labeling, watermarking, and access restriction are the technical safeguards required before deploying AI capable of generating convincing synthetic journalism.'},
  {text:'Release only to academic researchers since consumer deployment of convincing fake journalism AI is too risky',score:0,feedbackText:'Academic-only access addresses immediate consumer risk but does not resolve the capability question for eventual broader deployment. Building in technical safeguards now prepares for responsible future expansion.'}
]},
{cat:'ai-media-content',d:1,s:'You run a small newsletter and want to use AI to improve your open rates by personalizing subject lines for different subscriber segments.',t:'AI-personalized subject lines can significantly improve open rates when they reflect genuine content differentiation for each segment, not just name insertion.',options:[
  {text:'Insert each subscriber\'s first name into a standard AI-generated subject line',score:0,feedbackText:'Name insertion is the most basic personalization and has declining effectiveness as subscribers have become accustomed to it. Segment-specific content framing is more effective.'},
  {text:'Create content variants for each subscriber segment and use AI to generate subject lines that accurately reflect the segment-specific content angle each will receive',score:100,feedbackText:'Excellent! Subject line personalization that reflects actual content variation is the most effective form. Subscribers who open based on an accurate preview convert better than those attracted by a misleading hook.'},
  {text:'Use the same subject line for all subscribers to maintain brand voice consistency',score:-100,feedbackText:'Identical subject lines sacrifice personalization benefit without gaining meaningful brand value. Consistent tone and voice can coexist with segment-specific subject line framing.'}
]},
{cat:'ai-media-content',d:2,s:'A video game studio wants to use AI to generate dialogue for non-player characters at scale instead of hiring voice actors.',t:'AI voice generation at scale creates efficiency but raises ethical questions about displacement of voice acting labor and appropriate residual compensation frameworks.',options:[
  {text:'Replace all voice actors with AI voice generation immediately since the quality is now comparable',score:-100,feedbackText:'Comparable quality does not resolve the labor displacement ethics. The industry is developing frameworks for AI voice use with consent and compensation for source actor voices.'},
  {text:'Use AI voice for generic NPCs while retaining human voice actors for named characters, and review industry emerging standards on AI voice licensing and consent',score:100,feedbackText:'Correct! Tiered use that reserves meaningful roles for human actors plus engagement with industry ethical frameworks is the responsible path during this rapidly evolving area.'},
  {text:'Only use AI voices trained on synthetic data without real actor source voices to avoid consent issues',score:0,feedbackText:'Fully synthetic voices without real actor basis avoid some consent issues but still displace voice acting work. Labor displacement questions remain regardless of the voice generation method.'}
]},
{cat:'ai-media-content',d:1,s:'You run a social media account and want to use AI to schedule and automate posting so you are active even when you are not online.',t:'AI posting automation maintains presence and consistency but authentic engagement with audience comments and messages still requires human participation.',options:[
  {text:'Automate all posting and let AI respond to comments since engagement at scale requires automation',score:-100,feedbackText:'AI comment responses are often detectable as generic and damage the authentic community relationship that social media builds. Automation is appropriate for scheduling, not for relationship responses.'},
  {text:'Use AI to schedule content in advance and batch replies, but respond authentically to comments personally even if less frequently',score:100,feedbackText:'Excellent! Scheduled content plus authentic personal engagement is the right balance. Your audience follows you, not a posting bot — authentic responses maintain the relationship that drives loyalty.'},
  {text:'Avoid AI posting automation since authenticity requires real-time posting',score:0,feedbackText:'Scheduled content is not inauthentic — it is planned. Automation for scheduling while maintaining authentic engagement is a sustainable approach for creators who have other responsibilities.'}
]},
{cat:'ai-media-content',d:2,s:'A major studio is using AI to generate background environments for films. Directors are concerned that AI backgrounds look visually similar across productions.',t:'AI-generated visual assets require art direction investment to maintain distinctive visual identity that differentiates one production from another.',options:[
  {text:'Accept some visual similarity since AI efficiency justifies the trade-off',score:0,feedbackText:'Visual similarity across productions dilutes brand identity and audience recognition. The efficiency of AI generation should not come at the cost of distinctive visual storytelling.'},
  {text:'Establish strong art direction briefs for AI-generated environments based on each production\'s unique visual identity, and involve visual development artists in reviewing and refining AI outputs',score:100,feedbackText:'Correct! Art direction briefs plus VFX artist review maintain visual identity within AI-generated environments. AI without art direction produces generic environments regardless of technical quality.'},
  {text:'Return to fully human-created backgrounds since AI cannot replicate the unique vision of skilled artists',score:-100,feedbackText:'Human artists working with strong art direction and AI tools can produce more distinctive environments than either alone. Categorical rejection of AI tools in visual effects forgoes significant capability.'}
]},
{cat:'ai-media-content',d:3,s:'An AI writing assistant used by your team has started generating content that subtly promotes a political viewpoint you have not authorized.',t:'AI systems with unexpected bias in generated content require immediate output auditing and prompt/model adjustment before further content is published.',options:[
  {text:'Note the political lean but continue publishing since all media has some editorial perspective',score:-100,feedbackText:'Accepting unauthorized AI political bias as equivalent to editorial perspective ignores the governance issue. Your editorial policy, not an AI model\'s training bias, should determine your political framing.'},
  {text:'Suspend AI-generated content immediately, audit recent published content for bias, identify the source of the bias in prompts or model behavior, and correct before resuming',score:100,feedbackText:'Excellent! Suspension, audit, root cause identification, and correction before resuming are the complete response. Publishing politically biased content without awareness is a governance failure.'},
  {text:'Add a human editor review step before all AI content is published to catch bias going forward',score:0,feedbackText:'Human review going forward is necessary but incomplete. Published content with undetected bias has already created audience exposure. Retroactive audit and correction should accompany the new process.'}
]},
{cat:'ai-media-content',d:1,s:'You want to use AI voice cloning to create content in languages you do not speak. The AI clones your voice in the target language.',t:'AI voice cloning for multilingual content is a powerful reach expansion tool but requires disclosure to audiences who may assume you speak the language.',options:[
  {text:'Publish AI-cloned multilingual content without disclosure since your voice is being used',score:0,feedbackText:'Your voice in a language you do not speak is a misrepresentation of your actual capabilities. Disclosure maintains the authenticity contract even as AI enables the reach expansion.'},
  {text:'Publish with clear disclosure that the audio was AI-generated in the target language, and partner with native speakers to review for accuracy and cultural appropriateness',score:100,feedbackText:'Correct! Disclosure plus native speaker review addresses both the authenticity and the quality issues. AI voice cloning expands reach; disclosure and review maintain trust and accuracy.'},
  {text:'Avoid AI voice cloning for languages you do not speak since it misrepresents your capabilities',score:-100,feedbackText:'Avoiding AI multilingual expansion categorically forecloses a major reach opportunity. The ethical issue is disclosure, not the use of the technology. Disclose and use it responsibly.'}
]},

// ===== ai-myths-facts (20) =====
{cat:'ai-myths-facts',d:1,s:'A colleague insists that the AI chatbot they use "understands" their questions the same way a human does.',t:'AI language models predict statistically likely word sequences — they process language without understanding meaning, intent, or context the way humans do.',options:[
  {text:'Agree since AI responses are often indistinguishable from human understanding',score:-100,feedbackText:'Human-like output does not require human-like understanding. AI produces fluent responses through statistical pattern matching without any comprehension of what it is saying.'},
  {text:'Explain that AI processes patterns in language without genuine understanding — it predicts likely responses rather than comprehending meaning',score:100,feedbackText:'Correct! The distinction between pattern-matching fluency and genuine comprehension is fundamental. Understanding this helps users use AI appropriately and catch its characteristic failures.'},
  {text:'Say that whether AI "understands" is a philosophical question without a clear answer',score:0,feedbackText:'While some philosophical debate exists, the computational reality is well understood: current AI language models do not process meaning the way biological cognition does.'}
]},
{cat:'ai-myths-facts',d:1,s:'Someone tells you that AI will soon surpass human intelligence in every domain and that this will happen within the next few years.',t:'Current AI systems are narrow specialists that exceed humans in specific, well-defined tasks but have no general intelligence or cross-domain reasoning comparable to humans.',options:[
  {text:'Agree since AI is advancing so rapidly that Artificial General Intelligence is imminent',score:-100,feedbackText:'AGI timelines are genuinely uncertain and contested among experts. "Imminent" is not a consensus view — and claims of near-term general human-surpassing intelligence consistently exceed what evidence supports.'},
  {text:'Clarify that current AI is narrow and task-specific, that AGI timelines are genuinely uncertain, and that responsible AI use today should not wait for a speculative future',score:100,feedbackText:'Correct! Current AI capability, AGI uncertainty, and the importance of acting on what we know now are the three grounded responses to AGI-imminence claims.'},
  {text:'Say AI will never surpass human intelligence since general intelligence is uniquely human',score:0,feedbackText:'Categorical certainty that AI will never surpass human general intelligence is also unsupportable. The honest answer is genuine uncertainty, not confident prediction in either direction.'}
]},
{cat:'ai-myths-facts',d:2,s:'A business decision-maker believes that larger AI models are always better for their use case than smaller ones.',t:'Model size affects capability but not always in the direction relevant to a specific use case — smaller, fine-tuned models often outperform large general models on narrow tasks.',options:[
  {text:'Agree since larger models have more parameters and therefore more capability',score:-100,feedbackText:'More parameters means more general capability, not more capability for your specific task. Fine-tuned smaller models regularly outperform large general models on narrow specialized applications.'},
  {text:'Explain that model selection should be based on task requirements: small specialized models often outperform large general ones for specific tasks and are much cheaper to run',score:100,feedbackText:'Excellent! Task-fit, cost, and latency are all better served by smaller specialized models in many practical applications. Biggest is not always best.'},
  {text:'Suggest running both and comparing results empirically since there is no general answer',score:0,feedbackText:'Empirical comparison is good advice but the underlying explanation matters too. Understanding why smaller specialized models can outperform large general ones informs future decisions beyond this one comparison.'}
]},
{cat:'ai-myths-facts',d:1,s:'A friend says they heard that AI is completely objective and unbiased because it works with data rather than emotions.',t:'AI systems encode the biases present in their training data and can amplify those biases at scale — data-based does not mean unbiased.',options:[
  {text:'Agree since mathematical processing eliminates the subjectivity that causes human bias',score:-100,feedbackText:'Training data reflects human decisions made with human biases. AI systems that learn from biased data learn to replicate those biases with mathematical consistency at scale.'},
  {text:'Explain that AI bias comes from training data, not emotions — and that biased data produces biased AI outputs that are often harder to detect than human bias',score:100,feedbackText:'Correct! Data-based bias is real and often less visible than human bias because it is expressed as statistical outputs. Understanding this is critical for responsible AI deployment.'},
  {text:'Say AI bias is possible but rare since data scientists review training data for bias before training',score:0,feedbackText:'Bias review in training data is improving but not comprehensive. Many forms of bias — historical, sampling, labeling — are difficult to detect and remove before training.'}
]},
{cat:'ai-myths-facts',d:2,s:'A product manager says your team does not need to worry about model hallucinations since your AI is connected to real-time data.',t:'Real-time data access reduces hallucination risk on factual queries but does not eliminate the model\'s tendency to generate confident incorrect statements on topics outside the retrieved data.',options:[
  {text:'Agree since real-time data retrieval means the AI always has access to current information',score:-100,feedbackText:'Real-time retrieval improves accuracy for retrievable facts but does not prevent hallucinations on topics outside what was retrieved or in reasoning chains that extend beyond retrieved data.'},
  {text:'Explain that real-time data reduces but does not eliminate hallucination — reasoning, edge cases, and topics not in the retrieved context can still produce confident incorrect output',score:100,feedbackText:'Correct! The distinction is important for quality design: verification protocols remain necessary even with real-time data retrieval because hallucination risk persists in retrieval gaps.'},
  {text:'Suggest testing the system to see how often it hallucinates rather than making general claims',score:0,feedbackText:'Empirical testing is valuable but the conceptual correction matters here: real-time retrieval does not eliminate hallucinations. This framing affects how the PM designs quality controls.'}
]},
{cat:'ai-myths-facts',d:1,s:'A manager says they cannot use AI for creative work since creativity is uniquely human and AI cannot truly create.',t:'AI can generate novel combinations, styles, and ideas that serve creative purposes — the debate about whether this constitutes "true" creativity does not affect its practical usefulness.',options:[
  {text:'Agree since creativity requires human experience, emotion, and intention that AI lacks',score:0,feedbackText:'The philosophical argument is valid but not practically useful. AI-generated creative work has demonstrable value as a starting point, inspiration source, and production accelerator regardless of whether it is "truly" creative.'},
  {text:'Explain that AI generates genuinely novel combinations that serve creative purposes — the practical question is whether the output is useful, not whether the process is identical to human creativity',score:100,feedbackText:'Correct! Practical utility is the right test for creative AI use. Whether AI "truly" creates is an interesting philosophical question but should not block access to a genuinely useful tool.'},
  {text:'Say AI can only remix existing creative work and therefore cannot be genuinely creative',score:-100,feedbackText:'Human creativity is also significantly influenced by prior exposure and cultural input. The remix critique applies to human creativity as well and does not distinguish AI from human creative processes as cleanly as it implies.'}
]},
{cat:'ai-myths-facts',d:2,s:'Someone argues that AI safety concerns are overblown by researchers who want to attract funding rather than address real problems.',t:'AI safety research addresses both near-term and long-term risks — current AI systems already exhibit harmful behaviors that safety research helps prevent.',options:[
  {text:'Agree since AI harms today are manageable and safety concerns about future AI are speculative',score:0,feedbackText:'Near-term AI harms from bias, privacy violations, and misinformation are not speculative — they are documented and ongoing. Safety research addressing these concerns is responding to real problems.'},
  {text:'Explain that AI safety research addresses both current harms from deployed AI systems and longer-term risks, and that dismissing it as a funding play ignores documented evidence of real harm',score:100,feedbackText:'Correct! The bifurcation into "real" near-term and "speculative" long-term concerns is a false framing. Current systems have real safety issues that safety research actively addresses.'},
  {text:'Agree that long-term AI risks are speculative but acknowledge near-term safety concerns are real',score:-100,feedbackText:'Partial agreement on near-term concerns is more accurate than full dismissal, but "speculative" for long-term risks overstates certainty. Both near-term and longer-term safety research responds to identified risk categories.'}
]},
{cat:'ai-myths-facts',d:1,s:'A skeptic in a meeting says that AI tools are just a trend that will fade like previous tech hypes.',t:'AI adoption differs from prior tech hypes in its breadth of use cases, proven productivity improvements, and integration into fundamental business processes.',options:[
  {text:'Agree since many technology hypes like blockchain and metaverse did not produce the promised transformation',score:0,feedbackText:'Some technology hypes do fade but AI differs in its practical, measurable productivity impact across a wide range of applications that are already demonstrably useful today.'},
  {text:'Distinguish AI from prior hypes by pointing to specific measurable productivity gains in deployed applications and the breadth of integration into everyday tools',score:100,feedbackText:'Correct! Evidence-based distinction from prior hypes is the right response to dismissal. Specific examples of documented productivity improvement are more persuasive than general enthusiasm.'},
  {text:'Strongly disagree since AI is clearly a permanent and transformative technology',score:-100,feedbackText:'Confident disagreement without evidence does not engage the skeptic\'s concern. Specific evidence of deployed impact and integration is more credible than counter-enthusiasm.'}
]},
{cat:'ai-myths-facts',d:2,s:'A developer claims that if you just make your prompts longer and more detailed, AI outputs will always be better.',t:'Prompt quality matters but longer prompts can introduce ambiguity, contradiction, and focus dilution — well-structured concise prompts often outperform verbose ones.',options:[
  {text:'Agree since more instruction and context gives AI more to work with',score:0,feedbackText:'More context has diminishing returns and negative returns when it introduces contradictions or buries the key instruction in noise. Prompt quality is not the same as prompt length.'},
  {text:'Explain that well-structured prompts with clear goals outperform verbose ones, and that unnecessary length can actually degrade output quality by diluting focus',score:100,feedbackText:'Correct! Clarity and structure drive prompt quality, not length. Long prompts that bury the core request in context noise often produce worse outputs than focused concise ones.'},
  {text:'Suggest testing longer versus shorter prompts empirically since there is no universal rule',score:-100,feedbackText:'Testing is always valuable but the conceptual error matters here. The developer will keep writing longer prompts expecting improvement. Understanding why length alone does not help shapes better prompting practice.'}
]},
{cat:'ai-myths-facts',d:1,s:'A friend says they never have to fact-check AI since it only says things it is confident about.',t:'AI confidence in output correlates poorly with accuracy — hallucinated facts are often expressed with the same certainty as correct ones.',options:[
  {text:'Agree since AI usually qualifies uncertain answers with phrases like "I think" or "I\'m not sure"',score:-100,feedbackText:'AI qualification of uncertainty is inconsistent. Hallucinated facts are frequently expressed with full declarative confidence. Confident AI output is not a reliable signal of accuracy.'},
  {text:'Explain that AI confidence and accuracy are poorly correlated — AI regularly states false information with complete certainty, making fact-checking essential for consequential uses',score:100,feedbackText:'Correct! The disconnect between AI expressed confidence and actual accuracy is one of the most important things to understand about current AI systems. It means verification cannot be skipped.'},
  {text:'Suggest using a more accurate AI model rather than fact-checking since model quality varies',score:0,feedbackText:'Better models do reduce hallucination rates but do not eliminate them. Fact-checking for consequential uses remains necessary regardless of model quality.'}
]},
{cat:'ai-myths-facts',d:2,s:'A startup is building their first AI product and a technical advisor tells them that more training data always produces a better model.',t:'Training data quality, relevance, and cleanliness matter more than raw quantity for many specific-domain AI applications.',options:[
  {text:'Agree since more diverse data exposes the model to more patterns',score:0,feedbackText:'More diverse data helps general models but for domain-specific applications, irrelevant data can dilute performance. Relevant, clean, quality data outperforms larger volumes of noisy data.'},
  {text:'Explain that data quality, relevance to the task, and cleanliness often matter more than volume, and that more data from irrelevant domains can actually reduce performance',score:100,feedbackText:'Excellent! Quality over quantity is a fundamental data insight for domain-specific AI. The startup needs to invest in curating relevant data, not just accumulating volume.'},
  {text:'Tell them to collect as much data as possible now and worry about quality later',score:-100,feedbackText:'Large volumes of low-quality or irrelevant data produce models that perform poorly on the target task and create technical debt from the need to clean what was accumulated carelessly.'}
]},
{cat:'ai-myths-facts',d:3,s:'A policy analyst says AI cannot make decisions, it only provides recommendations, and therefore humans bear full moral responsibility for all AI-related harms.',t:'While legal accountability rests with humans, AI systems making consequential recommendations can be designed to diffuse responsibility in ways that reduce actual accountability.',options:[
  {text:'Agree since humans who act on AI recommendations are always the responsible party',score:0,feedbackText:'Human accountability is legally correct but empirically weak when AI recommendations are presented with high confidence, acted on routinely, and the volume makes individual review notional.'},
  {text:'Explain that AI recommendation design affects real accountability: high-confidence framing, automation bias, and volume can reduce effective human oversight even when formal responsibility remains with humans',score:100,feedbackText:'Correct! Formal legal responsibility and effective accountability are not the same thing. AI system design that maintains genuine human oversight — not nominal oversight — is a design responsibility.'},
  {text:'Disagree since AI systems are autonomous agents that share moral responsibility for their outputs',score:-100,feedbackText:'AI systems are not moral agents. But the analyst\'s claim that human responsibility is always complete ignores the real ways AI system design affects the quality of human oversight.'}
]},
{cat:'ai-myths-facts',d:1,s:'A non-technical manager assumes that an AI trained on their company\'s data will keep that data private from other users of the same AI service.',t:'Training a shared AI model on proprietary data does not necessarily prevent that information from influencing outputs to other users — data handling architecture matters.',options:[
  {text:'Agree since companies contract with AI providers specifically to keep their data private',score:0,feedbackText:'Contractual data protection is important but different from technical isolation. Understanding how training data influences model outputs for other users requires reviewing the specific service architecture.'},
  {text:'Explain that how training data affects model behavior for other users depends on the AI service architecture, and that privacy guarantees require explicit technical and contractual verification',score:100,feedbackText:'Correct! Architecture determines privacy, not contracts alone. The manager needs to understand whether their data affects a shared model, a private fine-tune, or is only used in their inference context.'},
  {text:'Reassure the manager that reputable AI providers always keep training data isolated',score:-100,feedbackText:'Reputation is not technical architecture. The specific service design determines data isolation. Assuming reputation guarantees isolation leads to unvalidated privacy claims.'}
]},
{cat:'ai-myths-facts',d:2,s:'A CEO says their company is "AI-first" because they use ChatGPT for some administrative tasks.',t:'AI-first as a business strategy means systematically integrating AI into core processes and decisions — it is far more than using consumer AI tools for administrative convenience.',options:[
  {text:'Agree since using AI tools at all reflects forward-thinking adoption',score:-100,feedbackText:'Consumer AI tool use for administrative tasks is basic adoption, not strategic transformation. Agreeing inflates the CEO\'s assessment and provides false confidence about their actual AI maturity.'},
  {text:'Gently distinguish between AI tool adoption and AI-first strategy, which requires systematic integration into core workflows, decision processes, and business model',score:100,feedbackText:'Correct! The distinction matters because strategic AI investment requires honest assessment of current maturity. Conflating tool adoption with strategy leads to underinvestment in genuine transformation.'},
  {text:'Avoid challenging the CEO\'s framing since the label matters less than the actual adoption behavior',score:0,feedbackText:'The framing does matter because it shapes investment priorities. A CEO who believes they are AI-first based on ChatGPT use may not invest in the deeper integration that actual AI-first strategy requires.'}
]},
{cat:'ai-myths-facts',d:1,s:'A student argues that AI will make learning unnecessary since AI can answer any question instantly.',t:'AI can retrieve and explain information instantly but cannot develop the underlying cognitive structures that learning builds — comprehension, synthesis, and judgment require active engagement.',options:[
  {text:'Partially agree since AI does remove the need to memorize information',score:0,feedbackText:'Memorization is only one aspect of learning. Comprehension, analysis, application, and creative synthesis — the cognitive structures that enable original thinking — require active learning, not retrieval.'},
  {text:'Explain that AI can retrieve and explain information, but the cognitive development that comes from learning — reasoning, judgment, creative synthesis — cannot be acquired by reading AI outputs',score:100,feedbackText:'Correct! The distinction between information access and cognitive development is fundamental. AI answers the question; learning builds the capacity to ask better questions and evaluate answers.'},
  {text:'Agree that learning will need to fundamentally change because of AI, and this is a positive development',score:-100,feedbackText:'Learning will evolve with AI but framing AI answer access as reducing the need to learn misunderstands what learning produces. Cognitive development is not achieved by information retrieval.'}
]},
{cat:'ai-myths-facts',d:2,s:'Someone says that because AI cannot feel emotions, it is fundamentally safer and more reliable than humans for high-stakes decision-making.',t:'Absence of emotion does not make AI systems reliable for high-stakes decisions — they have different but equally serious failure modes including hallucination, bias, and distribution shift.',options:[
  {text:'Agree since emotional bias is one of the main sources of human decision-making error',score:0,feedbackText:'Emotional bias is a real human limitation but the comparison is not simply "emotional humans vs. unbiased AI." AI has its own serious failure modes that can be more dangerous precisely because they are less visible.'},
  {text:'Explain that AI failure modes — hallucination, training data bias, distribution shift — are different from human biases but equally serious and often less obvious to detect',score:100,feedbackText:'Excellent! Different failure mode profiles, not inherent reliability superiority, is the accurate comparison. AI errors can be systematic and at scale in ways human errors typically are not.'},
  {text:'Disagree completely since humans are always more reliable than AI for important decisions',score:-100,feedbackText:'Humans also have serious and systematic decision-making failures. The right frame is understanding each system\'s specific failure modes and designing governance to address both.'}
]},
{cat:'ai-myths-facts',d:1,s:'An executive claims that the company\'s use of AI is transparent because they disclosed it in a footnote of their annual report.',t:'Transparency in AI use means users affected by AI systems understand what is being used, how it affects them, and what they can do about it — not disclosure buried in regulatory filings.',options:[
  {text:'Accept that the disclosure is sufficient since annual report disclosure satisfies legal requirements',score:0,feedbackText:'Legal sufficiency and meaningful transparency are not the same thing. Users affected by AI systems need actionable information at the point of impact, not buried regulatory text.'},
  {text:'Explain that meaningful AI transparency requires disclosure at the point of user impact in language users can understand, not legal boilerplate in annual reports',score:100,feedbackText:'Correct! Point-of-impact transparency in accessible language is the standard that builds genuine user understanding. Annual report footnotes satisfy regulatory minimums but not meaningful transparency.'},
  {text:'Argue that AI use does not require any disclosure since it is an internal business process',score:-100,feedbackText:'AI systems that affect users, make decisions about them, or interact with them require appropriate disclosure under emerging regulations and ethical norms, regardless of how they are classified internally.'}
]},
{cat:'ai-myths-facts',d:3,s:'A researcher claims that AI neural networks are black boxes that can never be interpreted or understood, making explainability fundamentally impossible.',t:'Explainability in AI ranges from impossible for some architectures to practically achievable for others — the field has produced real techniques that work in specific contexts.',options:[
  {text:'Agree since the internal computations of deep neural networks are indeed incomprehensible',score:0,feedbackText:'Full mechanistic interpretability of large models is extremely difficult but practical explainability techniques that explain specific decisions to specific audiences do exist and work.'},
  {text:'Explain that explainability exists on a spectrum — some models are fully interpretable, others support local explanations of specific decisions, and full mechanistic transparency is the hardest frontier',score:100,feedbackText:'Correct! The spectrum framing is accurate. LIME, SHAP, attention analysis, and inherently interpretable models all provide real explanatory value. "Fundamentally impossible" overstates the current state.'},
  {text:'Disagree completely since AI systems can always be fully explained if the engineers work hard enough',score:-100,feedbackText:'Full mechanistic interpretability of large models is a genuinely hard open research problem. "Always possible with effort" overstates the current state in the other direction.'}
]},
{cat:'ai-myths-facts',d:2,s:'A hiring manager says they use AI to screen candidates "objectively" and therefore their hiring process is now free from the unconscious biases that plagued manual review.',t:'Algorithmic screening replaces some human biases with different algorithmic biases — often the biases in historical hiring data that the AI learned from.',options:[
  {text:'Agree since mathematical algorithms cannot be unconsciously biased the way humans are',score:-100,feedbackText:'Algorithms cannot be unconsciously biased, but they can encode historical biases explicitly. AI trained on biased historical hiring data replicates those biases systematically.'},
  {text:'Explain that AI screening replaces human unconscious bias with algorithmic bias from training data — and that the algorithmic version is often harder to detect and easier to scale',score:100,feedbackText:'Correct! Algorithmic bias is different from human bias but not less real. The change of bias type does not eliminate bias, and the systematic nature of algorithmic bias makes it potentially more harmful at scale.'},
  {text:'Partially agree since AI bias is at least consistent, even if it reflects historical hiring patterns',score:0,feedbackText:'Consistent bias is not better than inconsistent bias if it consistently disadvantages protected groups. Consistency in replicating historical discrimination is not a virtue.'}
]},

// ===== ai-psychology (20) =====
{cat:'ai-psychology',d:1,s:'You notice that when an AI chatbot expresses sympathy for your situation, you feel genuinely comforted even knowing it is an AI.',t:'Emotional responses to AI are natural human reactions to social cues — this does not mean AI has feelings, but it does mean users may form parasocial attachments that deserve awareness.',options:[
  {text:'Dismiss the comfort as irrational since AI cannot actually feel empathy',score:0,feedbackText:'Dismissing the emotional response as irrational misses its reality. The comfort is genuine — the important insight is understanding what produces it and maintaining clear perspective on what the AI relationship is.'},
  {text:'Acknowledge that emotional responses to AI are natural human reactions to social cues, while staying aware that AI does not have genuine empathy or concern for your wellbeing',score:100,feedbackText:'Correct! Both things can be true: the comfort is real, and the AI does not have feelings. Awareness of this distinction prevents parasocial AI attachment from substituting for genuine social support.'},
  {text:'Conclude that AI must have genuine empathy since it produces genuine emotional responses',score:-100,feedbackText:'Emotional response in the user does not imply emotional state in the AI. Social cues designed to mimic empathy reliably trigger human emotional responses without requiring genuine empathy in the source.'}
]},
{cat:'ai-psychology',d:2,s:'A colleague has started relying on AI validation before making any workplace decision, even minor ones. They seem anxious when the AI disagrees.',t:'Unhealthy AI reliance can erode decision-making confidence and create dependency that reduces professional effectiveness. Awareness and deliberate practice of independent judgment are needed.',options:[
  {text:'Encourage them since AI validation improves decision quality for any decision size',score:-100,feedbackText:'AI validation for minor decisions creates dependency without proportional benefit. Routine validation-seeking for all decisions is a pattern that reduces autonomous decision-making capacity over time.'},
  {text:'Gently note the pattern and suggest reserving AI validation for genuinely complex decisions while practicing independent judgment on routine ones',score:100,feedbackText:'Excellent! Tiered AI use that reserves AI for complexity is both more effective and healthier. Deliberate practice of independent judgment on routine decisions preserves that capacity for when it matters.'},
  {text:'Ignore the behavior since colleagues have the right to use AI tools as they see fit',score:0,feedbackText:'While autonomy matters, a pattern that visibly reduces a colleague\'s functioning is worth a conversation. Supportive observation is different from judgment or control.'}
]},
{cat:'ai-psychology',d:1,s:'You have been talking to an AI chatbot about personal problems and realize it has become your primary outlet for emotional processing.',t:'AI can be a useful thinking tool for processing thoughts, but human connection is irreplaceable for genuine emotional support and mental health.',options:[
  {text:'Continue using the AI as your primary outlet since it is always available and non-judgmental',score:-100,feedbackText:'AI availability and non-judgment are real features, but they do not substitute for the reciprocal human connection that genuine emotional support requires. AI as primary outlet can mask social isolation.'},
  {text:'Recognize the pattern and intentionally invest in human relationships for emotional support while using AI as a supplementary thinking tool',score:100,feedbackText:'Correct! AI as a supplementary thinking tool plus human relationships for genuine support is the healthy balance. Noticing the pattern and rebalancing is the right response.'},
  {text:'Reduce all AI chatbot use since the dependency suggests AI is harmful for mental health',score:0,feedbackText:'AI chatbot use is not inherently harmful and can genuinely help with thought organization. The issue is substitution for rather than supplementation of human connection.'}
]},
{cat:'ai-psychology',d:2,s:'Research shows that people trust AI medical diagnoses more when the AI presents information confidently, even when confidence is unwarranted.',t:'AI-expressed confidence is a design choice, not a reliability signal — health information requires verification regardless of how certain AI sounds.',options:[
  {text:'Use this insight to build more confident-sounding AI systems since users trust them more',score:-100,feedbackText:'Exploiting confidence bias to increase trust in potentially unreliable information is manipulative and creates real harm when users act on AI medical information without appropriate verification.'},
  {text:'Design AI systems to calibrate expressed confidence to actual accuracy, and educate users that confident AI delivery is not a reliability signal',score:100,feedbackText:'Correct! Calibrated confidence expression plus user education about the confidence bias are both needed. Trust should track accuracy, not delivery style.'},
  {text:'Present AI medical information with maximum uncertainty to prevent users from over-trusting it',score:0,feedbackText:'Maximum uncertainty framing prevents over-trust but also prevents legitimate use. Calibrated confidence that tracks actual reliability is better than deliberately understated confidence.'}
]},
{cat:'ai-psychology',d:1,s:'A student says they feel less creative since they started using AI for brainstorming because they always prefer the AI\'s ideas to their own.',t:'AI-first brainstorming can anchor your thinking to AI ideas before your own have a chance to develop. Generating your own ideas first preserves independent creative capacity.',options:[
  {text:'Tell them to stop using AI for brainstorming since it is clearly harming their creativity',score:0,feedbackText:'Full removal is not necessarily the right response. The anchoring effect comes from when AI is introduced in the process, not from using AI at all.'},
  {text:'Suggest generating their own ideas first before consulting AI, then using AI to expand or challenge those ideas rather than replace them',score:100,feedbackText:'Excellent! Process sequencing resolves the anchoring problem. Your-ideas-first preserves the creative generation phase; AI expands rather than anchors when introduced afterward.'},
  {text:'Agree that their AI-generated ideas are probably better and encourage them to use AI more',score:-100,feedbackText:'Affirming that AI ideas are better and encouraging more AI use accelerates the creative dependency rather than addressing it. Independent creative capacity is worth developing.'}
]},
{cat:'ai-psychology',d:2,s:'Your team consistently goes along with AI recommendations in meetings without critical evaluation, a pattern called automation bias.',t:'Automation bias in teams requires explicit process interventions — assigned critics, required objections, or pre-AI evaluation rounds — to restore genuine critical evaluation.',options:[
  {text:'Reduce AI recommendation frequency to encourage more independent thinking',score:0,feedbackText:'Less frequent AI recommendations is a partial intervention but does not address the bias itself. When recommendations do appear, the team still accepts them uncritically.'},
  {text:'Introduce a structured devil\'s advocate process where someone is explicitly assigned to challenge any AI recommendation before the team accepts it',score:100,feedbackText:'Correct! Explicit process interventions like assigned critics overcome automation bias by making critical evaluation a formal role rather than an optional individual behavior.'},
  {text:'Replace AI recommendations with AI-generated option lists so the team has to choose rather than accept',score:-100,feedbackText:'Option lists rather than recommendations is one tool but does not address the underlying bias if team members still systematically favor the AI\'s top option without genuine evaluation.'}
]},
{cat:'ai-psychology',d:3,s:'An AI companion app is designed to be maximally engaging to retain users. You notice users report feeling worse about themselves after extended sessions.',t:'AI engagement optimization that maximizes session time without regard to user wellbeing can produce compulsive use patterns that damage mental health.',options:[
  {text:'Assume the correlation is coincidental since AI companions are designed to be supportive',score:-100,feedbackText:'Supportive design intent does not prevent harmful engagement patterns. Engagement optimization that ignores psychological wellbeing can produce addictive use regardless of stated intent.'},
  {text:'Investigate whether the engagement design is optimizing metrics that conflict with user wellbeing, then redesign for wellbeing outcomes rather than session time',score:100,feedbackText:'Excellent! Wellbeing-aligned engagement design requires explicitly including wellbeing metrics in the optimization target. Session time as the sole metric will always trade user welfare for engagement.'},
  {text:'Add a daily usage limit since the problem is likely overuse rather than app design',score:0,feedbackText:'Usage limits are a partial intervention but address the symptom rather than the design problem. If the app produces negative wellbeing effects, a time limit reduces exposure without fixing the experience.'}
]},
{cat:'ai-psychology',d:1,s:'You notice that using AI for writing has made you more critical of your own unassisted writing since AI output often sounds more polished.',t:'Comparing your first-draft writing to polished AI output sets an unfair standard — AI outputs represent a finished product while your drafts represent a starting point.',options:[
  {text:'Use AI to polish all your writing before evaluating it since your raw drafts are now clearly below standard',score:-100,feedbackText:'Making AI-polished output your quality standard for first drafts creates an unsustainable workflow and erodes confidence in your authentic writing voice.'},
  {text:'Recognize that comparing your first draft to AI-polished output is an unfair comparison, and evaluate your writing against your own editing process rather than AI-generated alternatives',score:100,feedbackText:'Correct! Fair comparison is your best draft to AI output, not your first draft. AI never shares its rough drafts, so comparing to its finished output systematically undervalues your work.'},
  {text:'Agree that your unassisted writing is now below standard and focus on developing your AI prompting skills instead of writing skills',score:0,feedbackText:'Writing skills remain valuable and are what give you the ability to judge, edit, and improve AI output. Replacing writing development with prompting skills alone sacrifices a core capability.'}
]},
{cat:'ai-psychology',d:2,s:'A therapy chatbot has become popular among people with social anxiety because it lets them practice conversations without fear of judgment. Clinical psychologists have mixed views.',t:'AI-assisted social practice can reduce avoidance but must include real-world social exposure as the ultimate therapeutic goal, not permanent AI substitute socialization.',options:[
  {text:'Support the chatbot fully since any reduction in social anxiety is a positive outcome',score:0,feedbackText:'Reduction in anxiety within AI-only settings does not automatically transfer to real social situations. The therapeutic goal must include real-world exposure, which requires clinical guidance.'},
  {text:'Endorse AI practice as a low-stakes starting point with a clear clinical pathway toward real social exposure, guided by a therapist who monitors for avoidance reinforcement',score:100,feedbackText:'Excellent! AI practice as a step toward, not a substitute for, real social interaction is the clinically sound framing. Therapist oversight prevents the practice phase from becoming avoidance reinforcement.'},
  {text:'Reject the chatbot since therapeutic interventions must involve human therapists',score:-100,feedbackText:'Clinical human involvement is important for guidance but AI-assisted practice tools can serve legitimate therapeutic functions when integrated into a supervised treatment plan.'}
]},
{cat:'ai-psychology',d:1,s:'An AI recommender system has been showing you content so well-matched to your tastes that you have stopped exploring new topics or trying new things.',t:'AI personalization can inadvertently narrow experience and curiosity — deliberate exploration outside recommendations is a healthy counter-habit.',options:[
  {text:'Continue using the AI recommendations since they consistently give you content you enjoy',score:0,feedbackText:'Consistent enjoyment within a personalized bubble is comfortable but narrows exposure over time. The recommendations reflect your past preferences, which can freeze your interests rather than develop them.'},
  {text:'Regularly explore outside AI recommendations to maintain diverse interests and prevent your preferences from narrowing around what the algorithm already knows you like',score:100,feedbackText:'Correct! Deliberate exploration outside the recommendation bubble maintains the curiosity and exposure diversity that algorithm-served preferences gradually erode.'},
  {text:'Turn off all AI recommendations since personalization is harmful to intellectual development',score:-100,feedbackText:'AI recommendations have real value for discovery within known interest areas. The problem is exclusive reliance, not the tool itself. Supplementing recommendations with deliberate exploration is better than eliminating them.'}
]},
{cat:'ai-psychology',d:2,s:'A manager notices their team members are more confident in decisions when an AI tool confirms their initial instinct, even for complex uncertain decisions.',t:'AI confirmation of intuition can bypass the critical evaluation that uncertain complex decisions require — confidence should come from reasoning quality, not AI agreement.',options:[
  {text:'Encourage the pattern since AI-confirmed decisions reduce team anxiety and decision paralysis',score:-100,feedbackText:'Reduced anxiety from AI confirmation is not the same as better decisions. For complex uncertain decisions, confidence that bypasses critical evaluation is a problem, not a solution.'},
  {text:'Set a team norm that AI agreement with initial instincts requires the same scrutiny as AI disagreement — confidence in uncertain decisions must come from reasoning quality',score:100,feedbackText:'Excellent! Symmetric skepticism — applying the same critical evaluation to AI agreement and disagreement — is the right norm. AI confirmation should trigger deeper analysis, not reduce it.'},
  {text:'Stop using AI for decision support since it is clearly distorting the team\'s decision process',score:0,feedbackText:'Removing AI is disproportionate when the problem is a specific misuse pattern. Establishing norms for how to engage with AI confirmation is a more targeted and useful response.'}
]},
{cat:'ai-psychology',d:3,s:'Cognitive research shows that people who use AI for extended periods begin to change how they think, relying more on external validation and less on internal reasoning.',t:'Intentional use habits that preserve internal reasoning — including deliberate non-AI practice, meta-cognition, and explicit independence exercises — maintain cognitive capacity.',options:[
  {text:'Accept cognitive changes as the natural adaptation to a new cognitive tool environment',score:0,feedbackText:'Adaptation is natural but adaptive shifts that erode independent reasoning capacity deserve deliberate intervention. The goal is augmentation, not substitution, of human cognitive capacity.'},
  {text:'Build deliberate habits that preserve internal reasoning: practice solving certain problem types without AI regularly, and treat AI as an amplifier of your own thinking rather than a replacement',score:100,feedbackText:'Excellent! Deliberate practice for preserved capacity plus amplifier mindset are the two habits that maintain cognitive independence alongside AI use. The research finding is a design challenge, not a deterministic outcome.'},
  {text:'Stop using AI for all cognitive tasks to prevent cognitive dependency',score:-100,feedbackText:'Full avoidance prevents the negative cognitive effects but forecloses all the amplification benefits. Deliberate use habits are a more proportionate and practical response than abstinence.'}
]},
{cat:'ai-psychology',d:1,s:'You notice you feel a twinge of guilt when you correct or criticize an AI assistant, even though you know it has no feelings.',t:'Anthropomorphizing AI — attributing human emotions and social expectations to it — is natural but can inhibit users from providing the critical feedback that improves AI performance.',options:[
  {text:'Trust the feeling as a signal that you should treat AI more carefully to avoid harmful interactions',score:-100,feedbackText:'The guilt feeling is about you, not the AI. Acting on anthropomorphization feelings by avoiding correction makes your AI use less effective and the AI less accurate.'},
  {text:'Recognize the anthropomorphization tendency as natural while reminding yourself that direct correction of AI errors makes AI more useful and does not cause any harm',score:100,feedbackText:'Correct! Awareness of the anthropomorphization instinct without being controlled by it is the right stance. Correcting AI is not unkind — it is good usage practice.'},
  {text:'Immediately stop using any AI that triggers anthropomorphizing responses since this indicates psychological risk',score:0,feedbackText:'Anthropomorphization responses to social AI cues are universal human tendencies, not psychological risks. Awareness and perspective are sufficient — avoidance is not necessary.'}
]},
{cat:'ai-psychology',d:2,s:'A mental health professional is considering using AI to generate psychotherapy session notes from recordings. Their clients are not aware of this.',t:'Recording and AI processing of therapy sessions for any purpose requires explicit informed client consent under both ethical codes and privacy law.',options:[
  {text:'Proceed with AI note generation since the notes are only for the therapist\'s internal clinical records',score:-100,feedbackText:'Client confidentiality applies to therapy recordings regardless of their intended use. Processing recordings with AI tools without explicit consent violates both clinical ethics and privacy law.'},
  {text:'Obtain explicit informed consent from each client explaining that sessions are recorded and processed by AI for note generation before using the tool',score:100,feedbackText:'Excellent! Explicit informed consent before recording plus before AI processing is the required ethical and legal standard. Clients must understand and agree before any recording or AI processing occurs.'},
  {text:'Ask clients to sign a general consent form that includes session documentation methods without specifically mentioning AI',score:0,feedbackText:'General documentation consent does not satisfy the specificity requirement for AI processing of therapy sessions. Explicit disclosure that AI processes session recordings is a separate and required element.'}
]},
{cat:'ai-psychology',d:1,s:'Your company has implemented an AI that provides mental health support resources to employees. A manager wants to use the data to identify employees struggling with stress.',t:'Mental health AI data used to identify struggling employees for management intervention destroys the trust that makes the tool useful and may violate health data privacy law.',options:[
  {text:'Allow limited manager access to aggregated data since the goal is to help employees, not penalize them',score:0,feedbackText:'Even aggregated data tied to identifiable employees in small teams destroys confidentiality. Employees who fear management exposure will not use the tool, eliminating all benefit.'},
  {text:'Prohibit all manager access to individual or small-group data and communicate that commitment clearly to employees so they can use the resource confidently',score:100,feedbackText:'Correct! Absolute data firewall between the mental health tool and management is the only design that maintains employee trust. Clear communication of this commitment drives utilization.'},
  {text:'Use the data only for proactive wellness check-ins, not for performance management',score:-100,feedbackText:'Any management use of mental health tool data — even well-intentioned — creates the identification risk that makes employees avoid using the tool. The firewall must be complete.'}
]},
{cat:'ai-psychology',d:2,s:'A student uses AI to simulate difficult conversations with their parents before having them in real life. They say it helps them feel prepared.',t:'AI-simulated practice for real conversations is a legitimate preparation tool when it develops genuine flexible communication skills rather than script memorization.',options:[
  {text:'Encourage the practice entirely since preparation always improves communication',score:0,feedbackText:'Preparation helps when it builds flexible response skills. Over-scripted preparation can make real conversations more rigid if the other person deviates from the simulated path.'},
  {text:'Encourage practice that focuses on flexible listening and response rather than memorized scripts, so the preparation transfers to unpredictable real conversations',score:100,feedbackText:'Excellent! Flexibility practice transfers to real conversations; script memorization often does not. AI practice is most valuable when it develops adaptive skills rather than specific expected responses.'},
  {text:'Discourage AI simulation since rehearsed conversations feel inauthentic in real life',score:-100,feedbackText:'Preparation does not make conversations inauthentic — it makes people more capable and less defensive in difficult moments. The design of the practice matters more than whether practice occurred.'}
]},
{cat:'ai-psychology',d:3,s:'Social media companies use AI to maximize user engagement. Critics say this design deliberately exploits psychological vulnerabilities to create compulsive use.',t:'Engagement-optimized AI design can exploit psychological vulnerabilities like variable reward schedules — users benefit from understanding these mechanisms to manage their own use.',options:[
  {text:'Trust that companies design responsibly since users would stop using platforms that harm them',score:-100,feedbackText:'Users often cannot stop using platforms that exploit compulsive use mechanisms — that is the mechanism\'s purpose. Harm that is psychologically compelling is not self-correcting.'},
  {text:'Understand the variable reward and engagement mechanisms these systems use, then make deliberate choices about use patterns rather than defaulting to algorithm-driven behavior',score:100,feedbackText:'Correct! Mechanism awareness is the foundation of intentional use. Understanding why certain design patterns are compelling lets you choose engagement based on your actual interests.'},
  {text:'Avoid all engagement-optimized platforms since the psychological manipulation cannot be resisted',score:0,feedbackText:'Avoidance is one valid choice but mechanism awareness enables intentional use rather than requiring total abstinence. The goal is agency, not necessarily abstinence.'}
]},
{cat:'ai-psychology',d:1,s:'You find yourself dismissing your own well-reasoned conclusions when an AI presents a different answer, even when you cannot identify any flaw in your reasoning.',t:'AI authority bias — over-deferring to AI outputs over your own sound reasoning — is a specific form of automation bias worth recognizing and resisting.',options:[
  {text:'Accept the AI answer since it likely has access to more information than you do',score:0,feedbackText:'Access to more information does not guarantee a better conclusion. Your reasoning may have considered context, values, or constraints that the AI did not. Investigate the discrepancy rather than deferring.'},
  {text:'Compare your reasoning to the AI\'s reasoning rather than just the conclusions, and maintain your conclusion when your reasoning is sound even if the AI concludes differently',score:100,feedbackText:'Excellent! Reasoning comparison rather than conclusion comparison is the right approach to AI disagreement. Your sound reasoning has evidential weight independent of AI output.'},
  {text:'Conclude that your AI tool is biased or wrong and switch to a different one',score:-100,feedbackText:'Switching tools to get a preferred answer is confirmation-bias-driven AI use. Engaging with the reasoning discrepancy is more valuable than finding an AI that agrees with you.'}
]},
{cat:'ai-psychology',d:2,s:'After using AI writing assistants extensively, you realize you now write with more hedging language and qualifications than before, mimicking AI style.',t:'AI writing style influence on human writing voice is a real phenomenon — deliberate practice of writing without AI assistance periodically preserves authentic voice.',options:[
  {text:'Accept the stylistic evolution since AI-influenced writing is clearer and more nuanced',score:0,feedbackText:'AI hedging and qualification patterns serve AI accuracy requirements but may not serve your authentic communication goals. Whether the evolution improves or homogenizes your voice requires honest assessment.'},
  {text:'Periodically write important communications without AI assistance and compare to AI-influenced output to maintain awareness of your authentic voice and make deliberate style choices',score:100,feedbackText:'Correct! Periodic non-AI practice maintains voice awareness and the ability to make deliberate style choices. Style should reflect your intentions, not unconscious AI mimicry.'},
  {text:'Stop using AI writing tools entirely since they are changing your authentic voice',score:-100,feedbackText:'Full removal is disproportionate when periodic non-AI practice can preserve voice awareness. The goal is intentional style choice, not abstinence from AI writing assistance.'}
]},

// Extra questions to top off short categories
{cat:'ai-customer-service',d:2,s:'Your AI support bot handles billing queries but a regulation now requires that customers disputing charges must be able to reach a human within two minutes.',t:'Regulatory escalation timeline requirements must be technically implemented, not just policy-stated — two-minute paths to humans require queue and routing design that guarantees the SLA.',options:[
  {text:'Update your customer service policy to state that human escalation is available within two minutes',score:0,feedbackText:'Policy statements are not technical implementations. If the routing system cannot deliver a human within two minutes, the policy is a liability rather than a compliance measure.'},
  {text:'Design and test an escalation routing path that guarantees a human connection within the two-minute SLA, then monitor compliance with alerts for any breaches',score:100,feedbackText:'Excellent! Technical implementation plus SLA monitoring is the complete compliance design. The regulation requires a working escalation path, not a stated commitment to one.'},
  {text:'Apply for a regulatory exemption since two-minute human access is operationally challenging at scale',score:-100,feedbackText:'Seeking exemptions from consumer protection escalation requirements is both risky and reputationally damaging. Technical solutions that satisfy the requirement exist and are the right path.'}
]},
{cat:'ai-health',d:2,s:'A patient management AI in a dental practice schedules patient recall appointments based on AI-determined risk scores. Patients are not told their score.',t:'AI-determined health scores that affect care scheduling require patient disclosure and should be explainable in plain language when patients ask.',options:[
  {text:'Continue without disclosure since recall scheduling is an administrative function, not a clinical decision',score:0,feedbackText:'AI that determines when and how often patients receive care is a consequential health decision, not merely administrative scheduling. Patients have legitimate interests in understanding what drives their care timing.'},
  {text:'Disclose to patients that AI-assisted risk scoring helps prioritize recall timing, explain the factors considered, and allow patients to discuss their score with their provider',score:100,feedbackText:'Correct! Disclosure, explanation, and discussion pathway are the appropriate patient transparency measures for AI-driven care scheduling. Patients should understand what affects the timing of their healthcare.'},
  {text:'Rely on professional judgment overriding any AI score to ensure transparency is maintained at the clinical level',score:-100,feedbackText:'Clinical override is important but does not satisfy patient disclosure needs. Patients benefit from knowing AI influences their scheduling even when clinical judgment remains the final authority.'}
]},
{cat:'ai-health',d:1,s:'A telehealth platform uses AI triage to determine how quickly patients should be seen. A patient who was classified as low urgency later had a serious condition.',t:'AI triage misclassification in healthcare is a known risk that requires clear error reporting mechanisms and continuous model recalibration based on outcome data.',options:[
  {text:'Treat the case as a one-time statistical outlier since no triage system is perfectly accurate',score:0,feedbackText:'Retrospective analysis of misclassified cases is how AI triage models improve. Treating adverse outcomes as outliers without review prevents the learning cycle that improves safety.'},
  {text:'Review the case factors that led to misclassification, add them to the model retraining dataset, and check whether similar presentation patterns are also being misclassified',score:100,feedbackText:'Excellent! Case review plus model improvement plus similar-pattern audit is the complete quality cycle for AI triage. Each misclassification is both a care failure and a training signal.'},
  {text:'Replace the AI triage system with human triage since AI misclassification is unacceptable in healthcare',score:-100,feedbackText:'Human triage also has classification errors and at higher cost and lower scalability. The appropriate response is improving AI accuracy through systematic outcome review, not categorical rejection.'}
]},
{cat:'ai-manufacturing',d:2,s:'Your AI supply chain system suggests switching to a cheaper supplier based on cost optimization. The current supplier has been a trusted partner for fifteen years.',t:'AI cost optimization surfaces financial opportunities but cannot quantify relationship value, supply security, or switching risks that experienced procurement professionals can assess.',options:[
  {text:'Follow the AI recommendation immediately since cost optimization directly impacts profitability',score:-100,feedbackText:'Cost optimization that ignores relationship value, switching costs, and supply security risk can produce short-term savings with significant long-term operational exposure.'},
  {text:'Use the AI cost analysis as one input alongside relationship assessment, supply security evaluation, and switching cost analysis before making the sourcing decision',score:100,feedbackText:'Correct! AI provides the cost signal; procurement expertise adds the relationship, risk, and switching cost dimensions AI cannot quantify. All inputs together produce a sound decision.'},
  {text:'Ask the current supplier to match the price identified by AI to avoid any switching risk',score:0,feedbackText:'Price negotiation is a valid use of the AI cost analysis but does not resolve the strategic question of supplier diversification or supply security that may underlie the optimization suggestion.'}
]},
{cat:'ai-manufacturing',d:1,s:'Your factory wants to implement AI-driven lights-out manufacturing for overnight shifts with no human workers present.',t:'Lights-out AI manufacturing requires comprehensive safety monitoring, automatic shutdown triggers, and defined response protocols before human-free operation is safe.',options:[
  {text:'Implement lights-out manufacturing immediately since the AI automation is reliable enough based on daytime testing',score:-100,feedbackText:'Daytime testing with human oversight does not validate safety of unmonitored overnight operation. Night-specific failure modes and emergency response scenarios require specific evaluation and design.'},
  {text:'Design and test comprehensive monitoring systems, automatic shutdown triggers for safety events, remote alert protocols, and on-call response procedures before beginning unmonitored overnight operation',score:100,feedbackText:'Excellent! Monitoring plus auto-shutdown plus alert protocols plus response procedures are the four safety infrastructure requirements for unmonitored manufacturing. All must be tested before lights-out operation begins.'},
  {text:'Run lights-out manufacturing with a single overnight security guard who monitors cameras',score:0,feedbackText:'Camera monitoring by a single security guard is insufficient for industrial safety response. Production equipment failures require skilled technical response that one non-technical guard cannot provide.'}
]}

]

for(let i=0; i<ALL.length; i+=20) {
  const batch = ALL.slice(i, i+20)
  const cat = batch[0].cat
  process.stdout.write(`Inserting ${batch.length} ${cat} questions... `)
  const ok = await insert(batch)
  if(!ok) { console.error('FAILED at index', i); break }
}
console.log('DONE. Total:', ALL.length)
