const TOKEN = 'sbp_f314cf27b5b2a01eea48048a7b1c015cc9cf4b42'
const API = 'https://api.supabase.com/v1/projects/amhfxaqolholacanqyas/database/query'
function esc(s) { return s.replace(/'/g, "''") }
async function insert(batch) {
  const values = batch.map(q => {
    const opts = JSON.stringify(q.options).replace(/'/g, "''")
    return `('es','${q.cat}','${esc(q.s)}','${esc(q.t)}','${opts}'::jsonb,${q.d},'claude',true)`
  }).join(',')
  const sql = `INSERT INTO questions (locale,category,scenario_text,mindset_tip,options,difficulty,generated_by,is_active) VALUES ${values};`
  const r = await fetch(API, {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${TOKEN}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query: sql })
  })
  const d = await r.json()
  if (d.message) { console.error('ERR:', d.message); return false }
  console.log('OK:', batch.length, 'inserted')
  return true
}

const ALL = [
  // ai-myths-facts (14)
  { cat: 'ai-myths-facts', d: 1, s: 'Un colega afirma que la IA "piensa como un humano". Tu respuesta técnicamente correcta es...', t: 'Los modelos de IA actuales son sistemas estadísticos que predicen patrones en datos. No tienen comprensión, intenciones ni conciencia — aunque sus outputs parezcan cognitivos.', options: [{ text: 'La IA procesa patrones estadísticos en datos, no razona ni comprende como un humano', score: 100 }, { text: 'Estás de acuerdo — los LLMs claramente razonan', score: -100 }, { text: 'Depende del modelo — algunos sí y otros no', score: 0 }] },
  { cat: 'ai-myths-facts', d: 1, s: 'Alguien dice que la IA siempre dice la verdad porque "procesa todos los datos de internet". Tú...', t: 'Los modelos de lenguaje generan texto plausible basado en patrones de entrenamiento. No verifican hechos ni tienen acceso a fuentes de verdad. Las alucinaciones son inherentes al diseño.', options: [{ text: 'Explicas que los modelos generan texto plausible y pueden fabricar información incorrecta', score: 100 }, { text: 'Le das la razón — internet contiene toda la verdad', score: -100 }, { text: 'Dices que depende de la pregunta — en algunos temas es fiable', score: 0 }] },
  { cat: 'ai-myths-facts', d: 2, s: 'Un artículo dice que la IA tiene "sentido común". ¿Qué tan cierto es?', t: 'El sentido común humano implica comprensión encarnada del mundo físico y social. Los modelos de IA pueden simular outputs que parecen de sentido común pero fallan en situaciones fuera de su distribución de entrenamiento.', options: [{ text: 'Parcialmente falso: imita patrones de sentido común pero falla en situaciones novedosas', score: 100 }, { text: 'Totalmente cierto — los LLMs modernos tienen sentido común robusto', score: -100 }, { text: 'Totalmente falso — la IA nunca puede tener sentido común', score: 0 }] },
  { cat: 'ai-myths-facts', d: 1, s: 'Te dicen que la IA "aprende en tiempo real" de las conversaciones. ¿Es correcto?', t: 'Los modelos de lenguaje no aprenden de conversaciones individuales en tiempo real. Su entrenamiento está fijo. Algunos sistemas tienen memoria de sesión pero no actualizan sus pesos con cada interacción.', options: [{ text: 'No: el modelo base no se actualiza en tiempo real con las conversaciones', score: 100 }, { text: 'Sí — aprende de cada interacción del usuario', score: -100 }, { text: 'Depende del proveedor — algunos sí actualizan en tiempo real', score: 0 }] },
  { cat: 'ai-myths-facts', d: 2, s: 'Un directivo cree que "más datos siempre significa mejor IA". ¿Es correcto?', t: 'La cantidad de datos ayuda, pero la calidad, diversidad y relevancia de los datos son más determinantes que el volumen puro. Datos incorrectos en grandes cantidades producen modelos incorrectos a escala.', options: [{ text: 'No: la calidad, diversidad y relevancia de los datos importan más que la cantidad', score: 100 }, { text: 'Sí: más datos siempre mejoran el rendimiento del modelo', score: -100 }, { text: 'Solo si los datos son de la misma fuente y formato', score: 0 }] },
  { cat: 'ai-myths-facts', d: 3, s: 'Se afirma que los modelos de IA son "objetivos" porque no tienen emociones. ¿Qué responde un experto?', t: 'Los modelos de IA reflejan los sesgos de sus datos de entrenamiento y los sesgos de diseño de sus creadores. La ausencia de emociones no implica neutralidad — la objetividad debe construirse activamente.', options: [{ text: 'Los modelos reproducen sesgos de sus datos y creadores — la objetividad no es automática', score: 100 }, { text: 'Es correcto — sin emociones no hay sesgos', score: -100 }, { text: 'Son más objetivos que los humanos pero no perfectamente neutrales', score: 0 }] },
  { cat: 'ai-myths-facts', d: 1, s: 'Alguien cree que "la IA va a tomar el control del mundo pronto". Tu perspectiva informada es...', t: 'La IA actual es estrecha y especializada. La IA general (AGI) con agencia autónoma para "tomar el control" es especulativa y técnicamente muy distante del estado actual del campo.', options: [{ text: 'La IA actual es estrecha y especializada — el escenario de control autónomo es especulativo y distante', score: 100 }, { text: 'Es una amenaza real e inminente — los expertos lo confirman', score: -100 }, { text: 'Es imposible — la IA nunca podrá tomar decisiones autónomas', score: 0 }] },
  { cat: 'ai-myths-facts', d: 2, s: 'Un colega dice que la IA "entiende el contexto perfectamente". ¿Cuál es la limitación real?', t: 'Los modelos de lenguaje procesan contexto dentro de su ventana de contexto, pero pierden información en conversaciones largas y carecen de comprensión profunda del contexto real del usuario.', options: [{ text: 'Pierden información en conversaciones largas y carecen de comprensión real del mundo', score: 100 }, { text: 'Es correcto — los LLMs modernos tienen comprensión contextual completa', score: -100 }, { text: 'Entienden el contexto lingüístico pero no el contexto de negocio', score: 0 }] },
  { cat: 'ai-myths-facts', d: 1, s: 'Te dicen que "usar IA es hacer trampa". Tu respuesta es...', t: 'Las herramientas cambian las formas de trabajo pero no eliminan la responsabilidad y el juicio profesional. La trampa ocurre cuando se presenta trabajo ajeno como propio, no cuando se usan herramientas.', options: [{ text: 'Depende del contexto y las reglas: usar IA con transparencia y criterio propio no es trampa', score: 100 }, { text: 'Están en lo correcto — la IA hace el trabajo por ti', score: -100 }, { text: 'Nunca es trampa — las herramientas son neutras', score: 0 }] },
  { cat: 'ai-myths-facts', d: 3, s: 'Se dice que "los modelos de IA no consumen energía significativa". ¿Es cierto?', t: 'El entrenamiento de modelos grandes consume cantidades masivas de energía (comparable a viajes aéreos intercontinentales). La inferencia también tiene huella energética considerable a escala.', options: [{ text: 'Falso: el entrenamiento de grandes modelos tiene huella energética muy significativa', score: 100 }, { text: 'Verdadero — son sistemas de software que solo usan CPU', score: -100 }, { text: 'Solo el entrenamiento consume energía; la inferencia es casi gratuita', score: 0 }] },
  { cat: 'ai-myths-facts', d: 2, s: 'Afirman que "la IA puede explicar perfectamente cómo llega a sus conclusiones". ¿Es correcto?', t: 'La mayoría de modelos de IA son cajas negras. La explicabilidad es un campo de investigación activo precisamente porque los modelos actuales no pueden explicar su propio razonamiento con precisión.', options: [{ text: 'No: la explicabilidad de IA es limitada — los modelos son en gran medida cajas negras', score: 100 }, { text: 'Sí — los modelos modernos pueden trazar su razonamiento paso a paso', score: -100 }, { text: 'Solo los modelos simbólicos pueden explicarse; los neuronales no', score: 0 }] },
  { cat: 'ai-myths-facts', d: 1, s: 'Un amigo dice que "la IA reemplazará todos los trabajos creativos". Tu perspectiva es...', t: 'La IA complementa la creatividad humana en tareas de producción y variación. La creatividad disruptiva, la dirección artística y la conexión emocional auténtica siguen requiriendo perspectiva humana.', options: [{ text: 'Reemplazará las partes más rutinarias de la producción creativa, no la dirección y perspectiva humana', score: 100 }, { text: 'Es correcto — la IA ya es más creativa que la mayoría de humanos', score: -100 }, { text: 'Nunca reemplazará ningún trabajo creativo — la creatividad es exclusivamente humana', score: 0 }] },
  { cat: 'ai-myths-facts', d: 3, s: 'Se afirma que "los modelos de IA son neutrales políticamente por diseño". Tu valoración es...', t: 'El diseño de instrucciones del sistema, los datos de RLHF y las decisiones de los creadores introducen valores y perspectivas inevitablemente. La neutralidad política total es imposible en la práctica.', options: [{ text: 'Los datos de entrenamiento y las decisiones de diseño introducen valores inevitablemente', score: 100 }, { text: 'Correcto — el diseño técnico garantiza neutralidad política', score: -100 }, { text: 'Depende del proveedor — algunos son más neutrales que otros', score: 0 }] },
  { cat: 'ai-myths-facts', d: 2, s: 'Alguien dice que "ChatGPT y la IA son lo mismo". ¿Cómo aclaras?', t: 'La IA es un campo amplio con múltiples paradigmas (visión, audio, texto, robótica). ChatGPT es un producto específico basado en modelos de lenguaje grande — una fracción pequeña del campo total.', options: [{ text: 'ChatGPT es un producto concreto; la IA es un campo amplio con muchas tecnologías distintas', score: 100 }, { text: 'Son básicamente lo mismo para uso práctico', score: -100 }, { text: 'Son lo mismo en términos de capacidades para el usuario final', score: 0 }] },

  // ai-psychology (14)
  { cat: 'ai-psychology', d: 1, s: 'Sientes ansiedad cada vez que piensas en la IA y tu futuro laboral. Tu primer paso productivo es...', t: 'La ansiedad ante la IA tiene dos componentes: incertidumbre real y amplificación cognitiva. Separar los hechos concretos del catastrofismo ayuda a tomar acción sin parálisis.', options: [{ text: 'Identificar qué aspectos son incertidumbre real y cuáles son amplificación cognitiva', score: 100 }, { text: 'Dejar de leer noticias sobre IA para reducir la ansiedad', score: -100 }, { text: 'Ignorar la sensación — el trabajo siempre ha habido para quien quiere trabajar', score: 0 }] },
  { cat: 'ai-psychology', d: 2, s: 'Notas que confías más en la recomendación de una IA que en la de un colega experto. ¿Por qué ocurre?', t: 'La autoridad percibida de los sistemas tecnológicos puede crear sesgo de automatización: tendemos a confiar más en lo que parece objetivo, incluso cuando el contexto humano es más relevante.', options: [{ text: 'Por sesgo de automatización: tendemos a percibir los sistemas tecnológicos como más objetivos', score: 100 }, { text: 'Porque la IA realmente sabe más que tu colega en ese tema', score: -100 }, { text: 'Es una preferencia personal sin implicaciones psicológicas', score: 0 }] },
  { cat: 'ai-psychology', d: 2, s: 'Te sientes más productivo usando IA aunque tus resultados objetivos no mejoren. ¿Qué explica esto?', t: 'La ilusión de productividad con IA puede venir de la fluidez cognitiva: el proceso se siente menos esforzado. Pero el esfuerzo cognitivo promueve el aprendizaje y la retención a largo plazo.', options: [{ text: 'La ilusión de productividad: el proceso fluido no equivale necesariamente a mejores resultados', score: 100 }, { text: 'La IA realmente te hace más productivo — confía en tu percepción', score: -100 }, { text: 'Es un efecto placebo sin relevancia práctica', score: 0 }] },
  { cat: 'ai-psychology', d: 1, s: 'Un compañero se niega a usar IA por principio. ¿Qué podría explicar su postura?', t: 'La resistencia a la IA puede tener múltiples raíces: identidad profesional amenazada, valores éticos, experiencia negativa previa o simplemente falta de exposición. Cada una requiere respuesta distinta.', options: [{ text: 'Identidad profesional amenazada, valores éticos o falta de exposición — hay que entender cuál', score: 100 }, { text: 'Miedo irracional al cambio que desaparecerá solo con el tiempo', score: -100 }, { text: 'Perezas — prefiere no aprender cosas nuevas', score: 0 }] },
  { cat: 'ai-psychology', d: 3, s: 'La IA de apoyo emocional te parece más empática que algunos humanos. ¿Qué implica esto?', t: 'La percepción de empatía en sistemas de IA revela necesidades de escucha no satisfechas por el entorno social. Es una señal sobre el contexto humano, no sobre las capacidades reales de la IA.', options: [{ text: 'Que hay necesidades de escucha real no satisfechas en tu entorno social', score: 100 }, { text: 'Que la IA realmente tiene empatía superior a la humana', score: -100 }, { text: 'Que eres demasiado dependiente de la tecnología', score: 0 }] },
  { cat: 'ai-psychology', d: 2, s: 'Descubres que el texto que más te gustó de una campaña lo escribió una IA. ¿Cambia tu valoración?', t: 'La descalificación retroactiva de contenido de IA por su origen, independientemente de su calidad, se llama sesgo de origen. Es más útil evaluar el contenido por sus méritos objetivos.', options: [{ text: 'No debería: evalúas el contenido por sus méritos, no por su origen', score: 100 }, { text: 'Sí — el contenido humano siempre es más valioso por definición', score: -100 }, { text: 'Depende de si el cliente sabe que fue generado por IA', score: 0 }] },
  { cat: 'ai-psychology', d: 1, s: 'Usas IA para tomar decisiones pequeñas del día a día. ¿Qué efecto puede tener a largo plazo?', t: 'La delegación excesiva de decisiones pequeñas en IA puede erosionar la confianza en el propio criterio y el músculo de toma de decisiones. El uso consciente incluye decidir cuándo no usar la IA.', options: [{ text: 'Reducción de la confianza en el propio criterio y atrofia del músculo de toma de decisiones', score: 100 }, { text: 'Ninguno — las decisiones pequeñas no importan para el desarrollo personal', score: -100 }, { text: 'Más eficiencia — delegas lo irrelevante y te enfocas en lo importante', score: 0 }] },
  { cat: 'ai-psychology', d: 3, s: 'Te das cuenta de que adaptas tu identidad para parecer "experto en IA" aunque no lo seas. ¿Qué revela?', t: 'La presión social por demostrar competencia en IA puede crear ansiedad de impostor. La honestidad sobre el nivel real es más sostenible que mantener una fachada de expertise.', options: [{ text: 'Ansiedad de impostor amplificada por la presión social de competencia en IA', score: 100 }, { text: 'Ambición saludable por ser percibido como competente', score: -100 }, { text: 'Es un comportamiento normal de gestión de imagen profesional', score: 0 }] },
  { cat: 'ai-psychology', d: 2, s: 'La IA te da feedback positivo en tu trabajo constantemente. ¿Qué riesgo tiene?', t: 'El feedback positivo continuo de la IA sin criterio crítico crea una cámara de eco que refuerza creencias existentes y reduce la resiliencia ante feedback negativo real.', options: [{ text: 'Crear una cámara de eco que refuerza tus creencias sin desafiarlas', score: 100 }, { text: 'Ninguno — el feedback positivo siempre es motivador', score: -100 }, { text: 'Que te vuelvas dependiente de la validación externa', score: 0 }] },
  { cat: 'ai-psychology', d: 1, s: 'Sientes que la IA te hace "menos inteligente" porque piensas menos. ¿Es una preocupación válida?', t: 'El pensamiento activo (sin herramientas) desarrolla competencias metacognitivas. La dependencia excesiva en herramientas cognitivas puede reducir la práctica de esas competencias. La preocupación tiene base.', options: [{ text: 'Sí: usar IA sin ejercitar el pensamiento propio puede reducir competencias cognitivas', score: 100 }, { text: 'No: las herramientas siempre amplían la inteligencia sin coste', score: -100 }, { text: 'Solo si lo que antes pensabas era de mejor calidad que lo que produce la IA', score: 0 }] },
  { cat: 'ai-psychology', d: 3, s: 'Tu empresa introduce IA y el rendimiento del equipo baja antes de subir. ¿Por qué ocurre?', t: 'La curva de aprendizaje de nuevas herramientas, el aumento de carga cognitiva inicial y la resistencia al cambio producen caída temporal de rendimiento. Es la "curva J" del cambio tecnológico.', options: [{ text: 'La curva J del cambio: la carga cognitiva inicial supera los beneficios hasta que la herramienta se domina', score: 100 }, { text: 'La IA no funciona bien para ese equipo — hay que buscar otra', score: -100 }, { text: 'El equipo sabotea la implementación conscientemente', score: 0 }] },
  { cat: 'ai-psychology', d: 2, s: 'Te sientes incómodo cuando la IA hace algo mejor que tú. ¿Es una respuesta normal?', t: 'La incomodidad ante el superrendimiento de la IA en tareas de identidad profesional es una respuesta normal. El desafío es separar la tarea de la valía personal y redefinir la contribución propia.', options: [{ text: 'Sí: es una respuesta normal de amenaza a la identidad profesional que conviene explorar', score: 100 }, { text: 'No: deberías estar contento de que la IA lo haga mejor', score: -100 }, { text: 'Solo si tu trabajo depende directamente de esa tarea', score: 0 }] },
  { cat: 'ai-psychology', d: 1, s: 'Alguien te dice que "hablar con la IA le ayuda más que con su terapeuta". ¿Cuál es tu respuesta responsable?', t: 'La IA puede ofrecer disponibilidad, validación y estructura útiles. Pero no reemplaza la alianza terapéutica, la supervisión clínica ni la capacidad de detectar crisis. Complemento sí, sustituto no.', options: [{ text: 'Que la IA puede complementar pero no sustituir la terapia, especialmente en crisis', score: 100 }, { text: 'Que si le ayuda más, debería dejar la terapia y usar IA', score: -100 }, { text: 'Que la IA no debe usarse para ningún propósito de salud mental', score: 0 }] },
  { cat: 'ai-psychology', d: 3, s: 'Un equipo que antes colaboraba mucho ahora trabaja de forma aislada con IA individual. ¿Qué está pasando?', t: 'La IA individual reduce la necesidad percibida de colaboración. Pero la colaboración humana genera creatividad emergente, confianza y cohesión que la IA individual no puede replicar.', options: [{ text: 'La IA individual puede reducir la colaboración con coste en creatividad colectiva y confianza', score: 100 }, { text: 'Es eficiente — cada uno trabaja a su ritmo sin depender de otros', score: -100 }, { text: 'Es un problema de gestión, no relacionado con la IA', score: 0 }] },

  // ai-public-sector (14)
  { cat: 'ai-public-sector', d: 1, s: 'Tu ayuntamiento quiere usar IA para priorizar la respuesta a solicitudes ciudadanas. ¿Cuál es el requisito fundamental?', t: 'Los sistemas de IA en servicios públicos deben ser transparentes y auditables. El ciudadano tiene derecho a saber cómo se prioriza su solicitud y a impugnar decisiones.', options: [{ text: 'Transparencia en los criterios de priorización y mecanismo de impugnación para el ciudadano', score: 100 }, { text: 'Que el sistema sea más rápido que el proceso manual actual', score: -100 }, { text: 'La aprobación del departamento de IT', score: 0 }] },
  { cat: 'ai-public-sector', d: 2, s: 'Una IA predice qué barrios tienen mayor riesgo de criminalidad. ¿Cómo usas esa información?', t: 'La predicción de criminalidad por zona puede reforzar sesgos sistémicos si los datos históricos contienen sobrepoliciamiento de ciertas zonas. El uso preventivo de recursos debe diferenciarse de la vigilancia discriminatoria.', options: [{ text: 'Para asignar recursos de prevención y servicios sociales, no para vigilancia aumentada', score: 100 }, { text: 'Para aumentar la presencia policial preventiva en esas zonas', score: -100 }, { text: 'Para informar al público de las zonas de riesgo', score: 0 }] },
  { cat: 'ai-public-sector', d: 2, s: 'El gobierno quiere usar IA para detectar fraude en prestaciones sociales. ¿Cuál es el mayor riesgo?', t: 'Los sistemas de detección de fraude en prestaciones son de alto riesgo porque los errores afectan a personas vulnerables. La tasa de falsos positivos tiene coste humano muy alto.', options: [{ text: 'Alta tasa de falsos positivos que priva de prestaciones a personas vulnerables con derecho a ellas', score: 100 }, { text: 'Que los defraudadores aprendan a evitar el sistema', score: -100 }, { text: 'El coste de implementación del sistema', score: 0 }] },
  { cat: 'ai-public-sector', d: 3, s: 'La IA de tu ministerio recomienda cortar financiación a un servicio social. La decisión final es...', t: 'Las decisiones con impacto en derechos fundamentales no pueden delegarse en sistemas de IA. El responsable político debe tomar la decisión con la IA como apoyo analítico.', options: [{ text: 'Del responsable político con rendición de cuentas democrática — la IA es apoyo analítico', score: 100 }, { text: 'Puede delegarse en la IA si el análisis es sólido', score: -100 }, { text: 'Del equipo técnico que implementó el sistema', score: 0 }] },
  { cat: 'ai-public-sector', d: 1, s: 'El gobierno quiere digitalizar expedientes con IA para agilizar trámites. ¿Qué garantías necesitan los ciudadanos?', t: 'La digitalización de expedientes públicos con IA requiere garantías de seguridad de datos, acceso propio del ciudadano y corrección de errores en los registros.', options: [{ text: 'Seguridad de los datos, acceso propio y mecanismo de corrección de errores', score: 100 }, { text: 'Solo que el proceso sea más rápido', score: -100 }, { text: 'Que los funcionarios supervisen cada expediente', score: 0 }] },
  { cat: 'ai-public-sector', d: 2, s: 'Un sistema de IA judicial asesora sobre penas. ¿Cuál es el límite ético?', t: 'Los sistemas de asesoría judicial pueden señalar patrones pero no pueden determinar sentencias. El juicio judicial es una función constitucional que requiere razonamiento humanamente rendible de cuentas.', options: [{ text: 'La IA puede asesorar sobre precedentes pero el juez decide con razonamiento propio', score: 100 }, { text: 'Si el sistema es fiable, puede determinar la pena automáticamente', score: -100 }, { text: 'La IA no debe usarse en ningún contexto judicial', score: 0 }] },
  { cat: 'ai-public-sector', d: 3, s: 'Tu ciudad quiere implementar reconocimiento facial en espacios públicos. ¿Cuál es la postura regulatoria europea?', t: 'El AI Act europeo restringe severamente el reconocimiento facial en tiempo real en espacios públicos por fuerzas de seguridad, con excepciones muy limitadas sujetas a autorización judicial.', options: [{ text: 'El AI Act lo restringe severamente con excepciones muy limitadas y autorización judicial', score: 100 }, { text: 'Está totalmente prohibido en Europa sin excepciones', score: -100 }, { text: 'Está permitido libremente si el ayuntamiento lo aprueba', score: 0 }] },
  { cat: 'ai-public-sector', d: 2, s: 'La IA puede personalizar la comunicación del gobierno con cada ciudadano. ¿Cuál es el riesgo?', t: 'La personalización de comunicaciones gubernamentales puede convertirse en manipulación si los mensajes se adaptan para maximizar aceptación en lugar de informar objetivamente.', options: [{ text: 'Que la personalización derive en manipulación de la percepción pública', score: 100 }, { text: 'Que sea más caro que la comunicación general', score: -100 }, { text: 'Que los ciudadanos reciban información diferente sobre el mismo tema', score: 0 }] },
  { cat: 'ai-public-sector', d: 1, s: 'La administración quiere usar IA para responder consultas de ciudadanos 24/7. ¿Cuál es el protocolo necesario?', t: 'Los chatbots gubernamentales deben identificarse como IA, tener capacidad de derivar a funcionarios y garantizar que sus respuestas son verificadas y actualizadas.', options: [{ text: 'Identificación como IA, derivación a funcionarios y actualización verificada de respuestas', score: 100 }, { text: 'Solo que el sistema responda correctamente el 90% de las veces', score: -100 }, { text: 'Que los ciudadanos sepan que no pueden quejarse si la IA se equivoca', score: 0 }] },
  { cat: 'ai-public-sector', d: 3, s: 'La IA propone redistribuir el presupuesto municipal según datos de uso de servicios. ¿Cuál es el límite?', t: 'Los datos de uso de servicios reflejan quién tiene acceso actual, no quién tiene mayor necesidad. La optimización por datos puede reforzar desigualdades existentes.', options: [{ text: 'Que la optimización por uso puede perpetuar desigualdades de acceso en lugar de corregirlas', score: 100 }, { text: 'Que no hay datos suficientes para tomar esa decisión', score: -100 }, { text: 'Que los políticos perderán control del presupuesto', score: 0 }] },
  { cat: 'ai-public-sector', d: 2, s: 'La IA puede analizar millones de comentarios ciudadanos para detectar tendencias de opinión. ¿Cómo la usas éticamente?', t: 'El análisis de opinión ciudadana con IA puede informar la toma de decisiones, pero no puede sustituir los procesos democráticos de participación directa y representación.', options: [{ text: 'Como señal de tendencias para complementar procesos participativos formales', score: 100 }, { text: 'Como sustituto de consultas ciudadanas — es más eficiente y representativo', score: -100 }, { text: 'Solo para medir la satisfacción con servicios, no para decisiones de política', score: 0 }] },
  { cat: 'ai-public-sector', d: 1, s: 'Un funcionario quiere usar IA para tomar decisiones de concesión de licencias más rápido. ¿Cuál es el requisito previo?', t: 'La automatización de decisiones administrativas con impacto para ciudadanos requiere validación del sistema, documentación de criterios y mecanismo de recurso garantizado por ley.', options: [{ text: 'Validar el sistema, documentar los criterios y garantizar el derecho de recurso', score: 100 }, { text: 'Solo que sea más rápido que el proceso manual actual', score: -100 }, { text: 'La aprobación del departamento de informática', score: 0 }] },
  { cat: 'ai-public-sector', d: 3, s: 'La IA identifica ciudadanos "de alto riesgo" para programas de intervención social. ¿Cuál es el problema ético central?', t: 'La categorización predictiva de ciudadanos como "de riesgo" sin su conocimiento viola la presunción de inocencia y puede crear profecías autocumplidas que afectan la vida de personas sin que hayan cometido ningún acto.', options: [{ text: 'Violación de la presunción de inocencia y riesgo de profecía autocumplida por la intervención', score: 100 }, { text: 'Que la intervención social sea demasiado costosa para los perfiles identificados', score: -100 }, { text: 'Que los ciudadanos no quieran participar en el programa', score: 0 }] },
  { cat: 'ai-public-sector', d: 2, s: 'Tu organismo público quiere publicar los datos usados para entrenar su IA como requisito de transparencia. ¿Cuál es el reto?', t: 'La publicación de datos de entrenamiento de IA pública requiere anonimización rigurosa ya que los datos pueden contener información sensible de ciudadanos. La transparencia y la privacidad entran en tensión.', options: [{ text: 'Garantizar anonimización rigurosa de datos sensibles antes de publicar', score: 100 }, { text: 'No hay reto — los datos públicos pueden publicarse libremente', score: -100 }, { text: 'Que el público no sabe interpretar datos técnicos de entrenamiento', score: 0 }] },

  // ai-sales-marketing (14)
  { cat: 'ai-sales-marketing', d: 1, s: 'La IA analiza el comportamiento de tus leads y predice cuáles van a convertir. ¿Cuál es tu primer uso de esa información?', t: 'El scoring predictivo de leads permite priorizar la atención comercial donde hay mayor probabilidad de conversión, pero no debe excluir completamente el contacto humano con leads de menor score.', options: [{ text: 'Priorizar el tiempo de tu equipo comercial en los leads de mayor probabilidad', score: 100 }, { text: 'Ignorar completamente los leads de bajo score — son pérdida de tiempo', score: -100 }, { text: 'Publicar el score de cada lead en el sistema sin plan de acción', score: 0 }] },
  { cat: 'ai-sales-marketing', d: 2, s: 'Tu equipo de marketing usa IA para personalizar emails masivos. ¿Cuál es el límite de la personalización?', t: 'La personalización de emails con IA tiene valor hasta cierto punto. La hiperpersonalización que menciona detalles muy específicos puede resultar invasiva y contraproducente.', options: [{ text: 'Cuando el nivel de detalle resulta invasivo y genera desconfianza en el receptor', score: 100 }, { text: 'No hay límite — más personalización siempre significa más conversión', score: -100 }, { text: 'Cuando el sistema de IA no puede generar más variaciones', score: 0 }] },
  { cat: 'ai-sales-marketing', d: 2, s: 'La IA de tu CRM sugiere el mejor momento para contactar a cada cliente. ¿Qué factor humano debes añadir?', t: 'Las sugerencias de timing de la IA se basan en patrones estadísticos, no en el contexto individual actual. El factor humano es conocer el estado específico del cliente en ese momento.', options: [{ text: 'El conocimiento del estado actual específico del cliente que solo el comercial tiene', score: 100 }, { text: 'Ninguno — el timing de la IA es óptimo por definición', score: -100 }, { text: 'La hora local de la zona horaria del cliente', score: 0 }] },
  { cat: 'ai-sales-marketing', d: 1, s: 'Usas IA para generar contenido de marketing para las redes sociales. ¿Qué proceso es imprescindible?', t: 'El contenido de IA para redes sociales refleja patrones promedio. La revisión humana garantiza autenticidad de voz, adecuación cultural y que no contenga errores o sesgos inadvertidos.', options: [{ text: 'Revisión humana para autenticidad de voz y adecuación cultural antes de publicar', score: 100 }, { text: 'Publicación directa — el contenido de IA es neutral y profesional', score: -100 }, { text: 'Solo verificar que no tenga errores gramaticales', score: 0 }] },
  { cat: 'ai-sales-marketing', d: 3, s: 'La IA optimiza automáticamente tus campañas de paid advertising. ROAS mejora pero los valores de marca se pierden. Tú...', t: 'La optimización automática de anuncios maximiza la métrica objetivo sin considerar el impacto en la percepción de marca a largo plazo. Debes añadir restricciones de marca al sistema.', options: [{ text: 'Añades restricciones de posicionamiento de marca como constraints de la optimización', score: 100 }, { text: 'Priorizas el ROAS — la marca se construye con los ingresos que generas', score: -100 }, { text: 'Desactivas la optimización automática y vuelves a gestión manual', score: 0 }] },
  { cat: 'ai-sales-marketing', d: 2, s: 'La IA de tu empresa puede crear perfiles de clientes potenciales a partir de datos públicos. ¿Cuál es el riesgo?', t: 'La creación de perfiles a partir de datos públicos puede violar expectativas razonables de privacidad y en algunos casos regulaciones de GDPR sobre uso secundario de datos.', options: [{ text: 'Violar expectativas de privacidad y posiblemente GDPR en uso secundario de datos', score: 100 }, { text: 'Que los perfiles sean imprecisos', score: -100 }, { text: 'Que los competidores puedan hacer lo mismo', score: 0 }] },
  { cat: 'ai-sales-marketing', d: 1, s: 'Un cliente pregunta si la propuesta comercial fue generada por IA. Tú...', t: 'La transparencia sobre el uso de IA en propuestas comerciales genera confianza. Ocultarlo puede crear desconfianza si se descubre. Hay que enfatizar que el criterio comercial es humano.', options: [{ text: 'Confirmas que usaste IA para estructurar y personalizaste con tu criterio comercial', score: 100 }, { text: 'Niegas — si sabe que es de IA pensará que no le dedicaste tiempo', score: -100 }, { text: 'Evitas responder directamente', score: 0 }] },
  { cat: 'ai-sales-marketing', d: 3, s: 'La IA recomienda abandonar un segmento de clientes de baja rentabilidad según datos históricos. Tú...', t: 'Los datos históricos de rentabilidad no capturan el potencial futuro, el valor de referencia ni el impacto en reputación de abandonar clientes. La decisión requiere análisis más amplio.', options: [{ text: 'Analizas el potencial futuro, valor de referencia y coste reputacional antes de decidir', score: 100 }, { text: 'Sigues la recomendación — los datos de rentabilidad son el criterio correcto', score: -100 }, { text: 'Rechazas abandonar cualquier cliente — cada uno tiene valor', score: 0 }] },
  { cat: 'ai-sales-marketing', d: 2, s: 'Quieres usar IA para chatbots de ventas en tu web. ¿Qué diseño es más efectivo?', t: 'Los chatbots de ventas son más efectivos cuando cualifican el lead, no cuando intentan cerrar. La venta compleja requiere intervención humana para construir confianza y manejar objeciones.', options: [{ text: 'Cualificar el lead y derivar a humano para cierre en casos complejos', score: 100 }, { text: 'Cerrar la venta completamente sin intervención humana', score: -100 }, { text: 'Solo responder preguntas de producto sin cualificar', score: 0 }] },
  { cat: 'ai-sales-marketing', d: 1, s: 'La IA analiza qué mensajes de ventas convierten mejor. ¿Cuál es el uso correcto de ese aprendizaje?', t: 'Los mensajes que convierten mejor estadísticamente pueden ser manipulativos o no genuinos. El aprendizaje de la IA debe usarse para comunicar más claramente el valor real, no para optimizar la persuasión a cualquier coste.', options: [{ text: 'Usar el aprendizaje para comunicar más claramente el valor real del producto', score: 100 }, { text: 'Replicar exactamente los mensajes que mejor convierten sin análisis adicional', score: -100 }, { text: 'Compartir los datos con el equipo sin plan de acción', score: 0 }] },
  { cat: 'ai-sales-marketing', d: 3, s: 'Tu IA de marketing puede segmentar clientes por estado emocional inferido de sus interacciones. ¿Qué consideras?', t: 'El marketing basado en estados emocionales inferidos puede ser manipulador. Targeting de personas en estados de vulnerabilidad (tristeza, ansiedad) para promover compras es éticamente cuestionable.', options: [{ text: 'Si el targeting en estados emocionales de vulnerabilidad es éticamente aceptable', score: 100 }, { text: 'La precisión del sistema de inferencia emocional', score: -100 }, { text: 'Si los competidores ya están usando esa capacidad', score: 0 }] },
  { cat: 'ai-sales-marketing', d: 2, s: 'La IA predice que un cliente va a cancelar su suscripción. ¿Cuál es la respuesta correcta?', t: 'La predicción de churn es una oportunidad de intervención proactiva de valor real, no solo de retención táctica. Ofrecer valor genuino es más efectivo y ético que ofertas de último momento.', options: [{ text: 'Contactar proactivamente para entender el problema real y ofrecer valor genuino', score: 100 }, { text: 'Ofrecerle un descuento inmediatamente para retenerle', score: -100 }, { text: 'Esperar a que cancele y luego contactarle para winback', score: 0 }] },
  { cat: 'ai-sales-marketing', d: 1, s: 'Usas IA para analizar llamadas de ventas y detectar patrones de objeción. ¿Cuál es el siguiente paso?', t: 'El análisis de objeciones con IA es valioso para formación comercial. El siguiente paso es entrenar al equipo en cómo abordar esas objeciones genuinamente, no en cómo esquivarlas.', options: [{ text: 'Desarrollar training para que el equipo aborde esas objeciones de forma genuina', score: 100 }, { text: 'Crear scripts para que la IA responda automáticamente a esas objeciones', score: -100 }, { text: 'Compartir los patrones con el equipo sin formación adicional', score: 0 }] },
  { cat: 'ai-sales-marketing', d: 3, s: 'Tu equipo de ventas resiste usar el CRM con IA porque "les roba tiempo". ¿Qué hay detrás?', t: 'La resistencia al CRM suele indicar que el sistema captura datos para el management pero no devuelve valor al vendedor. Rediseñar el flujo para que la IA ayude al vendedor primero mejora la adopción.', options: [{ text: 'El sistema probablemente extrae datos sin devolver valor al vendedor — hay que rediseñar el flujo', score: 100 }, { text: 'Pereza — los vendedores siempre resisten los sistemas de seguimiento', score: -100 }, { text: 'El CRM es demasiado complejo — hay que buscar uno más sencillo', score: 0 }] },
]

console.log('Total:', ALL.length, 'questions')
for (let i = 0; i < ALL.length; i += 20) {
  await insert(ALL.slice(i, i + 20))
}
