const TOKEN = 'sbp_f314cf27b5b2a01eea48048a7b1c015cc9cf4b42'
const API = 'https://api.supabase.com/v1/projects/amhfxaqolholacanqyas/database/query'
function esc(s) { return s.replace(/'/g, "''") }
async function insert(batch) {
  const values = batch.map(q => {
    const opts = JSON.stringify(q.options).replace(/'/g, "''")
    return `('es','${q.cat}','${esc(q.s)}','${esc(q.t)}','${opts}'::jsonb,${q.d},'claude',true)`
  }).join(',')
  const sql = `INSERT INTO questions (locale,category,scenario_text,mindset_tip,options,difficulty,generated_by,is_active) VALUES ${values};`
  const r = await fetch(API, {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${TOKEN}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query: sql })
  })
  const d = await r.json()
  if (d.message) { console.error('ERR:', d.message); return false }
  console.log('OK:', batch.length, 'inserted')
  return true
}

const ALL = [
  // ai-education (14)
  { cat: 'ai-education', d: 1, s: 'Un estudiante usa IA para escribir su ensayo completo. Como docente, tus respuestas posibles son...', t: 'La IA como herramienta de aprendizaje y la IA como sustituto del aprendizaje son usos radicalmente distintos. El diseño pedagógico debe distinguirlos.', options: [{ text: 'Rediseñar la tarea para que la IA sea una herramienta de proceso, no de resultado final', score: 100 }, { text: 'Prohibir la IA en todos los trabajos escritos', score: -100 }, { text: 'Aceptar el ensayo — si la IA lo hace bien, el estudiante también aprende algo', score: 0 }] },
  { cat: 'ai-education', d: 2, s: 'Una escuela quiere usar IA para personalizar el ritmo de aprendizaje de cada alumno. ¿Cuál es el mayor reto?', t: 'La personalización por IA requiere datos de aprendizaje de calidad y un modelo pedagógico claro. Sin ellos, la IA optimiza métricas equivocadas.', options: [{ text: 'Definir qué métricas de aprendizaje realmente importan más allá de la velocidad', score: 100 }, { text: 'El coste de las licencias de la plataforma', score: -100 }, { text: 'La resistencia de los padres a la tecnología', score: 0 }] },
  { cat: 'ai-education', d: 2, s: 'La IA puede detectar cuándo un estudiante está perdido en tiempo real. ¿Cómo lo usas éticamente?', t: 'Los sistemas de detección de dificultad deben usarse para ayudar, no para etiquetar. La privacidad y el consentimiento son prerequisitos.', options: [{ text: 'Para intervenir pedagógicamente de inmediato con el consentimiento del estudiante', score: 100 }, { text: 'Para alertar automáticamente a los padres de cada dificultad detectada', score: -100 }, { text: 'Para agruparlo con otros estudiantes de nivel similar sin consultarle', score: 0 }] },
  { cat: 'ai-education', d: 1, s: 'Usas IA para preparar tus clases. ¿Cuál es el mayor beneficio?', t: 'La IA reduce el tiempo de preparación de materiales, liberando al docente para lo que más importa: la relación y el acompañamiento.', options: [{ text: 'Tener más tiempo para interacción real con los estudiantes', score: 100 }, { text: 'Que la IA reemplaza la necesidad de preparar clases', score: -100 }, { text: 'Generar más contenido aunque no tengas tiempo de revisarlo', score: 0 }] },
  { cat: 'ai-education', d: 3, s: 'Un sistema de IA propone suspender a un alumno basándose en sus datos de comportamiento. Tú...', t: 'Las decisiones disciplinarias con consecuencias para el alumno no pueden delegarse a la IA. Requieren juicio humano y proceso garantista.', options: [{ text: 'Tratas la IA como señal de alerta y aplicas proceso humano completo de evaluación', score: 100 }, { text: 'Confías en el sistema — está entrenado con miles de casos', score: -100 }, { text: 'Pides una segunda opinión de otro sistema de IA', score: 0 }] },
  { cat: 'ai-education', d: 2, s: 'Quieres que tus alumnos aprendan a usar IA críticamente. ¿Qué ejercicio diseñas?', t: 'El pensamiento crítico sobre IA se entrena comparando, cuestionando y verificando outputs. La evaluación pasiva no desarrolla esa competencia.', options: [{ text: 'Pides que generen una respuesta de IA y luego argumenten qué está bien, mal o falta', score: 100 }, { text: 'Prohíbes la IA para que aprendan sin muletas', score: -100 }, { text: 'Les muestras ejemplos de errores de IA pero sin que ellos interactúen', score: 0 }] },
  { cat: 'ai-education', d: 1, s: 'Un alumno dice que no necesita aprender a escribir porque la IA lo hace por él. Tu respuesta...', t: 'Escribir es pensar. La competencia de articular ideas con claridad no la reemplaza ninguna herramienta — la potencia.', options: [{ text: 'Le explicas que escribir entrena el pensamiento que luego la IA no puede suplir', score: 100 }, { text: 'Le dices que tiene razón — la escritura ya no es una habilidad esencial', score: -100 }, { text: 'Le pones una mala nota sin explicar por qué importa aprender', score: 0 }] },
  { cat: 'ai-education', d: 3, s: 'La IA de corrección automática da notas inconsistentes según el idioma del alumno. Tú...', t: 'Los sesgos lingüísticos en sistemas de evaluación automática son discriminatorios. No pueden usarse como sustituto de la evaluación humana.', options: [{ text: 'Suspendes su uso para evaluación oficial hasta corregir el sesgo', score: 100 }, { text: 'La usas solo para idioma mayoritario — funciona bien ahí', score: -100 }, { text: 'La mantienes como complemento sin informar del sesgo a los alumnos', score: 0 }] },
  { cat: 'ai-education', d: 2, s: 'Tu institución quiere reducir costes usando IA para sustituir tutorías de bajo rendimiento. Tú...', t: 'Las tutorías tienen un componente relacional que la IA no replica. Reducir costes eliminando contacto humano puede aumentar el abandono.', options: [{ text: 'Propones usar IA para preparar las tutorías, no para reemplazarlas', score: 100 }, { text: 'Apoyas el recorte — la IA puede hacer lo mismo más barato', score: -100 }, { text: 'Te opones sin proponer alternativa de eficiencia', score: 0 }] },
  { cat: 'ai-education', d: 1, s: 'Quieres usar IA para generar ejercicios personalizados para cada alumno. ¿Qué necesitas primero?', t: 'La personalización requiere diagnóstico previo. Sin saber dónde está cada alumno, la IA genera contenido genérico que llama "personalizado".', options: [{ text: 'Un diagnóstico claro del nivel y lagunas de cada alumno', score: 100 }, { text: 'La herramienta de IA más avanzada del mercado', score: -100 }, { text: 'El permiso del centro educativo', score: 0 }] },
  { cat: 'ai-education', d: 3, s: 'Una startup promete que su IA aumenta las notas medias un 20%. Tú...', t: 'Las afirmaciones de mejora de rendimiento de herramientas educativas requieren metodología rigurosa. La correlación no es causalidad.', options: [{ text: 'Pides la metodología del estudio y si hay grupo de control', score: 100 }, { text: 'Pruebas la herramienta — los resultados hablan por sí solos', score: -100 }, { text: 'La rechazas directamente — las promesas de ese tipo siempre son marketing', score: 0 }] },
  { cat: 'ai-education', d: 2, s: 'Tus alumnos usan diferentes herramientas de IA. ¿Cómo gestionas la equidad en el aula?', t: 'Las herramientas de IA creadoras de asimetría de acceso reproducen desigualdades. La equidad digital debe ser parte del diseño pedagógico.', options: [{ text: 'Garantizas acceso equitativo o diseñas actividades que no dependan de herramientas premium', score: 100 }, { text: 'Cada uno usa lo que tiene — así es el mundo real', score: -100 }, { text: 'Recomiendas las herramientas gratuitas sin verificar su calidad', score: 0 }] },
  { cat: 'ai-education', d: 1, s: 'La IA ha corregido el examen de tu asignatura. Antes de publicar notas, tú...', t: 'La IA puede corregir a escala pero comete errores sistemáticos en casos ambiguos. La revisión humana de casos límite es obligatoria.', options: [{ text: 'Revisas los casos límite y las respuestas que la IA puntuó con baja confianza', score: 100 }, { text: 'Publicas directamente — la IA es más objetiva que tú', score: -100 }, { text: 'Revisas todo manualmente — no confías en la IA para esto', score: 0 }] },
  { cat: 'ai-education', d: 3, s: 'Un gobierno propone usar IA para decidir qué carrera debería estudiar cada alumno. Tú...', t: 'Las decisiones vocacionales son profundamente personales y contextuales. Delegarlas en IA sin agencia del alumno viola su autodeterminación.', options: [{ text: 'Te opones: la IA puede ser herramienta de orientación pero la decisión es del alumno', score: 100 }, { text: 'Lo apoyas — la IA conoce el mercado laboral mejor que los orientadores', score: -100 }, { text: 'Lo aceptas si los padres dan su consentimiento', score: 0 }] },

  // ai-everyday (14)
  { cat: 'ai-everyday', d: 1, s: 'Empiezas a usar un asistente de IA en casa. ¿Cuál es la expectativa más realista?', t: 'La IA doméstica es mejor para tareas rutinarias y búsqueda de información. Necesita aprendizaje progresivo de tus preferencias para funcionar bien.', options: [{ text: 'Que automatice tareas rutinarias pero requiera ajuste inicial de tus hábitos', score: 100 }, { text: 'Que entienda todo perfectamente desde el primer día', score: -100 }, { text: 'Que sea útil para todo sin ningún esfuerzo de configuración', score: 0 }] },
  { cat: 'ai-everyday', d: 1, s: 'La IA de tu móvil te sugiere una ruta más rápida pero diferente a la habitual. Tú...', t: 'Las sugerencias de IA tienen contexto limitado: no sabe tu energía, tus preferencias ni tus paradas habituales. Tú decides con esa información.', options: [{ text: 'Evalúas si la sugerencia encaja con tu situación concreta hoy', score: 100 }, { text: 'La sigues siempre — el algoritmo sabe más que tú', score: -100 }, { text: 'La ignoras siempre — prefieres tu ruta conocida', score: 0 }] },
  { cat: 'ai-everyday', d: 2, s: 'Un asistente de IA escucha tus conversaciones para personalizar sugerencias. Tu postura es...', t: 'El valor de la personalización debe evaluarse frente al coste de privacidad. Ese trade-off es una decisión personal informada, no automática.', options: [{ text: 'Leer la política de privacidad y decidir si el valor merece el trade-off', score: 100 }, { text: 'Aceptar sin leer — todos lo hacen y no pasa nada', score: -100 }, { text: 'Rechazar cualquier asistente que acceda a audio', score: 0 }] },
  { cat: 'ai-everyday', d: 1, s: 'La IA de tu banco te alerta de un gasto inusual. Tú...', t: 'Las alertas de IA financiera son señales probabilísticas, no certezas. Verificar antes de actuar evita falsos positivos costosos.', options: [{ text: 'Verificas si reconoces el gasto antes de tomar cualquier acción', score: 100 }, { text: 'Bloqueas la tarjeta inmediatamente sin verificar', score: -100 }, { text: 'Ignoras la alerta — hay demasiadas y suelen ser falsas', score: 0 }] },
  { cat: 'ai-everyday', d: 2, s: 'Tu hijo de 10 años quiere usar un chatbot de IA para hacer los deberes. Tú...', t: 'La IA como herramienta de aprendizaje activo (preguntar, explorar) es muy diferente de usarla para obtener respuestas sin esfuerzo cognitivo.', options: [{ text: 'Le enseñas a usarla para entender, no solo para copiar respuestas', score: 100 }, { text: 'Se lo prohíbes totalmente — debe aprender solo', score: -100 }, { text: 'Le dejas usarla libremente — aprenderá los límites solo', score: 0 }] },
  { cat: 'ai-everyday', d: 1, s: 'Usas IA para gestionar tu agenda personal. ¿Qué información NO deberías darle?', t: 'Los asistentes de IA con acceso a información sensible son un vector de privacidad. El principio de mínimo dato necesario aplica en el uso personal también.', options: [{ text: 'Contraseñas, datos bancarios o información médica confidencial', score: 100 }, { text: 'Tus preferencias de horario de reuniones', score: -100 }, { text: 'Los nombres de tus contactos habituales', score: 0 }] },
  { cat: 'ai-everyday', d: 2, s: 'La IA de tu plataforma de streaming te recomienda siempre lo mismo. Tú...', t: 'Los algoritmos de recomendación crean burbujas de contenido. Interrumpir el ciclo de confirmación activamente amplía tu perspectiva.', options: [{ text: 'Buscas activamente contenido fuera de tus patrones habituales para diversificar', score: 100 }, { text: 'Confías en el algoritmo — si te recomienda eso, es lo que más te gusta', score: -100 }, { text: 'No haces nada — las recomendaciones son solo sugerencias', score: 0 }] },
  { cat: 'ai-everyday', d: 3, s: 'La IA de tu médico te diagnostica sin consulta humana. Tu reacción es...', t: 'La IA médica es una herramienta de apoyo, no de diagnóstico definitivo. Las decisiones clínicas requieren validación humana cualificada.', options: [{ text: 'Pides confirmación con un médico antes de seguir cualquier recomendación', score: 100 }, { text: 'Sigues el diagnóstico de IA — es más rápido y basado en más datos', score: -100 }, { text: 'Buscas un segundo diagnóstico de otra IA', score: 0 }] },
  { cat: 'ai-everyday', d: 1, s: 'Un chatbot de IA te da información contradictoria en dos momentos del mismo día. Tú...', t: 'Los modelos de IA no tienen memoria persistente entre sesiones por defecto y pueden ser inconsistentes. Verificar en fuentes externas es la respuesta correcta.', options: [{ text: 'Verificas la información en una fuente externa fiable', score: 100 }, { text: 'Crees la última respuesta — habrá actualizado su conocimiento', score: -100 }, { text: 'Dejas de usar el chatbot — si se contradice no sirve', score: 0 }] },
  { cat: 'ai-everyday', d: 2, s: 'Usas IA para traducir mensajes en un idioma que no dominas. ¿Cuál es el mayor riesgo?', t: 'Las traducciones de IA fallan en modismos, ironía y referencias culturales. En comunicaciones importantes, una segunda verificación es prudente.', options: [{ text: 'Que modismos o ironía se traduzcan literalmente y cambien el sentido', score: 100 }, { text: 'Que la gramática sea incorrecta', score: -100 }, { text: 'Que el receptor sepa que usaste IA para traducir', score: 0 }] },
  { cat: 'ai-everyday', d: 1, s: 'La IA de tu casa baja la calefacción automáticamente porque "detecta" que no estás. Pero sí estás. Tú...', t: 'Los sistemas de automatización doméstica deben tener controles manuales accesibles. La automatización sin override humano crea dependencia y fricción.', options: [{ text: 'Corriges manualmente y revisas qué dato hizo fallar la detección', score: 100 }, { text: 'Te adaptas — el sistema aprenderá con el tiempo', score: -100 }, { text: 'Desactivas toda la automatización por frustración', score: 0 }] },
  { cat: 'ai-everyday', d: 3, s: 'Una IA de bienestar te dice que estás estresado basándose en tu voz. Tú...', t: 'La detección de estados emocionales por IA es probabilística y tiene alta tasa de error. No debe reemplazar la autoconciencia ni la consulta profesional.', options: [{ text: 'Lo tomas como señal a reflexionar, no como diagnóstico', score: 100 }, { text: 'Lo aceptas — la IA detecta patrones que tú no percibes', score: -100 }, { text: 'Lo ignoras — una máquina no puede saber cómo te sientes', score: 0 }] },
  { cat: 'ai-everyday', d: 2, s: 'Quieres reducir el tiempo que pasas en redes sociales con ayuda de IA. ¿Qué herramienta es más efectiva?', t: 'Las herramientas de control de uso que generan fricción consciente son más efectivas que los bloqueos duros que se evitan fácilmente.', options: [{ text: 'Un sistema que registra el tiempo, te muestra patrones y te pide confirmación antes de abrir apps', score: 100 }, { text: 'Un bloqueador total de redes sociales en horas de trabajo', score: -100 }, { text: 'Notificaciones que te recuerdan cuánto llevas — sin acción automática', score: 0 }] },
  { cat: 'ai-everyday', d: 1, s: 'La IA te sugiere un producto basándose en tus búsquedas. Sabes que es publicidad disfrazada. Tú...', t: 'Distinguir recomendación genuina de publicidad algorítmica es una competencia digital esencial. El escepticismo informado es la defensa correcta.', options: [{ text: 'Evalúas el producto con criterios propios independientemente de la recomendación', score: 100 }, { text: 'Lo compras — si lo recomienda es porque lo necesitas', score: -100 }, { text: 'Lo rechazas automáticamente por principio', score: 0 }] },

  // ai-finance (14)
  { cat: 'ai-finance', d: 1, s: 'Una IA te recomienda una inversión con alto rendimiento histórico. Antes de invertir, tú...', t: 'El rendimiento histórico no garantiza rendimiento futuro. La IA optimiza sobre datos pasados y puede no capturar cambios estructurales del mercado.', options: [{ text: 'Analizas el riesgo actual, el contexto de mercado y consultas con un asesor humano', score: 100 }, { text: 'Inviertes directamente — los datos históricos son la mejor señal', score: -100 }, { text: 'Lo piensas mucho pero al final no actúas', score: 0 }] },
  { cat: 'ai-finance', d: 2, s: 'Tu empresa usa IA para detectar fraude en transacciones. Genera muchos falsos positivos. ¿Qué haces?', t: 'Los falsos positivos en detección de fraude tienen coste de negocio real. Ajustar el umbral requiere balancear sensibilidad y especificidad.', options: [{ text: 'Ajustas el umbral de confianza y añades revisión humana para casos intermedios', score: 100 }, { text: 'Bloqueas todas las transacciones dudosas — mejor prevenir', score: -100 }, { text: 'Desactivas el sistema — genera demasiado trabajo extra', score: 0 }] },
  { cat: 'ai-finance', d: 2, s: 'La IA de tu banco crea tu perfil de riesgo financiero. Discrepas con su evaluación. Tú...', t: 'Los perfiles de riesgo generados por IA pueden tener errores de datos o supuestos incorrectos. Tienes derecho a cuestionar y corregir.', options: [{ text: 'Solicitas explicación de los factores usados y presentas evidencias para revisión', score: 100 }, { text: 'Aceptas el perfil — el sistema sabe más que tú de tu situación', score: -100 }, { text: 'Cambias de banco sin intentar corregir el error', score: 0 }] },
  { cat: 'ai-finance', d: 1, s: 'Usas una app de IA para gestionar tu presupuesto personal. ¿Qué datos son esenciales darle?', t: 'Una app de presupuesto necesita datos de ingresos y gastos para funcionar. El mínimo necesario que permite análisis útil es el punto correcto de partida.', options: [{ text: 'Ingresos, gastos regulares y categorías de gasto que quieres controlar', score: 100 }, { text: 'Todos tus datos bancarios incluyendo contraseñas para acceso completo', score: -100 }, { text: 'Solo tus objetivos de ahorro sin datos de gastos reales', score: 0 }] },
  { cat: 'ai-finance', d: 3, s: 'Un robo-advisor de IA gestiona tu cartera de inversión autónomamente. Mercado cae 20%. Tú...', t: 'En correcciones de mercado, las ventas automáticas pueden cristalizar pérdidas. Los inversores a largo plazo suelen beneficiarse de no actuar en pánico.', options: [{ text: 'Revisas si la caída cambia tu tesis de inversión antes de tomar cualquier acción', score: 100 }, { text: 'Llamas para parar el robo-advisor y vendes todo', score: -100 }, { text: 'Ignoras completamente la caída — la IA sabe lo que hace', score: 0 }] },
  { cat: 'ai-finance', d: 2, s: 'Una IA de análisis financiero predice quiebra de una empresa en 6 meses. Tú...', t: 'Las predicciones de IA son probabilísticas. Antes de actuar sobre una predicción de quiebra, valida si el modelo captura información que tú conoces mejor.', options: [{ text: 'Analizas los fundamentos de la empresa y los factores que usa el modelo antes de decidir', score: 100 }, { text: 'Vendes inmediatamente — la IA tiene más datos que tú', score: -100 }, { text: 'Ignoras la predicción — las IAs no pueden predecir quiebras', score: 0 }] },
  { cat: 'ai-finance', d: 1, s: 'La IA de tu empresa detecta un posible error contable. Tu primer paso es...', t: 'Los errores contables detectados por IA deben verificarse antes de escalar. La IA puede detectar anomalías pero no siempre comprende el contexto.', options: [{ text: 'Verificar manualmente si es un error real o una anomalía con contexto válido', score: 100 }, { text: 'Corregirlo inmediatamente sin verificar', score: -100 }, { text: 'Ignorarlo hasta que el auditor lo encuentre', score: 0 }] },
  { cat: 'ai-finance', d: 3, s: 'Tu empresa quiere usar IA para scoring crediticio de clientes. ¿Cuál es el mayor riesgo ético?', t: 'El scoring crediticio por IA puede perpetuar sesgos históricos de discriminación si los datos de entrenamiento los contienen. Requiere auditoría continua.', options: [{ text: 'Que el modelo perpetúe sesgos históricos discriminando grupos protegidos', score: 100 }, { text: 'Que sea más lento que el proceso manual actual', score: -100 }, { text: 'Que los clientes rechacen compartir sus datos', score: 0 }] },
  { cat: 'ai-finance', d: 2, s: 'La IA propone recortar gastos en formación para mejorar el margen. Tú...', t: 'La IA optimiza las métricas que se le dan. Si no incluye el impacto de la formación en productividad y retención, su recomendación es incompleta.', options: [{ text: 'Preguntas qué impacto a largo plazo en retención y productividad tiene el recorte', score: 100 }, { text: 'Aceptas la recomendación — el margen es la prioridad', score: -100 }, { text: 'Rechazas sin analizar si la formación actual realmente tiene impacto medible', score: 0 }] },
  { cat: 'ai-finance', d: 1, s: 'Recibes un email de tu banco con un enlace a una IA que gestiona "inversiones automáticas". Tú...', t: 'Los fraudes financieros usan cada vez más fachadas de IA para parecer legítimos. Verificar el origen antes de hacer clic es seguridad básica.', options: [{ text: 'Verificas la autenticidad del email accediendo directamente a la web del banco', score: 100 }, { text: 'Haces clic — es de tu banco y la IA suena a servicio legítimo', score: -100 }, { text: 'Lo ignoras — nunca haces clic en emails bancarios', score: 0 }] },
  { cat: 'ai-finance', d: 3, s: 'La IA de tu departamento financiero recomienda una fusión. El CEO pregunta si confiar en ella. Tú...', t: 'Las recomendaciones de IA para decisiones estratégicas de alto impacto deben tratarse como análisis, no como decisiones. El juicio ejecutivo y el due diligence humano son insustituibles.', options: [{ text: 'Usarla como punto de partida del análisis, no como decisión final', score: 100 }, { text: 'Confiar completamente — la IA analiza más variables que cualquier equipo', score: -100 }, { text: 'Ignorarla para decisiones estratégicas — la IA no entiende el contexto', score: 0 }] },
  { cat: 'ai-finance', d: 2, s: 'Una IA predice que el precio de un activo subirá un 40% en un mes. Tu reacción es...', t: 'Las predicciones de mercado a corto plazo con alta precisión son sospechosas. Los mercados son impredecibles a ese horizonte incluso con IA avanzada.', options: [{ text: 'Extrema escepticismo — esa precisión a corto plazo no es estadísticamente creíble', score: 100 }, { text: 'Invertir una cantidad importante — la IA tiene datos que tú no', score: -100 }, { text: 'No hacer nada — no te fías de ninguna predicción de mercado', score: 0 }] },
  { cat: 'ai-finance', d: 1, s: 'Quieres usar IA para hacer tu declaración de impuestos. ¿Cuál es el límite apropiado?', t: 'La IA puede ayudar a organizar datos y detectar deducciones, pero la responsabilidad legal de la declaración es tuya. La firma humana debe ir precedida de revisión humana.', options: [{ text: 'Usarla para organizar datos y detectar deducciones, revisar tú mismo antes de firmar', score: 100 }, { text: 'Dejarla hacer toda la declaración y presentarla directamente', score: -100 }, { text: 'No usarla — los impuestos son demasiado importantes para IA', score: 0 }] },
  { cat: 'ai-finance', d: 3, s: 'Tu empresa considera automatizar completamente el departamento de finanzas con IA. Riesgos clave...', t: 'La automatización total en finanzas elimina el juicio humano ante anomalías inesperadas y puede crear fragilidad sistémica invisible.', options: [{ text: 'Pérdida de supervisión humana en anomalías y decisiones en contextos sin precedente', score: 100 }, { text: 'El coste inicial de implementación — si funciona, no hay riesgos reales', score: -100 }, { text: 'La resistencia del equipo al cambio', score: 0 }] },

  // ai-health (14)
  { cat: 'ai-health', d: 1, s: 'Una app de IA analiza tus síntomas y sugiere que podrías tener una enfermedad grave. Tú...', t: 'Las apps de síntomas de IA tienen alta tasa de falsas alarmas. Son útiles para decidir si ir al médico, no para diagnosticar.', options: [{ text: 'Consultas con un médico antes de alarmaerte o ignorarlo', score: 100 }, { text: 'Buscas más información en internet para confirmar el diagnóstico de IA', score: -100 }, { text: 'Ignoras la app — no puede saber lo que tienes', score: 0 }] },
  { cat: 'ai-health', d: 2, s: 'Un médico usa IA para apoyar su diagnóstico. Propone un tratamiento diferente al de la IA. ¿Qué debería hacer?', t: 'La IA en medicina es una herramienta de apoyo. El médico tiene información contextual, relacional y clínica que la IA no tiene. Su juicio prevalece.', options: [{ text: 'El médico evalúa por qué difieren y usa ambas perspectivas para decidir', score: 100 }, { text: 'Sigue la IA — tiene más datos y es más objetiva', score: -100 }, { text: 'Ignora la IA completamente — es solo un programa', score: 0 }] },
  { cat: 'ai-health', d: 2, s: 'Tu empresa de salud quiere compartir datos de pacientes con una IA para mejorar diagnósticos. Tu posición...', t: 'Los datos de salud son de máxima sensibilidad. El consentimiento informado, la anonimización y la gobernanza de datos son requisitos no negociables.', options: [{ text: 'Solo con consentimiento explícito del paciente y datos adecuadamente anonimizados', score: 100 }, { text: 'Los datos de salud deben fluir libremente para mejorar la IA — el beneficio es colectivo', score: -100 }, { text: 'Nunca — los datos de salud no deben usarse para entrenar IA', score: 0 }] },
  { cat: 'ai-health', d: 1, s: 'Una pulsera con IA detecta que tu frecuencia cardíaca es inusual durante la noche. Tú...', t: 'Los wearables de IA monitorizan patrones pero tienen alta tasa de falsas alarmas. Repetición y comparación con síntomas son mejores criterios de acción que una sola alerta.', options: [{ text: 'Observas si el patrón se repite y si hay síntomas antes de consultar al médico', score: 100 }, { text: 'Vas a urgencias inmediatamente — mejor prevenir', score: -100 }, { text: 'Ignoras la alerta — los wearables siempre dan falsas alarmas', score: 0 }] },
  { cat: 'ai-health', d: 3, s: 'La IA de un hospital recomienda priorizar pacientes según predicciones de recuperación. ¿Cuál es el riesgo ético?', t: 'La priorización basada en predicciones de IA puede discriminar a grupos históricamente infrarrepresentados en los datos de entrenamiento.', options: [{ text: 'Que el modelo favorezca a pacientes similares a los casos de éxito históricos, discriminando otros grupos', score: 100 }, { text: 'Que los médicos pierdan autonomía en sus decisiones clínicas', score: -100 }, { text: 'Que los pacientes rechacen ser evaluados por IA', score: 0 }] },
  { cat: 'ai-health', d: 2, s: 'Usas IA para monitorizar tu salud mental. Te dice que estás bien cuando tú no te sientes bien. Tú...', t: 'La IA de salud mental mide indicadores observables, no estados subjetivos. Tu propia percepción de tu estado tiene validez que ningún algoritmo puede invalidar.', options: [{ text: 'Priorizas tu percepción subjetiva y buscas apoyo profesional si lo necesitas', score: 100 }, { text: 'Confías en la IA — si dice que estás bien, probablemente exageras', score: -100 }, { text: 'Calibras la app con más datos antes de hacer nada', score: 0 }] },
  { cat: 'ai-health', d: 1, s: 'La IA de nutrición te recomienda una dieta personalizada. Antes de seguirla...', t: 'Las recomendaciones de nutrición de IA son generalizaciones estadísticas. Las condiciones individuales (alergias, medicamentos, historial) requieren validación profesional.', options: [{ text: 'Verificas que no contradice ninguna condición de salud tuya o medicación actual', score: 100 }, { text: 'La sigues directamente — está personalizada para ti', score: -100 }, { text: 'La ignoras — las dietas de IA son marketing', score: 0 }] },
  { cat: 'ai-health', d: 3, s: 'Una aseguradora quiere usar IA para ajustar primas según datos de salud de wearables. Tus derechos como asegurado...', t: 'El uso de datos de salud continua para ajustar primas es discriminación dinámica. Muchos países tienen regulaciones específicas al respecto.', options: [{ text: 'Derecho a no compartir esos datos y a que las primas no se calculen sobre comportamiento privado de salud', score: 100 }, { text: 'Aceptas — si llevas vida saludable, debería beneficiarte', score: -100 }, { text: 'No tienes derechos especiales — firmaste el contrato', score: 0 }] },
  { cat: 'ai-health', d: 2, s: 'La IA de tu clínica predice que un paciente abandonará el tratamiento. ¿Qué acción es ética?', t: 'Las predicciones de adherencia deben usarse para ofrecer apoyo, no para reducir recursos o etiquetar negativamente al paciente.', options: [{ text: 'Ofrecer al paciente apoyo adicional y eliminar barreras de acceso al tratamiento', score: 100 }, { text: 'Reducir inversión en ese paciente — la IA indica baja probabilidad de éxito', score: -100 }, { text: 'Informar al paciente de la predicción para que tome conciencia', score: 0 }] },
  { cat: 'ai-health', d: 1, s: 'Quieres usar IA para mejorar tus hábitos de sueño. ¿Qué necesitas monitorizar primero?', t: 'Sin datos de línea base, la IA no puede identificar qué hábitos específicos afectan tu sueño. El diagnóstico precede a la intervención.', options: [{ text: 'Tus patrones actuales de sueño, horarios y hábitos previos a dormir', score: 100 }, { text: 'Tu dieta completa de los últimos 6 meses', score: -100 }, { text: 'Tu nivel de estrés laboral únicamente', score: 0 }] },
  { cat: 'ai-health', d: 3, s: 'La IA de un ensayo clínico selecciona qué pacientes participan. ¿Cuál es el sesgo más probable?', t: 'Los ensayos clínicos con selección por IA pueden reproducir los sesgos de los datos históricos, excluyendo poblaciones subrepresentadas históricamente.', options: [{ text: 'Exclusión de grupos demográficos históricamente infrarrepresentados en ensayos previos', score: 100 }, { text: 'Seleccionar pacientes demasiado sanos para el ensayo', score: -100 }, { text: 'Seleccionar pacientes que no quieren participar', score: 0 }] },
  { cat: 'ai-health', d: 2, s: 'Tu empresa quiere implementar IA para detectar burnout en empleados. Los empleados no lo saben. Tú...', t: 'La vigilancia de salud laboral sin conocimiento del empleado viola la confianza y en muchos países es ilegal. La transparencia es condición previa.', options: [{ text: 'Te opones: primero comunicar, obtener consentimiento y diseñar garantías de privacidad', score: 100 }, { text: 'Lo apoyas — si ayuda a detectar burnout, el fin justifica los medios', score: -100 }, { text: 'Propones usarlo solo con directivos — tienen más responsabilidad', score: 0 }] },
  { cat: 'ai-health', d: 1, s: 'La IA de tu seguro de salud identifica que tienes hábitos de riesgo y te llama para "orientarte". Tú...', t: 'El uso de datos de salud para intervención proactiva de la aseguradora puede ser beneficioso o invasivo dependiendo del diseño y consentimiento previo.', options: [{ text: 'Preguntas qué datos usaron, con qué consentimiento y qué harán con la información', score: 100 }, { text: 'Agradeces el contacto — están cuidando tu salud', score: -100 }, { text: 'Cuelgas y cancelas el seguro', score: 0 }] },
  { cat: 'ai-health', d: 3, s: 'Un sistema de IA recomienda un medicamento fuera de ficha técnica basándose en patrones de datos. Tú...', t: 'Los usos off-label requieren evidencia clínica validada y decisión médica informada. La IA puede señalar correlaciones pero no sustituir el proceso de validación.', options: [{ text: 'Tratas la recomendación como hipótesis a validar por el médico especialista', score: 100 }, { text: 'Pruebas el medicamento — la IA tiene más datos que tu médico', score: -100 }, { text: 'Rechazas cualquier recomendación fuera de ficha técnica', score: 0 }] },
]

console.log('Total:', ALL.length, 'questions')
for (let i = 0; i < ALL.length; i += 20) {
  await insert(ALL.slice(i, i + 20))
}
