const TOKEN = 'sbp_f314cf27b5b2a01eea48048a7b1c015cc9cf4b42'
const API = 'https://api.supabase.com/v1/projects/amhfxaqolholacanqyas/database/query'
function esc(s) { return s.replace(/'/g, "''") }
async function insert(batch) {
  const values = batch.map(q => {
    const opts = JSON.stringify(q.options).replace(/'/g, "''")
    return `('es','${q.cat}','${esc(q.s)}','${esc(q.t)}','${opts}'::jsonb,${q.d},'claude',true)`
  }).join(',')
  const sql = `INSERT INTO questions (locale,category,scenario_text,mindset_tip,options,difficulty,generated_by,is_active) VALUES ${values};`
  const r = await fetch(API, {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${TOKEN}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query: sql })
  })
  const d = await r.json()
  if (d.message) { console.error('ERR:', d.message); return false }
  console.log('OK:', batch.length, 'inserted')
  return true
}

const ALL = [
  // ai-security-risk (14)
  { cat: 'ai-security-risk', d: 1, s: 'Recibes un email ultra-personalizado que cita detalles exactos de tu vida laboral. Sospechas que es phishing con IA. Tú...', t: 'El spear-phishing mejorado por IA usa datos de redes sociales y profesionales para crear mensajes hiperrealistas. La hiperpersonalización es ahora una señal de alerta, no de confianza.', options: [{ text: 'Verificas el remitente por canal alternativo antes de hacer clic en nada', score: 100 }, { text: 'Confías en el email porque los detalles son demasiado precisos para ser falsos', score: -100 }, { text: 'Lo reenvías al equipo de IT sin más análisis', score: 0 }] },
  { cat: 'ai-security-risk', d: 2, s: 'Tu empresa quiere usar un modelo de IA de un proveedor externo. ¿Qué evaluación de seguridad necesitas?', t: 'Los modelos de IA externos pueden filtrar datos de prompts, tener vulnerabilidades de inyección o no cumplir con los requisitos de privacidad de datos que envías a la API.', options: [{ text: 'Evaluar la política de uso de datos, el aislamiento de prompts y el cumplimiento normativo', score: 100 }, { text: 'Solo verificar que el proveedor tiene ISO 27001', score: -100 }, { text: 'Hacer una prueba de rendimiento antes de evaluar seguridad', score: 0 }] },
  { cat: 'ai-security-risk', d: 2, s: 'Un atacante usa prompt injection para manipular tu asistente de IA corporativo. ¿Cómo lo mitigas?', t: 'La inyección de prompts ocurre cuando inputs de usuario malicioso redefinen las instrucciones del sistema. La separación estricta entre datos de usuario e instrucciones del sistema es la defensa principal.', options: [{ text: 'Separar estrictamente instrucciones del sistema de inputs de usuario y validar todos los outputs', score: 100 }, { text: 'Filtrar palabras clave maliciosas en los inputs del usuario', score: -100 }, { text: 'Deshabilitar el asistente de IA para usuarios externos', score: 0 }] },
  { cat: 'ai-security-risk', d: 1, s: 'Tu empresa procesa datos sensibles de clientes con IA en la nube. ¿Cuál es el control más crítico?', t: 'Los datos sensibles procesados por IA en la nube requieren cifrado en tránsito y en reposo, y acuerdos contractuales claros sobre uso y eliminación de datos por el proveedor.', options: [{ text: 'Cifrado extremo a extremo y acuerdos contractuales de no uso de datos para entrenamiento', score: 100 }, { text: 'Que el proveedor tenga buena reputación en el mercado', score: -100 }, { text: 'Usar solo nubes de proveedores europeos', score: 0 }] },
  { cat: 'ai-security-risk', d: 3, s: 'La IA de tu empresa puede ser usada para generar desinformación sobre tu propia organización. ¿Qué controles implementas?', t: 'La IA generativa como vector de desinformación interna o externa es un riesgo emergente. Los controles de uso, monitorización de outputs y políticas claras de uso son la primera línea de defensa.', options: [{ text: 'Políticas de uso claras, monitorización de outputs y canales de reporte de uso indebido', score: 100 }, { text: 'Restricciones técnicas que impidan mencionar el nombre de la empresa', score: -100 }, { text: 'Solo dar acceso a la IA al equipo de comunicaciones', score: 0 }] },
  { cat: 'ai-security-risk', d: 2, s: 'Un deepfake de audio de tu CEO pide una transferencia urgente. El CFO llama a verificar. ¿Qué protocolo activas?', t: 'Los deepfakes de audio son un vector de fraude financiero creciente. Los protocolos de verificación fuera de banda (llamada a número conocido, clave de confirmación) son la defensa efectiva.', options: [{ text: 'Verificas por canal separado (llamada a número conocido del CEO) antes de cualquier transferencia', score: 100 }, { text: 'Confías en el audio — si suena al CEO, es el CEO', score: -100 }, { text: 'Preguntas al CEO por email para confirmar', score: 0 }] },
  { cat: 'ai-security-risk', d: 1, s: 'Tu sistema de IA tiene acceso a datos de toda la empresa. Un atacante lo compromete. ¿Cuál es el peor escenario?', t: 'Los sistemas de IA con acceso amplio son vectores de exfiltración de datos masiva. El principio de mínimo privilegio limita el impacto de una brecha.', options: [{ text: 'Exfiltración masiva de datos confidenciales de toda la empresa a través del sistema comprometido', score: 100 }, { text: 'Que el sistema deje de funcionar temporalmente', score: -100 }, { text: 'Que el atacante use la IA para responder emails internos', score: 0 }] },
  { cat: 'ai-security-risk', d: 3, s: 'Quieres hacer un red team de tu sistema de IA antes de desplegarlo. ¿Qué incluye ese ejercicio?', t: 'El red team de sistemas de IA incluye pruebas de jailbreak, inyección de prompts, extracción de datos de entrenamiento, y comportamientos inesperados en inputs extremos.', options: [{ text: 'Jailbreak, inyección de prompts, extracción de datos y comportamientos en inputs extremos', score: 100 }, { text: 'Solo pruebas de rendimiento bajo carga', score: -100 }, { text: 'Un análisis de código estático del modelo', score: 0 }] },
  { cat: 'ai-security-risk', d: 2, s: 'La IA de tu empresa usa datos de empleados para optimizar procesos. ¿Cuál es el riesgo de seguridad interno?', t: 'Los datos de empleados en sistemas de IA son un objetivo de insider threats. El acceso a esos datos debe limitarse y auditarse con el mismo rigor que los datos de clientes.', options: [{ text: 'Insider threat: empleados con acceso pueden exfiltrar datos de compañeros a través del sistema', score: 100 }, { text: 'Que los empleados no quieran que sus datos se usen', score: -100 }, { text: 'Que el sistema de IA tome decisiones sesgadas sobre empleados', score: 0 }] },
  { cat: 'ai-security-risk', d: 1, s: 'Usas una herramienta de IA gratuita para procesar documentos confidenciales. ¿Cuál es el riesgo principal?', t: 'Las herramientas gratuitas de IA a menudo usan los datos enviados para mejorar sus modelos o tienen términos de uso que permiten el procesamiento de los datos por el proveedor.', options: [{ text: 'Que los documentos puedan usarse para entrenamiento o sean accesibles al proveedor', score: 100 }, { text: 'Que la calidad del procesamiento sea inferior a las herramientas de pago', score: -100 }, { text: 'Que la herramienta no sea compatible con todos los formatos', score: 0 }] },
  { cat: 'ai-security-risk', d: 3, s: 'La IA puede automatizar ataques cibernéticos a escala. ¿Qué implica para la defensa?', t: 'La automatización de ataques con IA aumenta la velocidad y escala de las amenazas. La defensa requiere también IA para respuesta en tiempo real a la altura del atacante.', options: [{ text: 'Que la defensa debe también usar IA para operar a la velocidad y escala del atacante', score: 100 }, { text: 'Que la ciberseguridad tradicional es suficiente si se actualiza bien', score: -100 }, { text: 'Que el foco debe ser en aislar sistemas críticos de internet', score: 0 }] },
  { cat: 'ai-security-risk', d: 2, s: 'La IA de tu empresa tiene un fallo que permite a usuarios extraer información de otros usuarios. ¿Cuál es tu protocolo?', t: 'Una vulnerabilidad de filtración de datos en IA es un incidente de seguridad activo. Requiere respuesta inmediata: contención, notificación y análisis forense.', options: [{ text: 'Contener el fallo inmediatamente, notificar a afectados y realizar análisis forense', score: 100 }, { text: 'Corregir el fallo silenciosamente sin notificar a los usuarios afectados', score: -100 }, { text: 'Esperar a confirmar el alcance completo antes de tomar ninguna acción', score: 0 }] },
  { cat: 'ai-security-risk', d: 1, s: 'Tu empresa quiere usar IA para detectar amenazas de seguridad internas. ¿Cuál es el equilibrio correcto?', t: 'La vigilancia de empleados con IA para detectar amenazas internas requiere proporcionalidad, transparencia y garantías legales. La vigilancia excesiva deteriora la confianza y la cultura.', options: [{ text: 'Monitorizar anomalías en sistemas críticos con transparencia, no el comportamiento completo del empleado', score: 100 }, { text: 'Monitorizar todo el comportamiento digital — la seguridad es prioritaria', score: -100 }, { text: 'No monitorizar con IA — viola la privacidad del empleado', score: 0 }] },
  { cat: 'ai-security-risk', d: 3, s: 'La IA de tu empresa puede ser envenenada con datos maliciosos (data poisoning). ¿Cómo te proteges?', t: 'El envenenamiento de datos de entrenamiento puede degradar la fiabilidad del modelo o crear puertas traseras. La validación de la integridad de los datos y el monitoreo de comportamiento del modelo son las defensas clave.', options: [{ text: 'Validar la integridad de datos de entrenamiento y monitorizar comportamientos anómalos del modelo', score: 100 }, { text: 'Usar solo datos propios — el envenenamiento solo ocurre con datos externos', score: -100 }, { text: 'Reentrenar el modelo con más datos para diluir los datos maliciosos', score: 0 }] },

  // ai-sustainability (14)
  { cat: 'ai-sustainability', d: 1, s: 'Tu empresa quiere usar IA para reducir su huella de carbono. ¿Por dónde empiezas?', t: 'La IA puede optimizar consumo energético, logística y cadena de suministro. Pero primero hay que medir la huella actual para identificar dónde la IA puede tener mayor impacto.', options: [{ text: 'Midiendo la huella actual por proceso para identificar dónde la IA tiene mayor potencial', score: 100 }, { text: 'Implementando la IA de eficiencia energética más popular del mercado', score: -100 }, { text: 'Comunicando el uso de IA para sostenibilidad antes de tener resultados', score: 0 }] },
  { cat: 'ai-sustainability', d: 2, s: 'La IA que usa tu empresa tiene un alto consumo energético. ¿Cómo calculas su impacto neto?', t: 'El impacto neto de la IA en sostenibilidad requiere calcular el consumo energético de la IA versus los ahorros que genera. Solo si el balance es positivo tiene sentido usarla para sostenibilidad.', options: [{ text: 'Calculando el consumo energético de la IA versus los ahorros netos que genera', score: 100 }, { text: 'El impacto de la IA en el entorno es siempre positivo si se usa para sostenibilidad', score: -100 }, { text: 'Compensando el consumo de la IA con compra de créditos de carbono', score: 0 }] },
  { cat: 'ai-sustainability', d: 2, s: 'La IA puede predecir picos de demanda energética y optimizar el consumo. ¿Cuál es el mayor beneficio?', t: 'La optimización predictiva de consumo energético permite reducir el desperdicio en horas de baja demanda y desplazar el consumo a momentos de mayor disponibilidad de energía renovable.', options: [{ text: 'Desplazar el consumo a momentos de mayor disponibilidad de energía renovable', score: 100 }, { text: 'Reducir la factura energética sin importar de qué fuente viene la energía', score: -100 }, { text: 'Eliminar la necesidad de baterías de almacenamiento', score: 0 }] },
  { cat: 'ai-sustainability', d: 3, s: 'Tu empresa anuncia que usa IA para ser "100% sostenible". ¿Cuál es el riesgo de comunicación?', t: 'Las afirmaciones de sostenibilidad basadas en IA sin evidencia específica y auditable son greenwashing. Las regulaciones de la UE sobre comunicaciones verdes exigen sustancia, no solo promesas.', options: [{ text: 'Greenwashing si no hay métricas específicas y auditables que respalden la afirmación', score: 100 }, { text: 'Ninguno si se usa IA genuinamente — la afirmación es legítima', score: -100 }, { text: 'Que los competidores hagan afirmaciones similares y se pierda la diferenciación', score: 0 }] },
  { cat: 'ai-sustainability', d: 1, s: 'La IA puede ayudar a diseñar productos más sostenibles. ¿Cuál es su mayor valor en este proceso?', t: 'La IA puede analizar miles de combinaciones de materiales y diseños para optimizar la sostenibilidad del ciclo de vida completo del producto, algo imposible manualmente.', options: [{ text: 'Optimizar el ciclo de vida completo del producto considerando miles de combinaciones a la vez', score: 100 }, { text: 'Sustituir al equipo de diseño por procesos automáticos', score: -100 }, { text: 'Generar informes de sostenibilidad automáticamente', score: 0 }] },
  { cat: 'ai-sustainability', d: 2, s: 'El entrenamiento de un gran modelo de IA emite tanta CO2 como varios viajes transatlánticos. ¿Qué implica para el desarrollo?', t: 'El coste ambiental del entrenamiento de modelos grandes justifica la reutilización de modelos existentes mediante fine-tuning en lugar de entrenar desde cero, siempre que sea posible.', options: [{ text: 'Priorizar el fine-tuning de modelos existentes sobre el entrenamiento desde cero', score: 100 }, { text: 'Dejar de usar IA hasta que los centros de datos sean 100% renovables', score: -100 }, { text: 'El impacto es irrelevante si el modelo tiene valor social suficiente', score: 0 }] },
  { cat: 'ai-sustainability', d: 1, s: 'Tu cadena de suministro quiere usar IA para reducir el desperdicio de materiales. ¿Cuál es el primer dato que necesitas?', t: 'Para reducir desperdicio de materiales con IA necesitas primero datos precisos de dónde ocurre el desperdicio en la cadena. Sin visibilidad del problema, la IA no puede optimizar.', options: [{ text: 'Datos de cuándo, dónde y cuánto desperdicio ocurre en cada etapa de la cadena', score: 100 }, { text: 'El precio del material desperdiciado para calcular el ROI', score: -100 }, { text: 'La normativa de desperdicio del sector', score: 0 }] },
  { cat: 'ai-sustainability', d: 3, s: 'La IA puede optimizar rutas de logística para reducir emisiones. ¿Cuál es la tensión principal?', t: 'La optimización de rutas para emisiones puede entrar en conflicto con la optimización para velocidad o coste. Definir claramente la función objetivo (emisiones vs. tiempo vs. coste) es el paso clave.', options: [{ text: 'Que minimizar emisiones puede aumentar tiempo de entrega o coste operativo', score: 100 }, { text: 'Que la IA no tiene suficientes datos de tráfico en tiempo real', score: -100 }, { text: 'Que los conductores no quieran cambiar sus rutas habituales', score: 0 }] },
  { cat: 'ai-sustainability', d: 2, s: 'Quieres usar IA para medir la huella de carbono de tu empresa en tiempo real. ¿Cuál es el reto principal?', t: 'La medición de huella de carbono en tiempo real requiere datos de proveedores, consumo energético y operaciones. La calidad y estandarización de esos datos es el cuello de botella, no la IA.', options: [{ text: 'La calidad y estandarización de los datos de proveedores y operaciones', score: 100 }, { text: 'El coste de los sensores necesarios para la medición', score: -100 }, { text: 'Encontrar una IA lo suficientemente precisa para la tarea', score: 0 }] },
  { cat: 'ai-sustainability', d: 1, s: 'La IA puede predecir el impacto ambiental de nuevas regulaciones antes de que entren en vigor. ¿Para qué lo usas?', t: 'La anticipación de impacto regulatorio ambiental con IA permite preparar la adaptación con tiempo suficiente, lo que reduce el coste del cumplimiento y puede generar ventaja competitiva.', options: [{ text: 'Para preparar la adaptación de procesos antes de que la regulación entre en vigor', score: 100 }, { text: 'Para argumentar ante el regulador por qué la norma es demasiado restrictiva', score: -100 }, { text: 'Para comunicar externamente que estás adelantado a la regulación', score: 0 }] },
  { cat: 'ai-sustainability', d: 3, s: 'La IA de agricultura puede reducir el uso de pesticidas un 80%. ¿Cuál es el requisito para desplegar a escala?', t: 'Las aplicaciones de IA en agricultura de precisión requieren infraestructura de sensores, conectividad en campo y formación de agricultores. La tecnología es solo una parte del sistema.', options: [{ text: 'Infraestructura de sensores, conectividad y formación de agricultores para operar el sistema', score: 100 }, { text: 'Solo el algoritmo de IA — el resto es problema del agricultor', score: -100 }, { text: 'La aprobación regulatoria del nuevo método de aplicación', score: 0 }] },
  { cat: 'ai-sustainability', d: 2, s: 'La IA puede identificar inversiones ESG fraudulentas (greenwashing). ¿Cuál es su mayor limitación?', t: 'La IA detecta inconsistencias entre declaraciones y datos verificables. Pero el greenwashing sofisticado usa datos reales para afirmaciones engañosas. La IA no detecta la intención detrás de los datos.', options: [{ text: 'No puede detectar el greenwashing sofisticado que usa datos reales para afirmaciones engañosas', score: 100 }, { text: 'No tiene acceso a suficientes datos de empresas privadas', score: -100 }, { text: 'Los datos ESG son demasiado complejos para analizarlos con IA', score: 0 }] },
  { cat: 'ai-sustainability', d: 1, s: 'Tu empresa quiere compensar las emisiones de su IA comprando créditos de carbono. ¿Es suficiente?', t: 'Los créditos de carbono son un mecanismo de compensación, no de reducción. Son complemento a la reducción de emisiones, no sustituto. La adicionalidad y permanencia de los créditos también debe verificarse.', options: [{ text: 'No: la compensación es complemento a la reducción, no sustituto', score: 100 }, { text: 'Sí: si compra créditos equivalentes, el impacto neto es cero', score: -100 }, { text: 'Depende del precio del carbono en el mercado', score: 0 }] },
  { cat: 'ai-sustainability', d: 3, s: 'La IA puede optimizar el consumo energético de los edificios en tiempo real. El mayor obstáculo para la adopción...', t: 'La optimización energética de edificios con IA requiere integración con sistemas legacy de gestión del edificio que raramente tienen APIs modernas. La integración de sistemas es el verdadero cuello de botella.', options: [{ text: 'La integración con sistemas legacy de gestión del edificio sin APIs modernas', score: 100 }, { text: 'La resistencia de los ocupantes a perder control del clima de su espacio', score: -100 }, { text: 'El coste de los algoritmos de optimización', score: 0 }] },

  // ai-tools-comparison (14)
  { cat: 'ai-tools-comparison', d: 1, s: 'Tienes que elegir entre ChatGPT y Claude para tu equipo. ¿Cuál es el criterio más importante?', t: 'No hay una herramienta universalmente mejor. El criterio más relevante es qué tareas específicas necesita tu equipo y cuál herramienta rinde mejor en esas tareas concretas.', options: [{ text: 'Cuál rinde mejor en las tareas específicas que tu equipo necesita hacer', score: 100 }, { text: 'Cuál tiene más usuarios en el mundo — más popular es mejor', score: -100 }, { text: 'Cuál es más barata en el plan básico', score: 0 }] },
  { cat: 'ai-tools-comparison', d: 2, s: 'Tu empresa evalúa herramientas de IA para análisis de datos. ¿Cómo estructuras la evaluación?', t: 'La evaluación de herramientas de IA para datos requiere pruebas con datos reales representativos de tu caso, no solo demos del proveedor con ejemplos ideales.', options: [{ text: 'Con casos de uso reales de tu empresa y datos representativos, no con demos del proveedor', score: 100 }, { text: 'Con el benchmark de rendimiento general publicado por el proveedor', score: -100 }, { text: 'Con la opinión de los analistas del sector como Gartner', score: 0 }] },
  { cat: 'ai-tools-comparison', d: 1, s: 'Un colega dice que "la IA X es la mejor del mercado". ¿Cómo evalúas esa afirmación?', t: 'El rendimiento de los modelos de IA es específico por tarea. Un modelo puede ser mejor en razonamiento matemático y peor en redacción creativa. Los benchmarks generales tienen valor limitado para casos concretos.', options: [{ text: 'Preguntando en qué tareas específicas y con qué métricas la evalúa', score: 100 }, { text: 'Aceptando la afirmación — si hay consenso, probablemente es correcto', score: -100 }, { text: 'Buscando el ranking de IA más reciente en internet', score: 0 }] },
  { cat: 'ai-tools-comparison', d: 2, s: 'Tu empresa usa 5 herramientas de IA distintas para distintos departamentos. ¿Es esto problemático?', t: 'La fragmentación de herramientas de IA puede generar silos de datos, inconsistencias en outputs y mayor coste de licencias y formación. Consolidar donde sea posible es mejor práctica.', options: [{ text: 'Puede serlo si genera silos, inconsistencias y coste de formación innecesario', score: 100 }, { text: 'No: cada departamento sabe mejor qué herramienta necesita', score: -100 }, { text: 'Solo si las herramientas tienen funcionalidades solapadas exactas', score: 0 }] },
  { cat: 'ai-tools-comparison', d: 3, s: 'Un proveedor dice que su modelo de IA bate al competidor en todos los benchmarks. ¿Cuánto confías en eso?', t: 'Los benchmarks de IA pueden ser seleccionados estratégicamente para mostrar ventajas. Los benchmarks publicados por el propio proveedor tienen claro conflicto de interés y deben verificarse con evaluaciones independientes.', options: [{ text: 'Poco: los benchmarks propios son sesgados — busca evaluaciones independientes', score: 100 }, { text: 'Completamente: los benchmarks son datos objetivos', score: -100 }, { text: 'Depende del tamaño del proveedor', score: 0 }] },
  { cat: 'ai-tools-comparison', d: 2, s: 'Quieres comparar herramientas de IA generativa para tu equipo de marketing. ¿Qué criterios usas?', t: 'Para marketing, los criterios relevantes son calidad del output en tu idioma y tono, facilidad de personalización, capacidad de seguir brand guidelines y coste por uso a la escala de tu equipo.', options: [{ text: 'Calidad del output en tu idioma, adherencia al tono de marca y coste a tu escala de uso', score: 100 }, { text: 'Cuál tiene más parámetros en su modelo', score: -100 }, { text: 'Cuál usa más empresas de tu sector', score: 0 }] },
  { cat: 'ai-tools-comparison', d: 1, s: 'La herramienta de IA más cara no mejora los resultados de tu equipo. ¿Qué implica?', t: 'El precio de las herramientas de IA no correlaciona perfectamente con su utilidad para casos específicos. El valor real depende de la adecuación entre las capacidades de la herramienta y las necesidades del equipo.', options: [{ text: 'Que el precio no equivale a valor para tu caso de uso específico', score: 100 }, { text: 'Que tu equipo no sabe usarla correctamente todavía', score: -100 }, { text: 'Que la herramienta cara es innecesariamente compleja', score: 0 }] },
  { cat: 'ai-tools-comparison', d: 3, s: 'Tu empresa debe elegir entre un modelo de IA propietario y uno de código abierto. ¿Cuáles son los trade-offs clave?', t: 'Los modelos propietarios ofrecen mejor rendimiento y soporte pero dependencia del proveedor. Los de código abierto ofrecen control y privacidad pero requieren infraestructura y expertise propios.', options: [{ text: 'Propietario: mejor rendimiento pero dependencia; open source: control pero coste de infraestructura', score: 100 }, { text: 'El open source siempre es mejor por la transparencia', score: -100 }, { text: 'El propietario siempre es mejor por el soporte', score: 0 }] },
  { cat: 'ai-tools-comparison', d: 2, s: 'Las herramientas de IA evolucionan muy rápido. ¿Cómo gestionas el riesgo de quedarte obsoleto?', t: 'La velocidad de evolución de las herramientas de IA hace que la inversión en integración profunda con un solo proveedor sea arriesgada. Las arquitecturas modulares permiten cambiar herramientas con menor coste.', options: [{ text: 'Diseñando arquitecturas modulares que permitan cambiar herramientas con menor coste', score: 100 }, { text: 'Eligiendo siempre al proveedor de mayor tamaño — más recursos para mantenerse actualizado', score: -100 }, { text: 'Esperando a que el mercado se consolide antes de comprometerte', score: 0 }] },
  { cat: 'ai-tools-comparison', d: 1, s: 'Quieres usar IA para transcribir reuniones. ¿Cuál es el factor diferenciador más importante?', t: 'Para transcripción de reuniones en entornos profesionales, la precisión en vocabulario técnico y nombres propios de tu sector es el factor que más afecta a la utilidad real del resultado.', options: [{ text: 'La precisión en vocabulario técnico y nombres propios de tu sector', score: 100 }, { text: 'La velocidad de transcripción', score: -100 }, { text: 'Cuántos idiomas soporta la herramienta', score: 0 }] },
  { cat: 'ai-tools-comparison', d: 3, s: 'Tu empresa quiere usar IA para automatizar procesos legales. ¿Qué herramienta elegirías?', t: 'Los procesos legales requieren precisión, trazabilidad y explicabilidad. Los modelos especializados en dominio legal con capacidad de citar fuentes verificables son más adecuados que los modelos generalistas.', options: [{ text: 'Un modelo especializado en dominio legal con trazabilidad de fuentes y alta precisión', score: 100 }, { text: 'El modelo de lenguaje más grande disponible', score: -100 }, { text: 'La herramienta más barata que soporte documentos PDF', score: 0 }] },
  { cat: 'ai-tools-comparison', d: 2, s: 'Después de 3 meses de uso, tu equipo prefiere la herramienta B aunque en la evaluación inicial ganó la A. ¿Qué aprendes?', t: 'Los criterios de evaluación inicial raramente capturan la experiencia de uso real. La ergonomía, la integración en el flujo de trabajo y la curva de aprendizaje son factores que solo se revelan con uso sostenido.', options: [{ text: 'Que la experiencia de uso real revela factores que los criterios iniciales no capturaron', score: 100 }, { text: 'Que el equipo no evalúa correctamente las herramientas', score: -100 }, { text: 'Que la herramienta A era técnicamente superior pero mal comunicada', score: 0 }] },
  { cat: 'ai-tools-comparison', d: 1, s: 'Un proveedor de IA ofrece una prueba gratuita de 30 días. ¿Cómo la aprovechas al máximo?', t: 'Las pruebas de herramientas de IA deben ejecutarse con casos de uso reales y métricas claras de evaluación definidas antes de empezar. Sin ellas, la decisión se basa en impresiones subjetivas.', options: [{ text: 'Definiendo métricas de evaluación y ejecutando casos de uso reales desde el día 1', score: 100 }, { text: 'Explorando todas las funcionalidades disponibles sin plan específico', score: -100 }, { text: 'Comparando con el proveedor actual en las tareas más frecuentes', score: 0 }] },
  { cat: 'ai-tools-comparison', d: 3, s: 'Tu empresa considera construir su propio modelo de IA vs. usar uno de terceros. ¿Cuándo tiene sentido lo primero?', t: 'Construir un modelo propio solo tiene sentido cuando los datos propietarios dan ventaja competitiva que no puede obtenerse con fine-tuning, o cuando hay requisitos de privacidad que impiden usar APIs externas.', options: [{ text: 'Cuando los datos propietarios dan ventaja competitiva única o los requisitos de privacidad impiden usar APIs', score: 100 }, { text: 'Siempre que tengas un equipo de data science', score: -100 }, { text: 'Cuando quieres tener control total sobre el modelo', score: 0 }] },

  // automation-agents (14)
  { cat: 'automation-agents', d: 1, s: 'Un agente de IA puede ejecutar tareas en tu nombre de forma autónoma. ¿Cuál es el primer requisito?', t: 'Los agentes autónomos de IA que actúan en nombre del usuario necesitan alcance de permisos claramente limitado. El principio de mínimo privilegio es la primera capa de seguridad.', options: [{ text: 'Definir claramente qué puede y no puede hacer el agente con permisos mínimos necesarios', score: 100 }, { text: 'Darle acceso completo para que pueda resolver cualquier situación', score: -100 }, { text: 'Monitorizarlo durante los primeros días antes de darle autonomía', score: 0 }] },
  { cat: 'automation-agents', d: 2, s: 'Tu agente de IA toma una decisión que no esperabas y causa un problema. ¿Qué diseño habría prevenido esto?', t: 'Los agentes de IA necesitan puntos de confirmación humana en decisiones de alto impacto o irreversibles. La autonomía sin checkpoints es el riesgo principal de los agentes.', options: [{ text: 'Checkpoints de confirmación humana para decisiones de alto impacto o irreversibles', score: 100 }, { text: 'Un agente más inteligente que no cometa errores de juicio', score: -100 }, { text: 'Más datos de entrenamiento sobre el contexto específico', score: 0 }] },
  { cat: 'automation-agents', d: 2, s: 'Quieres usar agentes de IA para gestionar tu email automáticamente. ¿Cuál es el límite apropiado?', t: 'Los agentes de email pueden clasificar, priorizar y borrar, pero enviar respuestas o tomar compromisos en nombre del usuario requiere revisión humana antes de ejecutar.', options: [{ text: 'Clasificar y priorizar sí; enviar respuestas solo con revisión humana previa', score: 100 }, { text: 'Gestión completa — el agente sabe tu estilo y contexto', score: -100 }, { text: 'Solo archivar emails leídos — nada más', score: 0 }] },
  { cat: 'automation-agents', d: 3, s: 'Un agente de IA puede encadenar múltiples acciones de forma autónoma. ¿Cuál es el riesgo sistémico?', t: 'Los agentes que encadenan acciones pueden amplificar errores iniciales a lo largo de la cadena. Un error en el paso 2 de 10 produce un resultado final muy alejado del objetivo con mucho trabajo generado.', options: [{ text: 'La amplificación de errores a lo largo de la cadena puede generar resultados muy alejados del objetivo', score: 100 }, { text: 'Que el agente tarde demasiado en completar la cadena', score: -100 }, { text: 'Que algunos pasos fallen por problemas técnicos de API', score: 0 }] },
  { cat: 'automation-agents', d: 1, s: 'La diferencia entre automatización tradicional y agentes de IA es...', t: 'La automatización tradicional sigue reglas fijas predefinidas. Los agentes de IA toman decisiones basadas en contexto, lo que les da más flexibilidad pero también más imprevisibilidad.', options: [{ text: 'Los agentes toman decisiones basadas en contexto; la automatización sigue reglas fijas', score: 100 }, { text: 'Solo la velocidad de ejecución', score: -100 }, { text: 'Los agentes necesitan más datos para funcionar', score: 0 }] },
  { cat: 'automation-agents', d: 2, s: 'Tu empresa quiere automatizar el proceso de ventas completo con agentes de IA. ¿Cuál es el paso que NO debes automatizar?', t: 'La negociación de condiciones y el cierre de contratos tienen implicaciones legales y requieren responsabilidad humana. La automatización de estos pasos puede crear compromisos no deseados.', options: [{ text: 'La negociación de condiciones y cierre de contratos con implicaciones legales', score: 100 }, { text: 'El seguimiento de emails de prospección', score: -100 }, { text: 'La cualificación inicial de leads', score: 0 }] },
  { cat: 'automation-agents', d: 3, s: 'Un agente de IA tiene acceso a tus sistemas y toma una acción irreversible por error. ¿Qué aprende tu organización?', t: 'Las acciones irreversibles de agentes de IA sin mecanismo de rollback son el escenario de mayor riesgo. Todo agente con capacidad de acción irreversible debe tener un mecanismo de confirmación y, si posible, de deshacer.', options: [{ text: 'Que las acciones irreversibles requieren siempre confirmación explícita y mecanismo de rollback', score: 100 }, { text: 'Que no se deben usar agentes de IA para procesos críticos', score: -100 }, { text: 'Que el agente necesita más formación', score: 0 }] },
  { cat: 'automation-agents', d: 2, s: 'Quieres que un agente de IA automatice tu proceso de investigación. ¿Cuál es el mayor riesgo?', t: 'Los agentes de investigación pueden generar informes con información incorrecta o alucinada presentada con confianza. La verificación humana de fuentes es imprescindible en investigación con agentes.', options: [{ text: 'Que el agente presente información alucinada con aparente confianza y precisión', score: 100 }, { text: 'Que la investigación tarde más que hacerla manualmente', score: -100 }, { text: 'Que el agente no sepa qué fuentes consultar primero', score: 0 }] },
  { cat: 'automation-agents', d: 1, s: 'Quieres medir el rendimiento de tu agente de IA. ¿Cuál es la métrica más importante?', t: 'El rendimiento de un agente de IA debe medirse por la calidad del resultado final para el usuario, no solo por la velocidad o el número de tareas completadas.', options: [{ text: 'La calidad del resultado final para el usuario y la tasa de errores con consecuencias', score: 100 }, { text: 'El número de tareas completadas por hora', score: -100 }, { text: 'El porcentaje de tareas completadas sin intervención humana', score: 0 }] },
  { cat: 'automation-agents', d: 3, s: 'Tu agente de IA necesita acceder a datos de clientes para personalizar respuestas. ¿Qué arquitectura de privacidad usas?', t: 'Los agentes con acceso a datos de clientes deben implementar acceso mínimo necesario, logs de auditoría de qué datos accedió y cuándo, y encriptación de los datos accedidos.', options: [{ text: 'Acceso mínimo necesario, logs de auditoría y encriptación de datos accedidos', score: 100 }, { text: 'Acceso completo a todos los datos del cliente para mejor personalización', score: -100 }, { text: 'Preguntar al cliente sus datos en cada interacción para no almacenarlos', score: 0 }] },
  { cat: 'automation-agents', d: 2, s: 'Los agentes de IA pueden colaborar entre sí para completar tareas complejas. ¿Cuál es el desafío principal?', t: 'Los sistemas multi-agente amplifican tanto los beneficios como los errores. La coordinación entre agentes puede crear comportamientos emergentes no previstos que son difíciles de predecir y controlar.', options: [{ text: 'Comportamientos emergentes no previstos que son difíciles de predecir y controlar', score: 100 }, { text: 'Que los agentes necesitan más potencia de cálculo', score: -100 }, { text: 'Que los agentes se copian unos a otros y producen resultados redundantes', score: 0 }] },
  { cat: 'automation-agents', d: 1, s: 'Quieres que un agente de IA gestione tus tareas de proyecto. ¿Cuál es el primer paso?', t: 'Antes de delegar la gestión de tareas en un agente, necesitas definir claramente qué criterios usa para priorizar, qué decisiones puede tomar solo y cuándo debe escalar.', options: [{ text: 'Definir criterios de priorización, alcance de decisiones autónomas y protocolo de escalado', score: 100 }, { text: 'Darle acceso a todas tus herramientas de proyecto y ver qué hace', score: -100 }, { text: 'Empezar con tareas muy simples y ver si funciona', score: 0 }] },
  { cat: 'automation-agents', d: 3, s: 'La regulación de agentes autónomos de IA aún no está definida. ¿Cuál es tu estrategia?', t: 'En ausencia de regulación específica de agentes de IA, la estrategia más robusta es aplicar los principios de responsabilidad, transparencia y control humano que anticipa la regulación futura.', options: [{ text: 'Aplicar principios de responsabilidad, transparencia y control humano que anticipa la regulación', score: 100 }, { text: 'Esperar a que la regulación sea clara antes de desplegar agentes', score: -100 }, { text: 'Desplegar con libertad mientras no haya regulación específica', score: 0 }] },
  { cat: 'automation-agents', d: 2, s: 'Tu agente de IA falla en el 10% de los casos. ¿Es aceptable?', t: 'La aceptabilidad del 10% de fallos depende totalmente del impacto de cada fallo. Un 10% de fallos en clasificación de emails es aceptable; un 10% en un proceso médico o financiero crítico no lo es.', options: [{ text: 'Depende del impacto de cada fallo: hay casos donde el 1% sería inaceptable', score: 100 }, { text: 'Sí: el 90% de acierto es un rendimiento excelente para IA', score: -100 }, { text: 'No: la IA debe ser perfecta o no se debe usar', score: 0 }] },
]

console.log('Total:', ALL.length, 'questions')
for (let i = 0; i < ALL.length; i += 20) {
  await insert(ALL.slice(i, i + 20))
}
