const TOKEN = 'sbp_f314cf27b5b2a01eea48048a7b1c015cc9cf4b42'
const API = 'https://api.supabase.com/v1/projects/amhfxaqolholacanqyas/database/query'
function esc(s) { return s.replace(/'/g, "''") }
async function insert(batch) {
  const values = batch.map(q => {
    const opts = JSON.stringify(q.options).replace(/'/g, "''")
    return `('es','${q.cat}','${esc(q.s)}','${esc(q.t)}','${opts}'::jsonb,${q.d},'claude',true)`
  }).join(',')
  const sql = `INSERT INTO questions (locale,category,scenario_text,mindset_tip,options,difficulty,generated_by,is_active) VALUES ${values};`
  const r = await fetch(API, {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${TOKEN}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query: sql })
  })
  const d = await r.json()
  if (d.message) { console.error('ERR:', d.message); return false }
  console.log('OK:', batch.length, 'inserted')
  return true
}

const ALL = [
  // ai-career (14)
  { cat: 'ai-career', d: 1, s: 'Tu empresa anuncia que la IA automatizará partes de tu trabajo. Tu primera reacción es...', t: 'La IA elimina tareas repetitivas y crea nuevas oportunidades. Quienes se adaptan primero tienen ventaja.', options: [{ text: 'Entender qué tareas se automatizan y qué nuevas habilidades necesito', score: 100 }, { text: 'Ignorar el anuncio — seguro que no me afecta a mí', score: -100 }, { text: 'Esperar a ver qué pasa antes de actuar', score: 0 }] },
  { cat: 'ai-career', d: 1, s: 'Un compañero junior usa IA y produce el mismo trabajo que tú en la mitad del tiempo. Sientes...', t: 'La productividad con IA es una habilidad nueva. Aprenderla te hace más valioso, no menos.', options: [{ text: 'Curiosidad: ¿qué herramientas usa y cómo puedo aprenderlas?', score: 100 }, { text: 'Resentimiento: la IA hace el trabajo desleal', score: -100 }, { text: 'Algo de preocupación pero no cambias nada', score: 0 }] },
  { cat: 'ai-career', d: 2, s: 'Te ofrecen un ascenso pero requiere gestionar equipos que trabajan con IA. Nunca lo has hecho. Tú...', t: 'Liderar equipos con IA es una competencia emergente muy valorada. El reto vale la pena.', options: [{ text: 'Aceptas y te formas en gestión de flujos de trabajo con IA', score: 100 }, { text: 'Rechazas porque no te sientes preparado', score: -100 }, { text: 'Pides tiempo para pensarlo sin comprometerte a formarte', score: 0 }] },
  { cat: 'ai-career', d: 2, s: 'Tu CV no menciona ninguna herramienta de IA pero la oferta de trabajo las requiere. Tú...', t: 'Las habilidades en IA se aprenden rápido. Mostrar disposición a aprender es tan valioso como la experiencia.', options: [{ text: 'Añades los cursos rápidos que hagas y destacas tu disposición a aprender', score: 100 }, { text: 'No aplicas porque no cumples el requisito', score: -100 }, { text: 'Aplicas sin mencionar el tema y esperas que no lo pregunten', score: 0 }] },
  { cat: 'ai-career', d: 2, s: 'Tu sector entero está adoptando IA a velocidad acelerada. Tu respuesta a largo plazo es...', t: 'La adaptabilidad es la habilidad más importante del siglo XXI. Aprender continuamente es la estrategia ganadora.', options: [{ text: 'Diseñar un plan de aprendizaje continuo enfocado en IA aplicada a tu campo', score: 100 }, { text: 'Esperar a que las herramientas maduren antes de invertir tiempo', score: -100 }, { text: 'Seguir igual y ver si el sector vuelve a estabilizarse', score: 0 }] },
  { cat: 'ai-career', d: 3, s: 'Un headhunter te dice que las empresas valoran "pensamiento crítico sobre IA" más que saber usarla. Tú...', t: 'Saber cuándo confiar en la IA, cuándo cuestionarla y cuándo descartarla es la meta-habilidad del futuro.', options: [{ text: 'Desarrollas criterio propio para evaluar outputs de IA con ojo experto', score: 100 }, { text: 'Asumes que las herramientas son fiables y no necesitas pensamiento crítico', score: -100 }, { text: 'Tomas nota pero no cambias tu forma de trabajar', score: 0 }] },
  { cat: 'ai-career', d: 1, s: 'Tu empresa paga cursos de IA. Tú...', t: 'La formación patrocinada es una inversión sin coste personal. Ignorarla es dejar dinero sobre la mesa.', options: [{ text: 'Te apuntas a los más relevantes para tu puesto inmediatamente', score: 100 }, { text: 'No te parece necesario — ya sabes hacer tu trabajo', score: -100 }, { text: 'Lo piensas pero nunca llegas a inscribirte', score: 0 }] },
  { cat: 'ai-career', d: 2, s: 'Ves que ex-compañeros que saben IA ganan un 30% más. Tú...', t: 'La brecha salarial por habilidades en IA ya es medible. Actuar ahora es más barato que recuperar terreno después.', options: [{ text: 'Priorizas aprender IA aplicada a tu rol en los próximos 3 meses', score: 100 }, { text: 'Asumes que los sueldos se nivelarán solos con el tiempo', score: -100 }, { text: 'Te interesa pero no sabes por dónde empezar y lo pospones', score: 0 }] },
  { cat: 'ai-career', d: 3, s: 'Te proponen convertirte en el "experto de IA" de tu equipo sin formación adicional ni aumento. Tú...', t: 'Ser referente en IA aporta visibilidad. Negocia las condiciones pero acepta el rol si hay margen.', options: [{ text: 'Aceptas negociando visibilidad y desarrollo profesional a cambio', score: 100 }, { text: 'Rechazas — no es tu trabajo si no lo pagan', score: -100 }, { text: 'Aceptas sin negociar nada y lo haces informalmente', score: 0 }] },
  { cat: 'ai-career', d: 2, s: 'Descubres que la IA puede hacer el 70% de tus tareas actuales. Tú...', t: 'Si la IA puede hacer el 70% de tu trabajo, tienes espacio para enfocarte en el 30% que más valor aporta.', options: [{ text: 'Rediseñas tu rol centrándote en el 30% de alta complejidad y juicio humano', score: 100 }, { text: 'Ocultas esta información para proteger tu puesto', score: -100 }, { text: 'Usas la IA para esas tareas pero no cambias tu descripción de rol', score: 0 }] },
  { cat: 'ai-career', d: 1, s: 'Un amigo dice que la IA es una burbuja y no vale la pena aprender. Tú...', t: 'La automatización cognitiva ya está transformando mercados reales. Esperar pruebas perfectas tiene coste de oportunidad.', options: [{ text: 'Analizas evidencias concretas del impacto en tu sector antes de decidir', score: 100 }, { text: 'Le crees y no inviertes tiempo en IA', score: -100 }, { text: 'Dudas pero tampoco actúas en ningún sentido', score: 0 }] },
  { cat: 'ai-career', d: 3, s: 'Te piden que lideres la transformación digital con IA de tu departamento sin guía clara. Tú...', t: 'Los proyectos de transformación sin hoja de ruta fracasan. Primero diagnóstico, luego diseño, luego ejecución.', options: [{ text: 'Propones un diagnóstico de procesos antes de elegir herramientas', score: 100 }, { text: 'Implementas las herramientas más conocidas sin análisis previo', score: -100 }, { text: 'Aceptas el encargo pero esperas instrucciones más claras antes de actuar', score: 0 }] },
  { cat: 'ai-career', d: 2, s: 'Un recruiter dice que poner "usuario de ChatGPT" en el CV ya no impresiona. Tú...', t: 'El mercado ya asume uso básico de IA. Lo que diferencia es la aplicación experta en un dominio concreto.', options: [{ text: 'Destacas casos de uso específicos con resultados medibles en tu CV', score: 100 }, { text: 'Quitas la mención — si no sirve, para qué ponerla', score: -100 }, { text: 'La dejas igual — algo vale', score: 0 }] },
  { cat: 'ai-career', d: 3, s: 'Te dan a elegir entre dos proyectos: uno seguro y conocido, otro piloto con IA sin garantías. Tú...', t: 'Los proyectos piloto con IA generan aprendizaje y visibilidad. El riesgo calculado construye carrera.', options: [{ text: 'Eliges el piloto con IA y documentas el aprendizaje independientemente del resultado', score: 100 }, { text: 'Eliges el seguro — no puedes arriesgar tu reputación', score: -100 }, { text: 'Preguntas qué elige tu jefe antes de decidir', score: 0 }] },

  // ai-communication (14)
  { cat: 'ai-communication', d: 1, s: 'Tienes que redactar un email importante. Usas IA para...', t: 'La IA es mejor para estructura y claridad; tú aportas contexto, relación y juicio sobre el tono adecuado.', options: [{ text: 'Obtener un borrador que luego personalizas con tu conocimiento del receptor', score: 100 }, { text: 'Enviar el output directamente sin revisión', score: -100 }, { text: 'Generar opciones pero no sabes cuál elegir y lo escribes tú igualmente', score: 0 }] },
  { cat: 'ai-communication', d: 2, s: 'Tu equipo usa IA para resumir reuniones. Un colega dice que los resúmenes pierden matices importantes. Tú...', t: 'Los resúmenes de IA capturan información explícita pero pierden subtext y acuerdos implícitos. Un protocolo híbrido es mejor.', options: [{ text: 'Propones un protocolo: IA hace el resumen base, una persona añade los matices clave', score: 100 }, { text: 'Defiendes la IA — si alguien no lo escribe, no existía', score: -100 }, { text: 'Aceptas el punto pero no cambias el proceso', score: 0 }] },
  { cat: 'ai-communication', d: 1, s: 'Necesitas comunicar una mala noticia a un cliente. Usas IA para...', t: 'Las malas noticias requieren empatía genuina. La IA puede estructurar el mensaje pero el tono humano es tuyo.', options: [{ text: 'Estructurar el mensaje y luego reescribirlo con empatía real', score: 100 }, { text: 'Enviar el texto de IA — es neutral y profesional', score: -100 }, { text: 'Pides a la IA que "suene empático" pero no revisas si lo logra', score: 0 }] },
  { cat: 'ai-communication', d: 2, s: 'Tu empresa adopta IA para responder clientes automáticamente. ¿Qué protocolo propones?', t: 'La automatización sin supervisión genera errores sin detectar. Un umbral de confianza con revisión humana es más seguro.', options: [{ text: 'IA responde preguntas simples; un humano revisa antes de enviar en casos complejos o sensibles', score: 100 }, { text: 'IA responde todo — es más rápido y consistente', score: -100 }, { text: 'Un humano revisa todo — la IA no puede encargarse de comunicación', score: 0 }] },
  { cat: 'ai-communication', d: 2, s: 'Descubres que un colega envía emails generados por IA sin revisarlos. Varios tienen errores de contexto. Tú...', t: 'Los errores de contexto en comunicaciones profesionales dañan relaciones. Un mínimo de revisión humana es necesario siempre.', options: [{ text: 'Lo comentas directamente y sugieres al menos una revisión rápida de 2 minutos', score: 100 }, { text: 'No es tu problema — cada uno gestiona su trabajo', score: -100 }, { text: 'Le dices algo pero sin insistir si no reacciona', score: 0 }] },
  { cat: 'ai-communication', d: 3, s: 'Te piden crear comunicaciones personalizadas para 5.000 clientes diferentes con IA. El reto de calidad es...', t: 'La personalización a escala requiere variables claras de segmentación. Sin ellas, la IA genera uniformidad disfrazada de personalización.', options: [{ text: 'Defines segmentos claros y variables de personalización antes de generar', score: 100 }, { text: 'Generas todo con el mismo prompt y cambias solo el nombre', score: -100 }, { text: 'Haces una prueba piloto con 50 pero no escales sin validar', score: 0 }] },
  { cat: 'ai-communication', d: 1, s: 'La IA te sugiere un tono más formal para tu email. Tú...', t: 'El tono apropiado depende de la relación y el contexto, no solo de la formalidad. Tú conoces al receptor; la IA no.', options: [{ text: 'Evalúas si el receptor prefiere ese tono antes de aplicarlo', score: 100 }, { text: 'Aplicas la sugerencia — la IA sabe más de comunicación que tú', score: -100 }, { text: 'La ignoras por defecto sin reflexionar', score: 0 }] },
  { cat: 'ai-communication', d: 2, s: 'Usas IA para traducir comunicaciones internas al inglés. ¿Cuál es tu mayor riesgo?', t: 'Las traducciones de IA son buenas para contenido neutro pero fallan con jerga interna, humor y referencias culturales.', options: [{ text: 'Que jerga interna o referencias culturales se pierdan o malinterpreten', score: 100 }, { text: 'Que la gramática sea incorrecta — ese es el único riesgo real', score: -100 }, { text: 'Que sea demasiado formal — lo revisas solo para el tono', score: 0 }] },
  { cat: 'ai-communication', d: 3, s: 'Un cliente pregunta si el email que recibió fue escrito por IA. ¿Qué respondes?', t: 'La transparencia sobre el uso de IA en comunicaciones genera confianza. Ocultarlo puede erosionarla si se descubre.', options: [{ text: 'Confirmas que usaste IA como herramienta y que revisaste el contenido personalmente', score: 100 }, { text: 'Niegas — podría parecer impersonal y afectar la relación', score: -100 }, { text: 'Evitas responder directamente la pregunta', score: 0 }] },
  { cat: 'ai-communication', d: 2, s: 'Tu manager te pide que prepares 20 presentaciones similares para distintas audiencias. Usas IA para...', t: 'Las plantillas con IA permiten escalar contenido. La diferencia está en los detalles específicos de cada audiencia.', options: [{ text: 'Crear una plantilla base y luego adaptar los detalles de cada audiencia', score: 100 }, { text: 'Generar las 20 con el mismo prompt y entregarlas sin personalizar', score: -100 }, { text: 'Hacer las primeras 3 a mano y la IA el resto sin revisar', score: 0 }] },
  { cat: 'ai-communication', d: 1, s: 'Quieres mejorar tu escritura profesional. ¿Cómo usas la IA?', t: 'La IA como herramienta de aprendizaje activo — compara tu escritura con sugerencias y entiende por qué — es más valiosa que delegarle toda la redacción.', options: [{ text: 'Escribes primero, pides feedback de la IA y aprendes de las diferencias', score: 100 }, { text: 'La IA escribe todo — así siempre sale bien', score: -100 }, { text: 'Usas la IA solo cuando tienes bloqueo creativo', score: 0 }] },
  { cat: 'ai-communication', d: 3, s: 'La IA de tu empresa tiene un sesgo cultural evidente en sus comunicaciones externas. Tú...', t: 'Los sesgos culturales en comunicaciones de IA son un riesgo de reputación real. Identificarlos y corregirlos es responsabilidad del equipo humano.', options: [{ text: 'Documentas los ejemplos, los escales internamente y propones revisión del sistema de prompts', score: 100 }, { text: 'Lo ignoras — el sesgo cultural es inevitable en IA', score: -100 }, { text: 'Corriges manualmente los casos que ves pero sin escalar', score: 0 }] },
  { cat: 'ai-communication', d: 2, s: 'Tienes que dar feedback negativo a un colaborador. La IA genera un texto muy suavizado. Tú...', t: 'El feedback efectivo debe ser claro y accionable. La IA tiende a suavizar para evitar conflicto — tú debes restaurar la claridad.', options: [{ text: 'Reescribes para que sea directo, específico y constructivo', score: 100 }, { text: 'Envías el texto suavizado — menos conflicto', score: -100 }, { text: 'Mezclas el texto de IA con algo tuyo pero sin estructura clara', score: 0 }] },
  { cat: 'ai-communication', d: 1, s: 'Usas IA para preparar un discurso. ¿Cuál es el paso más importante?', t: 'Un discurso tiene que sonar como tú. La autenticidad en la presentación oral requiere que internalices el contenido, no que lo leas.', options: [{ text: 'Reescribir en tu voz y practicarlo hasta que suene natural', score: 100 }, { text: 'Leer el texto de IA tal cual — está bien redactado', score: -100 }, { text: 'Memorizarlo palabra por palabra sin adaptarlo', score: 0 }] },

  // ai-cost-business (14)
  { cat: 'ai-cost-business', d: 1, s: 'Tu empresa quiere implementar IA para reducir costes. El primer paso debería ser...', t: 'Sin diagnóstico previo, la IA resuelve los problemas equivocados. Primero identifica los procesos con mayor coste e ineficiencia.', options: [{ text: 'Mapear procesos actuales e identificar dónde están los mayores costes e ineficiencias', score: 100 }, { text: 'Adquirir las herramientas de IA más populares del mercado', score: -100 }, { text: 'Pedir propuestas a varios proveedores antes de analizar internamente', score: 0 }] },
  { cat: 'ai-cost-business', d: 2, s: 'Una solución de IA cuesta 50.000€/año pero promete ahorrar 200.000€. ¿Cómo evalúas la inversión?', t: 'El ROI proyectado raramente se cumple al 100%. Evalúa los supuestos detrás de la cifra y haz un análisis conservador.', options: [{ text: 'Analizas los supuestos del ahorro prometido y calculas un escenario conservador', score: 100 }, { text: 'Apruebas directamente — el ROI es obvio', score: -100 }, { text: 'Rechazas porque las promesas de proveedores son siempre exageradas', score: 0 }] },
  { cat: 'ai-cost-business', d: 2, s: 'El coste de licencias de IA está aumentando. Tu empresa debe decidir si renovar o cambiar de proveedor. Tú...', t: 'Los costes de cambio de proveedor (integración, formación, migración) pueden superar el ahorro en licencias. Hay que calcularlos.', options: [{ text: 'Calculas el coste total de cambio incluyendo migración y curva de aprendizaje', score: 100 }, { text: 'Cambias al más barato — el coste de licencia es lo único que importa', score: -100 }, { text: 'Renuevas automáticamente porque el cambio es demasiado complejo', score: 0 }] },
  { cat: 'ai-cost-business', d: 1, s: 'Un empleado tarda 10 horas en una tarea que la IA hace en 1 hora. ¿Qué haces con las 9 horas liberadas?', t: 'La IA libera tiempo; la pregunta estratégica es en qué reinvertirlo para crear más valor. No es solo eficiencia, es redirección.', options: [{ text: 'Reasignas al empleado a tareas de mayor valor que la IA no puede hacer', score: 100 }, { text: 'Reduces headcount — si la IA hace el trabajo, no necesitas a la persona', score: -100 }, { text: 'Dejas que el empleado decida qué hace con su tiempo libre', score: 0 }] },
  { cat: 'ai-cost-business', d: 3, s: 'Tu CEO quiere saber el ROI de la inversión en IA del último año. ¿Qué métricas presentas?', t: 'El ROI de IA incluye tiempo ahorrado, calidad mejorada, errores evitados y nuevas capacidades. Solo costes directos es una visión incompleta.', options: [{ text: 'Tiempo ahorrado valorado en horas, reducción de errores y nuevas capacidades habilitadas', score: 100 }, { text: 'Solo coste de licencias vs. reducción de headcount', score: -100 }, { text: 'Presentas satisfacción del equipo como métrica principal', score: 0 }] },
  { cat: 'ai-cost-business', d: 2, s: 'Una startup competidora con menos personal produce el mismo volumen que tu empresa con IA. Tu respuesta es...', t: 'La asimetría de capacidad por IA es una señal de alarma estratégica, no solo operativa. Requiere respuesta sistémica.', options: [{ text: 'Analizar su stack de IA y diseñar un plan de adopción comparable', score: 100 }, { text: 'Contratar más personal para compensar', score: -100 }, { text: 'Esperar a ver si su modelo es sostenible', score: 0 }] },
  { cat: 'ai-cost-business', d: 1, s: 'Tienes presupuesto limitado para IA. ¿En qué lo inviertes primero?', t: 'El mayor ROI temprano viene de automatizar tareas repetitivas de alto volumen. Los proyectos complejos requieren madurez en IA.', options: [{ text: 'En automatizar los procesos repetitivos de mayor volumen', score: 100 }, { text: 'En el proyecto más innovador aunque sea de bajo volumen', score: -100 }, { text: 'En formación del equipo antes de cualquier herramienta', score: 0 }] },
  { cat: 'ai-cost-business', d: 3, s: 'La IA de atención al cliente redujo costes pero también bajó la satisfacción del cliente. Tú...', t: 'Optimizar solo costes sin medir impacto en experiencia del cliente destruye valor a largo plazo. Las métricas deben estar conectadas.', options: [{ text: 'Redefines el caso de negocio incluyendo LTV del cliente como variable', score: 100 }, { text: 'Priorizas el ahorro — el coste es más fácil de medir que la satisfacción', score: -100 }, { text: 'Vuelves al modelo anterior sin analizar qué falló', score: 0 }] },
  { cat: 'ai-cost-business', d: 2, s: 'Tu equipo de finanzas quiere IA para proyecciones. ¿Cuál es el riesgo principal?', t: 'La IA proyecta basándose en patrones históricos. En entornos de alta incertidumbre o cambio estructural, esos patrones pueden ser engañosos.', options: [{ text: 'Que los modelos sobreajusten datos históricos y fallen en escenarios de ruptura', score: 100 }, { text: 'Que sea demasiado cara para el equipo de finanzas', score: -100 }, { text: 'Que los analistas no quieran usarla por miedo a perder relevancia', score: 0 }] },
  { cat: 'ai-cost-business', d: 1, s: 'Descubres que tu empresa paga por 5 herramientas de IA con funciones solapadas. Tú...', t: 'La redundancia en el stack de IA desperdicia presupuesto. Un audit periódico de herramientas es buena práctica.', options: [{ text: 'Haces un audit de uso real y propones consolidar en las más usadas', score: 100 }, { text: 'Mantienes todas — nunca sabes cuándo necesitarás cada una', score: -100 }, { text: 'Cancelas las más caras sin analizar cuáles se usan más', score: 0 }] },
  { cat: 'ai-cost-business', d: 3, s: 'El CFO te pregunta cómo justificar ante el consejo una inversión en IA sin ROI inmediato. Tú...', t: 'Las inversiones estratégicas en IA construyen capacidad diferencial. El argumento ante el consejo debe mezclar datos actuales y opcionalidad futura.', options: [{ text: 'Presentas quick wins medibles y el caso estratégico de capacidad a largo plazo', score: 100 }, { text: 'Le dices que espere hasta tener ROI claro — no puedes justificar sin datos', score: -100 }, { text: 'Usas benchmarks de competidores sin adaptarlos a tu contexto', score: 0 }] },
  { cat: 'ai-cost-business', d: 2, s: 'Un proveedor de IA dice que su herramienta "se paga sola en 3 meses". Tú...', t: 'Las afirmaciones de payback muy rápido suelen ignorar costes ocultos de implementación, formación y mantenimiento.', options: [{ text: 'Pides el detalle de los supuestos y los validas con tu propio contexto', score: 100 }, { text: 'Lo crees — tienen casos de éxito documentados', score: -100 }, { text: 'Lo rechazas de entrada — ninguna herramienta se paga en 3 meses', score: 0 }] },
  { cat: 'ai-cost-business', d: 1, s: 'La IA ha reducido un proceso de 5 días a 1. ¿Qué comunicas al equipo?', t: 'Comunicar la ganancia de productividad con IA como oportunidad, no como amenaza, determina la adopción cultural del equipo.', options: [{ text: 'Que el equipo puede dedicar los 4 días liberados a proyectos de mayor impacto', score: 100 }, { text: 'Que el departamento necesita menos personas ahora', score: -100 }, { text: 'Nada — la mejora habla por sí sola', score: 0 }] },
  { cat: 'ai-cost-business', d: 3, s: 'Tu empresa usa IA generativa para producir contenido de marketing. Los costes por pieza han bajado 80% pero la calidad percibida también. Tú...', t: 'El coste por pieza no es la única métrica. El coste por resultado (lead, conversión) es lo que importa para marketing.', options: [{ text: 'Analizas el impacto en conversiones y rediseñas el proceso de revisión humana', score: 100 }, { text: 'Aceptas la baja calidad — el ahorro compensa', score: -100 }, { text: 'Vuelves a producción manual para todo el contenido', score: 0 }] },

  // ai-customer-service (14)
  { cat: 'ai-customer-service', d: 1, s: 'Tu empresa implementa un chatbot de IA para atención al cliente. ¿Cuál es el error más común a evitar?', t: 'Los chatbots sin salida humana clara frustran a los clientes cuando el problema es complejo. El escalado fluido es crítico.', options: [{ text: 'No diseñar un proceso claro de escalado a agentes humanos', score: 100 }, { text: 'Entrenar el chatbot con demasiados datos', score: -100 }, { text: 'Usar lenguaje demasiado formal en las respuestas', score: 0 }] },
  { cat: 'ai-customer-service', d: 2, s: 'Un cliente furioso prefiere hablar con una persona en lugar del chatbot. Tu protocolo debe...', t: 'La preferencia del cliente por atención humana debe respetarse. Forzar IA cuando el cliente la rechaza daña la relación.', options: [{ text: 'Permitir el escalado inmediato a un agente humano sin fricción', score: 100 }, { text: 'Insistir en el chatbot — es más eficiente y resuelve el 90% de casos', score: -100 }, { text: 'Ofrecer un formulario en lugar de un agente — es el siguiente paso del proceso', score: 0 }] },
  { cat: 'ai-customer-service', d: 1, s: 'La IA de atención al cliente da una respuesta incorrecta a un cliente. ¿Qué proceso activas?', t: 'Los errores de IA en atención al cliente requieren corrección inmediata, disculpa y actualización del sistema para evitar recurrencia.', options: [{ text: 'Corriges al cliente, te disculpas y actualizas la base de conocimiento', score: 100 }, { text: 'Dices al cliente que la IA cometió un error — no es tu responsabilidad', score: -100 }, { text: 'Corriges al cliente pero no documentas el error', score: 0 }] },
  { cat: 'ai-customer-service', d: 2, s: 'Quieres medir si la IA de atención al cliente está funcionando. ¿Qué métricas usas?', t: 'Las métricas de atención al cliente con IA deben cubrir eficiencia (tiempo de resolución), calidad (CSAT) y riesgo (tasa de escalado).', options: [{ text: 'Tiempo de resolución, tasa de escalado y satisfacción post-interacción', score: 100 }, { text: 'Solo el número de interacciones gestionadas', score: -100 }, { text: 'Solo la satisfacción del cliente — es lo único que importa', score: 0 }] },
  { cat: 'ai-customer-service', d: 3, s: 'La IA gestiona el 80% de consultas pero el 20% más complejo satura a los agentes humanos. Tu solución es...', t: 'La distribución 80/20 es eficiente pero puede crear un cuello de botella humano si los casos complejos se concentran. Hay que rediseñar el flujo.', options: [{ text: 'Ampliar las capacidades de la IA para casos intermedios y reforzar el equipo humano para los más complejos', score: 100 }, { text: 'Reducir el umbral de escalado para que la IA gestione más casos', score: -100 }, { text: 'Contratar más agentes para el 20% — es un problema de capacidad', score: 0 }] },
  { cat: 'ai-customer-service', d: 2, s: 'Detectas que la IA de atención al cliente tiene un sesgo contra consultas en ciertos idiomas. Tú...', t: 'El sesgo lingüístico en atención al cliente discrimina a clientes por su idioma. Es un problema ético y de negocio que requiere acción inmediata.', options: [{ text: 'Documentas los casos, lo escalas internamente y pausas el uso en esos idiomas hasta corregirlo', score: 100 }, { text: 'Lo dejas pasar — es un problema menor de calidad', score: -100 }, { text: 'Añades un aviso de que el servicio es mejor en el idioma principal', score: 0 }] },
  { cat: 'ai-customer-service', d: 1, s: 'Tu empresa quiere usar IA para anticipar problemas del cliente antes de que los reporte. ¿Cuál es el primer paso?', t: 'La atención proactiva requiere datos de comportamiento del cliente. Sin datos de calidad, la IA no puede anticipar nada útil.', options: [{ text: 'Identificar las señales de datos que predicen los problemas más comunes', score: 100 }, { text: 'Implementar una IA predictiva y ver qué detecta', score: -100 }, { text: 'Preguntar a los agentes qué problemas se repiten más', score: 0 }] },
  { cat: 'ai-customer-service', d: 3, s: 'Un cliente VIP se queja de que la IA no entiende su situación particular. Tú...', t: 'Los clientes VIP suelen tener casos complejos o históricos que la IA no puede contextualizar. La atención personalizada humana debe estar disponible para ellos.', options: [{ text: 'Asignas un agente humano dedicado y revisas si el segmento VIP necesita un flujo diferenciado', score: 100 }, { text: 'Mejoras el prompt de la IA para ese tipo de caso', score: -100 }, { text: 'Le explicas que la IA funciona bien para el 95% de los clientes', score: 0 }] },
  { cat: 'ai-customer-service', d: 2, s: 'La IA de soporte resuelve los tickets un 60% más rápido pero los clientes dan peores valoraciones. ¿Por qué?', t: 'La velocidad sin calidad percibida no genera satisfacción. Los clientes valoran sentirse escuchados, no solo obtener una respuesta rápida.', options: [{ text: 'Porque la velocidad no compensa la falta de empatía y personalización en la respuesta', score: 100 }, { text: 'Porque los clientes no saben apreciar la eficiencia', score: -100 }, { text: 'Porque la IA comete más errores que los agentes humanos', score: 0 }] },
  { cat: 'ai-customer-service', d: 1, s: '¿En qué tipo de consultas añade más valor la IA en atención al cliente?', t: 'La IA brilla en consultas repetitivas y bien definidas. Los casos únicos, emocionales o de alta complejidad necesitan humanos.', options: [{ text: 'Consultas repetitivas con respuestas bien definidas como FAQs y rastreo de pedidos', score: 100 }, { text: 'Reclamaciones emocionales de clientes insatisfechos', score: -100 }, { text: 'Negociaciones de precio o condiciones personalizadas', score: 0 }] },
  { cat: 'ai-customer-service', d: 3, s: 'Tu IA de atención al cliente tiene acceso a datos sensibles del cliente. ¿Qué controles implementas?', t: 'La IA con acceso a datos sensibles requiere principio de mínimo privilegio: solo accede a lo necesario para responder la consulta específica.', options: [{ text: 'Acceso mínimo necesario, logs de auditoría y revisión periódica de permisos', score: 100 }, { text: 'Acceso completo — para personalizar mejor necesita toda la información', score: -100 }, { text: 'Sin acceso a datos — prefiero que pida la información al cliente cada vez', score: 0 }] },
  { cat: 'ai-customer-service', d: 2, s: 'Los agentes humanos dicen que la IA les quita los casos fáciles y les deja solo los difíciles. Tú...', t: 'La distribución asimétrica de carga puede desmotivar a los agentes. El diseño del flujo debe equilibrar volumen y variedad.', options: [{ text: 'Rediseñas el flujo para que los agentes mantengan variedad de casos y no solo los más difíciles', score: 100 }, { text: 'Les dices que se centren en lo que la IA no puede hacer — eso es más valioso', score: -100 }, { text: 'Aumentas su salario para compensar la mayor dificultad de los casos', score: 0 }] },
  { cat: 'ai-customer-service', d: 1, s: '¿Cuándo debe la IA decir explícitamente que es una IA?', t: 'La transparencia sobre el uso de IA en atención al cliente es una expectativa ética y en muchos países un requisito legal emergente.', options: [{ text: 'Siempre que el cliente lo pregunte o cuando empiece la interacción si hay regulación', score: 100 }, { text: 'Nunca — es mejor que el cliente piense que habla con una persona', score: -100 }, { text: 'Solo cuando cometa errores — así el cliente entiende por qué', score: 0 }] },
  { cat: 'ai-customer-service', d: 3, s: 'Tu empresa quiere usar IA para predecir qué clientes están en riesgo de abandonar. ¿Cuál es el dato más valioso?', t: 'El comportamiento reciente (cambios en uso, frecuencia de contacto, quejas) predice mejor el churn que los datos demográficos estáticos.', options: [{ text: 'Cambios recientes en el patrón de uso y frecuencia de contacto con soporte', score: 100 }, { text: 'Edad y localización del cliente', score: -100 }, { text: 'Número total de compras históricas', score: 0 }] },
]

console.log('Total:', ALL.length, 'questions')
for (let i = 0; i < ALL.length; i += 20) {
  await insert(ALL.slice(i, i + 20))
}
