const TOKEN = 'sbp_f314cf27b5b2a01eea48048a7b1c015cc9cf4b42'
const API = 'https://api.supabase.com/v1/projects/amhfxaqolholacanqyas/database/query'
function esc(s) { return s.replace(/'/g, "''") }
async function insert(batch) {
  const values = batch.map(q => {
    const opts = JSON.stringify(q.options).replace(/'/g, "''")
    return `('es','${q.cat}','${esc(q.s)}','${esc(q.t)}','${opts}'::jsonb,${q.d},'claude',true)`
  }).join(',')
  const sql = `INSERT INTO questions (locale,category,scenario_text,mindset_tip,options,difficulty,generated_by,is_active) VALUES ${values};`
  const r = await fetch(API, {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${TOKEN}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query: sql })
  })
  const d = await r.json()
  if (d.message) { console.error('ERR:', d.message); return false }
  console.log('OK:', batch.length, 'inserted')
  return true
}

const ALL = [
  // ai-law-regulation (14)
  { cat: 'ai-law-regulation', d: 1, s: 'Tu empresa quiere lanzar un producto de IA en Europa. ¿Qué regulación debes conocer primero?', t: 'El AI Act europeo clasifica sistemas de IA por nivel de riesgo. Conocerlo determina qué requisitos de conformidad, documentación y supervisión aplican.', options: [{ text: 'El AI Act europeo y su clasificación de sistemas por nivel de riesgo', score: 100 }, { text: 'Solo el GDPR — la privacidad es el único marco relevante', score: -100 }, { text: 'Las regulaciones se conocen cuando el regulador las aplica, no antes', score: 0 }] },
  { cat: 'ai-law-regulation', d: 2, s: 'La IA de tu empresa toma decisiones sobre empleados (evaluaciones, ascensos). ¿Qué derechos tienen?', t: 'Las decisiones automatizadas con impacto significativo en personas tienen regulación específica en Europa: derecho a explicación y revisión humana.', options: [{ text: 'Derecho a explicación de la decisión y a revisión humana de la misma', score: 100 }, { text: 'Ninguno especial — la IA decide igual que un humano', score: -100 }, { text: 'Solo el derecho a conocer que existe un sistema automatizado', score: 0 }] },
  { cat: 'ai-law-regulation', d: 2, s: 'Tu empresa entrena un modelo de IA con datos de clientes. ¿Qué base legal necesitas?', t: 'El uso de datos personales para entrenamiento de IA requiere base legal válida bajo GDPR: consentimiento explícito, interés legítimo o contrato, con documentación adecuada.', options: [{ text: 'Base legal válida bajo GDPR: consentimiento explícito o interés legítimo documentado', score: 100 }, { text: 'Ninguna — los datos propios se pueden usar libremente', score: -100 }, { text: 'Solo una cláusula genérica en los términos de uso', score: 0 }] },
  { cat: 'ai-law-regulation', d: 3, s: 'Una IA de contratación rechaza sistemáticamente a candidatos de cierta edad. Tu responsabilidad legal es...', t: 'La discriminación por IA en contratación es discriminación laboral ilegal aunque sea indirecta o no intencionada. La empresa es responsable del sistema que usa.', options: [{ text: 'Plena responsabilidad: debes auditar el sistema y corregir el sesgo de inmediato', score: 100 }, { text: 'Ninguna — la IA decidió de forma autónoma', score: -100 }, { text: 'Responsabilidad compartida con el proveedor de la IA', score: 0 }] },
  { cat: 'ai-law-regulation', d: 2, s: 'Quieres usar una IA generativa en tu producto. El contenido que genera puede incluir datos de terceros. Riesgo es...', t: 'Los modelos generativos pueden reproducir datos de entrenamiento protegidos por derechos de autor. Las empresas deben revisar sus acuerdos de uso y las licencias de los datos generados.', options: [{ text: 'Infracción de derechos de autor si el modelo reproduce contenido protegido', score: 100 }, { text: 'Ninguno — el contenido generado es siempre nuevo y libre de derechos', score: -100 }, { text: 'Solo riesgo reputacional si el contenido es inapropiado', score: 0 }] },
  { cat: 'ai-law-regulation', d: 1, s: 'El AI Act clasifica tu sistema de IA como "alto riesgo". ¿Qué obligaciones principales tienes?', t: 'Los sistemas de alto riesgo bajo el AI Act requieren documentación técnica, gestión de riesgos, supervisión humana y registro en la base de datos de la UE.', options: [{ text: 'Documentación técnica, gestión de riesgos, supervisión humana y registro en base de datos UE', score: 100 }, { text: 'Solo informar al usuario de que el sistema usa IA', score: -100 }, { text: 'Obtener certificación de cualquier empresa auditora', score: 0 }] },
  { cat: 'ai-law-regulation', d: 3, s: 'Tu IA comete un error que causa daño a un cliente. El marco legal actual para responsabilidad de IA en Europa es...', t: 'La regulación de responsabilidad civil por IA en Europa está evolucionando. La AI Liability Directive propone inversión de la carga de la prueba en ciertos casos de alto riesgo.', options: [{ text: 'Marco en evolución con la AI Liability Directive proponiendo nuevas reglas de responsabilidad', score: 100 }, { text: 'La IA no puede ser demandada — solo el fabricante del hardware', score: -100 }, { text: 'Las leyes actuales de producto defectuoso cubren todos los casos', score: 0 }] },
  { cat: 'ai-law-regulation', d: 2, s: 'Tu empresa usa IA para analizar el sentimiento en las redes sociales de tus empleados. ¿Es legal?', t: 'La monitorización del comportamiento online de empleados tiene límites legales estrictos relacionados con privacidad y proporcionalidad, incluso en contexto laboral.', options: [{ text: 'Depende de la jurisdicción, el alcance y si existe base legal proporcional y comunicada', score: 100 }, { text: 'Sí — los empleados usan redes públicas y la empresa puede monitorizar lo público', score: -100 }, { text: 'No — nunca es legal monitorizar empleados', score: 0 }] },
  { cat: 'ai-law-regulation', d: 1, s: 'Un proveedor de IA dice que sus datos de entrenamiento son "de dominio público". ¿Debes confiar?', t: 'El dominio público es una categoría legal compleja y varía por jurisdicción. Datos públicos pueden tener restricciones de uso comercial o derechos morales activos.', options: [{ text: 'Verificar la documentación de licencias antes de asumir uso libre', score: 100 }, { text: 'Sí — si son públicos, son libres de usar', score: -100 }, { text: 'No usar nunca datos de terceros para evitar riesgos', score: 0 }] },
  { cat: 'ai-law-regulation', d: 3, s: 'Quieres desplegar IA en un sector regulado (banca, salud, seguros). Tu estrategia regulatoria es...', t: 'Los sectores regulados tienen marcos específicos que se superponen al AI Act. La coordinación con el regulador sectorial desde el diseño evita problemas de conformidad tardíos.', options: [{ text: 'Identificar el marco sectorial específico y coordinarte con el regulador desde el diseño', score: 100 }, { text: 'Desplegar primero y adaptar si el regulador requiere cambios', score: -100 }, { text: 'Aplicar solo los requisitos generales del AI Act', score: 0 }] },
  { cat: 'ai-law-regulation', d: 2, s: 'La IA de tu empresa usa "perfilado" de usuarios para personalizar contenido. ¿Qué derechos GDPR aplican?', t: 'El perfilado bajo GDPR requiere base legal, derecho de oposición y, si tiene efectos significativos, derecho a no ser objeto de decisión exclusivamente automatizada.', options: [{ text: 'Derecho de oposición al perfilado y a no ser objeto de decisiones exclusivamente automatizadas', score: 100 }, { text: 'Ninguno — el perfilado es una práctica de marketing estándar', score: -100 }, { text: 'Solo el derecho de acceso a los datos usados', score: 0 }] },
  { cat: 'ai-law-regulation', d: 1, s: 'Tu startup desarrolla una IA. ¿Cuándo debes pensar en cumplimiento legal?', t: 'El cumplimiento legal en IA es más barato de integrar desde el diseño que de añadir después. El "privacy by design" y el "ethics by design" son principios del AI Act.', options: [{ text: 'Desde el inicio del diseño — es más fácil y barato que añadirlo después', score: 100 }, { text: 'Cuando el producto esté listo para lanzar', score: -100 }, { text: 'Solo si el regulador te lo pide explícitamente', score: 0 }] },
  { cat: 'ai-law-regulation', d: 3, s: 'El AI Act prohíbe algunos usos de IA completamente. ¿Cuáles son ejemplos de usos prohibidos?', t: 'El AI Act prohíbe sistemas de puntuación social generalizada, manipulación subliminal, identificación biométrica en tiempo real en espacios públicos por fuerzas de seguridad (con excepciones), y explotación de vulnerabilidades de grupos específicos.', options: [{ text: 'Puntuación social gubernamental, manipulación subliminal y explotación de vulnerabilidades de grupos', score: 100 }, { text: 'Sistemas de recomendación de contenido y reconocimiento de voz', score: -100 }, { text: 'Todo uso de datos biométricos sin excepción', score: 0 }] },
  { cat: 'ai-law-regulation', d: 2, s: 'Tu empresa quiere usar watermarking para identificar contenido generado por IA. ¿Por qué es importante?', t: 'El watermarking de contenido generado por IA es un requisito emergente de transparencia bajo el AI Act para grandes modelos. Previene desinformación y manipulación.', options: [{ text: 'Es un requisito de transparencia del AI Act y previene el uso malicioso del contenido', score: 100 }, { text: 'Es solo una buena práctica opcional de responsabilidad corporativa', score: -100 }, { text: 'Solo importa para contenido audiovisual, no para texto', score: 0 }] },

  // ai-leadership (14)
  { cat: 'ai-leadership', d: 1, s: 'Como directivo, tu equipo teme que la IA elimine sus puestos. Tu primer paso es...', t: 'El miedo a la IA se alimenta de la incertidumbre. La comunicación transparente sobre qué va a cambiar y qué no reduce la ansiedad y mejora la adopción.', options: [{ text: 'Comunicar con honestidad qué cambiará y cómo el equipo se verá afectado', score: 100 }, { text: 'Minimizar el tema para que no cunda el pánico', score: -100 }, { text: 'Esperar a que los cambios se implementen y gestionar las reacciones', score: 0 }] },
  { cat: 'ai-leadership', d: 2, s: 'Tu organización adopta IA pero los mandos intermedios bloquean la implementación. ¿Por qué ocurre y cómo lo gestionas?', t: 'Los mandos intermedios bloquean la IA cuando sienten que amenaza su rol de coordinación. Redefinir su valor en el nuevo contexto es la solución, no forzar la adopción.', options: [{ text: 'Involucras a los mandos en el diseño y les muestras cómo la IA potencia su liderazgo', score: 100 }, { text: 'Implementas desde arriba y les obligas a adaptarse', score: -100 }, { text: 'Les das más tiempo para adaptarse sin apoyo adicional', score: 0 }] },
  { cat: 'ai-leadership', d: 2, s: 'Como líder, ¿cómo tomas decisiones estratégicas con IA de apoyo?', t: 'La IA aporta análisis de datos; el liderazgo aporta contexto, valores y responsabilidad. La decisión final integra ambos, con el líder como último responsable.', options: [{ text: 'Usas la IA para análisis y escenarios pero la decisión integra tu juicio y valores', score: 100 }, { text: 'Sigues la recomendación de la IA si está respaldada por datos suficientes', score: -100 }, { text: 'Ignoras la IA para decisiones estratégicas — es para operaciones', score: 0 }] },
  { cat: 'ai-leadership', d: 3, s: 'La IA de tu empresa genera una recomendación que va contra tu intuición de liderazgo. Tú...', t: 'La tensión entre análisis de IA e intuición de liderazgo es productiva. La clave es articular por qué difieren y qué información tiene cada uno que el otro no tiene.', options: [{ text: 'Articulas por qué difieren y decides con transparencia sobre qué pesa más en este contexto', score: 100 }, { text: 'Sigues tu intuición — tienes más experiencia que cualquier algoritmo', score: -100 }, { text: 'Sigues la IA — si tienes buena IA, debes confiar en ella', score: 0 }] },
  { cat: 'ai-leadership', d: 1, s: 'Quieres crear una cultura de experimentación con IA en tu equipo. ¿Qué haces primero?', t: 'La cultura de experimentación con IA requiere seguridad psicológica: que el error en el experimento sea aprendizaje, no fracaso penalizable.', options: [{ text: 'Crear un entorno donde los experimentos fallidos sean aprendizaje valorado', score: 100 }, { text: 'Asignar un presupuesto de IA y pedir resultados en 30 días', score: -100 }, { text: 'Comprar las herramientas de IA más recomendadas y formarlo obligatoriamente', score: 0 }] },
  { cat: 'ai-leadership', d: 2, s: 'Tu empresa invierte en IA pero los líderes senior no la usan ellos mismos. ¿Qué impacto tiene?', t: 'El liderazgo por ejemplo es la señal cultural más poderosa. Si los líderes no usan la IA, el mensaje implícito es que no es realmente importante.', options: [{ text: 'Manda una señal cultural negativa que frena la adopción en toda la organización', score: 100 }, { text: 'Ninguno — los líderes tienen otros roles que no requieren IA', score: -100 }, { text: 'Es un problema de comunicación interna, no de liderazgo', score: 0 }] },
  { cat: 'ai-leadership', d: 3, s: 'La IA propone reorganizar tu departamento de forma que elimina 3 roles actuales. Tú...', t: 'Las reorganizaciones basadas en IA deben evaluarse con criterios humanos: impacto en personas, conocimiento tácito perdido y alternativas de recolocación.', options: [{ text: 'Analizas el impacto humano, exploras alternativas de recolocación y decides con datos completos', score: 100 }, { text: 'Implementas la propuesta — la IA optimiza mejor que la intuición', score: -100 }, { text: 'Rechazas cualquier reorganización que elimine roles existentes', score: 0 }] },
  { cat: 'ai-leadership', d: 2, s: 'Tu equipo de liderazgo pide métricas de rendimiento de la IA. ¿Qué presentas?', t: 'Las métricas de IA para el equipo directivo deben conectar con objetivos de negocio: impacto en ingresos, costes, calidad y capacidades nuevas, no solo métricas técnicas.', options: [{ text: 'Impacto en ingresos, costes, calidad de decisiones y nuevas capacidades habilitadas', score: 100 }, { text: 'Número de procesos automatizados y velocidad de respuesta del sistema', score: -100 }, { text: 'Satisfacción del equipo técnico con las herramientas', score: 0 }] },
  { cat: 'ai-leadership', d: 1, s: 'Eres líder y no entiendes bien cómo funciona la IA. ¿Cuál es tu responsabilidad?', t: 'Los líderes no necesitan saber programar IA, pero sí entender suficientemente cómo funciona para hacer buenas preguntas, evaluar riesgos y tomar decisiones informadas.', options: [{ text: 'Adquirir comprensión suficiente para hacer buenas preguntas y evaluar riesgos', score: 100 }, { text: 'Delegarlo todo en el equipo técnico — eso es para lo que están', score: -100 }, { text: 'Anunciar que apoyas la IA sin entrar en detalles técnicos', score: 0 }] },
  { cat: 'ai-leadership', d: 3, s: 'Un competidor usa IA para lanzar productos 3x más rápido. Tu respuesta como líder es...', t: 'La ventaja competitiva de un rival en velocidad con IA requiere respuesta sistémica: no solo herramientas, sino procesos, cultura y gobernanza que permitan esa velocidad.', options: [{ text: 'Diagnosticar qué combinación de procesos, herramientas y cultura permite esa velocidad', score: 100 }, { text: 'Comprar las mismas herramientas de IA que usan ellos', score: -100 }, { text: 'Esperar a ver si su ventaja se sostiene antes de invertir', score: 0 }] },
  { cat: 'ai-leadership', d: 2, s: 'Como líder, ¿cómo gestionas el talento que no quiere adoptar IA?', t: 'La resistencia a la IA suele tener raíces en miedo o falta de comprensión. La intervención efectiva es educación y demostración de valor, no imposición.', options: [{ text: 'Entiendes las razones de la resistencia y ofreces apoyo específico de formación', score: 100 }, { text: 'Pones un ultimátum: adoptar o buscar otro rol', score: -100 }, { text: 'Dejas que cada uno decida — no puedes forzar el cambio cultural', score: 0 }] },
  { cat: 'ai-leadership', d: 1, s: 'Tu empresa tiene un comité de ética de IA. ¿Cuál es su rol más importante?', t: 'El comité de ética de IA no es un freno sino un acelerador: identifica riesgos antes de que se conviertan en problemas y construye confianza interna y externa en el uso de IA.', options: [{ text: 'Identificar riesgos de sesgo, privacidad y equidad antes de que se conviertan en problemas', score: 100 }, { text: 'Aprobar formalmente todos los proyectos de IA — es un control de calidad', score: -100 }, { text: 'Comunicar externamente las iniciativas de IA responsable', score: 0 }] },
  { cat: 'ai-leadership', d: 3, s: 'El consejo de administración te pregunta cuál es la estrategia de IA de tu empresa. Tú...', t: 'Una estrategia de IA para el consejo debe conectar inversión con ventaja competitiva, riesgos gestionados y capacidades nuevas — no ser una lista de herramientas.', options: [{ text: 'Presentas cómo la IA conecta con la ventaja competitiva, los riesgos y las capacidades nuevas', score: 100 }, { text: 'Listas las herramientas de IA que ya usas', score: -100 }, { text: 'Describes los proyectos piloto en curso sin estrategia de escalado', score: 0 }] },
  { cat: 'ai-leadership', d: 2, s: 'La IA de gestión de proyectos predice que un proyecto clave fracasará. El equipo no lo cree. Tú...', t: 'Las predicciones de IA sobre proyectos en curso deben compartirse con el equipo para discutir los supuestos — no imponerse como verdad ni ignorarse como "solo un algoritmo".', options: [{ text: 'Compartes la predicción con el equipo, discutes los supuestos y revisáis el plan juntos', score: 100 }, { text: 'Cancelas el proyecto — si la IA lo predice, hay que confiar', score: -100 }, { text: 'Ignoras la predicción — el equipo tiene más contexto que la IA', score: 0 }] },

  // ai-manufacturing (14)
  { cat: 'ai-manufacturing', d: 1, s: 'Tu planta quiere usar IA para mantenimiento predictivo. ¿Por dónde empiezas?', t: 'El mantenimiento predictivo con IA requiere datos históricos de fallos y sensores en tiempo real. Sin ellos, la IA no tiene base para predecir nada útil.', options: [{ text: 'Inventariando los datos de sensores disponibles y el historial de fallos', score: 100 }, { text: 'Comprando la plataforma de IA predictiva más avanzada del mercado', score: -100 }, { text: 'Formando al equipo de mantenimiento en IA antes de tener herramientas', score: 0 }] },
  { cat: 'ai-manufacturing', d: 2, s: 'La IA de control de calidad rechaza el 15% de las piezas pero los operarios creen que algunas son válidas. Tú...', t: 'Las divergencias entre la IA y el criterio experto humano en control de calidad son información valiosa. Pueden indicar un mal calibrado del modelo o conocimiento tácito no capturado.', options: [{ text: 'Analizas los casos en disputa con el equipo para ajustar el modelo o las reglas', score: 100 }, { text: 'Confías en la IA — los operarios tienen sesgos subjetivos', score: -100 }, { text: 'Confías en los operarios — el criterio humano experto siempre supera la IA', score: 0 }] },
  { cat: 'ai-manufacturing', d: 2, s: 'Un robot con IA en tu línea de producción genera un incidente de seguridad. ¿Quién es responsable?', t: 'La responsabilidad en incidentes de sistemas autónomos industriales es del operador del sistema, que debe garantizar supervisión, mantenimiento y protocolos de seguridad adecuados.', options: [{ text: 'La empresa operadora del sistema: debe garantizar supervisión y protocolos de seguridad', score: 100 }, { text: 'El fabricante del robot — él diseñó el sistema', score: -100 }, { text: 'La IA es responsable — tomó la decisión de forma autónoma', score: 0 }] },
  { cat: 'ai-manufacturing', d: 1, s: 'La IA optimiza el tiempo de ciclo de producción. ¿Cuál es el primer efecto que debes medir?', t: 'La optimización de tiempo de ciclo puede crear cuellos de botella aguas abajo si otros procesos no escalan. El primer efecto a medir es el impacto en el sistema completo.', options: [{ text: 'Si la ganancia en esta etapa crea cuellos de botella en etapas siguientes', score: 100 }, { text: 'El ahorro de tiempo en el proceso optimizado únicamente', score: -100 }, { text: 'La satisfacción del operario con el nuevo ritmo de trabajo', score: 0 }] },
  { cat: 'ai-manufacturing', d: 3, s: 'Tu planta quiere implementar gemelos digitales con IA. ¿Cuál es el prerequisito más crítico?', t: 'Los gemelos digitales requieren sincronización en tiempo real entre el mundo físico y el modelo digital. La calidad y velocidad de los datos es la base de su utilidad.', options: [{ text: 'Infraestructura de datos en tiempo real con sensores calibrados y alta fiabilidad', score: 100 }, { text: 'Software de simulación 3D avanzado', score: -100 }, { text: 'Un equipo de data scientists dedicado al proyecto', score: 0 }] },
  { cat: 'ai-manufacturing', d: 2, s: 'La IA propone un cambio en la cadena de suministro que reduciría costes 20% pero con un único proveedor. Tú...', t: 'La optimización de costes con proveedor único crea fragilidad sistémica. Los eventos de riesgo de cadena de suministro (COVID, guerras) han demostrado el coste de esta concentración.', options: [{ text: 'Equilibras el ahorro con el riesgo de concentración y diseñas un plan de contingencia', score: 100 }, { text: 'Implementas la propuesta — el ahorro de 20% es prioritario', score: -100 }, { text: 'Rechazas cualquier cambio en la cadena de suministro — funciona bien', score: 0 }] },
  { cat: 'ai-manufacturing', d: 1, s: 'Los operarios temen que la IA de la planta los reemplace. ¿Cuál es tu mensaje?', t: 'En manufactura, la IA complementa las habilidades humanas en tareas peligrosas o repetitivas. Las habilidades de supervisión, resolución de problemas y mantenimiento ganan valor.', options: [{ text: 'Que la IA asume las tareas más peligrosas y repetitivas, y ellos se enfocan en supervisión y resolución de problemas', score: 100 }, { text: 'Que deben entender que la automatización es inevitable', score: -100 }, { text: 'Que su futuro en la empresa depende de cómo se adapten a la IA', score: 0 }] },
  { cat: 'ai-manufacturing', d: 3, s: 'La IA de planificación de producción comete un error que causa retrasos en toda la cadena. ¿Qué revisas?', t: 'Los errores de IA en planificación son síntomas de datos incorrectos, supuestos del modelo inadecuados o cambios no anticipados. El diagnóstico correcto previene la recurrencia.', options: [{ text: 'La calidad de los datos de entrada, los supuestos del modelo y qué cambio no fue anticipado', score: 100 }, { text: 'La herramienta de IA — probablemente tiene un bug', score: -100 }, { text: 'Al operador que aprobó la planificación', score: 0 }] },
  { cat: 'ai-manufacturing', d: 2, s: 'Quieres usar IA para reducir el desperdicio en la línea de producción. ¿Cuál es el mejor enfoque inicial?', t: 'Reducir desperdicio con IA requiere primero identificar dónde está la mayor fuente de desperdicio. Sin eso, la IA optimiza los puntos equivocados.', options: [{ text: 'Mapear y cuantificar las fuentes de desperdicio actuales antes de elegir solución de IA', score: 100 }, { text: 'Implementar IA de visión para detectar defectos en todas las etapas', score: -100 }, { text: 'Preguntar a los operarios qué mejorarían y usar IA para eso', score: 0 }] },
  { cat: 'ai-manufacturing', d: 1, s: 'La IA predice un fallo en una máquina crítica en 48 horas. Tu protocolo de respuesta...', t: 'La predicción de fallo con 48 horas de margen permite una respuesta planificada que evita una parada no programada. El valor del mantenimiento predictivo es exactamente este margen.', options: [{ text: 'Programar mantenimiento preventivo inmediato y preparar piezas de repuesto', score: 100 }, { text: 'Esperar a que falle para confirmar la predicción', score: -100 }, { text: 'Parar la producción inmediatamente por precaución', score: 0 }] },
  { cat: 'ai-manufacturing', d: 3, s: 'Tu empresa evalúa pasar de inspección humana a IA para el 100% del control de calidad. ¿Qué garantías necesitas?', t: 'El control de calidad 100% automatizado requiere validación del modelo en todos los escenarios de producción, especialmente en bordes del proceso donde los fallos son más críticos.', options: [{ text: 'Validación del modelo en todos los escenarios de producción y protocolo de override humano', score: 100 }, { text: 'Que la IA tenga al menos el mismo porcentaje de acierto que los inspectores humanos en promedio', score: -100 }, { text: 'La certificación del proveedor de que el sistema es preciso', score: 0 }] },
  { cat: 'ai-manufacturing', d: 2, s: 'La IA de tu fábrica recomienda aumentar el ritmo de producción más allá del diseño original de la línea. Tú...', t: 'Operar más allá del diseño original puede invalidar garantías, aumentar fallos y crear riesgos de seguridad que la IA no modela correctamente.', options: [{ text: 'Verificas con ingeniería si el diseño original soporta el ritmo propuesto antes de implementar', score: 100 }, { text: 'Lo implementas — si la IA lo recomienda, habrá calculado que es posible', score: -100 }, { text: 'Lo rechazas — la IA no puede recomendar operar fuera de diseño', score: 0 }] },
  { cat: 'ai-manufacturing', d: 1, s: 'Quieres medir el ROI de la IA en tu planta industrial. ¿Qué métricas son más relevantes?', t: 'El ROI industrial de IA se mide en tiempo de parada evitado, tasa de defectos, tiempo de ciclo y costes de mantenimiento. Las métricas abstractas no convencen a la dirección.', options: [{ text: 'Tiempo de parada no programada evitado, tasa de defectos y coste de mantenimiento', score: 100 }, { text: 'Número de alertas generadas por el sistema de IA', score: -100 }, { text: 'Satisfacción de los operarios con el nuevo sistema', score: 0 }] },
  { cat: 'ai-manufacturing', d: 3, s: 'Una IA de diseño de producto propone un componente que reduce costes 30% pero aún no está probado en producción real. Tú...', t: 'Las propuestas de IA en diseño de producto reducen el espacio de exploración pero no sustituyen la validación física. La producción en masa sin prueba de concepto es un riesgo alto.', options: [{ text: 'Produces un lote piloto para validar el rendimiento real antes de escalar', score: 100 }, { text: 'Implementas directamente — el ahorro justifica el riesgo', score: -100 }, { text: 'Rechazas — solo usas componentes con historial probado', score: 0 }] },

  // ai-media-content (14)
  { cat: 'ai-media-content', d: 1, s: 'Usas IA para generar el primer borrador de un artículo. ¿Cuál es el paso más importante después?', t: 'Un borrador de IA es un punto de partida, no un producto final. La revisión editorial que añade perspectiva, verifica hechos y da voz propia es lo que convierte el texto en periodismo.', options: [{ text: 'Verificar todos los datos, añadir perspectiva propia y reescribir en tu voz', score: 100 }, { text: 'Publicarlo directamente si el texto es fluido y coherente', score: -100 }, { text: 'Pasar un detector de IA para asegurarte de que no se note', score: 0 }] },
  { cat: 'ai-media-content', d: 2, s: 'Tu redacción usa IA para personalizar titulares según el perfil del lector. Riesgo principal...', t: 'La personalización de titulares puede crear burbujas informativas donde cada lector ve el encuadre que confirma sus creencias. El periodismo tiene responsabilidad en el encuadre colectivo de la realidad.', options: [{ text: 'Crear burbujas informativas que refuercen sesgos existentes de cada lector', score: 100 }, { text: 'Que los titulares sean menos creativos que los escritos por humanos', score: -100 }, { text: 'Que algunos lectores descubran que el titular fue generado por IA', score: 0 }] },
  { cat: 'ai-media-content', d: 2, s: 'La IA genera imágenes hiperrealistas para ilustrar noticias. ¿Cuál es la política editorial correcta?', t: 'Las imágenes de IA en periodismo deben marcarse explícitamente. El lector tiene derecho a saber si la imagen representa un evento real o es una ilustración generada.', options: [{ text: 'Etiquetar siempre las imágenes generadas por IA de forma visible y clara', score: 100 }, { text: 'Usarlas libremente si son realistas — equivalen a una ilustración', score: -100 }, { text: 'Usarlas solo en artículos de opinión, no en noticias', score: 0 }] },
  { cat: 'ai-media-content', d: 1, s: 'Un creador de contenido usa IA para generar 50 artículos por semana. ¿Cuál es el riesgo principal?', t: 'El volumen de contenido de IA sin supervisión editorial adecuada produce contenido sin diferenciación, con errores factuales y sin perspectiva original. La cantidad nunca sustituye la calidad.', options: [{ text: 'Producir contenido sin diferenciación, con errores y sin perspectiva real', score: 100 }, { text: 'Que el algoritmo de SEO penalice el contenido generado por IA', score: -100 }, { text: 'Que los lectores noten que el contenido no es humano', score: 0 }] },
  { cat: 'ai-media-content', d: 3, s: 'Una IA genera un deepfake de un político diciendo algo que nunca dijo. Tu redacción lo recibe como fuente. Tú...', t: 'La verificación de autenticidad de material audiovisual es un requisito periodístico básico amplificado en la era de los deepfakes. Publicar sin verificar es un error profesional grave.', options: [{ text: 'Aplicas protocolo de verificación de autenticidad antes de publicar o rechazar', score: 100 }, { text: 'Lo publicas si es noticiable — la audiencia juzgará', score: -100 }, { text: 'Lo rechazas directamente — el deepfake es evidente', score: 0 }] },
  { cat: 'ai-media-content', d: 2, s: 'Tu agencia crea campañas publicitarias con IA generativa. El cliente pide más "creatividad". Tú...', t: 'La IA genera creatividad estadística (lo que ha funcionado antes). La creatividad disruptiva requiere perspectiva humana que rompa con los patrones establecidos.', options: [{ text: 'Defines qué dimensión de creatividad busca el cliente y usas la IA como herramienta de exploración, no como creador final', score: 100 }, { text: 'Cambias el prompt para pedir más creatividad a la IA', score: -100 }, { text: 'Aumentas el presupuesto de generación para obtener más variaciones', score: 0 }] },
  { cat: 'ai-media-content', d: 1, s: 'Quieres usar IA para analizar qué contenido genera más engagement. ¿Qué métrica no debes optimizar únicamente?', t: 'Optimizar solo por engagement favorece el contenido que genera reacción emocional (indignación, miedo) sobre el que informa bien. La relevancia y la calidad informativa deben estar en la función objetivo.', options: [{ text: 'El engagement puro sin considerar calidad informativa y relevancia real', score: 100 }, { text: 'El tiempo de permanencia en la página', score: -100 }, { text: 'El número de veces compartido', score: 0 }] },
  { cat: 'ai-media-content', d: 3, s: 'La IA de tu plataforma amplifica contenido que genera más interacciones, incluyendo desinformación. Tú...', t: 'Los algoritmos que optimizan por interacción sin filtro de veracidad amplifican sistemáticamente el contenido más polarizante. La responsabilidad de la plataforma incluye el impacto del algoritmo.', options: [{ text: 'Propones modificar el algoritmo para incorporar señales de calidad informativa', score: 100 }, { text: 'No es tu responsabilidad — la plataforma solo distribuye lo que los usuarios eligen', score: -100 }, { text: 'Añades etiquetas de advertencia pero no cambias el algoritmo', score: 0 }] },
  { cat: 'ai-media-content', d: 2, s: 'Un periodista usa IA para entrevistar a una fuente a través de un avatar sintético de ella. ¿Es ético?', t: 'Crear un avatar sintético de una persona para simular sus respuestas sin su consentimiento es una violación de identidad, independientemente del propósito periodístico.', options: [{ text: 'No sin consentimiento explícito de la persona cuyo avatar se usa', score: 100 }, { text: 'Sí si el periodista revela que es un avatar al publicar', score: -100 }, { text: 'Depende de si las respuestas generadas son precisas', score: 0 }] },
  { cat: 'ai-media-content', d: 1, s: 'Tu equipo de contenido tiene dudas sobre cómo declarar el uso de IA. ¿Cuál es la política correcta?', t: 'La transparencia sobre el uso de IA en contenido periodístico es un estándar ético emergente que genera confianza en la audiencia y diferencia el periodismo responsable.', options: [{ text: 'Declarar el uso de IA de forma clara y describir qué rol tuvo en el proceso', score: 100 }, { text: 'No declararlo — es una herramienta interna como el corrector ortográfico', score: -100 }, { text: 'Declararlo solo cuando la IA escribió la mayor parte del contenido', score: 0 }] },
  { cat: 'ai-media-content', d: 3, s: 'La IA de tu editorial puede predecir qué libros serán bestsellers. ¿Cómo la usas?', t: 'Las predicciones de bestseller por IA identifican patrones del pasado. Usarlas como filtro único crea sesgo hacia lo seguro y reduce la diversidad cultural del catálogo.', options: [{ text: 'Como señal más entre muchas, sin convertirla en filtro único de decisión editorial', score: 100 }, { text: 'Como criterio principal de selección — reduce el riesgo editorial', score: -100 }, { text: 'Solo para decidir el tiraje inicial, no la selección', score: 0 }] },
  { cat: 'ai-media-content', d: 2, s: 'Tu plataforma de podcast usa IA para clonar la voz de locutores y crear más contenido. ¿Qué requieres?', t: 'La clonación de voz requiere consentimiento explícito, acuerdo sobre usos permitidos y compensación. Es una extensión de los derechos de imagen y personalidad del locutor.', options: [{ text: 'Consentimiento explícito del locutor con acuerdo de usos y compensación', score: 100 }, { text: 'Solo la aprobación del departamento legal', score: -100 }, { text: 'Que el resultado suene suficientemente diferente para no ser reconocible', score: 0 }] },
  { cat: 'ai-media-content', d: 1, s: 'La IA puede generar música de fondo para tus videos en segundos. ¿Qué consideraciones tienes?', t: 'La música generada por IA puede estar entrenada con obras protegidas por derechos de autor. Las plataformas de distribución tienen políticas diferentes sobre música generada por IA.', options: [{ text: 'Verificar la licencia de la plataforma de IA y la compatibilidad con tu plataforma de distribución', score: 100 }, { text: 'Usarla libremente — si la IA la genera, es nueva y libre de derechos', score: -100 }, { text: 'Evitar cualquier música de IA — demasiado riesgo legal', score: 0 }] },
  { cat: 'ai-media-content', d: 3, s: 'La IA puede personalizar completamente la experiencia informativa de cada usuario. ¿Qué principio editorial debe mantenerse?', t: 'La personalización total elimina el espacio informativo común que necesita una sociedad democrática para dialogar. Los medios tienen responsabilidad en preservar esa experiencia compartida.', options: [{ text: 'Que todos los usuarios accedan a cierto núcleo de información relevante compartida', score: 100 }, { text: 'Ninguno — cada usuario tiene derecho a recibir solo lo que le interesa', score: -100 }, { text: 'Que la IA no personalice noticias locales, solo internacionales', score: 0 }] },
]

console.log('Total:', ALL.length, 'questions')
for (let i = 0; i < ALL.length; i += 20) {
  await insert(ALL.slice(i, i + 20))
}
