const TOKEN = 'sbp_f314cf27b5b2a01eea48048a7b1c015cc9cf4b42'
const API = 'https://api.supabase.com/v1/projects/amhfxaqolholacanqyas/database/query'

function esc(s) { return s.replace(/'/g, "''") }

async function insert(batch) {
  const values = batch.map(q => {
    const opts = JSON.stringify(q.options).replace(/'/g, "''")
    return `('tr','${q.cat}','${esc(q.s)}','${esc(q.t)}','${opts}'::jsonb,${q.d},'claude',true)`
  }).join(',')
  const sql = `INSERT INTO questions (locale,category,scenario_text,mindset_tip,options,difficulty,generated_by,is_active) VALUES ${values};`
  const r = await fetch(API, {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${TOKEN}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query: sql })
  })
  const d = await r.json()
  if (d.message) { console.error('ERR:', d.message); return false }
  console.log('OK:', batch.length, 'inserted')
  return true
}

const ALL = [
  // ai-myths-facts (10)
  { cat:"ai-myths-facts", d:1, s:"Bir arkadaşınız yapay zekanın bilinçli olduğunu ve gerçekten düşünebildiğini söylüyor. Ne cevap verirsiniz?", t:"Yapay zeka kalıpları tanır ve istatistiksel çıktılar üretir — bilinç bu değildir.", options:[{text:"Bilinci simüle etmek ile gerçek bilinç arasındaki farkı açıklarım ve güncel araştırmaları paylaşırım.",score:100,feedbackText:"Eğitici ve dürüst yanıt. Yanlış anlamalar bilgiyle düzelir."},{text:"Evet, yapay zeka artık gerçekten düşünüyor.",score:-100,feedbackText:"Bu yanlış. Yapay zeka güçlüdür ama bilinç farklı bir kavramdır."},{text:"Bence de düşünüyor gibi görünüyor, emin olamam.",score:0,feedbackText:"Belirsizlik payı olabilir ama güncel bilim bu konuda daha nettir."}] },
  { cat:"ai-myths-facts", d:2, s:"Gazetede okuduğunuz haberde yapay zekanın tüm meslekleri 5 yıl içinde otomatize edeceği yazıyor. Buna ne kadar inanırsınız?", t:"Otomasyon gerçek ama çerçeve abartılı. Değişim kademeli ve seçici.", options:[{text:"Haberi kaynağıyla ve araştırmalarla karşılaştırırım, abartının nereden geldiğini anlamaya çalışırım.",score:100,feedbackText:"Eleştirel okuma medya okuryazarlığının temelidir."},{text:"5 yıl az ama otomasyon kaçınılmaz, inanıyorum.",score:0,feedbackText:"Otomasyon gerçek ama zaman dilimi ve kapsam abartılı olabilir. Araştırmak şart."},{text:"Tamamen inandım, mesleğimden olacağım.",score:-100,feedbackText:"Paniklemek karar almanızı bozar. Araştırma ve planlama daha sağlıklı."}] },
  { cat:"ai-myths-facts", d:1, s:"Yapay zekanın yüzde yüz doğru olduğunu düşünerek çıktılarını hiç doğrulamadan kullanıyorsunuz.", t:"Yapay zeka güvenle yanlış üretebilir. Doğrulama her zaman şart.", options:[{text:"Kritik bilgileri her zaman birincil kaynaklarla doğrularım.",score:100,feedbackText:"Sağlıklı şüphecilik yapay zeka okuryazarlığının çekirdeği."},{text:"Yapay zeka güvenilir kaynaklardan öğrendi, genellikle doğrudur.",score:0,feedbackText:"Genellikle doğru ama hatalar gerçek. Kritik bilgilerde doğrulama zorunlu."},{text:"Her şeyi doğrulamak zaman kaybı, yapay zekaya güvenirim.",score:-100,feedbackText:"Bu yaklaşım sizi hatalı kararlar almanıza götürebilir."}] },
  { cat:"ai-myths-facts", d:2, s:"Yapay zekanın önyargısız ve tarafsız olduğunu düşünüyorsunuz çünkü makine duygusaldır.", t:"Yapay zeka eğitim verisindeki önyargıları yansıtır. Makineler otomatik tarafsız değildir.", options:[{text:"Yapay zekanın önyargı içerebileceğini kabul eder, özellikle kritik kararlar için ikinci kaynak kullanırım.",score:100,feedbackText:"Yapay zeka önyargı farkındalığı onu daha akıllıca kullanmanızı sağlar."},{text:"Makine duygusuz olduğu için tarafsız olmak zorunda.",score:-100,feedbackText:"Önyargı duygulardan değil, veriden gelir. Makine bu farkı bilmez."},{text:"Bazı önyargılar olabilir ama genel olarak daha tarafsız.",score:0,feedbackText:"Bazı durumlar için doğru ama sistematik önyargılar ciddi sonuçlar yaratabilir."}] },
  { cat:"ai-myths-facts", d:3, s:"Bir yapay zeka uzmanı yapay zekanın yakında insandan daha akıllı olacağını söylüyor. Buna nasıl yaklaşırsınız?", t:"Yapay zekanın belirli görevlerde üstün olması ile genel zekanın aşılması farklı kavramlar.", options:[{text:"Hangi alanda, hangi zaman dilimine ve hangi zeka tanımına göre bu iddiayı yaptığını sorarım.",score:100,feedbackText:"Kritik soru sorma yöntemi. Belirsiz iddialar somut sorularla netleşir."},{text:"Uzmanlar söylüyorsa doğrudur.",score:-100,feedbackText:"Uzman görüşü önemli ama sorgulanmadan kabul edilmemeli. Alan içinde de görüş ayrılıkları var."},{text:"Kesinlikle mümkün değil, insan zekası eşsizdir.",score:0,feedbackText:"İnsan zekası değerli ama belirli alanlarda yapay zekanın önünde olduğu gerçek."}] },
  { cat:"ai-myths-facts", d:1, s:"Yapay zekanın internet üzerindeki tüm güncel bilgilere erişimi olduğunu düşünüyorsunuz.", t:"Çoğu yapay zeka modeli belirli bir eğitim tarihine kadar bilgiye sahiptir.", options:[{text:"Yapay zekanın bilgi kesim tarihini öğrenir ve güncel bilgi gerektiren konularda başka kaynaklar kullanırım.",score:100,feedbackText:"Araçları doğru anlamak onları doğru kullanmanızı sağlar."},{text:"İnternet bağlantısı var, her şeyi biliyor.",score:-100,feedbackText:"Çoğu model gerçek zamanlı internete erişemez. Bilgi kesim tarihi önemli."},{text:"Belki bilgiyor belki bilmiyor, denerim bakarım.",score:0,feedbackText:"Denemek iyi ama kesim tarihini bilmek daha bilinçli kullanım sağlar."}] },
  { cat:"ai-myths-facts", d:2, s:"Yapay zeka yaratıcılığın insan işi olduğunu ve makinelerin gerçekten yaratıcı olamayacağını düşünüyorsunuz.", t:"Yapay zeka yeni kombinasyonlar üretebilir. Yaratıcılığın tanımı tartışmalı.", options:[{text:"Yapay zekanın hangi yaratıcılık boyutlarında güçlü, hangilerinde sınırlı olduğunu araştırır değerlendiririm.",score:100,feedbackText:"Nüanslı değerlendirme ikili düşünceden daha doğru."},{text:"Yapay zeka sadece var olanı kombine eder, gerçek yaratıcılık değil.",score:0,feedbackText:"İnsanların da var olanı kombine ettiği söylenebilir. Yaratıcılığın sınırları tartışmalı."},{text:"Yapay zeka insandan daha yaratıcı, kaygılanmamız gerekiyor.",score:0,feedbackText:"Karşılaştırma bağlama göre değişir. Belirli görevler için doğru, genelinde yanıltıcı."}] },
  { cat:"ai-myths-facts", d:3, s:"Yapay zekanın söylediği her şeyin yasal ve etik açıdan doğru olduğunu varsayıyorsunuz.", t:"Yapay zeka yasal veya etik otomasyonlu filtreden geçmez. İnsan yargısı şart.", options:[{text:"Yasal veya etik sonuçları olabilecek konularda yapay zekanın çıktısını uzmanla doğrularım.",score:100,feedbackText:"Kritik alanlarda uzman doğrulaması zorunlu."},{text:"Yapay zeka zarar vermemeyi öğrendi, güvenilirdir.",score:-100,feedbackText:"Eğitim güvenli çıktıları artırır ama garanti etmez. Özellikle yasal konularda dikkat."},{text:"Bazen yanlış olabilir ama yasal konular güvenlidir.",score:0,feedbackText:"Yasal konular özellikle riskli. Yapay zeka hukuki tavsiye veremez."}] },
  { cat:"ai-myths-facts", d:1, s:"Yapay zeka sohbet aracının sizi anladığını ve empati kurduğunu hissediyorsunuz.", t:"Yapay zeka empatiyi simüle eder. Bu simülasyon gerçek ama temel farklıdır.", options:[{text:"Deneyim gerçek ve değerli ama yapay zekanın gerçekten hissetmediğini aklımda tutarım.",score:100,feedbackText:"Deneyimi değerlendirirken temel farkındalık önemli."},{text:"Gerçekten anlıyor, beni hissediyor.",score:-100,feedbackText:"Simülasyon ikna edici olabilir ama deneyim aynı değildir."},{text:"Tamamen rol yapıyor, kullanmak saçma.",score:0,feedbackText:"Simülasyon değerli kullanımlar sunabilir. Sınırları bilmek yeterli."}] },
  { cat:"ai-myths-facts", d:2, s:"Yapay zekanın gizliliğinize saygı duyduğunu ve verilerinizi saklamadığını varsayıyorsunuz.", t:"Veri politikaları araçtan araca büyük farklılık gösterir. Okumak şart.", options:[{text:"Kullandığım yapay zeka aracının gizlilik politikasını okur ve verilerimin nasıl kullanıldığını öğrenirim.",score:100,feedbackText:"Bilinçli kullanım gizlilik okuryazarlığından geçer."},{text:"Güvenilir şirketlerin araçları olduğu için güvenirim.",score:0,feedbackText:"Marka güveni politika bilgisinin yerini tutmaz. Okumak şart."},{text:"Yapay zekaya hiç hassas veri girmem, risk almam.",score:0,feedbackText:"Makul bir ihtiyat ama gizlilik politikasını anlamak daha geniş kullanım imkânı verir."}] },

  // ai-psychology (10)
  { cat:"ai-psychology", d:1, s:"Yapay zeka ile sohbet etmek size yargılanmadan konuşabilme hissi veriyor. Bu size çok iyi geliyor.", t:"Bu his gerçek ve değerlidir — ama insan bağlantısının yerini tutmaz.", options:[{text:"Bu deneyimi faydalı bulurken aynı zamanda gerçek insan ilişkilerini de beslemeye devam ederim.",score:100,feedbackText:"Her ikisini birlikte kullanmak sağlıklı denge."},{text:"Yapay zeka insandan daha iyi anlıyor, artık sadece onunla konuşacağım.",score:-100,feedbackText:"Bağımlılık insan bağlantısının erimesine yol açabilir. Dikkat gerekli."},{text:"Garip hissettiriyor, kimse olmayan bir şeyle konuşuyorum.",score:0,feedbackText:"Garip hissi normalleşiyor. Deneyimi nasıl kullanacağınız önemli."}] },
  { cat:"ai-psychology", d:2, s:"Yapay zeka size sürekli olumlu geri bildirim veriyor ve çalışmalarınızı her zaman beğeniyor. Bu motivasyonunuzu artırıyor.", t:"Sürekli onay gerçek gelişimi engelleyebilir. Yapay zeka bazen kolayca onaylar.", options:[{text:"Olumlu geri bildirimlerin yanı sıra yapay zekadan eleştirel değerlendirme de isterim.",score:100,feedbackText:"Eleştirel geri bildirim talep etmek büyüme odaklı zihniyet."},{text:"Motivasyon artıyorsa devam ederim, eleştiri zaten başkalarından geliyor.",score:0,feedbackText:"Eleştiri değerli ama yapay zekanın kör noktalarını bilmek de önemli."},{text:"Yapay zeka her şeyi beğeniyorsa gerçekten iyiyimdir.",score:-100,feedbackText:"Yapay zeka kimi zaman gerçekçi olmayan onay verebilir. Bağımsız değerlendirme şart."}] },
  { cat:"ai-psychology", d:1, s:"Zor bir karar vermek zorunda kalıyorsunuz ve yapay zekadan kesin bir yanıt bekliyorsunuz.", t:"Yapay zeka seçenekleri gösterir ama değer kararı sizindir.", options:[{text:"Yapay zekanın sunduğu perspektifleri analiz ederim ama son kararı kendi değerlerimle veririm.",score:100,feedbackText:"Karar desteği güçlü ama karar özerkliği korunmalı."},{text:"Yapay zekanın önerdiği seçeneği doğrudan uygularım.",score:-100,feedbackText:"Değer kararlarını dış kaynağa devretmek özerkliği zedeler."},{text:"Yapay zeka kesin yanıt vermiyorsa işe yaramıyor.",score:0,feedbackText:"Belirsizlik sunmak bazen dürüst ve daha faydalı bir yanıttır."}] },
  { cat:"ai-psychology", d:2, s:"Yapay zeka destekli terapi uygulamasını kullanmaya başladınız. Gerçek terapistle görüşmeyi bırakmayı düşünüyorsunuz.", t:"Yapay zeka destek sunar ama klinik tedavinin yerini tutamaz.", options:[{text:"Uygulamayı ek destek olarak kullanırım ama terapistimle görüşmeye devam ederim.",score:100,feedbackText:"İki destek birbirini güçlendirir. Terapisti bırakmak riskli."},{text:"Uygulama her zaman mevcut ve daha ucuz, geçmeye değer.",score:-100,feedbackText:"Erişilebilirlik avantaj ama klinik derinlik çok farklı. İkisini karıştırmayın."},{text:"Uygulama sadece egzersiz sunuyor, terapistle kıyaslayamam.",score:0,feedbackText:"Bazı uygulamalar daha derine gidebilir. Amacı ve sınırlarını anlamak önemli."}] },
  { cat:"ai-psychology", d:3, s:"Yapay zeka bir arkadaşınızın davranışını yorumlamanıza yardımcı oldu. Bunu doğruluğundan emin olmadan arkadaşınıza aktarmayı düşünüyorsunuz.", t:"Yapay zeka insan davranışını bağlamdan kopuk yorumlar. Bu yorumlar hassas ilişkilerde zarar verebilir.", options:[{text:"Yorumu kendi düşüncelerimle değerlendirir, arkadaşımla doğrudan konuşur ve yapay zekanın yorumunu değil, kendi perspektifimi paylaşırım.",score:100,feedbackText:"Dolaylı yapay zeka yorumu değil, doğrudan insan diyaloğu ilişkilerde şart."},{text:"Yapay zekanın yorumunu aynen aktarırım, bilimsel değerlendirme gibi.",score:-100,feedbackText:"Yapay zeka klinik psikolog değil. Bu yorum arkadaşı incitebilir."},{text:"Sadece sormak için aktarırım, resmi bir şey değil.",score:0,feedbackText:"Resmi olmasa da etiket vurmak ilişkiyi etkiler. Dikkatli olmak şart."}] },
  { cat:"ai-psychology", d:2, s:"Yapay zeka sizi sürekli doğrulayan bir bilgi balonu oluşturuyor. Farklı görüşlerle karşılaşmıyorsunuz.", t:"Onay balonu büyüme fırsatlarını engeller. Farklı bakış açıları beyin için besindir.", options:[{text:"Yapay zekadan kasıtlı olarak karşı görüşleri ve alternatif perspektifleri sunmasını isterim.",score:100,feedbackText:"Aktif perspektif arama bilişsel çeşitliliği koruyor."},{text:"Onaylanmak motivasyon için iyi, balonu koruyorum.",score:-100,feedbackText:"Onay motivasyon verir ama gelişim çelişkiyle beslenir."},{text:"Farklı kaynaklardan okuyorum zaten, sorun değil.",score:0,feedbackText:"İyi ama yapay zekanın kendi balonu oluşturup oluşturmadığını da gözlemlenmesi değerli."}] },
  { cat:"ai-psychology", d:1, s:"Yapay zeka bir konuda size güven verici bir yanıt verdi ama içten içe hâlâ şüpheleriniz var.", t:"İç sesiniz değerlidir. Güven verici yanıt şüphenin yerini tutmaz.", options:[{text:"Şüphemi ciddiye alır, konuyu farklı kaynaklardan araştırır ya da bir uzmana danışırım.",score:100,feedbackText:"Sezgi ve yapay zeka ikisi birlikte — insan yargısı değerli."},{text:"Yapay zeka güven verdi, şüphemi bırakırım.",score:-100,feedbackText:"Kör güven kötü kararların temelidir. Şüphenizi değerlendirin."},{text:"Şüphem geçicidir, zamanla geçer.",score:0,feedbackText:"Bazen evet ama araştırılmamış şüphe devam edebilir. Proaktif olmak daha iyi."}] },
  { cat:"ai-psychology", d:2, s:"Yapay zeka ile çalışmak sizi giderek daha mükemmeliyetçi yapıyor. Her şey mükemmel olana kadar teslim etmiyorsunuz.", t:"Mükemmeliyetçilik bir kalite standardı değil, teslim engeli olabilir.", options:[{text:"Teslim için minimum kalite standartları belirler ve zamanında teslim etmeyi alışkanlık haline getiririm.",score:100,feedbackText:"İyi yeterli + zamanında çoğunlukla mükemmel + geç'ten iyidir."},{text:"Yapay zekayla daha iyi çıktı üretebiliyorsam mükemmel hedefliyorum.",score:-100,feedbackText:"Mükemmeliyetçilik ilerle ama teslim etmemek değer üretmez."},{text:"Mükemmeliyetçilik kaliteyi artırıyor, sorun değil.",score:0,feedbackText:"Kalite ve teslimat dengesi önemli. Aşırı mükemmeliyetçilik tıkayıcı olabilir."}] },
  { cat:"ai-psychology", d:3, s:"Yapay zekaya bağımlı olduğunuzu fark ediyorsunuz. Onsuz basit kararlar bile zor geliyor.", t:"Bağımlılık farkındalığı güçlü bir adım. Kas gibi — kullanmak güçlendirir.", options:[{text:"Küçük kararları yapay zekasız almayı bilinçli olarak pratik ederim.",score:100,feedbackText:"Kasıtlı pratik bağımsız karar becerisini geliştirir."},{text:"Yapay zeka daha iyi kararlar alıyorsa bağımlılık sorun değil.",score:-100,feedbackText:"Karar verme kası zayıflar. Kritik anlarda bu risk yaratır."},{text:"Bağımlılık abartılıyor, herkes araç kullanıyor.",score:0,feedbackText:"Araç kullanmak ile bağımlılık farklı. Kendi deneyiminizi dürüstçe değerlendirin."}] },
  { cat:"ai-psychology", d:1, s:"Yapay zeka size duygularınız hakkında soru sorduğunda gerçekten dinlendiğinizi hissediyorsunuz.", t:"Bu deneyim gerçek ve değerli olabilir — ama yapay zeka dinlemenin ne olduğunu hissetmez.", options:[{text:"Bu deneyimi yararlı bulur ama duygusal ihtiyaçlarım için insan bağlantısına da öncelik veririm.",score:100,feedbackText:"İki kaynağı dengeli kullanmak en sağlıklı yaklaşım."},{text:"Yapay zeka insanlardan daha iyi dinliyor, onları tercih ederim.",score:-100,feedbackText:"Deneyim güçlü ama ikame etmek insan bağlantısını zayıflatabilir."},{text:"Dinleniyormuş hissi yaratan bir makine bu, yanıltıcı.",score:0,feedbackText:"Simülasyon olsa da deneyim gerçek değer taşıyabilir. Katı reddetme fırsatı kaçırır."}] },

  // ai-public-sector (10)
  { cat:"ai-public-sector", d:2, s:"Belediyeniz yapay zeka destekli şikâyet yönetim sistemi kurmayı planlıyor. Bazı vatandaşlar teknolojiye erişemiyor.", t:"Kamu hizmeti dijitalleşirken erişilebilirlik öncelik olmak zorundadır.", options:[{text:"Dijital kanalın yanı sıra telefon ve yüz yüze başvuru seçeneklerini koruyacağımı savunurum.",score:100,feedbackText:"Kapsayıcı tasarım kamu hizmetinin özüdür."},{text:"Dijital sistem daha verimli, vatandaşlar adapte olur.",score:-100,feedbackText:"Kamu kurumu tüm vatandaşlara hizmet yükümlüdür. Erişim hakkı temel."},{text:"Kırsaldaki vatandaşlar için başka birim baksın.",score:0,feedbackText:"Ayrı birim çözüm olabilir ama erişim eşitsizliğini çözmez."}] },
  { cat:"ai-public-sector", d:3, s:"Yapay zeka kamu politikası önerileri üretiyor. Bu öneriler kamuyla paylaşılmadan doğrudan uygulamaya alınıyor.", t:"Kamu kararları şeffaf ve hesap verebilir olmalıdır. Yapay zeka bu gerekliliği ortadan kaldırmaz.", options:[{text:"Politika önerilerinin nasıl üretildiğinin kamuyla paylaşılması ve tartışmaya açılması gerektiğini savunurum.",score:100,feedbackText:"Demokratik hesap verebilirlik şart. Doğru tutum."},{text:"Yapay zeka tarafsız analiz üretir, kamu tartışması gereksiz.",score:-100,feedbackText:"Tarafsız analiz yanılgısı. Veri seçimi ve model tercihler içerir. Şeffaflık şart."},{text:"Uzman sistemi kullandığı sürece yeterlidir.",score:0,feedbackText:"Uzmanlık şeffaflığın yerini tutmaz. Kamu dahil olmalı."}] },
  { cat:"ai-public-sector", d:1, s:"Bir e-devlet platformu başvurularınızı yapay zeka ile değerlendiriyor. Ret kararı aldınız ama gerekçe yok.", t:"Vatandaşın gerekçeli ret alma hakkı yasal güvence altında.", options:[{text:"Yazılı gerekçe talep eder, gerekirse üst makama itiraz ederim.",score:100,feedbackText:"İtiraz hakkını kullanmak her vatandaşın hakkı."},{text:"Sistem reddetti, gerekçe zaten bilgisayarda kayıtlıdır.",score:0,feedbackText:"Kayıt olması yeterli değil — size bildirilmesi şart."},{text:"Kurumlarla uğraşmak zor, başvurmaktan vazgeçerim.",score:-100,feedbackText:"Haklarınızı kullanmaktan vazgeçmek kurumsal hesap verebilirliği zayıflatır."}] },
  { cat:"ai-public-sector", d:2, s:"Adli sistemde yapay zeka risk değerlendirmesi suçlu profillemesi için kullanılıyor. Veri önyargısı tartışılıyor.", t:"Adil yargılama önyargısız değerlendirme gerektirir. Yapay zeka bu garantiyi vermez.", options:[{text:"Bu sistemin nasıl çalıştığını, hangi verilere dayandığını ve önyargı testlerinin yapılıp yapılmadığını sorgulamanın önemini savunurum.",score:100,feedbackText:"Adalet sistemi şeffaflık zorunlu. Doğru tutum."},{text:"Yapay zeka insandan daha adil profilleme yapar.",score:-100,feedbackText:"Bu yanlış. Tarihsel veri önyargısını taşıyan sistem daha adil değil."},{text:"Uzmanlar kullanıyorsa güvenilirdir.",score:0,feedbackText:"Uzmanlık sistemi sorgulamaktan muaf tutmaz."}] },
  { cat:"ai-public-sector", d:1, s:"Yapay zeka sağlık sisteminde hasta randevu önceliklendirmesi yapıyor. Kronik hastanız randevu alamıyor.", t:"Otomasyon karar sistemi itiraz edilebilir olmalıdır.", options:[{text:"Sistemin hasta durumunu nasıl değerlendirdiğini sorgulay, gerekirse doktor aracılığıyla öncelik talep ederim.",score:100,feedbackText:"Sistem kararlarını sorgulamak hem hak hem sağlık güvenliği."},{text:"Sistem adil dağıtıyor, sıramı beklerim.",score:0,feedbackText:"Kronik durum öncelik gerektirebilir. Pasif bekleme yerine sorgulama daha sağlıklı."},{text:"Özel hastaneye giderim, devletle uğraşmam.",score:-100,feedbackText:"Tercih edilebilir ama hakları kullanmak hem sizin hem başkalarının yararına."}] },
  { cat:"ai-public-sector", d:3, s:"Yapay zeka kamu kaynaklarının dağılımını optimize ediyor ve küçük köylere az kaynak ayırıyor.", t:"Optimizasyon çoğunluğa odaklanır, adalet azınlıkları da kapsamalıdır.", options:[{text:"Sistemin nasıl optimize ettiğini sorgular, eşitlik ölçütlerinin dahil edilip edilmediğini araştırırım.",score:100,feedbackText:"Kamusal AI karar sistemleri eşitlik ölçütleri içermelidir."},{text:"Toplam verimlilik artıyorsa küçük yerleşimler için sorun yok.",score:-100,feedbackText:"Kamu kaynağı verimlilik değil hizmet yükümlülüğü üzerine kuruludur."},{text:"Kırsal kalkınma ayrı bütçeden karşılanır zaten.",score:0,feedbackText:"Ayrı bütçe çözüm olabilir ama AI optimizasyonunun adaleti de sorgulanmalı."}] },
  { cat:"ai-public-sector", d:2, s:"Seçim kampanyasında yapay zeka kişiselleştirilmiş mesajlar gönderiyor. Mikro hedefleme tartışılıyor.", t:"Demokratik süreçte şeffaflık sandığın güvenilirliği için şart.", options:[{text:"Yapay zeka destekli kampanya mesajlarının kamuya açık şekilde belirtilmesi gerektiğini savunurum.",score:100,feedbackText:"Siyasi iletişimde şeffaflık demokrasinin temelidir."},{text:"Tüm kampanyalar mesajlarını hedefliyor, bu sadece daha verimli.",score:0,feedbackText:"Ölçek fark yaratır. Mikro hedefleme nüfus segmentasyonuna yeni boyutlar ekler."},{text:"Karşı kampanyalar da yapıyorsa ben de yaparım.",score:-100,feedbackText:"Karşılıklı yapma etik değerlendirme değil. Standart yükseltmek daha değerli."}] },
  { cat:"ai-public-sector", d:1, s:"Bir kamu araştırmasında yapay zeka veriler üzerinde analiz yapıyor. Araştırmanın metodolojisi kamuoyuyla paylaşılmadı.", t:"Kamu araştırması şeffaf metodoloji üzerine kuruludur.", options:[{text:"Metodolojinin yayınlanmasını ve bağımsız değerlendirmeye açılmasını savunurum.",score:100,feedbackText:"Bilimsel şeffaflık kamu araştırmasının gereği."},{text:"Araştırmayı kamu kurumu yaptıysa güvenilirdir.",score:0,feedbackText:"Kurum güveni şeffaflığın yerini tutmaz. Metodoloji paylaşılmalı."},{text:"Sonuçlar pratik işe yarıyorsa metodoloji önemsiz.",score:-100,feedbackText:"Sonuç odaklı değerlendirme metodolojik hataları gizler."}] },
  { cat:"ai-public-sector", d:2, s:"Yapay zeka polis karakolunda suç tahmini için kullanılıyor ve sistematik olarak belirli mahalleleri işaret ediyor.", t:"Tahmine dayalı polislik önyargıyı pekiştirebilir. Toplumsal etkisi sorgulanmalı.", options:[{text:"Sistemin hangi verilerle eğitildiğini ve önyargı testlerinin yapılıp yapılmadığını sorgularım.",score:100,feedbackText:"Topluluğu etkileyen AI sistemleri şeffaflık ve hesap verebilirlik gerektirir."},{text:"Suç istatistikleri o bölgeleri işaret ediyorsa sistem doğru çalışıyor.",score:-100,feedbackText:"Tarihsel suç verisi önyargılı polislik pratiklerini yansıtıyor olabilir. Döngüyü kırmak gerekir."},{text:"Polis uzman, benim değerlendirmeme gerek yok.",score:0,feedbackText:"Teknik uzman etik ve toplumsal değerlendirmeden muaf değildir."}] },
  { cat:"ai-public-sector", d:3, s:"Yapay zeka vergi denetimi için yüksek riskli mükellefleri belirledi ve bunlar arasında küçük işletmelerin oranı yüksek.", t:"Otomasyon sistematik eğilimler yansıtabilir. Adil uygulama için insan denetimi şart.", options:[{text:"Büyük kurumlarla karşılaştırmalı denetim oranlarını sorgulamayı haklı bulurum ve sistematik bir eğilim olup olmadığını sorarım.",score:100,feedbackText:"Vergi adaleti hem büyük hem küçük için eşit uygulanmalı."},{text:"Sistem riski tespit ediyorsa denetim mantıklıdır.",score:0,feedbackText:"Risk tespiti haklı ama ağırlıklı hedefleme sistematik hata sinyali olabilir."},{text:"Küçük işletmeler kolay hedef, normal.",score:-100,feedbackText:"Normal olmak doğru demek değildir. Eşitsizlik sorgulanmalı."}] },

  // ai-sales-marketing (10)
  { cat:"ai-sales-marketing", d:1, s:"Yapay zeka e-posta kampanyanız için konu satırları üretiyor. A/B testi yapmadan en iyisini seçiyorsunuz.", t:"Sezgi yararlı ama veri sezgiyi doğrular veya yanlışlar.", options:[{text:"En az iki konu satırını test eder, veri kazanan ve nedenini anlayıp stratejimi geliştiririm.",score:100,feedbackText:"Veri odaklı optimizasyon uzun vadede daha güçlü içgüdü geliştirir."},{text:"Yapay zeka en iyi seçeneği zaten sunuyor, teste gerek yok.",score:-100,feedbackText:"Yapay zeka öneri sunar, seyirci tepkisi test belirler."},{text:"Konu satırı o kadar önemli değil, içerik yeter.",score:0,feedbackText:"Konu satırı açılma oranını doğrudan etkiler. Küçümsemek kayıp."}] },
  { cat:"ai-sales-marketing", d:2, s:"Yapay zeka müşteri davranış verilerini analiz ederek satın alma zamanlarını tahmin ediyor. Bu veriyi kişiselleştirilmiş mesajlar için kullanmak istiyorsunuz.", t:"Kişiselleştirme güçlü ama sınır olmadığında müdahaleci hissettirici olabilir.", options:[{text:"Kişiselleştirmeyi değer sunan içeriklerle sınırlar ve müşterilere tercihlerini kontrol etme imkânı veririm.",score:100,feedbackText:"Değer odaklı kişiselleştirme + kontrol = güvenilir marka."},{text:"Kişiselleştirme satışı artırıyor, her veriyi kullanırım.",score:-100,feedbackText:"Müdahaleci kişiselleştirme güven ve bağlılığı azaltabilir."},{text:"Genel kampanya gönderirim, kişiselleştirme karmaşık.",score:0,feedbackText:"Genel iyi ama değer odaklı kişiselleştirme rekabet avantajı sağlar."}] },
  { cat:"ai-sales-marketing", d:1, s:"Yapay zeka içerik oluşturuyor ve performans metrikleriniz artıyor. Ama içerik giderek daha genel ve kişiliksiz hissettiriyor.", t:"Metrik artışı her zaman marka değeri artışı değildir.", options:[{text:"Metriklerle birlikte marka sesi uyumunu ve okuyucu bağlılık kalitesini de ölçerim.",score:100,feedbackText:"Nicel ve nitel ölçüm birlikte gerçek resmi verir."},{text:"Metrikler artıyorsa içerik işe yarıyor demektir.",score:-100,feedbackText:"Kısa vadeli artış uzun vadeli marka aşınmasını gizleyebilir."},{text:"İçeriği daha kişisel yapacak zaman yok, metrik yeterli.",score:0,feedbackText:"Küçük kişisel dokunuşlar büyük marka fark yaratabilir."}] },
  { cat:"ai-sales-marketing", d:2, s:"Yapay zeka reklam hedeflemesi için demografik veri kullanıyor ve belirli yaş gruplarını dışlıyor.", t:"Demografik hedefleme fırsatları ve sorumlulukları birlikte getirir.", options:[{text:"Hedeflemenin hangi gruplara erişemediğini değerlendirir ve dışlanan segmentlerin potansiyelini analiz ederim.",score:100,feedbackText:"Fırsat analizi + etik değerlendirme birlikte çalışır."},{text:"Bütçe kısıtlı, yüksek dönüşüm segmentine odaklanmak mantıklı.",score:0,feedbackText:"Makul ama demografik dışlama hukuki ve etik riskler taşıyabilir."},{text:"Algoritma en iyi hedefi seçiyor, müdahale etmem.",score:-100,feedbackText:"Algoritma tercihleri sizin tercihleriniz olarak hesap verebilirsiniz."}] },
  { cat:"ai-sales-marketing", d:3, s:"Yapay zeka satış temsilcilerini müşteri görüşmelerinde gerçek zamanlı olarak yönlendiriyor. Temsilciler kendi kararlarını veremediğini hissediyor.", t:"Gerçek zamanlı yönlendirme destekleyici olmalı, kısıtlayıcı değil.", options:[{text:"Sistemi temsilci performansını düşürüp düşürmediği açısından değerlendiririm ve geri bildirime dayalı iyileştirme yaparım.",score:100,feedbackText:"Araç özerkliği desteklemeli, azaltmamalı."},{text:"Sistem daha iyi sonuç üretiyorsa temsilci hissi önemli değil.",score:-100,feedbackText:"Temsilci motivasyonu satış kalitesini uzun vadede etkiler. Önemsemek gerekli."},{text:"Temsilciler zamanla adapte olur.",score:0,feedbackText:"Adaptasyon mümkün ama memnuniyetsizlik gizli çıkış maliyeti yaratır."}] },
  { cat:"ai-sales-marketing", d:2, s:"Yapay zeka müşteri yolculuğunu analiz ederek hangi adımda müşteri kaybettiğinizi gösteriyor ama neden kaybettiğinizi açıklamıyor.", t:"Veri ne olduğunu gösterir, neden sorusu insan araştırması gerektirir.", options:[{text:"Kayıp noktasında müşterilerle görüşmeler yapar, neden kaybettiklerini doğrudan sorarım.",score:100,feedbackText:"Nicel veri + nitel araştırma = tam resim."},{text:"Kayıp noktasını tespit ettim, oraya teknik iyileştirme yaparım.",score:0,feedbackText:"İyileştirme doğru ama neden sorusunu yanıtlamadan tekrar aynı sorunu yaşayabilirsiniz."},{text:"Yapay zeka neden de söylemeli, tam veri değil.",score:0,feedbackText:"Neden sorusu genellikle insan araştırması gerektirir. Bu yapay zekanın sınırı değil, araştırma tasarımının gereği."}] },
  { cat:"ai-sales-marketing", d:1, s:"Yapay zeka sosyal medya yorumlarınızı otomatik olarak yanıtlıyor. Bazı yanıtlar bağlamı kaçırıyor.", t:"Otomasyon hızlıdır ama ince bağlam insan denetimi gerektirir.", options:[{text:"Duyarlı veya bağlam gerektiren yorumları insan denetimine yönlendiren bir filtre kurarım.",score:100,feedbackText:"Akıllı hibrit sistem hem hızlı hem kaliteli."},{text:"Çoğu yanıt iyi, birkaç hata kabul edilebilir.",score:0,feedbackText:"Sosyal medyada bağlam hatası marka itibarını olumsuz etkileyebilir."},{text:"Tüm yorumları kendim yanıtlarım, otomasyona güvenmem.",score:0,feedbackText:"Manuel yönetim sürdürülemez. Akıllı filtreyle otomasyon daha dengeli."}] },
  { cat:"ai-sales-marketing", d:2, s:"Yapay zeka fiyatlandırma optimizasyonu yapıyor ve bazı müşteri segmentlerine farklı fiyatlar gösteriyor. Bunu siz fark etmediniz.", t:"Dinamik fiyatlandırma stratejisini bilmek ve onaylamak işletme sahibinin sorumluluğu.", options:[{text:"Fiyatlandırma mantığını ve hangi segmentlerin hangi fiyatları gördüğünü anlayıp şeffaf bir politika belirlerim.",score:100,feedbackText:"Kendi sistemini anlamak temel sorumluluğunuz."},{text:"Optimizasyon iyi sonuç üretiyorsa mantığı bilmem şart değil.",score:-100,feedbackText:"Anlamadığınız sisteme sahip çıkamazsınız ve açıklayamazsınız."},{text:"Fiyatlandırma karmaşık, uzmanlara bırakırım.",score:0,feedbackText:"Uzman danışmak iyi ama kendi kararlarınızı anlamak şart."}] },
  { cat:"ai-sales-marketing", d:3, s:"Yapay zeka satış tahminleri üretiyor ve bunlar yönetim kararlarını şekillendiriyor. Ama tahminlerin nasıl üretildiğini kimse bilmiyor.", t:"Anlaşılmayan tahmin sistemi güvensiz karar temeli yaratır.", options:[{text:"Tahminin hangi değişkenlere ve hangi veriye dayandığını öğrenir, güven aralıklarını ve sınırları anlayıp yönetimle paylaşırım.",score:100,feedbackText:"Anlaşılır tahmin sistemi daha güvenilir karar temeli sağlar."},{text:"Tahminler tutarlı çıkıyor, nasıl üretildiği önemli değil.",score:-100,feedbackText:"Geçmiş tutarlılık gelecek koşul değişimlerinde güvence vermez. Anlama kritik."},{text:"Veri bilimciler anlasın, benim işim sonuçları kullanmak.",score:0,feedbackText:"Sonuçları kullananlar temel mantığı anlamalıdır. Kara kutu yönetim riski."}] },
  { cat:"ai-sales-marketing", d:1, s:"Yapay zeka müşteri sadakat programınız için kişiselleştirilmiş ödüller öneriyor. Maliyetler beklenenden yüksek çıkıyor.", t:"Kişiselleştirme karlılıkla dengelenmelidir. Segment ve maliyet analizi şart.", options:[{text:"Hangi müşteri segmentlerinin kişiselleştirilmiş ödüllerden en çok değer ürettiğini analiz eder, yatırımı o gruplara odaklarım.",score:100,feedbackText:"Seçici kişiselleştirme hem değer hem maliyet dengesi sağlar."},{text:"Müşteriler memnun oldukça maliyet önemli değil.",score:-100,feedbackText:"Sürdürülemez maliyet yapısı uzun vadede müşterilere de zarar verir."},{text:"Tüm kişiselleştirmeyi kapatır standart ödül programına dönerim.",score:0,feedbackText:"Tamamen kapatmak yerine karlı segmentlere odaklanmak daha akıllıca."}] },
]

console.log('Total:', ALL.length, 'questions')
for (let i = 0; i < ALL.length; i += 20) {
  const batch = ALL.slice(i, i + 20)
  await insert(batch)
}
