const TOKEN = 'sbp_f314cf27b5b2a01eea48048a7b1c015cc9cf4b42'
const API = 'https://api.supabase.com/v1/projects/amhfxaqolholacanqyas/database/query'

function esc(s) { return s.replace(/'/g, "''") }

async function insert(batch) {
  const values = batch.map(q => {
    const opts = JSON.stringify(q.options).replace(/'/g, "''")
    return `('tr','${q.cat}','${esc(q.s)}','${esc(q.t)}','${opts}'::jsonb,${q.d},'claude',true)`
  }).join(',')
  const sql = `INSERT INTO questions (locale,category,scenario_text,mindset_tip,options,difficulty,generated_by,is_active) VALUES ${values};`
  const r = await fetch(API, {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${TOKEN}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query: sql })
  })
  const d = await r.json()
  if (d.message) { console.error('ERR:', d.message); return false }
  console.log('OK:', batch.length, 'inserted')
  return true
}

const ALL = [
  // ai-security-risk (10)
  { cat:"ai-security-risk", d:2, s:"Bir siber saldırı simülasyonunda yapay zeka saldırı vektörlerini otomatik olarak buluyor. Bu kapasiteyi savunma için kullanmak istiyorsunuz.", t:"Saldırı kapasitesini anlamak savunmayı güçlendirir.", options:[{text:"Yapay zeka tabanlı saldırı tespitini etik çerçevede ve açık onayla savunma sistemine entegre ederim.",score:100,feedbackText:"Kırmızı takım teknikleri savunmayı güçlendirir. Doğru yaklaşım."},{text:"Yapay zekanın saldırı kapasitelerini kullanmak tehlikeli, bu araçları kullanmam.",score:0,feedbackText:"Savunma için kullanmak meşru. Etik çerçeve ve onay şart."},{text:"Bu kapasiteyi başkalarına karşı aktif olarak kullanırım.",score:-100,feedbackText:"Saldırı amacıyla kullanmak yasadışı ve etik dışı."}] },
  { cat:"ai-security-risk", d:1, s:"Yapay zeka phishing e-postalarını tespit ediyor ama bazı meşru e-postalar da engelleniyor. Çalışanlar şikâyetçi.", t:"Güvenlik ve kullanılabilirlik dengelenmelidir. Sıfır hata hedefe ulaşılamaz.", options:[{text:"Yanlış pozitif oranını ölçer, karantina sistemini gözden geçirir ve çalışanlara beyaz liste seçeneği sunarım.",score:100,feedbackText:"Ölçüm + düzeltme + esneklik dengeli güvenlik yönetimi."},{text:"Güvenlik önce, bazı meşru e-postalar engellenebilir.",score:0,feedbackText:"Güvenlik önemli ama fazla engelleme iş süreçlerini bozar. Denge gerekli."},{text:"Çalışanlar şikâyetçi olduğu için sistemi kapatırım.",score:-100,feedbackText:"Sorun sistemi kapatmakla değil, ince ayar yaparak çözülür."}] },
  { cat:"ai-security-risk", d:3, s:"Yapay zeka destekli saldırı araçları giderek ucuzlaşıyor. Küçük şirketiniz için siber güvenlik bütçesi sınırlı.", t:"Küçük bütçe kötü güvenlik anlamına gelmez. Öncelikler doğru belirlenmeli.", options:[{text:"En kritik varlıklarımı belirler, sınırlı bütçeyi bu alanlara odaklar ve ücretsiz açık kaynak araçları değerlendiririm.",score:100,feedbackText:"Kaynak kısıtlı ortamda odak şart. Doğru yaklaşım."},{text:"Büyük şirket değiliz, hedef olmayız.",score:-100,feedbackText:"Küçük işletmeler genellikle daha kolay hedef. Bütçe küçük olsa da önlem şart."},{text:"Sigorta alırım, güvenlik ihlaline karşı kapsam oluşturur.",score:0,feedbackText:"Sigorta tamamlayıcıdır ama ihlali önleme daha değerli."}] },
  { cat:"ai-security-risk", d:2, s:"Yapay zeka ile deepfake ses oluşturan bir dolandırıcı CFO'nuzu taklit etti. Çalışan yanlışlıkla para transferi yaptı.", t:"Deepfake saldırıları doğrulama protokolleri gerektiriyor.", options:[{text:"Tüm finansal transferler için bant dışı doğrulama protokolü (telefon, yüz yüze) oluştururum.",score:100,feedbackText:"Çok kanallı doğrulama deepfake riskini azaltır."},{text:"Çalışanı sorumlu tutar, dikkatli olmalıydı.",score:-100,feedbackText:"Suç çalışanda değil, sistemde. Protokol yoksa bireysel suçlama adil değil."},{text:"Yapay zekayı kullananlar için hukuki işlem başlatırım.",score:0,feedbackText:"Hukuki yol gerekebilir ama önleyici protokol daha önemli."}] },
  { cat:"ai-security-risk", d:1, s:"Yapay zeka kod güvenlik açıklarını otomatik tarıyor. Sistem 50 açık buldu ama hepsini aynı anda kapatmak mümkün değil.", t:"Güvenlik açığı yönetiminde öncelik kritiklik ve olasılığa göre belirlenir.", options:[{text:"Açıkları kritiklik ve sömürülme olasılığına göre sıralar, en tehlikelilerden başlar.",score:100,feedbackText:"Risk önceliklendirme kaynak yönetiminin özü."},{text:"Hepsini bir hafta içinde kapatmak için ekibi zorlarım.",score:0,feedbackText:"İcap ettiğinde baskı yapılabilir ama kritiklik sıralaması olmadan verimli değil."},{text:"Sistem buldu ama henüz saldırı yok, bekleyebilirim.",score:-100,feedbackText:"Tespit edilmiş açık yakında sömürülmüş açık olabilir. Proaktif önlem şart."}] },
  { cat:"ai-security-risk", d:2, s:"Yapay zeka büyük dil modeli API'nize erişen bir uygulamada prompt injection açığı var. Kullanıcılar sistemi manipüle edebiliyor.", t:"Prompt injection yeni bir güvenlik vektörü. Her LLM uygulaması buna hazır olmalı.", options:[{text:"Kullanıcı girdilerini doğrular, sistem promptlarını izole eder ve açığı kapatana kadar riski değerlendiririm.",score:100,feedbackText:"LLM güvenliği geleneksel güvenlikten farklı önlemler gerektirir."},{text:"Büyük dil modeli API'leri bu risklere karşı zaten korumalıdır.",score:-100,feedbackText:"API seviyesinde koruma yetmez. Uygulama katmanı kendi önlemlerini almalı."},{text:"Kullanıcıların bunu fark etmesi zor, büyük risk değil.",score:0,feedbackText:"Güvenlik açıkları kolay keşfedilmesi zor olsa da ciddi risk taşır."}] },
  { cat:"ai-security-risk", d:3, s:"Yapay zekanın ürettiği sentetik verilerle model eğitiyorsunuz. Ama bu veri gerçek veri dağılımını tam yansıtmıyor.", t:"Sentetik veri kalitesi model kalitesini doğrudan etkiler.", options:[{text:"Sentetik veriyi gerçek veriyle kıyaslar, dağılım farklarını ölçer ve modeli gerçek verinin olmadığı alanlarda dikkatle değerlendiririm.",score:100,feedbackText:"Veri kalitesi model kalitesinin belirleyicisi. Doğru yaklaşım."},{text:"Sentetik veri sınırsız, gerçek veriye ihtiyaç yok.",score:-100,feedbackText:"Gerçek dağılımdan kopuk model gerçek dünyada kötü performans gösterir."},{text:"Model iyi sonuçlar üretiyorsa veri kalitesi önemli değil.",score:0,feedbackText:"Kısa vadeli iyi performans dağılım farkını maskeleyebilir. Uzun vadede sorun çıkar."}] },
  { cat:"ai-security-risk", d:1, s:"Çalışanlar kişisel yapay zeka araçlarını iş verisi ile kullanıyor. Şirket politikası henüz yok.", t:"Politikasız kullanım kontrol edilemeyen risktir.", options:[{text:"Hızla bir politika oluşturur, hangi araçların hangi verilerle kullanılabileceğini netleştiririm.",score:100,feedbackText:"Politika önceden değil, zamanında yapılmalı. Doğru öncelik."},{text:"Kullanım verimliliği artırıyor, müdahale etmem.",score:-100,feedbackText:"Politikasız kullanım veri ihlali riskini görünmez kılar."},{text:"Tüm yapay zeka araçlarını yasaklarım.",score:0,feedbackText:"Yasak çözüm değil. Gizli kullanıma yol açar. Çerçeve daha etkili."}] },
  { cat:"ai-security-risk", d:2, s:"Yapay zeka sisteminiz müşteri verilerini işliyor ve bir güvenlik araştırmacısı açık bildirdi. Açığı kabul etmek istemiyorsunuz.", t:"Güvenlik açığını kabul etmek zayıflık değil, sorumluluktur.", options:[{text:"Araştırmacının bulgusunu ciddiye alır, doğrular ve sorumlu açıklama politikasıyla işlerim.",score:100,feedbackText:"Responsible disclosure güvenlik ekosistemini güçlendirir."},{text:"Araştırmacı hata yapıyor, bulgusunu reddederim.",score:-100,feedbackText:"Reddetmek sorunu çözmez ve araştırmacı kamuya açıklayabilir."},{text:"Açığı sessizce kapatır, araştırmacıya yanıt vermem.",score:0,feedbackText:"Sessiz kapatma kısa vadeli ama araştırmacıya yanıt vermek ilişkiyi güçlendirir."}] },
  { cat:"ai-security-risk", d:3, s:"Yapay zeka modeliniz rakip şirketin verilerini yanlışlıkla eğitim verisi olarak kullandı. Bunu sonradan öğrendiniz.", t:"Veri kökeni kritik hukuki ve etik risktir. Şeffaf hareket şart.", options:[{text:"Hukuki danışman alır, durumu değerlendiririm, gerekirse ilgili tarafları bilgilendirir ve modeli yeniden eğitirim.",score:100,feedbackText:"Proaktif şeffaflık ve düzeltme en doğru yol."},{text:"Kimse fark etmeyecek, modeli kullanmaya devam ederim.",score:-100,feedbackText:"Gizlemek hukuki ve itibar riskini katlar."},{text:"Modeli kullanımdan kaldırırım ama kimseye söylemem.",score:0,feedbackText:"Kaldırmak doğru ama etkilenen tarafları bilgilendirmek de gerekebilir."}] },

  // ai-sustainability (10)
  { cat:"ai-sustainability", d:2, s:"Büyük dil modeli kullanımınız karbon ayak izinizi artırıyor. Sürdürülebilirlik hedefleri tehlikede.", t:"AI enerji tüketimi gerçek ve ölçülebilir. Bilinçli kullanım fark yaratır.", options:[{text:"Yapay zeka kullanımımı ölçer, gereksiz sorgulardan kaçınır ve karbon nötr veri merkezi seçeneklerini araştırırım.",score:100,feedbackText:"Ölçüm + azaltma + alternatif arama sürdürülebilir teknoloji yaklaşımı."},{text:"Yapay zeka verimliliği artırıyor, karbon maliyeti kabul edilebilir.",score:0,feedbackText:"Denge önemli ama ölçmeden bilemezsiniz. Somut veri gerekli."},{text:"Karbon ayak izi bireysel ölçekte önemli değil.",score:-100,feedbackText:"Kurumsal ölçekte etki büyük. Bireysel sorumluluğu küçümsemek doğru değil."}] },
  { cat:"ai-sustainability", d:1, s:"Yapay zeka enerji optimizasyon sistemi binalarınızdaki tüketimi yüzde onbeş azaltabileceğini söylüyor.", t:"AI odaklı enerji optimizasyonu doğrulanmış kazanımlar sunar.", options:[{text:"Pilot alanda sistemi test eder, gerçek tasarrufu ölçür ve sonra genişletirim.",score:100,feedbackText:"Pilot önce, ölçek sonra. En güvenilir yaklaşım."},{text:"Yüzde onbeş az gibi görünüyor, daha büyük adımlar ararım.",score:0,feedbackText:"Küçük artış büyük ölçekte önemlidir. Sistemi denemeden küçümsemek erken."},{text:"Mevcut sistemimiz çalışıyor, değiştirmem.",score:-100,feedbackText:"Çalışan sistem ile optimal sistem farklıdır. Değerlendirme şart."}] },
  { cat:"ai-sustainability", d:2, s:"Tedarik zinciri yapay zeka analizi çevresel açıdan sorunlu bir tedarikçiyi işaret ediyor. Ama bu tedarikçiyle 10 yıllık ilişkiniz var.", t:"Sürdürülebilirlik kararları ilişkisel baskı altında da verilmelidir.", options:[{text:"Tedarikçiyle çevresel sorunları açıkça görüşür, iyileştirme taahhüdü bekler ve gerekirse alternatif ararım.",score:100,feedbackText:"Diyalog + hesap verebilirlik + seçenek. Dengeli yaklaşım."},{text:"İlişkimiz değerli, çevresel iyileştirme için zaman tanırım.",score:0,feedbackText:"Zaman tanımak makul ama somut taahhüt ve süre belirlenmeli."},{text:"Çevresel sorunları benim işim değil, tedarikçi halleder.",score:-100,feedbackText:"Tedarik zinciri etkisi sizin sürdürülebilirlik profilinizi şekillendirir."}] },
  { cat:"ai-sustainability", d:3, s:"Yapay zeka tarım optimizasyonu sulama miktarını düşürmeyi öneriyor ama çiftçiler bu değişiklikten endişeli.", t:"Veri odaklı tarım yerel bilgiyle birleşince en güçlü sonucu verir.", options:[{text:"Öneriyi küçük bir parselde çiftçilerle birlikte test eder, sonuçları birlikte değerlendiririm.",score:100,feedbackText:"Yerel bilgi + veri = güçlü hibrit karar."},{text:"Yapay zeka veriyi analiz etti, çiftçiler adapte olur.",score:-100,feedbackText:"Yerel bilgiyi görmezden gelmek hem etik hem pratik sorun yaratır."},{text:"Çiftçiler rahatsızsa öneriyi iptal ederim.",score:0,feedbackText:"İptal yerine test etmek hem veriyi hem çiftçileri dinlemek anlamına gelir."}] },
  { cat:"ai-sustainability", d:1, s:"Yapay zeka raporlama sisteminiz şirketin çevresel etki verilerini otomatik hesaplıyor. İlk rapor hazır.", t:"Otomatik raporlar doğrulama gerektiriyor. Çevresel veri hesap verebilirlik taşır.", options:[{text:"Raporu uzman ekiple gözden geçirir, veri kaynaklarını doğrular ve metodoloji notlarıyla birlikte yayınlarım.",score:100,feedbackText:"Doğrulanmış veri yeşil yıkama riskini azaltır."},{text:"Sistem hesapladı, doğrudan yayınlarım.",score:-100,feedbackText:"Doğrulanmamış çevresel iddia yeşil yıkama suçlamasına yol açabilir."},{text:"Raporu iç kullanım için saklarım, kamuya açıklamam.",score:0,feedbackText:"İç kullanım başlangıç ama kamuoyu şeffaflık bekliyor."}] },
  { cat:"ai-sustainability", d:2, s:"Yapay zeka ürün tasarımında malzeme seçimini optimize ediyor ama bazı sürdürülebilir seçenekler daha pahalı.", t:"Sürdürülebilirlik maliyeti ve uzun vadeli değer birlikte hesaplanmalı.", options:[{text:"Kısa vadeli maliyet ile uzun vadeli çevresel etki ve marka değerini birlikte hesaplarım.",score:100,feedbackText:"Toplam maliyet analizi kısa vadeli bakıştan daha doğru karar sağlar."},{text:"Maliyet önce, sürdürülebilirlik gelir.",score:0,feedbackText:"Kısa vadeli düşünce uzun vadeli fırsatları ve riskleri kaçırır."},{text:"Sürdürülebilir malzeme kullanmak rakiplere karşı dezavantaj.",score:-100,feedbackText:"Tüketici tercihleri ve regülasyonlar sürdürülebilirliği rekabet avantajına dönüştürüyor."}] },
  { cat:"ai-sustainability", d:1, s:"Yapay zeka çalışanların seyahat ihtiyaçlarını analiz ederek toplu taşıma ve video konferans alternatifleri öneriyor.", t:"Küçük davranış değişiklikleri toplamda büyük etki yaratır.", options:[{text:"Öneriyi çalışanlarla paylaşır, uygulamayı teşvik eder ve alternatif ulaşım için kolaylaştırıcı destek sunarım.",score:100,feedbackText:"Teşvik ve kolaylaştırıcı destek birlikte davranış değişimi sağlar."},{text:"Seyahat çalışanların kararı, müdahale etmem.",score:0,feedbackText:"Doğru ama kurumsal teşvik ve kolaylaştırıcılık fark yaratabilir."},{text:"Video konferans verimliliği düşürüyor, seyahati desteklerim.",score:-100,feedbackText:"Verimliliği koruyan alternatifleri değerlendirmeden reddetmek erken karar."}] },
  { cat:"ai-sustainability", d:3, s:"Yapay zeka şirketin net sıfır hedefleri için karbon ofset önerileri sunuyor. Ama bazı ofset projeleri tartışmalı.", t:"Karbon ofset kalitesi büyük farklılık gösterir. Araştırma şart.", options:[{text:"Her ofset projesini bağımsız sertifikasyon ve ölçülebilir etki açısından değerlendiririm.",score:100,feedbackText:"Ofset kalitesi kadar önemlidir. Doğru değerlendirme şart."},{text:"Ofset aldık, yükümlülüğümüzü yerine getirdik.",score:-100,feedbackText:"Kalitesiz ofset yeşil yıkamadır. Gerçek etki şart."},{text:"Önce emisyonu azaltmak, ofset son çare.",score:0,feedbackText:"Doğru sıralama ama azaltma yetersizse kaliteli ofset tamamlayıcı."}] },
  { cat:"ai-sustainability", d:2, s:"Yapay zeka akıllı şehir altyapısı enerji tüketimini optimize ediyor ama elde edilen tasarruf sakin mahalle konuklarına yansıtılmıyor.", t:"Teknoloji faydası eşit dağılmalıdır, aksi takdirde eşitsizliği artırır.", options:[{text:"Tasarrufların hangi alanlara yönlendirileceğini savunur, özellikle dezavantajlı mahallelere öncelik verilmesini talep ederim.",score:100,feedbackText:"Teknoloji faydası adalet perspektifiyle dağıtılmalı."},{text:"Tasarruf belediye bütçesine katkı, yeterince fayda.",score:0,feedbackText:"Genel fayda eşitsizliği maskeleyebilir. Dağılım şeffaflığı gerekli."},{text:"Mahalle bazlı dağılım çok karmaşık, genel iyileştirme yeterli.",score:-100,feedbackText:"Karmaşıklık çözümsüzlük gerekçesi değil. Adalet kritik."}] },
  { cat:"ai-sustainability", d:1, s:"Yapay zeka e-atık tahmini yapıyor ve şirketinizin yakında büyük miktarda elektronik cihaz atığı üreteceğini söylüyor.", t:"Atık tahmini önlem almanın başlangıcıdır.", options:[{text:"Yenileme planlarını gözden geçirir, cihaz ömrünü uzatma stratejileri ve yetkili e-atık geri dönüşüm partnerleri belirlerim.",score:100,feedbackText:"Tahmin + önlem + sorumluluk zinciri. Tam sürdürülebilirlik yaklaşımı."},{text:"Her şirket e-atık üretiyor, bu normal.",score:-100,feedbackText:"Normal olmak sorumluluğu ortadan kaldırmaz."},{text:"Atık yasal yollarla bertaraf ediliyor zaten.",score:0,feedbackText:"Yasal bertaraf minimum. Azaltma ve geri dönüşüm daha değerli."}] },

  // ai-tools-comparison (10)
  { cat:"ai-tools-comparison", d:1, s:"ChatGPT mi, Claude mu yoksa Gemini mi kullanacağınıza karar veremiyorsunuz. Her biri farklı güçlere sahip.", t:"Tek araç her göreve uygun değil. Görev bazlı araç seçimi daha verimli.", options:[{text:"Her aracı farklı görev türleri için deneyip hangi göreve hangi aracın daha iyi uyduğunu test ederim.",score:100,feedbackText:"Karşılaştırmalı değerlendirme en doğru seçim yöntemi."},{text:"En popüler olanı seçer, herkes kullanıyorsa iyidir.",score:-100,feedbackText:"Popülerlik kendi ihtiyacınıza uygunluğun göstergesi değil."},{text:"Hepsini aynı anda kullanırım, hangisi iyi sonuç verirse onu tutarım.",score:0,feedbackText:"Çoklu kullanım başlangıç için iyi ama sistematik değerlendirme daha verimli."}] },
  { cat:"ai-tools-comparison", d:2, s:"Şirketiniz için yapay zeka araç setini değerlendiriyorsunuz. Satıcılar kendi ürünlerini en iyi olarak tanıtıyor.", t:"Satıcı iddiaları bağımsız değerlendirmeyle doğrulanmalıdır.", options:[{text:"Bağımsız kıyaslama testleri yapar, referans müşterilerle konuşur ve ücretsiz pilot uygularım.",score:100,feedbackText:"Bağımsız doğrulama satıcı söyleminden çok daha güvenilir."},{text:"En ünlü markayı seçerim, güvenilirdir.",score:0,feedbackText:"Marka güveni değerli ama kendi ihtiyacınıza uygunluğu test etmek şart."},{text:"En ucuz olanı alırım, tüm araçlar benzer.",score:-100,feedbackText:"Araçlar arasındaki farklar gerçek ve önemli. Maliyet tek kriter değil."}] },
  { cat:"ai-tools-comparison", d:1, s:"Kullandığınız yapay zeka aracını başkasının önerisiyle değiştirmeyi düşünüyorsunuz. Ama mevcut araç işinizi görüyor.", t:"Değişim maliyeti var. Geçişin gerçek faydası ölçülmeli.", options:[{text:"Yeni aracı ücretsiz plan veya denemede test eder, mevcut araçla karşılaştırır ve somut fark varsa geçerim.",score:100,feedbackText:"Pilot karşılaştırma en sağlıklı karar verme yöntemi."},{text:"Öneri iyi geldiyse hemen geçerim.",score:-100,feedbackText:"Geçiş öğrenme maliyeti ve iş akışı değişimi gerektirir. Gerçek faydayı test edin."},{text:"Mevcut araç yeterliyse hiç değiştirmem.",score:0,feedbackText:"Yeterli ile daha iyi arasındaki fark bazen büyük olabilir. Test etmek değer."}] },
  { cat:"ai-tools-comparison", d:2, s:"Kod yazmak için farklı yapay zeka araçlarını karşılaştırıyorsunuz. Sonuçlar çok farklı.", t:"Kod araçları görev türüne, dile ve bağlama göre farklı performans gösterir.", options:[{text:"Gerçek iş senaryolarımla her aracı test eder, hata oranı ve kod kalitesini kıyaslarım.",score:100,feedbackText:"Gerçek senaryo testi en anlamlı kıyaslama yöntemi."},{text:"Diğer geliştiricilerin kullandığı aracı kullanırım.",score:0,feedbackText:"Topluluk desteği değerli ama kendi kullanım kalıplarınızı test etmek daha doğru."},{text:"İlk denediğim iyiydi, araştırma yapmama gerek yok.",score:-100,feedbackText:"İlk iyi daha iyi seçeneği keşfetmenizi engelleyebilir."}] },
  { cat:"ai-tools-comparison", d:3, s:"Şirketiniz yapay zeka platformu seçiminde maliyeti öncelikli kriterle değerlendiriyor. Ama performans farkı anlamlı.", t:"Düşük maliyet kötü performans karşısında uzun vadede pahalıya patlar.", options:[{text:"Toplam sahip olma maliyetini hesaplarım: lisans + insan zamanı + hata maliyeti + yeniden çalışma.",score:100,feedbackText:"Tam maliyet analizi yüzey fiyatından daha doğru karar sağlar."},{text:"Bütçe kısıtlı, ucuz seçenek şart.",score:0,feedbackText:"Kısıt gerçek ama toplam maliyet ucuz aracın daha pahalı olduğunu gösterebilir."},{text:"Maliyeti düşük tutmak rekabetçi avantaj, performans kabul edilebilir.",score:-100,feedbackText:"Düşük performans iş çıktısını etkiler ve uzun vadede daha fazla maliyet yaratır."}] },
  { cat:"ai-tools-comparison", d:2, s:"Yapay zeka araçlarınızı karşılaştırdınız ve en iyi sonucu veren aracın kişisel veri politikası endişe verici.", t:"Performans ve gizlilik birlikte değerlendirilmeli. İkisinden biri feda edilemez.", options:[{text:"Performans kaybını kabul ederek gizlilik politikası daha sağlıklı olan alternatifi kullanırım.",score:100,feedbackText:"Veri güvenliği uzun vadede performanstan daha önemli olabilir."},{text:"Performansı için veri politikasına katlanırım.",score:0,feedbackText:"Kabul edebilir ama riskleri bilmek ve sınırlamak önemli."},{text:"Tüm araçların veri politikaları zaten sorunlu, fark etmez.",score:-100,feedbackText:"Farklılıklar gerçek ve önemli. Pasif kabul riski artırır."}] },
  { cat:"ai-tools-comparison", d:1, s:"Yapay zeka metin oluşturma araçlarını karşılaştırıyorsunuz ama hangisinin daha iyi olduğuna karar veremiyorsunuz.", t:"Genel sıralama değil, kendi kullanım durumunuz için en iyi hangisi sorusu doğru soru.", options:[{text:"Kendi yazım görevlerime özel bir kıyaslama seti oluştururum ve sonuçları değerlendiririm.",score:100,feedbackText:"Görev odaklı değerlendirme genel sıralamadan daha değerli."},{text:"İnternetteki en iyi listeye bakarım.",score:0,feedbackText:"Listeler başlangıç noktası olabilir ama kendi görevlerinizle test etmek şart."},{text:"Hepsini karıştırırım, farklı bölümler için farklı araç kullanırım.",score:0,feedbackText:"Çoklu araç yapılabilir ama verimlilik açısından baskın aracı belirlemek daha iyi."}] },
  { cat:"ai-tools-comparison", d:2, s:"Ekibiniz birden fazla yapay zeka aracı kullanıyor. Araçlar arasında veri paylaşımı olmuyor ve verimlilik sorunu var.", t:"Araç parçalanması entegrasyon kaybı yaratır. Ekosistem yaklaşımı daha etkili.", options:[{text:"Araçları entegre eden veya veri akışını sağlayan bir merkezi platform değerlendiririm.",score:100,feedbackText:"Entegre ekosistem parçalı araçlar toplamından daha verimli."},{text:"Herkes kendi aracını kullansın, farklılık yaratıcılığı artırır.",score:0,feedbackText:"Çeşitlilik değerli ama entegrasyonsuz parçalanma verimliliği düşürür."},{text:"Hepsini kaldırır tek bir araca geçerim.",score:0,feedbackText:"Standartlaştırma iyi ama hangi tek aracın ihtiyaçları karşılayacağını değerlendirin."}] },
  { cat:"ai-tools-comparison", d:3, s:"Yapay zeka modeli karşılaştırmasında bir model matematiksel hesaplamada çok iyi ama yaratıcı yazımda zayıf. Diğeri tam tersi.", t:"Farklı modeller farklı güçlere sahip. Görev eşleşmesi sonucu belirler.", options:[{text:"Her model türünü en güçlü olduğu görev türüyle eşleştiren bir iş akışı tasarlarım.",score:100,feedbackText:"Görev-model eşleşmesi maksimum değer çıkarır."},{text:"Tek modelde kalmak daha tutarlı, ikisini kullanmak karmaşık.",score:0,feedbackText:"Karmaşıklık yönetilebilir. Doğru araç doğru iş için önemli."},{text:"Daha iyi bir model çıkana kadar beklerim.",score:-100,feedbackText:"Mükemmeli beklemek fırsatı kaçırır. Mevcut en iyi seçenek yeterlidir."}] },
  { cat:"ai-tools-comparison", d:1, s:"Yapay zeka araçlarından biri güncellemesinde önemli bir özelliği kaldırdı. İş akışınız etkilendi.", t:"Araç bağımlılığı risk taşır. Esneklik stratejisi önemli.", options:[{text:"Alternatifleri araştırır ve kritik özellikler için tek araca bağımlı olmamayı sağlayan bir yedekleme planı oluştururum.",score:100,feedbackText:"Araç çeşitlendirmesi tek nokta bağımlılığını azaltır."},{text:"Şikâyet ederim, özelliği geri getirsinler.",score:0,feedbackText:"Geri bildirim değerli ama alternatif plan yapmak daha güvenli."},{text:"Yeni iş akışına adapte olacağım, sorun yok.",score:0,feedbackText:"Adaptasyon iyi ama kırılganlığı azaltmak için yedekleme da önemli."}] },

  // automation-agents (10)
  { cat:"automation-agents", d:2, s:"Yapay zeka ajanınız otonom kararlar alıyor ve zaman zaman beklenmedik aksiyonlar gerçekleştiriyor.", t:"Otonom ajanlar net kapsam, sınır ve denetim mekanizmaları gerektirir.", options:[{text:"Ajanın hareket alanını netleştiren kurallar koyar, kritik aksiyonlar için insan onayı gereksinimi eklerim.",score:100,feedbackText:"Ajan özerkliği + insan denetimi = güvenli otomasyon."},{text:"Otonom olması verimliliği artırıyor, beklenmedik aksiyonlar kabul edilebilir.",score:-100,feedbackText:"Beklenmedik aksiyon kontrol kaybı sinyali. Risk değerlendirmesi şart."},{text:"Ajanı tamamen kapatırım, otomasyon güvenilmez.",score:0,feedbackText:"Kapatmak yerine sınırları belirlemek daha değerli."}] },
  { cat:"automation-agents", d:1, s:"Yapay zeka ajan takımı kuruyorsunuz ama ajanlar arasındaki koordinasyon çöküyor.", t:"Çoklu ajan sistemleri koordinasyon tasarımı gerektirir.", options:[{text:"Ajanlar arasındaki veri akışını ve sorumluluk sınırlarını net şekilde tanımlarım.",score:100,feedbackText:"Koordinasyon mimarisi çoklu ajan güvenilirliğinin temelidir."},{text:"Daha fazla ajan eklerim, birileri işi tamamlar.",score:-100,feedbackText:"Koordinasyonsuz ajan ekleme kaosa yol açar."},{text:"Ajanları sıralı çalıştırırım, paralel yerine.",score:0,feedbackText:"Sıralı çalışma basit ama paralelliğin avantajını kaçırır. Koordinasyon tasarlanabilir."}] },
  { cat:"automation-agents", d:3, s:"Otomasyon ajanınız müşteriye yanlış bilgi verdi. Müşteri bu bilgiyle önemli bir karar aldı.", t:"Otonom hatalar insani sorumluluk gerektirir. Sistem + kişi birlikte yanıt vermeli.", options:[{text:"Müşteriye doğru bilgiyi veririm, sorumluluğu üstlenirim ve ajanın hata kaynağını düzeltirim.",score:100,feedbackText:"Şeffaflık + sorumluluk + düzeltme. Doğru sıralama."},{text:"Sistem verdi, ben değil — sorumluluk bende değil.",score:-100,feedbackText:"Sistemi konuşlandıran olarak sorumluluk sizde. Bu savunma işe yaramaz."},{text:"Müşteriye kendi araştırmasını yapması gerektiğini söylerim.",score:0,feedbackText:"Doğrulama tavsiyesi iyi ama önce hatayı kabul etmek şart."}] },
  { cat:"automation-agents", d:2, s:"Yapay zeka iş akışı ajananı belgeleri otomatik olarak işliyor. Bazı belgeler gizli sınıflandırmaya sahip.", t:"Otomasyon gizli veriyle çalışırken erişim kontrolü kritik.", options:[{text:"Ajanın yalnızca erişim yetkisi olan belgeleri işleyebilmesini güvence altına alırım.",score:100,feedbackText:"Otomasyon erişim kontrolünü atlamamalı."},{text:"Ajan herkese açık arayüzden çalışıyor, güvenlik sorun değil.",score:-100,feedbackText:"Arayüz erişimi ile veri erişim yetkisi aynı değil. Kontrol gerekli."},{text:"Gizli belgeleri ayrı bir sistemde tutarım, ajan ulaşamaz.",score:0,feedbackText:"Ayrıştırma iyi ama genel erişim politikasını da gözden geçirmek gerekir."}] },
  { cat:"automation-agents", d:1, s:"Yapay zeka ajananız e-postalarınızı otomatik yanıtlıyor. Bir müşteriye yanlış bilgi içeren yanıt gönderildi.", t:"Otomasyon kalite kontrolünü ortadan kaldırmaz.", options:[{text:"Gönderilen e-postaları düzenli örnekleme ile kontrol eder ve kritik müşteriler için onay adımı eklerim.",score:100,feedbackText:"Örnekleme + kritik onay hibrit bir denetim sağlar."},{text:"Ajan genellikle doğru, nadir hata kabul edilebilir.",score:0,feedbackText:"Müşteri iletişiminde hata oranı sıfıra yakın olmalı. Denetim şart."},{text:"Yanıtları tamamen insan yazacak, otomasyon kapatılıyor.",score:0,feedbackText:"Kapatmak yerine denetimi güçlendirmek daha verimli."}] },
  { cat:"automation-agents", d:2, s:"Yapay zeka ajananız veri tabanınızda değişiklik yapma yetkisine sahip. Bir hata tüm müşteri verilerini etkileyebilir.", t:"Yüksek etkili aksiyonlar için geri döndürülebilirlik ve onay mekanizması şart.", options:[{text:"Ajana yalnızca salt okunur yetki veririm; yazma işlemleri için insan onayı gerektirir.",score:100,feedbackText:"En az yetki prensibi otomasyon güvenliğinin temelidir."},{text:"Ajan güvenilir, tam yetki verebilirim.",score:-100,feedbackText:"Güven yetmez. Hata tek bir karar anında felakete yol açabilir."},{text:"Yedekleme sistemi var, büyük sorun olmaz.",score:0,feedbackText:"Yedekleme iyileştirir ama önlemek daha iyi. Yetki sınırlaması şart."}] },
  { cat:"automation-agents", d:3, s:"Yapay zeka araştırma ajanınız internette özerkçe bilgi topluyor. Toplanan bilginin kaynağı güvenilir değil.", t:"Otonom bilgi toplama kaynağın doğruluğunu garanti etmez.", options:[{text:"Ajanın kullandığı kaynakları günlük olarak gözden geçirir ve güvenilmez kaynak listesi oluştururum.",score:100,feedbackText:"Kaynak kalitesi bilgi kalitesini belirler. Sürekli denetim şart."},{text:"Ajan internetten alıyor, taraflı olmaz.",score:-100,feedbackText:"İnternet tarafsız değil. Kaynak kalitesi ajan çıktısını doğrudan etkiler."},{text:"Bilgiyi her zaman ikinci kaynakla doğrularım.",score:0,feedbackText:"Doğrulama iyi ama önceden kaynak filtresi de şart."}] },
  { cat:"automation-agents", d:1, s:"Yapay zeka otomasyon ajananız haftalık raporlar hazırlıyor. Raporlar doğru ama kimse artık okumadan imzalıyor.", t:"Otomasyon insan dikkatini azaltabilir. Kritik belgeler aktif gözlem gerektirir.", options:[{text:"Raporların kritik bölümlerini vurgulayan bir özet ekler ve aylık rastgele derin denetim uygularım.",score:100,feedbackText:"Dikkat yönetimi otomasyon çağında yeni bir beceri."},{text:"Sistem doğru çıktı üretiyor, imzalamak yeterli.",score:-100,feedbackText:"Anlamadan imzalamak imzacının sorumluluğunu ortadan kaldırmaz."},{text:"Rapor hazırlamayı tekrar insanlara veririm.",score:0,feedbackText:"Önce denetim mekanizmasını güçlendirmek daha verimli."}] },
  { cat:"automation-agents", d:2, s:"Yapay zeka satın alma ajanınız otomatik sipariş veriyor. Bütçe limitini beklenmedik şekilde aştı.", t:"Otonom finansal aksiyonlar bütçe kontrol mekanizmaları gerektirir.", options:[{text:"Ajana harcama limitleri ve onay eşiği tanımlar, limit aşımında otomatik duraklatma eklerim.",score:100,feedbackText:"Finansal otomasyon kontrol mekanizmaları olmadan riskli."},{text:"Ajana limit vermek verimliliği düşürür.",score:-100,feedbackText:"Limit verimliliği değil, kontrolsüz riski sınırlar."},{text:"Limiti sonradan düzeltirim, bu seferlik kabul.",score:0,feedbackText:"Sonradan düzeltmek iyileştirir ama önleyici mekanizma şart."}] },
  { cat:"automation-agents", d:3, s:"Yapay zeka çoklu ajan sisteminiz bir iş sürecini tamamen devraldı. Ekip artık sürecin nasıl çalıştığını bilmiyor.", t:"Kurumsal bilgi kaybı uzun vadede büyük kırılganlık yaratır.", options:[{text:"Sürecin nasıl çalıştığını belgeler, ekibi bu bilgiyle donatır ve manuel yedek prosedür oluştururum.",score:100,feedbackText:"Otomasyon kurumsal bilgiyi değil, manuel yükü almalıdır."},{text:"Sistem çalışıyor, ekibin bilmesine gerek yok.",score:-100,feedbackText:"Sistem çöktüğünde hiç kimse devam ettiremez. Bilgi kaybı kritik risk."},{text:"Yeni personel işe alırım, sistem onlara anlatsın.",score:0,feedbackText:"Sistemin kendini anlatması güvenilmez. Belgeleme insan tarafından yapılmalı."}] },
]

console.log('Total:', ALL.length, 'questions')
for (let i = 0; i < ALL.length; i += 20) {
  const batch = ALL.slice(i, i + 20)
  await insert(batch)
}
