const TOKEN = 'sbp_f314cf27b5b2a01eea48048a7b1c015cc9cf4b42'
const API = 'https://api.supabase.com/v1/projects/amhfxaqolholacanqyas/database/query'

function esc(s) { return s.replace(/'/g, "''") }

async function insert(batch) {
  const values = batch.map(q => {
    const opts = JSON.stringify(q.options).replace(/'/g, "''")
    return `('tr','${q.cat}','${esc(q.s)}','${esc(q.t)}','${opts}'::jsonb,${q.d},'claude',true)`
  }).join(',')
  const sql = `INSERT INTO questions (locale,category,scenario_text,mindset_tip,options,difficulty,generated_by,is_active) VALUES ${values};`
  const r = await fetch(API, {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${TOKEN}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query: sql })
  })
  const d = await r.json()
  if (d.message) { console.error('ERR:', d.message); return false }
  console.log('OK:', batch.length, 'inserted')
  return true
}

const ALL = [
  // ai-education (10)
  { cat:"ai-education", d:1, s:"Öğrencileriniz yapay zekayı ödevlerinde kullanıyor. Bunu nasıl değerlendirirsiniz?", t:"Araç kullanımı bir beceridir. Asıl soru: öğrenci neyi öğrendi?", options:[{text:"Yapay zekayla nasıl çalıştıklarını, süreci nasıl değerlendirdiklerini sorarım.",score:100,feedbackText:"Eleştirel kullanım öğrenmeyi destekler. Doğru yaklaşım."},{text:"Yapay zeka kullanımını tamamen yasaklarım.",score:-100,feedbackText:"Yasak gerçeklikten kopuk — öğrenciler okul dışında da kullanacak."},{text:"Fark etmez, sonuç doğruysa sorun yok.",score:0,feedbackText:"Sonuç tek kriter değil. Süreç ve anlama da öğrenmenin parçası."}] },
  { cat:"ai-education", d:2, s:"Yapay zeka destekli kişiselleştirilmiş öğrenme sistemi size sunuldu. Ama öğretmenlerin rolünün azalacağından endişelisiniz.", t:"Teknoloji öğretmeni destekler, yerini alamaz. İnsani ilişki öğrenmede kritiktir.", options:[{text:"Sistemi denerim ama öğretmen-öğrenci ilişkisini merkeze alan bir tasarımda kullanırım.",score:100,feedbackText:"Hibrit yaklaşım en güçlü öğrenme ortamını yaratır."},{text:"Öğretmen rolünü korumak için sistemi reddederim.",score:-100,feedbackText:"Reddetmek fırsatı kaçırmak demek. Sistemi doğru konumlandırmak daha iyi."},{text:"Sistemi olduğu gibi devreye alırım, öğretmenler adapte olur.",score:0,feedbackText:"Adapte olmak zor olabilir. Öğretmenlerin sürece dahil edilmesi şart."}] },
  { cat:"ai-education", d:1, s:"Öğrenciler yapay zekadan aldıkları cevapları kaynak göstermeden sunuyor. Akademik dürüstlük sorunu mu?", t:"Yapay zeka bir araç — ama şeffaflık akademik dürüstlüğün parçası.", options:[{text:"Öğrencilere yapay zeka kullanımını nasıl şeffaf şekilde belgeleyeceklerini öğretirim.",score:100,feedbackText:"Doğru — alet kutusunu açıkça göstermek akademik bir beceri."},{text:"Yapay zeka kullanımı tespit edilen tüm ödevleri sıfır puanla değerlendiririm.",score:-100,feedbackText:"Yasaklama teknolojik gerçeklikle çelişiyor. Kullanım becerisini değerlendirmek daha iyi."},{text:"Bu kadar detay çok zaman alır, önemsemem.",score:0,feedbackText:"Akademik dürüstlük uzun vadeli beceridir. Küçük adımlar büyük fark yaratır."}] },
  { cat:"ai-education", d:2, s:"Bir yapay zeka eğitim platformu öğrencilerin öğrenme verilerini topluyor. Veliler endişeli.", t:"Çocuk verisi hassastır — şeffaflık ve onay zorunlu, performans ikincil.", options:[{text:"Hangi verilerin toplandığını, nasıl kullanıldığını ve kim tarafından erişildiğini veli toplantısında açıklarım.",score:100,feedbackText:"Şeffaflık güven inşa eder. Zorunlu ve doğru yaklaşım."},{text:"Veriler eğitimi iyileştiriyor, veliler abartıyor.",score:-100,feedbackText:"Veli kaygısı meşru. Çocuk verisinde şeffaflık tartışılmaz."},{text:"Onay formunu imzalatırım, yeterli.",score:0,feedbackText:"Form başlangıç ama gerçek şeffaflık detayları da içermeli."}] },
  { cat:"ai-education", d:3, s:"Yapay zeka sayesinde bazı öğrenciler çok hızlı ilerliyor, diğerleri geride kalıyor. Sınıfta eşitsizlik artıyor.", t:"Araç erişimi eşit olmalı — aksi takdirde teknoloji eşitsizliği derinleştirir.", options:[{text:"Tüm öğrencilerin araçlara erişimini sağlarım ve dijital okuryazarlığı sınıfın tamamı için odak haline getiririm.",score:100,feedbackText:"Eşit erişim + ortak temel = fırsat eşitliği."},{text:"Hızlı öğrenenleri öne çıkarırım, rekabet motivasyonu artırır.",score:-100,feedbackText:"Rekabet bazılarını motive ederken çoğunluğu demotive edebilir."},{text:"Yapay zeka kullanımını durdururum, herkes eşit yavaşlasın.",score:0,feedbackText:"Geri çekmek sorunu çözmez. Erişimi ve becerileri eşitlemek daha iyi."}] },
  { cat:"ai-education", d:1, s:"Yapay zeka ders notları özetliyor. Öğrenciler artık derste daha az not tutuyor.", t:"Not tutma bir öğrenme sürecidir — sadece kayıt değil.", options:[{text:"Öğrencilere not tutmanın bilişsel değerini anlatır, yapay zekayı ek kaynak olarak değil, başlangıç noktası olarak kullanmalarını öneririm.",score:100,feedbackText:"Süreç ve araç birlikte değerlendirilmeli. İyi yaklaşım."},{text:"Not tutmayı zorunlu kılarım, yapay zeka kullanımını sınıfta yasaklarım.",score:-100,feedbackText:"Yasaklama değil, farkındalık. Teknoloji dışarıda da var."},{text:"Not tutmak artık gereksiz, yapay zeka daha iyi özetliyor.",score:0,feedbackText:"Özetleme kısayol. Anlama ise aktif süreç gerektirir."}] },
  { cat:"ai-education", d:2, s:"Yapay zeka sınavlarda hile riskini artırıyor. Sınav formatınızı değiştirmeniz gerekebilir.", t:"Ölçme aracını değiştirmek köklü bir pedagojik karardır.", options:[{text:"Açık kaynak sınavlar, sözlü savunma ve süreç odaklı değerlendirmelere geçerim.",score:100,feedbackText:"Yapay zekaya dirençli değerlendirme daha derin öğrenmeyi ölçer."},{text:"Yapay zekayı tespit eden sistemler kurarım.",score:0,feedbackText:"Tespit bir çözüm ama kedi-fare oyunu kaçınılmaz. Tasarımı değiştirmek daha sağlıklı."},{text:"Sınavları kaldırır proje tabanlı değerlendirmeye geçerim.",score:0,feedbackText:"Proje tabanlı iyi ama tamamen kaldırmak bazı öğrenme çıktılarını kaçırabilir."}] },
  { cat:"ai-education", d:3, s:"Öğretmenler yapay zeka kullanım kılavuzu olmadan farklı kurallar uyguluyor. Sınıflar arasında tutarsızlık var.", t:"Kurumsal tutarsızlık öğrenci için adaletsizlik demektir.", options:[{text:"Okul çapında açık bir yapay zeka kullanım politikası geliştirmek için öğretmenlerle çalışırım.",score:100,feedbackText:"Kurumsal netlik güvenilirliği artırır. Doğru adım."},{text:"Her öğretmen kendi sınıfında özgürce karar versin.",score:-100,feedbackText:"Özgürlük değerli ama tutarsızlık öğrenci için adaletsiz bir ortam yaratır."},{text:"Sadece teknik okullar için politika gerekli, genel eğitimde şart değil.",score:0,feedbackText:"Yapay zeka tüm eğitim kademelerini etkiliyor. Politika evrensel olmalı."}] },
  { cat:"ai-education", d:1, s:"Yapay zeka ile kişiselleştirilmiş geri bildirim alabileceğinizi öğrendiniz. Öğrencilerinizin performans verisine dayalı anında geri bildirim almaları mümkün.", t:"Anında geri bildirim öğrenme döngüsünü hızlandırır — ama insan yorumu da şart.", options:[{text:"Sistemi denerim, öğrencilerin geri bildirimleri nasıl kullandığını gözlemler ve gerekli yerlerde kendi değerlendirmecilik rolümü sürdürürüm.",score:100,feedbackText:"Deneyim + gözlem + insan değerlendirmesi üçlüsü güçlü."},{text:"Geri bildirim benim işim, sistemi kullanmam.",score:-100,feedbackText:"Kıskançlık değil, işbirliği. Otomasyon zamanınızı daha değerli işlere bırakabilir."},{text:"Sistemi doğrudan devreye alır, geri bildirimleri takip etmem.",score:0,feedbackText:"Takip etmeden sistemin etkisini değerlendiremezsiniz."}] },
  { cat:"ai-education", d:2, s:"Bir yapay zeka eğitim aracı sınıftaki öğrencilerin dikkat düzeyini izliyor. Yönetim bunu uygulamak istiyor.", t:"Gözaltı teknolojisi eğitimde güven ve özerklik sorunları yaratır.", options:[{text:"Öğrencilerin ve velilerin onayı olmadan bu sistemi uygulamayı reddederim ve etik alternatifler önerim.",score:100,feedbackText:"Etik önce. Çocuk gözetimi şeffaflık ve rıza gerektirir."},{text:"Dikkat izleme öğrenmeyi iyileştirir, uygularım.",score:-100,feedbackText:"Amaç iyi olsa da araç etik sorunlar taşıyor. Onay ve şeffaflık şart."},{text:"Sadece anonim toplu veriyle kullanırsam sorun olmaz.",score:0,feedbackText:"Anonimleştirme riski azaltır ama tamamen ortadan kaldırmaz. Rıza yine gerekli."}] },

  // ai-everyday (10)
  { cat:"ai-everyday", d:1, s:"Her gün kullandığınız uygulamalar artık yapay zeka özellikleri ekliyor. Bunları kullanmak için özel çaba harcamak gerekiyor.", t:"Küçük alışkanlık değişiklikleri zamanla büyük verimlilik kazanımları sağlar.", options:[{text:"Günlük kullandığım uygulamalarda yapay zeka özelliklerini birer birer deneyip işime yarayanları alışkanlık haline getiririm.",score:100,feedbackText:"Kademeli adaptasyon sürdürülebilir. Doğru yaklaşım."},{text:"Yeni özellikler dikkat dağıtıcı, eski arayüzde kalırım.",score:-100,feedbackText:"Kaçınmak kazanımları da kaçırır. Küçük bir deneme bile karar vermenizi sağlar."},{text:"Zamanım olursa bakarım, önceliğim değil.",score:0,feedbackText:"Erteleme alışkanlığa dönüşür. Günde 10 dakika araştırmak yeterli."}] },
  { cat:"ai-everyday", d:1, s:"Yapay zeka asistanınız kişisel verilerinize erişerek daha iyi öneriler sunuyor. Mahremiyetinizden endişelisiniz.", t:"Kişiselleştirme ve mahremiyet değiş tokuşunu bilinçli yönetmek mümkün.", options:[{text:"Hangi verilere erişim izni verdiğimi gözden geçiririm ve gereksiz erişimleri kapatırım.",score:100,feedbackText:"Bilinçli veri kontrolü akıllı tüketici davranışı."},{text:"Asistanı siliyorum, bu kadar veri vermek istemiyorum.",score:0,feedbackText:"Aşırı tepki olabilir. İzin ayarlarını kısıtlamak daha dengeli."},{text:"Veri zaten her yerde var, umursamam.",score:-100,feedbackText:"Pasiflik mahremiyet kaybını artırır. Seçim yapmak mümkün."}] },
  { cat:"ai-everyday", d:2, s:"Yapay zeka ev asistanınız alışveriş listesi öneriyor ama yanlış tahminiyor. Düzeltmek yorucu geliyor.", t:"Yapay zeka alışır — sabırlı düzeltmeler sistemi iyileştirir.", options:[{text:"Düzeltmeleri tutarlı yaparsam sistem öğrenir. Bir süre sabırlı olurum.",score:100,feedbackText:"Geri bildirim döngüsü yapay zekayı iyileştirir. Doğru yaklaşım."},{text:"Asistanı devre dışı bırakırım, kendim listeleyeyim.",score:0,feedbackText:"Geçerli tercih ama sabırsızlıkla bırakmak fırsatı kaçırabilir."},{text:"Yanlış olsa da öneriyi kabul ederim, düzeltmek zaman alır.",score:-100,feedbackText:"Hatalı alışkanlıklar sistemin kalıcı hataları haline gelir."}] },
  { cat:"ai-everyday", d:1, s:"Arkadaşlarınız yapay zeka ile sohbet etmeyi eğlenceli buluyor. Siz biraz ürkütücü hissediyorsunuz.", t:"Yeni teknolojilere şüpheyle yaklaşmak sağlıklı — ama deneyim önyargıyı kırar.", options:[{text:"Küçük ve güvenli bir konuyla denemek için yapay zeka ile kısa bir sohbet başlatırım.",score:100,feedbackText:"Deneyim en iyi öğretmen. Küçük adım büyük korkuyu azaltır."},{text:"Arkadaşlarım ne yaptıysa benim için değil, kullanmam.",score:-100,feedbackText:"Kaçınmak merak etmekten zor. Tek bir deneme fikrinizi değiştirebilir."},{text:"İzin verirsem bir gün sohbetlerim toplanacak, güvenmem.",score:0,feedbackText:"Gizlilik endişesi makul ama yerel veya gizli modda denemek mümkün."}] },
  { cat:"ai-everyday", d:2, s:"Yapay zeka tavsiye ettiği bir restoranı deniyorsunuz ama beğenmiyorsunuz. Bu deneyim yapay zekaya güveninizi sarsıyor.", t:"Tek bir hata yapay zekanın tüm değerini ortadan kaldırmaz. Tercihler öznel.", options:[{text:"Geri bildirim veririm ve yapay zekanın tercihlerimi daha iyi öğrenmesi için birkaç deneme daha yaparım.",score:100,feedbackText:"Sistemler geri bildirimle iyileşir. Sabır kazanım sağlar."},{text:"Yapay zeka tavsiyelerine bir daha güvenmem.",score:-100,feedbackText:"Aşırı tepki. İnsanlar da zaman zaman yanlış öneri yapar."},{text:"Bundan sonra sadece benim bildiğim yerlere giderim.",score:0,feedbackText:"Keşfetmemek kayıp da olabilir. Deneme yanılma normaldir."}] },
  { cat:"ai-everyday", d:2, s:"Yapay zeka navigasyon uygulamanız trafik tahmini yapıyor ve sizi alışılmadık bir yoldan götürüyor. Güvenmekte zorlanıyorsunuz.", t:"Yapay zeka büyük veri kalıplarını görür, siz günlük deneyimi görürsünüz. İkisi birbirini tamamlar.", options:[{text:"En az bir kez deneyim, önerilen rotanın mantığını anlamaya çalışırım.",score:100,feedbackText:"Merak + deney en iyi öğrenme yolu."},{text:"Her zaman bildiğim yolu tercih ederim, güven sorunum var.",score:0,feedbackText:"Güven zaman alır ama bildiğiniz yol her zaman en iyi değildir."},{text:"Uygulama saçmalıyor, hemen kapıya dönüş yaparım.",score:-100,feedbackText:"Veri tabanlı öneriyi bir kez de olsa test etmek değer."}] },
  { cat:"ai-everyday", d:1, s:"Yapay zeka e-posta filtreleme yapıyor ve bazı önemli mesajları spam olarak işaretliyor. Ne yaparsınız?", t:"Otomasyon hataları düzeltilebilir — önemli olan öğrenme döngüsü.", options:[{text:"Spam klasörümü düzenli kontrol eder, yanlış sınıflandırmaları işaretleyip sistemi eğitirim.",score:100,feedbackText:"Aktif yönetim sistemi iyileştirir. Doğru alışkanlık."},{text:"Yapay zeka filtrelemesini tamamen kapatırım, kendim ayıklarım.",score:0,feedbackText:"Geçerli ama zaman maliyeti yüksek. Sistemi geliştirmek daha verimli."},{text:"Önemli kişilerden gelen mesajları kaçırırsam sonra bakarım.",score:-100,feedbackText:"Reaktif yaklaşım önemli fırsatları kaçırmanıza yol açabilir."}] },
  { cat:"ai-everyday", d:3, s:"Yapay zeka sağlık uygulamanız uyku düzeninizi analiz ediyor ve bazı endişe verici kalıplar tespit ediyor.", t:"Yapay zeka veri gösterir, teşhis koymaz. Uzman değerlendirmesi şart.", options:[{text:"Bulgularımı bir doktora götürür, daha kapsamlı değerlendirme isterim.",score:100,feedbackText:"Doğru. Uygulama rehberlik eder, teşhis koyamaz."},{text:"Uygulamanın önerilerine göre yaşam tarzımı hemen değiştiririm.",score:0,feedbackText:"Uygulama önerileri genel. Kişisel durum için uzman değerlendirmesi önemli."},{text:"Telefon sağlık uygulamaları güvenilmez, silerim.",score:-100,feedbackText:"Silmek yerine doğru kullanmayı öğrenmek daha değerli."}] },
  { cat:"ai-everyday", d:2, s:"Çocuğunuz yapay zeka ile oyun oynuyor ve öğreniyor. Ekran süresi konusunda endişeleniyorsunuz.", t:"İçerik kalitesi ve kullanım amacı ekran süresinden daha önemli.", options:[{text:"İçeriği birlikte incelir, öğrenme amaçlı kullanımı destekler ve günlük süre sınırı belirlerim.",score:100,feedbackText:"Aktif ebeveynlik + içerik kalitesi + sınır = dengeli yaklaşım."},{text:"Ekran süresini sıfıra indiririm, çocuk teknolojiden uzak kalsın.",score:-100,feedbackText:"Tamamen kısıtlamak dijital okuryazarlığı geliştirme fırsatını da kısıtlar."},{text:"Çocuk eğleniyorsa sorun görmem, bırakırım.",score:0,feedbackText:"Eğlence tek kriter değil. İçerik kalitesi ve denge de önemli."}] },
  { cat:"ai-everyday", d:1, s:"Yapay zeka beslenme uygulamanız size özelleştirilmiş bir diyet planı sunuyor. Diyetisyeninize danışmak yerine bunu takip etmeyi düşünüyorsunuz.", t:"Yapay zeka genel kalıpları öğrenir, diyetisyen bireysel sağlık geçmişini bilir.", options:[{text:"Planı diyetisyenimle paylaşır, birlikte değerlendiririz.",score:100,feedbackText:"İki bakış açısını birleştirmek en güvenli yol."},{text:"Uygulamanın planını takip ederim, bilimsel temelli görünüyor.",score:0,feedbackText:"Genel plan kişisel sağlık durumunuzu dikkate almayabilir."},{text:"Diyetisyen pahalı, uygulamayı tercih ederim.",score:-100,feedbackText:"Maliyet anlaşılır ama beslenme sağlıkla doğrudan bağlantılı. Uzman desteği değerli."}] },

  // ai-finance (10)
  { cat:"ai-finance", d:2, s:"Yapay zeka destekli bir yatırım uygulaması size portföy önerisi sunuyor. Öneriyi olduğu gibi kabul edecek misiniz?", t:"Yapay zeka kalıpları bulur, piyasa riskini garantileyemez. Karar sizin.", options:[{text:"Öneriyi anlayıp gerekçesini araştırır, mali danışmanımla konuşur ve sonra karar veririm.",score:100,feedbackText:"Bilinçli karar vericiler hem aracı hem uzmanı kullanır."},{text:"Yapay zeka büyük veri kullanıyor, tahmin etmem kendimden iyidir.",score:-100,feedbackText:"Geçmiş performans geleceği garantilemez — yapay zeka için de geçerli."},{text:"Önerilerin bir kısmını alır, kalanı kendi bilgimle seçerim.",score:0,feedbackText:"Parçalı yaklaşım makul ama gerekçeyi anlamadan seçmek risk taşır."}] },
  { cat:"ai-finance", d:1, s:"Yapay zeka harcamalarınızı analiz ediyor ve tasarruf önerileri sunuyor. İlk bakışta bazı öneriler mantıklı görünüyor.", t:"Veri odaklı tasarruf önerileri faydalı ama kişisel değerlere uymak da önemli.", options:[{text:"Önerileri inceledikten sonra değerlerimle çelişmeyenleri uygularım.",score:100,feedbackText:"Akıllı filtreleme. Araç öneri sunar, karar sizin."},{text:"Hepsini uygularım, yapay zeka daha iyi biliyor.",score:-100,feedbackText:"Kör itaat finansal özerkliği zedeler. Değerlendirme şart."},{text:"Harcama analizini görmek bile mahremiyetimi ihlal eder.",score:0,feedbackText:"Mahremiyet meşru endişe ama araç kendi verilerinize bakar. Kontrol edin."}] },
  { cat:"ai-finance", d:2, s:"Vergi beyannamenizi yapay zeka yardımıyla doldurmayı düşünüyorsunuz. Mali danışman olmaksızın.", t:"Basit beyannameler için yapay zeka yardımcı olabilir ama karmaşık durumlar uzman gerektirir.", options:[{text:"Basit gelir kalemlerim var, yapay zekayı kullanırım ama sonunda bir kez kontrol ettiririm.",score:100,feedbackText:"Araç + doğrulama = güvenli yaklaşım."},{text:"Vergi konusunda yapay zekaya güvenmem, her şeyi muhasebecime bırakırım.",score:0,feedbackText:"Tercih edilebilir ama basit durumlar için yapay zeka zaman ve maliyet kazandırabilir."},{text:"Yapay zeka doldurur, ben imzalarım, sorun olmaz.",score:-100,feedbackText:"Vergi beyannamesi hatalı olursa sorumluluk sizde. Kontrol şart."}] },
  { cat:"ai-finance", d:3, s:"Yapay zeka fintech uygulaması kredi puanınızı analiz ederek kredi için uygunluğunuzu değerlendiriyor. Sonuç olumsuz ama gerekçe belirsiz.", t:"Yapay zeka kredi kararlarında şeffaf olmalı. Gerekçeyi sormak hakkınız.", options:[{text:"Kararın gerekçesini yazılı olarak talep eder ve farklı kurumlarla karşılaştırırım.",score:100,feedbackText:"Şeffaflık talep etmek hakkınız. Tek kaynağa güvenmemek akıllıca."},{text:"Sistemi güveniyorum, olumsuz karar doğru olmalı.",score:-100,feedbackText:"Yapay zeka sistemleri hata yapabilir veya bias içerebilir. Sorgulamak meşru."},{text:"Kredi almaktan vazgeçerim, reddedildim.",score:0,feedbackText:"Tek ret nihai karar değil. Alternatif kurumları denemek mantıklı."}] },
  { cat:"ai-finance", d:1, s:"Yapay zeka bütçe planlama uygulamanız gelecek ay için harcama tahminleri yapıyor. Tahminler gerçekçi görünüyor.", t:"Tahmin bir araç — gerçek harcamalar her zaman farklı olabilir. Esneklik gerekli.", options:[{text:"Tahmini başlangıç noktası olarak kullanır, gerçek harcamalarımı haftalık takip ederim.",score:100,feedbackText:"Tahmin + izleme + esneklik güçlü bütçe yönetimi."},{text:"Tahmine güvenir, aylık harcamalarımı izlemem.",score:-100,feedbackText:"Tahmin gerçeği garanti etmez. İzleme olmadan sapmalar fark edilmez."},{text:"Bütçe yapmak çok zor, tahmini de kullanmam.",score:0,feedbackText:"Yapay zeka başlangıç kolaylaştırır. Küçük adımla başlamak değer."}] },
  { cat:"ai-finance", d:2, s:"Dolandırıcılık tespiti için yapay zeka bankacılık işlemlerinizi anlık olarak izliyor. Bazen meşru işlemler de bloke ediliyor.", t:"Güvenlik ve rahatlık dengelenmeli. Yanlış pozitifler müşteri deneyimini etkiler.", options:[{text:"Yanlış bloke edilen işlemler için bankayla iletişime geçer, sistemi iyileştirmeleri için geri bildirim veririm.",score:100,feedbackText:"Aktif geri bildirim sistemi geliştirir. Doğru tutum."},{text:"Yapay zeka bloke ediyorsa muhtemelen şüpheli, kabul ederim.",score:-100,feedbackText:"Yanlış pozitifler gerçek. Meşru işlemleri sorgulamak hakkınız."},{text:"Güvenlik can sıkıcı ama ne yapabilirim ki.",score:0,feedbackText:"Geri bildirim verebilirsiniz. Pasif kabul sizi ve diğer müşterileri etkiler."}] },
  { cat:"ai-finance", d:3, s:"Sigorta şirketiniz yapay zeka ile kişiselleştirilmiş prim hesaplıyor ve sizin risk profiliniz beklenenden yüksek çıkıyor.", t:"Yapay zeka risk modeli itiraz edilebilir. Verinin doğruluğunu sorgulamak hakkınız.", options:[{text:"Hangi verilerle hesaplandığını sorar, yanlış veya eksik bilgi varsa itiraz ederim.",score:100,feedbackText:"Veriye dayalı itiraz hakkınız. Şeffaflık talep etmek meşru."},{text:"Prim yüksek olsa da yapay zeka hesapladıysa doğru olmalı.",score:-100,feedbackText:"Yapay zeka hatalı veya eksik veriye dayalı karar verebilir. İtiraz şart."},{text:"Başka sigorta şirketine geçerim.",score:0,feedbackText:"Alternatif aramak makul ama önce mevcut hesabı sorgulamak fırsatı kaçırmayın."}] },
  { cat:"ai-finance", d:1, s:"Yapay zeka ekonomik haberleri analiz ederek yatırım fırsatları sunuyor. Haberler genellikle negatif.", t:"Piyasa haberleri ile yatırım fırsatları arasındaki ilişki karmaşıktır.", options:[{text:"Yapay zekanın analizini okur, kendi araştırmamla doğrular ve uzun vadeli stratejimi koruyarak karar veririm.",score:100,feedbackText:"Çok kaynaklı analiz + uzun vadeli bakış = sağlıklı yatırım."},{text:"Haberler kötü, şimdi yatırım yapmamalıyım.",score:0,feedbackText:"Negatif haberler her zaman kötü fırsat anlamına gelmez. Analiz şart."},{text:"Yapay zekanın önerdiği fırsata hemen para koyarım.",score:-100,feedbackText:"Tek kaynak yatırım kararı için yetersiz. Araştırma ve risk değerlendirmesi şart."}] },
  { cat:"ai-finance", d:2, s:"Muhasebe yazılımınıza yapay zeka eklendi ve otomatik kategorizasyon yapıyor. Bazı işlemler yanlış kategorize edilmiş.", t:"Otomasyon verimliliği artırır ama insan denetimi doğruluğu sağlar.", options:[{text:"Aylık kapanışlarda kategorileri kontrol eder, yanlışları düzeltir ve sistemi eğitirim.",score:100,feedbackText:"Düzenli denetim + eğitim = güvenilir otomasyon."},{text:"Yazılım otomatik yapıyor, ben de güvenirim.",score:-100,feedbackText:"Yanlış kategorizasyon vergi ve finansal raporlamayı etkiler. Kontrol şart."},{text:"Yazılımı kaldırırım, elle yaparsam daha az hata olur.",score:0,feedbackText:"Elle yapmak hataya açık ve zaman alıcı. Sistemi geliştirmek daha iyi."}] },
  { cat:"ai-finance", d:3, s:"Yapay zeka destekli bir borsa robotu sürekli küçük işlemler yapıyor. Siz büyük resmi görmekte zorlanıyorsunuz.", t:"Otomasyon hızı verimlidir ama anlaşılabilirlik kontrolü sürdürmeniz için şart.", options:[{text:"Robotun stratejisini anlamak için belgeleri okur, anlamadığım yerleri danışmana sorum.",score:100,feedbackText:"Anlayarak yönetmek en güvenli yaklaşım."},{text:"Robot iyi sonuçlar üretiyorsa anlamak zorunda değilim.",score:-100,feedbackText:"Anlamadan devam etmek piyasa dönüşlerinde sizi hazırlıksız bırakır."},{text:"Robotu durdurur, kendi işlem stratejime dönerim.",score:0,feedbackText:"Duraklamak anlaşılır ama stratejiyi öğrendikten sonra devam etmek değer."}] },

  // ai-health (10)
  { cat:"ai-health", d:1, s:"Yapay zeka sağlık uygulamanız belirtilerinize bakarak olası bir hastalık önerdi. Ne yaparsınız?", t:"Yapay zeka tarama yapar, teşhis koyamaz. Doktora gitmek değişmez adım.", options:[{text:"Öneriyi doktora götürür, uzman değerlendirmesi isterim.",score:100,feedbackText:"Yapay zeka rehberlik eder, doktor teşhis koyar. Doğru sıralama."},{text:"Uygulamanın önerdiği ilacı araştırıp alırım.",score:-100,feedbackText:"Teşhissiz ilaç risk taşır. Uzman değerlendirmesi şart."},{text:"Belirti geçer diye beklerim, uygulama abartıyor olabilir.",score:0,feedbackText:"Bazen beklemek mantıklı ama ciddi belirti işaretlerini görmezden gelmek tehlikeli."}] },
  { cat:"ai-health", d:2, s:"Yapay zeka tıbbi görüntüleme raporunuzu analiz etti ve potansiyel bir anomali işaretledi. Radyoloji uzmanının raporu henüz gelmedi.", t:"Yapay zeka tarama yapar, uzman değerlendirir. İkisi birlikte güvenilirdir.", options:[{text:"Radyoloji uzmanının raporunu bekler, her iki sonucu birlikte değerlendiririm.",score:100,feedbackText:"Doğru sıralama. Yapay zeka önce tarar, uzman sonra doğrular."},{text:"Yapay zeka anomali gördüyse hemen ameliyata hazırlanırım.",score:-100,feedbackText:"Panik erken. Uzman değerlendirmesi olmadan karar vermek yanlış."},{text:"Yapay zeka yanılıyor olabilir, radyoloji raporunu bekleyip yapay zekayı dikkate almam.",score:0,feedbackText:"Uzman değerlendirmesi öncelikli ama yapay zekanın işaretini de aktarmak değerli."}] },
  { cat:"ai-health", d:1, s:"Akıllı bilekliğiniz kalp atış hızınızda düzensizlik tespit etti. Endişeli hissediyorsunuz.", t:"Giyilebilir cihazlar erken uyarı verir. Doğrulama için tıbbi değerlendirme şart.", options:[{text:"Kardiyologa randevu alır, bilekliğin verilerini doktora gösteririm.",score:100,feedbackText:"Veri + uzman = doğru değerlendirme."},{text:"Düzensizlik hafif görünüyor, görmezden gelirim.",score:-100,feedbackText:"Kalp ritim sorunları erken tespitte daha kolay yönetilir. Endişeyi önemsemek şart."},{text:"İnternetten araştırırım ve ne yapacağıma karar veririm.",score:0,feedbackText:"Araştırma başlangıç için iyi ama teşhis için uzman gerekli."}] },
  { cat:"ai-health", d:2, s:"Yapay zeka akıl sağlığı uygulamanız düzenli olarak ruh halinizi takip ediyor ve anksiyete belirtileri artıyor.", t:"Yapay zeka destek sağlar ama ruh sağlığı profesyonel desteğin yerini tutmaz.", options:[{text:"Verileri terapistimle paylaşır, profesyonel destek alırım.",score:100,feedbackText:"Veri + profesyonel = en güçlü destek kombinasyonu."},{text:"Uygulama egzersiz ve meditasyon öneriyor, bunları yaparsam yeter.",score:0,feedbackText:"Bu aktiviteler faydalı ama anksiyete artışında profesyonel değerlendirme önemli."},{text:"Uygulamayı silerim, sürekli izlenmek beni daha endişeli yapıyor.",score:0,feedbackText:"Makul tepki olabilir. Ancak veriyi doktora götürmeden önce silmek fırsatı kaçırabilir."}] },
  { cat:"ai-health", d:3, s:"Hastaneniz yapay zeka tabanlı teşhis sistemini kullanmaya başladı. Doktorunuz yapay zekanın önerisine güvenerek tedaviyi değiştirdi. Sizi endişelendiriyor.", t:"Yapay zeka karar destek aracıdır, son karar klinisyende olmalıdır.", options:[{text:"Doktorumdan yapay zekanın önerisinin gerekçesini ve kendi klinik değerlendirmesini açıklamasını isterim.",score:100,feedbackText:"Hasta olarak bilgi talep etmek hakkınız. Şeffaflık şart."},{text:"Yapay zeka büyük veri kullanıyor, daha iyi teşhis koyuyor olabilir.",score:0,feedbackText:"Veri gücü var ama hasta bireyselliği ve klinik bağlam da kritik."},{text:"Doktorumu değiştiririm, yapay zekaya güvenen birine güvenmiyorum.",score:0,feedbackText:"Önce gerekçeyi anlamak daha sağlıklı. Sonra değerlendirme yapabilirsiniz."}] },
  { cat:"ai-health", d:1, s:"Yapay zeka beslenme uygulamanız sizin için özelleştirilmiş kalori hedefleri hesaplıyor. Çok düşük geliyor.", t:"Yapay zeka genel algoritmalar kullanır, bireysel metabolizma farklıdır.", options:[{text:"Hedefi bir diyetisyenle gözden geçiririm, kendi vücudumu daha iyi bilirim.",score:100,feedbackText:"Algoritmalar genel. Uzman kişiselleştirir."},{text:"Uygulama hesapladıysa doğrudur, o kadar yiyeyim.",score:-100,feedbackText:"Çok düşük kalori metabolizmanıza zarar verebilir. Uzman değerlendirmesi şart."},{text:"Hesabı değiştiririm, istediğim rakamı girerim.",score:0,feedbackText:"Takip gerçekçi veriye dayalı olmalı. Gerçek hedef için destek alın."}] },
  { cat:"ai-health", d:2, s:"Yapay zeka ilaç etkileşim kontrolü yapıyor ve iki ilacınızın birlikte kullanılmasını önermiyor. Ama doktorunuz bunu zaten reçete etti.", t:"Yapay zeka genel bilgiye dayanır, doktor bireysel durumunuzu bilir. Çelişkiyi sorun.", options:[{text:"Doktoruma yapay zekanın uyarısını gösterir ve birlikte değerlendirip güvende olup olmadığımı sorarım.",score:100,feedbackText:"Çelişkiyi açıkça sorgulamak en güvenli yaklaşım."},{text:"Yapay zeka uyardıysa ilacı kullanmam.",score:-100,feedbackText:"Doktoru devre dışı bırakmak tehlikeli olabilir. Birlikte değerlendirme şart."},{text:"Doktor zaten verdi, yapay zekayı dikkate almam.",score:0,feedbackText:"Uyarıyı aktarmak doktora da değerli olabilir. Görmezden gelmek fırsatı kaçırır."}] },
  { cat:"ai-health", d:3, s:"Sağlık sigortanız yapay zeka analizine dayanarak belirli bir tedaviyi kapsam dışında bıraktı.", t:"Yapay zeka sigorta kararlarında itiraz edilebilir. Şeffaflık ve itiraz hakkı yasal.", options:[{text:"Kararın gerekçesini yazılı olarak isterim ve gerekirse itiraz ederim.",score:100,feedbackText:"İtiraz hakkınız var. Aktif kullanmak önemli."},{text:"Sigorta reddetmişse tedavi gereksizdir.",score:-100,feedbackText:"Sigorta kararı tıbbi gereklilik kararı değildir. İkisi farklı."},{text:"Tedaviden vazgeçerim, paralı tedaviye gidemem.",score:0,feedbackText:"Önce itiraz deneyin. Ek seçenekler de olabilir."}] },
  { cat:"ai-health", d:1, s:"Yapay zeka uyku takip uygulamanız sürekli uyku kalitenizin kötü olduğunu söylüyor. Bu sizi her sabah stres yapıyor.", t:"Araç kaygı yaratıyorsa kullanım biçimini gözden geçirmek gerekir.", options:[{text:"Veriyi doktora götürür ama uygulamayı sabahları kontrol etmeyi bırakırım.",score:100,feedbackText:"Veri faydalı ama kaygı verici kullanım alışkanlığı değiştirilebilir."},{text:"Uygulama doğru diyorsa uyku sorunum var, daha çok endişelenirim.",score:-100,feedbackText:"Araç odaklı kaygı uyku kalitesini daha da düşürür. Doktor değerlendirmesi daha sağlıklı."},{text:"Uygulamayı silerim, bilmemek daha iyi.",score:0,feedbackText:"Veriyi gözardı etmek sorunu çözmez ama araçla ilişkiyi yönetmek önemli."}] },
  { cat:"ai-health", d:2, s:"Yapay zeka genetik test sonuçlarınızı analiz ederek belirli hastalıklara yatkınlığınız olduğunu söylüyor.", t:"Genetik yatkınlık kader değildir. Yaşam tarzı kararları belirleyicidir.", options:[{text:"Sonuçları genetik danışmanla yorumlar, önleyici sağlık adımlarını öğrenirim.",score:100,feedbackText:"Bilgi kaygıya değil, eyleme dönüştürülmeli. Doğru yaklaşım."},{text:"Yatkınlık varsa nasılsa hastalanacağım, bir şey yapmam.",score:-100,feedbackText:"Yatkınlık kader değil. Önleyici yaşam tarzı büyük fark yaratabilir."},{text:"Genetik test sonuçlarını görmek istemezdim, bilmemek daha iyi.",score:0,feedbackText:"Bu tercih makul ama bilgi bilinçli önlem alma fırsatı sunar."}] },
]

console.log('Total:', ALL.length, 'questions')
for (let i = 0; i < ALL.length; i += 20) {
  const batch = ALL.slice(i, i + 20)
  await insert(batch)
}
