const TOKEN = 'sbp_f314cf27b5b2a01eea48048a7b1c015cc9cf4b42'
const API = 'https://api.supabase.com/v1/projects/amhfxaqolholacanqyas/database/query'

function esc(s) { return s.replace(/'/g, "''") }

async function insert(batch) {
  const values = batch.map(q => {
    const opts = JSON.stringify(q.options).replace(/'/g, "''")
    return `('tr','${q.cat}','${esc(q.s)}','${esc(q.t)}','${opts}'::jsonb,${q.d},'claude',true)`
  }).join(',')
  const sql = `INSERT INTO questions (locale,category,scenario_text,mindset_tip,options,difficulty,generated_by,is_active) VALUES ${values};`
  const r = await fetch(API, {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${TOKEN}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query: sql })
  })
  const d = await r.json()
  if (d.message) { console.error('ERR:', d.message); return false }
  console.log('OK:', batch.length, 'inserted')
  return true
}

const ALL = [
  // ai-law-regulation (10)
  { cat:"ai-law-regulation", d:2, s:"Şirketiniz yapay zeka kullanıyor ama GDPR uyumluluğunu hiç değerlendirmedi. Bir müşteri veri talebi aldınız.", t:"Yapay zeka kullanan her şirket veri işleme sorumluluğu taşır.", options:[{text:"Hukuk danışmanımla birlikte mevcut yapay zeka kullanımımızı GDPR kapsamında değerlendiririm.",score:100,feedbackText:"Proaktif uyum reaktif krizden çok daha az maliyetlidir."},{text:"Müşterinin talebini görmezden gelirim, küçük bir şirketiz.",score:-100,feedbackText:"GDPR büyüklük ayrımı yapmaz. Görmezden gelmek ağır para cezasına yol açabilir."},{text:"Standart bir veri yanıtı şablonu bulur gönderirim.",score:0,feedbackText:"Şablon başlangıç ama bireysel duruma göre yanıt şart."}] },
  { cat:"ai-law-regulation", d:3, s:"Yapay zeka tarafından verilen bir kredi reddi kararına itiraz etmek istiyorsunuz ama sistemin nasıl karar verdiği belirsiz.", t:"Otomatik karar alma sistemlerinde şeffaflık ve itiraz hakkı yasal güvence altında.", options:[{text:"Yazılı gerekçe talep eder, gerekirse tüketici hakları kuruluşuna başvururum.",score:100,feedbackText:"İtiraz hakkınızı kullanmak meşru. Şeffaflık talep edin."},{text:"Sistem böyle karar verdiyse doğru olmalı.",score:-100,feedbackText:"Yapay zeka sistemleri hata yapabilir veya önyargılı olabilir. Sorgulamak hakkınız."},{text:"Başka bir kuruma başvururum, bu kurumla uğraşmam.",score:0,feedbackText:"Alternatif aramak mantıklı ama itiraz hakkını kullanmayı da düşünün."}] },
  { cat:"ai-law-regulation", d:2, s:"Yapay zeka oluşturduğunuz bir içerik için telif hakkı talebi aldınız. İçerik yapay zeka tarafından üretildi.", t:"Yapay zeka üretiminin telif hakkı statüsü hâlâ tartışmalı ve ülkeden ülkeye değişiyor.", options:[{text:"Hukuki danışman alırım ve yapay zeka üretimi içerik için politikamı netleştiririm.",score:100,feedbackText:"Belirsiz alanda hukuki danışmanlık şart."},{text:"Yapay zeka üretimi korumalı değil, talep geçersizdir.",score:0,feedbackText:"Genel doğru ama durum karmaşık. Hukuki değerlendirme gerekebilir."},{text:"Tazminat öderim, dava açılmasın.",score:-100,feedbackText:"Ödemeden önce hukuki durumunuzu öğrenin. Gereksiz ödeme yapabilirsiniz."}] },
  { cat:"ai-law-regulation", d:1, s:"Yapay zeka işe alım aracınız bazı demografik gruplara karşı önyargılı davranıyor olabilir. Bunu fark ettiniz.", t:"Önyargılı işe alım yapay zekası yasal sorumluluk yaratabilir.", options:[{text:"Sistemi askıya alır, önyargı analizini denetim firmasına yaptırır ve düzeltmeden sonra devreye sokarım.",score:100,feedbackText:"Proaktif önlem hem etik hem yasal koruma sağlar."},{text:"İşe alım kararları benden geçiyor, sistem sadece filtreler.",score:0,feedbackText:"Filtreleme de ayrımcılık kapsamında değerlendirilebilir. Sistemi gözden geçirin."},{text:"Sorun olmaz, herkese aynı kriterleri uyguluyoruz.",score:-100,feedbackText:"Eşit kriter görünümlü sistem de önyargılı çıktı üretebilir. Analiz şart."}] },
  { cat:"ai-law-regulation", d:3, s:"Yapay zeka bir sözleşme taslağı hazırladı. Avukat kontrolü olmadan imzalamayı düşünüyorsunuz.", t:"Yapay zeka hukuki taslak üretebilir ama yasal sorumluluk insandadır.", options:[{text:"Avukata kontrol ettiririm — özellikle yükümlülük ve fesih maddelerini.",score:100,feedbackText:"Hukuki belgede uzman gözetimi zorunlu."},{text:"Yapay zeka iyi bir taslak çıkardı, imzalayabilirim.",score:-100,feedbackText:"Hatalı sözleşme ciddi yasal ve mali sonuçlar doğurur. Avukat şart."},{text:"Küçük bir sözleşme, avukatsız da olur.",score:0,feedbackText:"Küçük görünen sözleşmeler büyük sorunlar yaratabilir. Risk almayın."}] },
  { cat:"ai-law-regulation", d:2, s:"Yapay zeka ürününüz AB Yapay Zeka Yasası kapsamına girebilir. Ama yasayı henüz okumadınız.", t:"Düzenleyici uyum proaktif bir sorumluluktur, reaktif bir kriz değil.", options:[{text:"Hukuk ekibimle yasayı değerlendiririm ve ürünümüzün hangi risk kategorisine girdiğini belirleriz.",score:100,feedbackText:"Proaktif uyum hem daha ucuz hem daha güvenli."},{text:"Yasa henüz tam uygulanmıyor, sonra bakarım.",score:-100,feedbackText:"Hazırlıksız yakalanmak maliyetlidir. Şimdiden öğrenmek avantaj sağlar."},{text:"Küçük şirketlere uygulanmıyor olabilir, kontrol etmem.",score:0,feedbackText:"Yanlış varsayım. Kontrol etmek on dakika alır."}] },
  { cat:"ai-law-regulation", d:1, s:"Rakibinizin yapay zeka sistemi etik dışı davranış gösteriyor ama düzenleyici kuruma şikayette bulunup bulunmayacağınızı bilmiyorsunuz.", t:"Etik ihlallerin raporlanması sektörü düzeltir ve uzun vadede herkesin yararınadır.", options:[{text:"Somut kanıtları düzenleyici kuruma bildiririm.",score:100,feedbackText:"Etik ihlal raporlamak sektör standartlarını korur."},{text:"Kendi işime bakarım, rakibim beni ilgilendirmez.",score:-100,feedbackText:"Sektördeki etik sorunlar tüm oyuncuları etkiler. Pasif kalmak da bir tercih."},{text:"Önce sektör kuruluşuna danışırım, doğrudan şikayette bulunmam.",score:0,feedbackText:"Sektör kanalları başlangıç olabilir ama resmi şikayet daha güçlü etki yaratır."}] },
  { cat:"ai-law-regulation", d:3, s:"Yapay zeka sisteminiz bir hata yaptı ve müşteri zarara uğradı. Sorumluluk kime ait?", t:"Yapay zeka hataları için sorumluluk paylaşımlıdır. Politika ve şeffaflık şart.", options:[{text:"Müşteriye açık bir özür ve tazminat sunar, iç soruşturma başlatır ve sorumluluğu şeffaf netleştiririm.",score:100,feedbackText:"Şeffaf sorumluluk güveni korur ve yasal riski azaltır."},{text:"Sistem otomatik karar verdi, benim hatam değil.",score:-100,feedbackText:"Sistemi konuşlandıran olarak sorumluluk sizde. Reddetmek durumu daha kötü yapar."},{text:"Hukuk ekibi halleder.",score:0,feedbackText:"Hukuk şart ama müşteri iletişimini ihmal etmek itibar zedeleyebilir."}] },
  { cat:"ai-law-regulation", d:2, s:"Yapay zekanın oluşturduğu bir haber makalesi yanlış bilgi içeriyordu ve yayınlandı. Sorumlu kim?", t:"İçerik yayımlamak yayıncıya sorumluluk yükler, üretim aracına değil.", options:[{text:"Yayınlanan içerikten editoryal sorumluluk bizde. Düzeltme yayınlar ve denetim sürecini güçlendiririm.",score:100,feedbackText:"Doğru tutum. Yayıncı sorumludur."},{text:"Yapay zeka oluşturdu, biz sadece yayınladık.",score:-100,feedbackText:"Bu savunma basın hukukunda geçerli değil. Yayıncı sorumlu."},{text:"Yanlış bilgiyi düzeltiriz ama kamuya açıklamayız.",score:0,feedbackText:"Kamuoyu hakikate erişim hakkına sahip. Şeffaf düzeltme daha doğru."}] },
  { cat:"ai-law-regulation", d:1, s:"Yapay zeka veri analiz aracınız kişisel sağlık verilerini işliyor. HIPAA veya GDPR gereksinimlerini bilmiyorsunuz.", t:"Hassas veri işleyen araçlar özel düzenlemelere tabidir. Bilgisizlik mazerete dönüşmez.", options:[{text:"Hukuki danışmandan hangi mevzuatın uygulandığını ve uyum gereksinimlerini öğrenirim.",score:100,feedbackText:"Önce öğrenmek sonra hareket etmek doğru sıra."},{text:"Küçük şirketiz, bize uygulanmıyor olabilir.",score:-100,feedbackText:"Sağlık verisi işleyen her kuruluş kapsama girer. Boyut fark etmez."},{text:"Kullanıcı onayı alırsam yeter.",score:0,feedbackText:"Onay tek gereklilik değil. Depolama, güvenlik ve bildirim kuralları da var."}] },

  // ai-leadership (10)
  { cat:"ai-leadership", d:2, s:"Ekibiniz yapay zeka dönüşümüne direniyor. Siz bu dönüşümün kaçınılmaz olduğuna inanıyorsunuz.", t:"Direniş genellikle korku ya da belirsizlikten kaynaklanır. Lider olarak bunu adreslemek sizin sorumluluğunuz.", options:[{text:"Ekibin kaygılarını bireysel görüşmelerle anlayıp somut fayda ve destek sunarım.",score:100,feedbackText:"Empati + somut destek en güçlü liderlik aracı."},{text:"Dönüşüm zorunlu, direnenler adapte olur ya da ayrılır.",score:-100,feedbackText:"Zorlama değil ikna. Değerli çalışanlar böyle kaybedilir."},{text:"Dönüşümü yavaşlatırım, ekibin hazır olmasını beklerim.",score:0,feedbackText:"Hazırlık önemli ama aşırı yavaşlamak rekabette geride bırakır."}] },
  { cat:"ai-leadership", d:1, s:"Yapay zeka ile alınan bir karar yanlış çıktı. Ekip sizin kararınız gibi algılıyor.", t:"Lider şeffaf olduğunda güven artar. Aracı gizlemek güveni zedeler.", options:[{text:"Yapay zekanın önerisini dikkate aldığımı ama kararın sorumluluğunun bende olduğunu açıklarım.",score:100,feedbackText:"Şeffaflık + sorumluluk = güvenilir liderlik."},{text:"Yapay zekanın önerdiğini söylersem otoritemi kaybederim.",score:-100,feedbackText:"Şeffaflık otorite kaybı değil, güven artışı sağlar."},{text:"Hatayı kabul eder, nereden kaynaklandığını anlatmam.",score:0,feedbackText:"Kabullenme iyi ama öğrenim için kaynak analizini paylaşmak değerli."}] },
  { cat:"ai-leadership", d:3, s:"Yapay zeka stratejik analizler sunuyor ama ekibiniz veriye değil içgüdüye güveniyor. İkisi çelişince ne yaparsınız?", t:"İyi liderler veriyi ve deneyimi birlikte değerlendirir. Biri diğerini iptal etmez.", options:[{text:"Her iki bakışı masaya yatırır, verinin neyi gösterdiğini ve deneyimin ne söylediğini birlikte tartışırım.",score:100,feedbackText:"Entegratif liderlik — en güçlü karar en zengin bilgiye dayanır."},{text:"Veri her zaman kazanır, ekibin içgüdüsü geçersiz.",score:-100,feedbackText:"Veri bağlamı yakalayamayabilir. Deneyim önemli bir girdi."},{text:"Ekip içgüdüsüne güvenirim, veri her zaman sağlıklı değil.",score:0,feedbackText:"İçgüdü değerli ama veriyi görmezden gelmek kaçırılan fırsatlar demektir."}] },
  { cat:"ai-leadership", d:2, s:"Bir ekip üyeniz yapay zekayı kullanmak için değil, kullanıyor gibi görünmek için kullanıyor. Çıktılar yüzeysel.", t:"Araç kullanımı performans değil, gerçek değer üretimi için olmalıdır.", options:[{text:"Çalışanla birebir konuşur, yapay zekayla nasıl çalıştığını ve çıktı kalitesini birlikte değerlendiririm.",score:100,feedbackText:"Dürüst konuşma ve yönlendirme en etkili düzeltme yolu."},{text:"Yapay zeka kullanımını göstermelik olarak görürsem onu işten çıkarırım.",score:-100,feedbackText:"Önce anlayın. Belki araç eğitimi eksik ya da süreç sorunu var."},{text:"Herkes farklı kullanır, çıktı kabul edilebilirse sorun yok.",score:0,feedbackText:"Yüzeysel çıktı uzun vadede kalite sorunu yaratır. Konuşmak gerekli."}] },
  { cat:"ai-leadership", d:1, s:"Yapay zeka toplantı özetleri ve aksiyon listeleri oluşturuyor. Ekip toplantılara daha az hazırlanıyor.", t:"Araç kolaylığı bazen daha derin işlemenin önüne geçer.", options:[{text:"Toplantı öncesi hazırlığı yapay zekadan bağımsız tutarım; özet aracını toplantı sonrası takip için kullanırım.",score:100,feedbackText:"Araç alanını doğru tanımlamak verimliliği artırır."},{text:"Özetler hazırlığı gereksiz kılıyor, modern çalışma biçimi bu.",score:-100,feedbackText:"Hazırlıksız toplantı kararların kalitesini düşürür."},{text:"Yapay zeka özetleri olduğu sürece hazırlık isteğe bağlı.",score:0,feedbackText:"Toplantı türüne göre değişir ama genel bir politika olarak riskli."}] },
  { cat:"ai-leadership", d:3, s:"Üst yönetim yapay zeka yatırım kararı almak için sizden net bir ROI taahhüdü istiyor. Henüz pilot yaptınız.", t:"Taahhüt vermeden pilot verisi toplamalısınız. Veri öncesinde kesin sayı vaat etmek yanıltıcı.", options:[{text:"Pilot bulgularını paylaşır, gerçekçi aralıklar sunar ve daha kapsamlı ölçüm için süre isterim.",score:100,feedbackText:"Dürüst lider vaat değil, veri sunar."},{text:"Rakamları tahmin ederim, sonuçlar konuşur.",score:-100,feedbackText:"Gerçekleşmeyen taahhütler güvenilirliği zedeler."},{text:"ROI belirsiz olduğu için yatırımı önermem.",score:0,feedbackText:"Belirsizlik engellemez — pilotu güçlendirerek belirsizliği azaltmak daha iyi."}] },
  { cat:"ai-leadership", d:2, s:"Ekibinizde yapay zekayı çok iyi kullanan bir çalışan var. Diğerleri dışlanmış hissediyor.", t:"Teknoloji avantajı paylaşılabilir. Lider olarak bilgi aktarımını kolaylaştırmak sizin rolünüz.", options:[{text:"Yapay zekayı iyi kullanan çalışanı iç eğitici olarak görevlendiririm.",score:100,feedbackText:"Kapasite geliştirme her zaman ekip avantajı."},{text:"Herkes kendi kendine öğrenir, bu işin doğası.",score:-100,feedbackText:"Bu yaklaşım uçurumları büyütür ve ekip uyumunu bozar."},{text:"Ekibin dışlanma hissini çözmek için yapay zeka kullanımını sınırlarım.",score:0,feedbackText:"Yetenekleri kısıtlamak yerine diğerlerini güçlendirmek daha iyi çözüm."}] },
  { cat:"ai-leadership", d:1, s:"Yapay zeka ile otomatize edilebilecek görevler için hâlâ tam zamanlı çalışan istihdam ediyorsunuz.", t:"İş gücü kararları maliyet-değer dengesi gerektirir. Aceleyle otomasyon değer kaybına yol açabilir.", options:[{text:"Otomatize edilebilir görevleri belirlerim ama etkilenecek çalışanların daha değerli işlere yönlendirilmesini de planlarım.",score:100,feedbackText:"Verimlilik + insani sorumluluk birlikte yönetilmeli."},{text:"Maliyet azaltmak için tüm tekrarlayan görevleri hemen otomatize ederim.",score:-100,feedbackText:"Acele otomasyon çalışan motivasyonunu ve kurumsal bilgiyi zedeler."},{text:"Çalışanları korumak için otomasyona geçmem.",score:0,feedbackText:"Koruma anlayışlı ama rekabet ortamında uzun vadeli sürdürülebilir değil."}] },
  { cat:"ai-leadership", d:2, s:"Yapay zeka şirket verilerinizi analiz ederek liderlik ekibine öneride bulunuyor. Bazı öneriler mevcut stratejinizle çelişiyor.", t:"Veri odaklı meydan okuma stratejiyi güçlendirir. Savunmacı tepki fırsatı kaçırır.", options:[{text:"Önerileri ciddiye alır, ekiple birlikte mevcut stratejiyi bu bakış açısıyla değerlendiririm.",score:100,feedbackText:"Veri meydan okuması değerli. Açık fikirle yaklaşmak liderlik gücü."},{text:"Stratejiyi biz geliştirdik, yapay zekanın önerisi dış bakış açısıdır.",score:-100,feedbackText:"Dış bakış açısı — ister insandan ister yapay zekadan — gelişim fırsatı sunar."},{text:"Önerileri saklarım, ekibi karıştırmak istemiyorum.",score:0,feedbackText:"Saklama kısa vadede kolaylık ama uzun vadede güven sorunu yaratır."}] },
  { cat:"ai-leadership", d:3, s:"Çalışanlarınızdan birinin performansı yapay zeka analiz sistemiyle izleniyor. Çalışan bundan rahatsız.", t:"Gözetim teknolojisi güven değil kontrol atmosferi yaratabilir.", options:[{text:"Çalışanla konuşur, izlemenin amacını ve sınırlarını açıklarım; gerekirse sistemi gözden geçiririm.",score:100,feedbackText:"Şeffaflık ve diyalog güveni korur."},{text:"Performans takibi şirketi hakkı, çalışan buna uyum sağlamalı.",score:-100,feedbackText:"Yasal olabilir ama güven zedeleyen sistemler çalışan bağlılığını düşürür."},{text:"Sistemi kaldırırım, çalışan rahatsız.",score:0,feedbackText:"Silmek yerine şeffaflığı artırmak daha sürdürülebilir."}] },

  // ai-manufacturing (10)
  { cat:"ai-manufacturing", d:1, s:"Üretim hattınızda yapay zeka kalite kontrol sistemi kurmak istiyorsunuz. Çalışanlar yerlerini kaybetmekten endişeli.", t:"Otomasyon kaçınılmaz ama geçişi yönetmek liderlik sorumluluğudur.", options:[{text:"Çalışanları sistem tasarımına dahil eder, kalite kontrol rollerini sistemi denetleme ve iyileştirmeye dönüştürürüm.",score:100,feedbackText:"Değişimi birlikte şekillendirmek hem daha etik hem daha etkili."},{text:"Sistemi kurarım, gereksiz hale gelen pozisyonları kapatırım.",score:-100,feedbackText:"Ani işten çıkarmalar moral bozar ve kurumsal bilgiyi kaybettirir."},{text:"Çalışanlar endişeli olduğu için sistemi kurmaktan vazgeçerim.",score:0,feedbackText:"Endişeleri çözmek projeyi iptal etmekten daha iyi. Geçiş yönetimi şart."}] },
  { cat:"ai-manufacturing", d:2, s:"Yapay zeka tahmine dayalı bakım sistemi bir arızayı önceden işaret etti. Ekip buna inanmıyor ve bakımı erteliyor.", t:"Veriye dayalı uyarıları görmezden gelmek maliyetli olabilir.", options:[{text:"Verinin dayandığı sensör verilerini ekiple paylaşır, uyarının gerekçesini anlatırım. Önlem alırım.",score:100,feedbackText:"Veri okuryazarlığı + proaktif önlem = üretimde güç."},{text:"Ekibin deneyimine güvenirim, makine iyi görünüyor.",score:-100,feedbackText:"Deneyim değerli ama veri erken uyarı verir. İkisi birlikte kullanılmalı."},{text:"Arıza çıkarsa o zaman bakarım.",score:0,feedbackText:"Reaktif bakım planlı bakımdan çok daha pahalıdır."}] },
  { cat:"ai-manufacturing", d:2, s:"Yapay zeka üretim planlamasını optimize ederken bazı ürün gruplarına öncelik veriyor. Bunun neden olduğunu anlamıyorsunuz.", t:"Anlaşılmayan otomasyon güvensizlik yaratır. Kara kutu kararlar sorgulanmalı.", options:[{text:"Sistemi konfigüre eden ekipten önceliklendirme mantığını anlatmalarını isterim.",score:100,feedbackText:"Anlamak kontrol etmenin başlangıcı. Doğru tutum."},{text:"Sonuçlar iyi çıkıyor, mantığını anlamak zorunda değilim.",score:0,feedbackText:"Bugün iyi ama koşullar değiştiğinde kara kutu yönetimi zorlaşır."},{text:"Sistemi kapatır eski planlama yöntemine dönerim.",score:-100,feedbackText:"Anlamamak çözüm değil. Öğrenmek daha değerli."}] },
  { cat:"ai-manufacturing", d:1, s:"Yapay zeka tedarik zinciri riskleri konusunda erken uyarılar veriyor. Ama tedarikçilerinizle uzun süreli ilişkiniz var ve güveniyorsunuz.", t:"Veriye dayalı uyarı kişisel güveni yerinden etmez — ama görmezden de gelmez.", options:[{text:"Tedarikçimle uyarı konusunu açıkça görüşür, birlikte risk değerlendirmesi yaparız.",score:100,feedbackText:"Şeffaf diyalog ve veri birlikte güçlü tedarik yönetimi."},{text:"Uzun yıllık ilişkim var, sisteme değil tedarikçime güvenirim.",score:-100,feedbackText:"Güven değerli ama veri bağımsız sinyal. İkisi birlikte daha iyi karar verir."},{text:"Alternatif tedarikçi aramaya başlarım.",score:0,feedbackText:"Alternatif akıllıca ama önce mevcut tedarikçiyle görüşmek daha adil."}] },
  { cat:"ai-manufacturing", d:3, s:"Yapay zeka üretim verimlilik verilerini analiz etti ve bir operatörün performansının düşük olduğunu gösteriyor. Ancak operatörün 20 yıllık deneyimi var.", t:"Veri kalıpları gösterir, bağlamı insanlar yorumlar. Deneyim verinin ötesinde anlam taşır.", options:[{text:"Operatörle bire bir konuşur, verinin gösterdiği kalıbı paylaşır ve nedenini birlikte anlarım.",score:100,feedbackText:"Veri + insan diyaloğu = adil ve doğru değerlendirme."},{text:"Veri düşük performans gösteriyorsa resmi uyarı veririm.",score:-100,feedbackText:"Bağlamı anlamadan veriyle karar vermek adaletsiz olabilir."},{text:"20 yıllık deneyim her şeyi anlatır, veriye inanmam.",score:0,feedbackText:"Deneyim değerli ama veri de bir sinyal. İkisini birleştirmek en sağlıklı yol."}] },
  { cat:"ai-manufacturing", d:2, s:"Yapay zeka enerji tüketim optimizasyonu öneriyor. Ama önerilen değişiklikler mevcut üretim ritminizi bozacak.", t:"Verimlilik ve ritim birlikte değerlendirilmeli. Optimizasyon tek boyutlu değildir.", options:[{text:"Önerileri üretim ekibiyle test eder, ritme etkisini ölçer ve sonra karar veririm.",score:100,feedbackText:"Pilot test büyük değişikliklerden önce şart."},{text:"Enerji maliyeti önceliğim, üretim ritmi ayarlanır.",score:0,feedbackText:"Ritim bozulması kalite ve termin sorunlarına yol açabilir. Dikkatli analiz gerekli."},{text:"Mevcut ritmimiz iyi, öneriyi reddederim.",score:-100,feedbackText:"Red yerine test etmek bilgi kazandırır. Hiç denemeden reddetmek fırsatı kaçırır."}] },
  { cat:"ai-manufacturing", d:1, s:"Yapay zeka ürün kalite tahminleri yapıyor ve bazı ürünleri henüz üretilmeden hurda olarak işaretliyor.", t:"Tahmine dayalı kalite kontrolü hurda maliyetini düşürür ama yanlış pozitifler sorundur.", options:[{text:"Hurda işaretlenen ürünleri manuel olarak kontrol eder, sistemin doğruluğunu ölçerim.",score:100,feedbackText:"Doğrulama olmadan otomasyon güvenilir olmaz."},{text:"Sistem işaretliyorsa hemen hurda yaparım, güveniyorum.",score:-100,feedbackText:"Yanlış pozitifler değerli ürünleri israf edebilir. Doğrulama şart."},{text:"Sistemi kapatırım, üretim tamamlanana kadar kalite kontrolü yapamam.",score:0,feedbackText:"Tahmin hatalı olabilir ama değeri de var. Doğrulama süreciyle kullanmak daha iyi."}] },
  { cat:"ai-manufacturing", d:2, s:"Üretim siteniz yapay zeka tabanlı güvenlik izleme sistemi kuruyor. Çalışanlar sürekli izlendiklerini hissediyor.", t:"Güvenlik izleme güven değil denetim hissi yaratabilir. Şeffaflık şart.", options:[{text:"Sistemin amacını, hangi verilerin toplandığını ve nasıl kullanıldığını çalışanlara açıklarım.",score:100,feedbackText:"Şeffaflık güven inşa eder. Zorunlu adım."},{text:"Güvenlik için izleme şart, çalışanlar alışır.",score:-100,feedbackText:"Zorunlu olabilir ama şeffaf olmadan adaptasyon sağlanamaz."},{text:"İzleme sistemini kaldırırım, çalışan memnuniyeti önce.",score:0,feedbackText:"Güvenlik önemli. Şeffaflıkla ikisi birlikte sağlanabilir."}] },
  { cat:"ai-manufacturing", d:3, s:"Yapay zeka üretim hattınızda bir güvenlik riski tespit etti ama insan gözetmenler bunu görmemiş.", t:"Yapay zeka çok sayıda sensör verisini eş anlı izler — insanın gözden kaçırabileceğini yakalayabilir.", options:[{text:"Yapay zekanın tespit ettiği riski güvenlik ekibiyle birlikte hemen değerlendiririm.",score:100,feedbackText:"Güvenlik konusunda hızlı hareket şart. Doğru tutum."},{text:"Gözetmenler görmedi, yanlış alarm olabilir.",score:-100,feedbackText:"Güvenlik risklerinde yanlış alarm ucuz, kazalar pahalıdır. Değerlendirme şart."},{text:"Sistemi kalibre ettiririm, fazla alarm veriyorsa güvenilmez.",score:0,feedbackText:"Kalibrasyon gerekebilir ama önce bu spesifik riski değerlendirin."}] },
  { cat:"ai-manufacturing", d:1, s:"Yapay zeka üretim maliyetlerinizi analiz etti ve bir hammadde tedarikçisini değiştirmenizi öneriyor. Mevcut tedarikçiyle 10 yıllık ilişkiniz var.", t:"Veri odaklı kararlar ilişkileri göz ardı etmemeli ama ilişkiler veriyi geçersiz kılmamalı.", options:[{text:"Tedarikçiyle veriye dayalı bir konuşma yapar, fiyat ve kalite konusunda birlikte çözüm ararım.",score:100,feedbackText:"Diyalog ilişkiyi ve veriyi birlikte değerlendirir. En dengeli yaklaşım."},{text:"10 yıllık ilişki her şeyden değerli, tedarikçiyi değiştirmem.",score:-100,feedbackText:"İlişki önemli ama sürekli yüksek maliyet sürdürülebilir değil."},{text:"Yapay zekanın önerdiği tedarikçiye geçerim.",score:0,feedbackText:"Geçmeden önce mevcut ilişkiyi değerlendirmek hem adil hem stratejik."}] },

  // ai-media-content (10)
  { cat:"ai-media-content", d:1, s:"Bir yapay zeka makalenizin ilk taslağını oluşturdu. Yayınlamadan önce ne yaparsınız?", t:"Yapay zeka hız sağlar, editöryal sorumluluk insana aittir.", options:[{text:"Gerçekleri doğrularım, sesimi eklerim, alıntıları kontrol eder ve sonra yayınlarım.",score:100,feedbackText:"Yapay zeka taslakta, insan kalitede. Doğru iş akışı."},{text:"Taslak iyi göründü, olduğu gibi yayınlarım.",score:-100,feedbackText:"Yapay zeka hatalı bilgi üretebilir. Doğrulama zorunlu."},{text:"Yapay zeka yazdıysa benim makalem değil, kullanmam.",score:0,feedbackText:"Araç kullanmak insan yazarlığını ortadan kaldırmaz. İnsan editöryal kararla sahiplenir."}] },
  { cat:"ai-media-content", d:2, s:"Yapay zeka ürettiğiniz içeriği okuyuculardan saklamanız mı gerekiyor? Şeffaflık meselesini tartışıyorsunuz.", t:"Şeffaflık okuyucu güveninin temelidir. Gizleme kısa vadede kolaylık, uzun vadede kriz.", options:[{text:"Yapay zeka destekli içerikleri açıkça belirtirim — okuyucular bu bilgiyi hak ediyor.",score:100,feedbackText:"Şeffaflık güveni artırır ve sektör standardını yükseltir."},{text:"Tüm içerikler editoryal denetimden geçiyor, etiket şart değil.",score:0,feedbackText:"Denetim olsa da okuyucu şeffaflık talep etme hakkına sahip."},{text:"Rakiplerim yazmıyor, ben de yazmam.",score:-100,feedbackText:"Sektör standardı argümanı zayıf. Güven bireysel karar."}] },
  { cat:"ai-media-content", d:1, s:"Yapay zeka sosyal medya içeriklerinizi otomatik planlamak ve yayınlamak istiyor. Her şeyi otomatik bırakmayı düşünüyorsunuz.", t:"Otomasyon hızlandırır ama gerçek zamanlı olaylar otomasyonu devre dışı bırakabilir.", options:[{text:"Rutin içerikleri otomatikleştiririm ama kriz anlarında ve güncel olaylar sırasında manuel kontrol yaparım.",score:100,feedbackText:"Otomasyon + insan denetimi = güvenli içerik yönetimi."},{text:"Tam otomasyon verimliliği artırır, her şeyi bırakırım.",score:-100,feedbackText:"Hassas bir durumda yanlış içerik yayınlamak marka krizine yol açabilir."},{text:"Sosyal medyayı tamamen kendim yönetirim, otomasyon güvenilmez.",score:0,feedbackText:"Tam manuel yönetim sürdürülemez. Hibrit yaklaşım daha akıllıca."}] },
  { cat:"ai-media-content", d:2, s:"Yapay zeka yazdığınız haberler gerçek haberlere çok benziyor ama tamamen kurgusal. Yanlış anlaşılma riski var.", t:"Kurgusal içerik açıkça etiketlenmezse dezenformasyon olur.", options:[{text:"Kurgusal içerikleri açıkça etiketlerim ve gerçek haberlerden görsel olarak ayırt edici yaparım.",score:100,feedbackText:"Şeffaf etiketleme dezenformasyonu önler. Zorunlu."},{text:"Okuyucular anlar, gerçek haber gibi görünüyor ama değil.",score:-100,feedbackText:"Okuyucuların yüzde yüzü ayırt edemez. Kasıtlı karıştırma etik ihlaldir."},{text:"Bir uyarı notu eklerim sayfanın altına.",score:0,feedbackText:"Altbilgi yetersiz. Belirgin etiket şart."}] },
  { cat:"ai-media-content", d:3, s:"Yapay zeka röportaj verilerini analiz ederek size alıntı önerileri sunuyor. Ama bu alıntılar gerçek röportajdan değil, yapay zeka sentezi.", t:"Röportaj alıntısı kişinin kendi sözleri olmalıdır. Sentezlenmiş alıntı dezenformasyondur.", options:[{text:"Yalnızca gerçek röportaj alıntıları kullanırım. Yapay zeka analize yardımcı olabilir ama alıntı üretemez.",score:100,feedbackText:"Gazetecilik etiği açık. Gerçek alıntı şart."},{text:"Genel fikri doğruysa alıntıyı kullanabilirim.",score:-100,feedbackText:"Fikirde benzer olsa bile kelimeler kişinin kendi sözleri değil. Yanıltıcı."},{text:"Alıntı sentezi olduğunu bir not olarak belirtirim.",score:0,feedbackText:"Notla bile sentezlenmiş alıntı kullanmak gazetecilik standardının dışına çıkar."}] },
  { cat:"ai-media-content", d:2, s:"Yapay zeka sizin için tıklama oranını artıracak başlıklar üretiyor. Ama bunlar içeriği abartıyor.", t:"Clickbait kısa vadeli tıklama, uzun vadede güven kaybı demektir.", options:[{text:"İçeriği doğru yansıtan, merak uyandıran ama abartmayan başlıklar için yapay zekayı yeniden yönlendiririm.",score:100,feedbackText:"Doğru çerçeveleme hem etik hem uzun vadede daha değerli."},{text:"Tıklama önemli, başlık abartılsa da içerik doğru.",score:-100,feedbackText:"Okuyucu başlıkla aldatıldığını hissedince güveni kalıcı olarak kaybolur."},{text:"Rakipler yapıyor, ben de yaparsam sorun yok.",score:0,feedbackText:"Sektör standardı argümanı etik değerlendirme değil. Güven bireysel karar."}] },
  { cat:"ai-media-content", d:1, s:"Yapay zeka görsel üretiyorsunuz ama bu görseller var olan fotoğrafçıların çalışmalarına çok benziyor.", t:"Yapay zeka görsellerinde telif ve etik sorunlar henüz netlik kazanmadı.", options:[{text:"Eğitim verisi ve benzerlik konusunda hukuki değerlendirme yaptırır, güvenli bir kullanım politikası oluştururum.",score:100,feedbackText:"Belirsiz alanda dikkatli olmak hem etik hem akıllıca."},{text:"Yapay zeka üretimi özgün sayılır, sorun yok.",score:-100,feedbackText:"Bu yargı tartışmalı. Hukuki belirsizlik riskini küçümsemek sorunlu."},{text:"Sadece kendi orijinal fotoğraflarımı kullanırım.",score:0,feedbackText:"Güvenli seçim ama yapay zekanın etik kullanımını öğrenmek de değerli."}] },
  { cat:"ai-media-content", d:3, s:"Yapay zeka ile üretilen deepfake videolar gerçek kişileri taklit ediyor. Bunları içerik oluşturmak için kullanmayı düşünüyorsunuz.", t:"Deepfake içerik etik ve yasal sorunlar taşır. Onaysız gerçek kişi taklidi zararlıdır.", options:[{text:"Gerçek kişilerin rızası olmadan deepfake kullanmayı reddederim.",score:100,feedbackText:"Net etik sınır. Doğru tutum."},{text:"Eğlence amaçlı kullanım zararlı değildir.",score:-100,feedbackText:"Onaysız taklit kişinin itibarını zedeler ve pek çok ülkede yasal sorunlar yaratır."},{text:"Sadece kamuya açık kişiler için kullanırım.",score:0,feedbackText:"Kamuya açık kişi de rıza gerektiren bir bireydir. Onay şart."}] },
  { cat:"ai-media-content", d:2, s:"Yapay zeka içerik algoritması takipçi büyüme için belirli konulara odaklanmanızı öneriyor ama bu konular değerlerinizle çelişiyor.", t:"Algoritmanın önerdiği ile değerlerinizin buluştuğu alan en sürdürülebilir içerik stratejisidir.", options:[{text:"Değerlerimle örtüşen ama algoritmaya da uygun içerikler bulmak için farklı konular denerim.",score:100,feedbackText:"Değer + algoritma dengesi uzun vadeli büyüme için doğru yol."},{text:"Büyüme için değerlerimden taviz veririm, geçici bir strateji.",score:-100,feedbackText:"Değer erozyonu kalıcı hale gelir ve takipçi güvenini aşındırır."},{text:"Algoritmayı görmezden gelirim, doğal büyüme oluşur.",score:0,feedbackText:"Organik büyüme güzel ama algoritmayı tamamen reddetmek fırsatı kaçırır."}] },
  { cat:"ai-media-content", d:1, s:"Yapay zeka podcast bölümleriniz için özet ve başlıklar üretiyor. Ama özet bazen yanlış bağlamlar çıkarıyor.", t:"Otomatik özetler bağlamı kaçırabilir. İnsan denetimi kaliteyi korur.", options:[{text:"Yapay zekanın özetlerini her bölüm için gözden geçirir, yanlış bağlamları düzeltirim.",score:100,feedbackText:"Denetim + düzeltme = kaliteli otomasyon kullanımı."},{text:"Özetler yeterince iyi, her bölümü kontrol etmem.",score:-100,feedbackText:"Yanlış bağlam markanıza ve içeriğinizin güvenilirliğine zarar verir."},{text:"Yapay zeka özetlerini kullanmam, hepsini kendim yazarım.",score:0,feedbackText:"Manuel yazmak değerli ama taslak alıp düzeltmek hem hızlı hem kaliteli."}] },
]

console.log('Total:', ALL.length, 'questions')
for (let i = 0; i < ALL.length; i += 20) {
  const batch = ALL.slice(i, i + 20)
  await insert(batch)
}
