const TOKEN = 'sbp_f314cf27b5b2a01eea48048a7b1c015cc9cf4b42'
const API = 'https://api.supabase.com/v1/projects/amhfxaqolholacanqyas/database/query'

function esc(s) { return s.replace(/'/g, "''") }

async function insert(batch) {
  const values = batch.map(q => {
    const opts = JSON.stringify(q.options).replace(/'/g, "''")
    return `('tr','${q.cat}','${esc(q.s)}','${esc(q.t)}','${opts}'::jsonb,${q.d},'claude',true)`
  }).join(',')
  const sql = `INSERT INTO questions (locale,category,scenario_text,mindset_tip,options,difficulty,generated_by,is_active) VALUES ${values};`
  const r = await fetch(API, {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${TOKEN}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query: sql })
  })
  const d = await r.json()
  if (d.message) { console.error('ERR:', d.message); return false }
  console.log('OK:', batch.length, 'inserted')
  return true
}

const ALL = [
  // ai-career (10)
  { cat:"ai-career", d:1, s:"Özgeçmişinizde 'yapay zeka deneyimi' bölümü boş kalıyor çünkü hiç kullanmadınız. Bir iş başvurusu yapacaksınız.", t:"Her uzman bir zamanlar acemiydi. Küçük bir adım atmak sizi hiç kullanmadım kategorisinden çıkarır.", options:[{text:"Ücretsiz bir araçla küçük bir proje yapıp bunu deneyim olarak yazarım.",score:100,feedbackText:"Harika. Gerçek deneyim en hızlı yol — üstelik özgeçmişiniz de güncelleniyor."},{text:"O bölümü boş bırakırım, yalan söylemem.",score:0,feedbackText:"Dürüstlük değerlidir ama alternatif var: öğrenerek dürüst bir şekilde doldurmak."},{text:"Yapay zeka deneyimi isteyen pozisyonlara başvurmam.",score:-100,feedbackText:"Bu yaklaşım seçeneklerinizi her geçen ay daraltır."}] },
  { cat:"ai-career", d:2, s:"İş görüşmesinde size 'yapay zekayla iş yapma deneyiminizi anlatın' diyorlar. Çok az deneyiminiz var ama öğrenmeye açıksınız.", t:"İşverenler çoğunlukla hazır uzmandan çok öğrenmeye hevesli biri arar.", options:[{text:"Az ama gerçek deneyimimi paylaşıp aktif öğrenme sürecimden bahsederim.",score:100,feedbackText:"Dürüstlük ve öğrenme motivasyonu güçlü bir kombinasyon."},{text:"Deneyimimi biraz abartarak kendimi daha güçlü gösteririm.",score:-100,feedbackText:"İşe başladıktan sonra bu boşluk ortaya çıkar ve güven sorunu yaratır."},{text:"Soruyu yönlendirip başka güçlü yönlerimden bahsederim.",score:0,feedbackText:"Yön değiştirmek geçici çözüm — açıkça cevaplamak daha etkili olurdu."}] },
  { cat:"ai-career", d:2, s:"Sektörünüzde yapay zeka sertifikaları giderek daha fazla iş ilanında gereksinim olarak çıkıyor. Aylarca süren ve ücretli bir program var.", t:"Stratejik sertifikalar kariyer değeri taşır — ama hangisinin değerli olduğunu araştırmak gerekir.", options:[{text:"Alandaki sertifikaları araştırır, işverenlerin gerçekten aradığını öğrenir ve en değerlisine yatırım yaparım.",score:100,feedbackText:"Bilinçli yatırım doğru yaklaşım."},{text:"Sertifika olmadan da iyi işler bulunur diyerek beklerim.",score:-100,feedbackText:"Bu mantık doğru olabilir — ama trendin aksi yönüne gitmek risk taşır."},{text:"En ucuz sertifikayı alırım, en azından bir şeyim olsun.",score:0,feedbackText:"Bir sertifika hiçbirinden iyidir ama nitelik daha önemli olabilir."}] },
  { cat:"ai-career", d:3, s:"Şirketiniz yapay zeka dönüşümü geçiriyor. Kıdemli çalışanlar olarak eski süreçlerin ustasısınız ama yeni sistem için liderlik teklif edildi. Yetersiz hissediyorsunuz.", t:"Uzmanlık + yeni beceri = güçlü liderlik. Alanı iyi bilenler yapay zekayı en iyi yönlendirebilir.", options:[{text:"Teklifi kabul eder, alan uzmanlığımı getirirken yapay zeka konusunda öğrenmeye devam ederim.",score:100,feedbackText:"Sektör bilgisi + yeni araç bilgisi = nadide kombinasyon. Mükemmel tercih."},{text:"Teklifi geri çeviririm, yetersiz hissediyorum.",score:-100,feedbackText:"Yetersizlik hissi genellikle geçicidir — bu fırsat bir daha gelmeyebilir."},{text:"Kendimi daha hazır hissedene kadar beklerim.",score:0,feedbackText:"Tam hazır hissetmek çoğunlukla mümkün olmaz. Öğrenerek ilerlemek daha gerçekçi."}] },
  { cat:"ai-career", d:1, s:"Bir arkadaşınız yapay zeka sayesinde iş başvurularını üç katına çıkardığını söylüyor. Siz hâlâ el ile her başvuruyu özelleştiriyorsunuz.", t:"Araçlar verimliliği artırır ama kalite kontrolü sizde kalmalı.", options:[{text:"Yapay zekayı özgeçmiş ve başvuru mektuplarını optimize etmek için kullanmayı denerim.",score:100,feedbackText:"Verimlilik kazanımı gerçek — üstelik zaman kaliteli başvurulara ayrılabilir."},{text:"Kendi yöntemime güveniyorum, değiştirmem.",score:-100,feedbackText:"Güven iyi ama iş aramanın yapay zeka çağında değiştiğini görmezden gelmek zor."},{text:"Belki denerim, belki denemem — zamanla bakarım.",score:0,feedbackText:"Belirsizlik bir strateji değil. Az bir deneme bile çok şey öğretir."}] },
  { cat:"ai-career", d:2, s:"Yapay zekanın 'yeni yaratacağı' meslekleri okuyorsunuz ama bunlar için hangi becerileri geliştirmeniz gerektiği belirsiz.", t:"Ortaya çıkan mesleklerde genellikle AI okuryazarlığı + alan uzmanlığı + insani beceriler birleşir.", options:[{text:"Mevcut sektörümde AI okuryazarlığı + eleştirel düşünme + iletişim becerilerini güçlendiririm.",score:100,feedbackText:"Bu üçlü, çoğu yeni meslek için geçerli temel."},{text:"Yeni meslekler netleşene kadar beklerim.",score:-100,feedbackText:"Netleştiğinde rekabet çok artmış olur. Şimdiden temel atmak avantaj sağlar."},{text:"Mevcut kariyerimde kalmak daha güvenli.",score:0,feedbackText:"Güvenli görünebilir ama değişen sektörlerde durağanlık da bir risktir."}] },
  { cat:"ai-career", d:1, s:"Bir yapay zeka CV tarama sisteminin başvurularınızı eleyebileceğini fark ediyorsunuz. Çok sayıda başvurunuz yanıtsız kaldı.", t:"ATS optimizasyonu artık kariyer okuryazarlığının bir parçası.", options:[{text:"Özgeçmişimi anahtar kelime ve format açısından ATS sistemlerine göre optimize ederim.",score:100,feedbackText:"Doğru. Sistemi anlamadan sistemi geçemezsiniz."},{text:"Tanıdıklar aracılığıyla doğrudan başvururum, sistemi atlayabilirim.",score:0,feedbackText:"Network değerlidir ama özgeçmişi optimize etmek de şart — ikisi birbirini dışlamaz."},{text:"Sistem haksız, ben gerçek yeteneklere odaklanırım.",score:-100,feedbackText:"Haksız olabilir ama gerçeklik bu. Sistemi değiştirene kadar içinde oynamak zorundasınuz."}] },
  { cat:"ai-career", d:3, s:"Meslektaşınız yapay zeka yardımıyla aynı işi sizden iki kat hızlı yapıyor. Veriminiz geride kalıyor ama siz kaliteye daha çok önem veriyorsunuz.", t:"Hız ve kalite artık zıt değil — ikisi birlikte mümkün.", options:[{text:"Meslektaşımın kullandığı araçları öğrenir, kalite standartlarımı koruyarak verimliliğimi artırırım.",score:100,feedbackText:"İşte bu yaklaşım rekabet gücü sağlar."},{text:"Kalite önemli, hız ikincildir — yöntemimi değiştirmem.",score:-100,feedbackText:"Müşteri ve işveren gözünde kalite + hız birlikte beklentiye dönüştü."},{text:"İkimizi karşılaştırmak adil değil, her çalışma tarzı farklı.",score:0,feedbackText:"Farklılık gerçek ama piyasanın beklentisi değişiyor — farkında olmak önemli."}] },
  { cat:"ai-career", d:2, s:"Kariyerinizde büyük bir değişim yapmak istiyorsunuz. Hedeflediğiniz sektör yapay zekayı yoğun kullanıyor ama siz dışarıdan geliyorsunuz.", t:"Sektörler arası geçişlerde AI becerileri köprü görevi görür.", options:[{text:"Hedef sektördeki AI kullanım pratiklerini öğrenir, portfolyom için projeler üretirim.",score:100,feedbackText:"Güçlü strateji. Yapay zeka projeleri somut geçiş kanıtı olur."},{text:"Önce geleneksel yolla sektöre girip sonra AI öğrenirim.",score:0,feedbackText:"İşe yarayabilir ama AI okuryazarlığıyla girmek ilk adımdan avantaj sağlar."},{text:"Bu sektöre geçmek için çok geç, farklı bir hedef seçerim.",score:-100,feedbackText:"Geç değil. Doğru stratejiyle sektör geçişleri her zaman mümkün."}] },
  { cat:"ai-career", d:3, s:"Kariyerinizde 15 yıllık uzmanlığınız var. Yapay zekanın alanınızdaki etkisini nesnel değerlendirmenizi istediler — kendinize karşı dürüst olmak zor geliyor.", t:"Alan uzmanlığı + AI eleştirisi = değerli kombinasyon. Deneyiminiz yargılamanızı güçlendirir.", options:[{text:"Yapay zekanın güçlü ve zayıf yönlerini nesnel değerlendirip hangi görevlerde gerçekten yardımcı olduğunu belirtirim.",score:100,feedbackText:"Deneyimli ve dürüst değerlendirme — bu perspektif çok değerli."},{text:"Yapay zekanın alanımı tehdit etmediğini savunurum.",score:-100,feedbackText:"Savunmacı tutum nesnel değerlendirmeyi engeller ve güvenilirliği zedeler."},{text:"Yapay zekanın her şeyi değiştireceğini kabul ederim çünkü gündemde bu var.",score:0,feedbackText:"Trende uymak gerçek değerlendirmenin yerini tutmaz. Kendi analiziniz daha değerli."}] },

  // ai-communication (10)
  { cat:"ai-communication", d:1, s:"Ekibinize uzun bir e-posta yazmanız gerekiyor ama zaman baskısı altındasınız. Yapay zeka yazmaya yardım edebilir.", t:"Yapay zeka taslak oluşturur, siz kendi sesinizi ve bağlamı eklersiniz.", options:[{text:"Yapay zekadan bir taslak alır, kendi sesim ve detaylarımla düzenleyerek gönderirim.",score:100,feedbackText:"Verimli ve kaliteli — taslak başlangıcı hızlandırır, düzenleme kaliteyi sağlar."},{text:"Yapay zekanın yazdığını olduğu gibi gönderirim, zaman yok.",score:-100,feedbackText:"Bağlama uymayan veya soğuk gelen bir mesaj iletişimi zayıflatır."},{text:"Yapay zekayı kullanmam, e-postayı kendim yazarım ama kısa tutarım.",score:0,feedbackText:"Kısa iyi ama gerekli detaylar kaybolabilir. Taslak alarak denemek değer."}] },
  { cat:"ai-communication", d:2, s:"Müşterinize zor bir haberi iletmeniz gerekiyor. Yapay zeka empati odaklı bir mesaj yazmanıza yardımcı olabilir ama bu çok kişisel bir durum.", t:"Empati özgündür. Yapay zeka yapıyı kurar, insani dokunuşu siz eklersiniz.", options:[{text:"Yapay zekadan bir çerçeve alır, müşteriyle ilişkime ve duruma göre tamamen özelleştiririm.",score:100,feedbackText:"Doğru denge: yapı + özgün empati."},{text:"Zor haberler için yapay zekayı hiç kullanmam, çok kişisel.",score:0,feedbackText:"Bu tercih saygıdeğer ama yapay zekanın yapıyı kurması sizi daha net ifade ettirmeye yardımcı olabilir."},{text:"Yapay zekanın yazdığı empati mesajını aynen gönderirim, iyi yazıyor.",score:-100,feedbackText:"Şablonlaşmış empati bazen daha soğuk algılanabilir. Kişiselleştirme şart."}] },
  { cat:"ai-communication", d:1, s:"Farklı kültürlerden ekip üyelerine e-posta gönderiyorsunuz. Kültürel nüanslar konusunda emin değilsiniz.", t:"Kültürel farkındalık iletişimi güçlendirir — yapay zeka bu konuda rehberlik edebilir.", options:[{text:"Yapay zekadan kültürel iletişim farklılıkları konusunda rehberlik ister, mesajı buna göre düzenlerim.",score:100,feedbackText:"Bilinçli iletişim kültürlerarası ilişkileri güçlendirir."},{text:"İngilizce resmi bir tarz kullanır ve herkesin anlayacağını umarım.",score:0,feedbackText:"Resmiyet güvenli ama bazı kültürler farklı ton bekler. Öğrenmek değer."},{text:"Herkese aynı mesajı gönderirim, dil bariyerlerini aşmak onların sorumluluğu.",score:-100,feedbackText:"Bu yaklaşım ekip uyumunu ve iletişimi zayıflatır."}] },
  { cat:"ai-communication", d:2, s:"Önemli bir sunum yapacaksınız. Yapay zeka slayt içeriklerini otomatik oluşturmayı teklif ediyor ama siz her detayı kontrol etmek istiyorsunuz.", t:"Kontrol ve verimlilik dengelenebilir. Yapay zeka taslak sunar, siz sahiplenirsiniz.", options:[{text:"Yapay zekadan iskelet ve öneriler alır, her slaydı detaylıca gözden geçirip onaylarım.",score:100,feedbackText:"Verimli ve kontrollü. Taslaktan başlamak kaliteyi düşürmez."},{text:"Her slaydı sıfırdan kendim yaparım, böylece her şeyden eminim.",score:0,feedbackText:"Tam kontrol değerli ama yapay zekayla başlamak zaman ve enerji kazandırır."},{text:"Yapay zekanın oluşturduğunu doğrudan kullanırım, kontrol etmem.",score:-100,feedbackText:"Sunumunuzdaki hata veya yanlış bilgi sizi temsil eder. Kontrol şart."}] },
  { cat:"ai-communication", d:3, s:"Müzakere sürecinde karşı tarafın argümanlarına yanıt hazırlamak için yapay zekadan destek aldınız. Karşı taraf bunu öğrenirse ne düşünürsünüz?", t:"Araç kullanmak stratejik zayıflık değil — ama şeffaflık güven inşa eder.", options:[{text:"Sorun görmem. Araştırma ve hazırlık için araç kullanmak meşru — önemli olan kendi kararım.",score:100,feedbackText:"Doğru tutum. Araç hazırlık için, karar sizin."},{text:"Utanırdım, yapay zeka kullandığımı söylemezdim.",score:-100,feedbackText:"Utanmak için sebep yok. Araç kullanmak standart bir pratik haline geliyor."},{text:"Belki gelecekte kullanmam, güven sorunu yaratmasın.",score:0,feedbackText:"Şeffaf olmak mümkün — analiz için araçlar kullandım demek zayıflık değil."}] },
  { cat:"ai-communication", d:1, s:"Sosyal medyada şirketiniz adına yorum yazmanız gerekiyor. Yapay zeka bir yanıt önerdi ama biraz genel geliyor.", t:"Marka sesi özgündür. Yapay zekanın çerçevesi + markanın kişiliği birleşince etkili olur.", options:[{text:"Öneriyi marka sesimize ve durumun özelliğine göre düzenleyip yayınlarım.",score:100,feedbackText:"Doğru yaklaşım. Genel şablon yerine özgün ses."},{text:"Yapay zekanın yazdığını olduğu gibi yayınlarım, yeterince iyi.",score:-100,feedbackText:"Genel yanıtlar markanın özgünlüğünü zayıflatır ve bazen yanlış tonu yakalar."},{text:"Yapay zekayı sosyal medyada hiç kullanmam, çok riskli.",score:0,feedbackText:"Risk yönetilebilir. Kontrollü kullanım verimliliği artırır."}] },
  { cat:"ai-communication", d:2, s:"Ekip toplantısı notlarınızı yapay zeka ile özetlettiniz. Ama toplantıda söylenenlerin bazıları yanlış yorumlanmış gibi görünüyor.", t:"Yapay zeka yorumlar — bağlamı kaçırabilir. İnsan denetimi kritik.", options:[{text:"Özeti dikkatlice kontrol eder, yanlış yorumlanan kısımları düzeltirim ve sonra paylaşırım.",score:100,feedbackText:"İnsan denetimi şart. Özetin güvenilirliği sizin kontrolünüzden geçer."},{text:"Yapay zekanın özetini doğrudan paylaşırım, genellikle doğrudur.",score:-100,feedbackText:"Genellikle doğru kritik toplantılar için yeterli değil. Bir hata güven kaybına yol açabilir."},{text:"Bundan sonra not özetleme için yapay zeka kullanmam.",score:0,feedbackText:"Tek kötü deneyim aracı bırakmak için sebep değil. Süreci geliştirmek daha iyi."}] },
  { cat:"ai-communication", d:3, s:"Uluslararası bir iş ortağıyla iletişimde yapay zekadan çeviri yardımı alıyorsunuz. Ama bazı ifadeler kültürel bağlamda yanlış anlaşılmış gibi görünüyor.", t:"Makine çevirisi kelimeyi çevirir, kültürü değil. İnsan yargısı hâlâ şart.", options:[{text:"Çeviriyi bir kültürel danışmana veya yerel konuşmacıya kontrol ettiririm ve önemli iletişimlerde ikinci göz kullanırım.",score:100,feedbackText:"Profesyonel yaklaşım. Kültürel nüans iş ilişkisini belirler."},{text:"Yapay zeka çevirisi yeterli, küçük hatalar affedilebilir.",score:-100,feedbackText:"Küçük kültürel hatalar bazen büyük yanlış anlaşılmalara yol açar."},{text:"Bundan sonra sadece İngilizce iletişim kurarım, çeviri riski almam.",score:0,feedbackText:"İngilizce güvenli ama ortağın dilinde iletişim güven inşa eder. Riski yönetmek daha iyi."}] },
  { cat:"ai-communication", d:1, s:"Yeni bir müşteriye tanıtım mesajı yazıyorsunuz. Yapay zeka şablonlar sunuyor ama müşteri çok özgün bir profil.", t:"Şablonlar başlangıç noktası — özgün bağlam sizi farklılaştırır.", options:[{text:"Şablonu temel alır ama müşterinin sektörüne, sorunlarına ve hedeflerine özel detaylar eklerim.",score:100,feedbackText:"Kişiselleştirme yanıt oranını artırır. İyi strateji."},{text:"En iyi şablonu bulur ve olduğu gibi gönderirim, zamanım yok.",score:-100,feedbackText:"Şablon mesajlar genellikle görmezden gelinir. Az bir kişiselleştirme büyük fark yaratır."},{text:"Yapay zeka şablonlarını kullanmam, hepsini sıfırdan yazarım.",score:0,feedbackText:"Sıfırdan yazmak değerli ama şablondan başlayıp kişiselleştirmek hem hızlı hem etkili."}] },
  { cat:"ai-communication", d:2, s:"Kriz anında hızlı iletişim kurmanız gerekiyor. Yapay zekadan acil basın açıklaması yardımı aldınız ama içerik hassas bilgiler içeriyor.", t:"Kriz iletişiminde hız + doğruluk + gizlilik birlikte yönetilmelidir.", options:[{text:"Yapay zekaya yalnızca kamuya açık bilgiler veririm, hassas kısımları kendim yazarım ve hukuki ekiple onaylatırım.",score:100,feedbackText:"Güvenli ve etkili yaklaşım. Gizlilik sınırlarını korumak şart."},{text:"Zaman baskısı var, yapay zekaya her şeyi anlatır ve açıklamayı hemen yayınlarım.",score:-100,feedbackText:"Hassas bilgilerin üçüncü taraf sistemlere girmesi ciddi risk taşır."},{text:"Kriz anında yapay zeka kullanmam, çok kritik.",score:0,feedbackText:"Dikkatli kullanım mümkün. Sınırları belirlemek riski azaltır."}] },

  // ai-cost-business (10)
  { cat:"ai-cost-business", d:1, s:"Şirketiniz yapay zeka abonelik maliyetlerini sorguluyor. Araçlar pahalı ama ekip bunlara alıştı.", t:"Maliyet analizi için kullanım verilerine bakın — hangi araç gerçekten değer yaratıyor?", options:[{text:"Her aracın kullanım oranını ve iş çıktısına katkısını ölçer, kullanılmayanları iptal ederim.",score:100,feedbackText:"Veriye dayalı karar en doğrusu. Alışkanlık maliyet gerekçesi değil."},{text:"Ekip alıştıysa iptaller moral bozar, devam edelim.",score:-100,feedbackText:"Alışkanlık maliyet yönetiminin önüne geçmemeli. ROI şart."},{text:"Fiyat müzakeresi yaparım ama iptale gitmem.",score:0,feedbackText:"Müzakere iyi ama kullanılmayan araçlar için bile para ödüyor olabilirsiniz."}] },
  { cat:"ai-cost-business", d:2, s:"Bir yapay zeka projesine yatırım yapmayı planlıyorsunuz ama geri dönüş süresi belirsiz. Yönetim ROI istiyor.", t:"Belirsiz ROI ölçülebilir hedeflerle netleşir. Verimliliği, zamanı ve kaliteyi ölçün.", options:[{text:"Pilot proje ile somut ölçümler yaparım: zaman tasarrufu, hata azalması, gelir etkisi — bunları yönetime sunarım.",score:100,feedbackText:"Pilot ROI en ikna edici yöntem. Doğru yaklaşım."},{text:"ROI belirsiz olduğu için projeyi ertelerim.",score:-100,feedbackText:"Her dijital dönüşüm başlangıçta belirsizdir. Pilot ile ölçmek bu belirsizliği kırar."},{text:"Rakiplerimiz yapıyor diye gerekçe sunarım.",score:0,feedbackText:"Rekabet gerekçesi zayıf — somut ölçüm çok daha ikna edici."}] },
  { cat:"ai-cost-business", d:2, s:"Küçük işletmeniz için yapay zeka araçlarına para harcamak istemiyorsunuz, ancak ücretsiz seçenekler yetersiz kalıyor.", t:"Ücretsiz araçlar başlangıç için, ücretli araçlar büyüme için — dönüm noktasını tanıyın.", options:[{text:"Hangi görevlerde ücretsiz araçların yetersiz kaldığını tespit eder, yalnızca o görevler için ücretli sürüme geçerim.",score:100,feedbackText:"Hedefli yatırım akıllıca. Tüm ekrana değil, asıl darboğaza harcayın."},{text:"Ücretsiz araçlarla idare ederim, para harcamam.",score:0,feedbackText:"Başlangıç için iyi ama büyüdükçe ücretsiz araçlar sınırlayıcı olabilir."},{text:"En kapsamlı paketi satın alırım, ihtiyacım olacaktır eninde sonunda.",score:-100,feedbackText:"İhtiyacından fazla harcamak küçük işletme için kritik nakit akışını etkiler."}] },
  { cat:"ai-cost-business", d:3, s:"Müşteri hizmetlerini yapay zeka chatbot ile otomatize etmek istiyorsunuz. Maliyeti yüksek ama personel maliyetinden çok daha az. Çalışanlar endişeli.", t:"Otomasyon kararlarında hem maliyet hem de insan faktörü dikkate alınmalı.", options:[{text:"Chatbotu rutin sorular için kurar, karmaşık durumlar için çalışanları müşteri ilişkisine ve yaratıcı çözümlere yönlendiririm.",score:100,feedbackText:"Hibrit model hem verimli hem de çalışan değerini koruyor."},{text:"Maliyeti düşük olduğu için tüm müşteri hizmetlerini chatbota devrederim.",score:-100,feedbackText:"Müşteriler karmaşık durumda insana ulaşmak ister. Tam otomasyon memnuniyeti düşürür."},{text:"Çalışanlar endişeli olduğu için projeden vazgeçerim.",score:0,feedbackText:"Çalışan kaygıları dinlenmeli ama bu kaygıları çözmek projeyi iptal etmekten daha iyi."}] },
  { cat:"ai-cost-business", d:1, s:"Yapay zeka araçlarını kullanmaya başladınız ama aylık masraf yüksek. Tam olarak ne kazandığınızı ölçmüyorsunuz.", t:"Maliyet varsa ölçüm de olmalı. Kazanç görünmezse maliyet haksız görünür.", options:[{text:"Araçların kullanıldığı görevleri takip eder, harcanan zaman ve çıktı kalitesini öncesiyle karşılaştırırım.",score:100,feedbackText:"Ölçüm olmadan değerlendirme olmaz. Doğru adım."},{text:"Zaten işe yarıyor hissediyorum, ölçmeme gerek yok.",score:-100,feedbackText:"Hissetmek bütçe kararı için yeterli değil. Rakamlar şart."},{text:"Maliyeti azaltmak için bazı araçları iptal ederim, kararımı sonra değerlendiririm.",score:0,feedbackText:"Önce ölçmek, sonra kesmek daha akıllıca — hangi araç değer üretiyor belli olur."}] },
  { cat:"ai-cost-business", d:2, s:"Yatırım yaptığınız yapay zeka çözümü beklentileri karşılamıyor. Sözleşme devam ediyor, çıkmak maliyetli.", t:"Kötü yatırımda devam kararı duygusalla değil, gerçek maliyetle verilmeli.", options:[{text:"Kalan sürede maksimum değer çıkarmak için kullanım stratejimi gözden geçirir ve bir sonraki sözleşmede daha iyi müzakere yaparım.",score:100,feedbackText:"Pragmatik yaklaşım. Hem bugünkü kaybı minimize eder hem de gelecek için öğrenir."},{text:"Sözleşmeyi feshetmek için her yolu denerim, para gidiyor.",score:0,feedbackText:"Çıkış maliyeti bazen devam etmekten pahalı olabilir. Hesaplamak gerekir."},{text:"Devam ederim ve değişmeyeceğine inandım, sonuçlara bakarım.",score:-100,feedbackText:"Pasif bekleme kayıpları büyütür. Aktif çözüm arayışı şart."}] },
  { cat:"ai-cost-business", d:3, s:"Şirketiniz yapay zeka altyapısı için kendi sistemi mi yoksa hazır SaaS çözümü mü kullanacağını tartışıyor. Her iki seçeneğin de maliyeti yüksek.", t:"Yapı veya satın alma kararında ölçek, ihtiyaç ve sürdürülebilirlik belirleyicidir.", options:[{text:"İki seçeneği gerçek ihtiyaçlarımıza, takım kapasitemize ve uzun vadeli maliyete göre karşılaştırırım.",score:100,feedbackText:"Doğru çerçeve. Teknik kapasite + maliyet + ihtiyaç birlikte değerlendirilmeli."},{text:"SaaS her zaman daha hızlı ve ucuzdur, onu seçerim.",score:0,feedbackText:"Genellikle doğru ama büyük ölçekte kendi sistemi daha ekonomik olabilir. Karşılaştırma gerekli."},{text:"Kendi sistemimizi kurarız, verilerimiz bizde olsun.",score:-100,feedbackText:"Veri gizliliği önemli ama inşa maliyeti ve bakım yükü göz ardı edilemez."}] },
  { cat:"ai-cost-business", d:1, s:"Yapay zekayı kullanmak için hangi araçlara para harcayacağınızı bilmiyorsunuz. Piyasada çok fazla seçenek var.", t:"İhtiyacı önce tanımlayın, sonra araca bakın — ters sıra parayı boşa harcar.", options:[{text:"Hangi iş problemlerimi çözmek istediğimi listeler, her problem için en basit ve ucuz çözümü denerim.",score:100,feedbackText:"İhtiyaç önce, araç sonra. En sağlıklı yaklaşım."},{text:"En popüler araçları satın alırım, herkesin kullandığı iyidir.",score:-100,feedbackText:"Popülerlik kendi ihtiyacınıza uygun olduğu anlamına gelmez."},{text:"Ücretsiz denemeler yaparım ve ne işime yaradığını deneyerek anlarım.",score:0,feedbackText:"Denemeler değerli ama sistematik ihtiyaç analizi olmadan çok araç denersiniz."}] },
  { cat:"ai-cost-business", d:2, s:"Küçük bir start-up olarak yapay zeka harcamaları bütçenizin büyük bölümünü alıyor ama bu harcamalar büyüme için kritik görünüyor.", t:"Kritik harcama ile savurgan harcama arasındaki fark: ölçülebilir büyüme etkisi.", options:[{text:"Her AI harcamasının büyüme metriğime direkt etkisini takip eder, etkisiz olanları hemen keserim.",score:100,feedbackText:"Verimli optimizasyon erken evrede şart. Doğru yaklaşım."},{text:"Büyüme için para gerekir, hepsini harcamaya devam ederim.",score:-100,feedbackText:"Harcama-büyüme bağlantısı kurulmadan harcamak nakit yakıcı olabilir."},{text:"Mümkün olduğunca az harcayıp ücretsiz alternatiflerde kalırım.",score:0,feedbackText:"Tasarruf sağlıklı ama kritik büyüme araçlarını es geçmek geri kalmanıza yol açabilir."}] },
  { cat:"ai-cost-business", d:3, s:"Departmanınız için yapay zeka bütçesi talep ettiniz ama üst yönetim somut iş etkisi görmeden onaylamıyor.", t:"Yönetim dili: ROI, risk azaltma, rekabet avantajı. Teknik dil değil.", options:[{text:"Pilot proje için küçük bütçe talep eder, somut ölçümler alır ve bu verilerle büyük bütçeyi onaylattırırım.",score:100,feedbackText:"Pilot ile kanıtlamak en ikna edici yol. Stratejik yaklaşım."},{text:"Rakipler yapıyor diye çerçeveleyip onay almaya çalışırım.",score:0,feedbackText:"Rekabet argümanı zayıf — rakibin ROI si şirketinize uygulanamaz."},{text:"Onay gelene kadar beklerim, alternatif araç kullanmam.",score:-100,feedbackText:"Beklemek rekabette geri kalma riski taşır. Küçük adımlar bile ilerleme sağlar."}] },

  // ai-customer-service (10)
  { cat:"ai-customer-service", d:1, s:"Bir müşteri şikayetiyle başa çıkıyorsunuz. Yapay zeka standart bir yanıt önerdi ama müşteri öfkeli ve çok kişisel bir durum var.", t:"Standart yanıtlar verimliliği artırır ama öfkeli müşteri insani dokunuş ister.", options:[{text:"Yapay zekanın çerçevesini kullanırım ama tonu ve kişisel empatiyi kendim eklerim.",score:100,feedbackText:"Doğru denge. Çerçeve verimlilik, özgün empati ilişki kurar."},{text:"Yapay zekanın yazdığını olduğu gibi gönderirim, eğitilmiş bir yanıt bu.",score:-100,feedbackText:"Öfkeli müşteri şablonun ötesinde insan sesi ister. Bu yaklaşım riski artırır."},{text:"Müşteri çok duygusal, yanıt vermemek daha iyi olabilir.",score:0,feedbackText:"Yanıtsız kalmak güvensizlik yaratır. Her şikayete yanıt vermek şart."}] },
  { cat:"ai-customer-service", d:2, s:"Chatbotunuz müşteri sorularının yüzde seksenini çözüyor ama yüzde yirmisinde başarısız oluyor ve müşteriler sinirli hissediyor.", t:"İyi yeterli müşteri memnuniyetinde çalışmaz. Başarısız anların analizi gelişim yolu.", options:[{text:"Başarısız vakaları analiz eder, chatbotu bu boşluklar için geliştiririm ve insana devir sürecini iyileştiririm.",score:100,feedbackText:"Sürekli iyileştirme kültürü. Tam olarak doğru yaklaşım."},{text:"Yüzde seksen çok iyi, kalan için müşteriler anlayış göstermeli.",score:-100,feedbackText:"Yüzde yirmi başarısızlık beş müşteriden birinin hayal kırıklığı demek. Kabul edilemez."},{text:"Chatbotu kapatıp tüm sorulara insan yanıt versin.",score:0,feedbackText:"Yüzde seksen verimliliği atmak çok pahalı. Sistemi geliştirmek daha akıllıca."}] },
  { cat:"ai-customer-service", d:1, s:"Müşteri hizmetleri ekibiniz yapay zekadan gelen otomatik yanıt önerilerini kullanmaktan çekiniyor. Kendi işimi yapabilirim diyorlar.", t:"Araç desteği otomasyon değil — hızlanma ve kalite artışı.", options:[{text:"Ekibe öneri sisteminin işlerini almadığını, daha zor vakalara zaman kazandırdığını gösteririm.",score:100,feedbackText:"Somut fayda göstermek direnç kırar. Doğru yaklaşım."},{text:"Kullanmak istemiyorlarsa zorlamam, iş yapıldıkça yeterli.",score:-100,feedbackText:"Kullanılmayan araç yatırımı boşa harcar ve ekip geride kalır."},{text:"Sistemi zorunlu kullanıma alırım, direktif veririm.",score:0,feedbackText:"Zorlama kullanım olmadan işe yaramaz. İkna daha etkili."}] },
  { cat:"ai-customer-service", d:2, s:"Yapay zeka chatbotunuz yanlış bir bilgi vererek bir müşteriyi yanılttı. Müşteri bu bilgiyle karar aldı.", t:"Yapay zeka hataları sorumluluk gerektirir. Düzeltme ve önlem birlikte gelmelidir.", options:[{text:"Müşteriye açıkça özür diler, doğru bilgiyi veririm ve chatbotun neden hata yaptığını analiz edip sistemi düzeltirim.",score:100,feedbackText:"Şeffaf sorumluluk + sistem iyileştirme. En profesyonel yaklaşım."},{text:"Chatbot verdi diyerim, benim hatam değil.",score:-100,feedbackText:"Müşteri için tek muhatap siz ya da şirketinizsiniz. Sorumluluğu almak güveni korur."},{text:"Müşteriye özel bir indirim ya da tazminat teklif ederim ama hatayı kapatırım.",score:0,feedbackText:"Tazminat iyi ama kaynağı kapatmadan aynı hata tekrar olur."}] },
  { cat:"ai-customer-service", d:3, s:"Kişiselleştirilmiş müşteri deneyimi için yapay zeka müşteri geçmişini analiz ediyor ama bazı müşteriler nasıl bildiniz diye soru soruyor.", t:"Kişiselleştirme değerlidir ama şeffaflık güven inşa eder.", options:[{text:"Müşterilere veri kullanımını açıkça bildiririm ve isteyen için kişiselleştirmeyi kapatma seçeneği sunarım.",score:100,feedbackText:"Şeffaflık + kontrol = güven. En sürdürülebilir yaklaşım."},{text:"Bilmeseler daha iyi, kişiselleştirme onlara iyi geliyor.",score:-100,feedbackText:"Gizli veri kullanımı güven krizine yol açabilir. Şeffaflık tercih değil, zorunluluk."},{text:"Kişiselleştirmeyi tamamen kapatırım, risk almam.",score:0,feedbackText:"Kişiselleştirme müşteri memnuniyeti için güçlü araç. Riski yönetmek daha akıllıca."}] },
  { cat:"ai-customer-service", d:1, s:"Müşteri hizmetlerinizde sıkça tekrar eden sorular için FAQ sayfası güncellemek istiyorsunuz. Yapay zeka bu içerikleri sizin için oluşturabilir.", t:"Yapay zeka içerik üretir, siz doğruluğu ve tonu onaylarsınız.", options:[{text:"Yapay zekadan taslaklar alır, kendi ürün bilgilerimle kontrol eder ve markanın sesine uyarlarım.",score:100,feedbackText:"Verimli ve kaliteli. Taslak + doğrulama mükemmel kombinasyon."},{text:"FAQ içeriklerini müşteri hizmetleri ekibi yazsın, bilgi onlarda.",score:0,feedbackText:"Ekip bilgisi değerli ama yapay zeka taslak oluşturarak ekibin zamanını optimize edebilir."},{text:"Yapay zekanın yazdığını doğrudan yayınlarım, hızlı çözüm.",score:-100,feedbackText:"Yanlış bilgi içeren FAQ ciddi müşteri sorunlarına yol açar. Kontrol şart."}] },
  { cat:"ai-customer-service", d:2, s:"Müşteri memnuniyet skorlarınız düşüyor. Yapay zeka analizi yanıt süresi ve empati sorunlarını gösteriyor.", t:"Veri problemi gösterir, çözüm insan kararı gerektirir.", options:[{text:"Her iki soruna ayrı stratejiler geliştiririm: yanıt süresi için otomasyon, empati için eğitim ve daha iyi devir süreçleri.",score:100,feedbackText:"Somut ve hedefe yönelik. Doğru analiz kullanımı."},{text:"Müşteriler çok talepkâr, her skoru iyileştirmek mümkün değil.",score:-100,feedbackText:"Bu tutum sizi sorunun bir parçası yapar. Müşteri beklentisi gerçektir."},{text:"Yanıt süresini otomatize ederim, empati konusu zaten iyi oluyor.",score:0,feedbackText:"Veri iki sorunu da işaret ediyor. Birini görmezden gelmek memnuniyeti tam düzeltmez."}] },
  { cat:"ai-customer-service", d:3, s:"Yapay zeka destekli müşteri hizmetleri kurarsanız insan temsilcilerin işini kaybedeceğini düşünen bir yöneticiniz var.", t:"Otomasyon rutin işleri alır, insanlar karmaşık ve ilişki odaklı işlere odaklanır.", options:[{text:"Veri ve örneklerle hibrit modelin nasıl çalıştığını gösterir, temsilcilerin hangi vakalarda daha değerli olduğunu vurgularım.",score:100,feedbackText:"Kanıta dayalı ikna. Profesyonel yaklaşım."},{text:"Yönetici kaygısı haklı, yapay zeka uygulamasını erteliyorum.",score:-100,feedbackText:"Kaygıyı çözmek yerine ertelemek rekabette geri bırakır."},{text:"Yapay zekayı sessizce kademeli olarak devreye alırım, fark etmeyecekler.",score:0,feedbackText:"Şeffaf olmayan dönüşüm güven sorunları yaratır. Açık iletişim daha sağlıklı."}] },
  { cat:"ai-customer-service", d:1, s:"Bir müşteri yapay zeka ile mi yoksa insan ile mi konuştuğunu sormak istedi. Politikanız bunu açıklamamak.", t:"Şeffaflık müşteri ilişkisinin temelidir. Gizlilik güven krizine yol açabilir.", options:[{text:"Müşteriye dürüstçe yapay zeka ile konuştuğunu söylerim ve isterse insan temsilciye aktarabileceğimi belirtirim.",score:100,feedbackText:"Dürüstlük + seçenek sunmak güveni artırır."},{text:"Politika bu, cevap vermem.",score:-100,feedbackText:"Cevapsızlık şüphe uyandırır ve müşteriyi kaybetme riski taşır."},{text:"İnsan gibi davranmaya devam ederim, müşteriler sormamalı.",score:-100,feedbackText:"Yapay zekayı insan gibi göstermek etik sınırı aşar ve güven krizi yaratır."}] },
  { cat:"ai-customer-service", d:2, s:"Yapay zeka destekli müşteri hizmetleriniz çok iyi çalışıyor ama bazı yaşlı müşteriler teknolojiyle zorluk yaşıyor.", t:"Erişilebilirlik hizmet kalitesinin parçasıdır — tüm müşteri segmentleri önemlidir.", options:[{text:"Yaşlı müşteriler için alternatif iletişim kanalları açık tutarım ve chatbotu daha basit yanıtlar verecek şekilde optimize ederim.",score:100,feedbackText:"Kapsayıcı hizmet tasarımı. Mükemmel yaklaşım."},{text:"Teknolojiyi öğrenmeleri gerekiyor, bu müşteri segmenti küçük.",score:-100,feedbackText:"Küçük segment bile sadakatle değerli olabilir. Dışlamak marka hasarı yaratır."},{text:"Yaşlı müşteriler için özel bir hat oluştururum ama maliyetli.",score:0,feedbackText:"Maliyet göz önünde bulundurulmalı ama seçenekler çeşitlendirilebilir."}] },
]

console.log('Total:', ALL.length, 'questions')
for (let i = 0; i < ALL.length; i += 20) {
  const batch = ALL.slice(i, i + 20)
  await insert(batch)
}
