const TOKEN = 'sbp_f314cf27b5b2a01eea48048a7b1c015cc9cf4b42'
const API = 'https://api.supabase.com/v1/projects/amhfxaqolholacanqyas/database/query'

function esc(s) { return s.replace(/'/g, "''") }

async function insert(batch) {
  const values = batch.map(q => {
    const opts = JSON.stringify(q.options).replace(/'/g, "''")
    return `('tr','${q.cat}','${esc(q.s)}','${esc(q.t)}','${opts}'::jsonb,${q.d},'claude',true)`
  }).join(',')
  const sql = `INSERT INTO questions (locale,category,scenario_text,mindset_tip,options,difficulty,generated_by,is_active) VALUES ${values};`
  const r = await fetch(API, {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${TOKEN}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query: sql })
  })
  const d = await r.json()
  if (d.message) { console.error('ERR:', d.message); return false }
  console.log('OK:', batch.length, 'inserted')
  return true
}

const ALL = [
  // change-collaboration (10)
  { cat:"change-collaboration", d:1, s:"Ekibiniz yapay zeka dönüşümüne direniyor. Siz değişimin öncüsü olmak istiyorsunuz.", t:"Değişim öncüsü zorlamayla değil, somut örnekle olur.", options:[{text:"Küçük bir yapay zeka uygulamasında başarı elde eder ve bunu ekiple paylaşırım.",score:100,feedbackText:"Gösteri ikna eder. Doğru yaklaşım."},{text:"Yönetimden direktif çıkarırım, ekip uyum sağlar.",score:-100,feedbackText:"Direktif uyumu zorunlu kılar ama benimsemeyi sağlamaz."},{text:"Ekip hazır olana kadar beklerim.",score:0,feedbackText:"Bekleme fırsat kaybı. Küçük öncü adım süreci başlatır."}] },
  { cat:"change-collaboration", d:2, s:"Yapay zeka projesinde farklı departmanlar farklı beklentilere sahip. Uyum sağlamak zor görünüyor.", t:"Farklı beklentiler diyalogla yönetilir, kararla değil.", options:[{text:"Tüm paydaşların beklentilerini listeler, ortak zemin ve öncelikleri birlikte belirleriz.",score:100,feedbackText:"Paydaş yönetimi başarının temelidir."},{text:"En kıdemli departmanın beklentisini esas alırım.",score:0,feedbackText:"Kıdem değil, proje etkisi esas alınmalı."},{text:"Her departmana farklı çözüm sunarım.",score:-100,feedbackText:"Parçalı çözüm entegrasyon sorunları yaratır."}] },
  { cat:"change-collaboration", d:1, s:"Yapay zeka destekli bir işbirliği aracı ekibinize sunuldu. Kullanım oranı düşük.", t:"Araç benimsemesi otomatik değil, kolaylaştırma gerektirir.", options:[{text:"Ekibin neden kullanmadığını sorar, engelleri gideririm ve gerçek bir kullanım senaryosu için rehberlik ederim.",score:100,feedbackText:"Neden sorgusu engeli ortaya çıkarır. Doğru başlangıç."},{text:"Kullanıma zorunlu kılarım, metriklerle takip ederim.",score:0,feedbackText:"Zorunlu kullanım yüzeysel benimseme yaratır. Gerçek değeri göstermek daha etkili."},{text:"Aracı kaldırır, ekip beğenmedi.",score:-100,feedbackText:"Düşük kullanım ile değersiz araç aynı şey değil. Nedenini anlamak şart."}] },
  { cat:"change-collaboration", d:2, s:"Yapay zeka dönüşüm projesinde bazı çalışanlar merak ederken bazıları endişeli. İki grubu nasıl yönetirsiniz?", t:"Her grubun motivasyonu farklıdır — tek mesaj ikisine birden işe yaramaz.", options:[{text:"Meraklı grubu erken uygulayıcı olarak kullanır, endişeli gruba güvenli öğrenme ortamı oluştururum.",score:100,feedbackText:"Segmentasyon değişim yönetiminde güçlü strateji."},{text:"Endişeli gruba odaklanır, meraklılar zaten ilerler.",score:0,feedbackText:"Meraklı grubu erken kazanç üretici olarak kullanmak iyi fırsat."},{text:"Herkese aynı mesajı veririm, tutarlılık şart.",score:-100,feedbackText:"Tutarlılık iyi ama farklı kaygılar farklı yanıtlar gerektirir."}] },
  { cat:"change-collaboration", d:3, s:"Yapay zeka dönüşümü sırasında bazı çalışanlar yapay zekanın kendi rollerini tehdit ettiğini düşünüyor.", t:"Tehdit algısı gerçektir ve görmezden gelinmemelidir.", options:[{text:"Çalışanlarla açık sohbet eder, rolün nasıl evrildiğini somut olarak gösteririm.",score:100,feedbackText:"Şeffaflık ve somutluk kaygıyı azaltır."},{text:"Bu kaygılar abartılıyor, gerçek değil.",score:-100,feedbackText:"Kaygıyı küçümsemek güven kaybıdır. Ciddiye almak şart."},{text:"Sigorta önlemleri alırım ama konuşmam.",score:0,feedbackText:"Sessiz önlem kaygıyı çözmez. Diyalog şart."}] },
  { cat:"change-collaboration", d:2, s:"Yapay zeka ekip üretkenliğini ölçüyor ama ölçüm çalışanları tedirgin ediyor.", t:"Ölçüm neyin ölçüldüğüne ve nasıl kullanıldığına göre anlam kazanır.", options:[{text:"Ölçüm amacını ve verinin nasıl kullanılacağını ekiple şeffaf biçimde paylaşırım.",score:100,feedbackText:"Şeffaflık güvensizliği azaltır."},{text:"Ölçüm şart, tedirginlik olağan.",score:0,feedbackText:"Olağan olabilir ama yönetmek mümkün. Şeffaflık fark yaratır."},{text:"Ölçümü kaldırırım, tedirginlik verimliliği etkiliyor.",score:-100,feedbackText:"Sorun ölçüm değil iletişim eksikliği."}] },
  { cat:"change-collaboration", d:1, s:"Yapay zeka dönüşüm projesinde bütçe kısıtlaması nedeniyle eğitim planı kısaltıldı. Ekip hazır değil.", t:"Yetersiz eğitim dönüşüm başarısını tehdit eder.", options:[{text:"Kritik eğitimleri öncelikle belirler, bütçe içinde en yüksek etkiyi sağlayan içeriklere odaklanırım.",score:100,feedbackText:"Öncelikli minimum eğitim sıfır eğitimliden çok daha iyi."},{text:"Ekip çalışırken öğrenir, eğitim gereksiz.",score:-100,feedbackText:"Yaparak öğrenme değerli ama temel hazırlıksız başarı düşürür."},{text:"Projeyi geciktiririm, eğitim tamamlanana kadar başlamam.",score:0,feedbackText:"Geciktirmek bir seçenek ama pilot grupla başlamak daha pratik."}] },
  { cat:"change-collaboration", d:2, s:"Yapay zeka dönüşümünde yönetim tarafından belirlenen hız ekip kapasitesini aşıyor.", t:"Sürdürülemez hız uzun vadede tükenmişlik ve kalite kaybı yaratır.", options:[{text:"Veri ile kapasiteyi gösterir, hızı düşürme veya kaynak artırma seçeneklerini yönetimle görüşürüm.",score:100,feedbackText:"Veriye dayalı itiraz sorumluluk göstergesi."},{text:"Yapabileceğimiz kadar hızlı gideriz, sonuçlara bakarım.",score:0,feedbackText:"Kısa vadede çalışır ama sürdürülebilir değil."},{text:"Yönetimin dediği hızda giderim, eleştirmem.",score:-100,feedbackText:"Sessiz uyum problemi görünmez kılar. Geri bildirim liderlik sorumluluğu."}] },
  { cat:"change-collaboration", d:1, s:"Yapay zeka projesinde kararlar üst yönetim tarafından alınıyor ama uygulama ekip tarafından yapılıyor. Arada kopukluk var.", t:"Strateji ile uygulama arasındaki köprü iletişimdir.", options:[{text:"Yönetim-ekip arasında düzenli geri bildirim döngüsü kurar, uygulama gerçeklerini yukarı taşırım.",score:100,feedbackText:"Köprü olmadan strateji uygulama olmaz."},{text:"Yönetim karar verir, ekip uygular — bu hiyerarşi.",score:-100,feedbackText:"Hiyerarşi doğru ama kopukluk başarıyı engeller. İletişim şart."},{text:"Ekip kendi kararını verir, yönetim sonuçlara bakar.",score:0,feedbackText:"Özerklik iyi ama yönlendirme eksikliği kaynakları yanlış harcar."}] },
  { cat:"change-collaboration", d:3, s:"Yapay zeka dönüşüm projesinde başarı kriterleri belirsiz. Kim ne başardığını bilmiyor.", t:"Belirsiz başarı kriterleri motivasyonu ve hesap verebilirliği zayıflatır.", options:[{text:"Proje başında ölçülebilir başarı kriterleri tanımlar ve tüm paydaşlara bildiririm.",score:100,feedbackText:"Net kriter net yön verir. Başlangıçta şart."},{text:"Başarı projeyi tamamlamak, başka kriter gerekmez.",score:-100,feedbackText:"Tamamlamak değil, değer üretmek başarıdır. Kriter şart."},{text:"Proje tamamlanınca değerlendiririz.",score:0,feedbackText:"Sonradan değerlendirme geç dönüt sağlar. Önceden tanımlamak daha etkili."}] },

  // creativity-ideation (10)
  { cat:"creativity-ideation", d:1, s:"Yapay zekadan fikir üretmesini istediydiniz ama fikirler çok genel ve sıradandı.", t:"Yapay zekanın çıktısı sorunuzun kalitesiyle doğru orantılı.", options:[{text:"Daha spesifik bağlam, kısıt ve hedef belirterek soruyu yeniden sorarım.",score:100,feedbackText:"İyi prompt daha iyi fikir üretir. Girdinin kalitesi çıktıyı belirler."},{text:"Yapay zeka yaratıcı değil, kendim düşüneceğim.",score:0,feedbackText:"Yaratıcılık işbirliğiyle güçlenir. Promtu iyileştirmek sonucu değiştirir."},{text:"Sunulan fikirleri olduğu gibi kullanırım, yeterli.",score:-100,feedbackText:"Genel fikirler rakiplerin de düşündüğü fikirler. Spesifikleştirme fark yaratır."}] },
  { cat:"creativity-ideation", d:2, s:"Ekibinizle beyin fırtınası yapıyorsunuz ama yapay zeka toplantıda sürekli konuşmayı kesiyor. Yaratıcı akış bölünüyor.", t:"Araç, süreci desteklemeli; bölmemeli.", options:[{text:"Yapay zekayı beyin fırtınası sırasında değil, fikirleri işleme ve geliştirme aşamasında kullanırım.",score:100,feedbackText:"Doğru araç, doğru zamanda. Süreç tasarımı yaratıcılığı etkiler."},{text:"Yapay zekayı toplantıdan çıkarırım, insanlar daha iyi düşünüyor.",score:0,feedbackText:"Zamanlamayı değiştirmek tamamen çıkarmaktan daha değerli."},{text:"Yapay zekanın önerilerine öncelik veririm, zaten iyi fikirler üretiyor.",score:-100,feedbackText:"Ekip dinamiğini görmezden gelmek uzun vadede bağlılığı düşürür."}] },
  { cat:"creativity-ideation", d:1, s:"Yapay zeka ürün geliştirme için 50 fikir üretti. Hangisinden başlayacağınızı bilmiyorsunuz.", t:"Çok seçenek karar felci yaratır. Filtre kriterleri şart.", options:[{text:"Fikirleri etki ve uygulanabilirlik matrisiyle değerlendirer, en yüksek puanlı üçünü derinleştiririm.",score:100,feedbackText:"Matris değerlendirme karar felcini aşar."},{text:"Hepsini denerim, en çok ilgi çeken devam eder.",score:0,feedbackText:"Tüm fikirleri denemek kaynakları dağıtır. Önceliklendirme daha verimli."},{text:"Yapay zekanın en çok önerdiği fikri seçerim.",score:-100,feedbackText:"Yapay zekanın önerme sıklığı fikrin iyiliğini göstermez. Kendi kriterleri gerekli."}] },
  { cat:"creativity-ideation", d:2, s:"Yapay zeka mevcut ürününüzle örtüşen bir fikir önerdi. Bunu orijinal bir fikir olarak sunmak istiyorsunuz.", t:"Yapay zeka destekli fikirler özgün olabilir ama şeffaflık önemli.", options:[{text:"Yapay zekanın önerisini kendi yaratıcı sürecimle geliştirerek gerçekten özgün bir ürüne dönüştürürüm.",score:100,feedbackText:"Birleşimsel yaratıcılık gerçek. Geliştirme fark yaratır."},{text:"Yapay zeka verdi diyerek sunarsam fikrim güçsüz görünür.",score:0,feedbackText:"Kaynağı saklamak yerine katkınızı net kılmak daha güçlü."},{text:"Herkes yapay zeka kullanıyor, özgünlük kalmaması normal.",score:-100,feedbackText:"Özgünlük hâlâ mümkün ve değerli. Kolaya kaçmak fark yaratmaz."}] },
  { cat:"creativity-ideation", d:3, s:"Yapay zeka ile üretilen içerik daha fazla tıklama alıyor ama takipçiler özgün sesini özlüyor.", t:"Metrik artışı marka derinliğinin erimesini gizleyebilir.", options:[{text:"Tıklama odaklı içerikle marka sesi içeriğini dengeli dağıtır, uzun vadeli bağlılığı ölçerim.",score:100,feedbackText:"Kısa ve uzun vade birlikte değerlendirilmeli."},{text:"Tıklama iyi metrik, devam ederim.",score:-100,feedbackText:"Tıklama ilgi, bağlılık değer. İkisi aynı şey değil."},{text:"Takipçilerin beğenmediği içerik üretmem.",score:0,feedbackText:"Mükemmel ikisinin dengesi. Tamamen birini seçmek yerine harmanlayın."}] },
  { cat:"creativity-ideation", d:2, s:"Yapay zeka ile birlikte yaratıcı bir senaryo yazıyorsunuz. Çıktılar iyi ama hepsi benzer kalıba sahip.", t:"Yapay zeka eğitim verisinin kalıplarını yansıtır. Kırmak için insan müdahalesi gerekir.", options:[{text:"Alışılmadık kısıtlar ve beklenmedik kombinasyonlar isteyerek kalıpları kırmaya çalışırım.",score:100,feedbackText:"Kasıtlı bozma yeni yollar açar."},{text:"Çıktılar benzer ama kaliteli, devam ederim.",score:0,feedbackText:"Kalite iyi ama özgünlük de değerli. İkisini birlikte hedeflemek mümkün."},{text:"Yapay zeka gerçekten yaratıcı değil, kendi yazarım.",score:-100,feedbackText:"Yaratıcılık araçla değil, nasıl kullandığınızla belirlenir. Promtu değiştirin."}] },
  { cat:"creativity-ideation", d:1, s:"Yapay zeka size ilham verici bir fikir üretmek için büyük miktarda örnek vermesini istedi. Bunlar çok zaman alıyor.", t:"Giriş zenginliği çıkış kalitesini artırır ama zaman maliyeti dengelenmeli.", options:[{text:"Örnekleri seçici toplar, en temsili birkaçını vererek daha verimli prompt yaratırım.",score:100,feedbackText:"Az ama seçici girdi zaman ve kalite dengeler."},{text:"Tüm örnekleri veririm, daha iyi sonuç alırım.",score:0,feedbackText:"Fazla örnek zaman alır ama her zaman daha iyi sonuç vermez. Seçicilik daha verimli."},{text:"Örneksiz ilerlerim, yapay zeka zaten bilgi sahibi.",score:0,feedbackText:"Bağlam vermek genellikle çıktıyı iyileştirir. Sıfır bağlam kaçırılan fırsat."}] },
  { cat:"creativity-ideation", d:2, s:"Yapay zeka ürün ismi için öneriler sundu. Hepsi mantıklı ama hiçbiri ilham verici değil.", t:"Mantıksal isimler akılda kalmaz. Yaratıcılık bazen mantığın dışından gelir.", options:[{text:"Yapay zekadan mantıksız, deneysel, şiirsel veya beklenmedik isimler üretmesini özellikle isterim.",score:100,feedbackText:"Kasıtlı alışılmadık talep alışılmadık sonuç getirir."},{text:"İlk listeyi seçim için ekiple paylaşırım, biri beğenir.",score:0,feedbackText:"Ekip seçimi değerli ama ilham arayışını terk etmek erken."},{text:"Yapay zeka yeterince iyi isim veremiyor, ajans tutarım.",score:-100,feedbackText:"Önce promtu değiştirip denemek daha ucuz ve hızlı."}] },
  { cat:"creativity-ideation", d:3, s:"Yapay zeka destekli tasarım sürecinde ekip yapay zekanın önerdiği görselleri tartışmadan kabul ediyor.", t:"Araç otomatizmi eleştirel düşünceyi köreltiyor olabilir.", options:[{text:"Her öneri için ekiple neden seçiyoruz, ne ifade ediyor, alternatifleri ne sorularını sorarım.",score:100,feedbackText:"Aktif sorgulama araç bağımlılığını önler."},{text:"Yapay zeka iyi seçimler yapıyor, tartışma zaman kaybı.",score:-100,feedbackText:"Tartışmasız kabul ekibin tasarım gücünü zayıflatır."},{text:"Zaman kısıtlı, hızlı kararlar şart.",score:0,feedbackText:"Hız değerli ama birkaç dakikalık sorgulama uzun vadede tasarım kalitesini korur."}] },
  { cat:"creativity-ideation", d:1, s:"Yapay zekaya yeni bir kampanya fikri geliştirmesini istediniz. Fikir güçlü ama tamamen yapay zeka ürünü. Katkınız ne olacak?", t:"İnsan katkısı fikri ürün haline getirir. Seçim, düzenleme ve uygulama yaratıcılıktır.", options:[{text:"Fikri kendi deneyimim ve hedef kitlem için dönüştürür, uygulama kararlarını kendim veririm.",score:100,feedbackText:"Dönüştürme ve uygulama insan katkısının özü."},{text:"Fikir hazır, hemen uygularım.",score:0,feedbackText:"Hızlı başlangıç iyi ama özelleştirmeden yüzeysel kalır."},{text:"Kendi fikrimi bulana kadar beklerim.",score:-100,feedbackText:"Beklemek fırsat kaybı. İyiyi daha iyi yapmak da yaratıcılık."}] },

  // critical-thinking (10)
  { cat:"critical-thinking", d:1, s:"Yapay zeka güvenle yanlış bir bilgi verdi. Siz bunu fark etmediniz ve aktardınız.", t:"Yapay zeka yanılmazlığı yoktur. Doğrulama alışkanlığı kritik.", options:[{text:"Önemli bilgileri her zaman birincil kaynakla doğrularım ve yapay zekanın güven tonuna aldanmam.",score:100,feedbackText:"Güvenden bağımsız doğrulama temel beceri."},{text:"Bu sefer oldu, bir daha dikkatli olurum.",score:0,feedbackText:"Dikkat sistematik doğrulama alışkanlığıyla korunur. Bireysel tetikte olmak yetmez."},{text:"Yapay zeka genellikle doğru, bu istisnai bir durum.",score:-100,feedbackText:"İstisna değil kalıp. Hallüsinasyon gerçek ve tekrarlayan bir sorun."}] },
  { cat:"critical-thinking", d:2, s:"Yapay zeka analizi kendi varsayımlarınızla örtüşüyor. Bunu güvenilirlik kanıtı olarak alıyorsunuz.", t:"Örtüşme doğrulama değildir. Onay önyargısı kritik düşünceyi köreltiyor.", options:[{text:"Kendi görüşümle örtüşen analizleri özellikle eleştirel incelerim ve çelişen bakış açılarını ararım.",score:100,feedbackText:"Onay önyargısına karşı kasıtlı çelişki arayışı güçlü eleştirel düşünce."},{text:"Yapay zeka da aynı sonuca vardıysa doğru olmalı.",score:-100,feedbackText:"İkisi de aynı kalıptan besleniyorsa ikisi de aynı hatayı yapabilir."},{text:"Örtüşme güven verici ama ikinci kaynakla da kontrol ederim.",score:0,feedbackText:"İkinci kaynak iyi ama onay önyargısı farkındalığı da önemli."}] },
  { cat:"critical-thinking", d:1, s:"Yapay zeka size bir argüman sundu. Güçlü görünüyor ama hiç karşı argüman üretmedi.", t:"Tek taraflı argüman ne kadar güçlü görünse de eleştirel değerlendirme eksik.", options:[{text:"Yapay zekadan aynı konuya karşı argümanlar üretmesini isterim ve her iki tarafı değerlendiririm.",score:100,feedbackText:"Karşıt argüman isteme eleştirel çerçevenin önemli aracı."},{text:"Argüman güçlü göründüyse doğrudur.",score:-100,feedbackText:"Güçlü görünüm doğruluğun kanıtı değil. Her argümanın zayıf yanı vardır."},{text:"İkinci kaynaktan benzer argüman bulursam güçlendiririm.",score:0,feedbackText:"İkinci kaynak iyi ama karşıt argüman aramak daha kapsamlı değerlendirme sağlar."}] },
  { cat:"critical-thinking", d:2, s:"Yapay zekayla bir konuyu araştırıyorsunuz. Her soruda önceki yanıtları doğrulayan cevaplar alıyorsunuz.", t:"Yapay zeka önceki bağlamdan etkilenir. Bağlamı temizleyerek sıfırdan sormak farklı bakış açısı sunar.", options:[{text:"Yeni bir sohbet başlatır, konuya farklı açılardan bağımsız sorular sorarım.",score:100,feedbackText:"Bağlam bağımsız sorgulama daha dengeli sonuç verir."},{text:"Yanıtlar tutarlı çıkıyorsa doğru demektir.",score:-100,feedbackText:"Tutarlılık gerçeklik değil. Bağlam döngüsü tutarlı yanıtlar üretir."},{text:"Birden fazla yapay zeka aracında aynı soruyu sorarım.",score:0,feedbackText:"Çoklu araç iyi ama her birindeki bağlam etkisini de göz önüne almak şart."}] },
  { cat:"critical-thinking", d:3, s:"Yapay zeka destekli araştırma raporunuz çok etkileyici görünüyor. Yönetim hemen uygulamak istiyor.", t:"Etkileyici görünüm metodoloji kalitesiyle aynı şey değildir.", options:[{text:"Raporun kaynaklarını, metodolojisini ve varsayımlarını doğrulamadan uygulamaya geçilmesini öneririm.",score:100,feedbackText:"Kritik değerlendirme uygulamadan önce şart."},{text:"Yönetim beğendi, hemen başlarız.",score:-100,feedbackText:"Yönetim onayı doğrulama değildir. Metodoloji sorgulanmalı."},{text:"Birkaç uzmanın görüşünü alıp sonra başlarım.",score:0,feedbackText:"Uzman görüşü değerli ama metodoloji sorgulaması daha sistematik."}] },
  { cat:"critical-thinking", d:2, s:"Yapay zeka bir kararı destekleyen verilerle sunuluyor. Ama bu verinin nasıl seçildiği belirsiz.", t:"Veri seçimi sonucu şekillendirir. Metodoloji sorusu kritik.", options:[{text:"Hangi verilerin dahil edilip çıkarıldığını ve seçim kriterlerini sorarım.",score:100,feedbackText:"Veri seçimi sorusu eleştirel veri okuryazarlığının özü."},{text:"Veri destekliyor, güvenilirdir.",score:-100,feedbackText:"Seçici veri güçlü görünen ama yanıltıcı argüman üretebilir."},{text:"İlave veri toplayarak analizi genişletirim.",score:0,feedbackText:"Genişletme iyi ama önce mevcut seçimin mantığını anlamak şart."}] },
  { cat:"critical-thinking", d:1, s:"Yapay zeka çok kesin bir dil kullanarak sonuç bildirdi. Belirsizliği yansıtmıyor.", t:"Kesin dil güveni artırabilir ama gerçek belirsizliği maskeleyebilir.", options:[{text:"Sonucun güven aralığını ve belirsizliğini açıklamasını isterim.",score:100,feedbackText:"Belirsizliği açıklatmak daha gerçekçi değerlendirme sağlar."},{text:"Kesin konuşuyorsa emin olduğu için öyledir.",score:-100,feedbackText:"Kesinlik dili güvenden değil, eğitim verisinden gelir. Belirsizliği sorgulamak şart."},{text:"İkinci araçta da aynı soruyu sorar karşılaştırırım.",score:0,feedbackText:"İyi ama her araç aynı güveni yansıtabilir. Belirsizliği sormak daha doğrudan."}] },
  { cat:"critical-thinking", d:2, s:"Yapay zeka büyük bir kararı destekler nitelikte analiz sundu. Siz zaten bu kararı vermek istiyordunuz.", t:"Kararı doğrulayan analiz eleştirel değerlendirmeyi köreltiyor olabilir.", options:[{text:"Kararıma karşı en güçlü argümanları özellikle araştırır ve analizde eksik bırakılan noktaları ararım.",score:100,feedbackText:"Karşıt argüman aramak en kuvvetli eleştirel düşünce pratiği."},{text:"Analiz kararımı destekledi, haklıyım.",score:-100,feedbackText:"Onay sadece onay. Eleştirel değerlendirme bağımsız olmalı."},{text:"Kararı meslektaşlarımla tartışırım.",score:0,feedbackText:"Tartışma iyi ama siz de onay önyargısıyla girerseniz etki azalır."}] },
  { cat:"critical-thinking", d:3, s:"Yapay zeka trend analizi yapıyor ve belirli bir sektörün beş yıl içinde yüzde elli büyüyeceğini söylüyor.", t:"Gelecek tahminleri belirsizlikle dolu. Kesin rakamlar güven verici görünür ama yanıltıcı olabilir.", options:[{text:"Tahmin metodolojisini, varsayımları ve hangi koşullarda geçerli olduğunu araştırırım.",score:100,feedbackText:"Tahmin değerlendirmesi bağlam ve metodoloji sorusuyla başlar."},{text:"Yapay zeka büyük veri analiz etti, tahmine güvenirim.",score:-100,feedbackText:"Büyük veri hatalı model + hatalı tahmin üretebilir. Metodoloji şart."},{text:"Beş yıllık tahmin belirsiz, dikkate almam.",score:0,feedbackText:"Belirsizlik görmezden gelmek için değil, değerlendirmek için bir başlangıç."}] },
  { cat:"critical-thinking", d:1, s:"Yapay zekaya sordunuz ve yanıt mantıklı geldi. Ama konu sizin için yeni.", t:"Mantıklı görünüm kendi uzmanlığınızın yerini tutmaz. Yeni konularda özellikle dikkatli olmak şart.", options:[{text:"Yanıtı alanlı bir uzmana doğrulattırır ya da güvenilir birincil kaynaklarla karşılaştırırım.",score:100,feedbackText:"Yeni konularda doğrulama daha kritik. Doğru tutum."},{text:"Mantıklıysa yeterli, alan bilgisi her zaman şart değil.",score:-100,feedbackText:"Mantıklı görünüm doğruluğun kanıtı değil. Yeni konularda özellikle risk."}  ,{text:"İkinci bir yapay zekaya sorar karşılaştırırım.",score:0,feedbackText:"İkinci araç faydalı ama her ikisi de aynı hatayı yapabilir. Uzman daha güvenilir."}] },

  // efficiency-analysis (10)
  { cat:"efficiency-analysis", d:1, s:"Yapay zeka iş akışınızda en çok zaman alan adımları tespit etti. Ama sadece süreye bakarak önemi göz ardı etti.", t:"Süre tek verimlilik ölçütü değildir. Etkiyi de değerlendirmek şart.", options:[{text:"Her adımın hem süresini hem iş çıktısına katkısını ölçer, süre değil etki odaklı önceliklendirme yaparım.",score:100,feedbackText:"Etki-süre matrisi doğru önceliklendirme sağlar."},{text:"Uzun adımları kısaltan her çözüm verimliliği artırır.",score:0,feedbackText:"Doğru olabilir ama önemli adımları yanlışlıkla kısaltmak kaliteyi düşürür."},{text:"Analizi görmezden gelirim, iş akışım iyi.",score:-100,feedbackText:"Veriyi reddetmek fırsat kaçırma. En azından değerlendirin."}] },
  { cat:"efficiency-analysis", d:2, s:"Yapay zeka e-posta yönetim sürenizi ölçtü ve günde iki saat harcadığınızı gösterdi. Bu sizi şaşırttı.", t:"Veri farkındalık yaratır. Farkındalık eylem başlatır.", options:[{text:"Bu sürenin kaçının değerli, kaçının gereksiz olduğunu analiz eder, yalnızca gereksiz kısımları azaltırım.",score:100,feedbackText:"Toplu azaltma değil, seçici azaltma. Doğru yaklaşım."},{text:"İki saat çok değil, e-posta iş gerektiriyor.",score:0,feedbackText:"Doğru olabilir ama ne kadarının değerli olduğunu analiz etmeden bilemezsiniz."},{text:"E-postayı kapatırım, zaman tasarrufu sağlarım.",score:-100,feedbackText:"Aşırı önlem kritik iletişimi kesebilir. Seçici yaklaşım daha dengeli."}] },
  { cat:"efficiency-analysis", d:1, s:"Yapay zeka raporları otomatik oluşturuyor. Ama raporları hazırlama sürecindeki anlama ve öğrenme değeri kayboluyor.", t:"Otomasyon hız sağlar ama bazı süreçler öğrenme değeri taşır.", options:[{text:"Kritik raporları kendi anlayışımla hazırlar, rutin tekrarlayan raporları otomatize ederim.",score:100,feedbackText:"Öğrenme değeri olan süreçleri korumak uzun vadeli yatırım."},{text:"Tüm raporları otomatize ederim, zaman daha iyi kullanılabilir.",score:0,feedbackText:"Zaman doğru ama bazı raporlar veriyi anlamak için iyi pratik. Seçici olun."},{text:"Raporları kendin hazırlamak en iyi yol.",score:0,feedbackText:"Deneyim değerli ama verimlilik de önemli. Hangisinin öğrenme değeri yüksek, bunu belirleyin."}] },
  { cat:"efficiency-analysis", d:2, s:"Yapay zeka toplantı sürelerinizi analiz etti ve ortalama toplantıların üçte birinin gereksiz olduğunu gösterdi.", t:"Toplantı verimliliği organizasyonel değişim gerektirir.", options:[{text:"Gereksiz olarak işaretlenen toplantıların amacını ve katılımcıları değerlendirerek iptal veya kısaltma kararı alırım.",score:100,feedbackText:"Veri + değerlendirme + karar. Etkili verimlilik yönetimi."},{text:"Herkes toplantıyı seviyor, azaltmak moral bozar.",score:-100,feedbackText:"Moral önemli ama gereksiz toplantılar da motivasyonu zedeler. Denge şart."},{text:"Analizi paylaşırım, herkes kendi kararını versin.",score:0,feedbackText:"Bireysel karar dağınık olabilir. Organizasyonel kural daha etkili."}] },
  { cat:"efficiency-analysis", d:3, s:"Yapay zeka çalışan verimliliğini ölçüyor ama yaratıcı ve düşünme gerektiren işler düşük puanlıyor.", t:"Çıktı sayısı yaratıcı değerin ölçütü değildir.", options:[{text:"Ölçüm sistemine yaratıcı ve stratejik iş için kalite ve etki ölçütleri eklerim.",score:100,feedbackText:"Ölçüm tasarımı değerlendirmenin kalitesini belirler."},{text:"Düşük puan alanlar verimsiz, performans planı yaparım.",score:-100,feedbackText:"Yanlış ölçüm yanlış karar üretir. Önce ölçümü düzeltin."},{text:"Yaratıcı iş ölçülemez, analizi görmezden gelirim.",score:0,feedbackText:"Tam ölçümlenemez ama kısmen ölçmek hiç ölçmemekten iyidir."}] },
  { cat:"efficiency-analysis", d:2, s:"Yapay zeka en verimli çalışma saatlerinizin sabah erken olduğunu söylüyor. Ama sizin sosyal ve aile sorumluluklarınız bu saatleri doluyor.", t:"Veri rehberdir, kural değil. Yaşam dengesi de bir değişken.", options:[{text:"Sabahları verimli olduğumu bilerek, aile sorumluluklarımla çakışmayan en az bir blok sabah zamanı oluştururum.",score:100,feedbackText:"Veriyi yaşam koşullarıyla uyumlandırmak akıllı esneklik."},{text:"Sabahları aileme ayırırım, verimlilik önemli değil.",score:0,feedbackText:"Öncelikler sizin — ama veriyi tamamen görmezden gelmek de kayıp."},{text:"Verimli saatlerimi aileyle görüşerek yeniden düzenlerim.",score:0,feedbackText:"Aile diyaloğu güçlü. Hem veri hem ilişki yönetimi birlikte çalışır."}] },
  { cat:"efficiency-analysis", d:1, s:"Yapay zeka en verimli araçları listeledi. Ama bazı araçlar ekibinizin kullanmasını bilmediği şeyler.", t:"Araç verimliliği kullanım becerisine bağlıdır.", options:[{text:"Önce ekibi mevcut araçlarda ustalaştırır, sonra yeni araç eklerim.",score:100,feedbackText:"Yeterli kullanım + doğru araç = gerçek verimlilik."},{text:"En verimli araçlara hemen geçerim, ekip öğrenir.",score:0,feedbackText:"Öğrenme süreci verimliliği geçici düşürür. Hazırlık planlamak daha iyi."},{text:"Ekibin bildiği araçlarla kalırım, değişim gerekmez.",score:0,feedbackText:"Mevcut araçlar bazen yeterli ama daha verimli seçenekleri keşfetmek değerli."}] },
  { cat:"efficiency-analysis", d:2, s:"Yapay zeka görev tamamlama hızınızı ölçtü. Hızlı olduğunuz ama hata oranınızın yüksek olduğunu gösteriyor.", t:"Hız ve kalite birlikte değerlendirilmeli. Sadece biri yeterli değil.", options:[{text:"Bazı adımlarda kasıtlı yavaşlayarak doğrulama ekler, hız-kalite dengesini optimize ederim.",score:100,feedbackText:"Verimlilik hız değil, kaliteli sonuç üretmektir."},{text:"Hız doğru ölçüm, hatalar düzeltilebilir.",score:-100,feedbackText:"Hata düzeltme yeniden çalışma maliyetidir. Önce doğru daha verimli."},{text:"Yavaşlarsam daha az iş bitiririm, hız önce.",score:0,feedbackText:"Hız tek boyut. Hatalı iş yapıp düzeltmek aslında daha uzun sürer."}] },
  { cat:"efficiency-analysis", d:3, s:"Yapay zeka müşteri hizmetleri sürecinizi analiz etti. Belirli adımları kısaltmak toplam süreyi yüzde yirmi azaltıyor ama müşteri memnuniyeti düşebilir.", t:"Süre optimizasyonu her zaman değer optimizasyonu değildir.", options:[{text:"Kısaltma önerilerini müşteri memnuniyetiyle etkisini ölçerim; ikisi birlikte kabul edilebilir seviyede kalıyorsa uygularım.",score:100,feedbackText:"Tam maliyet analizi süreyi ve memnuniyeti birlikte ele alır."},{text:"Yüzde yirmi süre tasarrufu büyük, uygularım.",score:-100,feedbackText:"Memnuniyet kaybı uzun vadede daha büyük maliyet. Önce test."}  ,{text:"Müşteri memnuniyeti önce, süre ikincil.",score:0,feedbackText:"Memnuniyet önemli ama süre kaybı da ciddi. Denge ve test gerekli."}] },
  { cat:"efficiency-analysis", d:1, s:"Yapay zeka günlük işlerinizi yüzde kırk oranında otomatize edebileceğini söylüyor. Ne hissediyorsunuz?", t:"Otomasyon fırsatı enerjinizi daha değerli işlere yönlendirme şansıdır.", options:[{text:"Hangi yüzde kırklık işin otomatize edileceğini inceler ve kalan zamana daha stratejik görevler planlarım.",score:100,feedbackText:"Otomasyon zamanı boşaltır, siz bu zamanı doldurursunuz. Proaktif planlama şart."},{text:"Yüzde kırk azalırsa değersiz hissederim.",score:-100,feedbackText:"Değer ürettiğiniz şey değişiyor — kaybolmuyor. Strateji gerekiyor."},{text:"Merak ederim, ne tür işler otomatize olacak.",score:0,feedbackText:"Merak iyi başlangıç. Bir sonraki adım planlamak."}] },
]

console.log('Total:', ALL.length, 'questions')
for (let i = 0; i < ALL.length; i += 20) {
  const batch = ALL.slice(i, i + 20)
  await insert(batch)
}
