const TOKEN = 'sbp_f314cf27b5b2a01eea48048a7b1c015cc9cf4b42'
const API = 'https://api.supabase.com/v1/projects/amhfxaqolholacanqyas/database/query'

function esc(s) { return s.replace(/'/g, "''") }

async function insert(batch) {
  const values = batch.map(q => {
    const opts = JSON.stringify(q.options).replace(/'/g, "''")
    return `('tr','${q.cat}','${esc(q.s)}','${esc(q.t)}','${opts}'::jsonb,${q.d},'claude',true)`
  }).join(',')
  const sql = `INSERT INTO questions (locale,category,scenario_text,mindset_tip,options,difficulty,generated_by,is_active) VALUES ${values};`
  const r = await fetch(API, {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${TOKEN}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query: sql })
  })
  const d = await r.json()
  if (d.message) { console.error('ERR:', d.message); return false }
  console.log('OK:', batch.length, 'inserted')
  return true
}

const ALL = [
  // knowledge-research (10)
  { cat:"knowledge-research", d:1, s:"Yapay zeka ile hızlı literatür taraması yapıyorsunuz ama hangi kaynakların gerçekten atıfta bulunulduğunu kontrol etmiyorsunuz.", t:"Yapay zeka kaynak üretebilir ama var olmayan kaynaklar da üretebilir.", options:[{text:"Her atıfı birincil kaynak veritabanında doğrularım.",score:100,feedbackText:"Hayali kaynak riski araştırma güvenilirliğini tehdit eder. Doğrulama zorunlu."},{text:"Yapay zeka güvenilir kaynaklardan öğrendi, atıflar doğru olmalı.",score:-100,feedbackText:"Hallüsinasyon gerçek. Atıflar doğrulanmadan kullanılamaz."},{text:"Önemli atıfları kontrol ederim, hepsini değil.",score:0,feedbackText:"Seçici doğrulama hiçbirinden iyi ama tüm atıfları doğrulamak şart."}] },
  { cat:"knowledge-research", d:2, s:"Yapay zeka araştırmanız için mükemmel bir özet oluşturdu. Kaynak notlarınız yerine bunu kullanmayı düşünüyorsunuz.", t:"Özet anlayışı kolaylaştırır ama birincil kaynak derinliğinin yerini tutmaz.", options:[{text:"Özeti giriş olarak kullanır, kritik argümanlar için birincil kaynakları okurım.",score:100,feedbackText:"Özet pusula, birincil kaynak harita. İkisi birlikte güçlü."},{text:"Özet yeterliyse birincil kaynağa gerek yok.",score:-100,feedbackText:"Özetin neyi kaçırdığını özetten anlayamazsınız."},{text:"Özetle başlar, ihtiyaç duyarsam kaynağa giderim.",score:0,feedbackText:"Mantıklı yaklaşım ama ihtiyacı önceden belirlemek daha verimli."}] },
  { cat:"knowledge-research", d:1, s:"Yapay zeka araştırma sorunuzu yeniden çerçeveliyor ve daha geniş bir konuya genişletiyor. Bu sizi heyecanlandırıyor.", t:"Kapsam genişlemesi hem fırsat hem tuzak olabilir. Odak değerlidir.", options:[{text:"Genişletilmiş çerçeveyi değerlendiririm ama asıl araştırma sorumuza odaklanmayı koruyarak ilgili kısımları dahil ederim.",score:100,feedbackText:"Genişleme ile odak arasında denge araştırma kalitesini korur."},{text:"Yeni çerçeve daha ilginç, oraya geçerim.",score:0,feedbackText:"İlgi iyi ama sık konu değiştirme sonuçsuz araştırmaya yol açar."},{text:"Yapay zekanın önerisini reddeder, kendi soruma kalırım.",score:0,feedbackText:"Yeni perspektifi görmezden gelmek de fırsatı kaçırmak. Değerlendirin."}] },
  { cat:"knowledge-research", d:2, s:"Yapay zeka araştırmanızda bir pazar büyüklüğünü kesin rakamla verdi. Kaynağı yok.", t:"Kayıpsız rakamlar araştırmada güvenilmezdir. Kaynak şart.", options:[{text:"Rakamın kaynağını sorar, bulunamazsa bağımsız araştırmayla doğrularım.",score:100,feedbackText:"Kayıpsız istatistik araştırma kalitesini düşürür. Doğrulama şart."},{text:"Yaklaşık olarak kullanırım, kesin değil zaten.",score:0,feedbackText:"Yaklaşık kullanım güveni azaltır. Doğrulanmış kaynak daha güçlü."},{text:"Mantıklı bir rakam, olduğu gibi kullanırım.",score:-100,feedbackText:"Mantıklı görünüm kaynak yerine geçmez. Hallüsinasyon mantıklı görünebilir."}] },
  { cat:"knowledge-research", d:3, s:"Yapay zeka rakip analizi yapmanıza yardımcı oldu. Ama veri kesim tarihinden sonra piyasada büyük değişimler oldu.", t:"Yapay zeka bilgi kesim tarihi güncel durumu yansıtmayabilir.", options:[{text:"Analizin bilgi kesim tarihini kontrol eder ve kesim sonrası gelişmeleri başka kaynaklarla tamamlarım.",score:100,feedbackText:"Bilgi kesim tarihini anlamak yapay zeka okuryazarlığının kritik parçası."},{text:"Analiz sağlam, küçük değişimler önemli değil.",score:-100,feedbackText:"Piyasa dinamikleri hızlı değişir. Eski analiz yanıltıcı karar verilmesine yol açabilir."},{text:"Yeni veriyle analizi tamamen yenilerim.",score:0,feedbackText:"Yenileme iyi ama eski analizi tamamen atmak yerine tamamlamak daha verimli."}] },
  { cat:"knowledge-research", d:2, s:"Yapay zeka ile tartışmalı bir konuyu araştırıyorsunuz. Yapay zeka dengeli görünüyor ama tek bir bakış açısını daha çok vurguluyor.", t:"Görünür denge gerçek denge olmayabilir. Ağırlık dağılımı önemli.", options:[{text:"Daha az vurgulanan bakış açısını derinleştirip kendi sentezimi oluştururum.",score:100,feedbackText:"Aktif denge arayışı araştırma tarafsızlığını güçlendirir."},{text:"Dengeli görünüyorsa tarafsız demektir.",score:-100,feedbackText:"Ton dengeli olsa da vurgulama tartışmalı konularda ayrım yaratabilir."},{text:"Her bakış açısını ayrı araçlarla araştırırım.",score:0,feedbackText:"Çoklu kaynak iyi ama her araç da benzer eğilimler taşıyabilir."}] },
  { cat:"knowledge-research", d:1, s:"Yapay zeka bir konuda size hızlı bir özet verdi. Siz bunu sunumunuzda kaynak göstermeden kullandınız.", t:"Yapay zeka çıktısı kaynak gerektiren iddialar içerir.", options:[{text:"Sunumda yapay zeka yardımıyla hazırlandığını ve temel iddiaların doğrulanmış kaynaklara dayandığını belirtirim.",score:100,feedbackText:"Şeffaflık + kaynak bütünlüğü. Akademik ve profesyonel standart."},{text:"Sunum kişisel, kaynak gerekmez.",score:0,feedbackText:"Kişisel sunumda bile güvenilmez iddia aktarmak itibar sorununa yol açabilir."},{text:"Yapay zeka özetledi, onun kaynakları kendi içinde var.",score:-100,feedbackText:"Yapay zeka kendi kaynaklarını doğrulanabilir biçimde sunmaz. Doğrulama sizin sorumluluğunuz."}] },
  { cat:"knowledge-research", d:3, s:"Yapay zeka akademik makale taslağı oluşturdu. Bunu kendi makaleniz olarak sunmayı düşünüyorsunuz.", t:"Yapay zeka destekli yazarlık şeffaflık ve kurumsal politika gerektirir.", options:[{text:"Kurumun yapay zeka politikasını öğrenir, yaptığım katkıyı açıkça belirtir ve yapay zekayı araştırma aracı olarak değil, yazım asistanı olarak kullanımımı bildiririm.",score:100,feedbackText:"Şeffaflık hem etik hem kurumsal gereklilik."},{text:"Yapay zeka sadece taslak çıkardı, ekleme ve düzenlemeler benimdir.",score:0,feedbackText:"Katkı gerçek ama şeffaflık eksik. Politikayı kontrol etmek şart."},{text:"Herkes kullanıyor, kurumun haberi bile yok.",score:-100,feedbackText:"Yaygınlık politikayı değiştirmez. Etik ihlal ciddiye alınır."}] },
  { cat:"knowledge-research", d:2, s:"Yapay zeka tarihsel bir olayı anlatıyor ama bazı detaylar tarihçilerin yazılarıyla örtüşmüyor.", t:"Tarihsel konularda yapay zeka hataları yaygın. Birincil ve uzman kaynaklar şart.", options:[{text:"Örtüşmeyen kısımları işaretler ve tarih kaynaklarıyla doğrularım.",score:100,feedbackText:"Kritik doğrulama tarihsel araştırmanın temelidir."},{text:"Küçük farklar olabilir, genel doğruysa kullanırım.",score:0,feedbackText:"Tarihsel detay önemlidir. Küçük hata büyük yorumu etkiler."},{text:"Yapay zeka birçok kaynaktan öğrendi, tarihçiden daha güvenilir.",score:-100,feedbackText:"Bu yanlış. Tarihçiler kaynaklara eleştirel yaklaşır. Yapay zeka bunu garanti etmez."}] },
  { cat:"knowledge-research", d:1, s:"Yapay zeka ile patent araştırması yapıyorsunuz. Sonuçlar kapsamlı görünüyor ama bazı kritik patentler eksik.", t:"Yapay zeka patent araştırmasında kapsamlı değildir. Resmi veritabanlar şart.", options:[{text:"Resmi patent veritabanlarında (EPO, USPTO) bağımsız tarama yaparım.",score:100,feedbackText:"Yasal sonuçları olan araştırma resmi kaynak gerektirir."},{text:"Yapay zeka kapsamlı tarama yaptı, yeterli.",score:-100,feedbackText:"Patent araştırmasında eksik sonuç ciddi hukuki risk taşır. Resmi kaynak şart."},{text:"Patent avukatına başvururum.",score:0,feedbackText:"Uzman değerli ama önce resmi veritabanında ön tarama hem hızlı hem maliyetsiz."}] },

  // privacy-ethics (10)
  { cat:"privacy-ethics", d:1, s:"Yapay zeka kişisel verilerinizi işleyerek öneri sunuyor. Gizlilik politikasını hiç okumadınız.", t:"Gizlilik politikası sıkıcı ama verilerinizin nereye gittiğini bilmek hakkınız.", options:[{text:"En azından hangi verilerin toplandığını ve paylaşıldığını öğrenirim.",score:100,feedbackText:"Bilinçli kullanım gizlilik okuryazarlığından başlar."},{text:"Popüler uygulama, güvenilirdir.",score:0,feedbackText:"Popülerlik gizlilik garantisi değildir."},{text:"Politikayı okumak zaman kaybı, herkes kabul ediyor.",score:-100,feedbackText:"Herkesin yapması doğru olduğu anlamına gelmez. Verileriniz değerlidir."}] },
  { cat:"privacy-ethics", d:2, s:"Yapay zeka çalışanlarınız hakkında veri topluyor ve performans tahminleri üretiyor. Çalışanlar haberdar değil.", t:"Çalışan verisi şeffaflık ve onay gerektirir. Gizli izleme güven zedeler.", options:[{text:"Çalışanlara hangi verilerin toplandığını ve nasıl kullanıldığını bildiririm.",score:100,feedbackText:"Şeffaflık çalışan güveni ve hukuki uyum için şart."},{text:"Performans yönetimi için veriye ihtiyaç var, bildirim gerekmez.",score:-100,feedbackText:"Gizli veri toplama pek çok ülkede yasadışı ve her koşulda etik dışı."},{text:"Sonuçları paylaşmam, sadece iç kullanım.",score:0,feedbackText:"Kullanım amacı şeffaflık yükümlülüğünü ortadan kaldırmaz."}] },
  { cat:"privacy-ethics", d:3, s:"Yapay zeka destekli bir hizmet kullanıcı verilerini üçüncü taraflarla paylaşıyor. Kullanıcılar bunu bilmiyor.", t:"Veri paylaşımı onaysız yapıldığında kullanıcı güvenini ve yasal yükümlülüğü ihlal eder.", options:[{text:"Hizmet koşullarını güncelleyerek kullanıcıları bilgilendiririm ve açık onay talep ederim.",score:100,feedbackText:"Şeffaflık ve onay veri etiğinin temelidir."},{text:"Paylaşım hizmetin işleyişi için gerekli, anlaşılır bir şey.",score:-100,feedbackText:"Gerekli olması şeffaflık yükümlülüğünü ortadan kaldırmaz."},{text:"Kullanıcılar gizlilik politikasını okumalı.",score:0,feedbackText:"Gizlilik politikası okunabilir olmalı ama aktif bildirim de şart."}] },
  { cat:"privacy-ethics", d:2, s:"Yapay zeka müşterilerinizin psikolojik profilini çıkararak satış stratejisi önerileri sunuyor. Müşteriler bundan haberdar değil.", t:"Psikolojik profilleme güçlü ama onaysız yapıldığında sömürücü olabilir.", options:[{text:"Bu tekniği yalnızca kullanıcıların bilgisiyle ve kabul edilebilir sınırlar içinde kullanırım.",score:100,feedbackText:"Güç ve sorumluluk birlikte gelir. Şeffaflık şart."},{text:"Herkes müşteri psikolojisini analiz ediyor, rekabetçi şart.",score:-100,feedbackText:"Yaygınlık etik gerekçe değil. Onaysız psikolojik profilleme güven eroziyonu."},{text:"Anonim verilerle çalışırsam sorun olmaz.",score:0,feedbackText:"Anonim profilleme de etik sorular taşır. Şeffaflık ve sınır önemli."}] },
  { cat:"privacy-ethics", d:1, s:"Yapay zekaya çalışma arkadaşınızla yaşadığınız çatışmayı anlatırken onun kişisel bilgilerini de paylaştınız.", t:"Üçüncü taraf bilgilerini yapay zeka sistemlerine girmek o kişinin mahremiyetini etkiler.", options:[{text:"Bundan sonra başkalarının kimliğini açıklamadan genel durumu anlatırım.",score:100,feedbackText:"Başkasının mahremiyetine saygı dijital ortamda da geçerli."},{text:"Yapay zekaya söylediğim saklı kalır.",score:-100,feedbackText:"Yapay zeka girişleri her zaman gizli kalmaz. Politikaya bakın."},{text:"Arkadaşımın adını değil sadece durumu anlattım.",score:0,feedbackText:"Tanımlanabilir detay isimden daha az önemli değil. Dikkatli olmak şart."}] },
  { cat:"privacy-ethics", d:2, s:"Yapay zeka uygulaması çocuğunuzun öğrenme davranışını analiz ediyor. Çocuk veri işleme nüanslarını anlayamıyor.", t:"Çocuk verisi en yüksek koruma standardını gerektirir.", options:[{text:"Ebeveyn olarak neyin toplandığını inceler, riskleri değerlendirir ve çocuğun bütünlüğünü koruyacak sınırlar koyarım.",score:100,feedbackText:"Ebeveyn denetimi çocuk verisi güvenliği için şart."},{text:"Eğitim uygulaması güvenilirdir, risk yok.",score:0,feedbackText:"Güvenilirlik veri politikasının okunmasının yerini tutmaz."},{text:"Çocuklar için tüm veri toplayan uygulamaları kullanmam.",score:0,feedbackText:"Aşırı ihtiyat olabilir ama çocuk verisinde katı standart makul."}] },
  { cat:"privacy-ethics", d:3, s:"Yapay zeka rakip şirketin çalışanlarının LinkedIn verilerini analiz ediyor ve kişisel kariyer tahminleri yapıyor.", t:"Kamuya açık veri her kullanım amacına açık değildir.", options:[{text:"Bu analizi etik açıdan değerlendiririm ve kişisel kariyer profillemesinden kaçınırım.",score:100,feedbackText:"Kamuya açık veri ile etik kullanım arasındaki sınır önemli."},{text:"Kamuya açık veri, kullanmak serbesttir.",score:-100,feedbackText:"Kamuya açıklık her amaç için kullanım izni değildir. Amaç ve bağlam önemli."},{text:"Rakip analizi meşru, kişisel profilleme de bunun parçası.",score:0,feedbackText:"Şirket analizi ile bireyleri profilleme farklı kategoriler."}] },
  { cat:"privacy-ethics", d:1, s:"Müşterilerinize yapay zeka ile kişiselleştirilmiş içerik sunuyorsunuz ama kullanıcılar bunun yapay zeka olduğunu bilmiyor.", t:"Yapay zeka destekli kişiselleştirme şeffaflık gerektirir.", options:[{text:"Kişiselleştirmenin yapay zeka tarafından yapıldığını açıkça belirtirim.",score:100,feedbackText:"Şeffaflık uzun vadede güveni artırır."},{text:"Kişiselleştirme kullanıcı deneyimini artırıyor, bilmek şart değil.",score:0,feedbackText:"Deneyim iyi ama bilgilendirilme hakkı da var."},{text:"Herkes yapay zeka kullanıyor, belirtmeye gerek yok.",score:-100,feedbackText:"Yaygınlık şeffaflık yükümlülüğünü ortadan kaldırmaz."}] },
  { cat:"privacy-ethics", d:2, s:"Yapay zeka sisteminiz kullanıcıların duygusal durumunu analiz ederek içerik sunuyor. Kullanıcılar haberdar değil.", t:"Duygusal profilleme en kırılgan veri kategorilerinden biri.", options:[{text:"Duygusal analiz yapıldığını açıkça bildiririm ve kullanıcılara vazgeçme hakkı sunarım.",score:100,feedbackText:"Hassas veri analizi özellikle şeffaflık ve onay gerektirir."},{text:"Daha iyi deneyim için yapıyoruz, iyi niyet var.",score:-100,feedbackText:"İyi niyet etik yükümlülüğü ortadan kaldırmaz."},{text:"Anonim tutulan duygusal analiz sorun değil.",score:0,feedbackText:"Anonim bile olsa duygusal profilleme bildirim gerektirebilir."}] },
  { cat:"privacy-ethics", d:3, s:"Yapay zeka destekli sistemin yanlış kararı bir kişinin hayatını olumsuz etkiledi. Sistem kararı şeffaf değil.", t:"Etkili yapay zeka kararları açıklanabilir ve itiraz edilebilir olmalıdır.", options:[{text:"Karar gerekçesini açıklar, itiraz süreci tanımlar ve sistemi bu açıdan geliştiririm.",score:100,feedbackText:"Açıklanabilirlik ve itiraz hakkı AI etiğinin temel unsurları."},{text:"Sistem kararı verdi, insan müdahale etmemeli.",score:-100,feedbackText:"İnsanı etkileyen karar hesap verebilir olmalı. Otomatik karar yeterli değil."},{text:"Zarara tazminat öderim ama sistemi değiştirmem.",score:0,feedbackText:"Tazminat başlangıç ama sistemi değiştirmemek aynı hatanın tekrarlanmasına yol açar."}] },

  // prompt-architecture (10)
  { cat:"prompt-architecture", d:1, s:"Yapay zekaya çok genel bir soru sordunuz ve yanıt çok genel geldi. Ne yaparsınız?", t:"Girdi kalitesi çıktı kalitesini doğrudan belirler.", options:[{text:"Bağlam, hedef ve kısıt ekleyerek soruyu yeniden çerçevelerim.",score:100,feedbackText:"Spesifik prompt spesifik çıktı üretir."},{text:"Yapay zeka iyi değil, başka araç denerim.",score:0,feedbackText:"Araç değiştirmeden önce promtu iyileştirmek daha hızlı çözüm."},{text:"Genel yanıt yeterli, devam ederim.",score:-100,feedbackText:"Genel yanıt gerçek ihtiyacınızı karşılamıyor olabilir. Spesifikleştirme değer katar."}] },
  { cat:"prompt-architecture", d:2, s:"Uzun ve karmaşık bir görev için yapay zekaya tek bir büyük prompt yazdınız. Yanıt dağınık.", t:"Karmaşık görevler adımlara bölündüğünde daha iyi işlenir.", options:[{text:"Görevi alt adımlara böler, her adım için ayrı ve odaklı prompt yazarım.",score:100,feedbackText:"Adım adım decomposition karmaşık görevlerde kaliteyi artırır."},{text:"Daha uzun prompt yazarsam daha iyi sonuç alırım.",score:-100,feedbackText:"Uzunluk netliğin garantisi değil. Yapı önemli."},{text:"Yanıtı ben düzenlerim, prompt önemli değil.",score:0,feedbackText:"Düzenleme iyi ama iyi prompt düzenleme yükünü azaltır."}] },
  { cat:"prompt-architecture", d:1, s:"Yapay zeka her seferinde farklı format ve uzunlukta yanıt veriyor. Tutarlılık ihtiyacınız var.", t:"Format talimatları tutarlı çıktı sağlar.", options:[{text:"Her promta format talimatları eklerim: uzunluk, yapı, ton ve çıktı biçimi.",score:100,feedbackText:"Format talimatı tutarlı çıktı garantisi."},{text:"Yanıtları aldıktan sonra düzenlerim.",score:0,feedbackText:"Düzenleme mümkün ama önceden belirtmek zaman kazandırır."},{text:"Farklı format sorun değil, içerik önemli.",score:0,feedbackText:"İçerik önemli ama format iş akışını etkiler."}] },
  { cat:"prompt-architecture", d:2, s:"Yapay zeka yanıtları bazen istediğinizden çok daha uzun. Zaman kaybediyorsunuz.", t:"Uzunluk talimatı net verildiğinde çok daha etkili.", options:[{text:"Promta maksimum kelime veya paragraf sayısı eklerim ve kısa tutmasını açıkça isterim.",score:100,feedbackText:"Uzunluk talimatı gereksiz içerik üretimini önler."},{text:"Sonradan keserim, sorun değil.",score:0,feedbackText:"Kesmek mümkün ama prompt ile önlemek daha verimli."},{text:"Yapay zeka her zaman çok konuşuyor, değiştirmek zor.",score:-100,feedbackText:"Uzunluğu kontrol etmek mümkün. Talimat işe yarar."}] },
  { cat:"prompt-architecture", d:3, s:"Karmaşık bir analiz görevi için chain-of-thought prompting kullanmayı duydunuz ama nasıl yapılacağını bilmiyorsunuz.", t:"Yapay zekadan adım adım düşünmesini istemek karmaşık analizde kaliteyi artırır.", options:[{text:"Adım adım düşün veya önce durumu analiz et, sonra sonuçlara geç gibi talimatlar eklerim.",score:100,feedbackText:"Açık düşünme talimatı analiz kalitesini artırır."},{text:"Sadece sonucu isterim, süreci önemli değil.",score:0,feedbackText:"Süreç hem kalite hem doğrulama için değerli."},{text:"Chain-of-thought gelişmiş, benim seviyem için değil.",score:-100,feedbackText:"Basit versiyonu herkesin kullanabileceği bir teknik. Denemek değer."}] },
  { cat:"prompt-architecture", d:2, s:"Aynı görevi farklı araçlara verdiniz. Sonuçlar çok farklı. Hangi aracın doğru yanıt verdiğini bilmiyorsunuz.", t:"Farklı modeller farklı güçler taşır. Doğrulama ikincil kaynak gerektirir.", options:[{text:"En kritik kısımları birincil kaynaklarla doğrularım ve farklı yanıtların nedenini analiz ederim.",score:100,feedbackText:"Model farkını anlamak araç okuryazarlığı."},{text:"En popüler araç doğrudur.",score:-100,feedbackText:"Popülerlik doğruluğun göstergesi değil."},{text:"İkisini birleştiririm, ortası doğru olur.",score:0,feedbackText:"Ortalama doğruluğu garanti etmez. Doğrulama şart."}] },
  { cat:"prompt-architecture", d:1, s:"Yapay zekaya rol vermek (sen bir uzman gibi davran) istediğinizi biliyor musunuz? Hiç denediniz mi?", t:"Rol talimatı yapay zekanın yanıt çerçevesini ve derinliğini etkiler.", options:[{text:"Belirli bir göreve uygun rol tanımı denerim ve farkı gözlemlerim.",score:100,feedbackText:"Rol talimatı güçlü bir prompt tekniği. Denemek öğretir."},{text:"Yapay zeka zaten elinden gelenin en iyisini yapıyor.",score:0,feedbackText:"Evet ama rol talimatı belirli alanlarda performansı artırabilir."},{text:"Rol vermek yapay amaçlı, kullanmam.",score:-100,feedbackText:"Rol vermek bağlamı zenginleştirir. Araştırmaya değer bir teknik."}] },
  { cat:"prompt-architecture", d:2, s:"Yapay zekadan kod yazdırıyorsunuz ama açıklama olmadan sadece kod geliyor. Neden çalıştığını anlamak istiyorsunuz.", t:"Çıktı formatı prompt talimatıyla şekillenir.", options:[{text:"Kodu yaz ve her adımı açıkla veya yorum satırları ekle talimatı eklerim.",score:100,feedbackText:"Format talimatı net çıktı üretir."},{text:"Kodu çalıştırırım, anlayamadığım yerleri ayrıca sorarım.",score:0,feedbackText:"İkinci soru da işe yarar ama tek promptta istemek daha verimli."},{text:"Kod yazdırmak için yapay zekayı kullanmam, öğrenme değeri kalmaz.",score:0,feedbackText:"Açıklama talep etmek hem kod alır hem öğrenir."}] },
  { cat:"prompt-architecture", d:3, s:"Yapay zekayla uzun bir sohbet yürütüyorsunuz ve sohbetin başındaki bağlamı unutuyor gibi görünüyor.", t:"Bağlam penceresi sınırlı. Uzun sohbetlerde özet ve hatırlatma gerekir.", options:[{text:"Uzun sohbetlerde periyodik özet ekler ve kritik bağlamı her yeni soruda hatırlatırım.",score:100,feedbackText:"Bağlam yönetimi uzun çalışmalarda kritik."},{text:"Unutuyorsa daha akıllı araç kullanırım.",score:0,feedbackText:"Tüm araçların bağlam penceresi var. Yönetimi öğrenmek araç değiştirmekten daha verimli."},{text:"Sıfırdan yeni sohbet başlatırım.",score:0,feedbackText:"Yeni sohbet temiz başlangıç sağlar ama önceki bağlamı kaybeder."}] },
  { cat:"prompt-architecture", d:2, s:"Yapay zekadan pazarlama metni istiyorsunuz ama sonuç kurumsal ve soğuk çıkıyor.", t:"Ton talimatı + örnek vererek tutarlı marka sesi elde edilir.", options:[{text:"Ton, hedef kitle ve marka sesine dair talimat ekler, istediğim sesten iki örnek gösteririm.",score:100,feedbackText:"Örnek ile talimat kombinasyonu ton ayarını hızlandırır."},{text:"Sonucu kendim düzeltirim, yapay zeka yaratıcılıkta iyi değil.",score:0,feedbackText:"Düzenleme mümkün ama doğru promptla zaman kazanılır."},{text:"Yapay zeka kurumsal üretir, bu kadarı.",score:-100,feedbackText:"Ton talimatıyla kısıtlamak mümkün. Önyargılı kabul fırsatı kaçırır."}] },

  // quality-measurement (10)
  { cat:"quality-measurement", d:1, s:"Yapay zeka çıktı kalitesini ölçmek için bir sistem kurmak istiyorsunuz ama nereden başlayacağınızı bilmiyorsunuz.", t:"Kalite ölçümü önce neyin kaliteli olduğunu tanımlamayı gerektirir.", options:[{text:"Hangi çıktı özelliklerinin önemli olduğunu belirler ve her biri için ölçülebilir kriter oluştururum.",score:100,feedbackText:"Kriter tanımı olmadan ölçüm anlamsız."},{text:"Kalite özneldir, ölçemem.",score:-100,feedbackText:"Tamamen subjektif değil. Özellikler belirlenip ölçülebilir."},{text:"Müşteri memnuniyetini ölçerim, yeter.",score:0,feedbackText:"Müşteri memnuniyeti iyi ama geç geri bildirim. Süreç ölçümü daha erken düzeltme sağlar."}] },
  { cat:"quality-measurement", d:2, s:"Yapay zeka içerik üretim hızı arttı ama editörler kalite sorunları bildiriyor. İkisi arasında denge nasıl kurulur?", t:"Hız ve kalite zıt değil ama dengeyi ölçmeden yönetmek zor.", options:[{text:"Hem hız hem kalite metriklerini ölçer, ikisindeki eğilimi birlikte analiz ederim.",score:100,feedbackText:"İkisini birlikte ölçmek denge noktasını ortaya çıkarır."},{text:"Editörler memnunsa hız önemli değil.",score:0,feedbackText:"Editör memnuniyeti kalite vekilini geç ve öznelleştirir."},{text:"Hız önce, kalite sonradan düzeltilir.",score:-100,feedbackText:"Düzeltme maliyeti hız kazanımını aşabilir."}] },
  { cat:"quality-measurement", d:1, s:"Yapay zekanın ürettiği içerikleri hiç değerlendirmeden yayınlıyorsunuz ve kalite sorunları çıkıyor.", t:"Yayın öncesi insan incelemesi kalite güvencesinin temelidir.", options:[{text:"Yayın öncesi kontrol listesi oluştururum: doğruluk, uyum ve ton. Her içeriği bu listeyle değerlendiririm.",score:100,feedbackText:"Sistematik kontrol kalite güvencesini standartlaştırır."},{text:"Hataları yayın sonrası düzeltirim.",score:-100,feedbackText:"Hata yayılır, düzeltmek itibar zararını geri almaz."},{text:"Zaman kısıtlı, her içeriği kontrol edemem.",score:0,feedbackText:"Hepsini değil ama rastgele örnekleme bile kalite sinyali sağlar."}] },
  { cat:"quality-measurement", d:2, s:"Yapay zeka müşteri hizmetleri yanıtlarını kalite puanıyla değerlendiriyor ama puanlar tutarsız.", t:"Yapay zeka kalite ölçümü kalibrasyona ihtiyaç duyar.", options:[{text:"İnsan değerlendirmesiyle yapay zeka puanlarını karşılaştırır, tutarsız kalıpları analiz edip kalibrasyon yaparım.",score:100,feedbackText:"Kalibrasyon ölçüm güvenilirliğinin temelidir."},{text:"Yapay zeka puanları yeterli, insan değerlendirmesine gerek yok.",score:-100,feedbackText:"Kalibrasyon olmadan sistemin ne ölçtüğünü bilmezsiniz."},{text:"Puanları tamamen insan değerlendirmesiyle değiştiririm.",score:0,feedbackText:"İnsan değerlendirmesi değerli ama ölçeklenemez. Hibrit kalibrasyon daha verimli."}] },
  { cat:"quality-measurement", d:3, s:"Yapay zeka kalite metrikleriniz hedeflere ulaştığınızı gösteriyor ama müşteri şikayetleri artıyor.", t:"Metrik ve gerçek deneyim arasındaki fark ölçümün yanlış şeyi ölçtüğüne işaret eder.", options:[{text:"Metriklerin neyi ölçtüğünü ve müşteri şikayetleriyle neden uyuşmadığını analiz eder, ölçüm sistemimi gözden geçiririm.",score:100,feedbackText:"Metrik-gerçeklik uyuşmazlığı ölçüm revizyonu sinyali."},{text:"Metrikler iyi, müşteriler aşırı talepkâr.",score:-100,feedbackText:"Müşteri şikayeti gerçek bir sinyaldir. Görmezden gelmek riski artırır."},{text:"Müşteri şikayetleri için ayrı bir ekip kurarım.",score:0,feedbackText:"Şikayet ekibi iyi ama kök neden ölçüm sisteminde. İkisini birlikte çözmek şart."}] },
  { cat:"quality-measurement", d:2, s:"Yapay zeka kod kalitesini analiz ediyor ve bir geliştiriciyi sürekli düşük puanlıyor. Geliştirici deneyimli ama puanlar düşük.", t:"Otomatik kalite ölçümleri bağlamı kaçırabilir.", options:[{text:"Geliştiricinin işinin bağlamını ve ölçüm sisteminin zayıf noktalarını incelerim.",score:100,feedbackText:"Ölçüm bağlamı yakalayamayabilir. İnsan değerlendirmesi şart."},{text:"Veri düşük gösteriyorsa performans sorunu var.",score:-100,feedbackText:"Ölçüm sistemi kusurlu olabilir. Bağlam analizi önce."},{text:"Geliştiriciyle konuşarak durumu anlarım.",score:0,feedbackText:"Diyalog iyi ama ölçüm sistemini de paralel gözden geçirin."}] },
  { cat:"quality-measurement", d:1, s:"Yapay zeka destekli ürününüzün kalitesini kullanıcı geri bildirimi olmadan ölçmeye çalışıyorsunuz.", t:"Teknik metrikler kullanıcı deneyimini tam yansıtmaz.", options:[{text:"Teknik metriklerin yanı sıra kullanıcı anketleri ve kullanım davranış verisi eklerim.",score:100,feedbackText:"Çok katmanlı ölçüm gerçek kalite resmini verir."},{text:"Teknik metrikler objektif, yeterli.",score:0,feedbackText:"Teknik metrikler önemli ama kullanıcı değeri farklı boyut."},{text:"Geri bildirim almak için zaman yok, daha sonra.",score:-100,feedbackText:"Erken geri bildirim geç düzeltmeden ucuzdur."}] },
  { cat:"quality-measurement", d:2, s:"Yapay zeka çeviri kalitesini otomatik ölçüyor ama dil uzmanları sonuçların yetersiz olduğunu söylüyor.", t:"Otomatik çeviri metrikleri insan algısını tam yakalayamaz.", options:[{text:"Otomatik metrikleri uzman değerlendirmesiyle kalibre eder ve metriklerin ne ölçtüğünü netleştiririm.",score:100,feedbackText:"Kalibrasyon ölçüm sistemini gerçeğe bağlar."},{text:"Uzmanlar eski yönteme alışık, zamanla kabul eder.",score:-100,feedbackText:"Uzman geri bildirimi değerlidir. Görmezden gelmek kalite sorununu büyütür."},{text:"Her iki değerlendirme türünü birlikte kullanırım.",score:0,feedbackText:"İyi yaklaşım ama ikisi arasındaki uyumsuzluğu da analiz etmek şart."}] },
  { cat:"quality-measurement", d:3, s:"Yapay zeka destekli ürün geliştirme sürecinizde kalite kontrol adımı yok. Ürün büyük ölçekte yayınlanıyor.", t:"Ölçek öncesi kalite güvencesi, ölçek sonrası düzeltmeden çok daha ucuz.", options:[{text:"Yayın öncesi minimum bir kalite kontrol noktası tanımlar, bu noktada otomatik ve manuel denetimleri uygularım.",score:100,feedbackText:"Yayın kapısı kalite güvencesinin temelidir."},{text:"Hatalar çıkarsa düzeltme yaparız.",score:-100,feedbackText:"Büyük ölçekte hata düzeltme maliyet ve itibar riski taşır."},{text:"Yapay zeka kalite garantisi sağlıyor, ayrıca kontrol gerekmez.",score:0,feedbackText:"Yapay zeka kaliteyi garanti etmez. Denetim şart."}] },
  { cat:"quality-measurement", d:1, s:"Yapay zeka özetleme kalitesini ölçmek için ROUGE skoru kullanıyorsunuz ama özetler anlamlı gelmiyor.", t:"Teknik metrik anlamlılığı ölçmez. Farklı metrikler farklı kalite boyutlarını yakalar.", options:[{text:"ROUGE'u tamamlayan anlamlılık ve okunabilirlik değerlendirmeleri eklerim.",score:100,feedbackText:"Tek metrik yeterli değil. Çok boyutlu ölçüm şart."},{text:"ROUGE standart metrik, güvenilirdir.",score:0,feedbackText:"Standart olmak her durumda yeterli olmak demek değil."},{text:"Metrikleri bırakır, sadece insan değerlendirmesi kullanırım.",score:0,feedbackText:"İnsan değerlendirmesi değerli ama ölçeklenemiyor. Hibrit daha verimli."}] },

  // workflow-integration (10)
  { cat:"workflow-integration", d:1, s:"Yapay zekayı iş akışınıza entegre etmek istiyorsunuz ama mevcut araçlarla uyumluluğu belli değil.", t:"Entegrasyon planı mevcut sistemleri anlamaktan başlar.", options:[{text:"Mevcut araçları ve veri akışlarını haritalandırır, sonra yapay zekanın en iyi nereye oturacağını değerlendiririm.",score:100,feedbackText:"Sistemi anlamak entegrasyonun başlangıç noktası."},{text:"Hemen entegre ederim, sorun olursa çözerim.",score:-100,feedbackText:"Planlamadan entegrasyon iş akışı kesintilerine yol açar."},{text:"Uyumsuz olursa eski araçları değiştiririm.",score:0,feedbackText:"Değiştirme seçenek olabilir ama mevcut değeri anlayarak karar vermek daha sağlıklı."}] },
  { cat:"workflow-integration", d:2, s:"Yapay zeka iş akışınıza entegre edildi ama kullanım oranı beklentinin altında. Ekip eskisi gibi çalışıyor.", t:"Teknik entegrasyon ile benimseme farklı şeyler.", options:[{text:"Ekibin neden kullanmadığını sorar, engelleri giderir ve gerçek bir iş sürecine entegre eder.",score:100,feedbackText:"Benimseme kullanıcı sorunlarını anlamakla başlar."},{text:"Sistemin kurulduğunu duyurduk, ekip kullanmalı.",score:-100,feedbackText:"Duyuru benimseme değil. Kolaylaştırıcı destek şart."},{text:"Kullanım oranı zamanla artar.",score:0,feedbackText:"Bazen doğru ama aktif destek süreci hızlandırır."}] },
  { cat:"workflow-integration", d:1, s:"Yapay zeka bir görev için çok güçlü ama diğer iş akışı adımlarıyla entegrasyonu çok karmaşık.", t:"Entegrasyon maliyeti gerçek maliyetin parçası.", options:[{text:"Entegrasyon maliyetini kazanımla karşılaştırır, net fayda varsa entegrasyon planı yaparım.",score:100,feedbackText:"Tam maliyet analizi akıllıca yatırım kararının temelidir."},{text:"Araç güçlü, entegrasyon sorunlarına katlanırım.",score:0,feedbackText:"Katlanma sürdürülebilir değil. Plan veya daha iyi entegrasyon arayın."},{text:"Bu araç yerine daha kolay entegre olan başka aracı kullanırım.",score:0,feedbackText:"Geçerli seçim ama performansı da karşılaştırmak şart."}] },
  { cat:"workflow-integration", d:2, s:"Yapay zeka entegrasyonunuz çalışıyor ama bir API değişikliği tüm sistemi bozdu.", t:"Bağımlılıklar kırılganlık yaratır. Dayanıklı entegrasyon plan gerektirir.", options:[{text:"API değişikliklerine karşı bildirim sistemi kurar ve kritik bağımlılıklar için yedek plan yaparım.",score:100,feedbackText:"Değişim yönetimi entegrasyonun sürekli parçasıdır."},{text:"Her API değişiminde ekibi bilgilendiririm.",score:0,feedbackText:"Bildirim iyi ama otomatik alarm daha güvenilir."},{text:"Üçüncü taraf API bağımlılığını kaldırır kendi sisteme geçerim.",score:0,feedbackText:"Kontrol avantajı var ama inşa maliyeti yüksek. Bağımlılık yönetimi daha pratik."}] },
  { cat:"workflow-integration", d:3, s:"Yapay zeka iş akışınızı otomatize etti ama bir hata olduğunda kim sorunlu adımı bulacağını kimse bilmiyor.", t:"Otomasyon görünürlük kaybı yaratır. Hata izleme sistematik olmalı.", options:[{text:"Her otomatik adım için loglama ve hata uyarı sistemi kurarım ve sorumlulukları netleştiririm.",score:100,feedbackText:"Görünürlük ve sorumluluk birlikte otomasyonu güvenilir kılar."},{text:"Hata çıkınca araştırırız.",score:-100,feedbackText:"Reaktif yaklaşım sorunu büyütür. Proaktif izleme şart."},{text:"Kullanıcılar hata bildirdiğinde müdahale ederim.",score:0,feedbackText:"Kullanıcı bildirimi geç sinyaldir. Sistem izleme daha erken yakalar."}] },
  { cat:"workflow-integration", d:2, s:"Yapay zeka iş akışınızda birden fazla araç birbirine bağlanıyor. Veri tutarsızlıkları oluşuyor.", t:"Entegre sistemlerde veri senkronizasyonu kritik.", options:[{text:"Veri tutarsızlığının nerede kaynaklandığını tespit eder, tek doğru kaynak tanımlar ve senkronizasyon kuralları koyarım.",score:100,feedbackText:"Tek doğru kaynak tutarsızlığın temel çözümüdür."},{text:"Araçlar aynı veriyi kullanıyor, tutarsızlık beklenmez.",score:-100,feedbackText:"Entegrasyon ne kadar iyi olursa olsun tutarsızlık riski gerçektir."},{text:"Her araçtaki veriyi manuel kontrol ederim.",score:0,feedbackText:"Manuel kontrol başlangıç için iyi ama otomasyon şart."}] },
  { cat:"workflow-integration", d:1, s:"Yapay zekayı iş akışınıza entegre etmek istiyorsunuz ama hangi adımdan başlayacağınızı bilmiyorsunuz.", t:"Başlangıç noktası en acı veren veya en tekrarlayan adımdır.", options:[{text:"İş akışımdaki en tekrarlayan ve en zaman alan adımı belirler, oradan başlarım.",score:100,feedbackText:"Yüksek etkili başlangıç momentum sağlar."},{text:"En karmaşık adımdan başlarım, başarırsam her şeye hazırım.",score:0,feedbackText:"Karmaşık başlangıç başarısızlık riskini artırır. Kolay kazanç ivme verir."},{text:"Tüm iş akışını birden dönüştürürüm.",score:-100,feedbackText:"Toplam dönüşüm riski yüksek. Adım adım daha sürdürülebilir."}] },
  { cat:"workflow-integration", d:2, s:"Yapay zeka e-posta, takvim ve proje yönetim araçlarınızla entegre. Ama bazen çift bildirim ve kayıt oluşuyor.", t:"Entegrasyon fazlalığı yönetim yükü yaratır.", options:[{text:"Hangi sistemin hangi görevi yöneteceğini netleştirir ve çakışan entegrasyonları devre dışı bırakırım.",score:100,feedbackText:"Net sorumluluk dağılımı entegrasyon gürültüsünü azaltır."},{text:"Birden fazla bildirim daha iyi, kaçırmam.",score:0,feedbackText:"Fazla bildirim dikkat yorgunluğu yaratır ve önemlileri gizleyebilir."},{text:"Entegrasyonları azaltırım, basit tutarım.",score:0,feedbackText:"Sadelik değerli ama hangi entegrasyonun değerli olduğunu belirleyerek seçici olun."}] },
  { cat:"workflow-integration", d:3, s:"Yapay zeka iş akışı entegrasyonu beklenmedik performans sorunlarına neden oldu. Üretim sistemleri yavaşladı.", t:"Entegrasyon testinin yük ve performans senaryolarını kapsaması şart.", options:[{text:"Problemi izole eder, yük testleri yapar ve yapay zeka entegrasyonunu performans etkisini minimize edecek şekilde yeniden yapılandırırım.",score:100,feedbackText:"Sistematik tanı ve optimizasyon mühendislik sorumluluğu."},{text:"Sunucuları yükseltirim, performans sorun değil.",score:0,feedbackText:"Yükseltme çözüm olabilir ama kök nedeni çözmeden sürdürülebilir değil."},{text:"Entegrasyonu kaldırırım, sorun çözüldü.",score:0,feedbackText:"Geçici çözüm. Kök neden analizi ve optimize entegrasyon daha iyi."}] },
  { cat:"workflow-integration", d:1, s:"Yapay zeka iş akışınızı iyileştirdi ama ekibinizdeki bazı kişiler yeni süreci öğrenmekte zorlanıyor.", t:"İş akışı değişimi eğitim ve destek gerektirir.", options:[{text:"Zorlananlara birebir destek sağlar, süreç dokümantasyonu ve kısa eğitim materyalleri hazırlarım.",score:100,feedbackText:"Benimseme desteği entegrasyonun kritik son adımıdır."},{text:"Yeni süreç daha iyi, zamanla öğrenirler.",score:0,feedbackText:"Kendi kendine öğrenme yavaş ve hatalı olabilir. Aktif destek fark yaratır."},{text:"Zorlananlara eski yöntemi kullanma izni veririm.",score:-100,feedbackText:"İki paralel süreç tutarsızlık ve kafa karışıklığı yaratır."}] },
]

console.log('Total:', ALL.length, 'questions')
for (let i = 0; i < ALL.length; i += 20) {
  const batch = ALL.slice(i, i + 20)
  await insert(batch)
}
